import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomUUID} from 'node:crypto';
import {owner,db,member,creator,denied} from './closing-test-fixture.mjs';
import {executeTask,parseCommand} from './task-adapter.ts';
import {formCommand} from './form-command-adapter.mjs';
import {createTaskHandler} from './task-http.ts';
const read=(f,a)=>db.transaction(async c=>(await c.query('SELECT candidate_operations.read_dish_cycle($1,$2,$3,$4) r',[a.subject,a.membershipId,'fictional-a',f.cycle.recordId])).rows[0].r);
async function fixture(){const people=await Promise.all([member([],'Dishwasher'),member([],'Dishwasher'),member([],'Dishwasher')]);const date=(await owner.query("SELECT to_char(coalesce(max(business_date),DATE '2031-01-01')+1,'YYYY-MM-DD') d FROM candidate_operations.dish_cycles")).rows[0].d;const cycle=await executeTask(db,creator,'fictional-a',{requestId:randomUUID(),locationId:'fictional-a',action:'task.dish-cycle',input:{amOwnerId:people[0].membershipId,pmOwnerIds:people.slice(1).map(p=>p.membershipId),businessDate:date,title:'Form projection test',detail:'Fictional conditions',due:date+'T23:00:00-04:00'}});return {people,date,cycle};}
test('form adapter retains ready answers and drops ignored checker answers without mutating input',()=>{const record={id:randomUUID(),revision:3},input={step:'ready',answers:[0,1],note:'Observed'};assert.deepEqual(formCommand('close.transition',input,record,'fictional-a').input,input);const confirm={...input,step:'confirm'};const c=formCommand('close.transition',confirm,record,'fictional-a');assert.equal(c.input.answers,undefined);assert.deepEqual(confirm.answers,[0,1]);assert.equal(c.expectedRevision,3);assert.equal(c.recordId,record.id);assert.doesNotThrow(()=>parseCommand(c,'fictional-a'));});
test('form adapter preserves correction attention and ordinary task input',()=>{const x=formCommand('close.transition',{step:'fix',answers:[],note:'Condition',managerAttention:'serious'},null,'fictional-a');assert.equal(x.input.managerAttention,'serious');const y=formCommand('task.transition',{step:'ready',note:'Done'},null,'fictional-a');assert.deepEqual(y.input,{step:'ready',note:'Done'});assert.notEqual(x.requestId,y.requestId);});
test('Dishwasher form records expose personal checkout only and manager gets all three',async()=>{const f=await fixture();const full=await read(f,creator);assert.equal(full.records.length,3);for(const [i,p] of f.people.entries()){const r=await read(f,p);assert.equal(r.records.length,1);assert.equal(r.records[0].ownerId,p.membershipId);assert.equal(r.records[0].data.dishCheckout.shift,i===0?'AM':'PM');assert.equal(r.records[0].data.history.length,1);}await assert.rejects(read(f,await member()),e=>e.code==='42501');});
test('AM receipt projection retains acceptance without leaking incoming work detail',async()=>{const f=await fixture(),am=(await read(f,f.people[0])).records[0];const child=await executeTask(db,f.people[0],'fictional-a',formCommand('task.dish-pass',{incomingId:f.people[1].membershipId,due:f.date+'T23:00:00-04:00',note:'Private incoming work detail'},am,'fictional-a'));const pm=await read(f,f.people[1]);assert.equal(pm.records.length,2);assert.equal(pm.records.find(r=>r.id===child.recordId).data.dishHandoff.acceptedBy,'');await executeTask(db,f.people[1],'fictional-a',formCommand('task.transition',{step:'accept',note:'Accepted'}, {id:child.recordId,revision:child.revision},'fictional-a'));const out=await read(f,f.people[0]);assert.equal(out.records.length,1);assert.equal(out.records[0].data.dishHandoffReceiptView,true);assert.equal(out.records[0].data.dishHandoffAcceptances[0].acceptedBy,f.people[1].membershipId);assert.equal((await read(f,f.people[2])).records.length,1);});
test('shift read permits owner and scoped manager, denying unrelated and mismatched identity',async()=>{const p=await member(),other=await member(),id=randomUUID();await owner.query("INSERT INTO candidate_operations.shift_references(id,restaurant_id,member_id,department,position,starts_at,ends_at,revision,published,checkout_profile) VALUES($1,'fictional-a',$2,'BOH','Cook','2031-01-01T12:00Z','2031-01-01T20:00Z',1,true,'ordinary')",[id,p.membershipId]);const get=a=>db.transaction(async c=>(await c.query('SELECT candidate_operations.read_shift($1,$2,$3,$4) r',[a.subject,a.membershipId,'fictional-a',id])).rows[0].r);assert.equal((await get(p)).ownerId,p.membershipId);assert.equal((await get(creator)).revision,1);await assert.rejects(get(other),e=>e.code==='42501');await assert.rejects(get({...p,subject:other.subject}),e=>e.code==='42501');const sessionId=randomUUID();await owner.query("INSERT INTO candidate_identity.sessions(id,subject,expires_at) VALUES($1,$2,clock_timestamp()+interval '1 hour')",[sessionId,p.subject]);const handler=createTaskHandler(db,async()=>({subject:p.subject,sessionId}));const response=await handler(new Request('https://candidate.invalid/api/operations/fictional-a/shifts/'+id,{headers:{Authorization:'Bearer fixture'}}));assert.equal(response.status,200);assert.equal((await response.json()).kind,'shift');});
test('runtime cannot bypass scoped summary projection or edit checkout records',async()=>{await assert.rejects(db.transaction(c=>c.query('SELECT candidate_operations.read_dish_cycle_summary($1,$2,$3,$4)',['manager',creator.membershipId,'fictional-a',randomUUID()])),e=>e.code==='42501');await assert.rejects(db.transaction(c=>c.query('SELECT * FROM candidate_operations.dish_handoffs',[])),e=>e.code==='42501');});
