import React,{useState,useEffect} from 'react';import {createRoot} from 'react-dom/client';import {RecordDetail} from '../../app/team/workspace-forms';import {DishCheckoutCycles} from '../../app/team/dish-checkouts';import {FollowDetail} from '../../app/team/followthrough-forms';import '../../app/team/workspace.css';import {formCommand} from './form-command-adapter.mjs';
import {IndexedDbQueueStorage,OfflineTaskQueue} from './offline-task-queue.mjs';import {employeeReady,retainReady,submissionMessage} from './checkout-queue-client.mjs';
const prefix='jmax-fictional-checkout-v1:',scope='fictional-a';
const saved=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(prefix+key))??fallback;}catch{return fallback;}};
const remember=(key,value)=>localStorage.setItem(prefix+key,JSON.stringify(value));
const queue=new OfflineTaskQueue(new IndexedDbQueueStorage('jmax-fictional-checkout-queue'),{maxAgeMs:86400000});
function Preview(){
 const [fixture,setFixture]=useState(null),[actor,setActor]=useState(()=>saved('actor','checkout-manager')),[mode,setMode]=useState(()=>saved('mode','close')),[record,setRecord]=useState(null),[records,setRecords]=useState([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[shiftId,setShiftId]=useState(''),[shift,setShift]=useState(null),[offline,setOffline]=useState(()=>saved('offline',false)),[entries,setEntries]=useState([]),[shell,setShell]=useState(false),[cached,setCached]=useState(false);
 const subject=fixture?.members.find(m=>m.actor===actor)?.subject,cacheKey=fixture&&'records:'+fixture.closeId+':'+actor+':'+mode,cycleKey=fixture&&'cycle:'+fixture.closeId,selectedKey=cacheKey+':selected';
 function connectionState(value){setOffline(value);remember('offline',value);}
 async function call(path,command){const tokenResponse=await fetch('/fixture-token?actor='+actor,{cache:'no-store'});if(!tokenResponse.ok)throw Object.assign(Error('Sign in required'),{status:401});const {token}=await tokenResponse.json();const response=await fetch('/api/operations/'+scope+path,{method:command?'POST':'GET',headers:{Authorization:'Bearer '+token,...(command?{'Content-Type':'application/json'}:{})},...(command?{body:JSON.stringify(command)}:{})});return {status:response.status,body:await response.json()};}
 async function read(path){const r=await call(path);if(r.status!==200)throw Object.assign(Error(r.body.error?.code??'Request failed'),{status:r.status});return r.body;}
 async function loadRecords(selected=saved(selectedKey,null)){if(mode==='close'){const r=await read('/closes/'+fixture.closeId);return {records:[r],record:r};}const id=saved(cycleKey,null);if(!id)return {records:[],record:null};const result=await read('/dish-cycles/'+id);return {records:result.records,record:result.records.find(r=>r.id===selected)??null};}
 function showSnapshot(snapshot,selected=saved(selectedKey,null)){setRecords(snapshot.records);setRecord(mode==='close'?snapshot.records[0]??null:snapshot.records.find(r=>r.id===selected)??null);}
 async function refresh(selected=record?.id){const result=await loadRecords(selected);setRecords(result.records);setRecord(result.record);remember(cacheKey,{records:result.records,loadedAt:new Date().toISOString()});setCached(false);if(shiftId)setShift(await read('/shifts/'+shiftId));setEntries(await queue.list(subject,scope));}
 function openRecord(r){setRecord(r);remember(selectedKey,r.id);}
 useEffect(()=>{(async()=>{try{const response=await fetch('/checkout-fixture',{cache:'no-store'});if(!response.ok)throw Error('Fixture unavailable');const raw=await response.json();const {sessions,...data}=raw;data.members=data.members.map(m=>({...m,subject:sessions[m.actor].subject}));remember('fixture',data);setFixture(data);}catch{const prior=saved('fixture',null);if(prior){setFixture(prior);connectionState(true);}else setMessage('Connect once to load fictional assignments.');}})();if('serviceWorker' in navigator)navigator.serviceWorker.register('/checkout-offline-worker.js').then(()=>navigator.serviceWorker.ready).then(()=>setShell(true)).catch(()=>setMessage('Offline page cache unavailable; keep this page open.'));},[]);
 useEffect(()=>{if(!fixture||!subject)return;let active=true;setRecord(null);setRecords([]);setShift(null);setEntries([]);setCached(false);(async()=>{const snapshot=saved(cacheKey,null);try{if(offline){if(snapshot&&active){showSnapshot(snapshot);setCached(true);}else if(active)setMessage('Connect to load this employee’s assignments.');}else{const result=await loadRecords();if(active){setRecords(result.records);setRecord(result.record);remember(cacheKey,{records:result.records,loadedAt:new Date().toISOString()});}}}catch(e){if(active){if(!e.status&&snapshot){showSnapshot(snapshot);setCached(true);connectionState(true);setMessage('Connection unavailable. Previously loaded assignment shown.');}else{setMessage(e.message);if(e.status)localStorage.removeItem(prefix+cacheKey);}}}if(active)setEntries(await queue.list(subject,scope));})();return()=>{active=false;};},[fixture,actor,mode,offline]);
 useEffect(()=>{if(fixture&&shiftId&&!offline)read('/shifts/'+shiftId).then(setShift).catch(e=>setMessage(e.message));},[shiftId,actor,offline]);
 async function send(action,input,r){if(busy)throw Error('Submission in progress');setBusy(true);try{const command=formCommand(action,input,r,scope);if(employeeReady(action,input)){await retainReady(queue,subject,scope,command);if(!offline)await queue.flush(subject,scope,c=>call('/commands',c));const current=await queue.list(subject,scope);setEntries(current);const entry=current.find(e=>e.requestId===command.requestId);setMessage(submissionMessage(entry));if(entry.status==='applied')await refresh(r.id);else if(entry.status==='pending')connectionState(true);return entry.status==='applied'?entry.result:{pending:true,requestId:entry.requestId};}if(offline)throw Error('Incoming acceptance, assignments, manager checks and shift release require a connection.');const result=await call('/commands',command);if(result.status!==200)throw Error(result.body.error?.code??'Request failed');if(action==='task.dish-cycle')remember(cycleKey,result.body.recordId);await refresh(action==='task.dish-pass'?result.body.recordId:r?.id);setMessage('Saved '+action+'.');return result.body;}finally{setBusy(false);}}
 async function reconnect(){setBusy(true);try{await queue.flush(subject,scope,c=>call('/commands',c));setEntries(await queue.list(subject,scope));await refresh(record?.id);connectionState(false);setMessage('Connected. Review the saved submission status below.');}catch(e){if(e.status===403){localStorage.removeItem(prefix+cacheKey);setRecords([]);setRecord(null);setCached(false);}connectionState(true);setEntries(await queue.list(subject,scope));setMessage(e.status===403?'Access changed. Saved submissions remain blocked; contact the manager.':'Connection or login required. Saved submissions remain on this device.');}finally{setBusy(false);}}
 if(!fixture)return <p>{message||'Loading fictional checkout…'}</p>;const w={location:{id:scope,name:'Fictional restaurant',timezone:'America/New_York',revision:1},me:fixture.members.find(m=>m.actor===actor),members:fixture.members,records:[...records,fixture.standard,...(shift?[shift]:[])]};
 return <main className="shared-workspace" style={{maxWidth:1040,margin:'24px auto',padding:24,fontFamily:'system-ui'}}><h1>Closing and Dishwasher · PostgreSQL preview</h1><p>Fictional local checks using unchanged Companion forms. Business date: {fixture.date}. Employee readiness can be saved for later submission.</p><label>Preview employee <select aria-label="Preview employee" disabled={busy} value={actor} onChange={e=>{setShiftId('');remember('actor',e.target.value);setActor(e.target.value);}}>{fixture.members.map(m=><option key={m.actor} value={m.actor}>{m.name}</option>)}</select></label><label> Workflow <select aria-label="Workflow" value={mode} disabled={busy} onChange={e=>{remember('mode',e.target.value);setMode(e.target.value);}}><option value="close">Closing assignment</option><option value="dish">Dishwasher checkout</option></select></label>
 <p>{shell?'Offline page ready.':'Preparing offline page…'}</p><label><input type="checkbox" checked={offline} disabled={busy} onChange={e=>connectionState(e.target.checked)}/>Delay submissions (preview)</label> <button disabled={busy||!subject} onClick={reconnect}>Reconnect and submit saved work</button><p>{offline?'Pending mode: employee readiness only. Manager checks require a connection.':'Connected mode.'}</p>{cached&&<p>Previously loaded assignment. Current permissions and work will be checked on reconnect.</p>}<p role="status">{message}</p>
 {mode==='dish'&&<DishCheckoutCycles w={w} send={send} busy={busy} onOpen={openRecord}/>}<section><h2>{record?.data.title??(mode==='close'?'Closing assignment':'Select checkout work')}</h2>{record&&(mode==='close'?<RecordDetail key={record.id+':'+record.revision+':'+actor} record={record} w={w} send={send} onError={setMessage} onOpen={openRecord} onWeek={()=>{}} onGuides={()=>{}} onAskWeek={()=>{}} now={new Date().toISOString()}/>:<FollowDetail key={record.id+':'+record.revision+':'+actor} record={record} w={w} send={send} onError={setMessage} onOpen={openRecord}/>)}</section>
 <section><h2>Saved submissions for this employee</h2><ul>{entries.map(e=><li key={e.requestId}>{e.status} · {e.command.input.note} · attempts {e.attempts}{e.error?' · '+e.error:''}</li>)}</ul><p>A pending submission does not pass an independent check or release a shift. Review blocked or changed work with the manager.</p></section>
 {actor==='checkout-manager'&&<section><h2>Separate manager checkout</h2><label>Shift to inspect <select aria-label="Shift to inspect" value={shiftId} disabled={offline||busy} onChange={e=>setShiftId(e.target.value)}><option value="">Choose shift</option>{fixture.shifts.map(s=><option key={s.id} value={s.id}>{fixture.members.find(m=>m.id===s.ownerId).name}</option>)}</select></label>{shift&&<><p>Release recorded: {shift.data.releasedAt?'Yes':'No'}</p><form onSubmit={async e=>{e.preventDefault();try{await send('shift.release',{note:new FormData(e.currentTarget).get('note')},shift);}catch(error){setMessage(error.message);}}}><label>Checkout confirmation note <textarea name="note" required/></label><button disabled={offline||busy||!!shift.data.releasedAt}>Confirm selected shift checkout</button></form></>}</section>}</main>;
}
createRoot(document.getElementById('root')).render(<Preview/>);
