import React,{useState,useEffect} from 'react';import {createRoot} from 'react-dom/client';import {RecordDetail} from '../../app/team/workspace-forms';import {DishCheckoutCycles} from '../../app/team/dish-checkouts';import {FollowDetail} from '../../app/team/followthrough-forms';import '../../app/team/workspace.css';import {formCommand} from './form-command-adapter.mjs';
function Preview(){const [fixture,setFixture]=useState(null),[actor,setActor]=useState('checkout-manager'),[mode,setMode]=useState('close'),[record,setRecord]=useState(null),[records,setRecords]=useState([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[shiftId,setShiftId]=useState(''),[shift,setShift]=useState(null);
async function call(path,command){const {token}=await (await fetch('/fixture-token?actor='+actor)).json();const response=await fetch('/api/operations/fictional-a'+path,{method:command?'POST':'GET',headers:{Authorization:'Bearer '+token,...(command?{'Content-Type':'application/json'}:{})},...(command?{body:JSON.stringify(command)}:{})});const body=await response.json();if(!response.ok)throw Error(body.error?.code??'Request failed');return body;}
async function refresh(selected=record?.id){if(!fixture)return;if(mode==='close'){const r=await call('/closes/'+fixture.closeId);setRecords([r]);setRecord(r);}else{const id=sessionStorage.getItem('checkout-preview-cycle');if(id){const result=await call('/dish-cycles/'+id);setRecords(result.records);setRecord(result.records.find(r=>r.id===selected)??null);}else{setRecords([]);setRecord(null);}}if(shiftId)setShift(await call('/shifts/'+shiftId));}
useEffect(()=>{fetch('/checkout-fixture').then(r=>r.json()).then(setFixture);},[]);useEffect(()=>{setRecord(null);setRecords([]);setMessage('');setShift(null);refresh().catch(e=>setMessage(e.message));},[fixture,actor,mode,shiftId]);
async function send(action,input,r){if(busy)throw Error('Submission in progress');setBusy(true);try{const result=await call('/commands',formCommand(action,input,r,'fictional-a'));if(action==='task.dish-cycle')sessionStorage.setItem('checkout-preview-cycle',result.recordId);await refresh(action==='task.dish-pass'?result.recordId:r?.id);setMessage('Saved '+action+'.');return result;}finally{setBusy(false);}}
if(!fixture)return <p>Loading fictional checkout…</p>;const w={location:{id:'fictional-a',name:'Fictional restaurant',timezone:'America/New_York',revision:1},me:fixture.members.find(m=>m.actor===actor),members:fixture.members,records:[...records,fixture.standard,...(shift?[shift]:[])]};
return <main className="shared-workspace" style={{maxWidth:1040,margin:'24px auto',padding:24,fontFamily:'system-ui'}}><h1>Closing and Dishwasher · PostgreSQL preview</h1><p>Fictional local checks using unchanged Companion forms. Business date: {fixture.date}. This preview requires a connection.</p><label>Preview employee <select aria-label="Preview employee" disabled={busy} value={actor} onChange={e=>{setShiftId('');setActor(e.target.value);}}>{fixture.members.map(m=><option key={m.actor} value={m.actor}>{m.name}</option>)}</select></label><label> Workflow <select aria-label="Workflow" value={mode} disabled={busy} onChange={e=>setMode(e.target.value)}><option value="close">Closing assignment</option><option value="dish">Dishwasher checkout</option></select></label><p role="status">{message}</p>
{mode==='dish'&&<DishCheckoutCycles w={w} send={send} busy={busy} onOpen={setRecord}/>}<section><h2>{record?.data.title??(mode==='close'?'Closing assignment':'Select checkout work')}</h2>{record&&(mode==='close'?<RecordDetail key={record.id+':'+record.revision+':'+actor} record={record} w={w} send={send} onError={setMessage} onOpen={setRecord} onWeek={()=>{}} onGuides={()=>{}} onAskWeek={()=>{}} now={new Date().toISOString()}/>:<FollowDetail key={record.id+':'+record.revision+':'+actor} record={record} w={w} send={send} onError={setMessage} onOpen={setRecord}/>)}</section>
{actor==='checkout-manager'&&<section><h2>Separate manager checkout</h2><label>Shift to inspect <select aria-label="Shift to inspect" value={shiftId} onChange={e=>setShiftId(e.target.value)}><option value="">Choose shift</option>{fixture.shifts.map(s=><option key={s.id} value={s.id}>{fixture.members.find(m=>m.id===s.ownerId).name}</option>)}</select></label>{shift&&<><p>Release recorded: {shift.data.releasedAt?'Yes':'No'}</p><form onSubmit={async e=>{e.preventDefault();try{await send('shift.release',{note:new FormData(e.currentTarget).get('note')},shift);}catch(error){setMessage(error.message);}}}><label>Checkout confirmation note <textarea name="note" required/></label><button disabled={busy||!!shift.data.releasedAt}>Confirm selected shift checkout</button></form></>}</section>}</main>;}
createRoot(document.getElementById('root')).render(<Preview/>);
