import React,{useEffect,useState} from 'react';import {createRoot} from 'react-dom/client';
import {FollowForm,FollowDetail} from '../../app/team/followthrough-forms';import '../../app/team/workspace.css';
function Preview(){const [fixture,setFixture]=useState(null),[actor,setActor]=useState('night-closing'),[record,setRecord]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
async function call(path,command){const {token}=await (await fetch('/fixture-token?actor='+actor)).json();const response=await fetch('/api/operations/fictional-a'+path,{method:command?'POST':'GET',headers:{Authorization:'Bearer '+token,...(command?{'Content-Type':'application/json'}:{})},...(command?{body:JSON.stringify(command)}:{})});const body=await response.json();if(!response.ok)throw Error(body.error?.code??'Request failed');return body;}
async function refresh(){const id=sessionStorage.getItem('overnight-preview-issue');if(id)setRecord(await call('/overnight/'+id));}
useEffect(()=>{fetch('/overnight-fixture').then(r=>r.json()).then(setFixture);},[]);useEffect(()=>{setRecord(null);refresh().catch(e=>setMessage(e.message));},[actor]);
async function send(action,input,r){setBusy(true);try{const result=await call('/commands',{requestId:crypto.randomUUID(),locationId:'fictional-a',action,input,...(r?{recordId:r.id,expectedRevision:r.revision}:{})});sessionStorage.setItem('overnight-preview-issue',result.recordId);await refresh();setMessage('Saved '+action+'.');}finally{setBusy(false);}}
if(!fixture)return <p>Loading fictional preview…</p>;const w={location:{id:'fictional-a',name:'Fictional restaurant',timezone:'America/New_York',revision:1},members:fixture.members,me:fixture.members.find(m=>m.actor===actor),records:[...fixture.leadership,...(record?[record]:[])]};
return <main className="shared-workspace" style={{maxWidth:1000,margin:'24px auto',padding:24}}><h1>Overnight manager handoff · PostgreSQL preview</h1><p>Fictional local test using unchanged Companion forms. Safe deferral, acceptance and resolution are separate steps.</p><label>Preview manager <select aria-label="Preview manager" disabled={busy} value={actor} onChange={e=>setActor(e.target.value)}>{fixture.members.map(m=><option key={m.actor} value={m.actor}>{m.name}</option>)}</select></label><p role="status">{message}</p><section><h2>New overnight issue</h2><FollowForm key={actor} kind="handoff" w={w} send={send} onError={setMessage}/></section><section><h2>Saved issue</h2>{record&&<FollowDetail key={record.id+':'+record.revision+':'+actor} record={record} w={w} send={send} onError={setMessage}/>}</section></main>;}
createRoot(document.getElementById('root')).render(<Preview/>);
