import assert from 'node:assert/strict';import {test} from 'node:test';import {randomUUID} from 'node:crypto';
import {db,owner,member,denied,fixture as shiftFixture,run as assign,creator} from './closing-test-fixture.mjs';import {executeTask} from './task-adapter.ts';
async function fixture(){const outgoing=await member(['tasks.manage']),incoming=await member(['tasks.manage']),replacement=await member(['tasks.manage']),a=randomUUID(),b=randomUUID(),c=randomUUID();for(const [id,person,start,end] of [[a,outgoing,'2030-01-01T16:00:00Z','2030-01-02T00:00:00Z'],[b,incoming,'2030-01-02T12:00:00Z','2030-01-02T20:00:00Z'],[c,replacement,'2030-01-03T12:00:00Z','2030-01-03T20:00:00Z']])await owner.query("INSERT INTO candidate_operations.leadership_references(id,member_id,restaurant_id,department,starts_at,ends_at) VALUES($1,$2,'fictional-a','BOH',$3,$4)",[id,person.membershipId,start,end]);return {outgoing,incoming,replacement,a,b,c,command:{requestId:randomUUID(),locationId:'fictional-a',action:'handoff.create',input:{title:'Fictional overnight issue',detail:'Condition, temporary action, next step',outgoingLeadershipId:a,incomingLeadershipId:b,incomingId:incoming.membershipId,priority:'routine',safeToDefer:true}}};}
const create=f=>executeTask(db,f.outgoing,'fictional-a',f.command);
const read=(f,r,actor=f.outgoing)=>db.transaction(async c=>(await c.query('SELECT candidate_operations.read_overnight($1,$2,$3,$4) result',[actor.subject,actor.membershipId,'fictional-a',r.recordId])).rows[0].result);
const command=(r,step,extra={})=>({requestId:randomUUID(),locationId:'fictional-a',action:'handoff.transition',recordId:r.recordId,expectedRevision:r.revision,input:{step,note:'Observed condition and next step',...extra}});
const send=(actor,r,step,extra={})=>executeTask(db,actor,'fictional-a',command(r,step,extra));
test('safe deferral retains closing owner until opening accepts; acceptance is distinct from resolution',async()=>{const f=await fixture(),r=await create(f);assert.equal((await read(f,r)).ownerId,f.outgoing.membershipId);const a=await send(f.incoming,r,'accept');assert.equal((await read(f,a)).data.phase,'accepted');assert.equal((await read(f,a)).ownerId,f.incoming.membershipId);const done=await send(f.incoming,a,'resolve');assert.equal((await read(f,done)).data.phase,'resolved');});
test('unsafe deferral and opening assignment preceding closing are denied',async()=>{const f=await fixture();await assert.rejects(executeTask(db,f.outgoing,'fictional-a',{...f.command,input:{...f.command.input,safeToDefer:false}}),denied(400));await owner.query("UPDATE candidate_operations.leadership_references SET starts_at='2030-01-01T20:00:00Z' WHERE id=$1",[f.b]);await assert.rejects(create(f),denied(403));});
test('dispute retains current owner; clarified offer can be accepted, and cancellation is separate',async()=>{const f=await fixture(),r=await create(f),d=await send(f.incoming,r,'dispute');assert.equal((await read(f,d)).ownerId,f.outgoing.membershipId);const offer=await send(f.outgoing,d,'offer',{incomingId:f.incoming.membershipId,incomingLeadershipId:f.b});await send(f.incoming,offer,'accept');const g=await fixture(),x=await create(g);assert.equal((await read(g,await send(g.outgoing,x,'cancel'))).data.phase,'cancelled');});
test('only named receiver can accept and only responsible manager resolves or cancels',async()=>{const f=await fixture(),r=await create(f);await assert.rejects(send(f.replacement,r,'accept'),denied(403));await assert.rejects(send(f.incoming,r,'cancel'),denied(403));const a=await send(f.incoming,r,'accept');await assert.rejects(send(f.outgoing,a,'resolve'),denied(403));await assert.rejects(read(f,a,await member()),e=>e.code==='42501');});
test('urgent deferral requires scoped escalation authority and queues owner notification',async()=>{const f=await fixture();f.command.input.priority='urgent';await assert.rejects(create(f),denied(403));const escalation=await member(['operations.escalation']);const r=await create(f);assert.ok((await owner.query('SELECT recipient_id FROM candidate_operations.overnight_outbox WHERE issue_id=$1',[r.recordId])).rows.some(x=>x.recipient_id===escalation.membershipId));await owner.query('UPDATE candidate_identity.membership_capabilities SET active=false WHERE membership_id=$1',[escalation.membershipId]);});
test('recovery retains recovering manager responsibility until replacement accepts without resolving condition',async()=>{const f=await fixture(),r=await create(f),a=await send(f.incoming,r,'accept'),recovered=await send(f.outgoing,a,'recover',{incomingId:f.replacement.membershipId,incomingLeadershipId:f.c});const record=await read(f,recovered);assert.equal(record.ownerId,f.outgoing.membershipId);assert.equal(record.data.phase,'offered');assert.equal(record.data.detail,f.command.input.detail);await send(f.replacement,recovered,'accept');});
test('recovered offer requires unexpired leadership and revoked manager cannot replay',async()=>{const f=await fixture(),r=await create(f),a=await send(f.incoming,r,'accept');await owner.query("UPDATE candidate_operations.leadership_references SET starts_at='2020-01-01',ends_at='2020-01-02' WHERE id=$1",[f.c]);await assert.rejects(send(f.outgoing,a,'recover',{incomingId:f.replacement.membershipId,incomingLeadershipId:f.c}),denied(409));await owner.query('UPDATE candidate_identity.membership_capabilities SET active=false WHERE membership_id=$1',[f.outgoing.membershipId]);await assert.rejects(create(f),denied(403));});
test('concurrent retries are stable and stale versions or changed payloads conflict',async()=>{const f=await fixture(),[a,b]=await Promise.all([create(f),create(f)]);assert.equal(a.recordId,b.recordId);assert.equal(Number(a.replayed)+Number(b.replayed),1);await assert.rejects(executeTask(db,f.outgoing,'fictional-a',{...f.command,input:{...f.command.input,title:'Changed'}}),denied(409));await send(f.incoming,a,'accept');await assert.rejects(send(f.incoming,a,'accept'),denied(409));});
test('notification failure rolls back issue state, event and receipt',async()=>{const f=await fixture(),r=await create(f),c=command(r,'accept');await owner.query(`CREATE FUNCTION candidate_operations.test_night_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'night failure'; END; $$; CREATE TRIGGER test_night_failure BEFORE INSERT ON candidate_operations.overnight_outbox FOR EACH ROW EXECUTE FUNCTION candidate_operations.test_night_failure();`);try{await assert.rejects(executeTask(db,f.incoming,'fictional-a',c),e=>e.message==='night failure');assert.equal((await read(f,r)).data.phase,'offered');assert.equal((await read(f,r)).revision,1);assert.equal((await owner.query('SELECT count(*)::int n FROM candidate_operations.command_receipts WHERE request_id=$1',[c.requestId])).rows[0].n,0);}finally{await owner.query('DROP TRIGGER test_night_failure ON candidate_operations.overnight_outbox; DROP FUNCTION candidate_operations.test_night_failure();');}});
test('shift-linked transfer reopens work and keeps original checkout blocked until incoming work is verified',async()=>{const f=await shiftFixture(),incoming=await member();await owner.query("UPDATE candidate_operations.shift_references SET checkout_profile='overnight-manager' WHERE id=$1",[f.shift]);const r=await executeTask(db,creator,'fictional-a',{requestId:randomUUID(),locationId:'fictional-a',action:'task.create',input:{kind:'handoff',ownerId:f.worker.membershipId,incomingId:incoming.membershipId,shiftId:f.shift,title:'Linked checkout transfer',detail:'Complete remaining work',due:'2026-10-09T20:00:00-04:00'}});const taskStep=(actor,r,step)=>executeTask(db,actor,'fictional-a',{...command(r,step),action:'task.transition'});const ready=await taskStep(f.worker,r,'ready'),verified=await taskStep(creator,ready,'verify'),accepted=await taskStep(incoming,verified,'accept');assert.equal((await db.transaction(async c=>(await c.query('SELECT candidate_operations.read_task($1,$2,$3,$4) result',[f.worker.subject,f.worker.membershipId,'fictional-a',r.recordId])).rows[0].result)).ownerId,incoming.membershipId);const release=()=>executeTask(db,f.manager,'fictional-a',{requestId:randomUUID(),locationId:'fictional-a',action:'shift.release',recordId:f.shift,expectedRevision:1,input:{note:'Separate checkout'}});await assert.rejects(release(),denied(409));await taskStep(creator,await taskStep(incoming,accepted,'ready'),'verify');await release();});
