import {fictionalStoreInsert} from './store-fixture.mjs';
import test,{after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import pg from 'pg';
import {connection} from './test-config.mjs';import {PostgresDatabase} from './postgres-driver.ts';import {createTaskHandler} from './task-http.ts';
const admin=new pg.Pool({...connection,user:'candidate_owner'}),db=new PostgresDatabase({...connection,user:'candidate_runtime'});after(async()=>{await admin.end();await db.close();});
async function fixture(){const scope='viewer-'+randomUUID(),person=randomUUID(),id=randomUUID(),session=randomUUID(),subject='viewer-'+id;
 await admin.query(fictionalStoreInsert,[scope,'Fictional screen restaurant']);await admin.query('INSERT INTO candidate_identity.people(id,name) VALUES($1,$2)',[person,'Fictional current user']);await admin.query('INSERT INTO candidate_identity.auth_links(subject,person_id) VALUES($1,$2)',[subject,person]);await admin.query("INSERT INTO candidate_identity.memberships(id,person_id,restaurant_id,department,position) VALUES($1,$2,$3,'BOH','GM')",[id,person,scope]);await admin.query("INSERT INTO candidate_identity.sessions(id,subject,expires_at) VALUES($1,$2,clock_timestamp()+interval '1 hour')",[session,subject]);return {scope,id,person,subject,session};}
const viewer=f=>db.transaction(async c=>(await c.query('SELECT candidate_operations.schedule_viewer($1,$2,$3) AS result',[f.subject,f.id,f.scope])).rows[0].result);
test('viewer uses current explicit permissions and eligibility, never management titles',async()=>{const f=await fixture();assert.deepEqual((await viewer(f)).me.capabilities,[]);await admin.query("INSERT INTO candidate_identity.membership_capabilities(membership_id,capability) VALUES($1,'schedule.manage')",[f.id]);await admin.query("INSERT INTO candidate_identity.schedule_eligibility(member_id,job,source) VALUES($1,'Cook','qualification'),($1,'Dishwasher','schedule-job')",[f.id]);const v=await viewer(f);assert.equal(v.location.id,f.scope);assert.equal(v.me.name,'Fictional current user');assert.deepEqual(v.me.capabilities,['schedule.manage']);assert.deepEqual(v.me.qualifications,['Cook']);assert.deepEqual(v.me.scheduleJobs,['Dishwasher']);for(const key of ['personId','subject','authUserId','email'])assert.equal(Object.hasOwn(v.me,key),false);await admin.query('UPDATE candidate_identity.membership_capabilities SET active=false WHERE membership_id=$1',[f.id]);assert.deepEqual((await viewer(f)).me.capabilities,[]);});
test('viewer denies forged identity, foreign scope, inactive and schedule-only memberships',async()=>{const f=await fixture(),other=await fixture();await assert.rejects(viewer({...f,subject:other.subject}),e=>e.code==='42501');await assert.rejects(viewer({...f,scope:other.scope}),e=>e.code==='42501');await admin.query('UPDATE candidate_identity.memberships SET schedule_only=true WHERE id=$1',[f.id]);await assert.rejects(viewer(f),e=>e.code==='42501');await admin.query('UPDATE candidate_identity.memberships SET schedule_only=false,active=false WHERE id=$1',[f.id]);await assert.rejects(viewer(f),e=>e.code==='42501');});
test('HTTP viewer resolves signed-session identity, rejects extraneous fields and notices revocation',async()=>{const f=await fixture(),handler=createTaskHandler(db,async()=>({subject:f.subject,sessionId:f.session}));const request=suffix=>new Request(`https://candidate.invalid/api/operations/${f.scope}/schedule-viewer${suffix}`,{headers:{Authorization:'Bearer verified-fictional'}});assert.equal((await handler(request(''))).status,200);for(const suffix of ['?limit=10','?actor=other','/'+randomUUID()])assert.equal((await handler(request(suffix))).status,400);await admin.query('UPDATE candidate_identity.sessions SET active=false WHERE id=$1',[f.session]);assert.equal((await handler(request(''))).status,401);});
test('runtime cannot read or modify private membership tables through the viewer contract',async()=>{await assert.rejects(db.transaction(c=>c.query('SELECT * FROM candidate_identity.memberships',[])),e=>e.code==='42501');await assert.rejects(db.transaction(c=>c.query('INSERT INTO candidate_identity.membership_capabilities DEFAULT VALUES',[])),e=>e.code==='42501');});
