import test,{after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import pg from 'pg';import {connection} from './test-config.mjs';import {PostgresDatabase} from './postgres-driver.ts';import {executeTask} from './task-adapter.ts';import {createTaskHandler} from './task-http.ts';import {scheduleReview} from './runtime/closing-reference/schedule-review.mjs';
const admin=new pg.Pool({...connection,user:'candidate_owner'}),db=new PostgresDatabase({...connection,user:'candidate_runtime'});after(async()=>{await admin.end();await db.close();});
async function fixture(){const scope=`week-${randomUUID()}`,actors=[];await admin.query('INSERT INTO candidate_identity.restaurants(id,name) VALUES($1,$2)',[scope,'Fictional weekly publication']);for(const department of ['BOH','BOH','BOH','FOH']){const person=randomUUID(),membershipId=randomUUID(),subject=`fictional-${randomUUID()}`;await admin.query('INSERT INTO candidate_identity.people VALUES($1,$2)',[person,'Fictional person']);await admin.query('INSERT INTO candidate_identity.auth_links VALUES($1,$2)',[subject,person]);await admin.query("INSERT INTO candidate_identity.memberships(id,person_id,restaurant_id,department,position) VALUES($1,$2,$3,$4,'Cook')",[membershipId,person,scope,department]);await admin.query("INSERT INTO candidate_identity.schedule_eligibility VALUES($1,'Cook','schedule-job',true)",[membershipId]);actors.push({subject,membershipId,department});}for(const a of actors.slice(2))await admin.query("INSERT INTO candidate_identity.membership_capabilities VALUES($1,'schedule.manage',true),($1,'schedule.publish',true),($1,'people.manage',true),($1,'tasks.manage',true),($1,'close.confirm',true)",[a.membershipId]);await admin.query("INSERT INTO candidate_identity.membership_capabilities VALUES($1,'location.manage',true)",[actors[2].membershipId]);await admin.query('INSERT INTO candidate_operations.schedule_input_reviews(restaurant_id,time_off_complete,reviewed_at) VALUES($1,true,clock_timestamp())',[scope]);return {scope,worker:actors[0],second:actors[1],manager:actors[2],foreign:actors[3]};}
const run=(f,c,a=f.manager)=>executeTask(db,a,f.scope,c);const draft=(f,person=f.worker,start='2031-05-01T13:00:00Z',end='2031-05-01T15:00:00Z',stationId)=>run(f,{requestId:randomUUID(),locationId:f.scope,action:'shift.save',input:{personId:person.membershipId,start,end,position:'Cook',...(stationId?{stationId}:{})}});const review=(f,rs,week='2031-04-28',a=f.manager)=>db.transaction(async c=>(await c.query('SELECT candidate_operations.weekly_review($1,$2,$3,$4,$5::jsonb) result',[a.subject,a.membershipId,f.scope,week,JSON.stringify(rs.map(r=>r.recordId))])).rows[0].result);const certify=f=>admin.query("INSERT INTO candidate_operations.weekly_scope_reviews(restaurant_id,workspace_revision,evidence) SELECT id,revision,'Complete fictional source fixture' FROM candidate_identity.restaurants WHERE id=$1 ON CONFLICT(restaurant_id) DO UPDATE SET workspace_revision=excluded.workspace_revision",[f.scope]);const command=(f,rs,v,input={})=>({requestId:randomUUID(),locationId:f.scope,action:'shift.publish-batch',input:{weekStart:'2031-04-28',drafts:rs.map(r=>({id:r.recordId,revision:r.revision,closing:[]})),confirmed:true,planningReview:v.planningReview,note:'Fictional weekly publication',...input}});async function staffing(f,minimum=2){const r=await run(f,{requestId:randomUUID(),locationId:f.scope,action:'staffing.save',input:{area:'BOH',title:'Fictional staffing',position:'Cook',start:'2031-05-01T13:00:00Z',end:'2031-05-01T15:00:00Z',minimum,source:'Fictional demand'}});return run(f,{requestId:randomUUID(),locationId:f.scope,action:'staffing.approve',recordId:r.recordId,expectedRevision:r.revision,input:{confirmed:true,note:'Fictional review'}});}
const published=async f=>(await admin.query('SELECT count(*)::int n FROM candidate_operations.shift_references WHERE restaurant_id=$1 AND published',[f.scope])).rows[0].n;
test('mixed-week selection is rejected by review and publication even with forged token',async()=>{
 const f=await fixture(),inside=await draft(f),outside=await draft(f,f.second,'2031-05-08T13:00:00Z','2031-05-08T15:00:00Z');
 const valid=await review(f,[inside]);await certify(f);
 await assert.rejects(review(f,[inside,outside]),e=>e.code==='42501'&&e.message==='week_selection_denied');
 await assert.rejects(run(f,command(f,[inside,outside],valid)),e=>e.status===403&&e.code==='week_selection_denied');
 await assert.rejects(run(f,command(f,[inside,outside],{planningReview:'f'.repeat(64)})),e=>e.status===403&&e.code==='week_selection_denied');
 assert.equal(await published(f),0);
 assert.equal((await admin.query('SELECT count(*)::int n FROM candidate_operations.command_receipts WHERE restaurant_id=$1 AND payload->>\'action\'=\'shift.publish\'',[f.scope])).rows[0].n,0);
});
test('private batch core independently rejects missing bounds and out-of-week drafts',async()=>{
 const f=await fixture(),outside=await draft(f,f.worker,'2031-05-08T13:00:00Z','2031-05-08T15:00:00Z');
 const payload={action:'shift.publish',recordId:outside.recordId,expectedRevision:outside.revision,input:{note:'Fictional bounded core test'}};
 const args=[f.manager.subject,f.manager.membershipId,f.scope,randomUUID(),JSON.stringify(payload)];
 await assert.rejects(admin.query('SELECT candidate_operations.publish_shift_core($1,$2,$3,$4,$5,true,NULL,NULL)',args),e=>e.code==='22023'&&e.message==='invalid_batch_period');
 await assert.rejects(admin.query("SELECT candidate_operations.publish_shift_core($1,$2,$3,$4,$5,true,'2031-04-28T04:00:00Z','2031-05-05T04:00:00Z')",args),e=>e.code==='42501'&&e.message==='week_selection_denied');
 await assert.rejects(admin.query('SELECT candidate_operations.publish_shift_core($1,$2,$3,$4,$5,true)',args),e=>e.code==='22023'&&e.message==='batch_period_required');
 await assert.rejects(db.transaction(c=>c.query("SELECT candidate_operations.publish_shift_core($1,$2,$3,$4,$5,true,'2031-04-28T04:00:00Z','2031-05-05T04:00:00Z')",args)),e=>e.code==='42501');
 assert.equal(await published(f),0);
});
test('covered weekly batch publishes only selected drafts with exact receipts',async()=>{const f=await fixture(),a=await draft(f),b=await draft(f,f.second),unselected=await draft(f,f.worker,'2031-05-02T13:00:00Z','2031-05-02T15:00:00Z');await staffing(f);const v=await review(f,[a,b]);assert.equal(v.plannedGapCount,0);await certify(f);const r=await run(f,command(f,[b,a],v));assert.equal(r.published.length,2);assert.equal(await published(f),2);assert.equal((await admin.query('SELECT published FROM candidate_operations.shift_references WHERE id=$1',[unselected.recordId])).rows[0].published,false);assert.equal((await admin.query('SELECT count(*)::int n FROM candidate_operations.publication_batches WHERE restaurant_id=$1',[f.scope])).rows[0].n,1);});
test('unselected drafts do not cover gaps; acknowledgment and written plan are required and retained',async()=>{const f=await fixture(),a=await draft(f);await draft(f,f.second);await staffing(f);const v=await review(f,[a]);assert.equal(v.plannedGapCount,1);assert.equal(v.staffing[0].gaps[0].scheduled,1);await certify(f);await assert.rejects(run(f,command(f,[a],v)),e=>e.code==='staffing_gap_plan_required');await assert.rejects(run(f,command(f,[a],v,{coverageAcknowledged:true,coverageNote:''})),e=>e.code==='staffing_gap_plan_required');await run(f,command(f,[a],v,{coverageAcknowledged:true,coverageNote:'Fictional manager will cover the remaining station'}));assert.equal((await admin.query('SELECT coverage_note FROM candidate_operations.publication_batches WHERE restaurant_id=$1',[f.scope])).rows[0].coverage_note,'Fictional manager will cover the remaining station');assert.equal((await admin.query('SELECT data FROM candidate_operations.publication_events WHERE shift_id=$1',[a.recordId])).rows[0].data.staffingException,'Fictional manager will cover the remaining station');});
test('staffing gap segments agree with original weekly source projection',async()=>{const f=await fixture(),a=await draft(f),b=await draft(f,f.second,'2031-05-01T14:00:00Z','2031-05-01T15:00:00Z');const need=await staffing(f),v=await review(f,[a,b]);const members=[f.worker,f.second,f.manager].map(x=>({id:x.membershipId,name:'Fictional person',locationId:f.scope,area:'BOH',position:'Cook',qualifications:[],scheduleJobs:['Cook'],capabilities:x===f.manager?['schedule.publish','location.manage']:[]}));const records=[{id:a.recordId,kind:'shift',ownerId:f.worker.membershipId,locationId:f.scope,area:'BOH',data:{position:'Cook',start:'2031-05-01T13:00:00Z',end:'2031-05-01T15:00:00Z',published:false}},{id:b.recordId,kind:'shift',ownerId:f.second.membershipId,locationId:f.scope,area:'BOH',data:{position:'Cook',start:'2031-05-01T14:00:00Z',end:'2031-05-01T15:00:00Z',published:false}},{id:need.recordId,kind:'staffing',locationId:f.scope,area:'BOH',data:{status:'approved',position:'Cook',minimum:2,start:'2031-05-01T13:00:00Z',end:'2031-05-01T15:00:00Z'}}];const original=scheduleReview({location:{id:f.scope,timezone:'America/New_York'},members,me:members[2],records},'2031-04-28',[a.recordId,b.recordId]);const normalize=rows=>rows.map(g=>({...g,start:new Date(g.start).toISOString(),end:new Date(g.end).toISOString()}));assert.deepEqual(normalize(v.staffing[0].gaps),original.staffing[0].planned);assert.equal(v.plannedGapCount,original.plannedGapCount);});
test('changed staffing and administrative job changes invalidate planning token',async()=>{const f=await fixture(),a=await draft(f),v=await review(f,[a]);await staffing(f);await certify(f);await assert.rejects(run(f,command(f,[a],v)),e=>e.code==='planning_review_conflict');const current=await review(f,[a]);await admin.query("UPDATE candidate_identity.schedule_eligibility SET active=false WHERE member_id=$1",[f.worker.membershipId]);await assert.rejects(run(f,command(f,[a],current)),e=>e.code==='planning_review_conflict');assert.equal(await published(f),0);});
test('scope evidence, week boundaries, duplicate selection and confirmed review are enforced',async()=>{const f=await fixture(),a=await draft(f),v=await review(f,[a]);await assert.rejects(run(f,command(f,[a],v)),e=>e.code==='weekly_scope_review_required');await certify(f);await assert.rejects(run(f,command(f,[a],v,{confirmed:false})),e=>e.status===400);await assert.rejects(run(f,command(f,[a,a],v)),e=>e.status===400);await assert.rejects(review(f,[a],'2031-05-05'),e=>e.code==='42501');await assert.rejects(review(f,[a],'2031-02-30'),e=>e.code?.startsWith('22'));await assert.rejects(review(f,[a],'2031-04-28',f.foreign),e=>e.code==='42501');});
test('stale closing selection cannot publish even with a fresh planning token',async()=>{const f=await fixture(),a=await draft(f),standard=randomUUID();await admin.query("INSERT INTO candidate_operations.standard_references VALUES($1,$2,'BOH','Fictional close','Grill','Cook',1,1,'manager','approved','[\"Clean\"]')",[standard,f.scope]);await admin.query('INSERT INTO candidate_operations.shift_standard_links(shift_id,standard_id,restaurant_id) VALUES($1,$2,$3)',[a.recordId,standard,f.scope]);await admin.query("INSERT INTO candidate_identity.station_clearances VALUES($1,$2,'Cook',true)",[f.worker.membershipId,f.scope]);const close=await run(f,{requestId:randomUUID(),locationId:f.scope,action:'close.assign',input:{shiftId:a.recordId,standardId:standard,managerId:f.manager.membershipId,due:'2031-05-01T14:30:00Z',note:'Fictional close'}});const v=await review(f,[a]);await certify(f);await assert.rejects(run(f,command(f,[a],v)),e=>e.code==='closing_selection_conflict');await run(f,command(f,[a],v,{drafts:[{id:a.recordId,revision:1,closing:[{id:close.recordId,revision:1}]}]}));assert.equal(await published(f),1);});
test('batch retries apply once and replay rechecks current publisher authority',async()=>{const f=await fixture(),a=await draft(f),v=await review(f,[a]);await certify(f);const c=command(f,[a],v),results=await Promise.all([run(f,c),run(f,c)]);assert.deepEqual(results.map(r=>r.replayed).sort(),[false,true]);assert.equal(await published(f),1);await assert.rejects(run(f,{...c,input:{...c.input,note:'Changed'}}),e=>e.code==='request_payload_conflict');await admin.query("UPDATE candidate_identity.membership_capabilities SET active=false WHERE membership_id=$1 AND capability='schedule.publish'",[f.manager.membershipId]);await assert.rejects(run(f,c),e=>e.status===403);});
test('failure on the later shift rolls back the whole batch including child receipts and scope revision',async()=>{const f=await fixture(),a=await draft(f),b=await draft(f,f.second,'2031-05-02T13:00:00Z','2031-05-02T15:00:00Z'),v=await review(f,[a,b]);await certify(f);const c=command(f,[a,b],v);await admin.query(`CREATE FUNCTION candidate_operations.fail_week() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.shift_id='${b.recordId}'::uuid THEN RAISE EXCEPTION 'fictional_week_failure'; END IF; RETURN NEW; END; $$`);await admin.query('CREATE TRIGGER fail_week BEFORE INSERT ON candidate_operations.publication_outbox FOR EACH ROW EXECUTE FUNCTION candidate_operations.fail_week()');try{await assert.rejects(run(f,c),e=>e.message==='fictional_week_failure');assert.equal(await published(f),0);assert.equal((await admin.query('SELECT revision FROM candidate_identity.restaurants WHERE id=$1',[f.scope])).rows[0].revision,v.workspaceRevision);assert.equal((await admin.query('SELECT count(*)::int n FROM candidate_operations.publication_batches WHERE restaurant_id=$1',[f.scope])).rows[0].n,0);assert.equal((await admin.query("SELECT count(*)::int n FROM candidate_operations.command_receipts WHERE restaurant_id=$1 AND payload->>'action' IN ('shift.publish','shift.publish-batch')",[f.scope])).rows[0].n,0);}finally{await admin.query('DROP TRIGGER fail_week ON candidate_operations.publication_outbox');await admin.query('DROP FUNCTION candidate_operations.fail_week()');}});
test('station goals originate from earliest selected shift regardless of selection order',async()=>{const f=await fixture(),station=await run(f,{requestId:randomUUID(),locationId:f.scope,action:'station.save',input:{title:'Fictional station',levels:[],status:'active',note:'Fictional setup',setup:{jobs:['Cook'],memberIds:[f.worker.membershipId],standardIds:[],allJobMembers:false,managerId:f.manager.membershipId,goals:[{id:'learn',title:'Fictional learning',definition:'Observable fictional outcome',dueDays:7}]}}});const a=await draft(f,f.worker,'2031-05-01T13:00:00Z','2031-05-01T15:00:00Z',station.recordId),b=await draft(f,f.worker,'2031-05-02T13:00:00Z','2031-05-02T15:00:00Z',station.recordId),v=await review(f,[b,a]);await certify(f);await run(f,command(f,[b,a],v));const goals=(await admin.query('SELECT station_learning FROM candidate_operations.employee_goals WHERE restaurant_id=$1',[f.scope])).rows;assert.equal(goals.length,1);assert.equal(goals[0].station_learning.shiftId,a.recordId);});
test('HTTP review is authenticated/read-only and private batch core/evidence writes are denied',async()=>{const f=await fixture(),a=await draft(f),sessionId=randomUUID();await admin.query("INSERT INTO candidate_identity.sessions(id,subject,expires_at) VALUES($1,$2,clock_timestamp()+interval '1 hour')",[sessionId,f.manager.subject]);const handler=createTaskHandler(db,async()=>({subject:f.manager.subject,sessionId})),headers={Authorization:'Bearer fictional','Content-Type':'application/json'},url=`http://candidate.invalid/api/operations/${f.scope}`;const response=await handler(new Request(url+'/week-review',{method:'POST',headers,body:JSON.stringify({weekStart:'2031-04-28',draftIds:[a.recordId]})}));assert.equal(response.status,200);const v=await response.json();await certify(f);assert.equal((await handler(new Request(url+'/commands',{method:'POST',headers,body:JSON.stringify(command(f,[a],v))}))).status,200);await assert.rejects(db.transaction(c=>c.query('SELECT candidate_operations.publish_shift_core($1,$2,$3,$4,$5,true)',[f.manager.subject,f.manager.membershipId,f.scope,randomUUID(),{}])),e=>e.code==='42501');await assert.rejects(db.transaction(c=>c.query('UPDATE candidate_operations.weekly_scope_reviews SET workspace_revision=999',[])),e=>e.code==='42501');await admin.query('UPDATE candidate_identity.sessions SET active=false WHERE id=$1',[sessionId]);assert.equal((await handler(new Request(url+'/week-review',{method:'POST',headers,body:JSON.stringify({weekStart:'2031-04-28',draftIds:[a.recordId]})}))).status,401);});
