import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {runPositionWeek} from './all-position-week-fixture.mjs';

const source='Owner-confirmed restaurant walkthrough through October 8; outputs/JMAX-Position-Review-and-Remaining-Gaps-2026-10-07.md. Test approval is fictional and is not restaurant SOP publication.';
const scenario=(title,detail,nextAction)=>({title,detail,nextAction});
const safety='Pause the affected task and contact the named BOH manager. Use an approved recipe or equipment method; do not invent a temperature, oil grade or chemical instruction.';
const commonClosing=['Hand off unresolved tickets, shortages and equipment concerns to the named BOH manager.','Request the assigned independent physical check and manager release; a ready signal alone is not permission to leave.'];
const profile=(id,position,opening,service,closing,dailyScenarios,extra={})=>({id:'berts-'+id,restaurant:'berts',area:'BOH',position,source,opening,service,closing:[...closing,...commonClosing],dailyScenarios,...extra});
export const bertsBohProfiles=[
 profile('dishwasher-am','Dishwasher',
  ['Check inherited dish-room readiness and assigned prep with the manager.','Complete outside grounds cleanup immediately before opening; do not move it to the afternoon.'],
  ['Keep dish work coordinated with the cook team and report missing supplies or equipment concerns.','Do only assigned prep using approved instructions.'],
  ['Leave the machine running at the AM-to-PM handoff and communicate pending work; BOH covers staffing gaps.'],
  [scenario('Inherited dirty racks','Previous close left racks dirty.','Retain the corrective assignment until the manager checks the remedy.'),scenario('Unclear prep instruction','AM dish is given prep without a current method.',safety),scenario('Grounds work interrupted before open','Outside cleanup cannot finish before opening.','Tell the manager the unfinished area; do not silently move the task to afternoon.'),scenario('Handoff employee arrives late','PM dish arrival is delayed.','Manager arranges BOH coverage; hand off pending loads and machine status.'),scenario('Sanitation supply unavailable','Approved dish supply is missing.',safety),scenario('Damaged rack discovered','A rack is broken while other clean racks are available.','Isolate damaged equipment and ask the manager for the approved alternative.'),scenario('Sunday readiness backlog','Opening inherits additional pans after a busy Saturday.','Prioritize with the manager and preserve unfinished work in the handoff.')],
  {shiftAssignment:'AM Dishwasher',dishShift:'AM',shiftStartHour:8,shiftEndHour:15,knownGaps:[{area:'Dish instructions',detail:'Equipment-specific cleaning and sanitation procedures need approved source content. No invented method or threshold is simulated.'}]}),
 profile('dishwasher-pm','Dishwasher',
  ['Receive the AM handoff, including pending work and machine status.','Confirm PM rinse/load and catch responsibilities with the manager.'],
  ['Rinse/load and catch staff help each other as volume changes.','Notify the BOH manager when staffing or equipment interrupts dish readiness.'],
  ['Finish dish-area cleanup and assigned put-away duties; the manager physically checks and releases the closer.'],
  [scenario('AM handoff has pending pans','Pending AM pans are explicitly handed over.','Coordinate the backlog without losing the original handoff.'),scenario('Catch bottleneck','Clean dishes accumulate at catch.','Rinse/load and catch help each other rather than treating it as another person\'s job.'),scenario('Closing inspection fails','Manager finds remaining dish-area cleanup.','Correct and request another independent check.'),scenario('Phone session renewed','Dish employee signs out and back in midweek.','Own assignment and prior handoff must remain visible.'),scenario('Machine concern during rush','Dish machine performance is uncertain.',safety),scenario('Closer absent','PM closer cannot finish assigned work.','Ask the manager to arrange coverage and keep the outstanding work assigned.'),scenario('Late pizza pans','Pans arrive after initial ready signal.','Reopen the relevant cleanup and obtain the manager\'s check before leaving.')],
  {shiftAssignment:'PM Dishwasher',dishShift:'PM',shiftStartHour:15,shiftEndHour:23,knownGaps:[{area:'Dish instructions',detail:'No equipment-specific shutdown, sanitation product or cycle settings are inferred from general role ownership.'}]}),
 profile('fryer','Fry',
  ['Check inherited station close, stock, clean utensils and fryer readiness.','Check oil condition at opening using the approved restaurant criteria.'],
  ['Follow tickets and recipes, coordinate with Expo and check oil again midshift.','Distinguish a planned filter, top-up or replacement from a completed oil action.'],
  ['Complete normal station cleanup and close-to-open stock; check oil at close.'],
  [scenario('Opening oil condition uncertain','The station has no approved grading/action instruction.',safety),scenario('Missing recipe portion','A modifier cannot be resolved from the current recipe.','Ask the BOH manager and do not improvise the recipe.'),scenario('Filter plan not completed','A filter action was proposed but not performed.','Keep planned and actual action separate; manager assigns the next step.'),scenario('Rush product shortage','Fryer stock runs short during service.','BOH manager decides who makes urgent prep; communicate the shortage to Expo.'),scenario('Incorrect item at Expo','Expo requests a recook for a cooking error.','Coordinate the recook and leave the original correction open until checked.'),scenario('Oil action unknown at close','Closing employee cannot establish whether oil was replaced.','Report the uncertainty; do not mark the action complete.'),scenario('Next-day unresolved stock','A closing shortage carries into the next opening.','Read the prior issue and confirm the manager-directed remedy.')],
  {knownGaps:[{area:'Oil procedure',detail:'Filtering schedule, grades and action criteria were explicitly deferred; the simulation tests escalation and carryover rather than inventing policy.'}]}),
 profile('grill','Grill',
  ['Check approved station setup, clean utensils, stock and inherited readiness.','Bert\'s includes the charbroiler; do not copy equipment assumptions to Rudd\'s.'],
  ['Follow the ticket and approved product/doneness checks.','Coordinate service timing with adjacent stations and Expo.'],
  ['Complete approved flat-top and station cleanup, product storage and handoff.'],
  [scenario('Charbroiler readiness concern','Bert\'s charbroiler needs manager attention.',safety),scenario('Flat-top stock short','Stock is insufficient for the next ticket.','Notify the BOH manager and coordinate prep.'),scenario('Doneness question','Current ticket conflicts with an unclear product instruction.',safety),scenario('Expo recook','Expo identifies a cooking error.','Coordinate the requested recook and communicate timing.'),scenario('Deep cleaning suggested in rush','Behind-equipment deep cleaning is proposed during active service.','Manager plans an appropriate slower period; do not treat deep-clean cadence as settled.'),scenario('Inspection fails underneath','Closing check finds incomplete station cleaning.','Correct then repeat independent verification.'),scenario('Unresolved repair at opening','An equipment concern remains from yesterday.','Retain the manager-owned issue and use only the approved safe alternative.')],
  {knownGaps:[{area:'Deep cleaning',detail:'Behind-equipment and hood cadence remains a separate pending procedure; no cadence is invented.'}]}),
 profile('flat-top-assignment','Cook',
  ['Confirm the Flat Top station boundary, menu ownership and approved instructions with the BOH manager.','Check tools, ingredients and inherited readiness.'],
  ['Follow current tickets and approved recipes; coordinate timing with adjacent stations and Expo.','Do not infer burger ownership from historical Grill material.'],
  ['Use the approved Flat Top cleaning/storage procedure and report unfinished work.'],
  [scenario('Missing Flat Top module','No complete current local module is available.',safety),scenario('Historical menu conflict','Old Grill material lists an item not assigned to this station.','Use current manager-approved menu ownership; do not adopt historical boundaries.'),scenario('Utensil shortage','A required clean utensil is unavailable.','Report the shortage and follow the approved alternative.'),scenario('Unclear shutdown authority','The worker does not know whether an appliance should be shut down.',safety),scenario('Ticket timing mismatch','An adjacent station cannot finish in time.','Coordinate with Expo and the BOH manager.'),scenario('Rejected closing check','Manager identifies remaining table cleanup.','Correct and request reinspection.'),scenario('Next-day equipment issue','Equipment concern survives the previous close.','Review the saved concern and manager direction before starting.')],
  {shiftAssignment:'Flat Top station assignment',knownGaps:[{area:'Station procedure',detail:'Flat Top is an assignment of Cook, not a new access tier. Starter reference says its complete local module and current menu boundary remain missing.'}]}),
 profile('sandwich-pasta','Sandwich/Pasta',
  ['Check the inherited station close, approved stock and utensils.','Review the current menu ownership and coordination with Oven.'],
  ['Assemble baked spaghetti and load it into the oven. Oven pulls, plates and sends it to Expo.','Oven assembles and bakes Reubens and chicken bacon ranch subs; do not duplicate their assembly here.'],
  ['Complete station breakdown, approved product storage, stock and close-to-open cleanup.'],
  [scenario('Baked spaghetti oven handoff','Spaghetti is loaded while Oven is busy.','Clearly communicate the ticket and outstanding oven finish to Oven.'),scenario('Old sub assembly list','Historical instructions put Reubens at Sandwich/Pasta.','Use the newer correction: Oven assembles and bakes them.'),scenario('Pasta prep shortage','Required pasta prep is short.','Ask BOH manager to assign urgent prep and coordinate with Expo.'),scenario('Unclear ingredient instruction','Recipe or allergen answer cannot be established.',safety),scenario('Oven finish delayed','Spaghetti cannot be pulled on time.','Communicate the incomplete handoff, ask the manager for help and retain the outstanding ticket.'),scenario('Storage check fails','Closing inspector finds unclear dating.','Use approved handling instructions and request another check.'),scenario('Close-to-open shortage','Next opening inherits missing stock.','Keep the prior shortage visible until the manager verifies correction.')],
  {knownGaps:[{area:'Service handoff',detail:'Generic task/message records preserve the reported handoff, but do not represent a live POS kitchen ticket or actual Oven delivery.'}]}),
 profile('salad-bar-room','Salad Bar Room',
  ['Review the manager\'s assigned salad-bar prep list and inherited close.','Check food quality and clean utensils; store prepared backup pans beneath the bar.'],
  ['Complete assigned salad-bar prep with approved product handling.','Hand upkeep to Host when leaving; Server owns final salad-bar close.'],
  ['Finish the employee\'s assigned room cleanup and communicate remaining prep and backup product.','Manager plans next-day salad bar, Back Window, restaurant prep and bulk-prep sheets.'],
  [scenario('Inherited food-quality concern','Opening finds a product whose quality is uncertain.',safety),scenario('Prep sheet missing','Assigned salad-bar prep sheet is unavailable.','Ask BOH manager or GM; do not invent the next-day list.'),scenario('Backup pans depleted','Service consumes the backup underneath the bar.','Report the shortage and request manager-directed prep.'),scenario('Weekday departure handoff','Salad employee leaves and Host maintains the bar.','Send clear remaining work to Host; final close remains Server-owned.'),scenario('Weekend later departure','Weekend service keeps salad prep staffed later.','Use the assigned shift, not a hard-coded weekday departure time.'),scenario('Unclear storage method','A product lacks approved storage instructions.',safety),scenario('Final-close ownership conflict','Prep employee is assumed to own final salad-bar close.','Retain the confirmed Server final close and manager check; do not silently move ownership.')],
  {knownGaps:[{area:'Cross-position coordination',detail:'This profile checks saved messages and work records, not automatic Host/Server reassignment of salad-bar maintenance or Jeff\'s live four-sheet release.'}]}),
 profile('combined-oven','Oven / Pizza Make / Catch',
  ['Have clean utensils, garnish bottles, shakers, boxes and service trays or platters ready.'],
  ['Assemble and bake pizza, breadsticks, dinner rolls, Reubens, chicken bacon ranch subs and potato skins.','Pull and plate the baked spaghetti assembled and loaded by Sandwich/Pasta; send it to Expo.'],
  ['Turn the oven off and clean the crumb tray; wipe tables and break down the pizza table.','Check dates and clean underneath; send pans to Dish and store or discard butter by approved instructions.','Clean the large mixing-bowl area and outside smoking area; set up close to open.'],
  [scenario('Baked spaghetti handoff','Sandwich/Pasta has assembled and loaded spaghetti.','Oven pulls, plates and sends it to Expo; do not reassign assembly.'),scenario('Combined role rush','Pizza and multiple oven foods are due together.','Coordinate priorities with Expo and BOH manager; teamwork remains flexible.'),scenario('Wrong garnish at Expo','Expo catches an incorrect garnish.','Correct the cooking error and retain follow-through until checked.'),scenario('Late pizza after ready','Late pizza arrives after the initial closing-ready signal.','Manager coordinates coverage and repeats affected closing checks.'),scenario('Butter handling unclear','A butter portion has uncertain approved storage instructions.',safety),scenario('Under-table dates fail','Manager finds unclear dates under the pizza table.','Correct with approved product handling and request reinspection.'),scenario('Mixing bowl area unfinished','Mixing-bowl area was not finished at prior close.','Carry the area issue forward and request manager verification.')],
  {knownGaps:[{area:'Assigned areas',detail:'Daily assigned-area source needs final source reconciliation; no historical extra cleaning assignment is silently added.'}]}),
 profile('boh-manager','BOH Manager',
  ['Review staffing, equipment and food readiness, shortages and outstanding Red Book issues.','Confirm delegated coverage and current prep needs; GM remains accountable during BOH-manager absence.'],
  ['Assign urgent prep, coordinate with Expo and FOH on shortages and staffing cuts.','Handle initial coaching for missed duties and escalate repeats to GM.','Perform the approved temperature, station and cooling verification process.'],
  ['Check station readiness and cooling verification; prepare the four next-day prep sheets and retain unresolved work.'],
  [scenario('Cook call-in','One station is unstaffed.','Arrange coverage and record the current staffing decision.'),scenario('Urgent prep shortage','Critical prep is short during service.','BOH manager assigns who stops current work to make it.'),scenario('Repeated unstocked station','A station repeats an unstocked close after coaching.','Coach initially and escalate continued misses to GM.'),scenario('Cut coordination','Business slows in FOH and BOH.','Coordinate support-first cuts while protecting required coverage.'),scenario('Cooling verification absent','A batch has no approved cooling verification.',safety),scenario('Four prep sheets incomplete','One next-day sheet is still missing.','Retain manager-owned unfinished prep planning until the sheet is prepared.'),scenario('BOH manager absent tomorrow','Manager will be absent next shift.','GM remains accountable and may appoint someone to perform checks.')],
  {capabilities:['tasks.manage','standards.approve','close.confirm','schedule.manage','schedule.change','operations.escalation'],knownGaps:[{area:'Food release and safety',detail:'This harness tests manager work, independent checkout and persistence. Live Jeff sheet release and equipment/product-specific temperature/cooling acceptance are separate unverified connections.'}]}),
 profile('prep-cook','Prep Cook',
  ['Read only the assigned released daily or bulk prep and its recipe instructions.','Check actual stock and report missing recipe, ingredient mapping or shelf-life metadata.'],
  ['Record actual completed quantity and explain a shortage; do not post a second inventory change.','Use reviewed units: ranch weekly six five-gallon vessels per Bert\'s; green peppers two dedicated vessels.'],
  ['Hand unfinished prep and shortage status to the manager; retain the original actual report and target date.'],
  [scenario('Recipe ingredient unmapped','Assigned recipe has an ingredient without a mapped source item.','Report missing mapping to manager rather than inventing the ingredient.'),scenario('Assignment changes mid-task','Manager assigns released prep to another employee.','Refresh before saving; former assignee must not report completion.'),scenario('Access withdrawn mid-save','Employee access is withdrawn during completion.','Reject without partial report or stock mutation.'),scenario('Zero actual with shortage','Expected prep cannot be made.','Record zero with a specific shortage note; keep it visible to manager.'),scenario('Advice is stale','Source recommendation changed since manager review.','Refresh and review; recommended stock par is not the entire production amount.'),scenario('Yesterday prep still unfinished','Past-target prep remains assigned next day.','Preserve its original target date and report completion on the original plan.'),scenario('Another restaurant recipe guessed','Worker tries a Rudd\'s assignment identifier.','Deny cross-restaurant access and preserve source stock.')],
  {knownGaps:[{area:'Prep execution boundary',detail:'This general weekly harness tests work/checkout/AI context. Existing tests/week-sim-prep-cook.test.mjs provides the actual seven-day count/release/recipe/actual Food handler loop; this profile alone is not Food completion proof.'},{area:'Prep shortage follow-through',detail:'The prior actual Food simulation found no dedicated manager shortage-resolution command. Generic task follow-up does not falsely claim that missing Food command exists.'}]}),
];

for(const p of bertsBohProfiles)test(`Bert's ${p.shiftAssignment??p.position}: durable seven-day opening/service/closing simulation`,{concurrency:false},async()=>{
 const result=await runPositionWeek(p);
 result.shiftAssignment=p.shiftAssignment??p.position;
 result.source=source;
 result.knownGaps=p.knownGaps??[];
 result.scenarioCount=p.dailyScenarios.length;
 fs.mkdirSync('evidence/all-position-week',{recursive:true});
 fs.writeFileSync(`evidence/all-position-week/berts-boh-${p.id}.json`,JSON.stringify(result,null,2)+'\n');
 assert.equal(result.days.length,7,JSON.stringify(result.failures));
 assert.equal(result.operationalReseeds,0);
 assert.equal(result.finalReopen,true);
 // Initial denied-Dish AI receipts are preserved in *-before-ai-fix.json.
 // Current scope-limited AI must work for Dish too, without granting goals
 // or generic management/closing permissions.
 assert.deepEqual(result.failures,[]);
 assert.equal(result.aiContextRequests,7);
});
