import test from 'node:test';import assert from 'node:assert/strict';import {sheetFixture,lines} from './catering-sheet-fixture.mjs';import {ok} from './maintenance-meter-fixture.mjs';import {facts,review} from './catering-fixture.mjs';import {cateringSheet} from '../.sites-runtime/shared/catering-sheet.mjs';import {cateringMenuLines} from '../.sites-runtime/shared/catering-menu.mjs';
test('menu quantities retain explicit units and reject invalid, excessive and imprecise rows',()=>{
 assert.deepEqual(cateringMenuLines(lines),lines);assert.equal(cateringMenuLines([{...lines[0],quantity:0.001}])[0].quantity,0.001);
 for(const input of [null,{},Array(41).fill(lines[0]),[null],[{...lines[0],item:''}],[{...lines[0],unit:''}],[{...lines[0],notes:'x'.repeat(501)}],...[0,-1,NaN,Infinity,100001,1.0001,'1'].map(quantity=>[{...lines[0],quantity}])])assert.throws(()=>cateringMenuLines(input));
 assert.deepEqual(cateringMenuLines([]),[]);
});
test('legacy publications never expose new draft quantities and omission preserves a saved menu during correction',async t=>{
 const f=await sheetFixture(t);let r=await f.publish({menuLines:[]});await f.db.prepare("UPDATE records SET data=json_remove(data,'$.publication.facts.menuLines') WHERE id=?").bind(r.recordId).run();r=ok(await f.call('manager','catering.revise',{...facts,menuLines:[{...lines[0],item:'PRIVATE-DRAFT-ITEM'}],note:'PRIVATE-CORRECTION'},r));
 const peer=(await f.view('worker')).records.find(x=>x.id===r.recordId);assert.deepEqual(peer.data.menuLines,[]);assert.doesNotMatch(JSON.stringify(peer),/PRIVATE-/);const print=await f.sheet('owner',r);assert.equal(print.status,200);assert.match(print.text,/SUPERSEDED/);assert.match(print.text,/quantities were not recorded/);assert.doesNotMatch(print.text,/PRIVATE-/);
 r=ok(await f.call('manager','catering.revise',{...facts,note:'Legacy client edits notes'},r));assert.equal((await f.saved(r)).data.menuLines[0].item,'PRIVATE-DRAFT-ITEM');r=ok(await f.call('manager','catering.submit',review,r));r=ok(await f.call('owner','catering.publish',review,r));assert.equal((await f.view('worker')).records.find(x=>x.id===r.recordId).data.menuLines[0].item,'PRIVATE-DRAFT-ITEM');
 r=ok(await f.call('manager','catering.revise',{...facts,menuLines:[],note:'Remove line with review'},r));assert.equal((await f.saved(r)).data.menuLines.length,0);assert.equal((await f.saved(r)).data.internal.versions.at(-1).facts.menuLines[0].item,'PRIVATE-DRAFT-ITEM');assert.equal((await f.view('worker')).records.find(x=>x.id===r.recordId).data.menuLines[0].item,'PRIVATE-DRAFT-ITEM');
});
test('menu edits use exact revisions and rollback without leaking changed quantities or duplicating retries',async t=>{
 const f=await sheetFixture(t);let r=await f.publish();const old=r,input={...facts,menuLines:[{...lines[0],quantity:30}],note:'Fixture quantity revision'};r=ok(await f.call('manager','catering.revise',input,r,{requestId:'menu-once'}));assert.deepEqual(ok(await f.call('manager','catering.revise',input,old,{requestId:'menu-once'})),r);assert.equal((await f.call('manager','catering.revise',input,old)).status,409);assert.equal((await f.view('worker')).records.find(x=>x.id===r.recordId).data.menuLines[0].quantity,24);
 await f.db.prepare("CREATE TRIGGER fail_menu BEFORE INSERT ON command_receipts WHEN NEW.request_id='menu-fail' BEGIN SELECT RAISE(ABORT,'fixture rollback'); END").run();assert.equal((await f.call('manager','catering.revise',{...input,menuLines:[]},r,{requestId:'menu-fail'})).status,503);assert.equal((await f.saved(r)).data.menuLines[0].quantity,30);
});
test('published sheets escape text, show exact units and publication identity, and omit all private and draft fields',async t=>{
 const f=await sheetFixture(t);let r=await f.publish({title:'<img src=x onerror=alert(1)>',menuLines:[{...lines[0],item:'<script>BAD</script>',notes:'A & B',reference:'<private>'}]});const w=await f.view(),row=await f.saved(r);row.data.menuNotes='UNREVIEWED';row.data.menuLines=[{...lines[0],item:'UNREVIEWED'}];row.data.status='draft';row.data.version++;
 const html=cateringSheet(w,row,'2099-09-01T00:00:00Z');assert.match(html,/&lt;script&gt;BAD&lt;\/script&gt;/);assert.match(html,/A &amp; B/);assert.match(html,/<td>24<\/td><td>boxes<\/td>/);assert.match(html,/Published version 1; latest event version 2/);assert.match(html,/SUPERSEDED/);assert.doesNotMatch(html,/<script|<img|PRIVATE-|UNREVIEWED|bookingRef|sourceRef|acknowledgments/);assert.match(html,/@media print/);assert.match(html,/table-header-group/);assert.match(html,/Printed copies do not update/);
 row.data.status='cancelled';row.data.notice={summary:'<cancelled>',by:'owner',at:'2099-09-01T00:00:00Z'};assert.match(cateringSheet(w,row,'2099-09-01T00:00:00Z'),/CANCELLED.*do not use for preparation/);assert.match(cateringSheet(w,row,'2099-09-01T00:00:00Z'),/&lt;cancelled&gt;/);row.data.status='completed';assert.match(cateringSheet(w,row,'2099-10-03T00:00:00Z'),/COMPLETION REPORTED/);row.data.status='published';row.data.notice=null;assert.match(cateringSheet(w,row,'2099-10-03T00:00:00Z'),/EVENT ENDED/);
});
test('sheet route requires current identity, restaurant, audience, publication and revision and is read-only',async t=>{
 const f=await sheetFixture(t);let r=ok(await f.call('manager','catering.create',{...facts,menuLines:lines}));assert.equal((await f.sheet('owner',r)).status,409);assert.equal((await f.sheet('worker',r)).status,404);r=ok(await f.call('manager','catering.submit',review,r));r=ok(await f.call('owner','catering.publish',review,r));
 const before=await f.saved(r),html=await f.sheet('worker',r);assert.equal(html.status,200);assert.equal(html.headers.get('Content-Type'),'text/html; charset=utf-8');assert.match(html.headers.get('Cache-Control'),/no-store/);assert.match(html.headers.get('Content-Security-Policy'),/default-src 'none'/);assert.equal(html.headers.get('X-Content-Type-Options'),'nosniff');assert.deepEqual(await f.saved(r),before);
 for(const actor of [null,'dish','schedule','foreign'])assert.notEqual((await f.sheet(actor,r)).status,200);assert.equal((await f.sheet('worker',r,{locationId:'b'})).status,403);assert.equal((await f.sheet('worker',r,{revision:String(r.revision-1)})).status,409);assert.equal((await f.sheet('worker',r,{revision:'1e1'})).status,400);assert.equal((await f.sheet('worker',r,{extra:'1'})).status,400);assert.equal((await f.sheet('worker',r,{},f.db,'POST')).status,405);
 await f.db.prepare("UPDATE memberships SET area='FOH',revision=revision+1 WHERE id='worker'").run();assert.equal((await f.sheet('worker',r)).status,404);await f.db.prepare("UPDATE records SET archived_at='2026-09-01T00:00:00Z' WHERE id=?").bind(r.recordId).run();assert.equal((await f.sheet('owner',r)).status,404);
});
test('sheet generation rejects manager access or workspace changes between initial read and final release',async t=>{
 const f=await sheetFixture(t);const r=await f.publish();let reads=0;const binding={withSession:()=>({prepare:(...args)=>f.db.prepare(...args),batch:async statements=>{const result=await f.db.batch(statements);if(++reads===1)await f.db.prepare("UPDATE memberships SET active=0,revision=revision+1 WHERE id='worker'").run();return result}})};assert.notEqual((await f.sheet('worker',r,{},binding)).status,200);
 let called=false;const changed={withSession:()=>({prepare:(...args)=>f.db.prepare(...args),batch:async statements=>{const result=await f.db.batch(statements);if(!called){called=true;await f.db.prepare("UPDATE locations SET revision=revision+1 WHERE id='a'").run()}return result}})};assert.equal((await f.sheet('owner',r,{},changed)).status,409);
});
