import test from 'node:test';import assert from 'node:assert/strict';import {fixture,ok} from './maintenance-meter-fixture.mjs';import {facts,review} from './catering-fixture.mjs';import {applyCommand} from '../.sites-runtime/shared/domain.mjs';import {cateringNoticeKey,cateringPhase,cateringOnDate} from '../.sites-runtime/shared/catering.mjs';
const create=async f=>ok(await f.call('manager','catering.create',facts));
async function publish(f){let r=await create(f);r=ok(await f.call('manager','catering.submit',review,r));return ok(await f.call('owner','catering.publish',review,r));}
test('event drafts stay private until exact owner publication, with audience and private sources enforced',async t=>{
 const f=await fixture(t);let r=await create(f);
 for(const actor of ['worker','othermanager','dish','schedule'])assert.equal((await f.view(actor)).records.some(x=>x.id===r.recordId),false);
 assert.equal((await f.call('manager','catering.create',{...facts,managerId:'othermanager'})).status,403);
 assert.equal((await f.call('owner','catering.publish',review,r)).status,400);r=ok(await f.call('manager','catering.submit',review,r));assert.equal((await f.call('manager','catering.publish',review,r)).status,403);r=ok(await f.call('owner','catering.publish',review,r));
 const peer=(await f.view('worker')).records.find(x=>x.id===r.recordId);assert.equal(peer.data.menuNotes,facts.menuNotes);assert.equal(peer.data.internal,undefined);assert.doesNotMatch(JSON.stringify(peer),/PRIVATE-/);
 for(const actor of ['dish','schedule'])assert.equal((await f.view(actor)).records.some(x=>x.id===r.recordId),false);
 await f.db.prepare("UPDATE memberships SET area='FOH',revision=revision+1 WHERE id='worker'").run();assert.equal((await f.view('worker')).records.some(x=>x.id===r.recordId),false);assert.equal((await f.view()).records.some(x=>x.kind==='message'||x.kind==='shift'||x.kind==='order'),false);
});
test('published revisions retain the old brief with a pending warning and exact-version read receipts',async t=>{
 const f=await fixture(t);let r=await publish(f),d=(await f.saved(r)).data;const key=cateringNoticeKey(d);
 r=ok(await f.call('worker','catering.acknowledge',{read:true,noticeKey:key},r));r=ok(await f.call('othermanager','catering.acknowledge',{read:true,noticeKey:key},r));assert.equal((await f.view('worker')).records.find(x=>x.id===r.recordId).data.acknowledgments.length,1);
 r=ok(await f.call('manager','catering.revise',{...facts,title:'UNREVIEWED-TITLE',menuNotes:'UNREVIEWED-MENU',note:'PRIVATE-CHANGE'},r));
 const p=(await f.view('worker')).records.find(x=>x.id===r.recordId);assert.equal(cateringPhase(p.data,'2099-09-01T12:00:00Z'),'update-pending');assert.equal(p.data.title,facts.title);assert.equal(p.data.menuNotes,facts.menuNotes);assert.doesNotMatch(JSON.stringify(p),/UNREVIEWED|PRIVATE-/);assert.equal((await f.call('worker','catering.acknowledge',{read:true,noticeKey:key},r)).status,409);
 assert.equal((await f.saved(r)).data.internal.versions[0].facts.menuNotes,facts.menuNotes);r=ok(await f.call('manager','catering.submit',review,r));r=ok(await f.call('owner','catering.return',review,r));r=ok(await f.call('manager','catering.submit',review,r));r=ok(await f.call('owner','catering.publish',review,r));
 d=(await f.view('worker')).records.find(x=>x.id===r.recordId).data;assert.equal(d.menuNotes,'UNREVIEWED-MENU');assert.notEqual(cateringNoticeKey(d),key);assert.equal(d.publication.version,2);
});
test('restaurant times reject invalid and ambiguous hours and date filters include overnight events',async t=>{
 const f=await fixture(t);for(const patch of [{guests:0},{guests:1.2},{guests:'24'},{audience:[]},{audience:['BOH','BOH']},{endDate:'2099-09-01'},{endDate:'2099-10-09'},{startDate:'2099-02-30'},{sourceRef:''},{managerId:'foreign'},{startDate:'2026-03-08',startTime:'02:30',endDate:'2026-03-08',endTime:'04:00'},{startDate:'2026-11-01',startTime:'01:30',endDate:'2026-11-01',endTime:'03:00'}])assert.notEqual((await f.call('manager','catering.create',{...facts,...patch})).status,200,JSON.stringify(patch));
 const a=await f.saved(ok(await f.call('manager','catering.create',{...facts,startDate:'2026-11-01',startTime:'01:30',startOccurrence:'earlier',endDate:'2026-11-01',endTime:'01:30',endOccurrence:'later'})));assert.equal(Date.parse(a.data.end)-Date.parse(a.data.start),3600000);
 const d=(await f.saved(await create(f))).data;assert.equal(cateringOnDate(d,'2099-09-30','America/New_York'),true);assert.equal(cateringOnDate(d,'2099-10-01','America/New_York'),true);assert.equal(cateringOnDate(d,'2099-10-02','America/New_York'),false);assert.equal(cateringOnDate({...d,end:'2099-10-01T04:00:00Z'},'2099-10-01','America/New_York'),false);
});
test('cancellation publishes a staff notice without exposing pending edits or private reasons',async t=>{
 const f=await fixture(t);let r=await publish(f);r=ok(await f.call('manager','catering.revise',{...facts,title:'PRIVATE-PENDING',note:'PRIVATE-CHANGE'},r));assert.equal((await f.call('manager','catering.cancel',{...review,summary:'Cancelled'},r)).status,403);r=ok(await f.call('owner','catering.cancel',{...review,summary:'Fixture event cancelled'},r));
 const d=(await f.view('worker')).records.find(x=>x.id===r.recordId).data;assert.equal(d.status,'cancelled');assert.equal(d.title,facts.title);assert.equal(d.notice.summary,'Fixture event cancelled');assert.doesNotMatch(JSON.stringify(d),/PRIVATE-/);assert.notEqual((await f.call('manager','catering.revise',{...facts,note:'Undo cancellation'},r)).status,200);ok(await f.call('worker','catering.acknowledge',{read:true,noticeKey:cateringNoticeKey(d)},r));
});
test('completion requires the event to end and a recorded outcome; publication rejects an expired event',async t=>{
 const f=await fixture(t);let r=await publish(f);const input={...review,summary:'Fixture reported outcome',outcomeSource:'PRIVATE-OUTCOME'};assert.equal((await f.call('manager','catering.complete',input,r)).status,400);const w=await f.view('manager'),cmd={locationId:'a',requestId:'complete',recordId:r.recordId,expectedRevision:r.revision,action:'catering.complete',input};assert.throws(()=>applyCommand(w,{...cmd,input:{...input,outcomeSource:''}},'2099-10-01T06:00:00Z'),/evidence/);assert.doesNotThrow(()=>applyCommand(w,cmd,'2099-10-01T06:00:00Z'));
 r=ok(await f.call('manager','catering.create',{...facts,startDate:'2026-01-01',endDate:'2026-01-02'}));r=ok(await f.call('manager','catering.submit',review,r));assert.equal((await f.call('owner','catering.publish',review,r)).status,400);
});
test('current manager eligibility is guarded through the commit and removal cannot publish a stale assignment',async t=>{
 const f=await fixture(t);let r=await create(f);r=ok(await f.call('manager','catering.submit',review,r));let batches=0;const binding={withSession:()=>({prepare:(...a)=>f.db.prepare(...a),batch:async statements=>{if(++batches===2)await f.db.prepare("UPDATE memberships SET active=0,revision=revision+1 WHERE id='manager'").run();return f.db.batch(statements)}})};assert.equal((await f.call('owner','catering.publish',review,r,{},binding)).status,409);assert.equal((await f.saved(r)).data.status,'review');assert.notEqual((await f.call('owner','catering.publish',review,r)).status,200);r=ok(await f.call('owner','catering.revise',{...facts,managerId:'othermanager',note:'Current manager reassignment'},r));assert.equal((await f.saved(r)).ownerId,'othermanager');
});
test('retry receipts, stale revisions and transaction failures preserve one exact event publication',async t=>{
 const f=await fixture(t);let r=ok(await f.call('manager','catering.create',facts,undefined,{requestId:'event-once'}));assert.deepEqual(ok(await f.call('manager','catering.create',facts,undefined,{requestId:'event-once'})),r);const old=r;r=ok(await f.call('manager','catering.submit',review,r));assert.equal((await f.call('owner','catering.publish',review,old)).status,409);await f.db.prepare("CREATE TRIGGER fail_catering BEFORE INSERT ON command_receipts WHEN NEW.request_id='event-fail' BEGIN SELECT RAISE(ABORT,'fixture rollback'); END").run();assert.equal((await f.call('owner','catering.publish',review,r,{requestId:'event-fail'})).status,503);assert.equal((await f.saved(r)).data.status,'review');const before=r;r=ok(await f.call('owner','catering.publish',review,r,{requestId:'publish-once'}));assert.deepEqual(ok(await f.call('owner','catering.publish',review,before,{requestId:'publish-once'})),r);assert.equal((await f.saved(r)).data.internal.history.filter(h=>h.action==='publish').length,1);
});
test('filed cancelled events preserve staff notices with private history restricted and owner restoration',async t=>{
 const f=await fixture(t);let r=await publish(f);r=ok(await f.call('owner','catering.cancel',{...review,summary:'Fixture cancellation'},r));await f.db.prepare("UPDATE records SET updated_at='2026-01-01T00:00:00Z' WHERE id=?").bind(r.recordId).run();const p=ok(await f.request('owner','/api/history?locationId=a&preview=1&before=2026-08-01'));ok(await f.request('owner','/api/history',{locationId:'a',requestId:'file-event',action:'archive',confirmed:true,before:'2026-08-01',workspaceRevision:p.workspaceRevision,records:p.records.map(({id,revision})=>({id,revision}))}));const peer=ok(await f.request('worker','/api/history?locationId=a&recordId='+r.recordId));assert.doesNotMatch(JSON.stringify(peer),/PRIVATE-/);assert.equal((await f.request('worker','/api/history?locationId=a&restore='+r.recordId)).status,403);const restore=ok(await f.request('owner','/api/history?locationId=a&restore='+r.recordId));ok(await f.request('owner','/api/history',{locationId:'a',requestId:'restore-event',action:'restore',confirmed:true,recordId:r.recordId,workspaceRevision:restore.workspaceRevision,records:restore.records.map(({id,revision})=>({id,revision}))}));assert.equal((await f.saved(r)).data.status,'cancelled');
});
