import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {Miniflare} from 'miniflare';
process.env.MINIFLARE_REGISTRY_PATH??=path.resolve('.wrangler/registry');

test('compiled permit renewal route keeps checked source snapshots, scoped access and an exact retry receipt',async t=>{
 let outbound=0;const mf=new Miniflare({modules:true,scriptPath:path.resolve('dist/server/index.js'),modulesRoot:path.resolve('dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js']}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],serviceBindings:{ASSETS:()=>new Response('Missing',{status:404})},outboundService:()=>{outbound++;throw Error('No outbound expected')}});t.after(()=>mf.dispose());
 const db=await mf.getD1Database('DB');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())await db.batch(fs.readFileSync('drizzle/'+f,'utf8').split('--> statement-breakpoint').filter(s=>s.trim()).map(s=>db.prepare(s)));
 for(const id of ['a','b'])await db.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').bind(id,'Fictional '+id,'America/New_York').run();
 for(const [id,caps,loc='a'] of [['owner',['location.manage']],['manager',['tasks.manage']],['worker',[]],['foreign',['location.manage'],'b']])await db.prepare("INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications,active) VALUES(?,?,?,?,?,'BOH','Manager',?,'[]',1)").bind(id,id+'@example.test',id+'-identity',loc,'Fictional '+id,JSON.stringify(caps)).run();
 const headers=id=>({'oai-authenticated-user-id':id+'-identity','oai-authenticated-user-email':id+'@example.test',Origin:'http://localhost','Content-Type':'application/json'});
 const call=async(id,action,input={},record,requestId=crypto.randomUUID())=>{const res=await mf.dispatchFetch('http://localhost/api/workspace',{method:'POST',headers:headers(id),body:JSON.stringify({locationId:'a',requestId,action,input,...(record?{recordId:record.recordId,expectedRevision:record.revision}:{})})});return {status:res.status,data:await res.json()}};
 const ok=r=>{assert.equal(r.status,200,JSON.stringify(r.data));return r.data};
 const view=async(id='owner')=>{const res=await mf.dispatchFetch('http://localhost/api/workspace?locationId=a',{headers:headers(id)});assert.equal(res.status,200);return res.json()};
 const facts={title:'Fictional earlier permit',type:'permit',authority:'Fictional authority',reference:'FIX-PERMIT-1',documentDate:'2026-01-01',dueDate:'2026-09-01',evidence:'Fixture source page 1; not operating evidence.',sourceUrl:'https://example.test/source',summary:'Fictional permit scope',responsibleId:'owner'};
 let earlier=ok(await call('owner','compliance.create',facts));earlier=ok(await call('owner','compliance.review',{note:'Fixture source checked',sourceChecked:true},earlier));
 const newerFacts={...facts,title:'Fictional newer permit',reference:'FIX-PERMIT-2',documentDate:'2026-09-01',dueDate:'2027-09-01'};
 let newer=ok(await call('owner','compliance.create',newerFacts));newer=ok(await call('owner','compliance.review',{note:'Fixture newer source checked',sourceChecked:true},newer));
 const input={previousId:earlier.recordId,previousRevision:earlier.revision,note:'Fixture page 2 establishes the renewal relationship',confirmed:true};
 for(const id of ['manager','worker','foreign'])assert.equal((await call(id,'compliance.renewal-link',input,newer)).status,403);
 assert.equal((await call('owner','compliance.renewal-link',{...input,previousRevision:1},newer)).status,409);
 const before=await view();const linked=ok(await call('owner','compliance.renewal-link',input,newer,'compiled-permit-renewal'));
 assert.deepEqual(ok(await call('owner','compliance.renewal-link',input,newer,'compiled-permit-renewal')),linked);
 let current=await view();let saved=current.records.find(r=>r.id===newer.recordId);
 assert.deepEqual(current.records.find(r=>r.id===earlier.recordId),before.records.find(r=>r.id===earlier.recordId));
 assert.equal(saved.data.renewalHistory.length,1);assert.equal(saved.data.renewal.previousFacts.reference,'FIX-PERMIT-1');assert.equal(saved.data.renewal.currentFacts.dueDate,'2027-09-01');assert.equal(saved.data.status,'tracking');
 earlier=ok(await call('owner','compliance.correct',{...facts,evidence:'Fixture corrected page 1',note:'Fixture transcription correction'},earlier));
 assert.equal((await call('owner','compliance.renewal-link',{...input,previousRevision:earlier.revision},linked)).status,400);
 earlier=ok(await call('owner','compliance.review',{note:'Fixture corrected source checked',sourceChecked:true},earlier));
 newer=ok(await call('owner','compliance.renewal-link',{...input,previousRevision:earlier.revision},linked));
 newer=ok(await call('owner','compliance.renewal-clear',{note:'Fixture relationship correction'},newer));
 current=await view();saved=current.records.find(r=>r.id===newer.recordId);
 assert.equal(saved.data.renewal,null);assert.deepEqual(saved.data.renewalHistory.map(e=>e.action),['linked','rechecked','cleared']);assert.equal(saved.data.renewalHistory[0].link.previousFacts.evidence,facts.evidence);assert.equal(saved.data.renewalHistory[1].link.previousFacts.evidence,'Fixture corrected page 1');
 assert.equal(current.records.length,2);assert.equal(saved.data.dueDate,newerFacts.dueDate);assert.equal((await db.prepare("SELECT count(*) n FROM command_receipts WHERE request_id='compiled-permit-renewal'").first()).n,1);
 for(const id of ['manager','worker'])assert.equal((await view(id)).records.length,0);
 assert.equal(outbound,0);
});
