import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {Miniflare} from 'miniflare';
process.env.MINIFLARE_REGISTRY_PATH??=path.resolve('.wrangler/registry');
test('compiled equipment register binds service to checked asset versions and restaurant permissions',async t=>{
 let outbound=0;const mf=new Miniflare({modules:true,scriptPath:path.resolve('dist/server/index.js'),modulesRoot:path.resolve('dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js']}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],serviceBindings:{ASSETS:()=>new Response('Missing',{status:404})},outboundService:()=>{outbound++;throw Error('No outbound expected')}});t.after(()=>mf.dispose());
 const db=await mf.getD1Database('DB');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())await db.batch(fs.readFileSync('drizzle/'+f,'utf8').split('--> statement-breakpoint').filter(s=>s.trim()).map(s=>db.prepare(s)));
 for(const id of ['a','b'])await db.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').bind(id,'Fictional '+id,'America/New_York').run();
 for(const [id,caps,loc='a'] of [['owner',['location.manage']],['manager',['tasks.manage']],['worker',[]],['foreign',['location.manage'],'b']])await db.prepare("INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications,active) VALUES(?,?,?,?,?,'BOH','Manager',?,'[]',1)").bind(id,id+'@example.test',id+'-identity',loc,'Fictional '+id,JSON.stringify(caps)).run();
 const headers=id=>({'oai-authenticated-user-id':id+'-identity','oai-authenticated-user-email':id+'@example.test',Origin:'http://localhost','Content-Type':'application/json'});
 const call=async(id,action,input={},record,requestId=crypto.randomUUID())=>{const res=await mf.dispatchFetch('http://localhost/api/workspace',{method:'POST',headers:headers(id),body:JSON.stringify({locationId:'a',requestId,action,input,...(record?{recordId:record.recordId,expectedRevision:record.revision}:{})})});return {status:res.status,data:await res.json()}};
 const ok=r=>{assert.equal(r.status,200,JSON.stringify(r.data));return r.data};
 const view=async()=>{const res=await mf.dispatchFetch('http://localhost/api/workspace?locationId=a',{headers:headers('owner')});assert.equal(res.status,200);return res.json()};

 const asset={title:'Fictional oven',assetTag:'FIX-OVEN-1',placement:'Test kitchen',model:'Fixture model',serial:'Fixture serial',sourceRef:'Fixture label',note:'Fixture physical asset checked',checked:true};
 let a=ok(await call('owner','equipment.create',asset));
 const facts={title:'Fictional service',equipment:'FIX-OVEN-1',task:'Fixture source task',sourceRef:'Fixture manual',initialDue:'2026-01-01',intervalDays:30,warningDays:7,managerId:'manager',checked:true,note:'Fixture checked',assetId:a.recordId,assetRevision:a.revision};
 for(const id of ['manager','worker','foreign'])assert.equal((await call(id,'equipment.create',asset)).status,403);
 let r=ok(await call('owner','maintenance.create',facts));
 const service={date:'2026-09-01',performedBy:'Fixture technician',evidence:'Fixture report',note:'Fixture task complete',completed:true};
 r=ok(await call('manager','maintenance.service',service,r));
 a=ok(await call('owner','equipment.revise',{...asset,placement:'Test east kitchen'},a));
 assert.equal((await call('manager','maintenance.service',{...service,date:'2026-09-02'},r)).status,409);
 assert.equal((await call('owner','maintenance.revise',facts,r)).status,409);
 r=ok(await call('owner','maintenance.revise',{...facts,assetRevision:a.revision},r));
 let next=ok(await call('manager','maintenance.service',{...service,date:'2026-09-02'},r,'checked-asset-service'));
 assert.deepEqual(ok(await call('manager','maintenance.service',{...service,date:'2026-09-02'},r,'checked-asset-service')),next);
 let saved=(await view()).records.find(x=>x.id===r.recordId);
 assert.equal(saved.data.services[0].plan.asset.facts.placement,'Test kitchen');assert.equal(saved.data.services[1].plan.asset.facts.placement,'Test east kitchen');
 a=ok(await call('owner','equipment.retire',{note:'Fixture retirement'},a));
 assert.equal((await call('manager','maintenance.service',{...service,date:'2026-09-03'},next)).status,409);
 assert.equal((await call('owner','equipment.create',asset)).status,409);
 const history=async(actor,params={},body)=>{const response=await mf.dispatchFetch('http://localhost/api/history?'+new URLSearchParams({locationId:'a',...params}),{headers:headers(actor),...(body?{method:'POST',body:JSON.stringify(body)}:{})});return {status:response.status,data:await response.json()}};
 await db.prepare("UPDATE records SET updated_at='2026-01-01T12:00:00Z'").run();
 assert.equal(ok(await history('owner',{preview:'1',before:'2026-05-01'})).records.length,0);
 next=ok(await call('owner','maintenance.retire',{note:'Fixture plan retirement'},next));await db.prepare("UPDATE records SET updated_at='2026-01-01T12:00:00Z'").run();
 const preview=ok(await history('owner',{preview:'1',before:'2026-05-01'}));assert.deepEqual(preview.records.map(x=>x.id),[r.recordId,a.recordId]);
 const filing={locationId:'a',requestId:'compiled-equipment-file',action:'archive',confirmed:true,before:'2026-05-01',workspaceRevision:preview.workspaceRevision,records:preview.records.map(({id,revision})=>({id,revision}))};const receipt=ok(await history('owner',{},filing));assert.deepEqual(ok(await history('owner',{},filing)),receipt);
 assert.equal((await view()).records.length,0);assert.equal(ok(await history('owner',{kind:'equipment'})).items.length,1);assert.equal(ok(await history('manager',{kind:'equipment'})).items.length,0);assert.equal((await history('foreign',{kind:'equipment'})).status,403);
 const detail=ok(await history('owner',{recordId:a.recordId}));assert.equal(detail.workspace.records[0].data.status,'retired');assert.equal(detail.canRestore,true);assert.equal((await call('owner','equipment.create',asset)).status,409);
 const restore=ok(await history('owner',{restore:r.recordId}));assert.equal(restore.records.length,2);ok(await history('owner',{}, {locationId:'a',requestId:'compiled-equipment-restore',action:'restore',confirmed:true,recordId:r.recordId,workspaceRevision:restore.workspaceRevision,records:restore.records.map(({id,revision})=>({id,revision}))}));
 const afterRestore=await view();assert.ok(afterRestore.records.every(x=>x.data.status==='retired'));assert.equal(afterRestore.records.find(x=>x.kind==='maintenance').data.services[0].plan.asset.facts.serial,'Fixture serial');
 const res=await mf.dispatchFetch('http://localhost/api/workspace?locationId=a',{headers:headers('worker')});
 const worker=await res.json();assert.ok(!worker.records.some(x=>x.kind==='equipment'||x.kind==='maintenance'));assert.equal(outbound,0);
});
