import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
for(const name of ['food-replacement-return','food-replacement','food-receiving-queue']){const js=ts.transpileModule(fs.readFileSync(`app/team/${name}.tsx`,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText.replace(/from '(\.\.?\/[^']+)'/g,"from '$1.mjs'");fs.mkdirSync('.sites-runtime/team',{recursive:true});fs.writeFileSync(`.sites-runtime/team/${name}.mjs`,js)}
const {ReplacementReturns,ReplacementReturnHistory}=await import('../.sites-runtime/team/food-replacement-return.mjs'),{ReplacementHistory}=await import('../.sites-runtime/team/food-replacement.mjs'),{DeliveryInvoiceCard,validReceivingQueue}=await import('../.sites-runtime/team/food-receiving-queue.mjs');
const w={location:{id:'a',timezone:'America/New_York'},me:{id:'manager',area:'BOH',capabilities:['tasks.manage']},members:[]},r={id:'item',locationId:'a',revision:5},invoice={invoiceNumber:'INV',lineReference:'1',quantity:80,supplierPackQuantity:2,invoiceUnit:'lb',sku:{vendor:'Fixture',packCount:8,unitQty:5,unitUOM:'lb',purchaseUnit:'case'}},replacement={receivingRevision:3,receiving:{invoice,deliveryReference:'ORIGINAL',receivedDate:'2026-09-28',rejected:10},quantity:10,invoiceUnit:'lb',supplierPacks:.25,receivedDate:'2026-09-28',deliveryReference:'REPLACEMENT',by:'manager',at:'2026-09-28T12:00:00Z',evidence:'Fictional arrival'},entry={revision:4,event:{replacement},replacementReturned:{entries:1,quantity:2}},props={entry,r,w,send(){},busy:false},render=(component,p=props)=>renderToStaticMarkup(React.createElement(component,p));
test('replacement return form explains the physical remainder, hides invalid sources and protects linked arrivals',()=>{
 const html=render(ReplacementReturns);assert.match(html,/2 lb returned/);assert.match(html,/8 lb not recorded as returned/);assert.match(html,/does not reopen the original replacement allowance/);assert.match(html,/Record actual replacement goods return/);
 assert.doesNotMatch(render(ReplacementReturns,{...props,entry:{...entry,replacementReturned:{entries:2,quantity:10}}}),/Record actual replacement goods return/);
 for(const changes of [{entry:{...entry,replacementVoided:{}}},{w:{...w,me:{id:'worker',area:'BOH',capabilities:[]}}},{r:{...r,locationId:'b'}}])assert.equal(render(ReplacementReturns,{...props,...changes}),'');
 const source=render(ReplacementHistory);assert.match(source,/Actual supplier pickups are linked/);assert.match(source,/<button disabled="">Void incorrect replacement/);
});
test('replacement pickup history preserves snapshots and escaped text with recorder/reviewer-only correction',()=>{
 const e={revision:5,event:{replacementReturn:{replacement,quantity:1e-8,supplierPacks:2.5e-10,invoiceUnit:'lb',returnReference:'R1',returnDate:'2026-09-29',by:'buyer',at:'2026-09-29T12:00:00Z',reason:'Fictional defect',evidence:'<script>test</script>'}}};
 const html=render(ReplacementReturnHistory,{...props,entry:e});assert.match(html,/&lt;0.000001 lb physically returned/);assert.match(html,/&lt;script&gt;/);assert.match(html,/Original pack: 8 × 5 lb/);assert.doesNotMatch(html,/<script>|Void incorrect pickup record/);
 const owner={...w,me:{id:'owner',capabilities:['location.manage']}};assert.match(render(ReplacementReturnHistory,{...props,w:owner,entry:e}),/Void incorrect pickup record/);
 const corrected=render(ReplacementReturnHistory,{...props,w:owner,entry:{...e,replacementReturnVoided:{by:'owner',at:'2026-09-29T14:00:00Z',reason:'Wrong ticket'}}});assert.match(corrected,/Pickup record voided/);assert.match(corrected,/Wrong ticket/);assert.doesNotMatch(corrected,/Void incorrect pickup record/);
});
test('delivery queue presents later returns separately and rejects older responses with missing return evidence',()=>{
 const e={sequence:1,recordId:'item',invoiceRevision:2,currentTitle:'Fixture',controlNumber:'A',invoice,accepted:70,rejected:10,remaining:0,receipts:1,replacementQuantity:10,replacementEntries:1,replacementRemaining:0,replacementReturned:2,replacementReturnEntries:1,extraEntries:0,voided:false};
 const html=render(DeliveryInvoiceCard,{entry:e,onOpen(){}});assert.match(html,/10 lb accepted replacements/);assert.match(html,/2 lb of recorded replacement arrivals were later returned/);assert.match(html,/do not reduce the arrival total or reopen its allowance/);
 const page={entries:[e],totals:{unreplaced:0,replacements:1},total:1,revision:1,next:null};assert.equal(validReceivingQueue(page),true);for(const change of [{replacementReturned:undefined},{replacementReturned:NaN},{replacementReturnEntries:.5},{replacementReturned:-1}])assert.equal(validReceivingQueue({...page,entries:[{...e,...change}]}),false);
});
