import test from 'node:test';import assert from 'node:assert/strict';import {fixture,ok} from './maintenance-meter-fixture.mjs';
import {rawItem,importInput,invoiceInput,receivingInput} from './food-excess-fixture.mjs';
process.env.JMAX_METER_COMPILED='1';
const pickup={replacementRevision:4,returnReference:'FICTIONAL-PICKUP',returnDate:'2026-09-29',quantity:2,invoiceUnit:'lb',reason:'Fictional later defect',evidence:'Fictional supplier pickup ticket',confirmed:true};
async function setup(t){const f=await fixture(t),post=(actor,loc,action,input,record,extra={})=>f.request(actor,'/api/food',{locationId:loc,requestId:crypto.randomUUID(),action,input,...(record?{recordId:record.recordId,expectedRevision:record.revision}:{}),...extra}),get=(actor,loc,params={})=>f.request(actor,'/api/food?'+new URLSearchParams({locationId:loc,dataset:'demo',view:'receiving',filter:'replacements',...params}));
 const records={};for(const [actor,loc] of [['owner','a'],['foreign','b'],['third','c']]){const item=ok(await post(actor,loc,'fooditem.import',{...importInput([rawItem]),destinationLocationId:loc})),invoice=ok(await post(actor,loc,'fooditem.invoice',invoiceInput,item)),receipt=ok(await post(actor,loc,'fooditem.receive',receivingInput(2),invoice));records[loc]=ok(await post(actor,loc,'fooditem.replacement',{receivingRevision:3,deliveryReference:'FICTIONAL-REPLACEMENT',receivedDate:'2026-09-28',quantity:10,invoiceUnit:'lb',evidence:'Fictional accepted arrival',confirmed:true},receipt));}return {...f,post,get,records};}
test('compiled replacement pickups isolate all three restaurants, preserve arrival balances and reject stale revisions',async t=>{
 const f=await setup(t);assert.equal((await f.post('worker','a','fooditem.replacement-return',pickup,f.records.a)).status,403);assert.equal((await f.post('foreign','a','fooditem.replacement-return',pickup,f.records.a)).status,403);assert.equal((await f.post('foreign','b','fooditem.replacement-return',pickup,f.records.a)).status,404);
 for(const [actor,loc] of [['manager','a'],['foreign','b'],['third','c']]){const saved=ok(await f.post(actor,loc,'fooditem.replacement-return',pickup,f.records[loc]));assert.equal((await f.post(actor,loc,'fooditem.replacement-return',{...pickup,returnReference:'STALE'},f.records[loc])).status,409);const q=ok(await f.get(actor,loc));assert.equal(q.total,1);assert.equal(q.entries[0].replacementReturned,2);assert.equal(q.entries[0].replacementQuantity,10);assert.equal(q.entries[0].replacementRemaining,0);assert.equal(ok(await f.get(actor,loc,{dataset:'operating'})).total,0);f.records[loc]=saved;}
 await f.db.prepare("UPDATE memberships SET active=0,revision=revision+1 WHERE id='manager'").run();assert.equal((await f.post('manager','a','fooditem.replacement-return',{...pickup,returnReference:'REVOKED'},f.records.a)).status,403);
});
test('compiled pickup corrections retain original facts and prevent removing a live return source',async t=>{
 const f=await setup(t),saved=ok(await f.post('manager','a','fooditem.replacement-return',pickup,f.records.a));assert.equal((await f.post('owner','a','fooditem.replacement-void',{replacementRevision:4,reason:'Blocked source'},saved)).status,409);
 const corrected=ok(await f.post('owner','a','fooditem.replacement-return-void',{returnRevision:saved.revision,reason:'Wrong pickup ticket'},saved));assert.equal(ok(await f.get('owner','a')).entries[0].replacementReturned,0);
 const history=ok(await f.get('owner','a',{view:'history',recordId:saved.recordId})).entries;assert.equal(history.find(e=>e.revision===saved.revision).event.replacementReturn.quantity,2);assert.equal(history.find(e=>e.revision===saved.revision).replacementReturnVoided.reason,'Wrong pickup ticket');ok(await f.post('owner','a','fooditem.replacement-void',{replacementRevision:4,reason:'Incorrect arrival'},corrected));
});
