import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
for(const name of ['food-replacement-return','food-replacement','food-return','food-receiving']){const js=ts.transpileModule(fs.readFileSync(`app/team/${name}.tsx`,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText.replace(/from '(\.\.?\/[^']+)'/g,"from '$1.mjs'");fs.mkdirSync('.sites-runtime/team',{recursive:true});fs.writeFileSync(`.sites-runtime/team/${name}.mjs`,js)}
const {ReceivingReplacements,ReplacementHistory}=await import('../.sites-runtime/team/food-replacement.mjs'),{ReceivingHistory}=await import('../.sites-runtime/team/food-receiving.mjs');
const w={location:{id:'a',timezone:'America/New_York'},me:{id:'manager',area:'BOH',capabilities:['tasks.manage']},members:[]},r={id:'item',locationId:'a',revision:4,data:{source:{dataset:'demo'}}},invoice={invoiceNumber:'I',lineReference:'1',invoiceUnit:'lb',sku:{vendor:'Fixture',vendorSku:'A',packCount:8,unitQty:5,unitUOM:'lb',purchaseUnit:'case'}},receiving={invoice,receivedDate:'2026-09-28',deliveryReference:'D1',accepted:70,rejected:10,by:'manager',at:'2026-09-28T12:00:00Z'},entry={revision:3,event:{receiving},receivingReplacements:{entries:1,quantity:4}},props={w,r,entry,send(){},busy:false};
test('replacement entry shows exact remaining evidence, guards role/store and hides fulfilled or voided sources',()=>{
 const render=p=>renderToStaticMarkup(React.createElement(ReceivingReplacements,p)),html=render(props);assert.match(html,/4 of 10 lb/);assert.match(html,/6 lb has no accepted replacement/);assert.match(html,/Record accepted replacement/);assert.match(html,/does not place an order/);
 assert.equal(render({...props,w:{...w,me:{id:'worker',area:'BOH',capabilities:[]}}}),'');assert.equal(render({...props,r:{...r,locationId:'b'}}),'');assert.equal(render({...props,entry:{...entry,receivingVoided:{}}}),'');
 const all=render({...props,entry:{...entry,receivingReplacements:{entries:2,quantity:10}}});assert.match(all,/All rejected quantity/);assert.doesNotMatch(all,/Record accepted replacement/);
});
test('original receiving correction is disabled when replacements are linked',()=>{const html=renderToStaticMarkup(React.createElement(ReceivingHistory,props));assert.match(html,/<button disabled="">Void incorrect receiving entry/);assert.match(html,/Accepted replacements for rejected goods/);});
test('replacement history preserves escaped source evidence and author or reviewer correction boundaries',()=>{
 const e={revision:4,event:{replacement:{receiving,invoiceUnit:'lb',quantity:1e-8,supplierPacks:2.5e-10,deliveryReference:'R1',receivedDate:'2026-09-28',evidence:'<script>unsafe</script>',by:'buyer',at:'2026-09-28T13:00:00Z'}}},render=p=>renderToStaticMarkup(React.createElement(ReplacementHistory,p));
 const html=render({...props,entry:e});assert.match(html,/&lt;0.000001 lb accepted/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>|Void incorrect replacement/);
 const owner={...w,me:{id:'owner',capabilities:['location.manage']}};assert.match(render({...props,w:owner,entry:e}),/Void incorrect replacement/);
 const voided=render({...props,w:owner,entry:{...e,replacementVoided:{reason:'Wrong ticket',by:'owner',at:'2026-09-28T14:00:00Z'}}});assert.match(voided,/Replacement voided; original retained/);assert.doesNotMatch(voided,/Void incorrect replacement/);
});
