import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {Miniflare} from 'miniflare';
import {seedManagerFixture} from './manager-log-fixture.mjs';import {seedFoodFixture} from './food-fixture.mjs';import {seedReplacementQueueFixture} from './replacement-queue-fixture.mjs';
process.env.MINIFLARE_REGISTRY_PATH??=path.resolve('.wrangler/registry');
test('compiled delivery queue filters partial and complete replacements, reloads corrections and preserves scoped history navigation',async t=>{
 let outbound=0;const mf=new Miniflare({modules:true,scriptPath:path.resolve('dist/server/index.js'),modulesRoot:path.resolve('dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js']}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],serviceBindings:{ASSETS:()=>new Response('Missing',{status:404})},outboundService:()=>{outbound++;throw Error('No outbound')}});t.after(()=>mf.dispose());const db=await mf.getD1Database('DB');
 for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())await db.batch(fs.readFileSync(`drizzle/${file}`,'utf8').split('--> statement-breakpoint').filter(s=>s.trim()).map(s=>db.prepare(s)));
 await seedManagerFixture(db);await seedFoodFixture(db);await seedReplacementQueueFixture((url,init)=>mf.dispatchFetch(url,init));
 const headers=actor=>({'oai-authenticated-user-id':actor+'-fixture','oai-authenticated-user-email':actor+'@example.test'}),get=async(actor='boh',params={})=>{const r=await mf.dispatchFetch('https://test.example/api/food?'+new URLSearchParams({locationId:'berts',dataset:'demo',view:'receiving',filter:'unreplaced',...params}),{headers:headers(actor)});return {status:r.status,data:await r.json()}};
 const first=await get();assert.equal(first.status,200);assert.equal(first.data.total,1);assert.equal(first.data.totals.rejected,2);assert.equal(first.data.totals.unreplaced,1);assert.equal(first.data.totals.replacements,2);assert.equal(first.data.entries[0].replacementRemaining,.5);
 const all=await get('admin',{filter:'replacements'});assert.equal(all.data.total,2);assert.equal(all.data.entries[0].replacementRemaining,0);assert.equal((await get('worker')).status,403);assert.equal((await get('foh')).status,403);assert.equal((await get('admin',{dataset:'operating'})).data.total,0);assert.equal((await get('admin',{locationId:'rudds'})).data.total,0);
 const entry=first.data.entries[0],history=await get('boh',{view:'history',recordId:entry.recordId,after:String(entry.sequence-1)});assert.equal(history.status,200);assert.equal(history.data.entries[0].revision,entry.invoiceRevision);assert.equal(history.data.entries[0].event.invoiceLine.invoiceNumber,'DEMO-REPLACEMENT-SOURCE');
 const r=await mf.dispatchFetch('https://test.example/api/food',{method:'POST',headers:{...headers('admin'),Origin:'https://test.example','Content-Type':'application/json'},body:JSON.stringify({requestId:crypto.randomUUID(),locationId:'berts',recordId:entry.recordId,expectedRevision:7,action:'fooditem.replacement-void',input:{replacementRevision:7,reason:'Fictional incorrect arrival'}})});assert.equal(r.status,200);const corrected=await get();assert.equal(corrected.data.total,2);assert.equal(corrected.data.totals.replacements,1);assert.equal(corrected.data.entries[0].replacementRemaining,1);assert.equal(outbound,0);
});
