import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {Miniflare} from 'miniflare';
import {seedManagerFixture} from './manager-log-fixture.mjs';import {seedFoodFixture} from './food-fixture.mjs';import {seedReplacementFixture} from './replacement-fixture.mjs';
process.env.MINIFLARE_REGISTRY_PATH??=path.resolve('.wrangler/registry');
test('compiled Food route saves, reloads and corrects replacements without widening source, store or count scope',async t=>{
 let outbound=0;const mf=new Miniflare({modules:true,scriptPath:path.resolve('dist/server/index.js'),modulesRoot:path.resolve('dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js']}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],serviceBindings:{ASSETS:()=>new Response('Missing',{status:404})},outboundService:()=>{outbound++;throw Error('No outbound')}});t.after(()=>mf.dispose());const db=await mf.getD1Database('DB');
 for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())await db.batch(fs.readFileSync(`drizzle/${file}`,'utf8').split('--> statement-breakpoint').filter(s=>s.trim()).map(s=>db.prepare(s)));
 await seedManagerFixture(db);await seedFoodFixture(db);await seedReplacementFixture((url,init)=>mf.dispatchFetch(url,init));
 const headers=actor=>({'oai-authenticated-user-id':actor+'-fixture','oai-authenticated-user-email':actor+'@example.test'}),get=async(actor='admin',locationId='berts',dataset='demo')=>{const r=await mf.dispatchFetch('https://test.example/api/food?'+new URLSearchParams({locationId,dataset,view:'history',recordId:'demo-food-WI-001'}),{headers:headers(actor)});return {status:r.status,data:await r.json()}};
 const post=async(actor,action,input,revision,locationId='berts')=>{const r=await mf.dispatchFetch('https://test.example/api/food',{method:'POST',headers:{...headers(actor),Origin:'https://test.example','Content-Type':'application/json'},body:JSON.stringify({locationId,recordId:'demo-food-WI-001',expectedRevision:revision,requestId:crypto.randomUUID(),action,input})});return {status:r.status,data:await r.json()}};
 const fields={receivingRevision:3,deliveryReference:'DEMO-REFILL',receivedDate:'2026-09-29',invoiceUnit:'case',quantity:.5,evidence:'Fictional accepted half case',confirmed:true};
 assert.equal((await post('worker','fooditem.replacement',fields,3)).status,403);assert.equal((await post('admin','fooditem.replacement',fields,3,'rudds')).status,404);
 const saved=await post('boh','fooditem.replacement',fields,3);assert.equal(saved.status,200,JSON.stringify(saved.data));let h=(await get()).data.entries;assert.equal(h.find(e=>e.revision===3).receivingReplacements.quantity,.5);assert.equal(h.find(e=>e.revision===2).invoiceReceiving.rejected,1);assert.equal((await get('admin','berts','operating')).status,404);
 assert.equal((await post('admin','fooditem.receive-void',{receivingRevision:3,reason:'Blocked source'},saved.data.revision)).status,409);
 const corrected=await post('admin','fooditem.replacement-void',{replacementRevision:saved.data.revision,reason:'Wrong arrival ticket'},saved.data.revision);assert.equal(corrected.status,200);h=(await get()).data.entries;assert.equal(h.find(e=>e.revision===3).receivingReplacements.quantity,0);assert.equal(h.find(e=>e.revision===saved.data.revision).replacementVoided.reason,'Wrong arrival ticket');
 const original=await post('admin','fooditem.receive-void',{receivingRevision:3,reason:'Wrong rejected entry'},corrected.data.revision);assert.equal(original.status,200);assert.equal((await post('boh','fooditem.replacement',fields,original.data.revision)).status,409);assert.equal(outbound,0);
});
