import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {Miniflare} from 'miniflare';import {rawItem,importInput,invoiceInput,receivingInput,excessInput} from './food-excess-fixture.mjs';
process.env.MINIFLARE_REGISTRY_PATH??=path.resolve('.wrangler/registry');
test('compiled Food route records and corrects checked extra-goods billing links',async t=>{
 let outbound=0;const mf=new Miniflare({modules:true,scriptPath:path.resolve('dist/server/index.js'),modulesRoot:path.resolve('dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js']}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],serviceBindings:{ASSETS:()=>new Response('Missing',{status:404})},outboundService:()=>{outbound++;throw Error('No outbound')}});t.after(()=>mf.dispose());const db=await mf.getD1Database('DB');
 for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())await db.batch(fs.readFileSync(`drizzle/${file}`,'utf8').split('--> statement-breakpoint').filter(s=>s.trim()).map(s=>db.prepare(s)));
 await db.prepare("INSERT INTO locations(id,name,timezone) VALUES('a','Fixture A','America/New_York')").run();await db.prepare('INSERT INTO memberships(id,email,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?)').bind('owner','owner@example.test','a','Owner','Executive','Owner','["location.manage"]','[]').run();
 const headers={'oai-authenticated-user-id':'owner-identity','oai-authenticated-user-email':'owner@example.test'},post=async(action,input,record)=>{const response=await mf.dispatchFetch('http://localhost/api/food',{method:'POST',headers:{...headers,Origin:'http://localhost','Content-Type':'application/json'},body:JSON.stringify({locationId:'a',requestId:crypto.randomUUID(),action,input,...(record?{recordId:record.recordId,expectedRevision:record.revision}:{})})});return {status:response.status,data:await response.json()}},ok=r=>{assert.equal(r.status,200,JSON.stringify(r.data));return r.data};
 const base=ok(await post('fooditem.import',importInput([rawItem]))),invoice=ok(await post('fooditem.invoice',invoiceInput,base)),receipt=ok(await post('fooditem.receive',receivingInput(2),invoice)),extra=ok(await post('fooditem.excess',excessInput(2),receipt)),bill=ok(await post('fooditem.invoice',{...invoiceInput,invoiceNumber:'BILL-EXTRA',quantity:4,lineTotal:'10.00'},extra));
 const get=async params=>{const response=await mf.dispatchFetch('http://localhost/api/food?'+new URLSearchParams({locationId:'a',dataset:'demo',...params}),{headers});assert.equal(response.status,200);return response.json()};
 let choices=await get({view:'extra-billing',recordId:base.recordId,excessRevision:'4'});assert.equal(choices.entries.length,1);assert.equal(choices.entries[0].revision,5);assert.equal(choices.entries[0].issue,'');
 const match=ok(await post('fooditem.excess-billing',{excessRevision:4,invoiceRevision:5,quantity:2,note:'Fictional issued document bills selected extras',confirmed:true},bill));
 choices=await get({view:'extra-billing',recordId:base.recordId,excessRevision:'4'});assert.equal(choices.matched,2);assert.equal(choices.entries[0].matched,2);
 assert.equal((await post('fooditem.invoice-void',{invoiceRevision:5,reason:'Incorrect invoice'},match)).status,409);
 assert.equal((await post('fooditem.excess-void',{excessRevision:4,reason:'Incorrect extra'},match)).status,409);
 const voided=ok(await post('fooditem.excess-billing-void',{matchRevision:6,reason:'Wrong association'},match));ok(await post('fooditem.invoice-void',{invoiceRevision:5,reason:'Incorrect invoice'},voided));
 const entries=(await get({view:'history',recordId:base.recordId})).entries;assert.equal(entries.find(e=>e.revision===6).excessBillingVoided.reason,'Wrong association');assert.equal(entries.find(e=>e.revision===4).excessBilled.quantity,0);assert.equal((await get({view:'extra-billing',recordId:base.recordId,excessRevision:'4'})).entries.length,0);assert.equal(outbound,0);
});
