import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {Miniflare} from 'miniflare';import {rawItem,importInput} from './food-excess-fixture.mjs';import {localDate} from '../.sites-runtime/shared/local-time.mjs';import {wasteExportCsv} from '../.sites-runtime/shared/food-waste-export.mjs';
process.env.MINIFLARE_REGISTRY_PATH??=path.resolve('.wrangler/registry');
test('compiled route exports actual saved waste, rejects stale revisions and honors later void/role scope',async t=>{
 let outbound=0;const mf=new Miniflare({modules:true,scriptPath:path.resolve('dist/server/index.js'),modulesRoot:path.resolve('dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js']}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],serviceBindings:{ASSETS:()=>new Response('Missing',{status:404})},outboundService:()=>{outbound++;throw Error('No outbound')}});t.after(()=>mf.dispose());const db=await mf.getD1Database('DB');
 for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())await db.batch(fs.readFileSync(`drizzle/${file}`,'utf8').split('--> statement-breakpoint').filter(s=>s.trim()).map(s=>db.prepare(s)));
 await db.prepare("INSERT INTO locations(id,name,timezone) VALUES('a','Fixture A','America/New_York')").run();for(const [who,area,caps] of [['owner','Executive',['location.manage']],['manager','BOH',['tasks.manage']],['foh','FOH',['tasks.manage']]])await db.prepare('INSERT INTO memberships(id,email,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?)').bind(who,who+'@example.test','a',who,area,'Manager',JSON.stringify(caps),'[]').run();
 const headers=who=>({'oai-authenticated-user-id':who+'-identity','oai-authenticated-user-email':who+'@example.test'}),ok=async r=>{const data=await r.json();assert.equal(r.status,200,JSON.stringify(data));return data},post=(who,action,input,record)=>mf.dispatchFetch('http://localhost/api/food',{method:'POST',headers:{...headers(who),Origin:'http://localhost','Content-Type':'application/json'},body:JSON.stringify({locationId:'a',requestId:crypto.randomUUID(),action,input,...(record?{recordId:record.recordId,expectedRevision:record.revision}:{})})});
 const base=await ok(await post('owner','fooditem.import',importInput([rawItem]))),saved=await ok(await post('manager','fooditem.waste',{quantity:0.25,reason:'dropped',note:'Fictional compiled test',confirmed:true},base));const date=localDate(new Date().toISOString(),'America/New_York');const get=(who,params)=>mf.dispatchFetch('http://localhost/api/food?'+new URLSearchParams({locationId:'a',dataset:'demo',from:date,through:date,...params}),{headers:headers(who)});
 const page=await ok(await get('manager',{view:'waste'})),full=await ok(await get('manager',{view:'waste-export',revision:page.revision}));assert.equal(full.entries.length,1);assert.equal(full.totals.knownEstimatedCents,2313);assert.match(wasteExportCsv(full),/23\.13/);assert.equal((await get('foh',{view:'waste-export',revision:page.revision})).status,403);assert.equal((await ok(await get('owner',{view:'waste-export',revision:page.revision,dataset:'operating'}))).entries.length,0);
 await ok(await post('manager','fooditem.waste-void',{wasteRevision:saved.revision,reason:'Fictional correction'},saved));assert.equal((await get('owner',{view:'waste-export',revision:page.revision})).status,409);const refreshed=await ok(await get('owner',{view:'waste'})),after=await ok(await get('owner',{view:'waste-export',revision:refreshed.revision}));assert.equal(after.entries.length,1);assert.equal(after.totals.active,0);assert.equal(after.entries[0].voided,true);assert.equal(outbound,0);
});
