import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
for(const name of ['food-excess-billing','food-excess-return','food-excess']){const js=ts.transpileModule(fs.readFileSync(`app/team/${name}.tsx`,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText.replace(/from '(\.\.?\/[^']+)'/g,"from '$1.mjs'");fs.mkdirSync('.sites-runtime/team',{recursive:true});fs.writeFileSync(`.sites-runtime/team/${name}.mjs`,js)}
const {ExtraGoodsReturns,ExtraReturnHistory}=await import('../.sites-runtime/team/food-excess-return.mjs'),{ExcessHistory}=await import('../.sites-runtime/team/food-excess.mjs');
const w={location:{id:'a',timezone:'America/New_York'},me:{id:'manager',capabilities:['tasks.manage'],area:'BOH'},members:[]},r={id:'item',revision:5,data:{source:{dataset:'demo'}}},invoice={invoiceNumber:'INV',lineReference:'1',quantity:80,invoiceUnit:'lb',supplierPackQuantity:2,sku:{vendor:'Fixture',packCount:8,unitQty:5,unitUOM:'lb',purchaseUnit:'case'}},extra={invoice,invoiceRevision:2,quantity:5,supplierPacks:.125,observedDate:'2026-09-28',deliveryReference:'EXTRA',at:'2026-09-28T12:00:00Z',by:'manager',receivingAtEntry:{accepted:70,rejected:10}},entry={revision:4,event:{excess:extra},excessReturned:{entries:1,quantity:2}},props={w,r,entry,send(){},busy:false};
test('partial pickup view preserves remainder meaning and hides entry for fully returned or voided observations',()=>{
 const html=renderToStaticMarkup(React.createElement(ExtraGoodsReturns,props));assert.match(html,/2 lb returned/);assert.match(html,/3 lb not recorded as returned/);assert.match(html,/not an instruction to return goods/);assert.match(html,/Record actual extra goods return/);
 const all=renderToStaticMarkup(React.createElement(ExtraGoodsReturns,{...props,entry:{...entry,excessReturned:{entries:2,quantity:5}}}));assert.match(all,/All extra goods in this observation have recorded returns/);assert.doesNotMatch(all,/Record actual extra goods return/);
 assert.equal(renderToStaticMarkup(React.createElement(ExtraGoodsReturns,{...props,entry:{...entry,excessVoided:{}}})), '');
});
test('linked pickups disable source correction in the rendered extra observation',()=>{const html=renderToStaticMarkup(React.createElement(ExcessHistory,props));assert.match(html,/Actual pickups are linked/);assert.match(html,/<button disabled="">Void incorrect extra goods entry/);assert.match(html,/Record actual extra goods return/);});
test('pickup history preserves original units and escaped evidence, restricts void and displays retained corrections',()=>{
 const event={excessReturn:{excess:extra,quantity:1e-8,supplierPacks:2.5e-10,returnReference:'P1',returnDate:'2026-09-28',by:'buyer',at:'2026-09-28T12:00:00Z',reason:'Excess',evidence:'<script>test</script>'}},e={revision:5,event};
 const html=renderToStaticMarkup(React.createElement(ExtraReturnHistory,{...props,entry:e}));assert.match(html,/&lt;0.000001 lb physically returned/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>|Void incorrect pickup record/);assert.match(html,/Original pack: 8 × 5 lb/);
 const owner={...w,me:{id:'owner',capabilities:['location.manage']}};assert.match(renderToStaticMarkup(React.createElement(ExtraReturnHistory,{...props,w:owner,entry:e})),/Void incorrect pickup record/);
 const corrected=renderToStaticMarkup(React.createElement(ExtraReturnHistory,{...props,w:owner,entry:{...e,excessReturnVoided:{reason:'Wrong ticket',by:'owner',at:'2026-09-28T14:00:00Z'}}}));assert.match(corrected,/Pickup record voided/);assert.match(corrected,/Wrong ticket/);assert.doesNotMatch(corrected,/Void incorrect pickup record/);
});
