import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
for(const name of ['food-excess-billing','food-excess-return','food-excess','food-receiving-queue']){const js=ts.transpileModule(fs.readFileSync(`app/team/${name}.tsx`,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText.replace(/from '(\.\.?\/[^']+)'/g,"from '$1.mjs'");fs.mkdirSync('.sites-runtime/team',{recursive:true});fs.writeFileSync(`.sites-runtime/team/${name}.mjs`,js)}
const {InvoiceExcess,ExcessHistory}=await import('../.sites-runtime/team/food-excess.mjs'),{FoodReceivingQueue}=await import('../.sites-runtime/team/food-receiving-queue.mjs');
const w={location:{id:'a',timezone:'America/New_York'},me:{id:'manager',capabilities:['tasks.manage'],area:'BOH'},members:[]},r={id:'item',revision:4,data:{source:{dataset:'demo'}}},invoice={invoiceNumber:'INV',lineReference:'1',quantity:80,invoiceUnit:'lb',supplierPackQuantity:2,sku:{vendor:'Fixture',packCount:8,unitQty:5,unitUOM:'lb',purchaseUnit:'case'}},entry={revision:2,event:{invoiceLine:invoice},invoiceReceiving:{entries:1,accepted:70,rejected:10},invoiceExcess:{entries:1,quantity:5}},props={w,r,entry,send(){},busy:false};
test('extra form entry explains separate quantities and withholds entry until invoiced goods accounted',()=>{
 const full=renderToStaticMarkup(React.createElement(InvoiceExcess,props));assert.match(full,/5 lb extra/);assert.match(full,/Record extra goods/);assert.match(full,/not a supplier settlement/);
 const partial=renderToStaticMarkup(React.createElement(InvoiceExcess,{...props,entry:{...entry,invoiceReceiving:{entries:0,accepted:0,rejected:0}}}));assert.match(partial,/Complete the invoiced quantity checks/);assert.doesNotMatch(partial,/Record extra goods/);
 assert.equal(renderToStaticMarkup(React.createElement(InvoiceExcess,{...props,entry:{...entry,invoiceVoided:{}}})), '');
});
test('extra history escapes evidence, preserves small original-unit amounts and restricts correction',()=>{
 const e={revision:4,event:{excess:{invoice,quantity:0.00000001,supplierPacks:0.00000000025,deliveryReference:'T1',observedDate:'2026-09-28',evidence:'<script>bad</script>',goodsLocation:'Shelf',by:'buyer',at:'2026-09-28T12:00:00Z',receivingAtEntry:{accepted:70,rejected:10}}}},html=renderToStaticMarkup(React.createElement(ExcessHistory,{...props,entry:e}));
 assert.match(html,/&lt;0.000001 lb/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>|Void incorrect extra goods entry/);assert.match(html,/70 accepted, 10 rejected lb/);
 const owner=renderToStaticMarkup(React.createElement(ExcessHistory,{...props,w:{...w,me:{id:'owner',capabilities:['location.manage']}},entry:e}));assert.match(owner,/Void incorrect extra goods entry/);
 const voided=renderToStaticMarkup(React.createElement(ExcessHistory,{...props,entry:{...e,excessVoided:{reason:'Wrong source'}}}));assert.match(voided,/Original retained/);assert.doesNotMatch(voided,/Void incorrect extra goods entry/);
});
test('existing delivery queue exposes an extra-goods view without claiming all deliveries were captured',()=>{const html=renderToStaticMarkup(React.createElement(FoodReceivingQueue,{w,apiRoot:'/api',dataset:'demo',onOpen(){}}));assert.match(html,/value="excess">With extra goods recorded/);assert.match(html,/empty queue does not prove all deliveries were recorded/);});
