import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {localTrial,managerCaps} from './hour-trial-local-fixture.mjs';
import {handleWorkspace} from '../.sites-runtime/shared/service.mjs';
import {handleFood} from '../.sites-runtime/shared/food-service.mjs';
import {handleFoodWorkflows} from '../.sites-runtime/shared/food-workflow-service.mjs';
import {handleFoodTransfers} from '../.sites-runtime/shared/food-transfer-service.mjs';
const trialDays=Number(process.env.HOUR_TRIAL_DAYS??7);assert.ok(Number.isInteger(trialDays)&&trialDays>=7&&trialDays<=21);

test(`Commissary shared hierarchy: ${trialDays} durable production-to-destination days, interrupted retries and unreconciled partial receipts`,async()=>{
 const RealDate=Date;let now=RealDate.parse('2026-10-08T12:00:00-04:00');globalThis.Date=class extends RealDate{constructor(...a){super(...(a.length?a:[now]));}static now(){return now;}};
 const actors=[...['comm','berts','rudds','papa'].map(loc=>({id:'comm-'+loc,loc,position:'Commissary Manager',caps:managerCaps})),...['berts','rudds'].map(loc=>({id:loc+'-receiver',loc,position:'BOH Manager',caps:managerCaps})),{id:'comm-cook',loc:'comm',position:'Commissary Production Cook'}];
 const h=localTrial('commissary',actors,['comm','berts','rudds','papa']);
 // Explicit scopes bind the identities even when legacy memberships exist in every restaurant.
 // Fixture identity header differs per membership in helper; bind one shared subject for the grant.
 for(const loc of ['comm','berts','rudds','papa'])h.sqlite.prepare('UPDATE memberships SET auth_user_id=?,email=? WHERE id=?').run('production-identity','production@example.test','comm-'+loc);
 h.sqlite.prepare('INSERT INTO restaurant_access(auth_user_id,kind,home_location_id) VALUES(?,?,?)').run('production-identity','commissary','comm');
 const report={id:'commissary-hierarchy-hour-trial',days:[],cases:[],failures:[],initialSeeds:1,operationalReseeds:0,sourceRevision:h.sourceRevision,database:h.file,limits:['Fictional demo Food data installed once; authenticated handlers mutate all counts, production plans, dispatch and receipts.','No hosted Jeff recipe/forecast, physical production, physical receiving or real inventory posting is proven.','Cook/manager are functional test groupings, not new operating job titles; no personal, schedule or cash access at destinations.','Accepted, rejected, missing and still-in-transit quantities stay distinct. Source stock remains unchanged.']};
 const req=(actor,route,loc,body,query='')=>actor==='production'?new Request(`https://hour-trial.example/api/${route}?locationId=${loc}&dataset=demo${query}`,{headers:{'oai-authenticated-user-id':'production-identity','oai-authenticated-user-email':'production@example.test',Origin:'https://hour-trial.example','Content-Type':'application/json'},...(body?{method:'POST',body:JSON.stringify(body)}:{})}):h.request(actor,route,loc,body,'&dataset=demo'+query);
 const call=async(handler,actor,loc,body,route='food/workflows',query='')=>{const r=await handler(req(actor,route,loc,body,query),h.db);return{status:r.status,data:await r.json()};};
 const cmd=(handler,actor,loc,action,input={},record,rid=crypto.randomUUID(),route)=>call(handler,actor,loc,{locationId:loc,requestId:rid,action,input:{dataset:'demo',...input},...(record?{recordId:record.recordId??record.id,expectedRevision:record.revision}:{})},route);
 const food=(actor,loc,action,input,record)=>cmd(handleFood,actor,loc,action,input,record,undefined,'food');
 const wf=(actor,loc,action,input,record,rid)=>cmd(handleFoodWorkflows,actor,loc,action,input,record,rid);
 const tx=(actor,loc,action,input,record,rid)=>cmd(handleFoodTransfers,actor,loc,action,input,record,rid,'food/transfers');
 const detail=(loc,r)=>call(handleFoodTransfers,loc+'-receiver',loc,undefined,'food/transfers','&recordId='+r.recordId).then(h.ok);
 const check=async(name,fn)=>{try{await fn();report.cases.push({name,status:'passed'});}catch(e){report.failures.push({name,error:String(e.stack)});throw e;}};
 const items={};let previousPartial,previousLoc;report.plannedDays=trialDays;report.receiptContinuations=[];
 try{
  for(const loc of ['comm','berts','rudds'])items[loc]=h.ok(await food(loc==='comm'?'production':loc+'-receiver',loc,'fooditem.import',{sourceRestaurantId:'fictional-'+loc,sourceLabel:'Local hierarchy trial only',destinationLocationId:loc,confirmed:true,rows:[{restaurantId:'fictional-'+loc,name:'Fictional ranch vessels',controlNumber:'RANCH',purchaseUnit:'vessel',packCount:1,unitQty:5,unitUOM:'gal',portionSize:1,portionUOM:'gal',par:6,active:true,countActive:true,needsReview:false,vendorSkus:[]}]}));
  const def=h.ok(await wf('production','comm','definition.save',{foodRecordId:items.comm.recordId,foodRevision:items.comm.revision,track:'bulk',countUnit:'vessel',par:6,reviewNote:'Reviewed fictional vessel counts, six five-gallon vessels. No tub conversion invented.',confirmed:true}));
  for(const loc of ['berts','rudds','papa'])h.sqlite.prepare('INSERT INTO food_transfer_routes(source_id,destination_id,dataset,active) VALUES(?,?,?,1)').run('comm',loc,'demo');
  const stock=JSON.stringify(h.sqlite.prepare('SELECT * FROM food_records ORDER BY id').all());
  for(let day=1;day<=trialDays;day++){
   const start=now,date=new Date(now).toISOString().slice(0,10),targetDate=new Date(now+86400000).toISOString().slice(0,10),loc=day%2?'berts':'rudds',other=loc==='berts'?'rudds':'berts';report.days.push({day,week:Math.ceil(day/7),receivingRestaurant:loc,curveball:['Interrupted retry','Wrong receiver','Production shortfall','Part arrival','Rejected vessel','Invalid recount','Week-boundary continuation'][(day-1)%7]});
   await check(`day ${day}: previous partial receipt survives next opening and cannot be silently voided`,async()=>{h.reopen();if(previousPartial){const pending=await detail(previousLoc,previousPartial);assert.equal(pending.transfer.status,'sent');assert.equal(pending.transfer.receipt.complete,false);assert.equal(pending.transfer.receipt.missing,0);const before=h.snapshot();assert.equal((await tx('production','comm','transfer.void',{reason:'Do not hide yesterday incomplete delivery'},previousPartial)).status,409);assert.equal(h.snapshot(),before);previousPartial=h.ok(await tx(previousLoc+'-receiver',previousLoc,'transfer.check-progress',{accepted:4,rejected:1,missing:0,complete:true,receivedAt:new Date(now).toISOString(),note:'Remaining goods arrived; one rejected in fixture',reason:'One rejected vessel',confirmed:true},previousPartial));assert.equal((await detail(previousLoc,previousPartial)).transfer.receipt.rejected,1);report.receiptContinuations.push({day,previousDay:day-1,transferId:previousPartial.recordId,crossWeek:(day-1)%7===0,accepted:4,rejected:1,missing:0});}});
   let count,plan;
   await check(`day ${day}: count, planned quantity and actual short production are separate saved facts`,async()=>{
    count=h.ok(await wf('production','comm','count.create',{track:'bulk',businessDate:date}));count=h.ok(await wf('production','comm','count.save',{lines:[{definitionId:def.recordId,quantity:1,note:'Fictional current count, one vessel'}]},count));count=h.ok(await wf('production','comm','count.submit',{confirmed:true},count));plan=h.ok(await wf('production','comm','plan.generate',{countId:count.recordId,countRevision:count.revision,targetDate}));plan=h.ok(await wf('production','comm','plan.release',{confirmed:true},plan));const original=plan,rid='short-production-'+day,input={definitionId:def.recordId,quantity:4,note:'Short one vessel: ingredient shortage remains in actual production note.',confirmed:true};plan=h.ok(await wf('production','comm','plan.complete',input,plan,rid));h.reopen();assert.deepEqual(h.ok(await wf('production','comm','plan.complete',input,original,rid)),plan);const saved=h.ok(await call(handleFoodWorkflows,'production','comm',undefined,'food/workflows','&recordId='+plan.recordId));assert.equal(saved.record.lines[0].plannedQty,5);assert.equal(saved.record.lines[0].completedQty,4);assert.match(saved.record.lines[0].completionNote,/Short one/);
   });
   now=start+2*3600000;let sent;
   await check(`day ${day}: dispatch lost response retries do not create second shipment`,async()=>{const rid='lost-response-dispatch-'+day,input={destinationId:loc,itemId:items.comm.recordId,itemRevision:items.comm.revision,reference:'FICTIONAL-TRIP-'+day,quantity:5,dispatchedAt:new Date(now).toISOString(),note:'Recorded dispatch includes existing stock plus current actual production; not a stock posting.',confirmed:true};sent=h.ok(await tx('production','comm','transfer.dispatch',input,undefined,rid));const countBefore=h.sqlite.prepare('SELECT count(*) AS n FROM food_transfers').get().n;h.reopen();assert.deepEqual(h.ok(await tx('production','comm','transfer.dispatch',input,undefined,rid)),sent);assert.equal(h.sqlite.prepare('SELECT count(*) AS n FROM food_transfers').get().n,countBefore);});
   await check(`day ${day}: wrong destination and low-privilege cook cannot receive or dispatch`,async()=>{let before=h.snapshot();assert.ok([403,404].includes((await tx(other+'-receiver',other,'transfer.receive',{accepted:5,rejected:0,missing:0,complete:true,receivedAt:new Date(now).toISOString(),note:'Wrong restaurant',reason:'',confirmed:true},sent)).status));assert.equal(h.snapshot(),before);assert.equal((await tx('production','comm','transfer.receive',{accepted:5,rejected:0,missing:0,complete:true,receivedAt:new Date(now).toISOString(),note:'Source cannot sign destination check',reason:'',confirmed:true},sent)).status,403);assert.equal(h.snapshot(),before);assert.equal((await tx('comm-cook','comm','transfer.dispatch',{destinationId:loc,itemId:items.comm.recordId,itemRevision:items.comm.revision,reference:'UNAUTHORIZED-'+day,quantity:1,dispatchedAt:new Date(now).toISOString(),note:'Cannot dispatch without Food permissions',confirmed:true})).status,403);assert.equal(h.snapshot(),before);});
   await check(`day ${day}: partial receiving cannot exceed dispatch or shrink saved arrivals`,async()=>{
    const before=h.snapshot();assert.equal((await tx(loc+'-receiver',loc,'transfer.receive',{accepted:6,rejected:0,missing:0,complete:true,receivedAt:new Date(now).toISOString(),note:'Impossible quantity',reason:'',confirmed:true},sent)).status,400);assert.equal(h.snapshot(),before);
    sent=h.ok(await tx(loc+'-receiver',loc,'transfer.receive',{accepted:2,rejected:0,missing:0,complete:false,receivedAt:new Date(now).toISOString(),note:'Only first two vessels arrived; three still pending.',reason:'',confirmed:true},sent));const after=h.snapshot();assert.equal((await tx(loc+'-receiver',loc,'transfer.check-progress',{accepted:1,rejected:0,missing:0,complete:false,receivedAt:new Date(now).toISOString(),note:'Cannot silently reduce count',reason:'',confirmed:true},sent)).status,409);assert.equal(h.snapshot(),after);const saved=await detail(loc,sent);assert.equal(saved.transfer.status,'sent');assert.equal(saved.transfer.receipt.accepted,2);assert.equal(saved.transfer.receipt.missing,0);previousPartial=sent;previousLoc=loc;
   });
   await check(`day ${day}: commissary route does not grant Papa personnel or general restaurant access`,async()=>{const before=h.snapshot();for(const dest of ['berts','rudds']){assert.equal((await call(handleWorkspace,'production',dest,undefined,'workspace')).status,403);assert.equal((await call(handleFoodWorkflows,'production',dest)).status,200);}assert.equal((await call(handleFoodWorkflows,'production','papa')).status,403);assert.equal((await tx('production','comm','transfer.dispatch',{destinationId:'papa',itemId:items.comm.recordId,itemRevision:items.comm.revision,reference:'PAPA-DENIED-'+day,quantity:1,dispatchedAt:new Date(now).toISOString(),note:'Configured route is not authorization',confirmed:true})).status,403);assert.equal(h.snapshot(),before);assert.equal(JSON.stringify(h.sqlite.prepare('SELECT * FROM food_records ORDER BY id').all()),stock,'Counts, plans, actual production and receipts must not silently post inventory twice.');});
   now=start+86400000;
  }
  h.reopen();report.finalReopen=true;report.savedTransfers=h.sqlite.prepare('SELECT count(*) AS n FROM food_transfers').get().n;report.pendingNextOpening=previousPartial.recordId;assert.equal((await detail(previousLoc,previousPartial)).transfer.status,'sent');report.currentCatalogUnchanged=true;report.sourceRevisionAfter=h.sourceHashes();assert.deepEqual(report.sourceRevisionAfter,report.sourceRevision);report.sourceUnchanged=true;
 }catch(e){if(!report.failures.length)report.failures.push({name:'setup/final',error:String(e.stack)});}finally{globalThis.Date=RealDate;h.close();fs.writeFileSync(h.file.replace('.sqlite','.json'),JSON.stringify(report,null,2)+'\n');}
 assert.equal(report.days.length,trialDays);assert.deepEqual(report.failures,[],JSON.stringify(report.failures));
});
