import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {localTrial,managerCaps} from './hour-trial-local-fixture.mjs';
import {handleWorkspace} from '../.sites-runtime/shared/service.mjs';
import {handleCompanionChat} from '../.sites-runtime/shared/companion-chat.mjs';
const trialDays=Number(process.env.HOUR_TRIAL_DAYS??7);assert.ok(Number.isInteger(trialDays)&&trialDays>=7&&trialDays<=21);

test(`Papa shared-team ${trialDays}-day trial: counter accuracy, failed prepaid delivery, deferred work, all-role close and independent GM checkout`,async()=>{
 const RealDate=Date;let now=RealDate.parse('2026-10-08T15:00:00-04:00');
 globalThis.Date=class extends RealDate{constructor(...a){super(...(a.length?a:[now]));}static now(){return now;}};
 const roles=[{id:'counter',position:'Counter',area:'FOH'},{id:'driver',position:'Delivery Driver',area:'FOH'},{id:'make',position:'Pizza Make'},{id:'catch',position:'Pizza Catch'},{id:'shared-dish',position:'Pizza Make'}];
 const actors=[...roles,{id:'gm',position:'General manager',caps:managerCaps},{id:'checker',position:'General manager',caps:managerCaps},{id:'foreign',position:'General manager',caps:managerCaps,loc:'berts'}];
 const h=localTrial('papas',actors);const report={id:'papa-shared-team-hour-trial',days:[],cases:[],failures:[],initialSeeds:1,operationalReseeds:0,sourceRevision:h.sourceRevision,database:h.file,limits:['Five Papa source-backed role assignments share one fictional durable database, including shared Dish on Pizza Make; GM has an independent authorized checker.','Papa opens at 3PM and has one shift. Eight-hour test duration is fictional, not an approved closing time.','Actual task, message, schedule, closing, release and chat-context handlers; physical cooking/cleaning, Shipday dispatch, order payment and cash payout are not executed.','Mock AI verifies saved context only; it does not grade real generated helpfulness. No external calls.']};
 const caseRun=async(name,fn)=>{try{await fn();report.cases.push({name,status:'passed'});}catch(e){report.failures.push({name,error:String(e.stack)});throw e;}};
 const record=id=>h.find(id);let previousPan,previousUnreachable;const pendingFollowups=[];const standards={};report.plannedDays=trialDays;report.customerCarry=[];
 const duties={counter:['Detail bathrooms, sweep and mop FOH, foyer and behind counter; clean counters and clear seven outdoor tables.','Count drawer and hand off to GM; trash up front.','Turn both hot boxes off, break down soda machine; owner-described nozzle soda-water soak overnight.'],driver:['Restore delivery staging area, assist FOH if available.','Turn all slips in to GM and await reviewed payout; prepaid orders do not require door collection.'],make:['Break down pizza table; date check and clean underneath; pans to Dish.','Shutdown oven and crumb tray when assigned; clean to open.'],catch:['Clean cutting area, utensils, garnish bottles, shakers; stock boxes and service trays.'], 'shared-dish':['Clean shared dish area and air-dry pizza pans overnight; next opening puts dry pans away.'],gm:['Personally verify dining room, bathrooms and entrances.','Review drawer handoff and unresolved delivery exceptions; retain next-day follow-through.']};
 async function task(owner,title,detail,day,shift){return h.command('gm','task.create',{ownerId:owner,title,detail,kind:'task',due:new Date(day+7*3600000).toISOString(),...(shift?{shiftId:shift.recordId}:{})});}
 async function finish(owner,r,checker='gm'){r=await h.command(owner,'task.transition',{step:'ready',note:'Fictional remedy evidenced; physical action not performed'},r);return h.command(checker,'task.transition',{step:'verify',note:'Independent fictional inspector review'},r);}
 try{
  for(const actor of [...roles,{id:'gm',position:'General manager'}]){let s=await h.command('checker','standard.save',{title:`Papa ${actor.id} close`,position:actor.position,area:actor.area??'BOH',zone:'Assigned Papa '+actor.id+' area',criteria:duties[actor.id],source:'Owner confirmed Papa one-shift Counter, Driver, Pizza Make/Catch and shared Dish; software QA only',version:1,verification:'manager',guide:{purpose:'Close to open',preparation:['Read current instructions and prior unfinished work'],steps:duties[actor.id],troubleshooting:['Report incomplete checks'],escalation:'Independent authorized manager'}});standards[actor.id]=await h.command('checker','standard.approve',{validated:true,note:'Fictional simulation guide approved'},s);}
  for(let day=1;day<=trialDays;day++){
   const curveball=['Missing cold item','Wrong pizza ticket','Changed guest order not reconciled','Incomplete condiment kit','Included seasoning bag missing','Wrong box label','Duplicate pickup ticket'][(day-1)%7];const start=now,dayReport={day,week:Math.ceil(day/7),curveball,businessDate:new Date(start).toISOString().slice(0,10),roles:roles.map(r=>r.id).concat('gm')};report.days.push(dayReport);h.reopen();
   await caseRun(`day ${day}: prior-day pans and unsuccessful delivery remain saved until remedy`,async()=>{if(previousPan){assert.equal(record(previousPan.recordId).data.phase,'open');previousPan=await finish('shared-dish',previousPan);assert.equal(record(previousPan.recordId).data.phase,'closed');}for(const pending of pendingFollowups.filter(p=>!p.resolvedDay)){assert.equal(record(pending.record.recordId).data.phase,'open');if(pending.resolveDay<=day){pending.record=await finish('driver',pending.record);pending.resolvedDay=day;assert.equal(record(pending.record.recordId).data.phase,'closed');}else report.customerCarry.push({day,originalDay:pending.originalDay,recordId:pending.record.recordId,phase:'open',expectedResolveDay:pending.resolveDay});}});
   const shifts={};await caseRun(`day ${day}: all five actual Papa role assignments plus GM begin one published shift`,async()=>{for(const actor of [...roles,{id:'gm',position:'General manager'}]){let s=await h.command('checker','shift.save',{personId:actor.id,position:actor.position,start:new Date(start).toISOString(),end:new Date(start+8*3600000).toISOString()});shifts[actor.id]=await h.command('checker','shift.publish',{},s);const opening=await task(actor.id,'Opening: '+actor.id,actor.id==='counter'?'Hot box water; soda assembly; dressing cups; chairs down; glass and doors; drawer counted; music.':actor.id==='driver'?'Shipday enabled, vehicle and fuel ready, boxes stocked; no real dispatch connected.':'Read manager briefing, station tools and ingredients, prior unfinished work.',start);await finish(actor.id,opening,actor.id==='gm'?'checker':'gm');}});
   now=start+2*3600000;
   let accuracy,notice,delivery,slips;
   await caseRun(`day ${day}: Counter error cannot be hidden by driver acknowledgment or second payment`,async()=>{
    accuracy=await task('counter','Order accuracy: '+curveball,'Fictional pickup discrepancy: '+curveball+'. Resolve against ticket before pickup; hot and cold items complete, order prepaid and Parmesan/pepper bag included.',start,shifts.counter);
    notice=await h.command('counter','message.send',{recipients:['driver','gm'],title:'Hold fictional order for accuracy correction',body:curveball+'; do not leave or collect payment. Original issue '+accuracy.recordId});
    notice=await h.command('driver','message.reply',{text:'Acknowledged hold; prepaid, no second payment. Restaurant to correct before any dispatch.'},notice);
    assert.equal(record(accuracy.recordId).data.phase,'open');const before=h.snapshot();assert.ok([403,404].includes((await h.raw('driver','task.transition',{step:'ready',note:'Cannot complete Counter work'},accuracy)).status));assert.equal(h.snapshot(),before);
    accuracy=await h.command('counter','task.transition',{step:'ready',note:'First bag check still does not resolve '+curveball},accuracy);accuracy=await h.command('gm','task.transition',{step:'fix',note:curveball+' still unresolved; original accuracy work remains pending'},accuracy);accuracy=await finish('counter',accuracy);assert.equal(record(accuracy.recordId).data.phase,'closed');
   });
   await caseRun(`day ${day}: driver unreachable guest escalates and work survives lost-response reopen`,async()=>{
    delivery=await task('driver','Unreachable prepaid delivery '+day,'Fictional dispatch only: guest call attempted; contact restaurant for direction. Do not automatically doorstep-drop. Keep unresolved until independent review.',start,shifts.driver);
    let message=await h.command('driver','message.send',{recipients:['gm','counter'],title:'Cannot complete fictional delivery',body:'Guest unreachable after call; ask restaurant for direction. No cash due. Saved issue '+delivery.recordId});
    message=await h.command('gm','message.reply',{text:'Return to restaurant in this fictional scenario; retain follow-up, do not mark delivered.'},message);assert.equal(record(delivery.recordId).data.phase,'open');
    const prior=delivery,rid='papa-return-'+day,input={step:'ready',note:'Driver returned; original customer outcome still unresolved'};delivery=await h.command('driver','task.transition',input,prior,rid);h.reopen();assert.deepEqual(await h.command('driver','task.transition',input,prior,rid),delivery);delivery=await h.command('gm','task.transition',{step:'fix',note:'Returning is not proof customer received order'},delivery);
    assert.equal(record(delivery.recordId).data.phase,'correction');const before=h.snapshot();assert.equal((await h.raw('driver','task.transition',{step:'verify',note:'Cannot self-verify delivery'},delivery)).status,403);assert.equal(h.snapshot(),before);
    previousUnreachable=await task('driver','Next-opening delivery follow-up '+day,'Original unresolved guest outcome: restaurant follow-up explicitly carried forward; returning is not delivery completion. Week-end cases stay open until a later documented remedy.',start+(day%7===0?72:24)*3600000);pendingFollowups.push({originalDay:day,resolveDay:day+(day%7===0?3:1),record:previousUnreachable});
    delivery=await h.command('driver','task.transition',{step:'ready',note:'Driver return/escalation completed; customer outcome remains open under saved follow-up '+previousUnreachable.recordId},delivery);delivery=await h.command('gm','task.transition',{step:'verify',note:'Independently verify return/escalation only; no delivered-customer or payment claim. Follow-up '+previousUnreachable.recordId+' remains open.'},delivery);slips=await task('driver','Slips and payout review '+day,'Fictional review record: all delivery slips to GM; payout evidence reviewed independently. No actual money moved.',start,shifts.driver);
   });
   await caseRun(`day ${day}: every role AI context retains current stage without modifying work`,async()=>{
    for(const actor of roles){const focus=actor.id==='driver'?(pendingFollowups.find(p=>!p.resolvedDay&&p.originalDay<day)?.record??previousUnreachable):await task(actor.id,'Current service '+actor.id,'Continue assigned service; do not turn closing instructions into current service. '+(actor.id==='make'?'Pizza Make owns its table.':actor.id==='catch'?'Catch checks tickets/cut/garnish correct box.':'Use current task history.'),start);let captured;
     const provider=async(_url,init)=>{const input=JSON.parse(init.body).input;captured=JSON.parse(input[1].content.split('\n').slice(1).join('\n'));return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({answer:'Follow the saved current task and manager direction. This mock has not completed work or notified anyone.',sourceIds:captured.evidence.map(e=>e.source.id).slice(0,20)})}]}]});};
     const binding={OPENAI_API_KEY:'sk-fictional-only',JMAX_OPENAI_MODEL:'gpt-5.4-mini'},current=h.ok(await h.call(async(r,db)=>handleCompanionChat(r,db,binding,provider,()=>now,'workforce'),actor.id,'companion','papa'));const before=JSON.stringify(h.sqlite.prepare('SELECT * FROM records ORDER BY rowid').all());
     const answer=h.ok(await h.call(async(r,db)=>handleCompanionChat(r,db,binding,provider,()=>now,'workforce'),actor.id,'companion','papa',{action:'ask',locationId:'papa',conversationId:current.conversationId,expectedRevision:current.revision,requestId:`${day}-${actor.id}-context`,question:'What is the actual current status and next action for my focused work?',focus:{id:focus.recordId,revision:focus.revision}}));
     assert.equal(answer.turns.at(-1).status,'complete');assert.ok(captured.evidence.some(e=>e.source.id===focus.recordId&&e.facts.phase===record(focus.recordId).data.phase));assert.equal(JSON.stringify(h.sqlite.prepare('SELECT * FROM records ORDER BY rowid').all()),before);if(actor.id!=='driver')await finish(actor.id,focus);
    }
   });
   now=start+7*3600000;
   await caseRun(`day ${day}: completed cleaning cannot bypass pending driver slips; GM cannot self-checkout`,async()=>{
    for(const actor of [...roles,{id:'gm',position:'General manager'}]){const reviewer=actor.id==='gm'?'checker':'gm';let close=await h.command('checker','close.assign',{shiftId:shifts[actor.id].recordId,standardId:standards[actor.id].recordId,managerId:reviewer,due:new Date(now).toISOString()});close=await h.command(actor.id,'close.transition',{step:'ready',answers:duties[actor.id].map((_,i)=>i),note:'Fictional inspector criterion assertions only'},close);
     if(actor.id==='gm'){const before=h.snapshot();assert.equal((await h.raw('gm','close.transition',{step:'confirm',note:'GM cannot confirm own close'},close)).status,403);assert.equal(h.snapshot(),before);}
     if((day-1)%7===2||actor.id==='gm'&&(day-1)%7===5){close=await h.command(reviewer,'close.transition',{step:'fix',note:'Simulated inspection finds unfinished cleaning'},close);assert.equal((await h.raw(reviewer,'shift.release',{note:'Cannot bypass correction'},shifts[actor.id])).status,400);close=await h.command(actor.id,'close.transition',{step:'ready',answers:duties[actor.id].map((_,i)=>i),note:'Fictional corrective inspection evidence'},close);}
     close=await h.command(reviewer,'close.transition',{step:'confirm',note:'Independent inspection confirms criteria'},close);
     if(actor.id==='driver'){assert.equal((await h.raw('gm','shift.release',{note:'Cleaning done but slips pending'},shifts.driver)).status,400);slips=await finish('driver',slips);}
     assert.equal((await h.raw(actor.id,'shift.release',{note:'Cannot release own shift'},shifts[actor.id])).status,403);await h.command(reviewer,'shift.release',{note:'Required fictional check records reviewed'},shifts[actor.id]);
    }
    previousPan=await task('shared-dish','Air-dried pizza pans: next opening '+day,'Overnight air drying; next opening puts dry pizza pans away. This is a next-day duty, not a second Papa shift.',start+24*3600000);
   });
   await caseRun(`day ${day}: Papa team cannot hop into Bert or Rudd workspace`,async()=>{const before=h.snapshot();for(const actor of [...roles,{id:'gm'}])for(const loc of ['berts','rudds'])assert.equal((await h.call(handleWorkspace,actor.id,'workspace',loc)).status,403);assert.equal(h.snapshot(),before);});
   now=start+86400000;
  }
  h.reopen();assert.equal(record(previousPan.recordId).data.phase,'open');assert.equal(record(previousUnreachable.recordId).data.phase,'open');report.finalReopen=true;report.aiContextRequests=trialDays*5;report.carryIntoNextOpening=[previousPan.recordId,...pendingFollowups.filter(p=>!p.resolvedDay).map(p=>p.record.recordId)];report.customerFollowupOutcomes=pendingFollowups;report.savedRecords=h.sqlite.prepare('SELECT count(*) AS n FROM records').get().n;report.sourceRevisionAfter=h.sourceHashes();assert.deepEqual(report.sourceRevisionAfter,report.sourceRevision);report.sourceUnchanged=true;
 }catch(e){if(!report.failures.length)report.failures.push({name:'setup/final',error:String(e.stack)});}finally{globalThis.Date=RealDate;h.close();fs.writeFileSync(h.file.replace('.sqlite','.json'),JSON.stringify(report,null,2)+'\n');}
 assert.equal(report.days.length,trialDays);assert.deepEqual(report.failures,[],JSON.stringify(report.failures));
});
