import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {createHash} from 'node:crypto';

test('All 42 current profiles and verified owner contexts retain multiweek memory without crossing privacy or retired-source boundaries',async()=>{
 const runId=crypto.randomUUID(),dir=path.resolve('evidence/hour-trial/memory-all-positions/'+runId),runtime=path.join(dir,'runtime');fs.mkdirSync(runtime,{recursive:true});
 const hashes=root=>Object.fromEntries(fs.readdirSync(root).filter(f=>f.endsWith('.mjs')).sort().map(f=>[f,createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')]));const original=hashes('.sites-runtime/shared');for(const f of Object.keys(original))fs.copyFileSync('.sites-runtime/shared/'+f,path.join(runtime,f));assert.deepEqual(hashes('.sites-runtime/shared'),original,'Do not snapshot during a coordinated compile');assert.deepEqual(hashes(runtime),original);
 const profiles=['berts-foh','berts-boh','rudds','papas','management','commissary'].flatMap(group=>JSON.parse(fs.readFileSync('evidence/all-position-week/'+group+'-profiles.json','utf8')).map(p=>({...p,sourceManifest:group+'-profiles.json'})));assert.equal(profiles.length,42);assert.equal(new Set(profiles.map(p=>p.id)).size,42);
 for(const ownerSeat of ['jay','rudd'])for(const restaurant of ['berts','rudds','papa','comm'])profiles.push({id:`owner-${ownerSeat}-${restaurant}`,restaurant,position:'Owner',area:'BOH',capabilities:['location.manage'],ownerSeat,sourceManifest:'Explicit unique owner seat policy, not inferred from title or capability'});
 fs.writeFileSync(path.join(dir,'profiles.json'),JSON.stringify(profiles,null,2)+'\n');const resumePath=process.env.HOUR_MEMORY_RESUME_SUMMARY,prior=resumePath?JSON.parse(fs.readFileSync(resumePath,'utf8')):null;const reuse=prior&&JSON.stringify(prior.runtimeRevision)===JSON.stringify(original)?prior.results.filter(r=>r.exitCode===0&&!r.failures.length):[];const results=[...reuse],pending=profiles.filter(p=>!reuse.some(r=>r.id===p.id));let index=0;
 const run=profile=>new Promise(resolve=>{const child=spawn(process.execPath,['tests/hour-memory-all-position-runner.mjs'],{stdio:['pipe','pipe','pipe']});let out='',err='';child.stdout.on('data',x=>out+=x);child.stderr.on('data',x=>err+=x);child.on('error',error=>resolve({id:profile.id,failures:[{error:String(error)}]}));child.on('close',code=>{let receipt;try{receipt=JSON.parse(out);}catch{receipt={id:profile.id,failures:[{error:'Missing runner receipt',out,err}]};}results.push({...receipt,exitCode:code,stderr:err});fs.writeFileSync(path.join(dir,'progress.json'),JSON.stringify({completed:results.length,expected:profiles.length,results},null,2)+'\n');resolve();});child.stdin.end(JSON.stringify({runId,runtime,profile}));});
 await Promise.all(Array.from({length:Math.min(4,pending.length)},async()=>{while(index<pending.length){const p=pending[index++];await run(p);}}));
 const summary={runId,runtime,runtimeRevision:original,runtimeUnchanged:JSON.stringify(hashes(runtime))===JSON.stringify(original),manifestProfiles:42,ownerContexts:8,totalProfiles:profiles.length,completedProfiles:results.length,totalCompletedDays:results.reduce((n,r)=>n+(r.days??0),0),workerAsks:results.reduce((n,r)=>n+(r.workerAsks??0),0),checks:results.reduce((n,r)=>n+(r.checks??0),0),externalCalls:0,operationalReseeds:0,reusedSuccessfulReceipts:reuse.length,replayedProfiles:pending.map(p=>p.id),...(resumePath?{priorSummary:resumePath,initialFailuresPreserved:true}:{}),results,proof:'Every current position/variant plus authorized owner contexts. Actual local handlers and fictional durable records, mocked provider context only; no training or generated helpfulness claim. Successful prior receipts are reused only when every pinned compiled-module hash is identical.'};fs.writeFileSync(path.join(dir,'summary.json'),JSON.stringify(summary,null,2)+'\n');console.log('Evidence:',path.join(dir,'summary.json'));assert.equal(results.length,50);for(const r of results){assert.equal(r.exitCode,0,JSON.stringify(r));assert.deepEqual(r.failures,[],JSON.stringify(r));assert.equal(r.days,45);assert.equal(r.workerAsks,94);}assert.equal(summary.runtimeUnchanged,true);
});
