import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {openPositionDatabase} from './all-position-week-fixture.mjs';
import {handleWorkspace} from '../.sites-runtime/shared/service.mjs';
import {carriedIssues,previousShift} from '../.sites-runtime/shared/operations.mjs';
import {localDate} from '../.sites-runtime/shared/local-time.mjs';

// One restaurant, one durable database, one initial seed. Bert's documented
// roles interact; only handler mechanics are shared with the Rudd's trial.
const NativeDate=Date;
const profiles=[...JSON.parse(fs.readFileSync('evidence/all-position-week/berts-foh-profiles.json','utf8')),...JSON.parse(fs.readFileSync('evidence/all-position-week/berts-boh-profiles.json','utf8'))];
const runId=new NativeDate().toISOString().replaceAll(':','-').replaceAll('.','-');
const output=path.join('evidence/hour-trial/berts-team',runId);
fs.mkdirSync(output,{recursive:true});
const id=p=>p.id.replace(/^berts-/,'');
const managers=new Set(['foh-manager','boh-manager']);

test('Bert’s integrated seven-day team: documented duties, kitchen/FOH handoffs, hierarchy, checkout and persistent next-opening issues',async()=>{
 const file=path.join(output,'durable-team.sqlite');let store=openPositionDatabase(file),now=NativeDate.parse('2026-10-08T08:00:00-04:00');
 globalThis.Date=class extends NativeDate{constructor(...values){super(...(values.length?values:[now]));}static now(){return now;}};
 const actors=profiles.map(p=>({id:id(p),profile:p}));
 // Dedicated extra PM participant is required by the actual AM+two-PM cycle.
 // It is not counted as an additional discovered restaurant role.
 actors.push({id:'dishwasher-pm-helper',profile:structuredClone(profiles.find(p=>id(p)==='dishwasher-pm'))});
 const report={status:'running',restaurant:'berts',documentedProfiles:profiles.length,documentedRoleDays:0,auxiliaryDishParticipants:1,initialSeeds:1,operationalReseeds:0,database:file,days:[],checks:[],failures:[],sources:profiles.map(p=>({id:p.id,position:p.position,source:p.source,provenance:p.provenance,opening:p.opening,service:p.service,closing:p.closing,knownGaps:p.knownGaps})),limits:['Actual local authenticated handlers and durable fictional records; no external AI calls, hosted rollout or browser execution.','Messages and tasks model explicitly reported work; no live guest tickets, recooks, food delivery, POS order edits, server banking or physical inspection are asserted.','Bert’s combined Oven assembles/bakes its documented items; Sandwich/Pasta assembles and loads baked spaghetti, then Oven pulls/plates it for Expo. The scenario does not invent recipes, temperatures, oil methods or equipment procedures.','All 17 documented profiles use the same restaurant database. An additional fictional PM dishwasher identity satisfies the existing AM+two-PM cycle; it is not a new operational position.','GM/administrator grants in this QA fixture are explicitly configured permissions, not authority inferred from a job title. Restaurant access remains Bert’s-only.','No shared equipment-learning or automated AI debrief feature is claimed. Saved manual manager summaries and private staff communications are exercised.']};
 const save=()=>fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(report,null,2)+'\n');
 const request=(who,body,loc='berts')=>new Request('https://berts-team.example/api/workspace?locationId='+loc,{headers:{'oai-authenticated-user-id':who+'-team-identity','oai-authenticated-user-email':who+'@example.test',Origin:'https://berts-team.example','Content-Type':'application/json'},...(body?{method:'POST',body:JSON.stringify(body)}:{})});
 const raw=async(who,action,input={},record,requestId=crypto.randomUUID(),loc='berts')=>{const r=await handleWorkspace(request(who,action?{locationId:loc,requestId,action,input,...(record?{recordId:record.recordId??record.id,expectedRevision:record.revision}:{})}:undefined,loc),store.db);return {status:r.status,data:await r.json()};};
 const command=async(...args)=>{const r=await raw(...args);assert.equal(r.status,200,JSON.stringify(r.data));return r.data;};
 const view=who=>command(who);
 const find=record=>{const row=store.sqlite.prepare('SELECT * FROM records WHERE id=?').get(record.recordId??record.id??record);return row&&{...row,ownerId:row.owner_id,data:JSON.parse(row.data)};};
 const snapshot=()=>JSON.stringify(Object.fromEntries(['locations','records','command_receipts','audit_events'].map(table=>[table,store.sqlite.prepare(`SELECT * FROM ${table} ORDER BY rowid`).all()])));
 const check=async(day,label,fn)=>{try{await fn();report.checks.push({day,label,status:'passed'});}catch(error){report.failures.push({day,label,error:String(error.stack??error)});throw error;}};
 const deny=async(day,label,args,status)=>check(day,label,async()=>{const before=snapshot(),r=await raw(...args);assert.equal(r.status,status,JSON.stringify(r.data));assert.equal(snapshot(),before,'Denied operation changes no records, receipts, audit or restaurant revision');});
 const message=async(from,to,title,body)=>{const m=await command(from,'message.send',{recipients:to,title,body});for(const person of to)assert.ok((await view(person)).records.some(r=>r.id===m.recordId));return m;};
 const reopen=()=>{const before=snapshot();store.close();store=openPositionDatabase(file);assert.equal(snapshot(),before);};
 const standards={},allIds=[];let carry,priorReport;
 const authority=(actor,bohChecker)=>managers.has(actor.id)?'gm':actor.profile.area==='FOH'?'foh-manager':bohChecker;
 try{
  for(const name of fs.readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())store.sqlite.exec(fs.readFileSync('drizzle/'+name,'utf8').replaceAll('--> statement-breakpoint',''));
  for(const loc of ['berts','rudds','papa'])store.sqlite.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').run(loc,'FICTIONAL '+loc,'America/New_York');
  for(const actor of [...actors,{id:'gm',profile:{area:'BOH',position:'General manager',capabilities:['location.manage','tasks.manage','close.confirm','standards.approve','schedule.manage','schedule.publish','schedule.change','people.manage']}}])store.sqlite.prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').run(actor.id,actor.id+'@example.test',actor.id+'-team-identity','berts','FICTIONAL '+actor.id,actor.profile.area,actor.profile.position,JSON.stringify(actor.profile.capabilities??[]),JSON.stringify([actor.profile.position]));
  for(const p of profiles){const actor=id(p);let standard=await command('gm','standard.save',{area:p.area,title:p.position+' · '+actor+' documented QA reference',position:p.position,zone:actor+' station',criteria:p.closing,source:'Fictional QA review; '+(p.source??JSON.stringify(p.provenance)),version:1,verification:'manager',guide:{purpose:'Exercise the documented Bert’s '+p.position+' duties',preparation:p.opening,steps:p.closing,troubleshooting:['Keep incomplete work open; use the named manager and approved source instructions'],escalation:'Named on-duty department manager; GM retains responsibility when absent'}});standard=await command('gm','standard.approve',{validated:true,note:'Fictional approval for this local test; not restaurant SOP publication'},standard);standards[actor]=standard;allIds.push(standard.recordId);}
  for(let day=1;day<=7;day++){
   const start=NativeDate.parse('2026-10-'+String(day+7).padStart(2,'0')+'T08:00:00-04:00');now=start;
   const businessDate=localDate(new Date().toISOString(),'America/New_York'),shifts={},openings={},curves={},closes={};
   const bohChecker=day===4?'gm':'boh-manager';
   const dayReport={day,businessDate,roles:[],bohCoverage:day===4?'BOH manager leaves early; named GM handles later kitchen checks':'Named BOH manager',events:[]};report.days.push(dayReport);
   if(day>1)await check(day,'Same team database reopens without operational reseeding; previous submitted report and GM-owned issue carry into opening',async()=>{reopen();for(const recordId of allIds)assert.ok(find(recordId));assert.equal(find(carry).data.status,'accepted');assert.equal(find(carry).ownerId,'gm');const w=await view('gm');assert.equal(previousShift(w,businessDate,'BOH')?.id,priorReport.recordId);assert.ok(carriedIssues(w,businessDate,'BOH').some(r=>r.id===carry.recordId));assert.ok(!(await view('server')).records.some(r=>r.id===carry.recordId));let summary=await command('gm','shiftentry.save',{department:'BOH',businessDate,shift:'opening',readiness:'action-needed',summary:'Yesterday’s unresolved reported shortage remains assigned to GM.',tomorrowNote:'Use the saved report and actual approved prep method; no reset or guessed recipe.',issueIds:[carry.recordId]});summary=await command('gm','shiftentry.submit',{},summary);allIds.push(summary.recordId);carry=await command('gm','managerlog.resolve',{note:'Fictional current opening checker reports the prior shortage remedied; record retains resolution history.'},carry);assert.equal(find(carry).data.status,'resolved');assert.ok(carriedIssues(await view('gm'),businessDate,'BOH').some(r=>r.id===carry.recordId),'Opening history retains issue even after resolution later that day');});
   const finish=new Date(start+15*3600000).toISOString();
   for(const actor of actors){const am=actor.id==='dishwasher-am',pm=actor.profile.dishShift==='PM';const roleStart=start+(pm?7:0)*3600000,roleEnd=start+(am?7:day===4&&actor.id==='boh-manager'?7:15)*3600000;let shift=await command('gm','shift.save',{personId:actor.id,position:actor.profile.position,start:new Date(roleStart).toISOString(),end:new Date(roleEnd).toISOString()});shift=await command('gm','shift.publish',{},shift);shifts[actor.id]=shift;allIds.push(shift.recordId);const checker=authority(actor,bohChecker);let opening=await command(checker,'task.create',{ownerId:actor.id,shiftId:shift.recordId,title:'Day '+day+' '+actor.profile.position+' opening',detail:actor.profile.opening.join('\n'),kind:'task',due:new Date(roleStart+3600000).toISOString()});openings[actor.id]=opening;allIds.push(opening.recordId);dayReport.roles.push({id:actor.id,position:actor.profile.position,documentedProfile:actor.id!=='dishwasher-pm-helper',shiftId:shift.recordId,openingId:opening.recordId,openingDuties:actor.profile.opening,serviceDuties:actor.profile.service,closingDuties:actor.profile.closing,scenario:actor.profile.dailyScenarios[day-1]});}
   for(const area of ['FOH','BOH']){const person=area==='FOH'?'foh-manager':'boh-manager',leadEnd=day===4&&area==='BOH'?new Date(start+7*3600000).toISOString():new Date(start+16*3600000).toISOString();const lead=await command('gm','leadership.assign',{personId:person,area,start:new Date(start).toISOString(),end:leadEnd,note:'Explicit fictional named department lead, not title-derived permission.'});allIds.push(lead.recordId);if(area==='FOH'){assert.ok((await view('server')).records.some(r=>r.id===lead.recordId));assert.ok(!(await view('combined-oven')).records.some(r=>r.id===lead.recordId));}else{assert.ok((await view('combined-oven')).records.some(r=>r.id===lead.recordId));assert.ok(!(await view('server')).records.some(r=>r.id===lead.recordId));}}
   await check(day,'All documented positions have a published shift and their own source-labelled opening in the shared restaurant',async()=>{for(const actor of actors){const w=await view(actor.id);assert.equal(w.me.locationId,'berts');assert.ok(w.records.some(r=>r.id===shifts[actor.id].recordId));assert.ok(w.records.some(r=>r.id===openings[actor.id].recordId));}});
   now=start+3600000;
   for(const actor of actors)await check(day,actor.id+' opening readiness independently checked',async()=>{let task=await command(actor.id,'task.transition',{step:'ready',note:'Fictional opening conditions reported; no physical proof claimed.'},openings[actor.id]);const checker=authority(actor,bohChecker);if(day===2&&actor.id==='back-window'){task=await command(checker,'task.transition',{step:'fix',note:'Dressing count/prep need not yet recorded; correct opening report.'},task);assert.equal(find(task).data.phase,'correction');task=await command(actor.id,'task.transition',{step:'ready',note:'Fictional missing opening count documented.'},task);}task=await command(checker,'task.transition',{step:'verify',note:'Independent fictional opening check.'},task);assert.equal(find(task).data.phase,'closed');openings[actor.id]=task;});
   now=start+8*3600000;
   // Each profile has its own real saved scenario and named checker. These are
   // explicitly reported interruptions, not manufactured physical service.
   for(const actor of actors){const checker=authority(actor,bohChecker),scenario=actor.profile.dailyScenarios[day-1];let curve=await command(checker,'task.create',{ownerId:actor.id,shiftId:shifts[actor.id].recordId,title:scenario.title,detail:[...actor.profile.service,scenario.detail,scenario.nextAction].join('\n'),kind:'task',due:find(shifts[actor.id]).data.end});curves[actor.id]=curve;allIds.push(curve.recordId);const notice=await message(actor.id,[checker],'Day '+day+' '+actor.profile.position+' exception',scenario.detail+'\n'+scenario.nextAction+'\nSaved assignment '+curve.recordId);const reply=await command(checker,'message.reply',{text:'Received. Keep the assignment open, apply approved instructions, and report readiness for an independent check.'},notice);assert.equal(find(reply).data.replies.at(-1).actorId,checker);allIds.push(reply.recordId);}
   await check(day,'Host/Busser/Server floor communication keeps seating authority with FOH manager',async()=>{const reset=await message('busser',['host'],'Reported table reset','Tabletop and seats reported wiped, chairs pushed in. Ready condition must be checked physically.');await command('host','message.read',{},reset);assert.ok(find(reset).data.readBy.includes('host'));let overload=await message('host',['foh-manager'],'Written rotation and seating pace','Next section is overloaded; request direction before seating it.');overload=await command('foh-manager','message.reply',{text:'Retain steady pace and wait for my coverage direction for that section.'},overload);assert.ok(!(await view('fryer')).records.some(r=>r.id===overload.recordId));});
   await check(day,'Bert’s baked-spaghetti handoff uses Sandwich/Pasta assembly and loading, combined Oven pull/plate, then Expo/Runner',async()=>{await message('sandwich-pasta',['combined-oven','expo'],'Bert’s baked-spaghetti handoff','Fictional reported item assembled and put in the oven by Sandwich/Pasta; combined Oven must pull/plate it and send it to Expo. Use actual approved ticket/recipe when available.');await message('combined-oven',['expo'],'Bert’s combined Oven return','Fictional reported baked spaghetti pulled and plated; assembled oven items remain this combined position’s duties.');await message('expo',['food-runner','server'],'Reported entrée ready','Runner coordinates the reported item with the server and follows the approved table delivery method. This message does not prove delivery.');});
   await check(day,'Back Window missing-cold-item and Server cooking-error reports go through Expo to combined Oven with BOH authority',async()=>{await message('back-window',['expo'],'Missing cold item during bagging','Bagging check found the cold side missing; add proper condiments/cups/kit, attach ticket, and keep order incomplete until corrected. No pickup completed by chat.');await message('server',['expo'],'Reported cooking error','Fictional guest reports incorrect oven entrée. Expo requests the cook-side correction; actual recipe and guest ticket are external evidence.');await message('expo',['combined-oven',bohChecker],'Named kitchen correction','Correct the reported oven item using current approved ticket/build instructions; pass the checked result through Expo.');let task=curves['combined-oven'];await deny(day,'FOH manager cannot inspect or verify BOH correction',['foh-manager','task.transition',{step:'verify',note:'FOH title cannot take kitchen authority.'},task],404);task=await command('combined-oven','task.transition',{step:'ready',note:'Fictional kitchen correction reported, not physical recook proof.'},task);await deny(day,'Oven employee cannot self-verify kitchen work',['combined-oven','task.transition',{step:'verify',note:'Self verification prohibited.'},task],403);task=await command(bohChecker,'task.transition',{step:'fix',note:'Independent fictional checker reports a remaining garnish or plate mismatch.'},task);task=await command('combined-oven','task.transition',{step:'ready',note:'Reported mismatch corrected.'},task);curves['combined-oven']=await command(bohChecker,'task.transition',{step:'verify',note:'Independent current kitchen correction checked.'},task);await message('combined-oven',['expo'],'Reported corrected oven handoff','Checked ticket, cut/garnished/boxed or plated as applicable; return through Expo.');await message('expo',['food-runner','server','back-window'],'Reported correction ready','Return through the responsible guest/pickup flow and retain actual contents/payment checks.');});
   await check(day,'Ordering error remains the FOH manager’s decision, separate from a cook-side correction',async()=>{let notice=await message('expo',['foh-manager'],'Ordering error','Reported ticket/guest order mismatch requires FOH manager direction; a remake does not establish the ordering decision.');notice=await command('foh-manager','message.reply',{text:'I own the ordering decision; communicate the approved correction to Server/Back Window and Expo.'},notice);await message('foh-manager',['server','back-window','expo'],'Ordering correction direction','Use the actual approved guest/ticket correction and follow it through. No POS order is changed by this message.');assert.equal(find(notice).data.replies.at(-1).actorId,'foh-manager');});
   if(day===3||day===6)await check(day,'Disputed Pasta-to-Oven station handoff is corrected and independently checked before acceptance',async()=>{let h=await command(bohChecker,'task.create',{ownerId:'sandwich-pasta',incomingId:'combined-oven',kind:'handoff',title:'Reported remaining oven handoff',detail:'Fictional remaining plate/oven condition; current approved preparation method remains separate.',due:finish});h=await command('sandwich-pasta','task.transition',{step:'ready',note:'Reported station handoff ready.'},h);h=await command(bohChecker,'task.transition',{step:'verify',note:'Reported condition checked; not recipient completion.'},h);h=await command('combined-oven','task.transition',{step:'dispute',note:'Named incoming person reports required plated component missing.'},h);assert.equal(find(h).data.phase,'correction');h=await command('sandwich-pasta','task.transition',{step:'ready',note:'Reported missing handoff condition corrected.'},h);h=await command(bohChecker,'task.transition',{step:'verify',note:'Fresh independent condition check.'},h);h=await command('combined-oven','task.transition',{step:'accept',note:'Incoming station condition accepted.'},h);assert.equal(find(h).data.phase,'closed');allIds.push(h.recordId);});
   if(day===5)await check(day,'Temporarily suspended Runner cannot complete or receive work; unchanged pending work survives restored access',async()=>{const before=find(curves['food-runner']);store.sqlite.prepare('UPDATE memberships SET active=0,revision=revision+1 WHERE id=?').run('food-runner');await deny(day,'Suspended runner is denied',['food-runner','task.transition',{step:'ready',note:'Access is suspended.'},curves['food-runner']],403);store.sqlite.prepare('UPDATE memberships SET active=1,revision=revision+1 WHERE id=?').run('food-runner');assert.equal(find(curves['food-runner']).revision,before.revision);assert.ok((await view('food-runner')).records.some(r=>r.id===before.id));});
   for(const actor of actors)if(actor.id!=='combined-oven')await check(day,actor.id+' saved exception remedy independently checked',async()=>{let task=await command(actor.id,'task.transition',{step:'ready',note:'Fictional approved correction reported.'},curves[actor.id]);if(day===6&&actor.id==='salad-bar-room'){task=await command(bohChecker,'task.transition',{step:'fix',note:'Reported remaining shared-area cleanup condition.'},task);task=await command(actor.id,'task.transition',{step:'ready',note:'Reported condition corrected.'},task);}task=await command(authority(actor,bohChecker),'task.transition',{step:'verify',note:'Independent fictional current correction check.'},task);assert.equal(find(task).data.phase,'closed');curves[actor.id]=task;});
   now=start+14*3600000;
   for(const actor of actors.filter(a=>a.profile.position!=='Dishwasher')){const checker=authority(actor,bohChecker);const close=await command(checker,'close.assign',{shiftId:shifts[actor.id].recordId,standardId:standards[actor.id].recordId,managerId:checker,due:find(shifts[actor.id]).data.end});closes[actor.id]=close;allIds.push(close.recordId);}
   await command(bohChecker,'task.dish-cycle',{amOwnerId:'dishwasher-am',pmOwnerIds:['dishwasher-pm','dishwasher-pm-helper'],businessDate,title:'Bert’s documented Dish close-to-open',detail:profiles.filter(p=>p.position==='Dishwasher').flatMap(p=>p.closing).join('\n'),due:finish});
   const dishTasks=(await view('gm')).records.filter(r=>r.kind==='task'&&r.data.dishCheckout?.businessDate===businessDate);assert.equal(dishTasks.length,3);
   if(day===2||day===4||day===7)await check(day,'Dish AM-to-PM pending-load acceptance retains shared restaurant history and requires independent completion',async()=>{const am=dishTasks.find(r=>r.data.dishCheckout.shift==='AM');await command('dishwasher-am','task.dish-pass',{incomingId:'dishwasher-pm',note:'Fictional pending AM pans/load; leave machine running for the AM-to-PM handoff and coordinate coverage.',due:finish},am);const child=(await view('gm')).records.find(r=>r.kind==='task'&&r.data.dishHandoff?.sourceId===am.id);assert.ok(child);let h=await command('dishwasher-pm','task.transition',{step:'accept',note:'Pending load accepted; actual work still remains.'},child);assert.equal(find(h).data.phase,'open');h=await command('dishwasher-pm','task.transition',{step:'ready',note:'Inherited work reported complete.'},h);h=await command(bohChecker,'task.transition',{step:'verify',note:'Independent fictional inherited-work check.'},h);assert.equal(find(h).data.phase,'closed');allIds.push(h.recordId);});
   for(const actor of actors)await check(day,actor.id+' closing correction and independent manager checkout before operational release',async()=>{let task;if(actor.profile.position==='Dishwasher'){task=find(dishTasks.find(r=>r.ownerId===actor.id).id);await deny(day,actor.id+' dated Dish checkout blocks early release',[bohChecker,'shift.release',{note:'Dated dish checkout unfinished.'},shifts[actor.id]],400);task=await command(actor.id,'task.transition',{step:'ready',note:'Fictional documented dish closing conditions reported.'},task);if(day===3){task=await command(bohChecker,'task.transition',{step:'fix',note:'Fictional physical checker reports incomplete put-away.'},task);task=await command(actor.id,'task.transition',{step:'ready',note:'Fictional put-away correction reported.'},task);}task=await command(bohChecker,'task.transition',{step:'verify',note:'Independent fictional Dish physical checkout.'},task);}else{const checker=authority(actor,bohChecker);task=await command(actor.id,'close.transition',{step:'ready',answers:actor.profile.closing.map((_,i)=>i),note:'Fictional report of all documented closing criteria.'},closes[actor.id]);await deny(day,actor.id+' unconfirmed close blocks release',[checker,'shift.release',{note:'Ready alone cannot release.'},shifts[actor.id]],400);if(day===3||day===6){task=await command(checker,'close.transition',{step:'fix',note:'Independent fictional checker reports one missed documented close condition.'},task);assert.equal(find(task).data.phase,'correction');task=await command(actor.id,'close.transition',{step:'ready',answers:actor.profile.closing.map((_,i)=>i),note:'Reported documented closing correction complete.'},task);}task=await command(checker,'close.transition',{step:'confirm',note:'Independent fictional closing check; bank/payment remains external where applicable.'},task);}assert.equal(find(task).data.phase,'closed');allIds.push(task.recordId);await deny(day,actor.id+' cannot release their own published shift',[actor.id,'shift.release',{note:'Cannot self-release.'},shifts[actor.id]],403);const released=await command(authority(actor,bohChecker),'shift.release',{note:'Documented assigned work independently checked; operational release does not clock out payroll.'},shifts[actor.id]);assert.ok(find(released).data.releasedAt);allIds.push(released.recordId);});
   await check(day,'Unresolved BOH issue transfers to GM, former owner cannot resolve, and manual closing summary links the issue',async()=>{carry=await command('boh-manager','managerlog.create',{ownerId:'boh-manager',department:'BOH',title:'Day '+day+' next-opening reported prep shortage',detail:'Fictional reported shortage requires tomorrow’s count and approved prep instruction; no guessed quantity or recipe.',category:'Food and prep',priority:'routine',due:new Date(start+86400000).toISOString()});carry=await command('boh-manager','managerlog.reassign',{ownerId:'gm',note:'Named GM retains ultimate responsibility and accepts the next-opening check when BOH manager is unavailable.',due:new Date(start+86400000).toISOString()},carry);await deny(day,'Former BOH issue owner cannot resolve GM-owned responsibility',['boh-manager','managerlog.resolve',{note:'Wrong owner cannot mark the new owner’s issue resolved.'},carry],403);carry=await command('gm','managerlog.accept',{note:'GM accepts next-opening responsibility; operational work is still open.'},carry);priorReport=await command('gm','shiftentry.save',{department:'BOH',businessDate,shift:'closing',readiness:'action-needed',summary:'Reported remaining shortage after all assigned station checkouts; named GM follow-through is still open.',tomorrowNote:'Read this report and the linked unresolved issue at opening before assigning approved prep.',issueIds:[carry.recordId]});priorReport=await command('gm','shiftentry.submit',{},priorReport);allIds.push(carry.recordId,priorReport.recordId);assert.equal(find(carry).data.status,'accepted');assert.equal(find(priorReport).data.status,'submitted');reopen();});
   await check(day,'Staff, department managers and this restaurant’s GM cannot switch to Rudd’s or Papa’s',async()=>{for(const actor of [...actors,{id:'gm'}])for(const loc of ['rudds','papa'])assert.equal((await raw(actor.id,undefined,undefined,undefined,undefined,loc)).status,403);});
   report.documentedRoleDays+=profiles.length;save();
  }
  now+=86400000;await check(8,'Final reopen retains the seventh closing report and open GM responsibility at the eighth opening',async()=>{reopen();const date=localDate(new Date().toISOString(),'America/New_York'),w=await view('gm');assert.equal(previousShift(w,date,'BOH')?.id,priorReport.recordId);assert.ok(carriedIssues(w,date,'BOH').some(r=>r.id===carry.recordId));assert.equal(find(carry).data.status,'accepted');for(const recordId of allIds)assert.ok(find(recordId));});
  report.status='passed';report.savedRecords=store.sqlite.prepare('SELECT count(*) AS n FROM records').get().n;report.savedAuditEvents=store.sqlite.prepare('SELECT count(*) AS n FROM audit_events').get().n;report.checkCount=report.checks.length;assert.equal(report.documentedRoleDays,119);assert.equal(report.failures.length,0);save();console.log(JSON.stringify({output,status:report.status,documentedProfiles:17,roleDays:119,checks:report.checkCount,savedRecords:report.savedRecords,failures:0}));
 }catch(error){report.status='failed';if(!report.failures.length)report.failures.push({day:report.days.at(-1)?.day??0,label:'setup or unwrapped operation',error:String(error.stack??error)});save();throw error;}finally{globalThis.Date=NativeDate;store.close();}
});

