import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {openPositionDatabase} from './all-position-week-fixture.mjs';
const runtime=process.env.JMAX_HANDOFF_RUNTIME??'.sites-runtime/shared';
const {handleWorkspace}=await import('../'+runtime+'/service.mjs');
const beforeMode=process.env.JMAX_RECOVERY_EXPECT_UNSUPPORTED==='1',receipts=[],dir='evidence/hour-trial/ai-quality';fs.mkdirSync(dir,{recursive:true});
async function fixture(t,location='berts'){
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'jmax-handoff-recovery-')),file=path.join(tmp,'case.sqlite');const open=()=>{const dbStore=openPositionDatabase(file),batch=dbStore.db.batch.bind(dbStore.db);let pending=Promise.resolve();dbStore.db.batch=statements=>{const operation=pending.then(()=>batch(statements));pending=operation.catch(()=>{});return operation;};return dbStore;};let store=open();const NativeDate=globalThis.Date,fixed=NativeDate.parse('2026-10-21T15:00:00Z');globalThis.Date=class extends NativeDate{constructor(...args){super(...(args.length?args:[fixed]));}static now(){return fixed;}};
 t.after(()=>{store.close();fs.rmSync(tmp,{recursive:true,force:true});globalThis.Date=NativeDate;});for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())store.sqlite.exec(fs.readFileSync('drizzle/'+f,'utf8').replaceAll('--> statement-breakpoint',''));
 for(const loc of ['berts','rudds','papa'])store.sqlite.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').run(loc,'Fictional '+loc,'America/New_York');const caps=['tasks.manage','schedule.publish','close.confirm'];
 for(const [id,area,position,permissions,loc=location]of[['outgoing','BOH','BOH Manager',caps],['absent','BOH','BOH Manager',caps],['replacement','BOH','BOH Manager',caps],['alternate','BOH','BOH Manager',caps],['gm','BOH','General Manager',[...caps,'location.manage','operations.escalation']],['front','FOH','FOH Manager',caps],['employee','BOH','Cook',[]],['foreign','BOH','BOH Manager',caps,location==='berts'?'rudds':'berts']])store.sqlite.prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').run(id,id+'@example.test',id+'-identity',loc,'Fictional '+id,area,position,JSON.stringify(permissions),JSON.stringify([position]));
 const snapshot=()=>JSON.stringify(Object.fromEntries(['records','command_receipts','audit_events'].map(table=>[table,store.sqlite.prepare('SELECT * FROM '+table+' ORDER BY rowid').all()]))),req=(actor,body,loc=location)=>new Request('https://recovery.example/api/workspace?locationId='+loc,{headers:{'oai-authenticated-user-id':actor+'-identity','oai-authenticated-user-email':actor+'@example.test',Origin:'https://recovery.example','Content-Type':'application/json'},...(body?{method:'POST',body:JSON.stringify(body)}:{})});
 const raw=async(actor,action,input={},record,rid=crypto.randomUUID(),loc=location)=>{const r=await handleWorkspace(req(actor,{requestId:rid,locationId:loc,action,input,...(record?{recordId:record.recordId??record.id,expectedRevision:record.revision}:{})},loc),store.db);return {status:r.status,data:await r.json()};},cmd=async(...args)=>{const r=await raw(...args);assert.equal(r.status,200,JSON.stringify(r.data));return r.data;},denied=async(status,...args)=>{const before=snapshot(),r=await raw(...args);assert.equal(r.status,status,JSON.stringify(r.data));assert.equal(snapshot(),before);return r;},record=id=>{const r=store.sqlite.prepare('SELECT * FROM records WHERE id=?').get(id);return {...r,id:r.id,ownerId:r.owner_id,locationId:r.location_id,data:JSON.parse(r.data)};},view=async(actor)=>{const r=await handleWorkspace(req(actor),store.db);assert.equal(r.status,200);return r.json();};
 const lead=async(id,area='BOH',start='2026-10-21T08:00:00Z',end='2026-10-21T22:00:00Z')=>cmd('gm','leadership.assign',{personId:id,area,start,end,note:'Explicit fictional leadership assignment'});
 const outgoing=await lead('outgoing','BOH','2026-10-20T08:00:00Z','2026-10-20T22:00:00Z'),absent=await lead('absent'),replacement=await lead('replacement'),alternate=await lead('alternate'),front=await lead('front','FOH');let handoff=await cmd('outgoing','handoff.create',{title:'Unresolved overnight work',detail:'Reported fictional unfinished work; original safe deferral assessment remains a report, not physical proof.',outgoingLeadershipId:outgoing.recordId,incomingId:'absent',incomingLeadershipId:absent.recordId,priority:'urgent',safeToDefer:true});handoff=await cmd('absent','handoff.transition',{step:'accept',note:'Named incoming manager accepted; work not resolved'},handoff);
 return {location,store:()=>store,raw,cmd,denied,record,view,snapshot,lead,handoff,replacement,alternate,front,absent,outgoing,reopen:()=>{const state=snapshot();store.close();store=open();assert.equal(snapshot(),state);},input:(receiver='replacement',leadership=replacement)=>({step:'recover',incomingId:receiver,incomingLeadershipId:leadership.recordId,note:'Accepted owner absent; named acting manager retains responsibility until eligible replacement explicitly accepts.'})};
}
for(const loc of ['berts','rudds','papa'])test(loc+': accepted-owner absence recovery retains responsibility until replacement accepts',async t=>{
 const f=await fixture(t,loc),original=f.record(f.handoff.recordId);f.store().sqlite.prepare('UPDATE memberships SET active=0,revision=revision+1 WHERE id=?').run('absent');f.store().sqlite.prepare('UPDATE memberships SET active=0,revision=revision+1 WHERE id=?').run('outgoing');
 if(beforeMode){const r=await f.denied(400,'gm','handoff.transition',f.input(),f.handoff);receipts.push({restaurant:loc,case:'unsupported accepted handoff recovery before fix',status:r.status,error:r.data.error});return;}
 const recovered=await f.cmd('gm','handoff.transition',f.input(),f.handoff,'recover-'+loc),after=f.record(recovered.recordId);assert.equal(after.ownerId,'gm');assert.equal(after.data.phase,'offered');assert.equal(after.data.outgoingId,original.data.outgoingId);assert.equal(after.data.outgoingLeadershipId,original.data.outgoingLeadershipId);assert.equal(after.data.incomingId,'replacement');assert.equal(after.data.detail,original.data.detail);assert.equal(after.data.priority,'urgent');assert.deepEqual(after.data.history.slice(0,-1),original.data.history);const notices=f.store().sqlite.prepare("SELECT owner_id,data FROM records WHERE kind='message'").all().filter(n=>JSON.parse(n.data).title==='Unresolved overnight work: offered');assert.deepEqual(new Set(notices.flatMap(n=>JSON.parse(n.data).recipients)),new Set(['gm','replacement']));assert.ok(notices.every(n=>JSON.parse(n.data).body.includes('until the named replacement accepts')));assert.ok(after.data.history.some(h=>h.action==='accept'));assert.equal(after.data.history.at(-1).action,'recover');f.reopen();await f.denied(400,'gm','handoff.transition',{step:'resolve',note:'Cannot resolve offered responsibility'},recovered);await f.denied(404,'employee','handoff.transition',{step:'accept',note:'Employee cannot accept manager work'},recovered);f.store().sqlite.prepare('UPDATE memberships SET active=1,revision=revision+1 WHERE id=?').run('absent');await f.denied(409,'absent','handoff.transition',{step:'resolve',note:'Old accepted snapshot must not resolve the recovered offer'},f.handoff);await f.denied(403,'absent','handoff.transition',{step:'accept',note:'Former receiver cannot reclaim offer'},recovered);await f.denied(403,'absent','handoff.transition',{step:'resolve',note:'Former owner cannot resolve'},recovered);
 const accepted=await f.cmd('replacement','handoff.transition',{step:'accept',note:'Replacement explicitly accepts unresolved responsibility'},recovered);assert.equal(f.record(accepted.recordId).ownerId,'replacement');assert.equal(f.record(accepted.recordId).data.phase,'accepted');await f.denied(403,'gm','handoff.transition',{step:'resolve',note:'Acting former owner cannot resolve'},accepted);const resolved=await f.cmd('replacement','handoff.transition',{step:'resolve',note:'Fictional current owner records actual reported remedy'},accepted);assert.equal(f.record(resolved.recordId).data.phase,'resolved');await f.denied(400,'gm','handoff.transition',f.input(),resolved);receipts.push({restaurant:loc,case:'accepted recovery receipt and ownership',passed:true,durableReopen:true,originalOutgoingPreserved:true});
});
if(!beforeMode){
 test('recovery enforces active leadership, department, restaurant and a different receiver',async t=>{const f=await fixture(t);await f.denied(404,'front','handoff.transition',f.input(),f.handoff);await f.denied(404,'employee','handoff.transition',f.input(),f.handoff);await f.denied(403,'foreign','handoff.transition',f.input(),f.handoff);await f.denied(400,'gm','handoff.transition',f.input('foreign'),f.handoff);await f.denied(400,'gm','handoff.transition',f.input('front',f.front),f.handoff);await f.denied(400,'gm','handoff.transition',f.input('gm'),f.handoff);await f.denied(400,'gm','handoff.transition',f.input('absent',f.absent),f.handoff);const revoked=await f.cmd('gm','leadership.revoke',{note:'Replacement cannot receive with revoked leadership'},f.replacement);await f.denied(400,'gm','handoff.transition',f.input('replacement',revoked),f.handoff);const expired=await f.lead('replacement','BOH','2026-10-21T01:00:00Z','2026-10-21T07:00:00Z');await f.denied(400,'gm','handoff.transition',f.input('replacement',expired),f.handoff);receipts.push({case:'recovery source and access boundaries',passed:true});});
 test('department manager may recover and reoffer while remaining current responsible owner',async t=>{const f=await fixture(t);let work=await f.cmd('outgoing','handoff.transition',f.input(),f.handoff);assert.equal(f.record(work.recordId).ownerId,'outgoing');work=await f.cmd('replacement','handoff.transition',{step:'dispute',note:'Replacement reports condition requiring clarification'},work);work=await f.cmd('outgoing','handoff.transition',{step:'offer',incomingId:'alternate',incomingLeadershipId:f.alternate.recordId,note:'Current owner clarifies and names different eligible replacement'},work);assert.equal(f.record(work.recordId).ownerId,'outgoing');work=await f.cmd('alternate','handoff.transition',{step:'accept',note:'Named second replacement explicitly accepts'},work);assert.equal(f.record(work.recordId).ownerId,'alternate');receipts.push({case:'department recovery disputed reoffer',passed:true});});
 test('GM recovery reoffer uses current owner rather than original outgoing identity',async t=>{const f=await fixture(t);let work=await f.cmd('gm','handoff.transition',f.input(),f.handoff);work=await f.cmd('replacement','handoff.transition',{step:'dispute',note:'Need clarification before acceptance'},work);await f.denied(403,'outgoing','handoff.transition',{step:'offer',incomingId:'alternate',incomingLeadershipId:f.alternate.recordId,note:'Original outgoing identity is no longer responsible'},work);work=await f.cmd('gm','handoff.transition',{step:'offer',incomingId:'alternate',incomingLeadershipId:f.alternate.recordId,note:'Acting current owner offers the clarified current condition'},work);assert.equal(f.record(work.recordId).ownerId,'gm');assert.equal(f.record(work.recordId).data.outgoingId,'outgoing');receipts.push({case:'current recovery owner reoffer',passed:true});});
 test('recovery retries are atomic and competing stale requests cannot overwrite ownership',async t=>{const f=await fixture(t);f.store().sqlite.exec("CREATE TRIGGER interrupt_recovery BEFORE UPDATE ON records WHEN OLD.id='"+f.handoff.recordId+"' BEGIN SELECT RAISE(ABORT,'Fictional storage failure'); END");await f.denied(503,'gm','handoff.transition',f.input(),f.handoff,'failed-recovery');f.store().sqlite.exec('DROP TRIGGER interrupt_recovery');const original=f.handoff,first=await f.cmd('gm','handoff.transition',f.input(),original,'safe-recovery-retry'),snapshot=f.snapshot();assert.deepEqual(await f.cmd('gm','handoff.transition',f.input(),original,'safe-recovery-retry'),first);assert.equal(f.snapshot(),snapshot);await f.denied(409,'outgoing','handoff.transition',f.input('alternate',f.alternate),original,'stale-competing-recovery');await f.denied(409,'gm','handoff.transition',{...f.input(),note:'Changed text is not the same retry'},original,'safe-recovery-retry');assert.equal(f.record(first.recordId).ownerId,'gm');assert.equal(f.record(first.recordId).data.incomingId,'replacement');receipts.push({case:'recovery atomic retry and competing stale request',passed:true});});
 test('recovered offer rejects replacement leadership revoked before receipt',async t=>{const f=await fixture(t);const recovered=await f.cmd('gm','handoff.transition',f.input(),f.handoff);await f.cmd('gm','leadership.revoke',{note:'Replacement authority revoked before receipt'},f.replacement);await f.denied(400,'replacement','handoff.transition',{step:'accept',note:'Revoked recipient cannot accept'},recovered);assert.equal(f.record(recovered.recordId).ownerId,'gm');assert.equal(f.record(recovered.recordId).data.phase,'offered');receipts.push({case:'recovered receiver rechecks current authority',passed:true});});
 test('two simultaneous authorized recoveries commit exactly one transition',async t=>{const f=await fixture(t);const before=f.snapshot();const results=await Promise.all([f.raw('gm','handoff.transition',f.input(),f.handoff,'concurrent-gm'),f.raw('outgoing','handoff.transition',f.input('alternate',f.alternate),f.handoff,'concurrent-department')]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const current=f.record(f.handoff.recordId);assert.equal(current.data.history.filter(h=>h.action==='recover').length,1);assert.equal(current.revision,f.handoff.revision+1);assert.ok(['gm','outgoing'].includes(current.ownerId));assert.notEqual(f.snapshot(),before);receipts.push({case:'simultaneous current-revision recovery',passed:true,statuses:results.map(r=>r.status),oneHistoryTransition:true});});

 test('recovered offer rejects authority expired between offer and acceptance',async t=>{const f=await fixture(t);const recovered=await f.cmd('gm','handoff.transition',f.input(),f.handoff),BaseDate=Date,future=BaseDate.parse('2026-10-22T15:00:00Z');globalThis.Date=class extends BaseDate{constructor(...args){super(...(args.length?args:[future]));}static now(){return future;}};await f.denied(400,'replacement','handoff.transition',{step:'accept',note:'Prior-day leadership is no longer eligible for recovered responsibility'},recovered);assert.equal(f.record(recovered.recordId).ownerId,'gm');receipts.push({case:'recovered receipt expires with receiver leadership',passed:true});});

 test('urgent recovery cannot lose its authorized escalation route',async t=>{const f=await fixture(t);f.store().sqlite.prepare('UPDATE memberships SET capabilities=?,revision=revision+1 WHERE id=?').run(JSON.stringify(['tasks.manage','schedule.publish','close.confirm','location.manage']),'gm');await f.denied(400,'gm','handoff.transition',f.input(),f.handoff);assert.equal(f.record(f.handoff.recordId).data.priority,'urgent');assert.equal(f.record(f.handoff.recordId).ownerId,'absent');receipts.push({case:'urgent escalation recipient required without partial writes',passed:true});});

}
test.after(()=>fs.writeFileSync(dir+(beforeMode?'/handoff-recovery-before-fix.json':'/handoff-recovery-final.json'),JSON.stringify({fictional:true,externalProviderCalls:0,proof:'Actual authenticated workspace handlers with durable SQLite. Reported absence/checks are fictional; no model, hardware, payroll or hosted mutation.',receipts},null,2)+'\n'));
