import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {spawnSync} from 'node:child_process';
import {localTrial,managerCaps} from './hour-trial-local-fixture.mjs';
import {handleFood} from '../.sites-runtime/shared/food-service.mjs';
import {handleEmployeePrep} from '../.sites-runtime/shared/employee-prep-service.mjs';
import {handleFoodWorkflows} from '../.sites-runtime/shared/food-workflow-service.mjs';
import {handleFoodAdvisor} from '../.sites-runtime/shared/food-advisor-service.mjs';
import {configuredFoodAdvisorProvider} from '../.sites-runtime/shared/food-advisor-provider.mjs';
import {handleFoodTransfers} from '../.sites-runtime/shared/food-transfer-service.mjs';

function fresh(h,actor,loc,route,body,dataset='operating',query=''){const r=spawnSync(process.execPath,['tests/hour-trial-reopen-command.mjs'],{input:JSON.stringify({file:h.file,actor,loc,route,body,dataset,query}),encoding:'utf8',timeout:15000});assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout);}
const body=(loc,action,input,record,requestId=crypto.randomUUID())=>({locationId:loc,action,input,requestId,...(record?{recordId:record.recordId??record.id,expectedRevision:record.revision}:{})});
function audit(h,id){const report={id,cases:[],failures:[],sourceRevision:h.sourceRevision,database:h.file,initialSeeds:1,operationalReseeds:0,limits:['Fictional durable database and actual local authenticated handlers; no production data or provider calls.','Fresh Node subprocesses prove process restart continuity; provider error responses are injected locally.','Direct recipe deletion/revision changes are labelled upstream-fault injection, not an implemented Jeff synchronization path.']};return{report,async check(name,fn){try{await fn();report.cases.push({name,status:'passed'});}catch(e){report.failures.push({name,error:String(e.stack)});throw e;}},save(){report.sourceRevisionAfter=h.sourceHashes();report.sourceUnchanged=JSON.stringify(report.sourceRevisionAfter)===JSON.stringify(report.sourceRevision);h.close();fs.writeFileSync(h.file.replace('.sqlite','.json'),JSON.stringify(report,null,2)+'\n');}};}

test('Upstream outage across process restart retains local assigned prep and never invents missing or changed recipe success',async()=>{
 const h=localTrial('commissary/outage',[{id:'manager',loc:'berts',position:'BOH Manager',caps:managerCaps},{id:'cook',loc:'berts',position:'Cook'}]);const a=audit(h,'durable-upstream-outage');
 const rawRecipe={title:'Fictional source recipe',sourceId:'source-recipe',recipeType:'prep',procedure:'Fictional reviewed method',equipment:'Fictional vessel',portionNote:'Fictional source portions',yieldQty:4,yieldUOM:'cup',shelfLife:'Fictional 3-day source metadata',lines:[],costCents:123};
 const insertRecipe=(id,source)=>h.sqlite.prepare('INSERT INTO food_records(id,location_id,kind,dataset,source_restaurant_id,source_key,title,owner_id,area,revision,data,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,'berts','foodrecipe','operating','fictional-berts',id,rawRecipe.title,'manager','BOH',1,JSON.stringify({...rawRecipe,source}),new Date().toISOString());
 const line=id=>({definitionId:id+'-line',foodRecordId:id,foodRevision:1,title:rawRecipe.title,countUnit:'cup',par:4,quantity:1,plannedQty:3,completedQty:null,completedAt:null,completedBy:null,completionNote:'',assignedTo:'cook'});
 const plan=id=>({id:id+'-plan',locationId:'berts',dataset:'operating',revision:1,kind:'plan',status:'released',targetDate:'2026-10-08',track:'daily',countId:'fixture-count',countRevision:1,lines:[line(id)],blockers:[],createdBy:'manager',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),releasedBy:'manager',releasedAt:new Date().toISOString()});
 try{
  for(const id of ['cached','changed','missing']){insertRecipe(id,{dataset:'operating',sourceRestaurantId:'fictional-berts'});const p=plan(id);h.sqlite.prepare('INSERT INTO food_workflows(id,location_id,dataset,kind,natural_key,revision,status,data,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(p.id,'berts','operating','plan',id,1,'released',JSON.stringify(p),new Date().toISOString());}
  h.sqlite.prepare('INSERT INTO food_sources(location_id,dataset,source_restaurant_id) VALUES(?,?,?)').run('berts','operating','fictional-berts');
  const call=(handler,actor,route,b)=>h.call(handler,actor,route,'berts',b,'&dataset=operating');const state=h.snapshot();
  await a.check('missing configured source token yields explicit unavailable while released local prep stays saved',async()=>{let networkCalls=0;const provider=configuredFoodAdvisorProvider({FOOD_ADVISOR_SOURCE_URL:'https://fictional.invalid',FOOD_ADVISOR_RESTAURANT_BINDINGS:'{"berts":"fictional-berts"}'},async()=>{networkCalls++;return Response.json({});});assert.equal(provider,undefined);const response=h.ok(await call((r,db)=>handleFoodAdvisor(r,db,provider),'manager','food/advisor'));assert.equal(response.status,'unavailable');assert.deepEqual(response.rows,[]);assert.equal(networkCalls,0);assert.equal(h.snapshot(),state);});
  await a.check('fresh process opens cached released instructions without claiming a hosted source connection',async()=>{const response=h.ok(fresh(h,'cook','berts','food/assigned-prep'));assert.equal(response.items.length,3);assert.equal(response.items[0].recipe.procedure,rawRecipe.procedure);assert.equal(h.snapshot(),state);a.report.cachedLocalRecipeReadable=true;});
  await a.check('expired source credentials and timeout return unavailable error with no advisory write or fake success',async()=>{for(const failure of ['401','timeout']){let calls=0;const provider=configuredFoodAdvisorProvider({FOOD_ADVISOR_SOURCE_URL:'https://fictional.invalid',FOOD_ADVISOR_SOURCE_TOKEN:'FICTIONAL-NOT-A-CREDENTIAL',FOOD_ADVISOR_RESTAURANT_BINDINGS:'{"berts":"fictional-berts"}'},async()=>{calls++;if(failure==='timeout')throw new Error('Fictional timeout');return new Response('Fictional authorization expired',{status:401});});const response=await call((r,db)=>handleFoodAdvisor(r,db,provider),'manager','food/advisor');assert.equal(response.status,503);assert.match(response.data.error,/could not be read.*No recommendation was applied/);assert.equal(calls,1);assert.equal(h.snapshot(),state);}});
  await a.check('changed and missing upstream recipe snapshots stay blocked after genuine process restart',async()=>{h.sqlite.prepare("UPDATE food_records SET revision=2 WHERE id='changed'").run();h.sqlite.prepare("DELETE FROM food_records WHERE id='missing'").run();const changedState=h.snapshot();h.reopen();const view=h.ok(fresh(h,'cook','berts','food/assigned-prep'));const changed=view.items.find(i=>i.foodRecordId==='changed'),missing=view.items.find(i=>i.foodRecordId==='missing');assert.equal(changed.recipe,null);assert.match(changed.recipeNotice,/changed/);assert.equal(missing.recipe,null);assert.match(missing.recipeNotice,/current preparation instructions/);for(const id of ['changed','missing']){const response=fresh(h,'cook','berts','food/workflows',body('berts','plan.employee-complete',{dataset:'operating',definitionId:id+'-line',quantity:3,note:'Cannot complete unsupported stale instructions',confirmed:true},{recordId:id+'-plan',revision:1}));assert.equal(response.status,id==='missing'?404:409);assert.equal(h.snapshot(),changedState);}a.report.recipeFaultsExplicit=true;});
  await a.check('cached valid recipe completion during source outage is one durable local result, not inventory synchronization',async()=>{const stock=JSON.stringify(h.sqlite.prepare('SELECT * FROM food_records ORDER BY id').all()),command=body('berts','plan.employee-complete',{dataset:'operating',definitionId:'cached-line',quantity:0,note:'Ingredient unavailable; fictional manager follow-up required.',confirmed:true},{recordId:'cached-plan',revision:1},'cached-local-save');const first=h.ok(fresh(h,'cook','berts','food/workflows',command));const after=h.snapshot();const retried=h.ok(fresh(h,'cook','berts','food/workflows',command));assert.deepEqual(retried,first);assert.equal(h.snapshot(),after);assert.equal(JSON.stringify(h.sqlite.prepare('SELECT * FROM food_records ORDER BY id').all()),stock);assert.equal(h.sqlite.prepare("SELECT count(*) AS n FROM food_workflow_events WHERE workflow_id='cached-plan'").get().n,1);assert.equal(h.sqlite.prepare("SELECT count(*) AS n FROM food_receipts WHERE request_id='cached-local-save'").get().n,1);});
 }catch(e){if(!a.report.failures.length)a.report.failures.push({name:'fixture/final',error:String(e.stack)});}finally{a.save();}assert.deepEqual(a.report.failures,[],JSON.stringify(a.report.failures));assert.equal(a.report.sourceUnchanged,true);
});

test('Commissary receiving process retry and interleaved reviewer commits retain one result without double stock',async()=>{
 const h=localTrial('commissary/outage',[{id:'source',loc:'comm',position:'Commissary Manager',caps:managerCaps},{id:'receiver',loc:'berts',position:'BOH Manager',caps:managerCaps},{id:'reviewer',loc:'berts',position:'BOH Manager',caps:managerCaps}],['comm','berts','rudds','papa']);const a=audit(h,'receipt-process-retry-conflicts');
 const tx=(actor,loc,action,input,record,rid)=>h.call(handleFoodTransfers,actor,'food/transfers',loc,body(loc,action,{dataset:'demo',...input},record,rid),'&dataset=demo');
 try{
  const item=h.ok(await h.call(handleFood,'source','food','comm',body('comm','fooditem.import',{dataset:'demo',sourceRestaurantId:'fictional-comm',sourceLabel:'Fictional outage test',destinationLocationId:'comm',confirmed:true,rows:[{restaurantId:'fictional-comm',name:'Fictional ranch vessel',controlNumber:'RANCH',purchaseUnit:'vessel',packCount:1,unitQty:5,unitUOM:'gal',portionSize:1,portionUOM:'gal',par:6,active:true,countActive:true,needsReview:false,vendorSkus:[]}]})));
  h.sqlite.prepare("INSERT INTO food_transfer_routes(source_id,destination_id,dataset,active) VALUES('comm','berts','demo',1)").run();const stock=JSON.stringify(h.sqlite.prepare('SELECT * FROM food_records ORDER BY id').all());
  const input={destinationId:'berts',itemId:item.recordId,itemRevision:item.revision,reference:'FICTITIOUS-RETRY',quantity:5,dispatchedAt:new Date().toISOString(),note:'Fictional transfer; not a real delivery',confirmed:true};
  let sent=h.ok(await tx('source','comm','transfer.dispatch',input));
  const receive={accepted:4,rejected:1,missing:0,receivedAt:new Date().toISOString(),complete:true,note:'Fictional destination check',reason:'One rejected vessel',confirmed:true};
  await a.check('destination final receipt saved by fresh process can replay after a second process starts exactly once',async()=>{const command=body('berts','transfer.receive',{dataset:'demo',...receive},sent,'delivery-check-response-lost'),first=h.ok(fresh(h,'receiver','berts','food/transfers',command,'demo'));const before=h.snapshot();assert.deepEqual(h.ok(fresh(h,'receiver','berts','food/transfers',command,'demo')),first);assert.equal(h.snapshot(),before);assert.equal(h.sqlite.prepare('SELECT count(*) AS n FROM food_transfer_events WHERE transfer_id=?').get(sent.recordId).n,2);assert.equal(h.sqlite.prepare("SELECT count(*) AS n FROM food_receipts WHERE request_id='delivery-check-response-lost'").get().n,1);sent=first;});
  await a.check('changed retry payload cannot reuse the durable receipt identifier',async()=>{const before=h.snapshot();const response=fresh(h,'receiver','berts','food/transfers',body('berts','transfer.receive',{dataset:'demo',...receive,accepted:5,rejected:0}, {recordId:sent.recordId,revision:1},'delivery-check-response-lost'),'demo');assert.equal(response.status,409);assert.equal(h.snapshot(),before);});
  let raced=h.ok(await tx('source','comm','transfer.dispatch',{...input,reference:'FICTITIOUS-RACE'}));
  await a.check('second reviewer commits while first read is in flight; first stale revision cannot overwrite receipt',async()=>{let winning,interleaved=false;const wrapped={prepare:sql=>h.db.prepare(sql),withSession:()=>wrapped,batch:async statements=>{if(!interleaved){interleaved=true;winning=h.ok(fresh(h,'reviewer','berts','food/transfers',body('berts','transfer.receive',{dataset:'demo',...receive},raced,'receipt-reviewer-winner'),'demo'));}return h.db.batch(statements);}};const staleReq=h.request('receiver','food/transfers','berts',body('berts','transfer.receive',{dataset:'demo',...receive,accepted:3,rejected:1,missing:1,reason:'Stale first count'},raced,'receipt-stale-reader'));const response=await handleFoodTransfers(staleReq,wrapped);assert.equal(response.status,409);assert.equal(interleaved,true);raced=winning;const row=h.sqlite.prepare('SELECT data FROM food_transfers WHERE id=?').get(raced.recordId);assert.equal(JSON.parse(row.data).receipt.by,'reviewer');assert.equal(JSON.parse(row.data).receipt.accepted,4);assert.equal(h.sqlite.prepare('SELECT count(*) AS n FROM food_transfer_events WHERE transfer_id=?').get(raced.recordId).n,2);assert.equal(h.sqlite.prepare("SELECT count(*) AS n FROM food_receipts WHERE request_id='receipt-stale-reader'").get().n,0);a.report.interleavedReceiptWinner='reviewer';});
  await a.check('concurrent source dispatch of same reference has one fresh-process winner and no duplicate transfer',async()=>{let interleaved=false;const next={...input,reference:'FICTITIOUS-DISPATCH-RACE'};const wrapped={prepare:sql=>h.db.prepare(sql),withSession:()=>wrapped,batch:async statements=>{if(!interleaved){interleaved=true;h.ok(fresh(h,'source','comm','food/transfers',body('comm','transfer.dispatch',{dataset:'demo',...next},undefined,'dispatch-second-winner'),'demo'));}return h.db.batch(statements);}};const response=await handleFoodTransfers(h.request('source','food/transfers','comm',body('comm','transfer.dispatch',{dataset:'demo',...next},undefined,'dispatch-first-stale')),wrapped);assert.equal(response.status,409);assert.equal(h.sqlite.prepare("SELECT count(*) AS n FROM food_transfers WHERE json_extract(data,'$.dispatch.reference')='FICTITIOUS-DISPATCH-RACE'").get().n,1);assert.equal(h.sqlite.prepare("SELECT count(*) AS n FROM food_receipts WHERE request_id='dispatch-first-stale'").get().n,0);});
  await a.check('successful receipt history survives reopen and no receiving or race posts catalog stock',async()=>{h.reopen();assert.equal(JSON.stringify(h.sqlite.prepare('SELECT * FROM food_records ORDER BY id').all()),stock);const result=h.ok(fresh(h,'reviewer','berts','food/transfers',undefined,'demo','&status=all'));assert.equal(result.total,3);a.report.catalogUnchanged=true;});
 }catch(e){if(!a.report.failures.length)a.report.failures.push({name:'fixture/final',error:String(e.stack)});}finally{a.save();}assert.deepEqual(a.report.failures,[],JSON.stringify(a.report.failures));assert.equal(a.report.sourceUnchanged,true);
});
