import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {localTrial,managerCaps} from './hour-trial-local-fixture.mjs';

test('Three restaurants: sixty durable conversation days cross archive limits, recall old reports and exclude revoked work',async()=>{
 const runtime=path.resolve('evidence/hour-trial/commissary/long-conversation/runtime-'+crypto.randomUUID());fs.mkdirSync(runtime,{recursive:true});
 for(const f of fs.readdirSync('.sites-runtime/shared').filter(f=>f.endsWith('.mjs')))fs.copyFileSync('.sites-runtime/shared/'+f,path.join(runtime,f));
 const hashes=()=>Object.fromEntries(fs.readdirSync(runtime).sort().map(f=>[f,createHash('sha256').update(fs.readFileSync(path.join(runtime,f))).digest('hex')]));const before=hashes();
 const {handleCompanionChat}=await import(pathToFileURL(path.join(runtime,'companion-chat.mjs')).href);const {handleWorkspace}=await import(pathToFileURL(path.join(runtime,'service.mjs')).href);
 const RealDate=Date;let now=RealDate.parse('2026-10-08T15:00:00-04:00');globalThis.Date=class extends RealDate{constructor(...a){super(...(a.length?a:[now]));}static now(){return now;}};
 const all=[];
 try{for(const loc of ['berts','rudds','papa']){
  now=RealDate.parse('2026-10-08T15:00:00-04:00');const position=loc==='papa'?'Counter':'Server';const actors=[{id:'worker',loc,position,area:'FOH'},{id:'backup',loc,position,area:'FOH'},{id:'manager',loc,position:'General manager',caps:managerCaps}];
  const h=localTrial('commissary/long-conversation/'+loc,actors);const report={restaurant:loc,position,days:[],cases:[],failures:[],initialSeeds:1,operationalReseeds:0,runtime,runtimeRevision:before,database:h.file,limits:['Two asks per simulated day plus targeted recall probes use a mock provider to inspect actual authorized retrieval. No generated-helpfulness claim.','Distinctive markers are fictional personal reports and work problems, not operating policy.','Fresh Node processes perform weekly history reads and a supported preference write; the active app handlers use a pinned compiled runtime. No external calls.']};all.push(report);
  const call=(actor,b,query='')=>h.call((r,db)=>handleCompanionChat(r,db,{OPENAI_API_KEY:'sk-fictional-only',JMAX_OPENAI_MODEL:'gpt-5.4-mini'},provider,()=>now,'workforce'),actor,'companion',loc,b,query);
  const cmd=async(actor,action,input,record)=>h.ok(await h.call(handleWorkspace,actor,'workspace',loc,{locationId:loc,requestId:crypto.randomUUID(),action,input,...(record?{recordId:record.recordId??record.id,expectedRevision:record.revision}:{})}));
  const fresh=(query='',body)=>{const r=spawnSync(process.execPath,['tests/hour-trial-conversation-reopen.mjs'],{input:JSON.stringify({runtime,file:h.file,actor:'worker',loc,now,query,body}),encoding:'utf8',timeout:15000});assert.equal(r.status,0,r.stderr);return h.ok(JSON.parse(r.stdout));};
  let context,lastQuestion,conversation,providerCalls=0,task;const original={};
  const provider=async(_url,init)=>{providerCalls++;const input=JSON.parse(init.body).input;context=JSON.parse(input[1].content.split('\n').slice(1).join('\n'));lastQuestion=input.at(-1).content;const sourceIds=context.selectedWork?[context.selectedWork.id]:[];return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({answer:'Fictional retrieval audit only. Historical reports do not prove completed work or approved policy. Chat has not saved or notified anyone.',sourceIds})}]}]});};
  const check=async(name,fn)=>{try{await fn();report.cases.push({name,status:'passed'});}catch(e){report.failures.push({name,error:String(e.stack),lastQuestion,providerMemory:context?.priorConversationMemory});throw e;}};
  const ask=async(question,focus,requestId)=>{conversation=h.ok(await call('worker'));if(conversation.full){const old=conversation.conversationId;conversation=h.ok(await call('worker',{locationId:loc,action:'start-new',conversationId:old,expectedRevision:conversation.revision}));report.archivesRotated=(report.archivesRotated??0)+1;assert.notEqual(conversation.conversationId,old);assert.equal(conversation.explanationStyle,'brief');}now+=6000;const response=h.ok(await call('worker',{locationId:loc,action:'ask',conversationId:conversation.conversationId,expectedRevision:conversation.revision,requestId,question,...(focus?{focus:{id:focus.recordId,revision:focus.revision}}:{})}));assert.equal(response.turns.at(-1).status,'complete');conversation=response;return response;};
  try{
   task=await cmd('manager','task.create',{ownerId:'worker',title:'AmberSpool unfinished issue '+loc,detail:'Fictional AmberSpool cold item discrepancy remains unresolved. Do not claim it was completed; contact the assigned manager.',kind:'issue',due:new Date(now+70*86400000).toISOString()});const initialTaskId=task.recordId;
   conversation=h.ok(await call('worker'));conversation=h.ok(await call('worker',{locationId:loc,action:'preferences',conversationId:conversation.conversationId,expectedRevision:conversation.revision,explanationStyle:'brief'}));
   for(let day=1;day<=60;day++){
    const start=now;report.days.push({day,week:Math.ceil(day/7)});
    if(day===55)await check('day55 source ownership revocation invalidates old operating memory without deleting personal report',async()=>{task=await cmd('manager','task.reassign',{ownerId:'backup',note:'Responsibility moved to authorized backup; former worker must not follow old operating advice.'},task);assert.equal(h.find(task.recordId).ownerId,'backup');report.revocation={day,recordId:task.recordId,currentRevision:task.revision};});
    for(let i=0;i<2;i++){const id=`${loc}-day-${day}-ask-${i}`;if(day===1&&i===0){const q='I prefer Marigold explanations with short sentences and one concrete example for restaurant work. This is my communication preference.';await ask(q,undefined,id);original.personal=id;original.personalConversation=conversation.conversationId;}else if(day===1&&i===1){await ask('My fictional AmberSpool issue is still unfinished; remember the saved ownership and next action, and do not claim it is complete.',task,id);original.operational=id;original.operationalConversation=conversation.conversationId;}else await ask(`Daily restaurant reporting observation ${day}, pass ${i}: explain how to distinguish a reported condition from a verified action.`,undefined,id);}
    if([30,45,60].includes(day))await check(`day${day} relevant recall reaches old archives beyond latest sixteen turns`,async()=>{
     const recordsBefore=JSON.stringify(h.sqlite.prepare('SELECT * FROM records ORDER BY rowid').all());await ask('Recall my Marigold communication preference and original AmberSpool unfinished issue report. Which older reports are supplied, and which work sources are still authorized?',undefined,`${loc}-day-${day}-recall`);
     const entries=context.priorConversationMemory.entries;assert.ok(entries.some(e=>e.requestId===original.personal),'Distinctive day1 personal report must be retrieved from its old archive');assert.ok(entries.find(e=>e.requestId===original.personal).userStatement.includes('short sentences'));assert.equal(entries.find(e=>e.requestId===original.personal).priorAssistantAnswer,undefined);
     if(day<55){assert.ok(entries.some(e=>e.requestId===original.operational),'Old unfinished work must be recalled before source revocation');assert.equal(h.find(initialTaskId).data.phase,'open');}else{assert.ok(!entries.some(e=>e.requestId===original.operational),'Former operating advice is no longer authorized');assert.ok(!entries.some(e=>e.sources.some(s=>s.id===initialTaskId&&s.revision===1)));}
     assert.equal(JSON.stringify(h.sqlite.prepare('SELECT * FROM records ORDER BY rowid').all()),recordsBefore);report.recallProof??=[];report.recallProof.push({day,originalPersonalRetrieved:true,originalOperationalRetrieved:entries.some(e=>e.requestId===original.operational),retrieved:entries.map(e=>({requestId:e.requestId,conversationId:e.conversationId,hasAssistantAnswer:e.priorAssistantAnswer!==undefined,sourceIds:e.sources.map(s=>s.id)})),currentQuestion:lastQuestion});
    });
    if(day%7===0)await check(`day${day} genuine fresh-process read and preference write preserve questions and archives`,async()=>{const snapshot=JSON.stringify(h.sqlite.prepare('SELECT * FROM companion_turns ORDER BY rowid').all());const view=fresh();assert.equal(view.conversationId,conversation.conversationId);assert.equal(view.explanationStyle,'brief');assert.equal(view.turns.length,conversation.turns.length);const history=fresh('&history=1');assert.equal(history.conversations.length,report.archivesRotated??0);conversation=fresh('',{locationId:loc,action:'preferences',conversationId:view.conversationId,expectedRevision:view.revision,explanationStyle:'brief'});assert.equal(conversation.revision,view.revision+1);assert.equal(conversation.explanationStyle,'brief');assert.equal(JSON.stringify(h.sqlite.prepare('SELECT * FROM companion_turns ORDER BY rowid').all()),snapshot);report.processRestarts=(report.processRestarts??0)+1;report.freshProcessWrites=(report.freshProcessWrites??0)+1;h.reopen();});
    report.completedDays=day;now=start+86400000;
   }
   await check('final archived reads retain report text while revoked source answers are stale and blank',async()=>{const archived=fresh('&archived='+original.operationalConversation);const operational=archived.turns.find(t=>t.id===original.operational),personal=archived.turns.find(t=>t.id===original.personal);assert.equal(operational.stale,true);assert.equal(operational.answer,'');assert.deepEqual(operational.sources,[]);assert.ok(personal.question.includes('Marigold'));assert.equal(h.find(initialTaskId).data.phase,'open');assert.equal(h.find(initialTaskId).ownerId,'backup');assert.equal(archived.turns.length,40);});
   assert.equal(h.sqlite.prepare('SELECT count(*) AS n FROM companion_turns').get().n,123);assert.equal(h.sqlite.prepare('SELECT count(*) AS n FROM companion_archives').get().n,3);assert.equal(providerCalls,123);report.finalDay=60;report.finalSourceOwner='backup';
  }catch(e){if(!report.failures.length)report.failures.push({name:'setup/final',error:String(e.stack)});}finally{report.totalSavedTurns=h.sqlite.prepare('SELECT count(*) AS n FROM companion_turns').get().n;report.savedArchives=h.sqlite.prepare('SELECT count(*) AS n FROM companion_archives').get().n;report.providerContextRequests=providerCalls;report.runtimeRevisionAfter=hashes();report.runtimeUnchanged=JSON.stringify(report.runtimeRevisionAfter)===JSON.stringify(before);h.close();fs.writeFileSync(h.file.replace('.sqlite','.json'),JSON.stringify(report,null,2)+'\n');}
 }}finally{globalThis.Date=RealDate;}
 const summary={runtime,runtimeUnchanged:JSON.stringify(hashes())===JSON.stringify(before),restaurants:all.map(r=>({restaurant:r.restaurant,attemptedDays:r.days.length,completedDays:r.completedDays,cases:r.cases.length,failures:r.failures,totalSavedTurns:r.totalSavedTurns,savedArchives:r.savedArchives,processRestarts:r.processRestarts,freshProcessWrites:r.freshProcessWrites,providerContextRequests:r.providerContextRequests,database:r.database}))};fs.writeFileSync(path.join(path.dirname(runtime),'summary-'+crypto.randomUUID()+'.json'),JSON.stringify(summary,null,2)+'\n');
 assert.equal(all.length,3);for(const r of all){assert.equal(r.days.length,60);assert.deepEqual(r.failures,[],JSON.stringify(r.failures));assert.equal(r.runtimeUnchanged,true);}assert.equal(summary.runtimeUnchanged,true);
});
