import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import ts from 'typescript';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {openPositionDatabase} from './all-position-week-fixture.mjs';

const runId=new Date().toISOString().replaceAll(':','-').replaceAll('.','-');
const evidence=path.resolve('evidence/hour-trial/dish-ui-acceptance',runId),compiled=path.resolve('.sites-runtime/hour-dish-ui',runId);
fs.mkdirSync(evidence,{recursive:true});fs.mkdirSync(compiled,{recursive:true});
const fingerprint=file=>({file,sha256:createHash('sha256').update(fs.readFileSync(file)).digest('hex')});
// Isolate the current source from the older frozen runtime used by long trials.
// This matches the repository's shared-test transpilation, without overwriting it.
const shared=path.join(compiled,'shared');fs.mkdirSync(shared,{recursive:true});
for(const name of fs.readdirSync('app/shared').filter(n=>n.endsWith('.ts'))){const js=ts.transpileModule(fs.readFileSync('app/shared/'+name,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replace(/from (['"])(\.\/[^'"]+)\1/g,(_,q,specifier)=>`from ${q}${specifier}.mjs${q}`);fs.writeFileSync(path.join(shared,name.replace('.ts','.mjs')),js);}
const {handleWorkspace}=await import(pathToFileURL(path.join(shared,'service.mjs'))),{closingStatus}=await import(pathToFileURL(path.join(shared,'closing-status.mjs'))),{workforceContext}=await import(pathToFileURL(path.join(shared,'workforce-context.mjs')));
const report={execution:'Actual local saved workspace states, React SSR and captured actual form callbacks; fictional records. Current source transpiled to an isolated runtime; frozen shared runtime is untouched.',sourceRevision:{isolatedRuntime:['domain','closing-status','shift-brief','workforce-context','service'].map(name=>fingerprint(path.join(shared,name+'.mjs'))),currentUi:['dish-checkouts','my-day','workspace-forms'].map(name=>fingerprint('app/team/'+name+'.tsx'))},checks:[],limits:['No browser click, viewport measurement or full mounted app navigation is exercised.','A JSX-runtime observer records rendered form callbacks without replacing component hooks or callback logic.','Acceptance records incoming responsibility; it does not complete PM work, perform a physical check or release an employee.','No live AI, Toast, Jeff or restaurant records are used.']};
// Observe real rendered native form props while forwarding React's JSX runtime.
// React itself still invokes components/hooks during server rendering.
const captureKey='__jmaxDishUiForms_'+runId;
const observer=path.join(compiled,'jsx-observer.mjs');
fs.writeFileSync(observer,`import {jsx as actualJsx,jsxs as actualJsxs,Fragment} from 'react/jsx-runtime';\nexport {Fragment};\nfunction observe(type,props){if(type==='form')globalThis[${JSON.stringify(captureKey)}]?.push(props);}\nexport function jsx(type,props,key){observe(type,props);return actualJsx(type,props,key);}\nexport function jsxs(type,props,key){observe(type,props);return actualJsxs(type,props,key);}\n`);
const visited=new Set();
function compile(file){if(visited.has(file))return;visited.add(file);const destination=path.join(compiled,path.relative(path.resolve('app'),file).replace(/\.tsx?$/,'.mjs'));let js=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;js=js.replace(/from (["'])react\/jsx-runtime\1/g,(_,q)=>`from ${q}${pathToFileURL(observer).href}${q}`).replace(/import ['"][^'"]+\.css['"];?/g,'').replace(/from (['"])(\.\.?\/[^'"]+)\1/g,(_,q,specifier)=>{const base=path.resolve(path.dirname(file),specifier);if(base.startsWith(path.resolve('app/shared')+path.sep))return `from ${q}${pathToFileURL(path.join(shared,path.relative(path.resolve('app/shared'),base)+'.mjs')).href}${q}`;const dependency=['.ts','.tsx'].map(ext=>base+ext).find(f=>fs.existsSync(f));assert.ok(dependency,base);compile(dependency);return `from ${q}${specifier}.mjs${q}`;});fs.mkdirSync(path.dirname(destination),{recursive:true});fs.writeFileSync(destination,js);}
for(const name of ['dish-checkouts','my-day','workspace-forms'])compile(path.resolve('app/team/'+name+'.tsx'));
const {DishCheckoutDetail,DishCheckoutCycles}=await import(pathToFileURL(path.join(compiled,'team/dish-checkouts.mjs'))),{MyDay}=await import(pathToFileURL(path.join(compiled,'team/my-day.mjs'))),{RecordDetail}=await import(pathToFileURL(path.join(compiled,'team/workspace-forms.mjs'))),{FollowDetail}=await import(pathToFileURL(path.join(compiled,'team/followthrough-forms.mjs')));
const now='2026-10-15T21:00:00Z';
function render(label,component,props){globalThis[captureKey]=[];const html=renderToStaticMarkup(React.createElement(component,props));const forms=globalThis[captureKey];delete globalThis[captureKey];fs.writeFileSync(path.join(evidence,label+'.html'),html);return {html,forms};}
const mark=(label,details={})=>report.checks.push({label,status:'passed',...details});
function button(html,text){const match=[...html.matchAll(/<button\b([^>]*)>([\s\S]*?)<\/button>/g)].find(m=>m[2].replace(/<[^>]+>/g,'')===text);assert.ok(match,'Missing button '+text);return {disabled:/\bdisabled(?:=|\s|$)/.test(match[1]),markup:match[0]};}
async function submit(form,step,note,fields={}){const original=globalThis.FormData;try{globalThis.FormData=class{get(key){return key==='note'?note:fields[key]??null;}};await form.onSubmit({preventDefault(){},currentTarget:{},nativeEvent:{submitter:{getAttribute:()=>step}}});await new Promise(resolve=>setImmediate(resolve));}finally{globalThis.FormData=original;}}
async function fixture(t,fileName='durable-ui.sqlite'){const file=path.join(evidence,fileName);let store=openPositionDatabase(file);t.after(()=>store.close());for(const name of fs.readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())store.sqlite.exec(fs.readFileSync('drizzle/'+name,'utf8').replaceAll('--> statement-breakpoint',''));store.sqlite.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').run('berts','Fictional Bert’s','America/New_York');for(const [id,area,position,caps]of [['am','BOH','Dishwasher',[]],['pm','BOH','Dishwasher',[]],['pm2','BOH','Dishwasher',[]],['manager','BOH','General manager',['location.manage','tasks.manage','schedule.manage','schedule.publish','schedule.change','close.confirm','standards.approve']],['server','FOH','Server',[]]])store.sqlite.prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').run(id,id+'@example.test',id+'-ui-identity','berts','Fictional '+id,area,position,JSON.stringify(caps),JSON.stringify([position]));const request=(actor,body)=>new Request('https://dish-ui.example/api/workspace?locationId=berts',{headers:{'oai-authenticated-user-id':actor+'-ui-identity','oai-authenticated-user-email':actor+'@example.test',Origin:'https://dish-ui.example','Content-Type':'application/json'},...(body?{method:'POST',body:JSON.stringify(body)}:{})});const raw=async(actor,action,input={},r)=>{const response=await handleWorkspace(request(actor,action?{locationId:'berts',requestId:crypto.randomUUID(),action,input,...(r?{recordId:r.id??r.recordId,expectedRevision:r.revision}:{})}:undefined),store.db);return {status:response.status,data:await response.json()};};const command=async(...args)=>{const r=await raw(...args);assert.equal(r.status,200,JSON.stringify(r.data));return r.data;};const work=actor=>command(actor);const record=id=>{const row=store.sqlite.prepare('SELECT * FROM records WHERE id=?').get(id.recordId??id.id??id);return {...row,ownerId:row.owner_id,data:JSON.parse(row.data)};};const rows=()=>store.sqlite.prepare('SELECT id FROM records').all().map(r=>record(r.id));const shift=async(actor,start,end)=>command('manager','shift.publish',{},await command('manager','shift.save',{personId:actor,position:actor==='server'?'Server':'Dishwasher',start,end}));const finish=async(task)=>command('manager','task.transition',{step:'verify',note:'Fictional independent check.'},await command(task.ownerId,'task.transition',{step:'ready',note:'Fictional work reported ready.'},task));const props=(w)=>({w,now,onOpen(){},onWeek(){},onGuides(){},onAskWeek(){},onTraining(){},onSchedule(){},onDuties(){},onAsk(){},onStart(){},onError(){},send:async()=>true});const reopen=()=>{const before=JSON.stringify(rows());store.close();store=openPositionDatabase(file);assert.equal(JSON.stringify(rows()),before);};return {command,raw,work,record,rows,shift,finish,props,reopen,sqlite:()=>store.sqlite};}
test.after(()=>{report.expectedChecks=14;report.status=report.checks.length===14?'passed':'incomplete or failed';fs.writeFileSync(path.join(evidence,'summary.json'),JSON.stringify(report,null,2)+'\n');});

test('Dish UI reflects narrow AM acceptance, PM inherited checks and manager shift release; ordinary Server flow remains unchanged',async t=>{
 const f=await fixture(t),amShift=await f.shift('am','2026-10-15T12:00:00Z','2026-10-15T20:00:00Z'),pmShift=await f.shift('pm','2026-10-15T20:00:00Z','2026-10-16T04:00:00Z');
 await f.command('manager','task.dish-cycle',{amOwnerId:'am',pmOwnerIds:['pm','pm2'],businessDate:'2026-10-15',title:'Fictional dated Dish checkout',detail:'Own documented put-away and independent checkout; no physical work performed.',due:'2026-10-16T04:00:00Z'});const am=f.rows().find(r=>r.data.dishCheckout?.shift==='AM'),pm=f.rows().find(r=>r.data.dishCheckout?.shift==='PM'&&r.ownerId==='pm');
 await f.command('am','task.dish-pass',{incomingId:'pm',note:'PRIVATE_PM_BODY: inherited load details must not appear in AM view.',due:'2026-10-16T04:00:00Z'},am);let child=f.rows().find(r=>r.data.dishHandoff?.sourceId===am.id);await f.finish(f.record(am));
 let w=await f.work('am'),parent=w.records.find(r=>r.id===am.id);assert.ok(!w.records.some(r=>r.id===child.id));let html=render('am-before-acceptance',DishCheckoutDetail,{...f.props(w),r:parent}).html;assert.match(html,/Incoming acknowledgment remains unconfirmed/);assert.doesNotMatch(html,/PRIVATE_PM_BODY|Open incoming work/);const beforeDay=render('am-my-day-pending',MyDay,f.props(w)).html;assert.match(beforeDay,/Checkout pending/);assert.match(beforeDay,/Closing work remains before manager checkout/);assert.doesNotMatch(beforeDay,/Waiting for manager checkout/);assert.equal(closingStatus(w,w.records.find(r=>r.id===amShift.recordId),{allowProjectedReceipts:true}).complete,false);mark('AM detail and My Day preserve pending acknowledgment without exposing PM child body');
 let mw=await f.work('manager'),managerHtml=render('manager-am-disabled',RecordDetail,{...f.props(mw),record:mw.records.find(r=>r.id===amShift.recordId)}).html;assert.equal(button(managerHtml,'Confirm checkout').disabled,true);assert.doesNotMatch(managerHtml,/Assign closing work/);assert.match(managerHtml,/Assign required checkout work/);assert.equal((await f.raw('manager','shift.release',{note:'Unaccepted outgoing work remains.'},amShift)).status,400);mark('Selected AM shift disables checkout, hides unsupported general close assignment, preserves required-task assignment, and domain rejects early release');
 w=await f.work('pm');let rendered=render('pm-child-before-acceptance',DishCheckoutDetail,{...f.props(w),r:w.records.find(r=>r.id===child.id)});assert.match(rendered.html,/Acknowledge incoming work/);assert.doesNotMatch(rendered.html,/Incoming work ready for manager validation/);let errors=[],sent=[],fail=true,flight;const send=async(action,input,r)=>{sent.push({action,input,id:r.id,revision:r.revision});if(fail)throw Error('Fictional interrupted receipt. No acknowledgment was saved.');flight=f.command('pm',action,input,r);return await flight;};rendered=render('pm-acknowledgment-callback',DishCheckoutDetail,{...f.props(w),r:w.records.find(r=>r.id===child.id),send,onError:error=>errors.push(error)});assert.equal(rendered.forms.length,1);await submit(rendered.forms[0],'accept','Explicit incoming acknowledgment');assert.match(errors[0],/No acknowledgment was saved/);assert.equal(f.record(child).data.dishHandoff.acceptedBy,'');fail=false;await submit(rendered.forms[0],'accept','Explicit incoming acknowledgment');await flight;assert.equal(errors.length,1);assert.deepEqual(sent[1],sent[0]);child=f.record(child);assert.equal(child.data.dishHandoff.acceptedBy,'pm');assert.equal(child.data.phase,'open');f.reopen();mark('Actual Dish acknowledgment form surfaces a failed receipt and safely retries without optimistic completion');
 w=await f.work('am');parent=w.records.find(r=>r.id===am.id);assert.ok(parent.data.dishHandoffReceiptView);assert.equal(parent.data.dishHandoffAcceptances.length,1);assert.ok(!w.records.some(r=>r.id===child.id));html=render('am-acknowledged-private-pm',DishCheckoutDetail,{...f.props(w),r:parent}).html;assert.match(html,/Incoming responsibility acknowledged/);assert.match(html,/PM work details remain outside your view/);assert.match(html,/acknowledgment does not complete that work/);assert.doesNotMatch(html,/PRIVATE_PM_BODY|Open incoming work|Incoming acknowledgment remains unconfirmed/);const afterDay=render('am-my-day-manager-release',MyDay,f.props(w)).html;assert.match(afterDay,/Waiting for manager checkout/);assert.doesNotMatch(afterDay,/Closing work remains before manager checkout/);mark('Accepted AM receipt changes My Day to waiting for manager release while PM work remains private and open');
 mw=await f.work('manager');managerHtml=render('manager-am-enabled',RecordDetail,{...f.props(mw),record:mw.records.find(r=>r.id===amShift.recordId)}).html;assert.equal(button(managerHtml,'Confirm checkout').disabled,false);const selected=workforceContext(mw,'Can the AM employee leave?',now,[],{id:amShift.recordId,revision:amShift.revision});assert.equal(selected.context.closingStatus.complete,true);assert.ok(!selected.context.evidence.some(e=>e.source.id===child.id));const release=await f.command('manager','shift.release',{note:'Own AM checkout verified and named incoming acknowledgment saved.'},amShift);assert.ok(f.record(release).data.releasedAt);assert.equal(f.record(child).data.phase,'open');mark('Manager AM selected context, enabled checkout button and actual release agree; accepted PM task is still open');
 w=await f.work('pm');html=render('pm-own-checkout-blocked',DishCheckoutDetail,{...f.props(w),r:w.records.find(r=>r.id===pm.id)}).html;assert.match(html,/Incoming unfinished work still needs acknowledgment, completion, and manager validation/);assert.equal(button(html,'Checkout ready for manager validation').disabled,true);const incomingDay=render('pm-my-day-inherited-pending',MyDay,f.props(w)).html;assert.match(incomingDay,/Finish the incoming dish work first/);assert.equal((await f.raw('pm','task.transition',{step:'ready',note:'Cannot skip inherited work.'},pm)).status,400);mark('PM detail and My Day block own readiness while accepted inherited work remains incomplete');
 let ready=await f.command('pm','task.transition',{step:'ready',note:'Fictional inherited work reported ready.'},child);w=await f.work('pm');html=render('pm-own-awaits-inherited-check',DishCheckoutDetail,{...f.props(w),r:w.records.find(r=>r.id===pm.id)}).html;assert.equal(button(html,'Checkout ready for manager validation').disabled,true);mw=await f.work('manager');html=render('manager-pm-disabled-inherited-ready',RecordDetail,{...f.props(mw),record:mw.records.find(r=>r.id===pmShift.recordId)}).html;assert.equal(button(html,'Confirm checkout').disabled,true);await f.command('manager','task.transition',{step:'verify',note:'Fictional independent inherited-work check.'},ready);w=await f.work('pm');html=render('pm-own-inherited-checked',DishCheckoutDetail,{...f.props(w),r:w.records.find(r=>r.id===pm.id)}).html;assert.equal(button(html,'Checkout ready for manager validation').disabled,false);assert.doesNotMatch(html,/Incoming unfinished work still needs/);mark('Reported inherited readiness is distinct from verification; only independent verification enables PM own checkout submission');
 ready=await f.command('pm','task.transition',{step:'ready',note:'Fictional own PM cleanup reported ready.'},pm);mw=await f.work('manager');html=render('manager-pm-own-ready-unverified',RecordDetail,{...f.props(mw),record:mw.records.find(r=>r.id===pmShift.recordId)}).html;assert.equal(button(html,'Confirm checkout').disabled,true);await f.command('manager','task.transition',{step:'verify',note:'Fictional independent PM checkout.'},ready);mw=await f.work('manager');html=render('manager-pm-enabled',RecordDetail,{...f.props(mw),record:mw.records.find(r=>r.id===pmShift.recordId)}).html;assert.equal(button(html,'Confirm checkout').disabled,false);w=await f.work('pm');html=render('pm-my-day-manager-release',MyDay,f.props(w)).html;assert.match(html,/Waiting for manager checkout/);await f.command('manager','shift.release',{note:'PM own checkout and inherited work independently checked.'},pmShift);assert.equal(f.rows().find(r=>r.data.dishCheckout?.shift==='PM'&&r.ownerId==='pm2').data.phase,'open');mark('PM own ready signal still blocks release; verified work enables checkout without waiting for unrelated PM employee');
 // Ordinary non-Dish shift-linked tasks use the existing readiness/check chain.
 const serverShift=await f.shift('server','2026-10-15T20:00:00Z','2026-10-16T04:00:00Z');let task=await f.command('manager','task.create',{ownerId:'server',shiftId:serverShift.recordId,title:'Documented Server side work',detail:'Bag silverware and obtain the manager check; bank settlement remains external.',kind:'task',due:'2026-10-16T04:00:00Z'});mw=await f.work('manager');html=render('server-manager-pending',RecordDetail,{...f.props(mw),record:mw.records.find(r=>r.id===serverShift.recordId)}).html;assert.equal(button(html,'Confirm checkout').disabled,true);assert.doesNotMatch(html,/Unfinished work passed forward|Incoming acknowledgment/);task=await f.command('server','task.transition',{step:'ready',note:'Fictional side work ready.'},task);mw=await f.work('manager');html=render('server-manager-ready',RecordDetail,{...f.props(mw),record:mw.records.find(r=>r.id===serverShift.recordId)}).html;assert.equal(button(html,'Confirm checkout').disabled,true);await f.command('manager','task.transition',{step:'verify',note:'Independent fictional side-work check.'},task);mw=await f.work('manager');html=render('server-manager-verified',RecordDetail,{...f.props(mw),record:mw.records.find(r=>r.id===serverShift.recordId)}).html;assert.equal(button(html,'Confirm checkout').disabled,false);assert.equal(closingStatus(mw,mw.records.find(r=>r.id===serverShift.recordId)).complete,true);await f.command('manager','shift.release',{note:'Verified non-Dish checkout unchanged.'},serverShift);mark('Ordinary Server linked-work readiness, verification and checkout controls remain unchanged');
 const cycle=render('manager-cycle-pm-other-open',DishCheckoutCycles,{w:await f.work('manager'),send:async()=>true}).html;assert.match(cycle,/2 of 3 checkouts manager validated/);assert.match(cycle,/Station incomplete/);mark('Whole-station manager view remains incomplete while unrelated PM employee is still open, independently of released AM/PM shifts');
});

test('Compact phone JM logo and blue-gradient theme are present in the working-shell source; browser geometry is unverified',()=>{
 const css=fs.readFileSync('app/team/inviting-theme.css','utf8'),shell=fs.readFileSync('app/team/workspace.tsx','utf8');assert.match(css,/@media\(max-width:700px\)\{[\s\S]*?\.shared-brand>\.jmax-wordmark\{display:none\}/);assert.match(css,/\.jmax-brand-icon\{[^}]*background-image:url\('\/brand\/jaymax-logo-sheet\.png'\)/);assert.match(css,/--jmax-gradient:linear-gradient\(112deg,#0871c9 0%,#1258b9 46%,#071e46 100%\)/);assert.match(css,/header::after\{[^}]*#00a6ff[^}]*#0761cf[^}]*#071e46/);assert.match(shell,/className="jmax-brand-icon"/);assert.ok(shell.indexOf("import './inviting-theme.css'")>shell.indexOf("import './jmax-shell.css'"));assert.ok(fs.statSync('public/brand/jaymax-logo-sheet.png').size>0);fs.writeFileSync(path.join(evidence,'branding-source-audit.json'),JSON.stringify({phoneBreakpoint:700,phoneWordmark:'hidden',logo:'JM square crop from supplied logo sheet',theme:['#0871c9','#1258b9','#071e46'],accentBar:['#00a6ff','#0761cf','#071e46'],legacyColors:'Earlier teal-like colors remain in base styles; combined-theme overrides are loaded afterward. Actual cascade/phone rendering is not a browser-tested claim.',browserLayoutVerified:false},null,2)+'\n');mark('Working-shell source includes compact JM phone branding, hidden wordmark and light-to-dark blue bar/theme',{boundary:'Source inspection only, not pixel, contrast or device-layout proof'});
});

test('A privileged manager cannot confirm their own departure; a different authorized manager retains the independent checkout action',async t=>{
 const f=await fixture(t,'durable-manager-own-shift-ui.sqlite');
 f.sqlite().prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').run('independent-manager','independent-manager@example.test','independent-manager-ui-identity','berts','Fictional independent manager','BOH','General manager','["location.manage","close.confirm"]','["General manager"]');
 const shift=await f.command('manager','shift.publish',{},await f.command('manager','shift.save',{personId:'manager',position:'General manager',start:'2026-10-15T12:00:00Z',end:'2026-10-15T20:00:00Z'}));
 let w=await f.work('manager');const record=w.records.find(r=>r.id===shift.recordId);assert.equal(closingStatus(w,record).complete,true);
 const ownHtml=render('manager-own-shift-independent-check-required',RecordDetail,{...f.props(w),record}).html;assert.doesNotMatch(ownHtml,/Confirm checkout|<summary>Shift checkout<\/summary>/);assert.match(ownHtml,/Another authorized closing manager must confirm your checkout/);assert.match(ownHtml,/You cannot release your own shift/);
 const denial=await f.raw('manager','shift.release',{note:'Attempted self-release must remain forbidden.'},shift);assert.equal(denial.status,403);assert.ok(!f.record(shift).data.releasedAt);
 w=await f.work('independent-manager');const otherHtml=render('independent-manager-confirms-manager-shift',RecordDetail,{...f.props(w),record:w.records.find(r=>r.id===shift.recordId)}).html;assert.equal(button(otherHtml,'Confirm checkout').disabled,false);assert.doesNotMatch(otherHtml,/You cannot release your own shift/);
 await f.command('independent-manager','shift.release',{note:'Fictional independent operational checkout, not a physical or payroll claim.'},shift);assert.ok(f.record(shift).data.releasedAt);f.reopen();
 mark('Own manager shift UI excludes forbidden self-release and explains independent checkout; separate authorized manager remains enabled and actual handler release succeeds',{boundary:'Actual local handlers and React SSR; existing server self-release denial preserved, no extra approval added to owner-reported manager issue resolution'});
});

test('Accepted manager recovery UI uses handoff department despite GM home area, filters replacement choices and preserves responsibility through failed submission',async()=>{
 const at=new Date().toISOString(),future=new Date(Date.now()+86400000).toISOString(),past=new Date(Date.now()-86400000).toISOString();
 const member=(id,area='BOH',capabilities=['tasks.manage'],locationId='berts')=>({id,locationId,name:'Fictional '+id,area,position:'Manager',capabilities,qualifications:['Manager']});
 const gm=member('gm','Executive',['location.manage','tasks.manage']),outgoing=member('original-outgoing'),current=member('old-receiver'),replacement=member('replacement'),expired=member('expired'),foreign=member('foreign','BOH',['tasks.manage'],'papa');
 const leader=(person,end=future,area=person.area)=>({id:'lead-'+person.id,kind:'leadership',locationId:person.locationId,ownerId:person.id,area,revision:1,updatedAt:at,data:{active:true,start:at,end,note:'Fictional published leadership assignment',history:[]}});
 const record={id:'accepted-manager-issue',kind:'handoff',locationId:'berts',area:'BOH',ownerId:current.id,revision:4,updatedAt:at,data:{title:'Saved manager handoff',detail:'Fictional remaining issue; no issue resolution or notification is implied by UI rendering.',phase:'accepted',priority:'routine',outgoingId:outgoing.id,incomingId:current.id,outgoingLeadershipId:'lead-original-outgoing',incomingLeadershipId:'lead-old-receiver',due:at,history:[]}};
 const w={location:{id:'berts',name:'Fictional Bert’s',timezone:'America/New_York',revision:1},me:gm,members:[gm,outgoing,current,replacement,expired,foreign],records:[record,leader(gm,future,'BOH'),leader(current),leader(replacement),leader(expired,past),leader(foreign),leader(outgoing,past)]};
 let errors=[],sent=[],fail=true;const send=async(action,input,r)=>{sent.push({action,input,id:r.id,revision:r.revision});if(fail)throw Error('Fictional replacement save interruption; responsibility unchanged.');return {recordId:r.id,revision:r.revision+1};};
 let rendered=render('gm-replacement-choices',FollowDetail,{w,record,send,onError:error=>errors.push(error)});
 assert.match(rendered.html,/Arrange replacement manager/);assert.match(rendered.html,/Request replacement acceptance/);assert.doesNotMatch(rendered.html,/Record resolution/);
 const options=rendered.html.match(/<select name="incomingLeadershipId"[\s\S]*?<\/select>/)?.[0];assert.ok(options);assert.match(options,/value="lead-replacement"/);assert.doesNotMatch(options,/value="lead-gm"|value="lead-old-receiver"|value="lead-expired"|value="lead-foreign"|value="lead-original-outgoing"/);assert.equal(rendered.forms.length,1);
 await submit(rendered.forms[0],'','Named manager unavailable; reviewed replacement requested',{incomingLeadershipId:'lead-replacement'});assert.match(errors[0],/responsibility unchanged/);assert.equal(record.data.phase,'accepted');assert.equal(record.ownerId,'old-receiver');
 fail=false;await submit(rendered.forms[0],'','Named manager unavailable; reviewed replacement requested',{incomingLeadershipId:'lead-replacement'});assert.deepEqual(sent[1],sent[0]);assert.deepEqual(sent[1],{action:'handoff.transition',input:{step:'recover',note:'Named manager unavailable; reviewed replacement requested',incomingLeadershipId:'lead-replacement',incomingId:'replacement'},id:record.id,revision:4});assert.equal(record.data.phase,'accepted','Form waits for an authoritative returned state rather than changing ownership optimistically');
 // Render the independently returned offered-state contract. The command
 // receipt above is stubbed; authoritative recovery is tested by root.
 const offered={...record,ownerId:'gm',revision:5,data:{...record.data,phase:'offered',outgoingId:'gm',incomingId:'replacement',incomingLeadershipId:'lead-replacement'}};
 w.records=w.records.map(r=>r.id===record.id?offered:r);rendered=render('gm-current-owner-after-recovery',FollowDetail,{w,record:offered,send,onError:error=>errors.push(error)});assert.match(rendered.html,/Your responsibility continues until the receiving manager accepts/);assert.match(rendered.html,/Send updated handoff|Cancel this deferral/);assert.doesNotMatch(rendered.html,/Record resolution|Arrange replacement manager/);
 const oldView=render('former-outgoing-no-owner-controls',FollowDetail,{w:{...w,me:outgoing},record:offered,send,onError(){}}).html;assert.doesNotMatch(oldView,/Send updated handoff|Cancel this deferral|Record resolution/);
 const receiverView=render('replacement-pending-acceptance',FollowDetail,{w:{...w,me:replacement},record:offered,send,onError(){}}).html;assert.match(receiverView,/Accept responsibility|Return with a concern/);assert.doesNotMatch(receiverView,/Record resolution/);
 mark('Accepted manager recovery UI preserves error state, selects same-handoff-area replacement and uses current-owner controls after returned reoffer',{boundary:'Actual SSR/forms, stubbed recovery receipt plus explicit returned offered-state fixture; backend recovery authorization belongs to root’s actual-handler regression'});
});

test('Rendered manager replacement callback survives an actual failed save, recovers the accepted record and gives reoffer controls only to its new owner',async t=>{
 const f=await fixture(t,'durable-manager-recovery-ui.sqlite');
 // Initial identity configuration only; every operational record below is
 // created, accepted, recovered and reoffered through authenticated handlers.
 f.sqlite().prepare('UPDATE memberships SET area=? WHERE id=?').run('Executive','manager');
 for(const actor of ['outgoing-manager','old-manager','replacement-manager'])f.sqlite().prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').run(actor,actor+'@example.test',actor+'-ui-identity','berts','Fictional '+actor,'BOH','Manager','["tasks.manage","schedule.change"]','["Manager"]');
 const at=Date.now(),time=offset=>new Date(at+offset*3600000).toISOString();
 const outgoing=await f.command('manager','leadership.assign',{personId:'outgoing-manager',area:'BOH',start:time(-2),end:time(-1),note:'Fictional closing leader.'});
 const incoming=await f.command('manager','leadership.assign',{personId:'old-manager',area:'BOH',start:time(-1),end:time(1),note:'Fictional opening leader who accepted the issue.'});
 const replacement=await f.command('manager','leadership.assign',{personId:'replacement-manager',area:'BOH',start:time(2),end:time(3),note:'Fictional reviewed replacement.'});
 let handoff=await f.command('outgoing-manager','handoff.create',{title:'Fictional unresolved manager issue',detail:'Saved condition and approved next action; no repair or safety proof is implied.',outgoingLeadershipId:outgoing.recordId,incomingLeadershipId:incoming.recordId,incomingId:'old-manager',priority:'routine',safeToDefer:true});
 handoff=await f.command('old-manager','handoff.transition',{step:'accept',note:'Explicit original incoming manager acceptance.'},handoff);let saved=f.record(handoff),w=await f.work('manager');
 const errors=[],sent=[];const send=async(action,input,r)=>{sent.push({action,input,id:r.id,revision:r.revision});const response=await f.raw('manager',action,input,r);if(response.status!==200)throw Error(response.data.error??'Replacement not saved');return response.data;};
 let rendered=render('actual-manager-recovery-before',FollowDetail,{w,record:w.records.find(r=>r.id===saved.id),send,onError:error=>errors.push(error)});assert.equal(rendered.forms.length,1);assert.match(rendered.html,/Request replacement acceptance/);
 f.sqlite().exec(`CREATE TRIGGER fail_recovery_ui BEFORE UPDATE ON records WHEN OLD.id='${saved.id}' BEGIN SELECT RAISE(ABORT,'Fictional interrupted manager recovery'); END`);
 await submit(rendered.forms[0],'','Original responsible manager unavailable; named replacement requested',{incomingLeadershipId:replacement.recordId});assert.equal(errors.length,1);assert.equal(f.record(saved).data.phase,'accepted');assert.equal(f.record(saved).ownerId,'old-manager');f.sqlite().exec('DROP TRIGGER fail_recovery_ui');
 await submit(rendered.forms[0],'','Original responsible manager unavailable; named replacement requested',{incomingLeadershipId:replacement.recordId});assert.equal(errors.length,1);assert.deepEqual(sent[1],sent[0]);saved=f.record(saved);assert.equal(saved.data.phase,'offered');assert.equal(saved.ownerId,'manager');assert.equal(saved.data.outgoingId,'outgoing-manager','Original reporter identity is retained');assert.equal(saved.data.incomingId,'replacement-manager');assert.equal(saved.data.detail,'Saved condition and approved next action; no repair or safety proof is implied.');assert.equal(saved.data.priority,'routine');f.reopen();
 w=await f.work('manager');rendered=render('actual-manager-current-owner-after-recovery',FollowDetail,{w,record:w.records.find(r=>r.id===saved.id),send,onError:error=>errors.push(error)});assert.equal(rendered.forms.length,1);assert.match(rendered.html,/Your responsibility continues until the receiving manager accepts/);assert.match(rendered.html,/Send updated handoff/);assert.doesNotMatch(rendered.html,/Record resolution/);
 await submit(rendered.forms[0],'offer','Current responsible GM updates the offered replacement',{incomingLeadershipId:replacement.recordId});saved=f.record(saved);assert.equal(saved.data.phase,'offered');assert.equal(saved.ownerId,'manager');
 const former=await f.work('outgoing-manager');const oldHtml=render('actual-former-outgoing-without-controls',FollowDetail,{w:former,record:former.records.find(r=>r.id===saved.id),send:async()=>true,onError(){}}).html;assert.doesNotMatch(oldHtml,/Send updated handoff|Cancel this deferral|Record resolution/);
 const receiver=await f.work('replacement-manager');const receiveHtml=render('actual-replacement-pending-acceptance',FollowDetail,{w:receiver,record:receiver.records.find(r=>r.id===saved.id),send:async()=>true,onError(){}}).html;assert.match(receiveHtml,/Accept responsibility/);assert.doesNotMatch(receiveHtml,/Record resolution/);
 assert.equal(f.record(saved).data.phase,'offered');assert.ok(f.record(saved).data.history.some(h=>h.action==='recover'));assert.ok(f.record(saved).data.history.some(h=>h.action==='offer'));
 mark('Actual recovery/reoffer form callbacks match saved handler ownership through failed save, durable reopen and current-owner-only controls',{boundary:'Actual local handlers, React-rendered callback and saved returned states; not browser navigation or real manager notification'});
});



