import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {openPositionDatabase} from './all-position-week-fixture.mjs';

test('Every authorized position and owner context excludes formally retired guide answers after durable continuation',async()=>{
 const summaryPath=process.env.HOUR_MEMORY_SUMMARY??'evidence/hour-trial/memory-all-positions/c4654738-783d-4c47-b35a-65d4a538fced/summary.json',prior=JSON.parse(fs.readFileSync(summaryPath,'utf8')),dir=path.resolve(path.dirname(summaryPath),'retired-guides-'+crypto.randomUUID());fs.mkdirSync(dir,{recursive:true});const receipts=[];
 for(const result of prior.results){
  const previous=JSON.parse(fs.readFileSync(result.receipt,'utf8')),runtime=previous.runtime,{handleWorkspace}=await import(pathToFileURL(path.join(runtime,'service.mjs')).href),{handleCompanionChat}=await import(pathToFileURL(path.join(runtime,'companion-chat.mjs')).href);
  const runtimeHash=createHash('sha256').update(fs.readFileSync(path.join(runtime,'companion-memory.mjs'))).digest('hex');assert.equal(runtimeHash,prior.runtimeRevision['companion-memory.mjs']);
  const file=path.join(dir,result.id+'.sqlite');const original=openPositionDatabase(result.database);try{original.sqlite.prepare('VACUUM INTO ?').run(file);}finally{original.close();}let store=openPositionDatabase(file),now=Date.parse('2026-12-01T15:00:00-05:00'),captured,providerCalls=0;
  const receipt={id:result.id,restaurant:result.restaurant,position:result.position,sourceDatabase:result.database,database:file,sourceReceipt:result.receipt,runtime,memoryHash:runtimeHash,initialSeeds:0,operationalReseeds:0,externalCalls:0,checks:[],failures:[],proof:'Continuation from a consistent SQLite clone of the successful 45-day durable history. Current fictional QA guide approval and retirement use actual handlers. Mock provider proves supplied context, not real-answer helpfulness.'};receipts.push(receipt);
  const request=(actor,route,body)=>new Request(`https://hour-trial.example/api/${route}?locationId=${result.restaurant}`,{headers:{'oai-authenticated-user-id':actor+'-identity','oai-authenticated-user-email':actor+'@example.test',Origin:'https://hour-trial.example','Content-Type':'application/json'},...(body?{method:'POST',body:JSON.stringify(body)}:{})});
  const ok=async response=>{const data=await response.json();assert.equal(response.status,200,JSON.stringify(data));return data;};
  const cmd=(action,input,record)=>handleWorkspace(request('manager','workspace',{locationId:result.restaurant,requestId:crypto.randomUUID(),action,input,...(record?{recordId:record.recordId,expectedRevision:record.revision}:{})}),store.db).then(ok);
  const provider=async(_url,init)=>{providerCalls++;const input=JSON.parse(init.body).input;captured={input,context:JSON.parse(input[1].content.split('\n').slice(1).join('\n'))};return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({answer:captured.context.selectedWork?'Use OLD_GUIDE_FLINTHARBOR_SENTINEL from the attached fictional QA guide; this is not completed work.':'No retired method is supplied. Ask the manager for current approved instructions. Chat has not saved or notified anyone.',sourceIds:captured.context.selectedWork?[captured.context.selectedWork.id]:[]})}]}]});};
  const chat=(body,query='')=>handleCompanionChat(new Request(`https://hour-trial.example/api/companion?locationId=${result.restaurant}${query}`,request('worker','companion',body)),store.db,{OPENAI_API_KEY:'sk-fictional-only',JMAX_OPENAI_MODEL:'gpt-5.4-mini'},provider,()=>now,'workforce').then(ok);
  const ask=async(question,id,focus)=>{let c=await chat();if(c.full)c=await chat({locationId:result.restaurant,action:'start-new',conversationId:c.conversationId,expectedRevision:c.revision});now+=6000;return chat({locationId:result.restaurant,action:'ask',conversationId:c.conversationId,expectedRevision:c.revision,requestId:id,question,...(focus?{focus:{id:focus.recordId,revision:focus.revision}}:{})});};
  try{
   let guide=await cmd('standard.save',{area:previous.provenance?.area??(JSON.parse(fs.readFileSync(path.join(path.dirname(summaryPath),'profiles.json'),'utf8')).find(p=>p.id===result.id).area??'BOH'),title:'FlintHarbor fictional QA memory guide',position:result.position,zone:'Isolated memory-retirement check',criteria:['Seek the current approved source before acting'],source:'Fictional QA reference only; this does not publish restaurant operating policy.',version:1,verification:'manager',guide:{purpose:'Test source retirement in historical memory',preparation:['Read the attached source'],steps:['Use only current approved source instructions'],troubleshooting:['A retired source is unavailable'],escalation:'Named manager'}});guide=await cmd('standard.approve',{validated:true,note:'Fictional QA approval for software-only retirement test.'},guide);
   const first=await ask('Explain the attached FlintHarbor QA guide.','guide-before-retirement',guide);assert.ok(captured.context.selectedWork);assert.ok(first.turns.at(-1).sources.some(s=>s.id===guide.recordId));receipt.checks.push('Approved guide is actually selected and cited');
   guide=await cmd('standard.retire',{note:'Fictional QA method retired; no replacement has been approved.'},guide);store.close();store=openPositionDatabase(file);receipt.checks.push('Supported retirement persists through database reopening');
   const c=await chat(),old=c.turns.find(t=>t.id==='guide-before-retirement');assert.equal(old.stale,true);assert.equal(old.answer,'');assert.deepEqual(old.sources,[]);receipt.checks.push('Old source-backed answer reads as stale and blank');
   await ask('Recall the earlier FlintHarbor guide discussion. Is its operating advice still authorized?','guide-after-retirement');assert.ok(!JSON.stringify(captured.input).includes('OLD_GUIDE_FLINTHARBOR_SENTINEL'));assert.ok(!captured.context.priorConversationMemory.entries.some(e=>e.requestId==='guide-before-retirement'));assert.ok(!captured.context.evidence.some(e=>e.source.id===guide.recordId));receipt.checks.push('Retired source and old assistant method never reach provider context');
   assert.equal(providerCalls,2);receipt.mockedProviderContexts=providerCalls;
  }catch(e){receipt.failures.push({error:String(e.stack),context:captured?.context});}finally{store.close();fs.writeFileSync(path.join(dir,result.id+'.json'),JSON.stringify(receipt,null,2)+'\n');}
 }
 const summary={sourceSummary:path.resolve(summaryPath),profiles:receipts.length,checks:receipts.reduce((n,r)=>n+r.checks.length,0),mockedProviderContexts:receipts.reduce((n,r)=>n+(r.mockedProviderContexts??0),0),failures:receipts.filter(r=>r.failures.length).map(r=>({id:r.id,failures:r.failures})),externalCalls:0,operationalReseeds:0,receipts:receipts.map(r=>path.join(dir,r.id+'.json'))};fs.writeFileSync(path.join(dir,'summary.json'),JSON.stringify(summary,null,2)+'\n');console.log('Evidence:',path.join(dir,'summary.json'));assert.equal(receipts.length,50);assert.deepEqual(summary.failures,[],JSON.stringify(summary.failures));assert.equal(summary.checks,200);
});
