import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {Miniflare} from 'miniflare';
process.env.MINIFLARE_REGISTRY_PATH??=path.resolve('.wrangler/registry');
test('compiled invoice catalog route scopes review and saves a chosen line through the existing writer',async t=>{
 let outbound=0;const mf=new Miniflare({modules:true,scriptPath:path.resolve('dist/server/index.js'),modulesRoot:path.resolve('dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js']}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],serviceBindings:{ASSETS:()=>new Response('Missing',{status:404})},outboundService:()=>{outbound++;throw Error('No outbound expected')}});t.after(()=>mf.dispose());
 const db=await mf.getD1Database('DB');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())await db.batch(fs.readFileSync('drizzle/'+f,'utf8').split('--> statement-breakpoint').filter(s=>s.trim()).map(s=>db.prepare(s)));
 for(const id of ['a','b'])await db.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').bind(id,'Fictional '+id,'America/New_York').run();
 for(const [id,caps,loc='a'] of [['owner',['location.manage']],['manager',['tasks.manage']],['worker',[]],['foreign',['location.manage'],'b']])await db.prepare("INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications,active) VALUES(?,?,?,?,?,'BOH','Manager',?,'[]',1)").bind(id,id+'@example.test',id+'-identity',loc,'Fictional '+id,JSON.stringify(caps)).run();
 const headers=id=>({'oai-authenticated-user-id':id+'-identity','oai-authenticated-user-email':id+'@example.test',Origin:'http://localhost','Content-Type':'application/json'});

 const call=async(actor,url,body)=>{const r=await mf.dispatchFetch('http://localhost'+url,{method:'POST',headers:headers(actor),body:JSON.stringify(body)});return {status:r.status,data:await r.json()}};
 const ok=r=>{assert.equal(r.status,200,JSON.stringify(r.data));return r.data};
 const item={restaurantId:'fixture',name:'Fictional ingredient',controlNumber:'FIX-1',purchaseUnit:'case',packCount:2,unitQty:5,unitUOM:'lb',vendorSkus:[{id:'sku',vendor:'Fixture Supplier',vendorSku:'001',purchaseUnit:'case',packCount:2,unitQty:5,unitUOM:'lb',price:10,priceUpdatedAt:'2026-01-01',available:true}]};
 const imported=ok(await call('owner','/api/food',{locationId:'a',requestId:'fixture-import',action:'fooditem.import',input:{dataset:'demo',sourceRestaurantId:'fixture',sourceLabel:'Fictional worker fixture',destinationLocationId:'a',confirmed:true,rows:[item]}}));
 const csv='\uFEFFvendor,vendor_sku,invoice_number,line_reference,invoice_date,quantity,unit_basis,invoice_unit,line_total\r\nFixture Supplier,001,INV-1,1,2026-01-01,20,measure,lb,30.00\r\n';
 const {readInvoiceUpload}=await import('../.sites-runtime/shared/invoice-csv-source.mjs');
 const selected=await readInvoiceUpload({name:'Fictional compiled invoice.csv',size:Buffer.byteLength(csv),arrayBuffer:async()=>new TextEncoder().encode(csv).buffer}),sha256=selected.file.sha256;
 const archived=ok(await call('owner','/api/food/invoice-files',{locationId:'a',dataset:'demo',csv:selected.csv,sha256,byteLength:selected.file.byteLength,fileName:selected.file.fileName,confirmed:true}));assert.equal(archived.file.sha256,sha256);
 const archiveListUrl='http://localhost/api/food/invoice-files?locationId=a&dataset=demo&view=list';
 const listed=await mf.dispatchFetch(archiveListUrl,{headers:headers('owner')});assert.equal(listed.status,200);const archivePage=await listed.json();assert.equal(archivePage.files[0].sha256,sha256);assert.equal(archivePage.totals.files,1);assert.equal(archivePage.files[0].csv,undefined);
 for(const actor of ['worker','foreign'])assert.equal((await mf.dispatchFetch(archiveListUrl,{headers:headers(actor)})).status,403);
 const downloaded=await mf.dispatchFetch('http://localhost/api/food/invoice-files?'+new URLSearchParams({locationId:'a',dataset:'demo',sha256,download:'1'}),{headers:headers('owner')});assert.equal(downloaded.status,200);const originalBytes=Buffer.from(await downloaded.arrayBuffer());assert.deepEqual(originalBytes,Buffer.from(csv));
 const {resumeInvoiceArchive}=await import('../.sites-runtime/shared/invoice-archive-resume.mjs');const resumed=await resumeInvoiceArchive(new Response(originalBytes),archivePage.files[0]);
 const denied=await mf.dispatchFetch('http://localhost/api/food/invoice-files?'+new URLSearchParams({locationId:'a',dataset:'demo',sha256}),{headers:headers('worker')});assert.equal(denied.status,403);
 const request={locationId:'a',dataset:'demo',csv:resumed.csv};
 const review=ok(await call('owner','/api/food/invoice-review',request));assert.equal(review.totals.ready,1);assert.equal(review.entries[0].matches[0].quantity,2);assert.equal(review.entries[0].matches[0].price,15);
 for(const actor of ['manager','worker','foreign'])assert.equal((await call(actor,'/api/food/invoice-review',request)).status,403);
 assert.equal(ok(await call('owner','/api/food/invoice-review',{...request,dataset:'operating'})).totals.unmatched,1);
 const match=review.entries[0].matches[0],row=review.entries[0].row;
 const body={locationId:'a',requestId:'fixture-invoice',action:'fooditem.invoice',recordId:match.itemId,expectedRevision:match.itemRevision,input:{...row,skuId:match.skuId,sourceNote:'Fictional source checked',confirmed:true,fileSource:{kind:'csv',fileName:'fixture.csv',byteLength:Buffer.byteLength(csv),sha256,row}}};
 const saved=ok(await call('owner','/api/food',body));assert.deepEqual(ok(await call('owner','/api/food',body)),saved);
 assert.equal((await call('owner','/api/food',{...body,requestId:'fixture-stale'})).status,409);
 const res=await mf.dispatchFetch('http://localhost/api/food?locationId=a&dataset=demo&itemId='+match.itemId,{headers:headers('owner')});const page=await res.json();assert.equal(page.records[0].data.vendorSkus[0].price,10);assert.equal(page.records[0].data.count,null);assert.equal(page.records[0].revision,saved.revision);
 const hist=await mf.dispatchFetch('http://localhost/api/food?locationId=a&dataset=demo&view=history&recordId='+match.itemId,{headers:headers('owner')});const history=await hist.json();assert.equal(history.entries.at(-1).event.invoiceLine.fileSource.row.vendorSku,'001');
 const recorded=ok(await call('owner','/api/food/invoice-review',request));assert.deepEqual(recorded.historyTotals,{notRecorded:0,recorded:1,conflict:0});assert.equal(recorded.entries[0].saved.source.sequence,history.entries.at(-1).sequence);
 const changed=ok(await call('owner','/api/food/invoice-review',{...request,csv:csv.replace('30.00','35.00')}));assert.equal(changed.entries[0].saved.state,'conflict');assert.deepEqual(changed.entries[0].saved.differences,['net line amount']);
 const voided=ok(await call('owner','/api/food',{locationId:'a',requestId:'fixture-void',action:'fooditem.invoice-void',recordId:match.itemId,expectedRevision:saved.revision,input:{invoiceRevision:saved.revision,reason:'Fictional source correction'}}));
 const refreshed=ok(await call('owner','/api/food/invoice-review',request));assert.equal(refreshed.entries[0].saved.state,'not-recorded');assert.equal(refreshed.entries[0].matches[0].itemRevision,voided.revision);
 const corrected=ok(await call('owner','/api/food',{...body,requestId:'fixture-corrected',expectedRevision:voided.revision}));assert.equal(ok(await call('owner','/api/food/invoice-review',request)).entries[0].saved.source.revision,corrected.revision);assert.equal(outbound,0);
});
