import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {DatabaseSync} from 'node:sqlite';
import {openPositionDatabase} from './all-position-week-fixture.mjs';
import {handleWorkspace} from '../.sites-runtime/shared/service.mjs';
import {handleCompanionChat} from '../.sites-runtime/shared/companion-chat.mjs';
import {snapshot,request} from './local-readiness-recovery-child.mjs';
const runtime=()=>Object.fromEntries(fs.readdirSync('.sites-runtime/shared').filter(f=>f.endsWith('.mjs')).sort().map(f=>[f,createHash('sha256').update(fs.readFileSync('.sites-runtime/shared/'+f)).digest('hex')]));
const output=path.resolve('evidence/local-readiness-2026-10-08/recovery',randomUUID());fs.mkdirSync(output,{recursive:true});const runtimeBefore=runtime(),results=[];
after(()=>{const runtimeAfter=runtime();fs.writeFileSync(path.join(output,'summary.json'),JSON.stringify({tests:7,results,runtimeBefore,runtimeAfter,runtimeStable:JSON.stringify(runtimeBefore)===JSON.stringify(runtimeAfter),limits:['Local fictional SQLite with the application handlers; no production restoration or deployment migration is claimed.','SQLite VACUUM INTO is a consistent test snapshot; no hosted D1 or Supabase backup acceptance is established.','Process exit injection occurs inside the real handler transaction before audit insert; a machine power loss and disk durability are not proven.','AI provider is mocked once per restaurant to test saved private history; no live AI helpfulness test.','Missing/corrupt backup rejection is tested in SQLite directly; app has no verified restoration UI or automated backup schedule.']},null,2));assert.deepEqual(runtimeAfter,runtimeBefore);});
async function fixture(t,restaurant){const dir=path.join(output,restaurant+'-'+randomUUID());fs.mkdirSync(dir);const file=path.join(dir,'original.sqlite');let store=openPositionDatabase(file);t.after(()=>store.close());store.sqlite.exec('PRAGMA journal_mode=WAL');
 for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())store.sqlite.exec(fs.readFileSync('drizzle/'+f,'utf8').replaceAll('--> statement-breakpoint',''));
 for(const l of ['berts','rudds','papa'])store.sqlite.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').run(l,'Fictional '+l,'America/New_York');
 for(const [actor,position,caps,loc] of [['manager','General Manager',['location.manage','tasks.manage'],restaurant],['worker','Cook',[],restaurant],['incoming','Cook',[],restaurant],['revoked','Cook',[],restaurant],['foreign','Cook',[],restaurant==='berts'?'rudds':'berts']])store.sqlite.prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').run(actor,actor+'@example.test',actor+'-identity',loc,'Fictional '+actor,'BOH',position,JSON.stringify(caps),JSON.stringify([position]));
 store.sqlite.prepare('UPDATE memberships SET active=0,revision=revision+1 WHERE id=?').run('revoked');
 const body=(action,input={},record,requestId=randomUUID())=>({locationId:restaurant,requestId,action,input,...(record?{recordId:record.recordId??record.id,expectedRevision:record.revision}:{})});
 const raw=async(actor,command)=>{const response=await handleWorkspace(request(restaurant,actor,command),store.db);return{status:response.status,data:await response.json()};};
 const cmd=async(actor,action,input,record,rid)=>{const result=await raw(actor,body(action,input,record,rid));assert.equal(result.status,200,JSON.stringify(result.data));return result.data;};
 const get=id=>{const r=store.sqlite.prepare('SELECT * FROM records WHERE id=?').get(id);return {...r,ownerId:r.owner_id,data:JSON.parse(r.data)};};
 return{restaurant,dir,file,store:()=>store,body,raw,cmd,get,reopen:()=>{store.close();store=openPositionDatabase(file);}};
}
for(const restaurant of ['berts','rudds','papa']){
 test(restaurant+': consistent backup restores pending work, named messages, permissions, private history and lost acknowledgment receipts in a separate process',async t=>{
  const f=await fixture(t,restaurant);const due='2027-01-01T00:00:00Z';let issue=await f.cmd('manager','task.create',{ownerId:'worker',kind:'issue',title:'Fictional unresolved interruption',detail:'Named manager follow-through is still required.',due});issue=await f.cmd('worker','task.transition',{step:'ready',note:'Initial remedy reported'},issue);issue=await f.cmd('manager','task.transition',{step:'fix',note:'Retain remaining work for next shift'},issue);
  let handoff=await f.cmd('manager','task.create',{ownerId:'worker',incomingId:'incoming',kind:'handoff',title:'Fictional incoming responsibility',detail:'Incoming coworker must explicitly accept.',due});handoff=await f.cmd('worker','task.transition',{step:'ready',note:'Outgoing work is prepared'},handoff);handoff=await f.cmd('manager','task.transition',{step:'verify',note:'Independent check done; incoming acceptance pending'},handoff);
  const message=await f.cmd('worker','message.send',{recipients:['incoming'],title:'Fictional named handoff',body:'Please open and accept your pending work.'});
  const now=Date.now(),binding={OPENAI_API_KEY:'sk-fictional-recovery'},provider=async()=>Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({answer:'The saved issue remains open; check with the named manager.',sourceIds:[issue.recordId]})}]}]});
  let chat=await handleCompanionChat(request(restaurant,'worker',undefined,'companion'),f.store().db,binding,provider,()=>now,'workforce');assert.equal(chat.status,200);const current=await chat.json(),privateQuestion='PRIVATE RECOVERY QA: what remains unresolved for my assigned issue?';chat=await handleCompanionChat(request(restaurant,'worker',{locationId:restaurant,action:'ask',requestId:'private-recovery',conversationId:current.conversationId,expectedRevision:current.revision,question:privateQuestion,focus:{id:issue.recordId,revision:issue.revision}},'companion'),f.store().db,binding,provider,()=>now,'workforce');assert.equal(chat.status,200);assert.equal((await chat.json()).turns.at(-1).status,'complete');
  const command=f.body('task.create',{ownerId:'worker',kind:'task',title:'Fictional acknowledged save',detail:'Response is considered lost after commit, then exactly retried.',due},undefined,'lost-acknowledgment');const saved=await f.raw('manager',command);assert.equal(saved.status,200);
  const expected=snapshot(f.store().sqlite),backup=path.join(f.dir,'consistent-backup.sqlite');assert.ok(!fs.existsSync(backup));f.store().sqlite.exec("VACUUM INTO '"+backup.replaceAll("'","''")+"'");
  await f.cmd('manager','task.create',{ownerId:'worker',kind:'task',title:'Post-backup work deliberately not restored',detail:'Recovery point limitation: later saves are outside the snapshot.',due});assert.notDeepEqual(snapshot(f.store().sqlite),expected);
  const restored=path.join(f.dir,'restored-copy.sqlite');fs.copyFileSync(backup,restored,fs.constants.COPYFILE_EXCL);const childSpec={database:restored,restaurant,expected,command,commandResult:saved.data,issueId:issue.recordId,handoffId:handoff.recordId,messageId:message.recordId,privateQuestion,now,output:path.join(f.dir,'new-process-result.json')};const spec=path.join(f.dir,'restore-spec.json');fs.writeFileSync(spec,JSON.stringify(childSpec));const child=spawnSync(process.execPath,['tests/local-readiness-recovery-child.mjs',spec],{encoding:'utf8',timeout:30000});assert.equal(child.status,0,child.stderr+child.stdout);const result=JSON.parse(fs.readFileSync(childSpec.output));results.push({...result,postBackupWorkExcluded:true,originalUnaffected:true,backup,restored});assert.equal(f.store().sqlite.prepare("SELECT count(*) AS n FROM records WHERE json_extract(data,'$.title')='Post-backup work deliberately not restored'").get().n,1);
 });
 test(restaurant+': hard process interruption during actual save rolls back and permits one exact retry after reopening',async t=>{
  const f=await fixture(t,restaurant);await f.cmd('manager','task.create',{ownerId:'worker',kind:'task',title:'Earlier committed work survives interruption',detail:'This record and its notices must stay intact.',due:'2027-01-01T00:00:00Z'});const before=snapshot(f.store().sqlite),command=f.body('task.create',{ownerId:'worker',kind:'task',title:'Interrupted before transaction commit',detail:'Deliberate isolated test process exit.',due:'2027-01-01T00:00:00Z'},undefined,'interrupted-save');f.store().sqlite.exec('PRAGMA wal_checkpoint(FULL)');const spec=path.join(f.dir,'crash-spec.json');fs.writeFileSync(spec,JSON.stringify({mode:'crash',database:f.file,restaurant,command}));const child=spawnSync(process.execPath,['tests/local-readiness-recovery-child.mjs',spec],{encoding:'utf8',timeout:30000});assert.equal(child.status,91,child.stderr+child.stdout);f.reopen();assert.deepEqual(snapshot(f.store().sqlite),before);assert.equal(f.store().sqlite.prepare('PRAGMA integrity_check').get().integrity_check,'ok');const first=await f.raw('manager',command);assert.equal(first.status,200);const committed=snapshot(f.store().sqlite);f.reopen();assert.deepEqual(await f.raw('manager',command),first);assert.deepEqual(snapshot(f.store().sqlite),committed);assert.equal((await f.raw('manager',{...command,input:{...command.input,detail:'Altered retry'}})).status,409);assert.deepEqual(snapshot(f.store().sqlite),committed);results.push({restaurant,case:'hard process interruption',exitCode:91,atomicRollback:true,previousCommittedWorkRetained:true,reopenedIntegrity:'ok',exactRetryOnce:true,alteredRetryRejected:true});
 });
}
test('missing and truncated backup do not pass integrity or silently replace an existing database',()=>{const missing=path.join(output,'missing.sqlite');assert.throws(()=>new DatabaseSync(missing,{readOnly:true}));assert.ok(!fs.existsSync(missing));const truncated=path.join(output,'truncated.sqlite');fs.writeFileSync(truncated,'SQLite format 3\0INTERRUPTED BACKUP');let db;assert.throws(()=>{db=new DatabaseSync(truncated,{readOnly:true});db.prepare('PRAGMA integrity_check').all();});db?.close();const existing=path.join(output,'protected-existing.sqlite');fs.writeFileSync(existing,'DO NOT REPLACE');assert.throws(()=>fs.copyFileSync(truncated,existing,fs.constants.COPYFILE_EXCL));assert.equal(fs.readFileSync(existing,'utf8'),'DO NOT REPLACE');results.push({case:'invalid recovery inputs',missingRejected:true,truncatedRejected:true,existingNotOverwritten:true});});
