import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import ts from 'typescript';
import React from 'react';

const runId=new Date().toISOString().replaceAll(':','-').replaceAll('.','-');
const base=path.resolve('evidence/local-readiness-2026-10-08/ui',runId),compiled=path.join(base,'runtime');fs.mkdirSync(compiled,{recursive:true});
const hash=f=>createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const runtimeHashes=()=>Object.fromEntries(fs.readdirSync('.sites-runtime/shared').filter(x=>x.endsWith('.mjs')).map(x=>[x,hash('.sites-runtime/shared/'+x)]));
const report={runId,checks:[],findings:[],source:{},runtimeBefore:runtimeHashes(),limits:['Actual ConnectedWorkspace and PrepReport callbacks run in a controlled hook lifetime adapter. Child presentation components are stubs, not browser/phone acceptance.','HTTP responses are fictional. No live providers, device notifications or production writes.']};
const key='__localReadinessUi'+runId;
fs.writeFileSync(path.join(compiled,'hooks.mjs'),`import * as R from 'react';const f=()=>globalThis[${JSON.stringify(key)}];export const useState=v=>f().state(v);export const useRef=v=>f().ref(v);export const useEffect=(c,d)=>f().effect(c,d);export const useLayoutEffect=useEffect;export const useMemo=(c,d)=>f().memo(c,d);export const useCallback=(c,d)=>useMemo(()=>c,d);export const lazy=R.lazy,Suspense=R.Suspense;`);
fs.writeFileSync(path.join(compiled,'jsx.mjs'),`import {jsx as a,jsxs as b,Fragment} from 'react/jsx-runtime';export {Fragment};function c(t,p){globalThis[${JSON.stringify(key+'props')}]?.push({type:t,props:p});}export function jsx(t,p,k){c(t,p);return a(t,p,k)}export function jsxs(t,p,k){c(t,p);return b(t,p,k)}`);
function compile(name){const source='app/team/'+name+'.tsx';report.source[source]=hash(source);let js=ts.transpileModule(fs.readFileSync(source,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;
 js=js.replace(/from (['"])react\1/g,(_,q)=>`from ${q}${pathToFileURL(path.join(compiled,'hooks.mjs')).href}${q}`).replace(/from (['"])react\/jsx-runtime\1/g,(_,q)=>`from ${q}${pathToFileURL(path.join(compiled,'jsx.mjs')).href}${q}`).replace(/import ['"][^'"]+\.css['"];?/g,'');
 js=js.replace(/import\s+\{([^}]+)\}\s+from\s+(['"])(\.\/[^'"]+)\2;/g,(_,bindings,q,s)=>{const file=path.join(compiled,s+'.stub.mjs');const names=bindings.split(',').map(x=>x.trim()).filter(Boolean);fs.writeFileSync(file,names.map(n=>`export function ${n}(){return null;}`).join('\n'));return `import {${bindings}} from ${q}${s}.stub.mjs${q};`;});
 js=js.replace(/from (['"])(\.\.\/shared\/[^'"]+)\1/g,(_,q,s)=>`from ${q}${pathToFileURL(path.resolve('.sites-runtime/shared',s.slice('../shared/'.length)+'.mjs')).href}${q}`);
 fs.writeFileSync(path.join(compiled,name+'.mjs'),js);return import(pathToFileURL(path.join(compiled,name+'.mjs')));}
const workspace=(await compile('workspace')).default,{PrepReport,EmployeePrep}=await compile('employee-prep');
const same=(a,b)=>Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((x,i)=>Object.is(x,b[i]));
const text=v=>typeof v==='string'||typeof v==='number'?String(v):Array.isArray(v)?v.map(text).join(''):React.isValidElement(v)?text(v.props.children):'';
class Frame{
 constructor(component,props){this.component=component;this.props=props;this.cells=[];this.effects=[];this.cursor=0;this.mutationsAfterUnmount=0;this.dead=false;}
 state(v){const i=this.cursor++;this.cells[i]??={value:typeof v==='function'?v():v};return[this.cells[i].value,x=>{if(this.dead)this.mutationsAfterUnmount++;this.cells[i].value=typeof x==='function'?x(this.cells[i].value):x;}];}
 ref(v){return this.cells[this.cursor++]??={current:v};}
 memo(f,d){const i=this.cursor++,old=this.cells[i];if(!old||!same(old.deps,d))this.cells[i]={value:f(),deps:d};return this.cells[i].value;}
 effect(f,d){const i=this.cursor++,old=this.cells[i];if(!old||!same(old.deps,d))this.effects.push(()=>{old?.cleanup?.();this.cells[i]={deps:d,cleanup:f()};});}
 render(){this.cursor=0;globalThis[key]=this;globalThis[key+'props']=[];try{this.element=this.component(this.props);}finally{delete globalThis[key];}this.seen=globalThis[key+'props'];delete globalThis[key+'props'];this.copy=text(this.element);return this;}
 runEffects(){for(const e of this.effects.splice(0))e();}
 componentProps(name){const p=this.seen.find(x=>typeof x.type==='function'&&x.type.name===name);assert.ok(p,'Missing mounted '+name);return p.props;}
 button(label){const p=this.seen.find(x=>x.type==='button'&&text(x.props.children)===label);assert.ok(p,'Missing button '+label);return p.props;}
 field(predicate){const p=this.seen.find(x=>x.type==='input'&&predicate(x.props));assert.ok(p,'Missing input');return p.props;}
 unmount(){this.dead=true;for(const c of this.cells)c?.cleanup?.();}
}
const flush=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));};
const mark=(name,details={})=>report.checks.push({name,status:'passed',...details});
const person=(loc='berts')=>({id:loc+'-employee',locationId:loc,name:'Fictional worker',position:'Server',area:'FOH',capabilities:[],qualifications:['Server']});
const w=(loc='berts')=>({location:{id:loc,name:'Fictional '+loc,timezone:'America/New_York',revision:1,weekStartsOn:1},me:person(loc),members:[person(loc)],records:[]});
async function browserFixture(){const old={fetch,window:globalThis.window,document:globalThis.document};const requests=[],storage=new Map(),listeners=new Map();let readFailure=null;
 globalThis.window={sessionStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},addEventListener:(k,f)=>listeners.set(k,f),removeEventListener:k=>listeners.delete(k),matchMedia:()=>({matches:true}),setInterval:()=>1,clearInterval:()=>{},location:{assign:()=>{}},innerHeight:900};globalThis.document={addEventListener:()=>{},removeEventListener:()=>{}};
 globalThis.fetch=async(url,init)=>{if(init?.method==='POST')return new Promise((resolve,reject)=>requests.push({url:String(url),init,resolve,reject}));if(readFailure)return Response.json({error:'Fictional refresh unavailable'},{status:readFailure});const parsed=new URL('https://local'+url),loc=parsed.searchParams.get('locationId');return Response.json(loc?w(loc):{memberships:['berts','rudds'].map(loc=>({id:person(loc).id,locationId:loc,locationName:'Fictional '+loc,name:'Fictional worker',position:'Server'}))});};
 const frame=new Frame(workspace,{signInPath:'/login'});frame.render();frame.runEffects();await flush();frame.render();frame.runEffects();await flush();frame.render();assert.equal(frame.componentProps('MyDay').w.location.id,'berts');return{frame,requests,storage,listeners,setReadFailure:s=>readFailure=s,restore(){frame.unmount();globalThis.fetch=old.fetch;globalThis.window=old.window;globalThis.document=old.document;}};
}
test.after(()=>{report.runtimeAfter=runtimeHashes();assert.deepEqual(report.runtimeBefore,report.runtimeAfter);for(const [f,digest]of Object.entries(report.source))assert.equal(hash(f),digest,'Actual tested source unchanged');fs.writeFileSync(path.join(base,'summary.json'),JSON.stringify(report,null,2)+'\n');});

test('root workspace uncertain committed response keeps exact retry, blocks double submit and restaurant switch',async()=>{
 const f=await browserFixture();try{const send=f.frame.componentProps('MyDay').send,promise=send('message.send',{title:'Fictional shortage',body:'Need manager help'});f.frame.render();assert.equal(await send('message.send',{body:'Duplicate'}),false);assert.equal(f.requests.length,1);const first=JSON.parse(f.requests[0].init.body);f.requests[0].reject(new Error('Fictional network lost after durable commit'));assert.equal(await promise,false);f.frame.render();assert.match(f.frame.copy,/waiting for confirmation|Retry the same change/);const select=f.frame.seen.find(x=>x.type==='select'&&x.props['aria-label']==='Current restaurant').props;assert.equal(select.disabled,true);select.onChange({target:{value:'rudds'}});await flush();f.frame.render();assert.equal(f.frame.componentProps('MyDay').w.location.id,'berts');const retry=f.frame.button('Retry the same change').onClick();assert.deepEqual(JSON.parse(f.requests[1].init.body),first);f.requests[1].resolve(Response.json({recordId:'same-durable-message'}));assert.equal(await retry,true);f.frame.render();assert.match(f.frame.copy,/Saved\./);assert.doesNotMatch(f.frame.copy,/waiting for confirmation/);mark('Actual root pending command uses exact request identity after lost response; double submit and cross-store change blocked');}finally{f.restore();}
});
test('root workspace confirmed save survives refresh failure with accurate saved notice',async()=>{
 const f=await browserFixture();try{const p=f.frame.componentProps('MyDay').send('message.send',{body:'Fictional issue'});f.setReadFailure(503);f.requests[0].resolve(Response.json({recordId:'durable-one'}));assert.equal(await p,true);f.frame.render();assert.match(f.frame.copy,/Your change was saved\. Refresh to see the latest state/);assert.match(f.frame.copy,/Fictional refresh unavailable/);assert.doesNotMatch(f.frame.copy,/Retry the same change/);mark('Confirmed save plus failed refresh never invites duplicate command and labels saved result accurately');}finally{f.restore();}
});
test('root workspace auth denial clears workspace, pending retry and remembered restaurant',async()=>{
 const f=await browserFixture();try{assert.ok(f.storage.size);const p=f.frame.componentProps('MyDay').send('message.send',{body:'Fictional revoked session'});f.requests[0].resolve(Response.json({error:'Fictional access revoked'},{status:403}));assert.equal(await p,false);f.frame.render();assert.ok(!f.frame.seen.some(x=>typeof x.type==='function'&&x.type.name==='MyDay'));assert.equal(f.storage.size,0);assert.doesNotMatch(f.frame.copy,/Retry the same change/);mark('403 root action removes current work and saved restaurant preference without leaving retry available');}finally{f.restore();}
});
for(const status of[500,502,503,504])test('root workspace gateway '+status+' preserves uncertain command instead of allowing fresh duplicate',async()=>{
 const f=await browserFixture();try{f.frame.componentProps('MyDay').onTraining();f.frame.render();f.frame.componentProps('TrainingHub').onHelp();f.frame.render();const originalForm=f.frame.componentProps('WorkspaceForm'),p=originalForm.send('message.send',{body:'Fictional committed before gateway failure'}),sent=JSON.parse(f.requests[0].init.body);f.requests[0].resolve(Response.json({error:'Fictional gateway lost confirmation'},{status}));assert.equal(await p,false);f.frame.render();assert.ok(f.frame.componentProps('WorkspaceForm'),'Unconfirmed form stays mounted');const retry=f.frame.seen.find(x=>x.type==='button'&&text(x.props.children)==='Retry the same change');if(!retry){const next=f.frame.componentProps('WorkspaceForm').send('message.send',{body:'Fictional committed before gateway failure'});const duplicate=JSON.parse(f.requests[1].init.body);f.requests[1].resolve(Response.json({recordId:'second-commit'}));await next;report.findings.push({name:'gateway-'+status+'-drops-idempotency',status,firstRequestId:sent.requestId,retryRequestId:duplicate.requestId,distinctRequestIds:sent.requestId!==duplicate.requestId});assert.fail('Gateway '+status+' cleared uncertain request identity and allowed fresh duplicate');}const p2=retry.props.onClick();assert.deepEqual(JSON.parse(f.requests[1].init.body),sent);f.requests[1].resolve(Response.json({recordId:'same-first-commit'}));await p2;mark('Gateway '+status+' retains form and exact uncertain command until acknowledgement');}finally{f.restore();}
});
test('root malformed JSON after save keeps same retry command',async()=>{
 const f=await browserFixture();try{const p=f.frame.componentProps('MyDay').send('message.send',{body:'Fictional post-commit bad JSON'}),sent=JSON.parse(f.requests[0].init.body);f.requests[0].resolve(new Response('{broken-confirmation',{status:200,headers:{'Content-Type':'application/json'}}));assert.equal(await p,false);f.frame.render();assert.doesNotMatch(f.frame.copy,/Saved\./);const retry=f.frame.button('Retry the same change').onClick();assert.deepEqual(JSON.parse(f.requests[1].init.body),sent);f.requests[1].resolve(Response.json({recordId:'same-committed-message'}));assert.equal(await retry,true);mark('Malformed JSON acknowledgement cannot erase original idempotent retry or label save confirmed');}finally{f.restore();}
});
for(const status of[400,409])test('root definite '+status+' rejection preserves form and permits corrected command',async()=>{
 const f=await browserFixture();try{f.frame.componentProps('MyDay').onTraining();f.frame.render();f.frame.componentProps('TrainingHub').onHelp();f.frame.render();const p=f.frame.componentProps('WorkspaceForm').send('message.send',{body:'Fictional original'}),sent=JSON.parse(f.requests[0].init.body);f.requests[0].resolve(Response.json({error:'Fictional definite rejection'},{status}));assert.equal(await p,false);f.frame.render();assert.doesNotMatch(f.frame.copy,/Retry the same change/);const form=f.frame.componentProps('WorkspaceForm'),p2=form.send('message.send',{body:'Fictional corrected'});assert.notEqual(JSON.parse(f.requests[1].init.body).requestId,sent.requestId);f.requests[1].resolve(Response.json({recordId:'corrected-message'}));assert.equal(await p2,true);mark('Definite '+status+' rejection retains form and allows a corrected request;409 reloads current workspace');}finally{f.restore();}
});
const item={planId:'fictional-plan',planRevision:4,definitionId:'ranch',quantity:10,unit:'cups',quantityMode:'whole-portions',title:'Ranch cups'};
async function prepFixture(){const previous=fetch,requests=[],events=[];globalThis.fetch=(url,init)=>new Promise((resolve,reject)=>requests.push({url:String(url),init,resolve,reject}));const frame=new Frame(PrepReport,{item,w:w(),apiRoot:'/api',onBusy:v=>events.push(['busy',v]),onSaved:()=>events.push(['saved']),onRefresh:()=>events.push(['refresh'])});frame.render();frame.runEffects();frame.field(p=>p.type==='number').onChange({target:{value:'7'}});frame.field(p=>p.maxLength===1000).onChange({target:{value:'Fictional ingredient short'}});frame.render();const submit=()=>frame.seen.find(x=>x.type==='form').props.onSubmit({preventDefault(){}});return{frame,requests,events,submit,restore(){frame.unmount();globalThis.fetch=previous;}};}
test('actual prep partial completion retains input and retry identity through malformed confirmation and network failure',async()=>{
 const f=await prepFixture();try{f.submit();f.submit();assert.equal(f.requests.length,1,'in-flight ref guards two submits before React commit');const sent=JSON.parse(f.requests[0].init.body);assert.equal(sent.input.quantity,7);assert.equal(sent.input.note,'Fictional ingredient short');f.requests[0].resolve(Response.json({recordId:'incomplete-envelope'}));await flush();f.frame.render();assert.equal(f.frame.field(p=>p.type==='number').value,'7');assert.match(f.frame.copy,/Save was not confirmed/);f.frame.button('Retry the same report').onClick();assert.deepEqual(JSON.parse(f.requests[1].init.body),sent);f.requests[1].reject(new Error('Fictional offline retry'));await flush();f.frame.render();assert.match(f.frame.copy,/Fictional offline retry/);f.frame.button('Retry the same report').onClick();assert.deepEqual(JSON.parse(f.requests[2].init.body),sent);f.requests[2].resolve(Response.json({recordId:'same-prep-report',revision:5}));await flush();assert.equal(f.events.filter(x=>x[0]==='saved').length,1);mark('Actual prep duplicate-submit guard and uncertain-save retries retain quantity, shortage note and exact command');}finally{f.restore();}
});
test('prep stale assignment/access denial refreshes work and success after unmount cannot report completion',async()=>{
 for(const status of[403,409]){const f=await prepFixture();try{f.submit();f.requests[0].resolve(Response.json({error:'Fictional changed assignment'},{status}));await flush();f.frame.render();assert.equal(f.events.filter(x=>x[0]==='refresh').length,1);assert.equal(f.events.filter(x=>x[0]==='saved').length,0);assert.doesNotMatch(f.frame.copy,/Retry the same report/);}finally{f.restore();}}
 const f=await prepFixture();try{f.submit();f.frame.unmount();const before=f.events.length;f.requests[0].resolve(Response.json({recordId:'late-save',revision:5}));await flush();assert.equal(f.events.length,before);assert.equal(f.frame.mutationsAfterUnmount,0);mark('Prep 403/409 requires fresh assignment and late unmounted completion cannot affect another screen');}finally{f.restore();}
});
test('assigned prep read hides prior restaurant immediately and ignores aborted late response',async()=>{
 const previous=fetch,requests=[],locks=[];globalThis.fetch=(url,init)=>new Promise(resolve=>requests.push({url:String(url),init,resolve}));const frame=new Frame(EmployeePrep,{w:w(),apiRoot:'/api',onBusy:v=>locks.push(v)});try{frame.render();frame.runEffects();requests[0].resolve(Response.json({locationId:'berts',dataset:'operating',items:[{...item,title:'Only Berts ranch'}]}));await flush();frame.render();assert.match(frame.copy,/Only Berts ranch/);frame.props={...frame.props,w:w('rudds')};frame.render();assert.doesNotMatch(frame.copy,/Only Berts ranch/);frame.runEffects();assert.equal(requests[0].init.signal.aborted,true);requests[1].resolve(Response.json({locationId:'berts',dataset:'operating',items:[{...item,title:'Forbidden stale ranch'}]}));await flush();frame.render();assert.doesNotMatch(frame.copy,/Forbidden stale ranch/);assert.match(frame.copy,/Refresh this restaurant/);frame.unmount();assert.equal(requests[1].init.signal.aborted,true);assert.equal(locks.at(-1),false);mark('Employee assigned-prep scope transition clears prior work immediately and refuses wrong-store response');}finally{frame.unmount();globalThis.fetch=previous;}
});
