import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {openPositionDatabase} from './all-position-week-fixture.mjs';
import {handleWorkspace} from '../.sites-runtime/shared/service.mjs';

const NativeDate=Date,root=path.resolve('evidence/local-readiness-2026-10-08/rush',randomUUID());
fs.mkdirSync(root,{recursive:true});
const hashes=()=>Object.fromEntries(fs.readdirSync('.sites-runtime/shared').filter(f=>f.endsWith('.mjs')).sort().map(f=>[f,createHash('sha256').update(fs.readFileSync('.sites-runtime/shared/'+f)).digest('hex')]));
const reports=[];
for(const restaurant of ['berts','rudds','papa'])test(restaurant+': six multi-person service waves preserve tasks, receipts, messages and ownership',async()=>{
 const file=path.join(root,restaurant+'.sqlite'),runtimeBefore=hashes(),events=[],waves=[];let store,queue=Promise.resolve(),reopens=0,clock=NativeDate.parse('2026-10-21T16:00:00Z');
 const open=()=>{const result=openPositionDatabase(file),batch=result.db.batch.bind(result.db);result.db.batch=statements=>{const operation=queue.then(()=>batch(statements));queue=operation.catch(()=>{});return operation;};return result;};store=open();
 const report={restaurant,database:file,initialSeeds:1,operationalReseeds:0,externalCalls:0,runtimeBefore,events,waves,limits:['Fictional staff, reported work and SQLite; no hosted trial, real notifications, model calls or physical work.','Concurrent authenticated handlers share reads; the fixture serializes atomic SQLite transactions as D1 does. This is not a production throughput benchmark.','Six service waves use one durable database and supported generic task/handoff commands; dedicated Dishwasher replacement is not asserted here.']};
 globalThis.Date=class extends NativeDate{constructor(...args){super(...(args.length?args:[clock]));}static now(){return clock;}};
 const workers=Array.from({length:8},(_,i)=>({id:'worker'+i,area:i<4?'FOH':'BOH',position:i<4?(restaurant==='papa'?'Counter':'Server'):'Pizza Make'}));
 const find=id=>{const r=store.sqlite.prepare('SELECT * FROM records WHERE id=?').get(id);return r&&{...r,ownerId:r.owner_id,data:JSON.parse(r.data)};};
 const snapshot=()=>JSON.stringify(Object.fromEntries(['records','command_receipts','audit_events'].map(table=>[table,store.sqlite.prepare('SELECT * FROM '+table+' ORDER BY rowid').all()])));
 const req=(actor,body,location=restaurant)=>new Request('https://local-rush.example/api/workspace?locationId='+location,{headers:{'oai-authenticated-user-id':restaurant+'-'+actor+'-identity','oai-authenticated-user-email':restaurant+'-'+actor+'@example.test',Origin:'https://local-rush.example','Content-Type':'application/json'},...(body?{method:'POST',body:JSON.stringify(body)}:{})});
 const raw=async(actor,action,input={},record,rid=randomUUID(),location=restaurant)=>{const begin=performance.now(),body=action?{locationId:location,action,input,requestId:rid,...(record?{recordId:record.id??record.recordId,expectedRevision:record.revision}:{})}:undefined,response=await handleWorkspace(req(actor,body,location),store.db),data=await response.json(),event={actor,action:action??'workspace.read',location,requestId:rid,status:response.status,elapsedMs:performance.now()-begin,...(record?{recordId:record.id??record.recordId,expectedRevision:record.revision}:{}),body,result:data};events.push(event);return event;};
 const cmd=async(...args)=>{const result=await raw(...args);assert.equal(result.status,200,JSON.stringify(result));return result.result;};
 const invariant=()=>{
  assert.deepEqual(store.sqlite.prepare('SELECT actor_id,request_id,count(*) n FROM command_receipts GROUP BY actor_id,request_id HAVING count(*)>1').all(),[]);
  for(const r of store.sqlite.prepare('SELECT * FROM records').all()){assert.equal(r.location_id,restaurant);const d=JSON.parse(r.data);if(r.kind==='task'&&d.closingHandoff){assert.equal(r.owner_id,d.closingHandoff.acceptedBy);assert.equal(d.history.filter(h=>h.action==='accepted').length,1);if(d.phase==='closed')assert.ok(d.history.findLastIndex(h=>h.action==='verify')>d.history.findIndex(h=>h.action==='accepted'));}if(r.kind==='message'){assert.equal(new Set(d.readBy).size,d.readBy.length);assert.equal(new Set(d.recipients).size,d.recipients.length);}}
  for(const e of events.filter(e=>e.action!=='workspace.read')){const row=store.sqlite.prepare('SELECT * FROM command_receipts WHERE actor_id=? AND request_id=?').get(e.actor,e.requestId);if(e.status===200){assert.ok(row,'Successful commands must have a durable receipt');assert.deepEqual(JSON.parse(row.result),e.result);}else if(e.status===403)assert.equal(row,undefined,'Cross-store denied operations have no receipt');}
  const successful=new Map(events.filter(e=>e.status===200&&e.action!=='workspace.read').map(e=>[e.actor+'|'+e.requestId,e]));assert.equal(store.sqlite.prepare('SELECT count(*) n FROM command_receipts').get().n,successful.size,'Every persisted receipt must correspond exactly to one successful command');assert.equal(store.sqlite.prepare('SELECT count(*) n FROM audit_events').get().n,[...successful.values()].filter(e=>e.action!=='message.read').length,'Every successful mutation except receipt-only read acknowledgments has exactly one audit event');
 };
 const reopen=async()=>{await queue;invariant();const before=snapshot();store.close();store=open();assert.equal(snapshot(),before,'All tasks, audit and receipts survive reopen');reopens++;invariant();};
 const reviewedRetries=[];
 report.reviewedRetries=reviewedRetries;
 const reviewRetry=async(event)=>{assert.equal(event.status,409);const b=event.body,current=b.recordId?find(b.recordId):undefined,prior=store.sqlite.prepare('SELECT * FROM command_receipts WHERE actor_id=? AND request_id=?').get(event.actor,event.requestId);assert.ok(prior||!current||current.revision===b.expectedRevision,'A changed target requires a different review; never blindly replay competing intent');const result=await raw(event.actor,b.action,b.input,b.recordId?{id:b.recordId,revision:b.expectedRevision}:undefined,b.requestId,event.location);assert.equal(result.status,200,JSON.stringify(result));reviewedRetries.push({originalRequestId:b.requestId,actor:event.actor,action:b.action,observedRevision:current?.revision,receiptAlreadyPresent:!!prior});return result;};
 const wave=async(name,operations,expected,review=true)=>{const begun=performance.now(),outcomes=await Promise.all(operations.map(fn=>fn())),initialStatuses=outcomes.map(r=>r.status);if(review)for(let i=0;i<outcomes.length;i++)if(outcomes[i].status===409&&(!outcomes[i].body.recordId||find(outcomes[i].body.recordId)?.revision===outcomes[i].body.expectedRevision||store.sqlite.prepare('SELECT 1 FROM command_receipts WHERE actor_id=? AND request_id=?').get(outcomes[i].actor,outcomes[i].requestId)))outcomes[i]=await reviewRetry(outcomes[i]);if(expected)expected(outcomes);await reopen();waves.push({name,requests:outcomes.length,initialStatuses,statuses:outcomes.map(r=>r.status),elapsedMs:performance.now()-begun});return outcomes;};
 try{
  for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())store.sqlite.exec(fs.readFileSync('drizzle/'+f,'utf8').replaceAll('--> statement-breakpoint',''));
  for(const loc of ['berts','rudds','papa'])store.sqlite.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').run(loc,'Fictional '+loc,'America/New_York');
  for(const a of [...workers,{id:'gm',area:'FOH',position:'General manager',caps:['location.manage','tasks.manage','schedule.manage','schedule.publish','schedule.change','operations.escalation']},{id:'fohlead',area:'FOH',position:'FOH Manager',caps:['tasks.manage']},{id:'bohlead',area:'BOH',position:'BOH Manager',caps:['tasks.manage']}])store.sqlite.prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').run(a.id,restaurant+'-'+a.id+'@example.test',restaurant+'-'+a.id+'-identity',restaurant,'Fictional '+a.id,a.area,a.position,JSON.stringify(a.caps??[]),JSON.stringify([a.position]));
  const shifts=[];for(const w of workers){let shift=await cmd('gm','shift.save',{personId:w.id,position:w.position,start:'2026-10-21T15:00:00Z',end:'2026-10-22T02:00:00Z'});shifts.push(await cmd('gm','shift.publish',{},shift));}
  for(let round=0;round<6;round++){
   clock+=30*60000;const jobs=[];
   const created=await wave('round '+round+' concurrent task assignment',workers.map((w,i)=>()=>raw('gm','task.create',{ownerId:w.id,kind:i%2===0?'handoff':'issue',...(i%2===0?{incomingId:workers[i+1].id,shiftId:shifts[i].recordId}:{}),title:'Fictional round '+round+' '+w.id,detail:'Reported remaining work requires a real saved independent review.',due:'2026-10-21T23:00:00Z'})),results=>assert.ok(results.every(r=>r.status===200),JSON.stringify(results)));
   for(let i=0;i<8;i++)jobs.push(created[i].result.recordId);
   const operations=[];for(const w of workers){const i=workers.indexOf(w);operations.push(()=>raw(w.id,'task.transition',{step:'ready',note:'Reported task progress round '+round},find(jobs[i])),()=>raw(w.id,'message.send',{recipients:['gm',w.area==='FOH'?'fohlead':'bohlead'],title:'Rush progress '+round+' '+w.id,body:'Task '+jobs[i]+' requires manager follow-through.'}),()=>raw(w.id,'message.send',{recipients:['gm'],title:'Foreign forbidden',body:'Must not save'},undefined,randomUUID(),restaurant==='berts'?'rudds':'berts'));}
   await wave('round '+round+' simultaneous progress, notices, cross-store rejection',operations,results=>{assert.equal(results.filter(r=>r.status===200).length,16);assert.equal(results.filter(r=>r.status===403).length,8);});
   const competing=[];for(let i=0;i<8;i++){const r=find(jobs[i]),lead=workers[i].area==='FOH'?'fohlead':'bohlead',steps=round%2?['fix','verify']:['verify','fix'];for(const [n,actor]of ['gm',lead].entries())competing.push(()=>raw(actor,'task.transition',{step:steps[n],note:'Independent competing review '+round+' '+n},r));}
   const reviews=await wave('round '+round+' sixteen competing reviewer requests',competing,results=>{for(let i=0;i<8;i++)assert.deepEqual(results.slice(i*2,i*2+2).map(r=>r.status).sort(),[200,409]);});
   for(let i=0;i<8;i++){const r=find(jobs[i]);assert.equal(r.data.history.length,3);if(r.data.phase==='correction'){await cmd(workers[i].id,'task.transition',{step:'ready',note:'Reported correction'},r);await cmd('gm','task.transition',{step:'verify',note:'Correction independently reviewed'},find(jobs[i]));}}
   await reopen();
   const handoffOps=[];const accepts=[];for(let i=0;i<8;i+=2){const r=find(jobs[i]),rid='round-'+round+'-accept-'+i;assert.equal(r.data.phase,'acceptance');const input={step:'accept',note:'Incoming employee explicitly receives unfinished work'};accepts.push({actor:workers[i+1].id,input,record:r,rid});handoffOps.push(()=>raw(workers[i+1].id,'task.transition',input,r,rid),()=>raw(workers[i+1].id,'task.transition',input,r,rid));}
   await wave('round '+round+' duplicate simultaneous incoming acceptances',handoffOps,results=>assert.ok(results.every(r=>r.status===200),JSON.stringify(results)));
   const saved=snapshot();for(const a of accepts)await cmd(a.actor,'task.transition',a.input,a.record,a.rid);assert.equal(snapshot(),saved,'Retry after reopen returns exact acceptance receipt without duplicate notification');
   const remaining=[];for(let i=0;i<8;i+=2){const r=find(jobs[i]);assert.equal(r.ownerId,workers[i+1].id);assert.equal(r.data.phase,'open');remaining.push(()=>raw(r.ownerId,'task.transition',{step:'ready',note:'Received work completed'},r),()=>raw(workers[i].id,'task.transition',{step:'ready',note:'Former owner cannot complete'},r));}
   await wave('round '+round+' incoming completion versus former owner',remaining,results=>{assert.equal(results.filter(r=>r.status===200).length,4);assert.ok(results.filter(r=>r.status!==200).every(r=>[403,404,409].includes(r.status)));});
   await wave('round '+round+' independent final checks',jobs.filter((_,i)=>i%2===0).map(id=>()=>raw('gm','task.transition',{step:'verify',note:'Received remaining work checked'},find(id))),results=>assert.ok(results.every(r=>r.status===200)));
   assert.ok(jobs.every(id=>find(id).data.phase==='closed'));
   const messages=store.sqlite.prepare("SELECT * FROM records WHERE kind='message'").all().map(r=>({id:r.id,revision:r.revision,data:JSON.parse(r.data)})).filter(r=>r.data.title.startsWith('Rush progress '+round));assert.equal(messages.length,8);
   const reads=messages.flatMap(m=>[()=>raw('gm','message.read',{},m),()=>raw(m.data.recipients.find(id=>id!=='gm'),'message.read',{},m)]);
   await wave('round '+round+' managers concurrently acknowledge staff notices',reads,results=>assert.ok(results.every(r=>r.status===200),JSON.stringify(results)));
   for(const m of messages){const r=find(m.id);assert.ok(m.data.recipients.every(id=>r.data.readBy.includes(id)));}
   const message=find(messages[0].id);await wave('round '+round+' competing replies retain one current response', [()=>raw('gm','message.reply',{text:'GM route recorded'},message),()=>raw('fohlead','message.reply',{text:'FOH route recorded'},message)],results=>assert.deepEqual(results.map(r=>r.status).sort(),[200,409]));assert.equal(find(message.id).data.replies.length,1);
   const staleReply=await raw('gm','message.reply',{text:'Stale changed response'},message);assert.equal(staleReply.status,409);await reopen();
   for(const w of workers){const viewed=await raw(w.id);assert.equal(viewed.status,200);assert.ok(viewed.result.records.some(r=>r.kind==='message'&&r.data.title.includes('Rush progress '+round)));assert.ok(viewed.result.records.every(r=>r.locationId===restaurant));}
  }
  await reopen();report.status='passed';report.runtimeAfter=hashes();assert.deepEqual(report.runtimeAfter,runtimeBefore,'Compiled runtime changed during run');report.reopens=reopens;report.concurrentRequests=waves.reduce((n,w)=>n+w.requests,0);report.totalRequests=events.length;report.statusCounts=Object.fromEntries([...new Set(events.map(e=>e.status))].map(status=>[status,events.filter(e=>e.status===status).length]));report.counts=Object.fromEntries(['records','command_receipts','audit_events'].map(table=>[table,store.sqlite.prepare('SELECT count(*) n FROM '+table).get().n]));report.closedTasks=store.sqlite.prepare("SELECT count(*) n FROM records WHERE kind='task' AND json_extract(data,'$.phase')='closed'").get().n;assert.equal(report.closedTasks,48);report.elapsedMsRange={min:Math.min(...events.map(e=>e.elapsedMs)),max:Math.max(...events.map(e=>e.elapsedMs))};
 }catch(error){report.status='failed';report.error=String(error.stack??error);report.reopens=reopens;throw error;}finally{globalThis.Date=NativeDate;store.close();fs.writeFileSync(path.join(root,restaurant+'.json'),JSON.stringify(report,null,2));reports.push(report);}
});
test.after(()=>{fs.writeFileSync(path.join(root,'summary.json'),JSON.stringify({root,status:reports.every(r=>r.status==='passed')?'passed':'failed',cases:reports.length,restaurants:reports.map(r=>({restaurant:r.restaurant,status:r.status,totalRequests:r.totalRequests,concurrentRequests:r.concurrentRequests,waves:r.waves.length,reopens:r.reopens,counts:r.counts,closedTasks:r.closedTasks,statusCounts:r.statusCounts})),runtimeBefore:reports[0]?.runtimeBefore,runtimeAfter:reports.at(-1)?.runtimeAfter,externalCalls:0},null,2));console.log('Rush evidence: '+root);});
