import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {Miniflare} from 'miniflare';
import {handleWorkspace} from '../.sites-runtime/shared/service.mjs';
import {localDate} from '../.sites-runtime/shared/local-time.mjs';
import {closingSelection} from '../.sites-runtime/shared/publication.mjs';
import {seedMockWeek} from './mock-week-fixture.mjs';
process.env.MINIFLARE_REGISTRY_PATH??=path.resolve('.wrangler/registry');
test('full mock week: separate department drafts, final publication, coverage, inherited close and independent checkout',async t=>{
 const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("mock")}}',compatibilityDate:'2026-05-22',d1Databases:['DB']});t.after(()=>mf.dispose());const db=await mf.getD1Database('DB');
 for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())await db.batch(fs.readFileSync('drizzle/'+f,'utf8').split('--> statement-breakpoint').filter(s=>s.trim()).map(s=>db.prepare(s)));
 const call=async(actor,action,input={},record,requestId=crypto.randomUUID())=>{const response=await handleWorkspace(new Request('https://mock.example/api/workspace'+(action?'':'?locationId=review'),{method:action?'POST':'GET',headers:{'oai-authenticated-user-id':actor+'-fixture','oai-authenticated-user-email':actor+'@example.test',Origin:'https://mock.example','Content-Type':'application/json'},...(action?{body:JSON.stringify({requestId,locationId:'review',action,input,...(record?{recordId:record.id??record.recordId,expectedRevision:record.revision}:{})})}:{})}),db);return {status:response.status,data:await response.json()}};
 const ok=r=>{assert.equal(r.status,200,JSON.stringify(r.data));return r.data},view=async actor=>ok(await call(actor)),fresh=async(actor,r)=>(await view(actor)).records.find(s=>s.id===(r.id??r.recordId));
 const f=await seedMockWeek(db,call),select=rs=>rs.map(r=>({id:r.id??r.recordId,revision:r.revision}));
 assert.equal((await view('worker')).records.filter(r=>r.kind==='shift'||r.kind==='close').length,0);
 assert.equal((await view('manager')).records.filter(r=>r.kind==='shift').length,14);
 assert.equal((await view('boh')).records.filter(r=>r.kind==='shift').length,14);
 const initial=await view('publisher');assert.equal(initial.records.filter(r=>r.kind==='close').length,14);
 const input={weekStart:f.start,drafts:select(f.drafts).map(s=>({...s,closing:closingSelection(initial,s.id)})),confirmed:true,note:'Mock full-week review'};
 assert.equal((await call('manager','shift.publish-batch',input)).status,403);
 assert.equal((await call('boh','shift.save',{personId:'worker',position:'Server',...f.period(f.start,'10:00','11:00')})).status,403);
 assert.equal((await call('manager','shift.save',{personId:'worker',position:'Server',...f.period(f.start,'15:00','16:00')})).status,400);
 assert.equal((await call('manager','shift.save',{personId:'incoming',position:'Server',...f.period(f.days[2],'16:00','23:00')})).status,400);
 assert.equal((await call('boh','shift.save',{personId:'dish',position:'Cook',...f.period(f.start,'10:00','11:00')})).status,400);
 const beforePublication=await view('worker');assert.equal(beforePublication.records.some(r=>r.kind==='leadership'),false);
 assert.equal((await call('publisher','shift.publish-batch',{...input,drafts:input.drafts.map((s,i)=>i===1?{...s,closing:[]}:s)})).status,409);
 const retryId=crypto.randomUUID(),receipt=ok(await call('publisher','shift.publish-batch',input,undefined,retryId));
 assert.deepEqual(ok(await call('publisher','shift.publish-batch',input,undefined,retryId)),receipt);
 const week=await view('publisher'),shifts=week.records.filter(r=>r.kind==='shift');assert.equal(shifts.length,28);assert.ok(shifts.every(r=>r.data.published));
 assert.equal(shifts.reduce((n,r)=>n+(Date.parse(r.data.end)-Date.parse(r.data.start))/3600000,0),188);
 for(const day of f.days)assert.equal(shifts.filter(r=>localDate(r.data.start,f.zone)===day).length,4);
 assert.equal(shifts.filter(r=>localDate(r.data.end,f.zone)>localDate(r.data.start,f.zone)).length,3);
 const staff=await view('worker');assert.equal(staff.records.filter(r=>r.kind==='leadership').length,4);assert.ok(staff.records.filter(r=>r.kind==='leadership').every(r=>r.data.note===''));
 const dish=await view('dish');assert.equal(dish.records.filter(r=>r.kind==='shift').length,4);assert.equal(dish.records.some(r=>['close','task','goal','development'].includes(r.kind)),false);
 assert.equal((await view('worker')).records.filter(r=>r.kind==='message'&&r.data.title==='Shift published').length,4);
 const shift=shifts.find(r=>r.ownerId==='worker'&&localDate(r.data.start,f.zone)===f.start);
 let offer=ok(await call('worker','coverage.create',{shiftId:shift.id,shiftRevision:shift.revision,note:'Private fictional reason'}));
 const candidate=await fresh('incoming',offer);assert.equal(candidate.data.eligible,true);assert.equal(candidate.data.note,'');assert.equal(candidate.data.duties.length,1);
 offer=ok(await call('incoming','coverage.volunteer',{confirmed:true},candidate));assert.equal((await fresh('worker',shift)).ownerId,'worker');
 assert.equal((await call('boh','coverage.approve',{personId:'incoming',confirmed:true,note:'Wrong department'},offer)).status,404);
 const decisionId=crypto.randomUUID(),decision={personId:'incoming',confirmed:true,note:'Fictional replacement and duties reviewed'};
 const approval=ok(await call('manager','coverage.approve',decision,offer,decisionId));assert.deepEqual(ok(await call('manager','coverage.approve',decision,offer,decisionId)),approval);
 assert.equal(await fresh('worker',shift),undefined);const replacement=await fresh('incoming',shift);assert.equal(replacement.ownerId,'incoming');
 let close=(await view('incoming')).records.find(r=>r.kind==='close'&&r.data.shiftId===shift.id);assert.equal(close.ownerId,'incoming');assert.equal(close.data.phase,'open');
 assert.equal((await call('manager','shift.release',{note:'Too early'},replacement)).status,400);
 close=ok(await call('incoming','close.transition',{step:'ready',answers:[0,1],note:'Fictional completion'},close));
 close=ok(await call('senior','close.transition',{step:'verify',note:'Fictional first check'},close));
 close=ok(await call('manager','close.transition',{step:'confirm',note:'Fictional final check'},close));
 assert.equal((await fresh('incoming',close)).data.phase,'closed');assert.equal((await fresh('incoming',shift)).data.releasedAt,undefined);
 ok(await call('manager','shift.release',{note:'Fictional separate checkout'},replacement));assert.ok((await fresh('incoming',shift)).data.releasedAt);
 assert.equal((await view('publisher')).records.filter(r=>r.kind==='shift').length,28);
});
