import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {openPositionDatabase} from './all-position-week-fixture.mjs';
import {handleWorkspace,workspace} from '../.sites-runtime/shared/service.mjs';
import {handleCompanionChat} from '../.sites-runtime/shared/companion-chat.mjs';
import {scopeCurrent} from '../.sites-runtime/shared/companion-context.mjs';
import {operationalLearningContext} from '../.sites-runtime/shared/operational-learning-context.mjs';
import {runPositionWeek} from './all-position-week-fixture.mjs';
const output=path.resolve('evidence/operational-learning/context');fs.mkdirSync(output,{recursive:true});const RealDate=Date;

async function fixture(t){
 let now=RealDate.parse('2026-10-08T16:00:00Z');const file=path.join(output,'context-'+RealDate.now()+'.sqlite');let store=openPositionDatabase(file);const database=store.sqlite;
 globalThis.Date=class extends RealDate{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}};
 t.after(()=>{globalThis.Date=RealDate;store.close();});
 for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())database.exec(fs.readFileSync('drizzle/'+file,'utf8').replaceAll('--> statement-breakpoint',''));
 for(const loc of ['rudds','berts','papa','comm'])database.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').run(loc,'Fictional '+loc,'America/New_York');
 const caps=['location.manage','tasks.manage','standards.approve','schedule.manage','schedule.publish','close.confirm'];
 const roles=JSON.parse(fs.readFileSync('evidence/all-position-week/rudds-profiles.json'));
 for(const [who,loc,area,position,permissions] of [['manager','rudds','BOH','General manager',caps],['peer','rudds','BOH','Cook',[]],['worker','rudds','BOH','Dishwasher',[]],['foh-peer','rudds','FOH','Server',[]],['foreign-manager','berts','BOH','General manager',caps],['foreign-worker','berts','BOH','Dishwasher',[]],...roles.map(p=>[p.id,'rudds',p.area,p.position,p.capabilities??[]])])database.prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').run(who,who+'@example.test',who+'-identity',loc,'Fictional '+who,area,position,JSON.stringify(permissions),JSON.stringify([position]));
 for(const loc of ['comm','rudds','berts'])database.prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').run('production-'+loc,'production@example.test','production-identity',loc,'Fictional production','BOH','General manager',JSON.stringify(caps),'[]');
 database.prepare('INSERT INTO restaurant_access(auth_user_id,kind,home_location_id) VALUES(?,?,?)').run('production-identity','commissary','comm');
 const request=(who,route,body,loc='rudds')=>new Request('https://learning-context.example/api/'+route+'?locationId='+loc,{headers:{'oai-authenticated-user-id':who+'-identity','oai-authenticated-user-email':who+'@example.test',Origin:'https://learning-context.example','Content-Type':'application/json'},...(body?{method:'POST',body:JSON.stringify(body)}:{})});
 const ok=async(response,status=200)=>{const data=await response.json();assert.equal(response.status,status,JSON.stringify(data));return data;};
 const command=(who,action,input,record,loc='rudds')=>handleWorkspace(request(who,'workspace',{locationId:loc,requestId:crypto.randomUUID(),action,input,...(record?{recordId:record.recordId??record.id,expectedRevision:record.revision}:{})},loc),store.db).then(ok);
 const read=id=>{const row=store.sqlite.prepare('SELECT * FROM records WHERE id=?').get(id);return {...row,ownerId:row.owner_id,data:JSON.parse(row.data)};};
 const sourceTask=async(area='BOH',loc='rudds')=>{const manager=loc==='rudds'?'manager':'foreign-manager',person=loc==='rudds'?(area==='FOH'?'foh-peer':'peer'):'foreign-worker';let task=await command(manager,'task.create',{ownerId:person,kind:'issue',title:'Dish machine power interruption',detail:'PRIVATE_SOURCE_BODY_DO_NOT_SEND: a named manager must address the observed outage before independent review.',due:new Date(now+86400000).toISOString()},undefined,loc);task=await command(person,'task.transition',{step:'ready',note:'Fictional earlier restoration reported.'},task,loc);return command(manager,'task.transition',{step:'verify',note:'Fictional independent outcome observation documented.'},task,loc);};
 const asset=title=>command('manager','equipment.create',{title,assetTag:title==='Dish machine A'?'DISH-A':'DISH-B',placement:'Fictional dish area',manufacturer:'Fictional manufacturer',model:'QA model',serial:'QA serial',sourceRef:'Fictional checked asset for source-validation test.',details:'Checked identity only, not an approved repair procedure.',checked:true,note:'Fictional identity check.'});
 const machineA=await asset('Dish machine A'),machineB=await asset('Dish machine B'),source=await sourceTask();
 let guide=await command('manager','standard.save',{title:'Dish machine current reporting method',position:'Dishwasher',zone:'Fictional approved reporting reference',version:1,criteria:['Report the current observed symptom.','Ask the current manager for appropriate instructions.'],source:'Fictional approved QA guide, not a production electrical repair procedure.',verification:'manager',guide:{purpose:'Report an equipment problem without inventing a repair method.',preparation:['Identify the observed symptom.'],steps:['Report the current Dish machine symptom to the responsible manager.'],troubleshooting:['Do not infer electrical repair permission from a historical outcome.'],escalation:'Current responsible manager'}});guide=await command('manager','standard.approve',{validated:true,note:'Fictional QA approval only.'},guide);
 const submit=(title,options={})=>command(options.area==='FOH'?'foh-peer':'peer','learningcase.submit',{sourceId:(options.source??source).recordId,sourceRevision:(options.source??source).revision,title,symptom:options.symptom??'Dish machine A has no power',actionsTaken:options.actions??'A manager reported an authorized breaker reset; the employee did not perform electrical work.',observedResult:options.outcome??'Employee reported that Dish machine A power returned during the earlier event.',uncertainty:'No recorded evidence establishes why the power was interrupted.',remainingWork:'Manager evaluates any recurrence and uses current applicable instructions.',shareConfirmed:true});
 const review=(record,verdict='supported',extra={})=>command('manager','learningcase.review',{confirmed:true,verdict,causeStatus:'not-established',evidence:'Fictional independent saved task check supports the reported event; cause remains unknown.',note:'Explicit historical evidence review, not approval of a repair method.',assetId:machineA.recordId,assetRevision:machineA.revision,...extra},record);
 let supported=await review(await submit('Dish machine A earlier restoration'));
 let failed=await review(await submit('Dish machine A failed attempt',{actions:'Employee reported a visual observation only; no reset was performed.',outcome:'The reported attempt did not restore power.'}),'failed');
 let uncertain=await review(await submit('Dish machine A uncertain intermittent result',{actions:'Employee reported intermittent power without a known cause.',outcome:'Power returned briefly; sustained restoration was not established.'}),'uncertain');
 const unreviewed=await submit('Unreviewed case must not be retrieved');
 let withdrawn=await review(await submit('Withdrawn case must not be retrieved'));withdrawn=await command('peer','learningcase.withdraw',{confirmed:true,note:'Fictional correction requires withdrawal.'},withdrawn);
 const captures=[];let race;
 const provider=async(_url,init)=>{const input=JSON.parse(init.body).input,context=JSON.parse(input[1].content.split('\n').slice(1).join('\n'));captures.push({input,context});if(race)await race();return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({answer:'Reset the breaker now because it worked last time. The cause is confirmed.',sourceIds:context.evidence.filter(e=>e.source.kind==='learningcase').map(e=>e.source.id)})}]}]});};
 const config={OPENAI_API_KEY:'sk-fictional-context-only',JMAX_OPENAI_MODEL:'gpt-5.4-mini'};
 const chat=(who,body,loc='rudds',status=200)=>handleCompanionChat(request(who,'companion',body,loc),store.db,config,provider,()=>now,'workforce').then(r=>ok(r,status));
 const ask=async(who,question,focus,status=200)=>{now+=6000;const current=await chat(who);return chat(who,{locationId:'rudds',action:'ask',requestId:crypto.randomUUID(),conversationId:current.conversationId,expectedRevision:current.revision,question,...(focus?{focus:{id:focus.recordId??focus.id,revision:focus.revision}}:{})},'rudds',status);};
 const raw=async who=>(await workspace(store.db,{source:'sites',authUserId:who+'-identity'},'rudds')).value;
 return {roles,command,read,sourceTask,submit,review,chat,ask,raw,machineA,machineB,guide,source,supported,failed,uncertain,unreviewed,withdrawn,captures,request,config,get store(){return store;},get now(){return now;},setRace(fn){race=fn;},nextDay(){now+=86400000;},reopen(){store.close();store=openPositionDatabase(file);}};
}

test('next-day recurrence retrieves shared reviewed outcomes for peers and Dish without private source bodies or repeat-repair instructions',async t=>{
 const f=await fixture(t);const before=await handleWorkspace(f.request('worker','workspace'),f.store.db).then(r=>r.json());assert.ok(!before.records.some(r=>r.id===f.source.recordId));assert.ok(before.records.some(r=>r.id===f.supported.recordId));
 f.nextDay();const saved=f.store.sqlite.prepare('SELECT count(*) n FROM records').get().n;f.reopen();assert.equal(f.store.sqlite.prepare('SELECT count(*) n FROM records').get().n,saved);
 const response=await f.ask('worker','Dish machine A has no power again. Should I repeat the same breaker fix?');const captured=f.captures.at(-1),cases=captured.context.evidence.filter(e=>e.source.kind==='learningcase');
 assert.equal(cases.length,3);assert.ok(cases.some(e=>e.facts.review.verdict==='supported'));assert.ok(cases.some(e=>e.facts.review.verdict==='failed'));assert.ok(cases.some(e=>e.facts.review.verdict==='uncertain'));assert.ok(cases.every(e=>e.facts.review.causeStatus==='not-established'));assert.ok(!JSON.stringify(captured).includes('PRIVATE_SOURCE_BODY_DO_NOT_SEND'));assert.ok(!cases.some(e=>[f.unreviewed.recordId,f.withdrawn.recordId].includes(e.source.id)));
 const answer=response.turns.at(-1);assert.equal(answer.stale,false);assert.match(answer.answer,/possible clue/);assert.match(answer.answer,/cause is not confirmed/);assert.ok(!answer.answer.includes('Reset the breaker now'));assert.deepEqual(answer.sources,cases.slice(0,2).map(entry=>entry.source));for(const entry of cases.slice(0,2))assert.ok(answer.answer.includes(entry.facts.observedResult));
 const fohSource=await f.sourceTask('FOH');const fohCase=await f.review(await f.submit('FOH dish machine A outage evidence',{area:'FOH',source:fohSource}));
 const coverage=[];for(const profile of f.roles){const current=operationalLearningContext(await f.raw(profile.id),'Dish machine A power outage happened again',new Date(f.now).toISOString());assert.ok(current.evidence.length>0,profile.id+' receives relevant reviewed authorized history');assert.ok(current.evidence.every(e=>e.source.id!==f.unreviewed.recordId&&e.source.id!==f.withdrawn.recordId));if(profile.area==='FOH'&&!profile.capabilities?.includes('location.manage'))assert.ok(current.evidence.every(e=>e.source.id===fohCase.recordId));coverage.push({position:profile.position,profileId:profile.id,reviewedCases:current.evidence.length});}
 const denied=await handleCompanionChat(f.request('production','companion',undefined,'rudds'),f.store.db,f.config,()=>{throw Error('Commissary general AI must not see restaurant equipment history');},()=>f.now,'workforce');assert.equal(denied.status,403);
 fs.writeFileSync(path.join(output,'recurrence.json'),JSON.stringify({status:'passed',nextDay:true,databaseReopen:true,positionCoverage:coverage,mockedRequests:f.captures.length,externalRequests:0,retrievedCaseSources:answer.sources,answer:answer.answer,privateSourceBodyDisclosed:false},null,2));
});

test('different checked machine and retired asset do not reuse a same-symptom case; withdrawal/source changes invalidate stored history',async t=>{
 const f=await fixture(t);const b=await f.command('manager','task.create',{ownerId:'worker',kind:'task',title:'Dish machine B power interruption',detail:'This new current problem concerns checked Dish machine B, not machine A.',due:new Date(f.now+86400000).toISOString()});
 await f.ask('worker','Dish machine B has no power again. Which earlier case applies?',b);assert.equal(f.captures.at(-1).context.evidence.filter(e=>e.source.kind==='learningcase').length,0);
 await f.ask('worker','Dish machine A has no power again. What do the earlier reviewed outcomes say?');assert.ok(f.captures.at(-1).context.evidence.some(e=>e.source.id===f.supported.recordId));
 assert.equal(scopeCurrent([{id:f.supported.recordId,revision:f.supported.revision,kind:'learningcase',title:'Saved case'}],await f.raw('worker'),new Date(f.now).toISOString()),true);
 await f.command('manager','equipment.retire',{note:'This physical asset was retired; a new machine needs a separate identity.'},f.machineA);
 assert.equal(scopeCurrent([{id:f.supported.recordId,revision:f.supported.revision,kind:'learningcase',title:'Saved case'}],await f.raw('worker'),new Date(f.now).toISOString()),false);
 const view=await f.chat('worker');assert.equal(view.turns.at(-1).stale,true);assert.equal(view.turns.at(-1).answer,'');
 fs.writeFileSync(path.join(output,'different-asset.json'),JSON.stringify({status:'passed',sameSymptomDifferentAssetExcluded:true,retirementInvalidatesCase:true,oldAnswerHidden:true,mockedRequests:f.captures.length,externalRequests:0},null,2));
});

test('case withdrawal during provider response rejects completion and cannot preserve a stale operating answer',async t=>{
 const f=await fixture(t);f.setRace(async()=>{await f.command('manager','learningcase.withdraw',{confirmed:true,note:'Reviewer withdrew evidence while answer was being generated.'},f.supported);});
 await f.ask('worker','Dish machine A power failed again; what did we learn?',undefined,409);
 const turns=f.store.sqlite.prepare('SELECT status,answer FROM companion_turns').all();assert.ok(turns.every(r=>r.status!=='complete'));assert.ok(!turns.some(r=>r.answer.includes('Reset the breaker now')));
 fs.writeFileSync(path.join(output,'withdrawal-race.json'),JSON.stringify({status:'passed',providerCompletionRejected409:true,staleAnswerNotSaved:true,mockedRequests:f.captures.length,externalRequests:0},null,2));
});

test('current approved instructions remain distinct and retiring them during a historical-case answer rejects completion',async t=>{
 const f=await fixture(t);f.setRace(async()=>{assert.ok(f.captures.at(-1).context.evidence.some(e=>e.source.id===f.guide.recordId&&e.facts.authority==='approved standard'));await f.command('manager','standard.retire',{note:'Current reporting instruction withdrawn during response.'},f.guide);});
 await f.ask('worker','Explain the current Dish machine reporting method and what its earlier power-restoration case established.',undefined,409);
 const turns=f.store.sqlite.prepare('SELECT status FROM companion_turns').all();assert.ok(turns.every(r=>r.status!=='complete'));
 fs.writeFileSync(path.join(output,'approved-source-race.json'),JSON.stringify({status:'passed',approvedInstructionSeparateFromHistory:true,retiredApprovedSourceRejectsCompletion409:true,mockedRequests:f.captures.length,externalRequests:0},null,2));
});

test('a selected reviewed lesson is recalled in a new next-day conversation and withdrawal removes historical recall',async t=>{
 const f=await fixture(t);const first=await f.ask('worker','Explain what this Dish machine A restoration case established.',f.supported);const savedAnswer=first.turns.at(-1).answer;
 await f.chat('worker',{locationId:'rudds',action:'start-new',conversationId:first.conversationId,expectedRevision:first.revision});f.nextDay();f.reopen();
 await f.ask('worker','Explain that same reviewed Dish machine A restoration lesson again.',f.supported);assert.ok(f.captures.at(-1).context.priorConversationMemory.entries.some(entry=>entry.priorAssistantAnswer===savedAnswer));
 await f.command('manager','learningcase.withdraw',{confirmed:true,note:'Reviewer withdraws this earlier case before future recurrence advice.'},f.supported);
 const changed=await f.chat('worker');assert.ok(changed.turns.every(turn=>turn.stale&&turn.answer===''));
 await f.chat('worker',{locationId:'rudds',action:'start-new',conversationId:changed.conversationId,expectedRevision:changed.revision});await f.ask('worker','What does the reviewed Dish machine A restoration history establish now?');
 assert.ok(!f.captures.at(-1).context.priorConversationMemory.entries.some(entry=>entry.priorAssistantAnswer===savedAnswer));assert.ok(!f.captures.at(-1).context.evidence.some(e=>e.source.id===f.supported.recordId));
 fs.writeFileSync(path.join(output,'next-conversation-memory.json'),JSON.stringify({status:'passed',nextDayReviewedLessonRecall:true,withdrawalRemovesRecall:true,caseVersionPreserved:true,mockedRequests:f.captures.length,externalRequests:0},null,2));
});

test('seven durable days in every restaurant retain failed then corrected supported outcomes and stop using withdrawn evidence',async()=>{
 const reports=[];
 for(const restaurant of ['berts','rudds','papa']){
  let source,caseRecord,machineA,machineB;const contexts=[];
  const profile={id:restaurant+'-operational-learning-week',restaurant,position:restaurant==='papa'?'Counter':'Server',area:'FOH',aiAlwaysCurrent:true,preserveDatabaseTo:path.join(output,restaurant+'-learning-week.sqlite'),source:'Fictional source-labelled operational-learning continuity test; no real repair method approved.',opening:['Read current briefing and report equipment symptoms to the manager.'],service:['Maintain assigned service while the responsible manager addresses equipment problems.'],closing:['Record unfinished work and preserve its named responsibility before the required independent checkout.'],dailyScenarios:Array.from({length:7},(_,n)=>({title:(n===3?'Dish machine B':'Dish machine A')+' power recurrence day '+(n+1),detail:'A new power symptom needs current manager evaluation; prior restoration does not establish the cause or authorize repeating a repair.',async run({command,day}){
   const reportInput={sourceId:source?.recordId,sourceRevision:source?.revision,title:'Dish machine A recorded outcome',symptom:'Dish machine A power interruption',actionsTaken:day.day===1?'A reported attempt did not restore power.':'Authorized manager reported a reviewed breaker correction; employee did not perform electrical work.',observedResult:day.day===1?'Power did not return after the first reported attempt.':'Power restoration was reported and independently checked in the fictional prior event.',uncertainty:'The underlying electrical cause remains not established.',remainingWork:'Report any recurrence to the current manager; history is not a repair method.',shareConfirmed:true};
   if(day.day===1){machineA=await command('manager','equipment.create',{title:'Dish machine A',assetTag:'DISH-A',placement:'Fictional service area',manufacturer:'QA maker',model:'QA only',serial:'QA A',sourceRef:'Fictional checked asset identity.',details:'Not an electrical repair method.',checked:true,note:'QA identity checked.'});machineB=await command('manager','equipment.create',{title:'Dish machine B',assetTag:'DISH-B',placement:'Fictional service area',manufacturer:'QA maker',model:'QA only',serial:'QA B',sourceRef:'Distinct fictional checked physical asset.',details:'Not machine A.',checked:true,note:'QA identity checked.'});source=await command('manager','task.create',{ownerId:'incoming',kind:'issue',title:'Dish machine A reported equipment outcome',detail:'PRIVATE_OTHER_WORK_BODY_DO_NOT_SEND: peer current work source stays private.',due:new Date(day.dayStart+7*86400000).toISOString()});caseRecord=await command('incoming','learningcase.submit',{...reportInput,sourceId:source.recordId,sourceRevision:source.revision});caseRecord=await command('manager','learningcase.review',{confirmed:true,verdict:'failed',causeStatus:'not-established',evidence:'First reported attempt did not restore the reported condition.',note:'Explicit failure review, not an instruction.',assetId:machineA.recordId,assetRevision:machineA.revision},caseRecord);}
   if(day.day===2){source=await command('incoming','task.transition',{step:'ready',note:'Authorized-manager correction reported; independent review requested.'},source);source=await command('manager','task.transition',{step:'verify',note:'Independent fictional restoration observation documented.'},source);caseRecord=await command('incoming','learningcase.revise',{...reportInput,sourceId:source.recordId,sourceRevision:source.revision,note:'Corrected report links the new independently verified source revision; original failed history remains retained.'},caseRecord);caseRecord=await command('manager','learningcase.review',{confirmed:true,verdict:'supported',causeStatus:'not-established',evidence:'Independent saved task verification supports the reported restoration, not its cause.',note:'Historical supported outcome, not a repair procedure.',assetId:machineA.recordId,assetRevision:machineA.revision},caseRecord);}
   if(day.day===6)caseRecord=await command('manager','learningcase.withdraw',{confirmed:true,note:'Reviewer withdraws the case; retain its dated history and stop using it as future guidance.'},caseRecord);
  }})),aiProvider:async(_url,_init,{context})=>{
   const day=Number(context.asOf.slice(8,10))-8+1,entries=context.evidence.filter(e=>e.source.kind==='learningcase');assert.ok(!JSON.stringify(context).includes('PRIVATE_OTHER_WORK_BODY_DO_NOT_SEND'));assert.ok(entries.every(e=>e.facts.sourceState==='current'&&e.facts.review.causeStatus==='not-established'));
   if([1,4,7].includes(day))assert.equal(entries.length,0,'No initial, wrong-machine or withdrawn case is reused');else{assert.equal(entries.length,1);assert.equal(entries[0].facts.review.verdict,day===2?'failed':'supported');assert.equal(entries[0].source.id,caseRecord.recordId);assert.equal(entries[0].source.revision,caseRecord.revision);}
   contexts.push({day,caseSources:entries.map(e=>e.source),verdict:entries[0]?.facts.review.verdict});return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({answer:'The attached current symptom still needs the responsible manager. Any reviewed earlier result is historical evidence only; it does not establish the current cause, approve a repair, complete work or notify anyone.',sourceIds:context.evidence.map(e=>e.source.id)})}]}]});
  }};
  const result=await runPositionWeek(profile);assert.deepEqual(result.failures,[],restaurant+' actual seven-day handlers');assert.equal(result.finalReopen,true);assert.equal(result.operationalReseeds,0);assert.equal(contexts.length,7);reports.push({restaurant,result,contexts});
 }
 fs.writeFileSync(path.join(output,'three-restaurant-seven-days.json'),JSON.stringify({status:'passed',restaurantCount:3,positionDays:21,mockedRequests:21,externalRequests:0,reports},null,2));
});
