import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import ts from 'typescript';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {openPositionDatabase} from './all-position-week-fixture.mjs';

const runId=new Date().toISOString().replaceAll(':','-').replaceAll('.','-');
const evidence=path.resolve('evidence/operational-growth-ui',runId),compiled=path.resolve('.sites-runtime/operational-growth-ui',runId);
fs.mkdirSync(evidence,{recursive:true});fs.mkdirSync(compiled,{recursive:true});
const fingerprint=file=>({file,sha256:createHash('sha256').update(fs.readFileSync(file)).digest('hex')});
// Isolate the current source from the older frozen runtime used by long trials.
// This matches the repository's shared-test transpilation, without overwriting it.
const shared=path.join(compiled,'shared');fs.mkdirSync(shared,{recursive:true});
for(const name of fs.readdirSync('app/shared').filter(n=>n.endsWith('.ts'))){const js=ts.transpileModule(fs.readFileSync('app/shared/'+name,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replace(/from (['"])(\.\/[^'"]+)\1/g,(_,q,specifier)=>`from ${q}${specifier}.mjs${q}`);fs.writeFileSync(path.join(shared,name.replace('.ts','.mjs')),js);}
const {handleWorkspace}=await import(pathToFileURL(path.join(shared,'service.mjs'))),{closingStatus}=await import(pathToFileURL(path.join(shared,'closing-status.mjs'))),{workforceContext}=await import(pathToFileURL(path.join(shared,'workforce-context.mjs')));
const report={execution:'Actual local saved workspace states, React SSR and captured actual form callbacks; fictional records. Current source transpiled to an isolated runtime; frozen shared runtime is untouched.',sourceRevision:{isolatedRuntime:['domain','closing-status','shift-brief','workforce-context','service'].map(name=>fingerprint(path.join(shared,name+'.mjs'))),currentUi:['operational-learning','position-achievements','my-day','workspace'].map(name=>fingerprint('app/team/'+name+'.tsx'))},checks:[],limits:['No browser click, viewport measurement or full mounted app navigation is exercised.','A JSX-runtime observer records rendered form callbacks without replacing component hooks or callback logic.','Acceptance records incoming responsibility; it does not complete PM work, perform a physical check or release an employee.','No live AI, Toast, Jeff or restaurant records are used.']};
// Observe real rendered native form props while forwarding React's JSX runtime.
// React itself still invokes components/hooks during server rendering.
const captureKey='__jmaxDishUiForms_'+runId;
const observer=path.join(compiled,'jsx-observer.mjs');
fs.writeFileSync(observer,`import {jsx as actualJsx,jsxs as actualJsxs,Fragment} from 'react/jsx-runtime';\nexport {Fragment};\nfunction observe(type,props){if(type==='form'||type==='button')globalThis[${JSON.stringify(captureKey)}]?.push({...props,capturedType:type});}\nexport function jsx(type,props,key){observe(type,props);return actualJsx(type,props,key);}\nexport function jsxs(type,props,key){observe(type,props);return actualJsxs(type,props,key);}\n`);
const visited=new Set();
function compile(file){if(visited.has(file))return;visited.add(file);const destination=path.join(compiled,path.relative(path.resolve('app'),file).replace(/\.tsx?$/,'.mjs'));let js=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;js=js.replace(/from (["'])react\/jsx-runtime\1/g,(_,q)=>`from ${q}${pathToFileURL(observer).href}${q}`).replace(/import ['"][^'"]+\.css['"];?/g,'').replace(/from (['"])(\.\.?\/[^'"]+)\1/g,(_,q,specifier)=>{const base=path.resolve(path.dirname(file),specifier);if(base.startsWith(path.resolve('app/shared')+path.sep))return `from ${q}${pathToFileURL(path.join(shared,path.relative(path.resolve('app/shared'),base)+'.mjs')).href}${q}`;const dependency=['.ts','.tsx'].map(ext=>base+ext).find(f=>fs.existsSync(f));assert.ok(dependency,base);compile(dependency);return `from ${q}${specifier}.mjs${q}`;});fs.mkdirSync(path.dirname(destination),{recursive:true});fs.writeFileSync(destination,js);}
for(const name of ['operational-learning','position-achievements','my-day','workspace-forms'])compile(path.resolve('app/team/'+name+'.tsx'));
const {OperationalLearning,OperationalLearningCard,OperationalLearningHome}=await import(pathToFileURL(path.join(compiled,'team/operational-learning.mjs'))),{PositionAchievements}=await import(pathToFileURL(path.join(compiled,'team/position-achievements.mjs'))),{MyDay}=await import(pathToFileURL(path.join(compiled,'team/my-day.mjs'))),{positionAchievements}=await import(pathToFileURL(path.join(shared,'position-achievements.mjs')));
const now='2026-10-15T21:00:00Z';
function render(label,component,props){globalThis[captureKey]=[];const html=renderToStaticMarkup(React.createElement(component,props));const captured=globalThis[captureKey],forms=captured.filter(p=>p.capturedType==='form'),buttons=captured.filter(p=>p.capturedType==='button');delete globalThis[captureKey];fs.writeFileSync(path.join(evidence,label+'.html'),html);return {html,forms,buttons};}
const mark=(label,details={})=>report.checks.push({label,status:'passed',...details});
function button(html,text){const match=[...html.matchAll(/<button\b([^>]*)>([\s\S]*?)<\/button>/g)].find(m=>m[2].replace(/<[^>]+>/g,'')===text);assert.ok(match,'Missing button '+text);return {disabled:/\bdisabled(?:=|\s|$)/.test(match[1]),markup:match[0]};}
async function submit(form,step,note,fields={}){const original=globalThis.FormData;try{globalThis.FormData=class{get(key){return key==='note'?note:fields[key]??null;}entries(){return Object.entries({...fields,...(note?{note}:{})})}};await form.onSubmit({preventDefault(){},currentTarget:{},nativeEvent:{submitter:{getAttribute:()=>step}}});await new Promise(resolve=>setImmediate(resolve));}finally{globalThis.FormData=original;}}
async function fixture(t,fileName='durable-ui.sqlite'){const file=path.join(evidence,fileName);let store=openPositionDatabase(file);t.after(()=>store.close());for(const name of fs.readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())store.sqlite.exec(fs.readFileSync('drizzle/'+name,'utf8').replaceAll('--> statement-breakpoint',''));store.sqlite.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').run('berts','Fictional Bert’s','America/New_York');for(const [id,area,position,caps]of [['am','BOH','Dishwasher',[]],['pm','BOH','Dishwasher',[]],['pm2','BOH','Dishwasher',[]],['manager','BOH','General manager',['location.manage','tasks.manage','schedule.manage','schedule.publish','schedule.change','close.confirm','standards.approve']],['server','FOH','Server',[]]])store.sqlite.prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').run(id,id+'@example.test',id+'-ui-identity','berts','Fictional '+id,area,position,JSON.stringify(caps),JSON.stringify([position]));const request=(actor,body)=>new Request('https://dish-ui.example/api/workspace?locationId=berts',{headers:{'oai-authenticated-user-id':actor+'-ui-identity','oai-authenticated-user-email':actor+'@example.test',Origin:'https://dish-ui.example','Content-Type':'application/json'},...(body?{method:'POST',body:JSON.stringify(body)}:{})});const raw=async(actor,action,input={},r)=>{const response=await handleWorkspace(request(actor,action?{locationId:'berts',requestId:crypto.randomUUID(),action,input,...(r?{recordId:r.id??r.recordId,expectedRevision:r.revision}:{})}:undefined),store.db);return {status:response.status,data:await response.json()};};const command=async(...args)=>{const r=await raw(...args);assert.equal(r.status,200,JSON.stringify(r.data));return r.data;};const work=actor=>command(actor);const record=id=>{const row=store.sqlite.prepare('SELECT * FROM records WHERE id=?').get(id.recordId??id.id??id);return {...row,ownerId:row.owner_id,data:JSON.parse(row.data)};};const rows=()=>store.sqlite.prepare('SELECT id FROM records').all().map(r=>record(r.id));const shift=async(actor,start,end)=>command('manager','shift.publish',{},await command('manager','shift.save',{personId:actor,position:actor==='server'?'Server':'Dishwasher',start,end}));const finish=async(task)=>command('manager','task.transition',{step:'verify',note:'Fictional independent check.'},await command(task.ownerId,'task.transition',{step:'ready',note:'Fictional work reported ready.'},task));const props=(w)=>({w,now,onOpen(){},onWeek(){},onGuides(){},onAskWeek(){},onTraining(){},onSchedule(){},onDuties(){},onAsk(){},onStart(){},onError(){},send:async()=>true});const reopen=()=>{const before=JSON.stringify(rows());store.close();store=openPositionDatabase(file);assert.equal(JSON.stringify(rows()),before);};return {command,raw,work,record,rows,shift,finish,props,reopen,sqlite:()=>store.sqlite};}
test.after(()=>{report.expectedChecks=8;report.status=report.checks.length===8?'passed':'incomplete or failed';fs.writeFileSync(path.join(evidence,'summary.json'),JSON.stringify(report,null,2)+'\n');});

const formFor=(rendered,action)=>{const f=rendered.forms.find(f=>f['data-workflow']===action);assert.ok(f,'Missing actual rendered workflow '+action);return f;};
const uiSend=(f,actor,sent=[])=>async(action,input,r)=>{sent.push({action,input,recordId:r?.id});const result=await f.raw(actor,action,input,r);if(result.status!==200)throw Error(result.data.error??'Change was not saved');return true;};

test('Dish shares only explicit facts; interrupted save retries, independent review needs current checked evidence, peer view remains narrow and withdrawal persists',async t=>{
 const f=await fixture(t,'growth-report-ui.sqlite');f.sqlite().prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').run('peer','peer@example.test','peer-ui-identity','berts','Fictional peer','BOH','Dishwasher','[]','["Dishwasher"]');
 let task=await f.command('manager','task.create',{ownerId:'am',title:'Fictional assigned cleanup work',detail:'PRIVATE_LINKED_TASK_DETAIL, not authorized for peer view.',kind:'task',due:'2026-10-16T04:00:00Z'});
 const fields={sourceId:task.recordId,sourceRevision:String(task.revision),title:'A checked shift lesson',symptom:'Observed repeated backed-up work',actionsTaken:'Followed assigned correction with manager direction',observedResult:'The reported backlog cleared',uncertainty:'Long-term cause has not been established',remainingWork:'Monitor the next shift',shareConfirmed:'on'};
 const sent=[];let w=await f.work('am'),rendered=render('dish-share-report',OperationalLearning,{w,send:uiSend(f,'am',sent),onOpen(){}});assert.match(rendered.html,/Private conversations|private JMAX conversations/);assert.ok(!rendered.html.includes('PRIVATE_LINKED_TASK_DETAIL'));const submitForm=formFor(rendered,'learningcase.submit');
 f.sqlite().exec("CREATE TRIGGER fail_learning_ui BEFORE INSERT ON records WHEN NEW.kind='learningcase' BEGIN SELECT RAISE(ABORT,'Fictional interrupted case save'); END");await submit(submitForm,'','',fields);assert.equal(f.rows().filter(r=>r.kind==='learningcase').length,0);f.sqlite().exec('DROP TRIGGER fail_learning_ui');await submit(submitForm,'','',fields);assert.equal(sent.length,2);assert.deepEqual(sent[0],sent[1]);let reportRecord=f.rows().find(r=>r.kind==='learningcase');assert.equal(reportRecord.data.status,'reported');assert.equal(reportRecord.data.review,null);assert.equal(reportRecord.data.symptom,fields.symptom);assert.equal(typeof sent[1].input.sourceRevision,'number');assert.ok(!(await f.work('peer')).records.some(r=>r.id===reportRecord.id));f.reopen();mark('All-role Dish report form survives an actual failed save and explicit same-form retry; pending report stays private to reporter/reviewers');
 w=await f.work('am');rendered=render('dish-own-report-no-self-review',OperationalLearningCard,{r:w.records.find(r=>r.id===reportRecord.id),w,send:uiSend(f,'am'),onOpen(){}});assert.ok(!rendered.forms.some(f=>f['data-workflow']==='learningcase.review'));let mw=await f.work('manager');rendered=render('manager-unchecked-outcome',OperationalLearningCard,{r:mw.records.find(r=>r.id===reportRecord.id),w:mw,send:uiSend(f,'manager'),onOpen(){}});assert.match(rendered.html,/<option value="supported" disabled=""/);assert.match(rendered.html,/Equipment identity alone is not repair evidence/);mark('Reporter has no self-review action; manager supported outcome is disabled before independently checked work');
 task=await f.command('am','task.transition',{step:'ready',note:'Fictional initial work reported ready.'},task);task=await f.command('manager','task.transition',{step:'fix',note:'Review found work still incomplete; correct it.'},task);task=await f.command('am','task.transition',{step:'ready',note:'Fictional correction reported complete.'},task);task=await f.command('manager','task.transition',{step:'verify',note:'Independent recorded correction check.'},task);
 mw=await f.work('manager');rendered=render('manager-stale-linked-evidence',OperationalLearningCard,{r:mw.records.find(r=>r.id===reportRecord.id),w:mw,send:uiSend(f,'manager'),onOpen(){}});assert.match(rendered.html,/linked evidence is changed/);assert.match(rendered.html,/Review is paused/);assert.ok(!rendered.forms.some(f=>f['data-workflow']==='learningcase.review'));
 w=await f.work('am');rendered=render('dish-relink-current-report',OperationalLearningCard,{r:w.records.find(r=>r.id===reportRecord.id),w,send:uiSend(f,'am'),onOpen(){}});await submit(formFor(rendered,'learningcase.revise'),'','Relink the independently checked current task',{...fields,sourceRevision:String(task.revision)});reportRecord=f.record(reportRecord);assert.equal(reportRecord.data.review,null);assert.equal(reportRecord.data.source.revision,task.revision);
 const machine=await f.command('manager','equipment.create',{title:'Fictional dish machine',assetTag:'DISH-QA-01',placement:'Fictional Dish area',sourceRef:'Fictional checked asset record',checked:true,note:'QA identity checked; no physical inspection claim.'});const otherMachine=await f.command('manager','equipment.create',{title:'Different fictional machine',assetTag:'DISH-QA-02',placement:'Fictional other area',sourceRef:'Separate fictional checked asset',checked:true,note:'Separate physical identity in QA.'});
 mw=await f.work('manager');rendered=render('manager-current-evidence-review',OperationalLearningCard,{r:mw.records.find(r=>r.id===reportRecord.id),w:mw,send:uiSend(f,'manager'),onOpen(){}});assert.match(rendered.html,/<option value="supported">/);await submit(formFor(rendered,'learningcase.review'),'','Reviewed outcome only, not a new procedure',{verdict:'supported',evidence:'Independent verified saved task and observed employee report',causeStatus:'not-established',assetId:machine.recordId,assetRevision:String(machine.revision),confirmed:'on'});reportRecord=f.record(reportRecord);assert.equal(reportRecord.data.status,'reviewed');assert.equal(reportRecord.data.review.by,'manager');assert.equal(reportRecord.data.review.causeStatus,'not-established');assert.equal(reportRecord.data.review.cause,'');assert.equal(reportRecord.data.asset.id,machine.recordId);mw=await f.work('manager');const locked=render('review-original-equipment-lock',OperationalLearningCard,{r:mw.records.find(r=>r.id===reportRecord.id),w:mw,send:uiSend(f,'manager'),onOpen(){}}).html;const assetOptions=locked.match(/<select name="assetId"[\s\S]*?<\/select>/)?.[0];assert.ok(assetOptions);assert.match(assetOptions,new RegExp(machine.recordId));assert.doesNotMatch(assetOptions,new RegExp(otherMachine.recordId));mark('Changed evidence blocks review; actual corrected linkage plus independent checked work saves supported outcome without inventing a cause or procedure');
 const ownReviewed=await f.work('am');assert.equal(positionAchievements(ownReviewed).find(c=>c.id==='shared-learning').state,'earned','Actual independent operational review automatically records the supported lesson milestone');const earnedHtml=render('review-automatically-earned-lesson-progress',PositionAchievements,{w:ownReviewed,send:uiSend(f,'am'),onOpen(){},onlyId:positionAchievements(ownReviewed).find(c=>c.id==='shared-learning').recordId}).html;assert.match(earnedHtml,/Helpful Lesson/);assert.match(earnedHtml,/Verified progress/);
 const originalEarnedAt=positionAchievements(ownReviewed).find(c=>c.id==='shared-learning').earnedAt;
 const updatedMachine=await f.command('manager','equipment.revise',{title:'Fictional dish machine',assetTag:'DISH-QA-01',placement:'Fictional Dish area',sourceRef:'Fictional rechecked source',checked:true,note:'Rechecked same physical identity in QA; original source retained.'},machine);assert.equal(positionAchievements(await f.work('am')).find(c=>c.id==='shared-learning').state,'review-needed');
 mw=await f.work('manager');rendered=render('manager-same-machine-current-record-recheck',OperationalLearningCard,{r:mw.records.find(r=>r.id===reportRecord.id),w:mw,send:uiSend(f,'manager'),onOpen(){}});assert.match(rendered.html,/same machine’s record changed/);await submit(formFor(rendered,'learningcase.review'),'','Rechecked current same-machine record and the saved verified outcome',{verdict:'supported',evidence:'Current same machine record and independently verified linked task checked again',causeStatus:'not-established',assetId:updatedMachine.recordId,assetRevision:String(updatedMachine.revision),confirmed:'on'});reportRecord=f.record(reportRecord);assert.equal(reportRecord.data.asset.revision,updatedMachine.revision);assert.ok(reportRecord.data.versions.some(v=>v.facts.asset?.revision===machine.revision));const ownRechecked=await f.work('am');assert.equal(positionAchievements(ownRechecked).find(c=>c.id==='shared-learning').state,'earned');assert.equal(positionAchievements(ownRechecked).find(c=>c.id==='shared-learning').earnedAt,originalEarnedAt);f.reopen();
 w=await f.work('peer');const publicCase=w.records.find(r=>r.id===reportRecord.id);assert.ok(publicCase);assert.equal(publicCase.data.readSourceState,'current');assert.ok(!w.records.some(r=>r.id===task.recordId));rendered=render('peer-reviewed-lesson-private-source',OperationalLearningCard,{r:publicCase,w,send:uiSend(f,'peer'),onOpen(){}});assert.match(rendered.html,/Linked evidence matches its saved version/);assert.match(rendered.html,/cause has not been established/);assert.doesNotMatch(rendered.html,/PRIVATE_LINKED_TASK_DETAIL|Open linked work|Save independent review/);assert.equal(rendered.forms.length,0);mark('Independent operational review automatically earns own lesson progress; reviewed facts reach same-department peer without private linked task body or review authority');
 w=await f.work('am');rendered=render('reporter-withdraw-reviewed-lesson',OperationalLearningCard,{r:w.records.find(r=>r.id===reportRecord.id),w,send:uiSend(f,'am'),onOpen(){}});await submit(formFor(rendered,'learningcase.withdraw'),'','Historical outcome no longer useful',{confirmed:'on'});f.reopen();assert.equal(f.record(reportRecord).data.status,'withdrawn');assert.ok(f.record(reportRecord).data.versions.length>=3);assert.ok(!(await f.work('peer')).records.some(r=>r.id===reportRecord.id));mark('Actual withdrawal removes peer sharing while dated report and review versions remain retained');
});

test('Progress comes from checked saved work, preserves truthful evidence limits, survives reopening, and invalidates changed source',async t=>{
 const f=await fixture(t,'growth-achievement-ui.sqlite');let task=await f.command('manager','task.create',{ownerId:'server',area:'FOH',title:'Fictional reviewed issue',detail:'Only a recorded application check, not physical work proof.',kind:'issue',due:'2026-10-16T04:00:00Z'});
 let w=await f.work('server'),cards=positionAchievements(w);assert.ok(cards.length>0);assert.ok(cards.every(c=>c.state!=='earned'));let rendered=render('server-progress-opportunities',PositionAchievements,{w,send:uiSend(f,'server'),onOpen(){}});assert.match(rendered.html,/Your next opportunity/);assert.match(rendered.html,/does not change your pay, permissions/);
 assert.ok(!rendered.buttons.some(b=>b.children==='Record checked progress'),'No earning action exists for unchecked opportunities');
 let ordinary=await f.command('manager','task.create',{ownerId:'server',area:'FOH',title:'Fictional ordinary side work',detail:'Recorded independent work check.',kind:'task',due:'2026-10-16T04:00:00Z'});ordinary=await f.command('server','task.transition',{step:'ready',note:'Ordinary work reported ready.'},ordinary);await f.command('manager','task.transition',{step:'verify',note:'Independent ordinary work check.'},ordinary);
 task=await f.command('server','task.transition',{step:'ready',note:'Fictional first report.'},task);task=await f.command('manager','task.transition',{step:'fix',note:'Correction needed.'},task);task=await f.command('server','task.transition',{step:'ready',note:'Corrected result reported.'},task);task=await f.command('manager','task.transition',{step:'verify',note:'Independent corrected result checked.'},task);
 w=await f.work('server');cards=positionAchievements(w);assert.equal(cards.find(c=>c.id==='checked-work').state,'earned');assert.equal(cards.find(c=>c.id==='problem-solver').state,'earned');assert.ok(cards.find(c=>c.id==='problem-solver').sourceRefs.every(s=>s.id===task.recordId));rendered=render('server-verified-progress',PositionAchievements,{w,send:uiSend(f,'server'),onOpen(){}});assert.match(rendered.html,/Verified progress/);assert.match(rendered.html,/does not independently observe physical work or POS accuracy/);assert.match(rendered.html,/Open evidence/);f.reopen();assert.equal(positionAchievements(await f.work('server')).find(c=>c.id==='problem-solver').state,'earned');assert.ok(!(await f.work('manager')).records.some(r=>r.kind==='achievement'&&r.ownerId==='server'));mark('Unchecked work has no earning action; independent correction review automatically earns own progress without a refresh tap, survives database reopening and stays private');
 // An adversarial current-source deletion, separate from normal work commands,
 // checks the renderer against unavailable proof without inventing completion.
 f.sqlite().prepare('DELETE FROM records WHERE id=?').run(task.recordId);w=await f.work('server');cards=positionAchievements(w);assert.equal(cards.find(c=>c.id==='problem-solver').state,'review-needed');assert.ok(cards.find(c=>c.id==='problem-solver').earnedAt);rendered=render('server-progress-source-unavailable',PositionAchievements,{w,send:uiSend(f,'server'),onOpen(){}});assert.match(rendered.html,/Evidence needs review/);assert.match(rendered.html,/Previously recorded/);mark('Deleted source prevents current earned presentation while retaining historical achievement date',{boundary:'Adversarial source deletion fixture, not a normal physical-work action'});
});

test('All documented restaurant positions have readable own progress and a lesson entry; actual employee and role-home mounts include Dish',()=>{
 const files=['berts-foh-profiles.json','berts-boh-profiles.json','rudds-profiles.json','papas-profiles.json','management-profiles.json','commissary-profiles.json'].map(name=>path.join('evidence/all-position-week',name)).filter(file=>fs.existsSync(file));const profiles=files.flatMap(file=>JSON.parse(fs.readFileSync(file,'utf8')));assert.equal(profiles.length,42);const seen=[];
 for(const profile of profiles){const me={id:'qa-'+profile.id,locationId:profile.restaurant,name:'Fictional employee',area:profile.area,position:profile.position,capabilities:[],qualifications:[profile.position]},w={location:{id:profile.restaurant,name:'Fictional '+profile.restaurant,timezone:'America/New_York',revision:1},me,members:[me],records:[]};const cards=positionAchievements(w);assert.ok(cards.length>0,profile.id);assert.ok(cards.every(c=>c.state==='opportunity'),profile.id);const html=render('position-'+profile.id,OperationalLearningHome,{w,onOpen(){},onShare(){}}).html;assert.match(html,/Share or read a shift lesson/);assert.match(html,/Private conversations stay private/);seen.push({id:profile.id,position:profile.position,restaurant:profile.restaurant,opportunities:cards.length});if(profile.position==='Dishwasher'){const day=render('dish-real-my-day-mount',MyDay,{w,now,onOpen(){},onTraining(){},onSchedule(){},onDuties(){},onAsk(){},onStart(){}}).html;assert.match(day,/Your assignments/);assert.match(day,/aria-label="Your day views"/);assert.match(day,/aria-pressed="true"[^>]*>Today/);assert.doesNotMatch(day,/Your work, moving forward|A useful lesson from your shift/);}}
 const shell=fs.readFileSync('app/team/workspace.tsx','utf8');assert.match(shell,/tab==='My day'&&\(personal\|\|dish\)&&<MyDay/);assert.match(shell,/dish\?\['Home','Schedule','Inbox','JMAX'\]/);assert.match(shell,/tab==='Shift lessons'.*<OperationalLearning/);assert.match(shell,/tab==='Your progress'.*<PositionAchievements/);assert.match(shell,/tab==='Role home'\|\|tab==='Operations home'\)&&<PositionAchievements/);fs.writeFileSync(path.join(evidence,'all-position-ui-coverage.json'),JSON.stringify(seen,null,2)+'\n');mark('Every documented profile has usable own opportunities and explicit lesson entry, with actual MyDay and role-home mounts and normal Dish Home navigation',{profiles:seen.length,boundary:'React SSR plus exact mount/source checks, not full browser navigation'});
});

