import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const runtime=process.env.JMAX_ACHIEVEMENT_REVIEW_RUNTIME??'.hour-achievement-review-runtime/shared';
const {positionAchievements,synchronizePositionAchievements,achievementReader,achievementView,applyPositionAchievements}=await import('../'+runtime+'/position-achievements.mjs');
const {applyOperationalLearning,operationalLearningReader,operationalLearningSourceState}=await import('../'+runtime+'/operational-learning.mjs');
const receipts=[];const times=['2026-10-08T12:00:00Z','2026-10-08T12:10:00Z','2026-10-08T12:20:00Z'];
const history=(actorId,action,index=1)=>({actorId,action,at:times[index],note:'Fictional saved evidence'});
function fixture(position='Server',area='FOH'){
 const worker={id:'worker',name:'Worker',locationId:'berts',area,position,capabilities:[],qualifications:['Original qualification']};
 const manager={id:'manager',name:'Manager',locationId:'berts',area,position:'General manager',capabilities:['location.manage','tasks.manage','people.manage','close.confirm'],qualifications:[]};
 return {location:{id:'berts',revision:1,timezone:'America/New_York'},me:worker,members:[worker,manager,{...worker,id:'incoming',name:'Incoming'},{...worker,id:'peer',name:'Peer'}],records:[]};
}
const record=(kind,id,data,extra={})=>({id,kind,locationId:'berts',ownerId:'worker',area:'FOH',revision:1,updatedAt:times[2],data,...extra});
const checkedTask=(extra={},data={})=>record('task','checked-task',{title:'Checked assigned work',detail:'Actual submitted work',kind:'task',phase:'closed',due:times[2],history:[history('worker','ready',0),history('manager','verify',1)],...data},extra);
const card=(w,id)=>positionAchievements(w).find(r=>r.id===id);
const merge=(w,changed)=>{const ids=new Set(changed.map(r=>r.id));w.records=[...w.records.filter(r=>!ids.has(r.id)),...changed];};
test('readiness, self-verification and phase-only records do not earn achievements',()=>{
 for(const data of [{phase:'verification'},{history:[history('worker','ready',0),history('worker','verify',1)]},{history:[]}]){const w=fixture();w.records=[checkedTask({},data)];assert.equal(card(w,'checked-work').state,'opportunity');assert.deepEqual(synchronizePositionAchievements(w,w.records,times[2]),[]);}
 receipts.push({case:'No self or phase-only award',passed:true});
});
test('one verified event stays one milestone through refresh and harmless revalidation without changing clearance',()=>{
 const w=fixture();w.records=[checkedTask()];const qualifications=structuredClone(w.members.map(m=>m.qualifications));let id=0;const changes=synchronizePositionAchievements(w,w.records,times[2],()=>`earned-${++id}`);assert.equal(changes.filter(r=>r.kind==='achievement'&&r.data.milestoneId==='checked-work').length,1);merge(w,changes);const earned=card(w,'checked-work');assert.equal(earned.state,'earned');assert.deepEqual(synchronizePositionAchievements(w,[w.records.find(r=>r.id==='checked-task')],times[2]),[]);
 const revised={...w.records.find(r=>r.id==='checked-task'),revision:2};merge(w,[revised]);assert.equal(card(w,'checked-work').state,'review-needed');const revalidated=synchronizePositionAchievements(w,[revised],'2026-10-09T12:00:00Z');merge(w,revalidated);assert.equal(card(w,'checked-work').state,'earned');assert.equal(card(w,'checked-work').earnedAt,earned.earnedAt);assert.equal(w.records.filter(r=>r.kind==='achievement'&&r.data.milestoneId==='checked-work').length,1);assert.deepEqual(w.members.map(m=>m.qualifications),qualifications);receipts.push({case:'Idempotent milestone and clearance unchanged',passed:true});
});
test('withdrawn work and a reassigned prior outcome lose current credit while history remains',()=>{
 const w=fixture();w.records=[checkedTask()];merge(w,synchronizePositionAchievements(w,w.records,times[2],()=> 'original-achievement'));const saved=w.records.find(r=>r.kind==='achievement'),earnedAt=saved.data.earnedAt;
 const withdrawn={...w.records.find(r=>r.kind==='task'),revision:2,data:{...w.records.find(r=>r.kind==='task').data,phase:'correction'}};merge(w,[withdrawn]);assert.equal(achievementView(saved,w).data.status,'review-needed');merge(w,synchronizePositionAchievements(w,[withdrawn],'2026-10-09T12:00:00Z'));assert.equal(w.records.find(r=>r.kind==='achievement').data.earnedAt,earnedAt);assert.ok(w.records.find(r=>r.kind==='achievement').data.history.length>1);
 const reassigned=checkedTask({ownerId:'peer',revision:3},{history:[history('worker','ready',0),history('manager','verify',1),history('manager','reassigned',2)]});merge(w,[reassigned]);assert.equal(card(w,'checked-work').state,'review-needed');const peer={...w,me:w.members.find(m=>m.id==='peer')};assert.equal(card(peer,'checked-work').state,'opportunity');receipts.push({case:'Withdrawn and reassigned evidence not current',passed:true});
});
test('goal Ready does not replace independent outcome review and changed approved instructions invalidate it',()=>{
 const w=fixture(),guide=record('standard','guide',{title:'Approved guide',status:'approved',position:'Server',criteria:['Observe agreed practice']},{ownerId:'manager'});
 const goal=record('goal','goal',{title:'Service practice',definition:'Observed service outcome',type:'development',managerId:'manager',due:times[2],standardId:'guide',standardRevision:1,phase:'verification',history:[history('worker','ready',0)]});w.records=[guide,goal];assert.equal(card(w,'learning-step').state,'opportunity');goal.data.phase='closed';goal.data.history.push(history('worker','verify',1));assert.equal(card(w,'learning-step').state,'opportunity');goal.data.history.push(history('manager','verify',2));assert.equal(card(w,'learning-step').state,'ready');merge(w,synchronizePositionAchievements(w,[goal],times[2],()=> 'learning-award'));merge(w,[{...guide,revision:2,data:{...guide.data,status:'retired'}}]);assert.equal(card(w,'learning-step').state,'review-needed');assert.equal(goal.data.phase,'closed');receipts.push({case:'Goal review remains independent and versioned',passed:true});
});
test('retired or revised station definition cannot remain a current assessment achievement',()=>{
 const w=fixture(),station=record('station','station',{title:'Service practice',status:'active',definitionRevision:1,levels:[{value:1,label:'Reviewed practice'}]},{ownerId:'manager'});
 const assessment=record('proficiency','assessment',{stationId:'station',stationRevision:1,level:1,evidence:'Independent fictional observed practice',history:[history('manager','manager-assessed',1)]});
 w.records=[station,assessment];assert.equal(card(w,'station-builder').state,'ready');merge(w,synchronizePositionAchievements(w,[assessment],times[2],()=> 'station-award'));const original=w.records.find(r=>r.kind==='achievement'),clearance=structuredClone(w.members);
 for(const data of [{...station.data,status:'archived'},{...station.data,definitionRevision:2}]){const changed={...station,revision:2,data};merge(w,[changed]);assert.equal(card(w,'station-builder').state,'review-needed');const pending=synchronizePositionAchievements(w,[changed],times[2]);merge(w,pending);assert.equal(w.records.find(r=>r.kind==='achievement').data.status,'review-needed');assert.equal(w.records.find(r=>r.kind==='achievement').data.earnedAt,original.data.earnedAt);assert.deepEqual(w.members,clearance);}
 receipts.push({case:'Retired station and changed definition invalidate current assessment credit',passed:true});
});

test('restaurant, person, department and schedule-only boundaries prevent personal achievement exposure',()=>{
 const w=fixture();w.records=[checkedTask({locationId:'rudds'}),checkedTask({id:'peer-task',ownerId:'peer'}),checkedTask({id:'other-area-task',area:'BOH'})];assert.equal(card(w,'checked-work').state,'opportunity');const a=record('achievement','private-award',{milestoneId:'checked-work',ruleVersion:1,title:'Private',earnedAt:times[2],sourceRefs:[],history:[],status:'earned'});assert.equal(achievementReader(a,w.me),true);assert.equal(achievementReader(a,w.members.find(m=>m.id==='peer')),false);assert.equal(achievementReader(a,w.members.find(m=>m.id==='manager')),false);assert.equal(achievementReader({...a,locationId:'rudds'},w.me),false);assert.deepEqual(positionAchievements({...w,me:{...w.me,scheduleOnly:true}}),[]);receipts.push({case:'Private local achievement boundaries',passed:true});
});
test('refresh cannot accept a supplied employee, proof, score or record identity',()=>{
 const w=fixture();w.records=[checkedTask()];const before=JSON.stringify(w);let writes=0;
 for(const [input,recordId] of [[{ownerId:'peer'},undefined],[{score:99},undefined],[{sourceRefs:[{id:'fake-proof'}]},undefined],[{},'foreign-award']])assert.throws(()=>applyPositionAchievements({w,me:w.me,input,command:{action:'achievement.refresh',recordId},at:times[2],save:()=>{writes++;},create:()=>{writes++;}}));
 assert.equal(writes,0);assert.equal(JSON.stringify(w),before);receipts.push({case:'No client supplied award authority',passed:true});
});
test('private corrections and ordinary recognition are not converted into success awards',()=>{
 const w=fixture(),guide=record('standard','guide',{title:'Approved guide',status:'approved',position:'Server',criteria:['Practice']},{ownerId:'manager'});
 const correction=record('goal','required-correction',{title:'Private coaching',definition:'Improve supported practice',type:'required-correction',phase:'closed',standardId:'guide',standardRevision:1,managerId:'manager',history:[history('worker','ready',0),history('manager','verify',1)]});
 const thankYou=record('recognition','thank-you',{title:'Named thanks',status:'published',recipientId:'worker',publication:{by:'manager',at:times[2]},history:[]},{ownerId:'peer'});w.records=[guide,correction,thankYou];assert.equal(card(w,'learning-step').state,'opportunity');assert.deepEqual(synchronizePositionAchievements(w,w.records,times[2]),[]);assert.equal(JSON.stringify(positionAchievements(w)).includes('Private coaching'),false);receipts.push({case:'Corrections and board submissions remain distinct',passed:true});
});
test('Dish clean-handoff rejects stale stored receipt when actual incoming owner or forward link changed',()=>{
 const w=fixture('Dishwasher','BOH'),source=checkedTask({id:'AM',area:'BOH'},{dishCheckout:{shift:'AM',cycleId:'cycle',businessDate:'2026-10-08',participantIds:['worker','incoming','peer']},dishHandoffs:['child'],dishHandoffAcceptances:[{handoffId:'child',acceptedBy:'incoming',acceptedAt:times[2]}]});
 const child=record('task','child',{title:'Private PM work',detail:'PM_PRIVATE_BODY',kind:'task',phase:'open',due:times[2],history:[],dishHandoff:{sourceId:'AM',cycleId:'cycle',businessDate:'2026-10-08',acceptedBy:'incoming',acceptedAt:times[2]}},{ownerId:'incoming',area:'BOH'});w.records=[source,child];assert.equal(card(w,'clean-handoff').state,'ready');
 for(const changed of [{...child,ownerId:'peer'},undefined]){w.records=[source,...(changed?[changed]:[])];assert.equal(card(w,'clean-handoff').state,'opportunity','Persisted AM receipt alone is not current child acceptance');}
 w.records=[{...source,data:{...source.data,dishHandoffReceiptView:true,dishHandoffPendingIds:['orphan']}},child];assert.equal(card(w,'clean-handoff').state,'opportunity','Unresolved outgoing identity must not receive clean-handoff credit');receipts.push({case:'Dish acceptance remains actual and current',passed:true});
});

function reportFixture(){const w=fixture(),source=checkedTask(),report=record('learningcase','report',{title:'Observed station issue',symptom:'Fictional equipment symptom',actionsTaken:'Reported actions only',observedResult:'Reported outcome only',uncertainty:'Cause not established',remainingWork:'Request review',source:{id:source.id,revision:1,kind:'task',title:source.data.title},status:'reported',review:null,versions:[],history:[]});w.records=[source,report];return {w,source,report};}
function reviewContext(w,report,me=w.members.find(m=>m.id==='manager'),input={}){const writes=[];return {writes,w,me,input:{confirmed:true,verdict:'supported',causeStatus:'not-established',cause:'',evidence:'Independent fictional checked outcome',note:'Reported history, not an approved method',...input},command:{action:'learningcase.review',recordId:report.id},at:times[2],find:()=>report,save:r=>writes.push(r),create:r=>writes.push(r),notify:()=>{},history:(action,note)=>({actorId:me.id,action,note,at:times[2]})};}
test('shared operational report needs independent review and actual checked source, not equipment identity or self report',()=>{
 const {w,source,report}=reportFixture();let c=reviewContext(w,report,w.me);assert.throws(()=>applyOperationalLearning(c));assert.equal(c.writes.length,0);
 for(const data of [{...source.data,phase:'open'},{...source.data,history:[history('worker','verify',1)]}]){w.records=[{...source,data},report];c=reviewContext(w,report);assert.throws(()=>applyOperationalLearning(c));assert.equal(c.writes.length,0);}
 w.records=[source,report];c=reviewContext(w,report);applyOperationalLearning(c);const reviewed=c.writes[0];assert.equal(reviewed.data.review.causeStatus,'not-established');assert.equal(reviewed.data.review.cause,'');assert.equal(reviewed.data.status,'reviewed');w.records=[source,reviewed];assert.equal(card(w,'shared-learning').state,'ready');assert.deepEqual(w.me.qualifications,['Original qualification']);assert.equal(w.records.some(r=>r.kind==='standard'),false,'A reported lesson never creates an approved procedure');receipts.push({case:'Shared lesson review is independent and not method approval',passed:true});
});
test('changed linked task or retired physical asset blocks current supported report credit',()=>{
 const {w,source,report}=reportFixture();const changed={...source,revision:2};w.records=[changed,report];assert.equal(operationalLearningSourceState(w,report),'changed');const c=reviewContext(w,report);assert.throws(()=>applyOperationalLearning(c));assert.equal(c.writes.length,0);
 const asset=record('equipment','machine',{title:'Fictional machine',assetTag:'LOCAL-1',status:'retired'},{ownerId:'manager'});report.data.asset={id:asset.id,revision:1,title:asset.data.title,assetTag:asset.data.assetTag};report.data.status='reviewed';report.data.review={verdict:'supported',by:'manager',at:times[2],evidence:'Reviewed fictional result',note:'Not a method',causeStatus:'not-established',cause:''};w.records=[source,asset,report];assert.equal(operationalLearningSourceState(w,report),'retired');assert.equal(card(w,'shared-learning').state,'opportunity');receipts.push({case:'Task and physical asset source changes invalidate operational lesson',passed:true});
});
test('operational report is local and department-scoped; private drafts are not shared with peers',()=>{
 const {w,report}=reportFixture(),peer=w.members.find(m=>m.id==='peer');assert.equal(operationalLearningReader(report,peer),false);assert.equal(operationalLearningReader({...report,data:{...report.data,status:'reviewed'}},peer),true);assert.equal(operationalLearningReader({...report,data:{...report.data,status:'reviewed'}},{...peer,area:'BOH'}),false);assert.equal(operationalLearningReader({...report,data:{...report.data,status:'reviewed'}},{...peer,locationId:'rudds'}),false);assert.equal(operationalLearningReader(report,{...w.me,scheduleOnly:true}),false);receipts.push({case:'Shared lesson never broadens private draft or restaurant access',passed:true});
});
test.after(()=>fs.writeFileSync('evidence/hour-trial/berts-boh/achievement-independent-review.json',JSON.stringify({providerCalls:0,runtime,receipts,proof:'Independent adversarial pure-module fixtures; source-linked outcome reading, not physical verification or real operating data.'},null,2)+'\n'));
