import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import ts from 'typescript';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {openPositionDatabase} from './all-position-week-fixture.mjs';
import {handleWorkspace} from '../.sites-runtime/shared/service.mjs';

const runId=new Date().toISOString().replaceAll(':','-').replaceAll('.','-'),base=path.resolve('evidence/schedule-toast-simulations-2026-10-08/ui',runId),compiled=path.join(base,'component-runtime');fs.mkdirSync(compiled,{recursive:true});
const hash=file=>createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const runtime=()=>Object.fromEntries(fs.readdirSync('.sites-runtime/shared').filter(f=>f.endsWith('.mjs')).sort().map(f=>[f,hash('.sites-runtime/shared/'+f)]));
const frozen=runtime(),report={runId,checks:[],findings:[],execution:'Actual local authenticated handlers with fictional records, React static markup, and actual component callbacks driven by an explicit root-component state/effect adapter.',limits:['The adapter supplies hook storage and effect lifetimes. It does not prove React concurrent scheduling, DOM behavior, browser navigation or phone layout.','HTTP response envelopes are controlled local fixtures; no live Toast, Supabase or external model requests occur.','No API writes to Toast or Sling are claimed. JMAX publication is distinct from external schedule publication.'],runtimeBefore:frozen,source:{}};
let active=null;const key='__scheduleToastUi'+runId;
fs.writeFileSync(path.join(compiled,'hooks.mjs'),`import * as React from 'react'; const current=()=>globalThis[${JSON.stringify(key)}]; export const useState=(v)=>current()?.state(v)??React.useState(v); export const useRef=(v)=>current()?.ref(v)??React.useRef(v); export const useEffect=(f,d)=>current()?current().effect(f,d):React.useEffect(f,d); export const useLayoutEffect=useEffect; export const useMemo=(f,d)=>current()?current().memo(f,d):React.useMemo(f,d); export const useCallback=(f,d)=>useMemo(()=>f,d); export default React;`);
const observer=path.join(compiled,'jsx.mjs');fs.writeFileSync(observer,`import {jsx as a,jsxs as b,Fragment} from 'react/jsx-runtime';export {Fragment};function collect(type,props){if(typeof type==='string'||typeof type==='function')globalThis[${JSON.stringify(key+'Props')}]?.push({type,props});}export function jsx(t,p,k){collect(t,p);return a(t,p,k)}export function jsxs(t,p,k){collect(t,p);return b(t,p,k)}`);
const visited=new Set();function compile(file){if(visited.has(file))return;visited.add(file);const target=path.join(compiled,path.relative(path.resolve('app/team'),file).replace(/\.tsx?$/,'.mjs'));let js=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;js=js.replace(/from (["'])react\/jsx-runtime\1/g,(_,q)=>`from ${q}${pathToFileURL(observer).href}${q}`).replace(/from (["'])react\1/g,(_,q)=>`from ${q}${pathToFileURL(path.join(compiled,'hooks.mjs')).href}${q}`).replace(/import ['"][^'"]+\.css['"];?/g,'').replace(/from (['"])(\.\.?\/[^'"]+)\1/g,(_,q,s)=>{const resolved=path.resolve(path.dirname(file),s);if(resolved.startsWith(path.resolve('app/shared')+path.sep))return `from ${q}${pathToFileURL(path.resolve('.sites-runtime/shared',path.relative(path.resolve('app/shared'),resolved)+'.mjs')).href}${q}`;const dependency=['.ts','.tsx'].map(ext=>resolved+ext).find(fs.existsSync);assert.ok(dependency,resolved);compile(dependency);return `from ${q}${s}.mjs${q}`;});fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,js);}
const names=['schedule-draft-editor','schedule-week','schedule-copy','schedule-transfer','toast-schedule-preview','toast-day-panel','employee-shift-week','access-setup'];for(const name of names){compile(path.resolve('app/team/'+name+'.tsx'));report.source[name]=hash('app/team/'+name+'.tsx');}
const modules=Object.fromEntries(await Promise.all(names.map(async name=>[name,await import(pathToFileURL(path.join(compiled,name+'.mjs')))])));
class Frame{
 constructor(component,props,label){this.component=component;this.props=props;this.label=label;this.cells=[];this.effects=[];this.cursor=0;this.propsSeen=[];}
 state(initial){const i=this.cursor++;if(!this.cells[i])this.cells[i]={value:typeof initial==='function'?initial():initial};return [this.cells[i].value,v=>{this.cells[i].value=typeof v==='function'?v(this.cells[i].value):v;}];}
 ref(initial){const i=this.cursor++;return this.cells[i]??=( {current:initial});}
 memo(factory,deps){const i=this.cursor++,old=this.cells[i];if(!old||!same(old.deps,deps))this.cells[i]={value:factory(),deps};return this.cells[i].value;}
 effect(callback,deps){const i=this.cursor++,old=this.cells[i];if(!old||!same(old.deps,deps)){this.effects.push(()=>{old?.cleanup?.();this.cells[i]={deps,cleanup:callback()};});}}
 render(props=this.props){this.props=props;this.cursor=0;globalThis[key]=this;globalThis[key+'Props']=[];let element;try{element=this.component(props);}finally{delete globalThis[key];}this.html=renderToStaticMarkup(element);this.propsSeen=globalThis[key+'Props'];delete globalThis[key+'Props'];fs.writeFileSync(path.join(base,this.label+'.html'),this.html);return this;}
 effectsNow(){const list=this.effects.splice(0);for(const effect of list)effect();}
 button(label){const entry=this.propsSeen.find(x=>x.type==='button'&&text(x.props.children)===label);assert.ok(entry,'Missing '+label);return entry.props;}
 field(type,predicate){const entry=this.propsSeen.find(x=>x.type===type&&predicate(x.props));assert.ok(entry,'Missing '+type);return entry.props;}
 form(){return this.field('form',()=>true);}
 unmount(){for(const cell of this.cells)cell?.cleanup?.();}
}
const same=(a,b)=>Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i]));
const text=value=>typeof value==='string'||typeof value==='number'?String(value):Array.isArray(value)?value.map(text).join(''):React.isValidElement(value)?text(value.props.children):'';
const flush=async()=>{for(let i=0;i<6;i++)await new Promise(resolve=>setImmediate(resolve));};
const mark=(label,details={})=>report.checks.push({label,status:'passed',...details});
async function submit(frame,fields={}){const previous=FormData;try{globalThis.FormData=class{get(k){return fields[k]??null;}};await frame.form().onSubmit({preventDefault(){},currentTarget:{}});await flush();}finally{globalThis.FormData=previous;}}
const member=(id,position='Server',caps=[],restaurant='berts')=>({id,locationId:restaurant,name:'Fictional '+id,position,area:'FOH',capabilities:caps,qualifications:[position]});
const basic=restaurant=>{const me=member('manager','General manager',['location.manage','schedule.manage','schedule.publish','schedule.change','tasks.manage','close.confirm'],restaurant);return {location:{id:restaurant,name:'Fictional '+restaurant,timezone:'America/New_York',revision:1,weekStartsOn:1},me,members:[me,member('one','Server',[],restaurant),member('two','Server',[],restaurant)],records:[]};};
async function fixture(t){const file=path.join(base,'schedule-callback.sqlite');let store=openPositionDatabase(file);t.after(()=>store.close());for(const name of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())store.sqlite.exec(fs.readFileSync('drizzle/'+name,'utf8').replaceAll('--> statement-breakpoint',''));for(const loc of ['berts','rudds']){store.sqlite.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').run(loc,'Fictional '+loc,'America/New_York');for(const person of basic(loc).members)store.sqlite.prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').run(loc==='berts'?person.id:loc+'-'+person.id,loc+'-'+person.id+'@example.test',loc+'-'+person.id+'-identity',loc,person.name,person.area,person.position,JSON.stringify(person.capabilities),JSON.stringify(person.qualifications));}const raw=async(actor,action,input={},record)=>{const request=new Request('https://schedule-ui.example/api/workspace?locationId=berts',{headers:{'oai-authenticated-user-id':'berts-'+actor+'-identity','oai-authenticated-user-email':'berts-'+actor+'@example.test',Origin:'https://schedule-ui.example','Content-Type':'application/json'},...(action?{method:'POST',body:JSON.stringify({locationId:'berts',requestId:crypto.randomUUID(),action,input,...(record?{recordId:record.id??record.recordId,expectedRevision:record.revision}:{})})}:{})});const response=await handleWorkspace(request,store.db);return {status:response.status,data:await response.json()};};const command=async(...args)=>{const result=await raw(...args);assert.equal(result.status,200,JSON.stringify(result.data));return result.data;};const view=actor=>command(actor),record=id=>{const r=store.sqlite.prepare('SELECT * FROM records WHERE id=?').get(id.id??id.recordId??id);return {...r,locationId:r.location_id,ownerId:r.owner_id,data:JSON.parse(r.data)};};const reopen=()=>{store.close();store=openPositionDatabase(file);};return {command,raw,view,record,reopen};}
test.after(()=>{report.runtimeAfter=runtime();assert.deepEqual(report.runtimeAfter,frozen);report.runtimeUnchanged=true;report.expectedChecks=20;report.status=report.checks.length!==20?'incomplete or failed':report.findings.length?'passed checks with reported UI gaps':'passed';fs.writeFileSync(path.join(base,'summary.json'),JSON.stringify(report,null,2)+'\n');});

test('actual draft edit, publication, copy callbacks retain review gates and publish employee notices',async t=>{
 const f=await fixture(t),draft=await f.command('manager','shift.save',{personId:'one',position:'Server',start:'2026-10-12T16:00:00Z',end:'2026-10-13T00:00:00Z'});let w=await f.view('manager'),saved=w.records.find(r=>r.id===draft.recordId),closed=0,lastSend=null,failNextAction='shift.save-batch';
 const send=async(action,input,record)=>{lastSend={action,input};if(action===failNextAction){failNextAction='';return false;}const result=await f.raw('manager',action,input,record);if(result.status!==200)return false;w=await f.view('manager');return true;};
 const editor=new Frame(modules['schedule-draft-editor'].ScheduleDraftEditor,{w,weekStart:'2026-10-12',drafts:[saved],send,busy:false,onClose:()=>closed++},'draft-editor');editor.render();editor.button('Select up to 100 drafts').onClick();editor.render();editor.button('Edit 1 selected drafts').onClick();editor.render();editor.field('input',p=>p.type==='time'&&p.value==='12:00').onChange({target:{value:'13:00'}});editor.render();await submit(editor);editor.render();assert.match(editor.html,/Before:|After:/);assert.match(editor.html,/1:00 PM/);await submit(editor,{note:'Explicit fictional manager draft edit',confirmed:'on'});editor.render();assert.equal(closed,0);assert.equal(f.record(draft).data.start,'2026-10-12T16:00:00.000Z');assert.ok(editor.button('Save selected drafts'));mark('Failed draft save remains in review, does not close editor or change durable assignment; exact form retry remains possible');await submit(editor,{note:'Explicit fictional manager draft edit',confirmed:'on'});assert.equal(closed,1);assert.equal(lastSend.action,'shift.save-batch');assert.equal(f.record(draft).data.start,'2026-10-12T17:00:00.000Z');assert.equal(f.record(draft).data.published,false);assert.ok(!(await f.view('one')).records.some(r=>r.id===draft.recordId));mark('Draft selection/edit/review actual callbacks save unpublished changes; employee does not see draft');
 const staleEditor=new Frame(modules['schedule-draft-editor'].ScheduleDraftEditor,{...editor.props,w,drafts:w.records.filter(r=>r.kind==='shift')},'stale-editor');staleEditor.render();staleEditor.button('Select up to 100 drafts').onClick();staleEditor.render();const changed=await f.command('manager','shift.save',{personId:'one',position:'Server',start:'2026-10-12T18:00:00Z',end:'2026-10-13T00:00:00Z',note:'Another editor changes the draft'},f.record(draft));w=await f.view('manager');staleEditor.render({...staleEditor.props,w});assert.match(staleEditor.html,/selected draft changed/);assert.equal(staleEditor.button('Edit 1 selected drafts').disabled,true);mark('Concurrent draft revision displays stale warning and disables edit review');
 const weekProps={w,now:'2026-10-08T12:00:00Z',start:'2026-10-12',setStart(){},onRequests(){},onAttendance(){},onHistory(){},onAdd(){},onStaffing(){},onCover(){},onOpen(){},send,busy:false,onAskWeek(){},onViewChange(){}};
 const week=new Frame(modules['schedule-week'].ScheduleWeek,weekProps,'publication');week.render();week.button('Select eligible drafts').onClick();week.render();week.button('Review 1 selected drafts').onClick();week.render();assert.match(week.html,/No closing work assigned/);assert.equal(week.button('Publish selected shifts').disabled,false);failNextAction='shift.publish-batch';await submit(week,{note:'Reviewed exact fictional shift and responsibilities',confirmed:'on'});week.render();assert.equal(f.record(changed).data.published,false);assert.ok(week.button('Publish selected shifts'));mark('Failed publication stays in exact-draft review and sends no premature employee schedule');await submit(week,{note:'Reviewed exact fictional shift and responsibilities',confirmed:'on'});assert.equal(lastSend.action,'shift.publish-batch');assert.equal(f.record(changed).data.published,true);const employee=await f.view('one');assert.ok(employee.records.some(r=>r.id===draft.recordId));assert.ok(employee.records.some(r=>r.kind==='message'&&r.data.title==='Shift published'&&r.data.recipients.includes('one')));mark('Exact saved-draft publication callback publishes the shift and creates actual employee Inbox notification');
 w=await f.view('manager');let created='';const copy=new Frame(modules['schedule-copy'].ScheduleCopy,{w,sourceWeek:'2026-10-12',send,busy:false,onClose(){},onCreated:date=>created=date},'copy-week');copy.render();copy.button('Select up to 100 source shifts').onClick();copy.render();copy.button('Review new week').onClick();copy.render();assert.match(copy.html,/Closing checks start over|stay unpublished/);failNextAction='shift.copy-week';await submit(copy,{note:'New dates and responsibilities reviewed',confirmed:'on'});copy.render();assert.equal(created,'');assert.equal((await f.view('manager')).records.filter(r=>r.kind==='shift'&&r.data.copiedFrom).length,0);assert.ok(copy.button('Create unpublished week'));mark('Failed copy keeps review and destination unchanged; retry creates no duplicate before success');await submit(copy,{note:'New dates and responsibilities reviewed',confirmed:'on'});assert.equal(created,'2026-10-19');const copies=(await f.view('manager')).records.filter(r=>r.kind==='shift'&&r.data.copiedFrom);assert.equal(copies.length,1);assert.equal(copies[0].data.published,false);assert.ok(!(await f.view('one')).records.some(r=>r.id===copies[0].id));f.reopen();assert.equal(f.record(copies[0]).data.published,false);mark('Prepare another week callback makes durable unpublished drafts without carrying publication or employee notice');
});

test('Toast planned-shift comparison handles offline errors, cancelled/unmatched records and stale request scope',async()=>{
 const original=fetch,pending=[];globalThis.fetch=(url,init)=>new Promise(resolve=>pending.push({url:String(url),init,resolve}));try{const w=basic('berts'),frame=new Frame(modules['toast-schedule-preview'].ToastSchedulePreview,{w,weekStart:'2026-10-12'},'toast-planned-shifts');frame.render();frame.effectsNow();frame.button('Read Toast planned shifts').onClick();frame.render();assert.equal(frame.button('Reading Toast shifts…').disabled,true);assert.match(pending[0].url,/locationId=berts/);frame.render({...frame.props,w:basic('rudds')});frame.effectsNow();frame.button('Read Toast planned shifts').onClick();assert.equal(pending[0].init.signal.aborted,true);const snapshot={weekStart:'2026-10-12',timezone:'America/New_York',retrievedAt:'2026-10-08T14:00:00Z',shifts:[{toastShiftId:'known',toastEmployeeId:'employee',start:'2026-10-12T16:00:00Z',end:'2026-10-13T00:00:00Z',deleted:false},{toastShiftId:'unmatched',toastEmployeeId:'unknown',start:'2026-10-13T16:00:00Z',end:'2026-10-14T00:00:00Z',deleted:false},{toastShiftId:'cancelled',toastEmployeeId:'employee',start:'2026-10-14T16:00:00Z',end:'2026-10-15T00:00:00Z',deleted:true}]};pending[0].resolve(Response.json({locationId:'berts',previewOnly:true,source:'toast-labor-scheduled-shifts',snapshot,employees:[{toastEmployeeId:'employee',name:'OLD_RESTAURANT_SECRET',memberId:'old'}]}));await flush();frame.render();assert.doesNotMatch(frame.html,/OLD_RESTAURANT_SECRET/);pending[1].resolve(Response.json({error:'Fictional Toast connection unavailable'},{status:503}));await flush();frame.render();assert.match(frame.html,/Fictional Toast connection unavailable/);frame.button('Read Toast planned shifts').onClick();pending[2].resolve(Response.json({locationId:'rudds',previewOnly:true,source:'toast-labor-scheduled-shifts',snapshot,employees:[{toastEmployeeId:'employee',name:'Fictional matched employee',memberId:'current'}]}));await flush();frame.render();assert.match(frame.html,/2 planned shifts.*1 cancelled records.*1 shifts without a verified employee match/);assert.match(frame.html,/Unmatched Toast employee|does not change or publish either schedule|does not establish what appears in Sling/);assert.doesNotMatch(frame.html,/OLD_RESTAURANT_SECRET/);mark('Toast planned comparison aborts old restaurant request, recovers offline retry, separates cancellations and unmatched employee identities');frame.unmount();}finally{globalThis.fetch=original;}
});

test('Toast saved-day panel rejects wrong scope and labels counts rather than sales or payroll',async()=>{
 const original=fetch,pending=[];globalThis.fetch=(url,init)=>new Promise(resolve=>pending.push({url:String(url),init,resolve}));try{const w=basic('berts'),frame=new Frame(modules['toast-day-panel'].ToastDayPanel,{w},'toast-saved-day');frame.render();frame.effectsNow();frame.render();assert.match(frame.html,/Reading saved imports/);const date=new URL('https://local'+pending[0].url).searchParams.get('businessDate');pending[0].resolve(Response.json({locationId:'rudds',businessDate:date,connection:'connected',orders:{importedRecordCount:999},labor:{importedRecordCount:999}}));await flush();frame.render();assert.match(frame.html,/did not match this restaurant and date/);assert.doesNotMatch(frame.html,/999 imported/);frame.button('Reload saved imports').onClick();frame.render();frame.effectsNow();const feed={state:'incomplete',freshness:'stale',recordCount:null,importedRecordCount:23,checkedAt:'2026-10-08T12:00:00Z',dataThrough:'2026-10-07T22:00:00Z',paginationComplete:false,correctionsApplied:false,dayClosed:false};pending[1].resolve(Response.json({locationId:'berts',businessDate:date,connection:'connected',orders:feed,labor:{...feed,importedRecordCount:7}}));await flush();frame.render();assert.match(frame.html,/23 imported records/);assert.match(frame.html,/import counts, not sales dollars, payroll totals/);assert.doesNotMatch(frame.html,/\$23|final sales|payroll total: 7/i);assert.match(frame.html,/Saved snapshot is stale/);assert.match(frame.html,/not fully reconciled/);assert.match(frame.html,/Not all pages have been confirmed/);assert.match(frame.html,/Late corrections have not been confirmed/);assert.match(frame.html,/Final day close has not been confirmed/);mark('Saved-day callback rejects wrong scope and separately shows stale/incomplete snapshot counts, timestamp and nonfinancial disclaimer');frame.unmount();}finally{globalThis.fetch=original;}
});

test('saved-week transfer hides prior preview during a scope change without making any write',async()=>{
 const original=fetch,pending=[];globalThis.fetch=(url,init)=>new Promise(resolve=>pending.push({url:String(url),init,resolve}));try{const frame=new Frame(modules['schedule-transfer'].ScheduleTransfer,{w:basic('berts'),onChanged:async()=>{}},'saved-transfer');frame.render();frame.effectsNow();pending[0].resolve(Response.json({pending:true,sourceId:'berts-source',revision:1,weekStart:'2026-10-12',weekEnd:'2026-10-18',shifts:8,people:4,newPeople:0,minutes:1000,conflicts:[]}));await flush();frame.render();assert.match(frame.html,/8 shifts.*4 people/);frame.render({...frame.props,w:basic('rudds')});frame.effectsNow();frame.render();const oldVisible=/8 shifts.*4 people/.test(frame.html)&&frame.propsSeen.some(x=>x.type==='button'&&text(x.props.children)==='Add saved shifts'&&!x.props.disabled);assert.equal(oldVisible,false);assert.equal(pending[0].init.signal.aborted,true);assert.ok(fs.readFileSync('app/team/workspace.tsx','utf8').includes("key={w.location.id+':'+w.me.id+':'+recoveryVersion}"));mark('Transfer component independently hides old scope; actual workspace already remounts keyed restaurant/member content; no writes');frame.unmount();}finally{globalThis.fetch=original;}
});

test('employee week callbacks retain exact identity and restaurant rather than matching names',()=>{
 const w=basic('berts');w.me=w.members[1];const make=(id,ownerId,start,end,locationId='berts',published=true)=>({id,kind:'shift',locationId,ownerId,area:'FOH',revision:1,updatedAt:'2026-10-08T12:00:00Z',data:{position:'Server',start,end,published,cancelled:false,history:[]}});const selected=make('own','one','2026-10-12T16:00:00Z','2026-10-13T00:00:00Z'),sameDay=make('own-split','one','2026-10-12T12:00:00Z','2026-10-12T15:00:00Z');w.records=[selected,sameDay,make('wrong-person','two','2026-10-13T16:00:00Z','2026-10-14T00:00:00Z'),make('wrong-store','one','2026-10-14T16:00:00Z','2026-10-15T00:00:00Z','rudds')];w.members[2].name=w.me.name;let chosen=null;const frame=new Frame(modules['employee-shift-week'].EmployeeShiftWeek,{w,shift:selected,onSelect:r=>chosen=r.id,children:React.createElement('p',null,'Own assigned work')},'employee-own-week');frame.render();assert.match(frame.html,/11h<\/strong> scheduled/);assert.doesNotMatch(frame.html,/Includes drafts/);const split=frame.propsSeen.find(x=>x.type==='button'&&text(x.props.children).includes('Shift 1'));assert.ok(split);split.props.onClick();assert.equal(chosen,'own-split');const off=frame.propsSeen.find(x=>x.type==='button'&&String(x.props['aria-label']).includes('Tuesday'));off.props.onClick();frame.render();assert.match(frame.html,/No shift scheduled/);mark('Employee week excludes another person with same name and foreign restaurant; own split shift and off-day callbacks work');
});

test('transfer completion after unmount cannot navigate a later workspace; failed and conflicting envelopes allow safe reload',async()=>{
 const original=fetch,pending=[];globalThis.fetch=(url,init)=>new Promise(resolve=>pending.push({url:String(url),init,resolve}));
 try{
  const preview={pending:true,sourceId:'berts-source',revision:2,weekStart:'2026-10-12',weekEnd:'2026-10-18',shifts:8,people:4,newPeople:0,minutes:1000,conflicts:[]};let changed=[];
  const frame=new Frame(modules['schedule-transfer'].ScheduleTransfer,{w:basic('berts'),onChanged:async date=>changed.push(date)},'transfer-unmount');frame.render();frame.effectsNow();pending[0].resolve(Response.json(preview));await flush();frame.render();frame.button('Add saved shifts').onClick();frame.render();assert.equal(frame.button('Adding shifts…').disabled,true);assert.deepEqual(JSON.parse(pending[1].init.body),{locationId:'berts',sourceId:'berts-source',revision:2,confirmed:true});frame.unmount();assert.equal(pending[1].init.signal.aborted,true);pending[1].resolve(Response.json({pending:false,weekStart:'2026-10-12',shifts:8,people:4}));await flush();assert.deepEqual(changed,[]);mark('Actual Add saved shifts callback ignores completion after unmount; it cannot navigate a later restaurant workspace');
  const retry=new Frame(modules['schedule-transfer'].ScheduleTransfer,{w:basic('berts'),onChanged:async date=>changed.push(date)},'transfer-retry');retry.render();retry.effectsNow();pending[2].resolve(Response.json({...preview,conflicts:['Fictional existing assignment']}));await flush();retry.render();assert.equal(retry.button('Add saved shifts').disabled,true);retry.button('Add saved shifts').onClick();assert.equal(pending.length,3,'Disabled DOM button is not clicked by browser; direct callback still guards conflicts');
  retry.unmount();
  const error=new Frame(modules['schedule-transfer'].ScheduleTransfer,{w:basic('berts'),onChanged:async date=>changed.push(date)},'transfer-envelope');error.render();error.effectsNow();pending[3].resolve(Response.json({...preview,conflicts:'malformed'}));await flush();error.render();assert.match(error.html,/response needs review/);error.button('Reload saved week').onClick();pending[4].resolve(Response.json(preview));await flush();error.render();error.button('Add saved shifts').onClick();pending[5].resolve(Response.json({pending:false,weekStart:'2026-10-19',shifts:8,people:4}));await flush();error.render();assert.match(error.html,/result could not be confirmed/);assert.deepEqual(changed,[]);error.button('Reload saved week').onClick();pending[6].resolve(Response.json(preview));await flush();error.render();error.button('Add saved shifts').onClick();pending[7].resolve(Response.json({pending:false,weekStart:'2026-10-12'}));await flush();assert.deepEqual(changed,['2026-10-12']);mark('Malformed transfer preview and wrong-week result are refused; safe reload supports an already-transferred idempotent result');error.unmount();
 }finally{globalThis.fetch=original;}
});

test('saved-day selection hides prior snapshot immediately, rejects contradictory completion metadata, and preserves genuine zero',async()=>{
 const original=fetch,pending=[];globalThis.fetch=(url,init)=>new Promise(resolve=>pending.push({url:String(url),init,resolve}));
 try{
  const frame=new Frame(modules['toast-day-panel'].ToastDayPanel,{w:basic('berts')},'toast-day-selection');frame.render();frame.effectsNow();const firstDate=new URL('https://local'+pending[0].url).searchParams.get('businessDate'),feed={state:'available',freshness:'current',recordCount:10,importedRecordCount:10,checkedAt:'2026-10-08T13:00:00Z',dataThrough:'2026-10-08T12:59:00Z',paginationComplete:true,correctionsApplied:true,dayClosed:true};
  pending[0].resolve(Response.json({locationId:'berts',businessDate:firstDate,connection:'connected',orders:feed,labor:feed}));await flush();frame.render();assert.match(frame.html,/10 imported records/);assert.match(frame.html,/current and complete within the stated snapshot window/);frame.button('Reload saved imports').onClick();frame.render();frame.effectsNow();frame.field('input',p=>p.type==='date').onChange({target:{value:'2026-10-05'}});frame.render();assert.doesNotMatch(frame.html,/10 imported records/,'Old snapshot cannot show beside a newly selected date, even before effect cleanup');frame.effectsNow();assert.equal(pending[1].init.signal.aborted,true);pending[1].resolve(Response.json({locationId:'berts',businessDate:firstDate,connection:'connected',orders:{...feed,recordCount:999,importedRecordCount:999},labor:feed}));await flush();frame.render();assert.doesNotMatch(frame.html,/999 imported/);mark('Date change immediately hides prior snapshot and aborted late reload cannot restore the old date');
  const empty={...feed,state:'empty',recordCount:0,importedRecordCount:0,checkedAt:'2026-10-08T14:00:00Z',dataThrough:'2026-10-08T13:59:00Z'};pending[2].resolve(Response.json({locationId:'berts',businessDate:'2026-10-05',connection:'connected',orders:empty,labor:empty}));await flush();frame.render();assert.match(frame.html,/0 imported records/);assert.match(frame.html,/Verified saved import has no records/);assert.doesNotMatch(frame.html,/No saved import/);mark('Genuine verified zero remains a saved zero, distinct from a missing or failed import');
  frame.button('Reload saved imports').onClick();frame.render();frame.effectsNow();pending[3].resolve(Response.json({locationId:'berts',businessDate:'2026-10-05',connection:'connected',orders:{...feed,paginationComplete:false},labor:feed}));await flush();frame.render();assert.match(frame.html,/response did not match/);assert.doesNotMatch(frame.html,/current and complete|10 imported records/);frame.button('Reload saved imports').onClick();frame.render();frame.effectsNow();pending[4].resolve(Response.json({error:'Fictional saved import unavailable'},{status:503}));await flush();frame.render();assert.match(frame.html,/Fictional saved import unavailable/);assert.doesNotMatch(frame.html,/0 imported records|current and complete/);mark('Contradictory feed state and offline failure do not fabricate current/complete totals or substitute zero');frame.unmount();
 }finally{globalThis.fetch=original;}
});

test('rehired employee retired Toast link requires an explicit reachable checkbox and keeps current access unchanged',async()=>{
 const original=fetch,pending=[];globalThis.fetch=(url,init)=>new Promise(resolve=>pending.push({url:String(url),init,resolve}));
 try{
  const w=basic('berts'),employment={status:'active',hireDate:'2026-10-08',endedDate:null,departureReason:null,archivedAt:null},account={...member('rehired','Cook',['tasks.manage']),email:'rehired@example.test',claimed:true,active:true,revision:6,outstanding:0,responsibilities:[],employment},guid='11111111-1111-4111-8111-111111111111',person={toastEmployeeId:'new-toast-id',name:'Fictional rehired',email:account.email,archived:false,jobs:[{toastJobId:'cook-job',title:'Cook',archived:false}],issues:[]},oldPerson={...person,toastEmployeeId:'old-toast-id',archived:true},sourceAt='2026-10-08T14:00:00Z',profile={name:account.name,email:account.email,area:account.area,position:account.position,capabilities:[],qualifications:[]},review={id:'new-review',restaurantGuid:guid,employeeId:person.toastEmployeeId,sourceAt,source:person,profile,note:'Checked rehire personal identity',status:'draft',memberId:null,revision:1,updatedAt:sourceAt},oldReview={...review,id:'old-review',employeeId:oldPerson.toastEmployeeId,source:oldPerson,status:'applied',memberId:account.id},state={accounts:[account],reviews:[oldReview,review],roster:{restaurantGuid:guid,retrievedAt:sourceAt,employees:[oldPerson,person],issues:[]},rosterMismatch:false,history:[{id:'later-profile',actorId:'manager',targetId:account.id,action:'account.save',note:'Legitimate checked profile edit after rehire preserves active employment',at:'2026-10-08T13:00:00Z',employment},{id:'checked-rehire',actorId:'manager',targetId:account.id,action:'account.rehire',note:'Checked identity and reviewed return',at:'2026-10-08T12:00:00Z',employment}]};
  let changed=0;const panel=new Frame(modules['access-setup'].AccessSetupPanel,{w,onChanged:async()=>changed++},'rehire-parent');panel.render();panel.effectsNow();pending[0].resolve(Response.json(state));await flush();panel.render();const choice=panel.propsSeen.find(x=>x.type==='button'&&text(x.props.children).includes(person.name)&&text(x.props.children).includes('Continue review'));assert.ok(choice);choice.props.onClick();panel.render();const mounted=panel.propsSeen.find(x=>typeof x.type==='function'&&x.type.name==='ApplyReview');assert.ok(mounted,'New option must be mounted in existing employee setup');
  const apply=new Frame(modules['access-setup'].ApplyReview,mounted.props,'rehire-explicit-review');apply.render();assert.doesNotMatch(apply.html,/name="replaceArchivedToastLink"/);apply.field('select',()=>true).onChange({target:{value:account.id}});apply.render();assert.match(apply.html,/name="replaceArchivedToastLink"/);assert.match(apply.html,/same JMAX person, history and reviewed access/);assert.equal(apply.button('Link to this employee').disabled,true);await submit(apply,{identity:'on'});assert.equal(pending.length,1,'Unticked retirement confirmation must not submit any replacement');mark('Actual mounted ApplyReview offers retired-link checkbox only after selecting the same checked rehired employee; unticked form cannot submit');
  apply.field('input',p=>p.name==='replaceArchivedToastLink').onChange({target:{checked:true}});apply.render();assert.equal(apply.button('Link to this employee').disabled,false);await submit(apply,{identity:'on',replaceArchivedToastLink:'on'});assert.equal(pending.length,2);const sent=JSON.parse(pending[1].init.body);assert.equal(sent.action,'review.apply');assert.equal(sent.recordId,review.id);assert.deepEqual(sent.input,{note:'Checked rehire personal identity Manager confirmed the displayed identity and access.',identityConfirmed:true,clearancesConfirmed:false,replaceArchivedToastLink:true,memberId:account.id,memberRevision:6});assert.deepEqual(account.capabilities,['tasks.manage']);assert.equal(account.active,true);pending[1].resolve(Response.json({error:'This account changed. Reload before linking this employee.'},{status:409}));await flush();panel.render();assert.match(panel.html,/account changed.*Reload/);assert.match(panel.html,/Retry the same change/);assert.equal(changed,0);const retry=panel.button('Retry the same change');retry.onClick();await flush();assert.deepEqual(JSON.parse(pending[2].init.body),sent,'Conflict retries preserve request identity rather than changing access');pending[2].resolve(Response.json({error:'Refresh and review the latest account.'},{status:409}));await flush();assert.equal(account.active,true);assert.deepEqual(account.capabilities,['tasks.manage']);mark('Checked real mounted form sends explicit replacement flag/current member revision; server conflict remains visible and cannot enable/relink or change permissions optimistically');
  for(const change of [{...state,history:[]},{...state,roster:{...state.roster,employees:[{...oldPerson,archived:false},person]}},{...state,rosterMismatch:true},{...state,accounts:[{...account,active:false}]},{...state,history:[{...state.history[1],employment:{...employment,hireDate:'2026-10-07'}}]}]){const candidate=change.accounts[0],blocked=new Frame(modules['access-setup'].ApplyReview,{...mounted.props,state:change,accounts:[candidate],submit:async()=>assert.fail('Unreviewed or active old link must not be replaced')},'rehire-ineligible');blocked.render();blocked.field('select',()=>true).onChange({target:{value:account.id}});blocked.render();assert.doesNotMatch(blocked.html,/name="replaceArchivedToastLink"/);assert.equal(blocked.button('Link to this employee').disabled,true);await submit(blocked,{identity:'on',replaceArchivedToastLink:'on'});}
  mark('No replacement checkbox/action for missing rehire, current old Toast link, mismatched restaurant roster, suspended account or changed employment evidence');panel.unmount();
 }finally{globalThis.fetch=original;}
});

test('Toast default business date uses the previous local calendar day across clock changes',async()=>{
 const ActualDate=Date,originalFetch=fetch,cases=[];
 try{
  for(const [now,expected] of [['2026-03-09T04:30:00Z','2026-03-08'],['2026-11-02T05:30:00Z','2026-11-01'],['2026-01-01T05:30:00Z','2025-12-31']]){
   globalThis.Date=class extends ActualDate{constructor(...args){super(...(args.length?args:[now]));}static now(){return ActualDate.parse(now);}};
   let requested='';globalThis.fetch=async(url)=>{requested=new URL('https://local'+String(url)).searchParams.get('businessDate');return Response.json({error:'Fictional offline result; inspecting requested calendar date only.'},{status:503});};
   const frame=new Frame(modules['toast-day-panel'].ToastDayPanel,{w:basic('berts')},'toast-yesterday-'+expected);frame.render();assert.equal(frame.field('input',p=>p.type==='date').value,expected);frame.effectsNow();await flush();assert.equal(requested,expected);frame.render();assert.match(frame.html,/Fictional offline result/);frame.unmount();cases.push({at:now,restaurantTimezone:'America/New_York',selectedDate:expected,requestedDate:requested});
  }
  mark('Initial displayed and requested business dates use calendar yesterday at spring/fall midnight boundaries and year rollover',{cases});
 }finally{globalThis.Date=ActualDate;globalThis.fetch=originalFetch;}
});





