import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';import {openPositionDatabase} from './all-position-week-fixture.mjs';import {trialSourceRevision} from './ai-task-trial-fixture.mjs';
const runtime=process.env.SCHEDULE_COVERAGE_RUNTIME??'.sites-runtime/shared';
const {handleWorkspace}=await import('../'+runtime+'/service.mjs'),{scheduleReview}=await import('../'+runtime+'/schedule-review.mjs'),{employeeShiftWeek}=await import('../'+runtime+'/employee-week.mjs'),{localInstant,nextDate}=await import('../'+runtime+'/local-time.mjs');
function revision(){const global=trialSourceRevision(),hash=createHash('sha256');for(const file of fs.readdirSync(runtime).filter(f=>f.endsWith('.mjs')).sort()){hash.update(file);hash.update(fs.readFileSync(runtime+'/'+file));}return {...global,referenceGlobalRuntimeSha256:global.runtimeSha256,executedRuntime:runtime,runtimeSha256:hash.digest('hex')};}
const zone='America/New_York',base='evidence/schedule-toast-simulations-2026-10-08/coverage',run=process.env.SCHEDULE_COVERAGE_PASS??'initial',root=base+'/'+run;fs.mkdirSync(root,{recursive:true});const sourceRevision=revision(),receipts=[];
function fixture(t,loc,label){const file=`${root}/${loc}-${label}.sqlite`;assert.equal(fs.existsSync(file),false,'Preserve prior evidence; choose a fresh SCHEDULE_COVERAGE_PASS');let store=openPositionDatabase(file);const events=[],gaps=[];
 for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())store.sqlite.exec(fs.readFileSync('drizzle/'+f,'utf8').replaceAll('--> statement-breakpoint',''));
 const id=(actor,location=loc)=>location+'-'+actor;
 for(const location of ['berts','rudds','papa']){store.sqlite.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').run(location,'Fictional '+location,zone);
 for(const [actor,qual,caps,active=1,roster=0] of [['worker',['Server'],[]],['incoming',['Server'],[]],['untrained',[],[]],['disabled',['Server'],[],0],['roster',[],[],0,1],['lead',['Server'],['schedule.manage','schedule.change']],['manager',['Server'],['location.manage','schedule.manage','schedule.change','schedule.publish','people.manage','tasks.manage','close.confirm','standards.approve']]])store.sqlite.prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications,schedule_jobs,active,schedule_only) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id(actor,location),id(actor,location)+'@example.test',id(actor,location)+'-identity',location,'Fictional '+actor,'FOH',actor==='manager'?'General manager':'Server',JSON.stringify(caps),JSON.stringify(qual),JSON.stringify(['Server']),active,roster);}
 const request=(actor,body,location=loc)=>new Request('https://schedule-coverage.example/api/workspace?locationId='+location,{headers:{'oai-authenticated-user-id':id(actor)+'-identity','oai-authenticated-user-email':id(actor)+'@example.test',Origin:'https://schedule-coverage.example','Content-Type':'application/json'},...(body?{method:'POST',body:JSON.stringify(body)}:{})});
 const invoke=async(actor,action,input={},record,requestId=crypto.randomUUID())=>{const response=await handleWorkspace(request(actor,{locationId:loc,action,input,requestId,...(record?{recordId:record.recordId??record.id,expectedRevision:record.revision}:{})}),store.db);return {status:response.status,data:await response.json()};};
 const ok=async(actor,action,input={},record)=>{const result=await invoke(actor,action,input,record);events.push({actor,action,status:result.status,id:result.data.recordId,error:result.data.error});assert.equal(result.status,200,JSON.stringify(result));return result.data;};
 const snapshot=()=>JSON.stringify(Object.fromEntries(['records','audit_events','command_receipts','memberships'].map(table=>[table,store.sqlite.prepare('SELECT * FROM '+table+' ORDER BY rowid').all()])));
 const deny=async(status,actor,action,input={},record)=>{const before=snapshot(),r=await invoke(actor,action,input,record);events.push({actor,action,status:r.status,expectedStatus:status,error:r.data.error});assert.ok((Array.isArray(status)?status:[status]).includes(r.status),JSON.stringify(r));assert.equal(snapshot(),before);return r;};
 const view=async(actor='manager',location=loc)=>{const response=await handleWorkspace(request(actor,undefined,location),store.db);return {status:response.status,data:await response.json()};};
 const work=async actor=>{const r=await view(actor);assert.equal(r.status,200,JSON.stringify(r));return r.data;};
 const record=id=>{const r=store.sqlite.prepare('SELECT * FROM records WHERE id=?').get(id);return r&&{...r,id:r.id,locationId:r.location_id,ownerId:r.owner_id,updatedAt:r.updated_at,data:JSON.parse(r.data)};};
 const reopen=()=>{const before=snapshot();store.close();store=openPositionDatabase(file);assert.equal(snapshot(),before);events.push({phase:'durable-reopen',passed:true});};
 const period=(date,start='16:00',end='22:00',overnight=false)=>({start:localInstant(date,start,zone),end:localInstant(overnight?nextDate(date):date,end,zone)});
 const shift=async(person,date,start='16:00',end='22:00',overnight=false)=>{let r=await ok('manager','shift.save',{personId:id(person),position:'Server',...period(date,start,end,overnight)});r=await ok('manager','shift.publish',{},r);return r;};
 const guide=async()=>{let r=await ok('manager','standard.save',{title:'Fictional Server close',position:'Server',zone:'Fictional station',criteria:['Fictional independent check'],source:'QA fixture only; no restaurant procedure publication',version:1,verification:'manager'});return ok('manager','standard.approve',{validated:true,note:'Fictional guide reviewed'},r);};
 t.after(()=>{const finalSourceRevision=revision(),receipt={restaurant:loc,label,events,gaps,file,initialSeeds:1,operationalReseeds:0,sourceRevision,finalSourceRevision,runtimeUnchanged:sourceRevision.runtimeSha256===finalSourceRevision.runtimeSha256,proof:'Authenticated actual local handlers and durable fictional SQLite, not Toast API or physical attendance. Member access/clearance revocations are explicitly labelled fault injections.'};receipts.push(receipt);fs.writeFileSync(`${root}/${loc}-${label}.json`,JSON.stringify(receipt,null,2)+'\n');store.close();});
 return {id,ok,deny,invoke,work,view,record,reopen,period,shift,guide,events,gaps,snapshot,store:()=>store};}

for(const loc of ['berts','rudds','papa']){
 test(`${loc}: three-week coverage ownership, independent leadership and close transfer`,async t=>{const f=fixture(t,loc,'coverage'),g=await f.guide();
 for(const date of ['2026-10-26','2026-11-02','2026-11-09']){
  const s=await f.shift('worker',date);const c=await f.ok('manager','close.assign',{shiftId:s.recordId,standardId:g.recordId,managerId:f.id('manager'),due:f.record(s.recordId).data.end});
  let offer=await f.ok('worker','coverage.create',{shiftId:s.recordId,shiftRevision:s.revision,note:'PRIVATE_COVERAGE_REASON'});const incoming=await f.work('incoming'),publicOffer=incoming.records.find(r=>r.id===offer.recordId);assert.equal(publicOffer.data.eligible,true);assert.equal(publicOffer.data.note,'');assert.doesNotMatch(JSON.stringify(publicOffer),/PRIVATE_COVERAGE_REASON/);
  await f.deny([403,404],'untrained','coverage.volunteer',{},offer);await f.deny(403,'disabled','coverage.volunteer',{},offer);await f.deny(403,'roster','coverage.volunteer',{},offer);
  offer=await f.ok('incoming','coverage.volunteer',{confirmed:true},offer);assert.equal(f.record(s.recordId).ownerId,f.id('worker'),'Volunteering does not transfer the shift');await f.deny(403,'lead','coverage.approve',{personId:f.id('incoming'),confirmed:true,note:'Unassigned leader cannot approve'},offer);
  offer=await f.ok('incoming','coverage.withdraw-volunteer',{},offer);await f.deny(409,'manager','coverage.approve',{personId:f.id('incoming'),confirmed:true,note:'Withdrawn volunteer not eligible'},offer);offer=await f.ok('incoming','coverage.volunteer',{confirmed:true},offer);await f.ok('manager','coverage.approve',{personId:f.id('incoming'),confirmed:true,note:'Independent manager reviewed current duties'},offer);
  assert.equal(f.record(s.recordId).ownerId,f.id('incoming'));assert.equal(f.record(c.recordId).ownerId,f.id('incoming'));assert.equal(f.record(c.recordId).data.phase,'open');assert.equal((await f.work('worker')).records.some(r=>r.id===s.recordId),false);
  const incomingView=await f.work('incoming'),week=employeeShiftWeek(incomingView,incomingView.records.find(r=>r.id===s.recordId));assert.equal(week.minutes,360);assert.equal(week.hasDrafts,false);
  const current=f.record(s.recordId);await f.deny(400,'manager','shift.cancel',{note:'Cannot strand the unfinished close'},current);await f.deny(400,'manager','shift.release',{note:'Cannot bypass final check'},current);
  const covering=await f.shift('worker',date);await f.ok('manager','shift.cancel',{note:'No-show coverage with explicit closing transfer',closeTransfers:[{closeId:c.recordId,shiftId:covering.recordId}]},current);assert.equal(f.record(c.recordId).ownerId,f.id('worker'));assert.equal(f.record(c.recordId).data.shiftId,covering.recordId);assert.equal(f.record(s.recordId).data.cancelled,true);
  let close=await f.ok('worker','close.transition',{step:'ready',answers:[0],note:'Fictional work submitted'},f.record(c.recordId));await f.deny(403,'worker','close.transition',{step:'confirm',note:'Cannot self confirm'},close);close=await f.ok('manager','close.transition',{step:'confirm',note:'Independent fictional final check'},close);await f.ok('manager','shift.release',{note:'Checked work before release'},f.record(covering.recordId));f.reopen();
 }
 assert.equal((await f.view('worker',loc==='berts'?'rudds':'berts')).status,403);
 });

 test(`${loc}: accepted swaps recheck competing work and changed original shifts`,async t=>{const f=fixture(t,loc,'swaps');
 const s=await f.shift('worker','2026-10-27','10:00','16:00');let r=await f.ok('worker','request.create',{type:'swap',shiftId:s.recordId,replacementId:f.id('incoming'),...f.period('2026-10-27','10:00','16:00'),note:'Fictional proposal'});await f.deny(403,'worker','request.consent',{accept:true},r);r=await f.ok('incoming','request.consent',{accept:true},r);assert.equal(f.record(s.recordId).ownerId,f.id('worker'));const overlap=await f.shift('incoming','2026-10-27','10:00','12:00');await f.deny(400,'manager','request.review',{approve:true,note:'Must recheck current conflicts'},r);await f.ok('manager','shift.cancel',{note:'Remove competing assignment'},overlap);await f.ok('manager','request.review',{approve:true,note:'Rechecked current replacement'},r);assert.equal(f.record(s.recordId).ownerId,f.id('incoming'));assert.equal(employeeShiftWeek(await f.work('incoming'),f.record(s.recordId)).minutes,360);f.reopen();
 const changed=await f.shift('worker','2026-11-03','10:00','16:00');let q=await f.ok('worker','request.create',{type:'swap',shiftId:changed.recordId,replacementId:f.id('incoming'),...f.period('2026-11-03','10:00','16:00'),note:'Fictional second proposal'});q=await f.ok('incoming','request.consent',{accept:true},q);await f.ok('manager','shift.save',{personId:f.id('worker'),position:'Server',...f.period('2026-11-03','11:00','16:00'),note:'Published schedule changed after consent'},changed);await f.deny(409,'manager','request.review',{approve:true,note:'Old accepted request must not replace revised shift'},q);assert.equal(f.record(q.recordId).data.status,'accepted-by-replacement');
 const disabledSwap=await f.shift('worker','2026-11-10','10:00','16:00');let d=await f.ok('worker','request.create',{type:'swap',shiftId:disabledSwap.recordId,replacementId:f.id('incoming'),...f.period('2026-11-10','10:00','16:00'),note:'Replacement later disabled'});d=await f.ok('incoming','request.consent',{accept:true},d);f.store().sqlite.prepare('UPDATE memberships SET active=0,revision=revision+1 WHERE id=?').run(f.id('incoming'));f.events.push({phase:'fault-injected access revocation',actor:'incoming',reason:'Explicitly simulate disabled replacement after consent; no operational reseed'});await f.deny(400,'manager','request.review',{approve:true,note:'Disabled replacement cannot inherit'},d);assert.equal(f.record(disabledSwap.recordId).ownerId,f.id('worker'));f.reopen();
 });

 test(`${loc}: approved restrictions, DST folds, superseded availability and real staffing gaps`,async t=>{const f=fixture(t,loc,'availability');
 let a=await f.ok('incoming','availability.save',{title:'Fictional Monday restriction',kind:'unavailable',startDate:'2026-10-26',endDate:'2026-11-16',days:[1],startMinute:540,endMinute:780,beforeMinutes:30,afterMinutes:30});a=await f.ok('manager','availability.review',{approve:true,note:'Fictional reviewed restriction'},a);
 await f.deny(400,'manager','shift.save',{personId:f.id('incoming'),position:'Server',...f.period('2026-10-26','13:00','16:00')});await f.shift('incoming','2026-10-26','13:30','16:00');await f.deny(400,'manager','shift.save',{personId:f.id('incoming'),position:'Server',...f.period('2026-11-01','23:30','10:00',true)});
 let sunday=await f.ok('incoming','availability.save',{title:'Fictional repeated-hour restriction',kind:'unavailable',startDate:'2026-11-01',endDate:'2026-11-01',days:[0],startMinute:60,endMinute:120});sunday=await f.ok('manager','availability.review',{approve:true,note:'Both repeated local hour instances restricted'},sunday);
 for(const fold of ['earlier','later'])await f.deny(400,'manager','shift.save',{personId:f.id('incoming'),position:'Server',start:localInstant('2026-11-01','01:30',zone,fold),end:localInstant('2026-11-01','03:00',zone)});
 let replacement=await f.ok('incoming','availability.save',{title:'Fictional replacement Tuesday restriction',kind:'unavailable',startDate:'2026-10-26',endDate:'2026-11-16',days:[2],startMinute:0,endMinute:60,replacesId:a.recordId});await f.ok('manager','availability.review',{approve:true,note:'Replace Monday restriction with reviewed Tuesday window'},replacement);assert.equal(f.record(a.recordId).data.status,'superseded');await f.shift('incoming','2026-11-02','09:00','13:00');
 await f.deny(400,'incoming','availability.withdraw',{note:'No implemented withdraw command'},replacement);f.gaps.push({area:'Availability withdrawal',detail:'No employee availability.withdraw action exists. Approved terms change through a new independently reviewed replacement; own pending-request withdrawal is not simulated as implemented.'});
 const shift=await f.shift('worker','2026-11-09','16:00','22:00');let need=await f.ok('manager','staffing.save',{title:'Fictional required evening staffing',area:'FOH',position:'Server',...f.period('2026-11-09','16:00','22:00'),minimum:1,source:'QA configured headcount, not restaurant policy'});need=await f.ok('manager','staffing.approve',{confirmed:true,note:'Fictional reviewed staffing need'},need);assert.equal(scheduleReview(await f.work('manager'),'2026-11-09').publishedGapCount,0);
 const off=await f.ok('worker','request.create',{type:'time-off',...f.period('2026-11-09','16:00','22:00'),note:'PRIVATE_TIMEOFF_REASON'});await f.ok('manager','request.review',{approve:true,note:'Independently approved time off'},off);assert.equal(f.record(shift.recordId).data.cancelled,true);const review=scheduleReview(await f.work('manager'),'2026-11-09');assert.equal(review.publishedGapCount,1);assert.equal(review.staffing[0].published[0].scheduled,0);const employee=await f.work('worker');assert.equal(employeeShiftWeek(employee,employee.records.find(r=>r.id===shift.recordId)).minutes,0);assert.doesNotMatch(JSON.stringify(await f.work('incoming')),/PRIVATE_TIMEOFF_REASON/);f.reopen();assert.equal(scheduleReview(await f.work('manager'),'2026-11-09').publishedGapCount,1);await f.deny(400,'manager','shift.save',{personId:f.id('worker'),position:'Server',...f.period('2026-11-09','16:00','22:00')});
 });

 test(`${loc}: replacement time off after volunteering blocks approval and leaves original responsibility`,async t=>{const f=fixture(t,loc,'coverage-eligibility-change'),s=await f.shift('worker','2026-11-15');let offer=await f.ok('worker','coverage.create',{shiftId:s.recordId,shiftRevision:s.revision,note:''});offer=await f.ok('incoming','coverage.volunteer',{confirmed:true},offer);let off=await f.ok('incoming','request.create',{type:'time-off',...f.period('2026-11-15'),note:'PRIVATE_REPLACEMENT_TIMEOFF'});await f.ok('manager','request.review',{approve:true,note:'Replacement restriction approved after volunteering'},off);await f.deny(409,'manager','coverage.approve',{personId:f.id('incoming'),confirmed:true,note:'Eligibility must be checked again'},offer);const visible=(await f.work('incoming')).records.find(r=>r.id===offer.recordId);assert.equal(visible.data.eligible,false);assert.equal(f.record(s.recordId).ownerId,f.id('worker'));assert.equal(f.record(offer.recordId).data.status,'open');f.reopen();assert.equal(f.record(s.recordId).ownerId,f.id('worker'));});
 test(`${loc}: changed published source invalidates pending coverage and old approval cannot apply`,async t=>{const f=fixture(t,loc,'coverage-source-change'),s=await f.shift('worker','2026-11-16');let offer=await f.ok('worker','coverage.create',{shiftId:s.recordId,shiftRevision:s.revision,note:''});offer=await f.ok('incoming','coverage.volunteer',{confirmed:true},offer);const changed=await f.ok('manager','shift.save',{personId:f.id('worker'),position:'Server',...f.period('2026-11-16','17:00','22:00'),note:'Times changed after the offered version'},s);const currentOffer=f.record(offer.recordId);assert.equal(currentOffer.data.status,'invalidated');await f.deny([409,404],'manager','coverage.approve',{personId:f.id('incoming'),confirmed:true,note:'Must not approve stale offered times'},currentOffer);assert.equal(f.record(changed.recordId).ownerId,f.id('worker'));const view=await f.work('worker');assert.equal(employeeShiftWeek(view,view.records.find(r=>r.id===changed.recordId)).minutes,300);f.reopen();assert.equal(f.record(offer.recordId).data.status,'invalidated');});

 test(`${loc}: accepted swap must not bypass the replacement's attached closing clearance`,async t=>{const f=fixture(t,loc,'clearance-repro'),g=await f.guide(),s=await f.shift('worker','2026-11-12');const c=await f.ok('manager','close.assign',{shiftId:s.recordId,standardId:g.recordId,managerId:f.id('manager'),due:f.record(s.recordId).data.end});let r=await f.ok('worker','request.create',{type:'swap',shiftId:s.recordId,replacementId:f.id('untrained'),...f.period('2026-11-12'),note:'Scheduling eligibility is not closing clearance'});r=await f.ok('untrained','request.consent',{accept:true},r);const before=f.record(c.recordId),beforeState=f.snapshot(),result=await f.invoke('manager','request.review',{approve:true,note:'Replacement has scheduling job but no reviewed Server clearance'},r);f.events.push({phase:'closing-clearance-bypass-reproduction',status:result.status,closeOwnerBefore:before.ownerId,closeOwnerAfter:f.record(c.recordId).ownerId,replacementQualifications:[],replacementSchedulingJobs:['Server'],response:result.data});assert.equal(result.status,400,'Accepted swap must not transfer independently assigned closing work to a replacement without its reviewed clearance');assert.equal(f.record(c.recordId).ownerId,before.ownerId);assert.equal(f.snapshot(),beforeState,'Rejected swap must not change any saved state');
 });
 test(`${loc}: direct closing assignment requires clearance distinct from roster scheduling jobs`,async t=>{const f=fixture(t,loc,'assignment-clearance-repro'),g=await f.guide(),s=await f.shift('untrained','2026-11-13');const beforeState=f.snapshot(),result=await f.invoke('manager','close.assign',{shiftId:s.recordId,standardId:g.recordId,managerId:f.id('manager'),due:f.record(s.recordId).data.end});f.events.push({phase:'direct-close-clearance-reproduction',status:result.status,replacementQualifications:[],replacementSchedulingJobs:['Server'],response:result.data});assert.equal(result.status,400,'Scheduling permission alone cannot assign reviewed closing work');assert.equal(f.snapshot(),beforeState,'Rejected assignment must not change any saved state');});
 test(`${loc}: cancelling a shift cannot transfer its pending close to an uncleared replacement`,async t=>{const f=fixture(t,loc,'cancel-clearance-repro'),g=await f.guide(),original=await f.shift('worker','2026-11-14'),replacement=await f.shift('untrained','2026-11-14');const c=await f.ok('manager','close.assign',{shiftId:original.recordId,standardId:g.recordId,managerId:f.id('manager'),due:f.record(original.recordId).data.end});const beforeState=f.snapshot(),result=await f.invoke('manager','shift.cancel',{note:'Replacement has roster job, no closing clearance',closeTransfers:[{closeId:c.recordId,shiftId:replacement.recordId}]},original);f.events.push({phase:'cancellation-close-clearance-reproduction',status:result.status,closeOwnerAfter:f.record(c.recordId).ownerId,replacementQualifications:[],replacementSchedulingJobs:['Server'],response:result.data});assert.equal(result.status,400,'Cancellation must not transfer closing work without reviewed clearance');assert.equal(f.record(original.recordId).data.cancelled,false);assert.equal(f.snapshot(),beforeState,'Rejected cancellation must not change any saved state');});
}
test.after(()=>fs.writeFileSync(`${root}/summary.json`,JSON.stringify({sourceRevision,finalSourceRevision:revision(),receipts,tests:receipts.length,providerCalls:0,liveToastRequests:0,proof:'Actual native handlers; stored fake operations and explicit access fault injection only. Executed runtime path identifies the selected isolated or shared checkpoint; no shared runtime overwrite.'},null,2)+'\n'));
