import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createHash,randomUUID} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';

// Each run freezes current source independently. No shared test runtime changes.
const output=path.resolve('evidence/schedule-toast-simulations-2026-10-08/saved-data',randomUUID());
const runtime=process.env.JMAX_TOAST_DATA_RUNTIME?path.resolve(process.env.JMAX_TOAST_DATA_RUNTIME):path.join(output,'runtime');
fs.mkdirSync(output,{recursive:true});
if(!process.env.JMAX_TOAST_DATA_RUNTIME){fs.mkdirSync(runtime,{recursive:true});for(const name of fs.readdirSync('app/shared').filter(n=>n.endsWith('.ts'))){const src=fs.readFileSync('app/shared/'+name,'utf8'),compiled=ts.transpileModule(src,{fileName:name,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replace(/from '(\.\/[^']+)'/g,"from '$1.mjs'");fs.writeFileSync(path.join(runtime,name.replace(/\.ts$/,'.mjs')),compiled);}}
const {handleToastDay}=await import(pathToFileURL(path.join(runtime,'toast-day-service.mjs')));
const {configuredToastDayReader}=await import(pathToFileURL(path.join(runtime,'toast-supabase-reader.mjs')));
const {adaptSavedToastFinancialDay}=await import(pathToFileURL(path.join(runtime,'toast-saved-financial-adapter.mjs')));
const {aggregateToastFinancialDays}=await import(pathToFileURL(path.join(runtime,'toast-financial-day.mjs')));
const {toastSourceInstant}=await import(pathToFileURL(path.join(runtime,'toast-source-time.mjs')));
const manifests=Object.fromEntries(fs.readdirSync(runtime).filter(n=>n.endsWith('.mjs')).sort().map(n=>[n,createHash('sha256').update(fs.readFileSync(path.join(runtime,n))).digest('hex')]));
const receipts=[];
const restaurants={berts:'6e09b799-f05e-4a86-9867-511b0bb23325',rudds:'95ac8855-65c8-4a49-9d3d-d25e36351edc',papa:'ddebbf7f-b32a-4df7-b75f-9428daffd946'};
const zone='America/New_York';
function open(file){const sqlite=new DatabaseSync(file),db={prepare(sql){let values=[];return {bind(...v){values=v;return this;},async first(){return sqlite.prepare(sql).get(...values)??null;},async all(){return {results:sqlite.prepare(sql).all(...values),meta:{changes:Number(sqlite.prepare('SELECT changes() n').get().n)}};},async run(){const r=sqlite.prepare(sql).run(...values);return {results:[],meta:{changes:Number(r.changes)}};}};},async batch(statements){sqlite.exec('BEGIN');try{const r=[];for(const s of statements)r.push(await s.all());sqlite.exec('COMMIT');return r;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};db.withSession=()=>db;return {sqlite,db};}
function seed(s){for(const f of fs.readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())s.sqlite.exec(fs.readFileSync('drizzle/'+f,'utf8').replaceAll('--> statement-breakpoint',''));for(const loc of Object.keys(restaurants)){s.sqlite.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').run(loc,'Fictional '+loc,zone);for(const [who,caps] of [['gm',['location.manage']],['staff',[]]])s.sqlite.prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').run(who+'-'+loc,who+'-'+loc+'@example.test',who+'-'+loc,loc,'Fictional '+who,'FOH',who==='gm'?'General Manager':'Server',JSON.stringify(caps),'[]');s.sqlite.prepare('INSERT INTO restaurant_access(auth_user_id,kind,home_location_id) VALUES(?,?,?)').run('gm-'+loc,'restaurant',loc);}}
const request=(who,loc,date)=>new Request('https://data-stress.example/api/integrations/toast-day?'+new URLSearchParams({locationId:loc,businessDate:date}),{headers:{'oai-authenticated-user-id':who,'oai-authenticated-user-email':who+'@example.test'}});
const call=async(s,loc,date,reader,who='gm-'+loc)=>{const response=await handleToastDay(request(who,loc,date),s.db,reader);return {status:response.status,data:await response.json()};};
const scoped=(loc,date)=>({locationId:loc,businessDate:date,timezone:zone});
const mapped=(loc,date)=>({...scoped(loc,date),restaurantGuid:restaurants[loc]});
const ev={businessDayVerified:true,correctionsApplied:true,dayClosed:true,refundsReconciled:true};
function financial(loc,date,n=1){const base={toast_restaurant_guid:restaurants[loc],business_date:date,fetched_at:'2026-10-07T12:00:00Z',ingestion_metadata:{paginationComplete:true}};return {evidence:{...ev},sales:{...base,report_kind:'sales',payload:[{guid:'order-'+n,businessDate:Number(date.replaceAll('-','')),voided:false,deleted:false,excessFood:false,checks:[{guid:'check-'+n,voided:false,deleted:false,amount:100+n,appliedDiscounts:[],selections:[{guid:'selection-'+n,voided:false,deferred:true,selectionType:'NONE',price:10,appliedDiscounts:[],modifiers:[]}],appliedServiceCharges:[],payments:[{guid:'payment-'+n,refundStatus:'PARTIAL',refund:{refundBusinessDate:Number(date.replaceAll('-','')),refundAmount:2,tipRefundAmount:8}}]}]}]},labor:{...base,report_kind:'labor',payload:[{guid:'entry-'+n,businessDate:Number(date.replaceAll('-','')),deleted:false,inDate:date+'T14:00:00Z',outDate:date+'T18:00:00Z',regularHours:4,overtimeHours:0,hourlyWage:12.5}]}};}
const adapt=(loc,date,input)=>adaptSavedToastFinancialDay(input,scoped(loc,date),mapped(loc,date),Date.parse('2026-10-08T20:00:00Z'));

test('three weeks per restaurant retain saved import observations, incomplete flags, isolated access and recovery across reopened days',async()=>{
 const file=path.join(output,'saved-imports.sqlite');let s=open(file);seed(s);s.sqlite.exec('CREATE TABLE qa_saved_imports(location_id TEXT,business_date TEXT,payload TEXT,PRIMARY KEY(location_id,business_date))');const calls=[],financialDays=[];
 for(let day=0;day<21;day++){const date=new Date(Date.UTC(2026,8,14+day)).toISOString().slice(0,10);if(day){s.sqlite.close();s=open(file);}for(const [index,loc] of Object.keys(restaurants).entries()){
  const complete=day%7!==1,stale=day%7===2,missing=day%7===3,empty=day%7===4,count=empty?0:day+index+1,at=new Date(Date.now()-2000).toISOString();const feed={recordCount:count,checkedAt:at,dataThrough:stale?new Date(Date.now()-3600000).toISOString():at,paginationComplete:complete,correctionsApplied:complete,dayClosed:complete};const payload={schemaVersion:'jmax-toast-day-read.v1',...scoped(loc,date),source:{system:'toast',restaurantGuid:restaurants[loc]},orders:missing?null:feed,labor:feed};s.sqlite.prepare('INSERT INTO qa_saved_imports VALUES(?,?,?)').run(loc,date,JSON.stringify(payload));
  const reader=configuredToastDayReader({SUPABASE_URL:'https://fictional-project.supabase.co',SUPABASE_SECRET_KEY:'sb_secret_FICTIONAL_PRIVATE'},async(url,init)=>{assert.equal(url,'https://fictional-project.supabase.co/rest/v1/rpc/jmax_toast_read_day');assert.equal(init.headers.Authorization,undefined);assert.equal(init.headers.apikey,'sb_secret_FICTIONAL_PRIVATE');assert.equal(init.redirect,'error');const args=JSON.parse(init.body);assert.deepEqual(args,{p_store_id:loc,p_business_date:date});calls.push(args);return Response.json(JSON.parse(s.sqlite.prepare('SELECT payload FROM qa_saved_imports WHERE location_id=? AND business_date=?').get(loc,date).payload));});
  const r=await call(s,loc,date,reader);assert.equal(r.status,200,JSON.stringify(r));assert.equal(r.data.orders.importedRecordCount,missing?null:count);assert.equal(r.data.orders.recordCount,missing||stale||!complete?null:count);assert.equal(r.data.orders.freshness,missing?'unknown':stale?'stale':'current');assert.doesNotMatch(JSON.stringify(r),/FICTIONAL_PRIVATE|employeeReference|netSales/);const before=calls.length;assert.equal((await call(s,loc,date,reader,'staff-'+loc)).status,403);assert.equal((await call(s,loc,date,reader,'gm-'+Object.keys(restaurants)[(index+1)%3])).status,403);assert.equal(calls.length,before);
  const batches=financial(loc,date,day+1);if(missing){batches.sales=null;batches.labor=null;}else if(!complete)batches.evidence.dayClosed=false;financialDays.push(adapt(loc,date,batches).day);receipts.push({case:'durable store-day saved import',locationId:loc,date,status:r.status,countState:r.data.orders.state,freshness:r.data.orders.freshness,readCalls:1,authorizationDenials:2});
 }}
 assert.equal(s.sqlite.prepare('SELECT count(*) n FROM qa_saved_imports').get().n,63);for(const table of ['records','command_receipts','audit_events'])assert.equal(s.sqlite.prepare('SELECT count(*) n FROM '+table).get().n,0,'Read preview must not mutate operating data');s.sqlite.close();s=open(file);assert.equal(s.sqlite.prepare('SELECT count(*) n FROM qa_saved_imports').get().n,63);s.sqlite.close();const group=aggregateToastFinancialDays(financialDays);assert.equal(group.netSales.value,null);assert.equal(group.laborPercent.value,null);assert.equal(group.coverage,'incomplete');assert.throws(()=>aggregateToastFinancialDays([...financialDays,financialDays[0]]));receipts.push({case:'63-day mixed completeness prevents false group total; persisted reopen',passed:true,database:file});
});

test('transport outages, malformed responses, wrong store and retry remain unknown and never write operating records',async t=>{
 const file=path.join(output,'transport.sqlite'),s=open(file);seed(s);t.after(()=>s.sqlite.close());const loc='berts',date='2026-10-01';const at=new Date(Date.now()-1000).toISOString(),feed={recordCount:0,checkedAt:at,dataThrough:at,paginationComplete:true,correctionsApplied:true,dayClosed:true};const good={schemaVersion:'jmax-toast-day-read.v1',...scoped(loc,date),source:{system:'toast',restaurantGuid:restaurants[loc]},orders:feed,labor:feed};
 for(const [name,response] of [['forbidden',()=>new Response('PRIVATE',{status:403})],['rate limited',()=>new Response('PRIVATE',{status:429})],['invalid JSON',()=>new Response('{bad')],['wrong scope',()=>Response.json({...good,locationId:'rudds'})],['future observation',()=>Response.json({...good,orders:{...feed,checkedAt:'2999-01-01T00:00:00Z'}})],['oversized',()=>new Response('x'.repeat(64001))]]){const reader=configuredToastDayReader({SUPABASE_URL:'https://fictional-project.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'PRIVATE_FAKE'},async()=>response());const r=await call(s,loc,date,reader);assert.equal(r.status,503,name);assert.equal(r.data.orders.recordCount,null);assert.equal(r.data.connection,'unavailable');assert.doesNotMatch(JSON.stringify(r),/PRIVATE/);receipts.push({case:'saved-data failure',name,status:r.status});}
 const reader=configuredToastDayReader({SUPABASE_URL:'https://fictional-project.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'PRIVATE_FAKE'},async(_url,init)=>{assert.equal(init.headers.Authorization,'Bearer PRIVATE_FAKE');return Response.json(good);});const r=await call(s,loc,date,reader);assert.equal(r.status,200);assert.equal(r.data.orders.recordCount,0);assert.equal(r.data.orders.state,'empty');for(const table of ['records','command_receipts','audit_events'])assert.equal(s.sqlite.prepare('SELECT count(*) n FROM '+table).get().n,0);receipts.push({case:'retry verifies explicit empty instead of inventing it during outage',passed:true});
});

test('late corrections replace the selected financial snapshot; order does not change totals; mixed pay and absent days suppress ratios',()=>{
 const loc='rudds',date='2026-10-01',one=financial(loc,date),before=adapt(loc,date,one);assert.equal(before.day.netSales.value,8900);assert.equal(before.day.laborSpend.value,5000);assert.equal(before.day.workedHours.value,4);one.sales.payload[0].checks[0].payments[0].refund.refundAmount=8;const corrected=adapt(loc,date,one);assert.equal(corrected.day.netSales.value,8300);assert.equal(corrected.day.discounts.value,0);one.labor.payload[0].overtimeHours=1;const ot=adapt(loc,date,one);assert.equal(ot.day.workedHours.value,5);assert.equal(ot.day.laborSpend.value,null);assert.equal(ot.regularHourlyPayComponent.value,5000);assert.equal(aggregateToastFinancialDays([ot.day]).laborPercent.value,null);
 const day2='2026-10-02',two=financial(loc,day2,2);two.sales.payload.push({...two.sales.payload[0],guid:'deleted',deleted:true});const b=adapt(loc,day2,two).day;const forward=aggregateToastFinancialDays([corrected.day,b]),reverse=aggregateToastFinancialDays([b,corrected.day]);assert.deepEqual({...forward,restaurantDays:[...forward.restaurantDays].sort()},{...reverse,restaurantDays:[...reverse.restaurantDays].sort()});const missing=adapt(loc,'2026-10-03',{sales:null,labor:null}).day;assert.equal(aggregateToastFinancialDays([corrected.day,b,missing]).salesPerLaborHour.value,null);receipts.push({case:'selected late refund correction, real hours vs unknown OT pay, sequence independent totals, explicit missing day',passed:true});
});

test('corrupt nested item identities and unknown refund classifications cannot produce finalized financial totals',()=>{
 const loc='papa',date='2026-10-01',observations=[];for(const [name,mutate] of [['duplicate deferred item',i=>{const c=i.sales.payload[0].checks[0];c.selections.push({...c.selections[0]});}],['missing selection identity',i=>delete i.sales.payload[0].checks[0].selections[0].guid],['unknown refund status',i=>i.sales.payload[0].checks[0].payments[0].refundStatus='UNVERIFIED'],['invalid closed date',i=>i.labor.payload[0].outDate='2026-02-30T18:00:00Z']]){const i=financial(loc,date);mutate(i);const r=adapt(loc,date,i),value=name==='invalid closed date'?r.day.workedHours.value:r.day.netSales.value;receipts.push({case:'malformed financial evidence',name,value,desired:null});observations.push({name,value});}assert.deepEqual(observations,observations.map(r=>({...r,value:null})));
});

test('actual saved RPC timestamp precision is accepted without falsely finalizing the imported records',async t=>{
 const file=path.join(output,'postgres-precision.sqlite'),s=open(file);seed(s);t.after(()=>s.sqlite.close());const snapshots=JSON.parse(fs.readFileSync('evidence/schedule-toast-simulations-2026-10-08/live-saved-rpc.json','utf8')).rows;
 const results=[];for(const {store_id:loc,business_date:date,snapshot} of snapshots){const reader=configuredToastDayReader({SUPABASE_URL:'https://fictional-project.supabase.co',SUPABASE_SECRET_KEY:'sb_secret_FICTIONAL_PRIVATE'},async()=>Response.json(snapshot));const r=await call(s,loc,date,reader);results.push({locationId:loc,status:r.status});receipts.push({case:'exact read-only live RPC response replay through protected local app handler',locationId:loc,date,status:r.status,sourceObservedAt:'2026-10-08',networkReplay:false});if(r.status===200){assert.equal(r.data.orders.recordCount,null);assert.equal(r.data.orders.state,'incomplete');assert.equal(r.data.orders.importedRecordCount,snapshot.orders.recordCount);}}
 assert.deepEqual(results,Object.keys(restaurants).map(locationId=>({locationId,status:200})));
});

test('high precision source timestamps preserve strict dates and source-scope checks',()=>{
 assert.equal(toastSourceInstant('2026-10-07T10:15:03.634606+00:00'),'2026-10-07T10:15:03.634Z');
 assert.equal(toastSourceInstant('2026-10-07T06:15:03.634606-04:00'),'2026-10-07T10:15:03.634Z');
 for(const value of ['2026-02-30T10:15:03.123456Z','2026-10-07T24:15:03.123456Z','2026-10-07T10:70:03.123456Z','2026-10-07T10:15:03.123456','2026-10-07T10:15:03.1234567890Z'])assert.throws(()=>toastSourceInstant(value));
 const loc='berts',date='2026-10-01',i=financial(loc,date);i.sales.fetched_at='2026-10-07T10:15:03.914503+00:00';i.labor.fetched_at='2026-10-07T10:15:03.634606+00:00';i.labor.payload[0].outDate='2026-10-01T18:00:00.123456Z';assert.equal(adapt(loc,date,i).day.netSales.value,8900);assert.equal(adapt(loc,date,i).day.workedHours.value,4);i.sales.toast_restaurant_guid=restaurants.rudds;assert.throws(()=>adapt(loc,date,i));receipts.push({case:'source timestamp precision with impossible calendars and wrong restaurant rejected',passed:true});
});

test('an advertised partial saved-data transport cannot become a complete snapshot',async t=>{
 const file=path.join(output,'partial-transport.sqlite'),s=open(file);seed(s);t.after(()=>s.sqlite.close());const loc='berts',date='2026-10-01',at=new Date(Date.now()-1000).toISOString(),feed={recordCount:1,checkedAt:at,dataThrough:at,paginationComplete:true,correctionsApplied:true,dayClosed:true},good={schemaVersion:'jmax-toast-day-read.v1',...scoped(loc,date),source:{system:'toast',restaurantGuid:restaurants[loc]},orders:feed,labor:feed};const reader=configuredToastDayReader({SUPABASE_URL:'https://fictional-project.supabase.co',SUPABASE_SECRET_KEY:'sb_secret_FICTIONAL_PRIVATE'},async()=>Response.json(good,{status:206,headers:{'Content-Range':'0-0/20'}}));const r=await call(s,loc,date,reader);receipts.push({case:'partial saved-data transport',actualStatus:r.status,desiredStatus:503,value:r.data.orders.recordCount});assert.equal(r.status,503);assert.equal(r.data.orders.recordCount,null);
});

test.after(()=>fs.writeFileSync(path.join(output,'summary.json'),JSON.stringify({runtime,modules:manifests,restaurants:Object.keys(restaurants),simulatedDaysPerRestaurant:21,externalNetworkCalls:0,receipts,limits:['Fictional saved imports in persistent SQLite; actual protected app read handler and Supabase transport shape.','Financial adapter is a server utility, not an installed sales dashboard or native Toast ingest route.','No real Toast API requests, employee pay records, inventory changes or schedule publication.']},null,2)+'\n'));
