import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {openPositionDatabase} from './all-position-week-fixture.mjs';
import {handleToastSchedule} from '../.sites-runtime/shared/toast-schedule-service.mjs';
import {normalizeToastSchedule,fetchToastSchedule} from '../.sites-runtime/shared/toast-schedule.mjs';
import {handleScheduleImport} from '../.sites-runtime/shared/schedule-import-service.mjs';
import {handleWorkspace} from '../.sites-runtime/shared/service.mjs';
import {cachedToastToken,forgetRejectedToastToken,ToastAuthWait} from '../.sites-runtime/shared/toast-auth-cache.mjs';

const out=path.resolve(process.env.TOAST_STRESS_OUTPUT??'evidence/schedule-toast-simulations-2026-10-08/toast-schedules');fs.mkdirSync(out,{recursive:true});
const guid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const restaurant=guid(1),employee=guid(22),job=guid(33);
const shift=(n=100,changes={})=>({guid:guid(n),employeeReference:{guid:employee},jobReference:{guid:job},inDate:'2026-10-07T16:00:00Z',outDate:'2026-10-07T20:00:00Z',modifiedDate:'2026-10-06T12:00:00Z',deleted:false,...changes});
const receipts=[];const defects=[];
function save(name,facts){const receipt={name,...facts};receipts.push(receipt);fs.writeFileSync(path.join(out,name+'.json'),JSON.stringify(receipt,null,2));fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify({status:defects.some(item=>item.severity!=='limitation')?'confirmed-gaps':defects.length?'passed-with-limitations':'passed',mockedRemoteRequests:true,externalToastRequests:0,receipts,defects,limits:['Preview reads planned POS shifts; no Sling-calendar equality or active-shift import is established.','HotSchedules import is a separate CSV reference flow; it never publishes shifts.','Official Toast GET shifts documents an unordered array, with no pagination parameters. Unexpected partial responses are tested as integrity failures, not proof of a documented paging contract.','Weekly coverage is supported for shifts of at most24elapsedhours. Arbitrary longer upstream shifts ending at/after the exclusive query boundary are not guaranteed complete.']},null,2));}
async function fixture(t){
 const file=path.join(out,crypto.randomUUID()+'.sqlite');let store=openPositionDatabase(file);
 t.after(()=>store.close());
 for(const name of fs.readdirSync('drizzle').filter(file=>file.endsWith('.sql')).sort())store.sqlite.exec(fs.readFileSync('drizzle/'+name,'utf8').replaceAll('--> statement-breakpoint',''));
 for(const loc of ['berts','rudds','papa'])store.sqlite.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').run(loc,'Fictional '+loc,'America/New_York');
 for(const [who,loc,caps] of [['admin','rudds',['location.manage','schedule.manage','schedule.publish']],['worker','rudds',[]],['second','rudds',[]],['outsider','berts',['location.manage']],['papa','papa',['location.manage']]])store.sqlite.prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').run(who,who+'@example.test',who+'-identity',loc,'Fictional '+who,'FOH',who==='worker'?'Server':'General manager',JSON.stringify(caps),'[]');
 const bindings={TOAST_LOCATION_ID:'rudds',TOAST_RESTAURANT_GUID:restaurant,TOAST_CLIENT_ID:'fictional-client',TOAST_CLIENT_SECRET:'fictional-private-secret'};
 const headers=who=>({'oai-authenticated-user-id':who+'-identity','oai-authenticated-user-email':who+'@example.test',Origin:'https://toast-stress.example','Content-Type':'application/json'});
 const request=(who='admin',query='locationId=rudds&weekStart=2026-10-05',method='GET',body)=>new Request('https://toast-stress.example/api/integrations/toast-schedule?'+query,{headers:headers(who),method,...(body?{body:JSON.stringify(body)}:{})});
 const call=(fetcher,who='admin',query,method='GET')=>handleToastSchedule(request(who,query,method),store.db,bindings,fetcher);
 const source=(rows,status=200,extraHeaders)=>async(url,options)=>url.includes('/authentication/')?Response.json({status:'SUCCESS',token:{tokenType:'Bearer',accessToken:'fictional-private-token',expiresIn:3600}}):Response.json(rows,{status,headers:extraHeaders});
 const match=(id,who,sourceEmployee=employee,status='applied',rest=restaurant)=>store.sqlite.prepare('INSERT INTO access_reviews(id,location_id,restaurant_guid,employee_id,source_at,source,data,status,member_id,revision,updated_at) VALUES(?,?,?,?,?,\'{}\',\'{}\',?,?,1,?)').run(id,'rudds',rest,sourceEmployee,'2026-10-08',status,who,'2026-10-08');
 const operational=()=>JSON.stringify(Object.fromEntries(['records','schedule_imports','access_reviews','memberships','audit_events','command_receipts'].map(table=>[table,store.sqlite.prepare('SELECT * FROM '+table+' ORDER BY rowid').all()])));
 return {file,bindings,headers,request,call,source,match,operational,get store(){return store;},reopen(){store.close();store=openPositionDatabase(file);}};
}

test('protected preview repeats and survives disk reopen without importing, publishing or provisioning staff',async t=>{
 const f=await fixture(t);f.match('valid','worker');let requests=[];const remote=async(url,options)=>{requests.push({path:new URL(url).pathname,method:options.method,restaurant:options.headers['Toast-Restaurant-External-ID']??null});if(url.includes('/authentication/'))return f.source([])(url,options);return Response.json([shift(),shift(101,{deleted:true})]);};
 const before=f.operational();const first=await f.call(remote);assert.equal(first.status,200);const data=await first.json();assert.equal(data.previewOnly,true);assert.equal(data.source,'toast-labor-scheduled-shifts');assert.equal(data.snapshot.restaurantGuid,restaurant);assert.equal(data.snapshot.shifts.length,2);assert.equal(data.employees[0].memberId,'worker');assert.ok(!JSON.stringify(data).includes('fictional-private'));assert.equal(f.operational(),before);f.reopen();const second=await f.call(remote);assert.equal(second.status,200);assert.deepEqual((await second.json()).snapshot.shifts,data.snapshot.shifts);assert.equal(f.operational(),before);assert.equal(requests.filter(r=>r.path.includes('authentication')).length,1);assert.ok(requests.filter(r=>r.path==='/labor/v1/shifts').every(r=>r.method==='GET'&&r.restaurant===restaurant));save('read-only-repeat',{status:'passed',actualProtectedReads:2,cacheSurvivesReopen:true,noOperationalWrites:true,deletedPreserved:true,provenance:data.source,database:f.file});
});

test('missing, malformed, duplicate and foreign employee references never silently become local identities',async t=>{
 const f=await fixture(t);const before=f.operational(),statuses=[];for(const invalid of [{employeeReference:{}},{employeeReference:null},{employeeReference:{guid:'not-an-id'}},{jobReference:{}},{deleted:null},{guid:undefined}]){const response=await f.call(f.source([shift(100,invalid)]));assert.equal(response.status,502);statuses.push(response.status);assert.equal((await response.json()).snapshot,undefined);}const duplicate=await f.call(f.source([shift(),shift()]));assert.equal(duplicate.status,502);f.match('foreign-review','worker',employee,'applied',guid(55));const foreignBefore=f.operational();const unmatched=await f.call(f.source([shift()]));assert.equal(unmatched.status,200);assert.deepEqual((await unmatched.json()).employees,[]);assert.equal(f.operational(),foreignBefore);save('employee-reference-integrity',{status:'passed',malformedCases:6,statuses,duplicateShiftRejected:true,foreignRestaurantReviewExcluded:true,unmatchedRemainsUnmatched:true,noOperationalWrites:true,database:f.file});
});

test('case-insensitive duplicate employee GUIDs stay unmatched rather than choosing an arbitrary local identity',async t=>{
 const f=await fixture(t);const mixed='abcdefab-cdef-4abc-8def-abcdefabcdef';f.match('lower','worker',mixed);f.match('upper','second',mixed.toUpperCase());const response=await f.call(f.source([shift(100,{employeeReference:{guid:mixed}})]));assert.equal(response.status,200);const data=await response.json();assert.deepEqual(data.employees,[]);save('ambiguous-employee-guid',{status:'passed',ambiguousNormalizedGuidExcluded:true,localMatches:data.employees.map(row=>row.memberId),database:f.file});
});

test('DST changes and Sunday overnight keep offset-aware instants and local starting-week boundaries',async t=>{
 const f=await fixture(t),rows=[shift(100,{inDate:'2026-11-01T01:30:00-04:00',outDate:'2026-11-01T02:30:00-05:00'}),shift(101,{inDate:'2026-11-01T23:00:00-05:00',outDate:'2026-11-02T03:00:00-05:00'}),shift(102,{inDate:'2026-11-02T00:30:00-05:00',outDate:'2026-11-02T04:00:00-05:00'})];let query;const response=await f.call(async(url,options)=>{if(url.includes('/authentication/'))return f.source([])(url,options);query=new URL(url).searchParams;return Response.json(rows);},'admin','locationId=rudds&weekStart=2026-10-26');assert.equal(response.status,200);const data=await response.json();assert.equal(data.snapshot.shifts.length,2);assert.equal(Date.parse(data.snapshot.shifts[0].end)-Date.parse(data.snapshot.shifts[0].start),2*3600000);assert.equal(query.get('startDate'),'2026-10-26T04:00:00.000Z');assert.equal(query.get('endDate'),'2026-11-03T05:00:00.000Z');assert.throws(()=>normalizeToastSchedule([shift(100,{inDate:'2026-11-01T01:30:00'})],restaurant,'2026-10-26','America/New_York'));save('dst-and-overnight',{status:'passed',offsetAwareElapsedHours:2,sundayOvernightIncluded:true,nextWeekStartExcluded:true,offsetlessTimeRejected:true,database:f.file});
});

test('nonexistent source calendar dates are rejected rather than rewritten into a different day',async t=>{
 const f=await fixture(t);const response=await f.call(f.source([shift(100,{inDate:'2026-02-30T12:00:00Z',outDate:'2026-02-30T16:00:00Z'})]),'admin','locationId=rudds&weekStart=2026-03-02');assert.equal(response.status,502);assert.equal((await response.json()).snapshot,undefined);assert.throws(()=>normalizeToastSchedule([shift(100,{modifiedDate:'2026-02-29T12:00:00Z'})],restaurant,'2026-10-05','America/New_York'));assert.equal(normalizeToastSchedule([shift(100,{inDate:'2028-02-29T12:00:00Z',outDate:'2028-02-29T16:00:00Z'})],restaurant,'2028-02-28','America/New_York').shifts.length,1);save('malformed-calendar-date',{status:'passed',malformedSourceDateRejected502:true,nonLeapModifiedDateRejected:true,validLeapDayAccepted:true,database:f.file});
});

test('partial HTTP success and unexpected continuation indicators never become a full weekly comparison',async t=>{
 const f=await fixture(t);for(const [status,headers] of [[206,{'Content-Range':'shifts 0-0/20'}],[200,{'Content-Range':'shifts 0-0/20'}],[200,{Link:'<https://ws-api.toasttab.com/labor/v1/shifts?page=2>; rel="next"'}],[200,{'Toast-Next-Page-Token':'fictional-next'}]]){const response=await f.call(f.source([shift()],status,headers));assert.equal(response.status,502);assert.equal((await response.json()).snapshot,undefined);}save('partial-response',{status:'passed',partialOrContinuationCases:4,incompletePreviewNeverDelivered:true,database:f.file});
});

test('dead cached session gets one bounded refresh and errors never fake an empty plan or reveal tokens',async t=>{
 const f=await fixture(t);let authCalls=0,shiftCalls=0;const dead=async(url,options)=>{if(url.includes('/authentication/')){authCalls++;return Response.json({status:'SUCCESS',token:{tokenType:'Bearer',accessToken:'fictional-private-token-'+authCalls,expiresIn:3600}});}shiftCalls++;return options.headers.Authorization.endsWith('-1')?new Response('PRIVATE_UPSTREAM_BODY',{status:401}):Response.json([shift()]);};for(let n=0;n<3;n++){const response=await f.call(dead);assert.equal(response.status,200);const data=await response.json();assert.equal(data.snapshot.shifts.length,1);assert.ok(!JSON.stringify(data).includes('PRIVATE_UPSTREAM_BODY'));assert.ok(!JSON.stringify(data).includes('fictional-private-token'));}assert.equal(authCalls,2);assert.equal(shiftCalls,4);let second401Reads=0,second401Auth=0;const fails=await f.call(async(url,options)=>{if(url.includes('/authentication/')){second401Auth++;return f.source([])(url,options);}second401Reads++;return new Response('PRIVATE_UPSTREAM_BODY',{status:401});});assert.equal(fails.status,503);assert.equal(second401Reads,2);assert.equal(second401Auth,1);for(const status of [301,302,403,429,500,503]){const response=await f.call(async(url,options)=>url.includes('/authentication/')?f.source([])(url,options):new Response('PRIVATE_UPSTREAM_BODY',{status}));assert.equal(response.status,status===429?429:503);assert.equal((await response.json()).snapshot,undefined);}save('dead-session-and-errors',{status:'passed',successfulReads:3,authCalls,shiftCalls,bounded401RetryReads:second401Reads,upstreamErrorCases:6,errorsNeverBecomeEmptyPlan:true,bodyAndTokenNotDisclosed:true,database:f.file});
});

test('mock honors Toast exclusive outDate filtering: normal Sunday overnight survives while exact query boundary cannot be claimed complete',async t=>{
 const f=await fixture(t),rows=[shift(100,{inDate:'2026-10-11T23:00:00-04:00',outDate:'2026-10-12T04:00:00-04:00'}),shift(101,{inDate:'2026-10-11T18:00:00-04:00',outDate:'2026-10-13T00:00:00-04:00'}),shift(102,{inDate:'2026-10-11T23:59:59-04:00',outDate:'2026-10-12T23:59:59-04:00'})];let bounds;const response=await f.call(async(url,options)=>{if(url.includes('/authentication/'))return f.source([])(url,options);const params=new URL(url).searchParams;bounds={startDate:params.get('startDate'),endDate:params.get('endDate')};return Response.json(rows.filter(row=>Date.parse(row.inDate)>=Date.parse(bounds.startDate)&&Date.parse(row.outDate)<Date.parse(bounds.endDate)));});assert.equal(response.status,200);const data=await response.json();assert.deepEqual(data.snapshot.shifts.map(row=>row.toastShiftId),[guid(100),guid(102)]);assert.equal(Date.parse(rows[1].outDate),Date.parse(bounds.endDate));assert.equal(Date.parse(data.snapshot.shifts[1].end)-Date.parse(data.snapshot.shifts[1].start),24*3600000);defects.push({id:'long-cross-week-query-boundary',severity:'limitation',observed:'A Sunday-start30-hour upstream shift ending exactly Tuesday00 query boundary is absent because Toast requires outDate strictly before endDate. Ordinary Sunday23→Monday04 and latestSunday24hourshift are returned.',scope:'The extra-day query covers shifts of at most24elapsedhours; arbitrary longer upstream shifts are not guaranteed complete. No invented pagination or shift-writing workaround.'});save('exclusive-end-boundary',{status:'limitation-recorded',normalSundayOvernightReturned:true,latestSunday24HourShiftReturned:true,exactQueryEndOmitted:true,exactBoundaryShiftHours:30,bounds,officialContract:'https://doc.toasttab.com/openapi/labor/operation/shiftsGet/',database:f.file});
});

test('late rejected-token cleanup preserves a newer session, another restaurant and an in-progress refresh lease',async t=>{
 const f=await fixture(t),config={locationId:'rudds',restaurantGuid:restaurant,host:'https://ws-api.toasttab.com',clientId:'fictional-client',clientSecret:'fictional-secret'};
 const other={...config,locationId:'berts',restaurantGuid:guid(99)};
 await cachedToastToken(f.store.db,config,async()=>({accessToken:'fictional-old',expiresIn:3600}));
 await cachedToastToken(f.store.db,other,async()=>({accessToken:'fictional-other',expiresIn:3600}));
 await forgetRejectedToastToken(f.store.db,config,'fictional-old');
 let release,entered;const began=new Promise(resolve=>{entered=resolve;});const gate=new Promise(resolve=>{release=resolve;});
 const refresh=cachedToastToken(f.store.db,config,async()=>{entered();await gate;return {accessToken:'fictional-new',expiresIn:3600};});await began;
 await forgetRejectedToastToken(f.store.db,config,'fictional-old');
 await assert.rejects(cachedToastToken(f.store.db,config,async()=>{throw Error('Must not bypass an active refresh lease');}),error=>error instanceof ToastAuthWait);
 release();assert.equal(await refresh,'fictional-new');await forgetRejectedToastToken(f.store.db,config,'fictional-old');
 assert.equal(await cachedToastToken(f.store.db,config,async()=>{throw Error('Late old rejection must not erase new cache');}),'fictional-new');
 assert.equal(await cachedToastToken(f.store.db,other,async()=>{throw Error('Other restaurant cache must survive');}),'fictional-other');
 const rows=f.store.sqlite.prepare('SELECT encrypted_token FROM toast_auth_cache').all();assert.equal(rows.length,2);assert.ok(rows.every(row=>!row.encrypted_token.includes('fictional-')));
 save('token-refresh-race',{status:'passed',concurrentRefreshLeasePreserved:true,newerTokenPreserved:true,otherRestaurantCachePreserved:true,encryptedOnlyPersistence:true,database:f.file});
});

test('wrong-store, staff, method and account-change rejection precede or invalidate source delivery',async t=>{
 const f=await fixture(t);let calls=0;const never=async()=>{calls++;throw Error('Must not contact remote');};for(const [who,query,method,status] of [['admin','locationId=berts&weekStart=2026-10-05','GET',403],['worker','locationId=rudds&weekStart=2026-10-05','GET',403],['admin','locationId=rudds&weekStart=2026-10-05','POST',405],['admin','locationId=rudds&weekStart=2026-10-05&accessToken=override','GET',400],['admin','locationId=rudds&locationId=papa&weekStart=2026-10-05','GET',400]])assert.equal((await f.call(never,who,query,method)).status,status);assert.equal(calls,0);const configRace=await f.call(async(url,options)=>{if(url.includes('/authentication/'))return f.source([])(url,options);f.bindings.TOAST_RESTAURANT_GUID=guid(99);return Response.json([shift()]);});assert.equal(configRace.status,409);f.bindings.TOAST_RESTAURANT_GUID=restaurant;const revoked=await f.call(async(url,options)=>{if(url.includes('/authentication/'))return f.source([])(url,options);f.store.sqlite.prepare("UPDATE memberships SET active=0,revision=revision+1 WHERE id='admin'").run();return Response.json([shift()]);});assert.equal(revoked.status,403);save('scope-and-inflight-change',{status:'passed',preFetchDenials:5,noRemoteRequestsForDeniedScopes:true,connectionChange409:true,revocation403:true,database:f.file});
});

test('Toast preview objects cannot enter the separate CSV reference import or publish native shifts',async t=>{
 const f=await fixture(t);const before=f.operational();const snapshot=await (await f.call(f.source([shift()]))).json();const request=new Request('https://toast-stress.example/api/integrations/hotschedules',{method:'POST',headers:f.headers('admin'),body:JSON.stringify({locationId:'rudds',action:'save',snapshot:snapshot.snapshot,confirmed:true})});const response=await handleScheduleImport(request,f.store.db);assert.equal(response.status,400);assert.equal(f.operational(),before);const workspaceRequest=new Request('https://toast-stress.example/api/workspace',{method:'POST',headers:f.headers('admin'),body:JSON.stringify({locationId:'rudds',requestId:crypto.randomUUID(),action:'toast.schedule.import',input:{snapshot:snapshot.snapshot}})});const command=await handleWorkspace(workspaceRequest,f.store.db);assert.equal(command.status,400);assert.equal(f.operational(),before);save('preview-not-import',{status:'passed',toastSnapshotCsvImportRejected:true,toastImportCommandAbsent:true,noNativeShiftImportPublishOrIdentityProvision:true,database:f.file});
});

test('weekly repeated source reads report current changes and deletions but never treat a preview as durable schedule memory',async t=>{
 const f=await fixture(t);let count=0;const source=async(url,options)=>url.includes('/authentication/')?f.source([])(url,options):Response.json([shift(100,{deleted:count++>0,modifiedDate:count>1?'2026-10-08T12:00:00Z':'2026-10-06T12:00:00Z'})]);const before=f.operational();const a=await (await f.call(source)).json();f.reopen();const b=await (await f.call(source)).json();assert.equal(a.snapshot.shifts[0].deleted,false);assert.equal(b.snapshot.shifts[0].deleted,true);assert.notEqual(a.snapshot.shifts[0].modifiedAt,b.snapshot.shifts[0].modifiedAt);assert.equal(f.operational(),before);save('current-source-not-imported-memory',{status:'passed',freshDeletionObserved:true,reopenDidNotCreateLocalShifts:true,previewNotStoredAsSchedule:true,database:f.file});
});
