import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import {Miniflare} from 'miniflare';import {seedManifest,manifestHeaders,addManifestTransfer} from './transfer-manifest-fixture.mjs';
process.env.MINIFLARE_REGISTRY_PATH??=path.resolve('.wrangler/registry');
test('compiled manifest route serves scoped read-only snapshots and suppresses unauthorized access',async t=>{
 let outbound=0;const mf=new Miniflare({modules:true,scriptPath:path.resolve('dist/server/index.js'),modulesRoot:path.resolve('dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js']}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],serviceBindings:{ASSETS:()=>new Response('Missing',{status:404})},outboundService:()=>{outbound++;throw Error('No outbound')}});t.after(()=>mf.dispose());const db=await mf.getD1Database('DB');await seedManifest(db);await addManifestTransfer(db,'one');await addManifestTransfer(db,'two');
 const get=(actor,loc='a',view='outgoing',dataset='demo')=>mf.dispatchFetch('http://localhost/api/food/transfers?'+new URLSearchParams({locationId:loc,dataset,manifest:'1',trip:'Trip 1',date:'2026-09-28',view}),{headers:manifestHeaders(actor)});
 const before=(await db.prepare('SELECT * FROM food_transfers').all()).results,r=await get('sender');assert.equal(r.status,200);const m=await r.json();assert.equal(m.kind,'trip-manifest');assert.deepEqual(m.counts,{transfers:2,parcels:2,arrived:0,awaiting:2});assert.equal((await (await get('receiver','b','incoming')).json()).counts.transfers,2);assert.equal((await (await get('sender','a','outgoing','operating')).json()).counts.transfers,0);
 for(const actor of ['worker','foh','outsider'])assert.equal((await get(actor)).status,403);
 assert.deepEqual((await db.prepare('SELECT * FROM food_transfers').all()).results,before);assert.equal((await db.prepare('SELECT count(*) n FROM food_receipts').first()).n,0);assert.equal(outbound,0);
});
