import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {handleFoodWorkflows} from '../.sites-runtime/shared/food-workflow-service.mjs';
import {handleEmployeePrep} from '../.sites-runtime/shared/employee-prep-service.mjs';
import {handleFoodAdvisor} from '../.sites-runtime/shared/food-advisor-service.mjs';
import {backWindowItems,estimateBackWindowCups,planBackWindowPrep} from '../.sites-runtime/shared/back-window-prep.mjs';
import {prepProgress} from '../.sites-runtime/shared/prep-progress.mjs';

// Executes the current authenticated services against disposable in-memory SQL.
// It does not call live sources, Workers, a browser, or a restaurant database.
const output=new URL('../evidence/week-simulation/back-window.json',import.meta.url);
const source=(file,needle)=>({path:file,line:fs.readFileSync(new URL('../'+file,import.meta.url),'utf8').split(/\r?\n/).findIndex(l=>l.includes(needle))+1});
const NativeDate=globalThis.Date;
let now='2026-09-30T22:00:00Z';
const dayDate=n=>new NativeDate(Date.UTC(2026,9,n)).toISOString().slice(0,10);
function fixture(t){
 const sqlite=new DatabaseSync(':memory:');t.after(()=>sqlite.close());
 const db={prepare(sql){let args=[];return {bind(...v){args=v;return this},async all(){const results=sqlite.prepare(sql).all(...args);return {results,meta:{changes:Number(sqlite.prepare('SELECT changes() AS n').get().n)}}},async first(){return sqlite.prepare(sql).get(...args)??null},async run(){const r=sqlite.prepare(sql).run(...args);return {results:[],meta:{changes:Number(r.changes)}}}}},async batch(stmts){sqlite.exec('BEGIN');try{const results=[];for(const s of stmts)results.push(await s.all());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}};db.withSession=()=>db;
 for(const f of fs.readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8').replaceAll('--> statement-breakpoint',''));
 for(const loc of ['berts','foreign-store'])sqlite.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').run(loc,'Fictional isolated '+loc,'America/New_York');
 for(const [id,loc,position,caps,scheduleOnly] of [['bw','berts','Back Window',[],0],['other','berts','Back Window',[],0],['manager','berts','FOH Manager',['tasks.manage','operations.store'],0],['foreign','foreign-store','Back Window',[],0],['schedule','berts','Back Window',[],1]])sqlite.prepare("INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications,active,schedule_only) VALUES(?,?,?,?,?,'FOH',?,?,'[]',1,?)").run(id,id+'@example.test',id+'-identity',loc,'Fictional '+id,position,JSON.stringify(caps),scheduleOnly);
 sqlite.prepare('INSERT INTO food_state(location_id) VALUES(?)').run('berts');
 for(const item of backWindowItems){
  const recipe={title:'Fictional '+item.title,recipeType:'prep',sourceId:item.id,yieldQty:50,yieldUOM:'cup',procedure:'Fictional fixture: portion reviewed dressing into ready cups.',equipment:'Portion cups, lids, storage pan',shelfLife:'5 days',portionNote:'3.25 oz portion cups; pan holds ready cups.',lines:[],source:{sourceRestaurantId:'fixture-berts',dataset:'operating'}};
  sqlite.prepare('INSERT INTO food_records(id,location_id,kind,dataset,source_restaurant_id,source_key,title,owner_id,area,revision,data,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run('recipe-'+item.id,'berts','foodrecipe','operating','fixture-berts',item.id,recipe.title,'manager','FOH',1,JSON.stringify(recipe),now);
 }
 let requestSequence=0;
 const raw=async(actor,handler,path,body)=>{const response=await handler(new Request('http://localhost'+path,{headers:{'oai-authenticated-user-id':actor+'-identity','oai-authenticated-user-email':actor+'@example.test',Origin:'http://localhost','Content-Type':'application/json'},...(body?{method:'POST',body:JSON.stringify(body)}:{})}),db);return {status:response.status,data:await response.json()}};
 const body=(action,input={},record,requestId)=>({requestId:requestId??'bw-week-'+(++requestSequence),locationId:'berts',action,input:{dataset:'operating',...input},...(record?{recordId:record.recordId??record.id,expectedRevision:record.revision}:{})});
 const command=(actor,action,input={},record,requestId)=>raw(actor,handleFoodWorkflows,'/api/food/workflows',body(action,input,record,requestId));
 const report=async(actor,command)=>raw(actor,handleFoodWorkflows,'/api/food/workflows',command);
 const view=actor=>raw(actor,handleEmployeePrep,'/api/food/assigned-prep?locationId=berts');
 const saved=ref=>JSON.parse(sqlite.prepare('SELECT data FROM food_workflows WHERE id=?').get(ref.recordId??ref.id).data);
 const plans=()=>sqlite.prepare("SELECT data FROM food_workflows WHERE kind='plan'").all().map(r=>JSON.parse(r.data));
 const totals=()=>Object.fromEntries(['food_workflow_events','food_receipts','audit_events'].map(table=>[table,Number(sqlite.prepare('SELECT count(*) AS n FROM '+table).get().n)]));
 return {sqlite,db,body,raw,command,report,view,saved,plans,totals};
}
const ok=result=>{assert.equal(result.status,200,JSON.stringify(result.data));return result.data};

test('Back Window seven-day current-service simulation with counts, release, actual work, shortages and concurrency',async t=>{
 globalThis.Date=class extends NativeDate{constructor(...args){super(...(args.length?args:[now]))}static now(){return new NativeDate(now).getTime()}};t.after(()=>{globalThis.Date=NativeDate});
 const f=fixture(t),definitions=new Map(),days=[],findings=[];
 const step=(day,action,expected,actual,evidence='executed-service')=>day.actions.push({action,expected,actual,evidence});
 for(const item of backWindowItems){const r=ok(await f.command('manager','definition.save',{foodRecordId:'recipe-'+item.id,foodRevision:1,track:'daily',countUnit:'cup',quantityMode:'whole-portions',par:item.referenceParCups,reviewNote:'Fictional manager deliberately selects reference par for this scenario; not a production decision.',confirmed:true}));definitions.set(item.id,r)}
 assert.equal(backWindowItems.length,8);assert.ok(backWindowItems.every(i=>i.cupSizeOz===3.25));
 let onHand=Object.fromEntries(backWindowItems.map(i=>[i.id,i.referenceParCups]));onHand.ranch=75;onHand['honey-mustard']=47;
 for(let d=1;d<=7;d++){
  const date=dayDate(d),countDate=dayDate(d-1),day={day:d,date,actor:'Fictional Back Window employee bw',physicalOpeningCups:{...onHand},actions:[]};days.push(day);
  now=countDate+'T22:00:00Z';
  step(day,'Check prior close; prepare equipment; friendly upsell; check Expo contents while bagging; attach ticket; verify guest name/payment; report error to Expo','Owner-confirmed routine remains available as source-backed catalog guidance. No guest-order or live service claim.',{catalog:'app/shared/starter-tasks.ts:33-36',opening:'Prior close and dressing count',service:'Expo check, condiments/cups/kits, ticket, name/payment, ready/pending order handoff',missingCatalogDetail:'Friendly upsell and Expo approx 90% complete are absent from Back Window reference.'},'source-only');
  if(d===3){onHand.french=estimateBackWindowCups({container:'sixth',fullPans:0,partialPanFraction:0.5}).usableCups;day.physicalOpeningCups.french=onHand.french}
  const employeeCount=await f.command('bw','count.create',{track:'daily',businessDate:countDate});assert.equal(employeeCount.status,403);step(day,'Employee records the evening count directly','Management boundary is enforced; an employee needs manager-mediated entry in current workflow.',employeeCount);
  let count=ok(await f.command('manager','count.create',{track:'daily',businessDate:countDate}));
  count=ok(await f.command('manager','count.save',{lines:backWindowItems.map(i=>({definitionId:definitions.get(i.id).recordId,quantity:d===5&&i.id==='tartar'?null:onHand[i.id],note:'Fictional observed ready portion cups, not gallons or liquid-pan fill.'}))},count));
  count=ok(await f.command('manager','count.submit',{confirmed:true},count));
  let plan=ok(await f.command('manager','plan.generate',{countId:count.recordId,countRevision:count.revision,targetDate:date}));
  if(d===5){const before=f.totals(),rejected=await f.command('manager','plan.release',{confirmed:true},plan);assert.equal(rejected.status,409);assert.deepEqual(f.totals(),before);step(day,'Submit unknown tartar count and try releasing work','Missing remains unknown, blocks release, and writes nothing.',rejected);count=ok(await f.command('manager','count.reopen',{reason:'Fictional physical recount confirms zero tartar cups.'},count));onHand.tartar=0;count=ok(await f.command('manager','count.save',{lines:[{definitionId:definitions.get('tartar').recordId,quantity:0,note:'Explicit observed zero.'}]},count));count=ok(await f.command('manager','count.submit',{confirmed:true},count));plan=ok(await f.command('manager','plan.generate',{countId:count.recordId,countRevision:count.revision,targetDate:date},plan));}
  const draft=f.saved(plan);
  if(d===1){const helper=planBackWindowPrep({itemId:'honey-mustard',forecastUsageCups:30,bufferCups:5,usableCups:47});assert.equal(helper.recommendedCups,0);const line=draft.lines.find(l=>l.definitionId===definitions.get('honey-mustard').recordId);assert.equal(line.plannedQty,3);step(day,'Compare 47 ready honey mustard cups with sufficient hypothetical coverage (30 demand +5 buffer)','Usage recommendation is zero; explicitly selected legacy par 50 requests three. No live forecast or configured advisor is inferred.',{helper,actualSavedPlan:{count:line.quantity,par:line.par,plannedQty:line.plannedQty}});findings.push({id:'BW-01',severity:'P1-product-integration',title:'Back Window usage helper is disconnected from the legacy released prep workflow',evidence:'executed-service-and-helper',location:source('app/shared/food-workflow-model.ts','export function planLines'),repro:'Create cup definition with manager-selected par 50, save47cups, submit current evening count, generate next-day plan, release/assign. Pure usage helper with explicit30usage+5buffer recommends0; saved plan asks3.',actual:{readyCups:47,selectedPar:50,hypotheticalUsage:30,hypotheticalBuffer:5,helperRecommendedCups:0,releasedWorkflowCups:3},qualification:'Existing authenticated Food advisor can update reviewed target pars when configured. This reproduces the deliberate legacy count track, not the deployed source extension planner or a live recommendation. The product gap is absent Back Window usage-helper integration and no available configured source in this fixture.'});}
  plan=ok(await f.command('manager','plan.release',{confirmed:true},plan));
  for(const line of f.saved(plan).lines.filter(l=>l.plannedQty>0))plan=ok(await f.command('manager','plan.assign',{definitionId:line.definitionId,assignedTo:'bw'},plan));
  const advance=ok(await f.view('bw'));assert.ok(advance.items.every(i=>i.targetDate===date));
  step(day,'Read assigned prep on the previous evening, before its target day','Released assignments display their target date. Advance visibility is recorded, not presumed incorrect.',{clock:now,items:advance.items.map(i=>({title:i.title,quantity:i.quantity,unit:i.unit,targetDate:i.targetDate}))});
  if(d===1){const shelf=advance.items[0].recipe;assert.equal(shelf.shelfLife,'5 days');assert.equal(JSON.parse(f.sqlite.prepare("SELECT data FROM food_records WHERE id='recipe-ranch'").get().data).shelfLife,'5 days');step(day,'Read source shelf-life metadata on the assigned recipe','Source metadata is preserved without inventing an expiration date.',{sourceShelfLife:'5 days (fictional fixture)',returnedRecipe:shelf});const advice=await f.raw('manager',handleFoodAdvisor,'/api/food/advisor?locationId=berts&dataset=operating');assert.equal(advice.status,200);assert.equal(advice.data.status,'unavailable');step(day,'Read source Food advisor with no connector configured','Explicit unavailable result, no invented history, forecast or live integration.',advice);}
  now=date+'T13:00:00Z';
  assert.equal((await f.view('other')).data.items.length,0);for(const actor of ['foreign','schedule'])assert.equal((await f.view(actor)).status,403);
  const unauthorized=await f.command('bw','plan.assign',{definitionId:definitions.get('ranch').recordId,assignedTo:'other'},plan);assert.equal(unauthorized.status,403);step(day,'Check other employee/store/schedule-only access and attempt employee assignment','No cross-person work; foreign/schedule-only access and employee management action rejected.',{otherItemCount:0,foreign:403,scheduleOnly:403,employeeAssign:unauthorized});
  let view=ok(await f.view('bw')),production={};
  if(d===3){const french=view.items.find(i=>i.definitionId===definitions.get('french').recordId);assert.equal(french.quantity,8);assert.equal(french.quantityMode,'whole-portions');const helper=planBackWindowPrep({itemId:'french',forecastUsageCups:15,bufferCups:0,usableCups:7.5});assert.equal(helper.recommendedCups,8);const before=f.totals(),snapshot=f.saved(plan);const fractional=await f.command('bw','plan.employee-complete',{definitionId:french.definitionId,quantity:7.5,note:'Fractional estimate is not actual whole portion output.',confirmed:true},plan);assert.equal(fractional.status,400);assert.deepEqual(f.totals(),before);assert.deepEqual(f.saved(plan),snapshot);step(day,'Half sixth-pan estimate remains approximate stock, while whole portion production rounds up','Observed ready7.5cups remains stored; released production is8; fractionalactual7.5 is rejected without writes.',{estimatedReadyCups:7.5,releasedPlannedCups:french.quantity,helperRecommendedWholeCups:helper.recommendedCups,fractionalActualStatus:fractional.status});findings.push({id:'BW-03',severity:'resolved-local',title:'Whole portion unit definition prevents fractional cup production and actuals',evidence:'executed-service-and-helper',location:source('app/shared/food-workflow-model.ts','export function planLines'),repro:'Reviewed whole-portions definition, estimated onhand7.5, par15 generates8; employeeactual7.5 rejects400 without changing workflow/events/receipts; integer actual follows.',actual:{estimate:7.5,plannedProduction:8,rejectedFractionalActualStatus:400,helperWholeProduction:8},qualification:'Explicit reviewed quantityMode is required. Legacy definitions remain continuous until reviewed; recipe measuring cups and other continuous units are not rounded.'});}
  if(d===4){const first=view.items[0],command=f.body('plan.employee-complete',{definitionId:first.definitionId,quantity:first.quantity,confirmed:true},plan,'day4-concurrent');const original=f.db.batch;let injected=false;f.db.batch=async stmts=>{if(stmts.length===6&&!injected){injected=true;f.sqlite.prepare("UPDATE food_state SET revision=revision+1 WHERE location_id='berts'").run()}return original(stmts)};const before=f.totals(),r=await f.report('bw',command);f.db.batch=original;assert.equal(r.status,409);assert.deepEqual(f.totals(),before);assert.equal(f.saved(plan).revision,plan.revision);step(day,'Another food operation changes state immediately before completion write','Stale transaction returns409 and preserves plan/history/receipts; refreshed retry can continue.',r);}
  if(d===7){const first=view.items[0];f.sqlite.prepare('UPDATE food_records SET revision=revision+1 WHERE id=?').run(first.foodRecordId);const staleView=ok(await f.view('bw')).items.find(i=>i.definitionId===first.definitionId);assert.equal(staleView.recipe,null);const before=f.totals(),r=await f.command('bw','plan.employee-complete',{definitionId:first.definitionId,quantity:first.quantity,confirmed:true},plan);assert.equal(r.status,409);assert.deepEqual(f.totals(),before);step(day,'Source recipe changes after release','Employee receives changed-recipe notice; completion is blocked without writes.',{notice:staleView.recipeNotice,result:r});f.sqlite.prepare('UPDATE food_records SET revision=revision-1 WHERE id=?').run(first.foodRecordId);step(day,'Restore fixture-only source revision to continue scenario','This is test fixture setup, not a user recovery action or production fix.',{fixtureOnly:true},'fixture-manipulation');}
  view=ok(await f.view('bw'));
  for(const item of view.items){const reported=d===2&&item.definitionId===definitions.get('ranch').recordId?0:item.quantity;const note=reported<item.quantity?'Fictional dressing unavailable; manager informed; planned amount not produced.':'';
   if(d===2&&reported===0){const before=f.totals(),r=await f.command('bw','plan.employee-complete',{definitionId:item.definitionId,quantity:0,confirmed:true},plan);assert.equal(r.status,400);assert.deepEqual(f.totals(),before);step(day,'Report zero production without explaining shortage','Rejects incomplete shortage report without writes.',r)}
   const command=f.body('plan.employee-complete',{definitionId:item.definitionId,quantity:reported,note,confirmed:true},plan,'day'+d+'-'+item.definitionId),before=f.totals();const first=await f.report('bw',command);plan=ok(first);const after=f.totals(),snapshot=f.saved(plan),retry=await f.report('bw',command);assert.deepEqual(retry,first);assert.deepEqual(f.totals(),after);assert.deepEqual(f.saved(plan),snapshot);assert.equal(after.food_workflow_events,before.food_workflow_events+1);
   if(d===1){const changed=await f.report('bw',{...command,input:{...command.input,quantity:reported+1}});assert.equal(changed.status,409)}
   production[backWindowItems.find(i=>definitions.get(i.id).recordId===item.definitionId).id]=reported;
  }
  assert.equal(ok(await f.view('bw')).items.length,0);const progress=prepProgress(f.plans(),'berts','operating');
  if(d===2){const short=progress.find(p=>p.id===plan.recordId);assert.equal(short.remaining,0);assert.equal(short.shortages.find(s=>s.title==='Fictional Ranch').actual,0);assert.equal(f.saved(plan).status,'completed');}
  step(day,'Complete assigned prep, retry exact reports, read manager shortages','One completion event per report; exact retries replay receipt. Zero with explanation is real; shortages remain in manager progress.',{production,planStatus:f.saved(plan).status,employeeUnfinished:0,managerShortages:progress.flatMap(p=>p.shortages),receiptCounts:f.totals()});
  // Fictional consumption is an explicit physical scenario ledger, not JMAX stock.
  const usage=Object.fromEntries(backWindowItems.map(i=>[i.id,i.id==='ranch'?35:i.id==='honey-mustard'?12:4]));
  onHand=Object.fromEntries(backWindowItems.map(i=>[i.id,Math.max(0,onHand[i.id]+(production[i.id]??0)-usage[i.id])]));
  step(day,'Hand off ready/pending orders, manager closes drawer; clean closing area','Catalog retains manager drawer ownership and employee area/restroom duty. Physical work/service actions are scenario narrative, not executed integration.',{manager:'Cash drawer close',employee:'Ready/pending orders; pizza box off; tables/shelves/cooler/window; underneath/steps; employee restroom'},'source-only');
  step(day,'Next shift performs new physical count','Previous production and explicit fictional usage inform a fresh observed count. No automatic stock posting is expected.',{fictionalUsageCups:usage,nextPhysicalCountCups:{...onHand},appFoodStockMutation:false},'fixture-ledger');
 }
 const report={schema:'jmax.week-simulation.back-window.v1',generatedAt:new NativeDate().toISOString(),role:'Back Window',restaurant:'Bert’s',dates:{start:dayDate(1),end:dayDate(7)},result:'PASS: stateful executed-service simulation; product gaps reproduced',proofBoundary:{executed:'Current prepared service modules, authenticated Requests, in-memory SQLite adapter implementing D1 prepare/batch, all repository schema applied only to memory, fictional actors/recipes/counts. Seven simulated calendar days using virtual process time.',sourceOnly:'Catalog routines, UI form numeric-step inspection, archived workbook read. Physical cleaning, guest order checks, payment, Expo service and drawer close are scenario actions only.',notEstablished:'Rendered UI, deployed worker/browser integration, live Toast/Jeff forecast, source migration installation, actual restaurant operations, food shelf-life approval.',externalCalls:0,productionWrites:0},sourceWorkbook:{path:'C:/Users/ruddm/Documents/Codex/2026-09-30/h/outputs/email-import-2026-10-05/Bulk_Prep_Items_Export.xlsx',inspectedReadOnly:true,sheet:'Bulk Prep Items',dimensions:{rows:31,columns:13},header:['ID','Item Name','Bulk Par (Total)','Par Unit',"Bert’s Par","Rudd’s Par",'Location','on hand','Shelf Life (Days)','MON','Tues','Fri','Order'],matchedRow:{row:12,item:'Ranch',bulkParTotal:6,parUnit:'5 Gallons',bertsPar:6,ruddsPar:6,location:'both',onHand:null,shelfLifeDays:5,Monday:1,Friday:1},qualification:'Archived email source metadata only; bulk recipe/production context. No conversion from gallons/bulk par to ready-cup counts and no approval/currentness assumption.'},portionReferences:backWindowItems,findings,observations:[{id:'BW-OBS-01',evidence:'executed-service',title:'Upcoming released prep is visible before target day, with target date preserved',qualification:'Advance prep may be intended. Clarify due/ready semantics only if employee interpretation needs it; absence of a date filter alone is not a confirmed defect.'},{id:'BW-OBS-02',evidence:'executed-service',title:'Employee cannot enter evening counts directly; manager enters employee observations',qualification:'Enforced food-management authority may be intended. Product expectation for employee count capture needs explicit design, not relaxed role access.'},{id:'BW-OBS-03',evidence:'source-only',location:source('app/shared/starter-tasks.ts',"{id:'back-window-berts'"),title:'Back Window catalog omits friendly upsell and approximately90%-complete Expo context',qualification:'Catalog is a reference separate from saved standards, not proof that released employee duties lack this context.'}],days,assertions:{allSevenDays:true,countsGeneratedSubmittedReleased:true,partialPanEstimate:true,unknownVsZero:true,shortProduction:true,exactRetries:true,reusedRequestDifferentInputRejected:true,concurrentWriteRejected:true,changedRecipeRejected:true,employeeStoreRoleBoundary:true,nextDayPhysicalRecount:true}};
 fs.mkdirSync(new URL('../evidence/week-simulation/',import.meta.url),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');
 assert.equal(days.length,7);assert.deepEqual(findings.map(f=>f.id),['BW-01','BW-03']);assert.equal(findings.find(f=>f.id==='BW-03').severity,'resolved-local');
});
