import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {Miniflare} from 'miniflare';
import {handleWorkspace} from '../.sites-runtime/shared/service.mjs';
import {myWork} from '../.sites-runtime/shared/my-work.mjs';
import {buildShiftBrief} from '../.sites-runtime/shared/shift-brief.mjs';
import {buildRoleHome} from '../.sites-runtime/shared/role-home.mjs';
import {workforceContext} from '../.sites-runtime/shared/workforce-context.mjs';
import {companionContext} from '../.sites-runtime/shared/companion-context.mjs';
import {confirmedDutiesForLocation,confirmedDutySource} from '../.sites-runtime/shared/starter-tasks.mjs';

process.env.MINIFLARE_REGISTRY_PATH=path.resolve('tmp/week-server-registry');
const NativeDate=Date;
const evidence={role:'Server',mode:'Executable local simulation with isolated D1 and real workspace handlers; virtual Node clock, no live browser or external requests',source:confirmedDutySource,days:[],gaps:[],coverageLimitations:['No actual guest service, physical inspection or bank settlement can be proved by this simulation.','No live AI, Toast order entry/payment, payroll, real employees or restaurant production data were used.','Source references are copied into a fictional approved fixture through actual standard commands; this is no real operating approval.','Virtual Node clock controls workspace handler timestamps and projections; Miniflare database has isolated persistence only.'],counts:{commands:0,accepted:0,rejected:0,projections:0,outbound:0}};
let clock='2026-10-12T15:00:00.000Z',day;
const at=(n,hour=20)=>`2026-10-${11+n}T${String(hour).padStart(2,'0')}:00:00.000Z`;
const log=(action,expected,actual)=>day.actions.push({action,expected,actual});
const gap=(id,description,source,reproduction,actual)=>evidence.gaps.push({id,description,source,reproduction,actual});

test('Server: seven persisted days of briefing, service references, changes, corrections and checkout',async t=>{
 const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("isolated")}}',compatibilityDate:'2026-05-22',d1Databases:['DB'],outboundService:()=>{evidence.counts.outbound++;throw Error('No outbound allowed');}});
 t.after(async()=>{globalThis.Date=NativeDate;await mf.dispose();assert.equal(evidence.counts.outbound,0);fs.mkdirSync('evidence/week-simulation',{recursive:true});fs.writeFileSync('evidence/week-simulation/server.json',JSON.stringify(evidence,null,2)+'\n');});
 const db=await mf.getD1Database('DB');
 for(const name of fs.readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())await db.batch(fs.readFileSync('drizzle/'+name,'utf8').split('--> statement-breakpoint').filter(s=>s.trim()).map(s=>db.prepare(s)));
 for(const loc of ['rudds','foreign'])await db.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').bind(loc,'Fictional '+loc,'America/New_York').run();
 const caps=['schedule.manage','schedule.publish','schedule.change','tasks.manage','close.confirm','standards.approve','people.manage'];
 for(const [id,position,capabilities,loc='rudds'] of [['fixture-server','Server',[]],['fixture-coworker','Server',[]],['fixture-manager','Manager',caps],['fixture-unassigned','Manager',caps],['fixture-foreign','Server',[],'foreign']])await db.prepare('INSERT INTO memberships(id,email,auth_user_id,location_id,name,area,position,capabilities,qualifications) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,id+'@example.test',id,loc,id,'FOH',position,JSON.stringify(capabilities),JSON.stringify(['Server'])).run();
 globalThis.Date=class extends NativeDate {constructor(...args){super(...(args.length?args:[clock]));}static now(){return NativeDate.parse(clock);}};
 const headers=actor=>({'oai-authenticated-user-id':actor,'oai-authenticated-user-email':actor+'@example.test'});
 const call=async(actor,action,input={},record,requestId=crypto.randomUUID())=>{evidence.counts.commands++;const res=await handleWorkspace(new Request('https://fixture.example/api/workspace',{method:'POST',headers:{...headers(actor),Origin:'https://fixture.example','Content-Type':'application/json'},body:JSON.stringify({requestId,locationId:'rudds',action,input,...(record?{recordId:record.recordId??record.id,expectedRevision:record.revision}:{})})}),db);const result={status:res.status,data:await res.json()};evidence.counts[res.status===200?'accepted':'rejected']++;return result;};
 const view=async(actor='fixture-server')=>{const res=await handleWorkspace(new Request('https://fixture.example/api/workspace?locationId=rudds',{headers:headers(actor)}),db);assert.equal(res.status,200);return res.json();};
 const ok=r=>{assert.equal(r.status,200,JSON.stringify(r.data));return r.data;};
 const fresh=async r=>(await view('fixture-manager')).records.find(x=>x.id===(r.recordId??r.id));
 const command=async(actor,action,input={},r)=>fresh(ok(await call(actor,action,input,r)));
 const duty=confirmedDutiesForLocation('rudds').find(r=>r.id==='server-shared'),local=confirmedDutiesForLocation('rudds').find(r=>r.id==='server-rudds-side-work');
 assert.ok(duty);assert.match(local.closing.join(' '),/no salad bar/);assert.deepEqual(duty,confirmedDutiesForLocation('berts').find(r=>r.id==='server-shared'));
 const guide={purpose:'Fictional Server week practice, from the owner-confirmed reference.',preparation:[...duty.opening],steps:[...duty.service,...duty.closing,...local.closing],troubleshooting:['Fixture only: ask the assigned manager for unresolved side work.'],escalation:'Fixture manager checks side work and settles bank before release; no cash amounts captured.'};
 const standardInput={title:'Fixture Server service and side work',zone:'Fixture Server section',position:'Server',criteria:['Bag silverware and complete assigned section cleanup.'],version:1,verification:'manager',source:'Owner-confirmed reference 2026-10-07; isolated fictional software approval.',guide};
 let standard=await command('fixture-manager','standard.save',standardInput);standard=await command('fixture-manager','standard.approve',{validated:true,note:'Fictional simulation only; no real approval.'},standard);
 const shifts=[],closes=[];
 for(let n=1;n<=7;n++){
  await command('fixture-manager','leadership.assign',{personId:'fixture-manager',area:'FOH',start:at(n,17),end:at(n,23),note:'Fictional named manager'});
  let s=await command('fixture-manager','shift.save',{personId:'fixture-server',position:'Server',start:at(n,18),end:at(n,22)});
  closes.push(await command('fixture-manager','close.assign',{shiftId:s.id,standardId:standard.id,managerId:'fixture-manager',due:at(n,22)}));
  s=await command('fixture-manager','shift.publish',{},s);shifts.push(s);
 }
 const begin=n=>{clock=at(n);day={day:n,businessDate:clock.slice(0,10),actions:[]};evidence.days.push(day);};
 const projections=async(actor='fixture-server')=>{const w=await view(actor);evidence.counts.projections+=4;return {w,work:myWork(w,clock),brief:buildShiftBrief(w,clock),home:buildRoleHome(w,'frontline',new Date(clock)),context:workforceContext(w,'What is my shift and remaining work?',clock)};};
 const ready=async(n,actor='fixture-server')=>{closes[n-1]=await command(actor,'close.transition',{step:'ready',answers:[0],note:'Fixture reports silverware and section ready.'},await fresh(closes[n-1]));return closes[n-1];};
 const finish=async(n,actor='fixture-server',releaseNote='Fixture manager physical check and bank reviewed manually.')=>{await ready(n,actor);closes[n-1]=await command('fixture-manager','close.transition',{step:'confirm',note:'Fixture independent physical check passed.'},closes[n-1]);shifts[n-1]=await command('fixture-manager','shift.release',{note:releaseNote},await fresh(shifts[n-1]));};

 begin(1);let p=await projections();assert.equal(p.work.shift.id,shifts[0].id);assert.equal(p.brief.current.id,shifts[0].id);assert.equal(p.context.context.myShift.status,'currently scheduled');assert.ok(p.work.guides.some(g=>g.id===standard.id));assert.match(p.work.guides[0].data.guide.steps.join(' '),/Welcome guests warmly.*two bites.*Bag silverware/);
 log('Arrival: published shift, approved service reference, no salad bar','Current Server shift and warm steps of service',`Current ${p.work.shift.id}, ${p.work.guides.length} approved guide; Rudd exception retained.`);
 let rejected=await call('fixture-server','close.transition',{step:'ready',answers:[],note:'Incomplete'},closes[0]);assert.equal(rejected.status,400);log('Report incomplete side work','Reject until every condition checked',rejected);
 await ready(1);assert.equal((await call('fixture-server','close.transition',{step:'confirm',note:'Self approve'},closes[0])).status,403);assert.equal((await call('fixture-unassigned','close.transition',{step:'confirm',note:'Wrong manager'},closes[0])).status,403);
 closes[0]=await command('fixture-manager','close.transition',{step:'fix',note:'Fixture silverware bag is missing.'},closes[0]);assert.match((await projections()).work.duties[0].next,/Correct/);await finish(1);assert.ok((await fresh(shifts[0])).data.releasedAt);log('Manager returns correction, employee retries, independent check and release','Correction remains open; self and wrong-manager checks reject', 'Correction → ready → manager confirmation → released; two unauthorized confirmations rejected.');

 begin(2);let carried=await command('fixture-manager','task.create',{ownerId:'fixture-server',kind:'task',title:'Fixture tea station restock',detail:'Fixture restock silverware and cups before next shift.',due:at(2,22)});
 await ready(2);clock=at(2,23);p=await projections();assert.equal(p.work.checkoutPending,true);assert.ok(p.work.duties.some(i=>i.record.id===carried.id));assert.equal((await call('fixture-manager','shift.release',{note:'Too early'},shifts[1])).status,400);
 const hasClose=p.context.evidence.some(e=>e.source?.id===closes[1].id)||p.context.scope.some(s=>s.id===closes[1].id);assert.equal(hasClose,true);assert.equal(JSON.stringify(p.context).includes(carried.data.detail),false);
 log('End shift with manager check and separate assignment pending','Both persist without employee self-release',`My day checkoutPending=true, task ${carried.id} remains open; early release rejected.`);
 const selectedContext=workforceContext(p.w,'What remains before I leave?',clock,[],{id:shifts[1].id,revision:shifts[1].revision}),legacyContext=companionContext(p.w,'What remains before I leave?',clock);evidence.counts.projections+=2;
 assert.equal(selectedContext.scope.some(s=>s.id===closes[1].id),true);assert.equal(selectedContext.scope.some(s=>s.id===carried.id),false);assert.ok(legacyContext.scope.some(s=>s.id===closes[1].id));assert.ok(legacyContext.scope.some(s=>s.id===carried.id));
 log('Compare general, selected-shift and underlying legacy context','Actual linked closing evidence is available; unrelated task remains outside focused checkout',{generalCheckoutStatus:p.context.context.myShift.status,generalCloseEvidence:true,selectedShiftCloseEvidence:true,unrelatedTaskExcluded:true,legacyCloseEvidence:true,legacyTaskEvidence:true});
 gap('SERVER-WORKFORCE-PARKED-PENDING-WORK','Resolved: general closing questions and selected-shift context now include actual linked closing work. Unrelated tasks remain excluded from focused shift checkout.','app/shared/workforce-context.ts; app/shared/shift-context.ts','Day 2: saved close in manager-confirmation and unrelated tea-station task open; compare My day, general workforceContext, selected-shift workforceContext and legacy companionContext.',{category:'resolved',myDayClose:closes[1].id,myDayTask:carried.id,generalCloseSource:true,selectedShiftCloseSource:true,unrelatedTaskExcluded:true,scope:p.context.scope.map(s=>s.kind)});

 begin(3);clock=at(3,15);p=await projections();assert.equal(p.work.shift.id,shifts[1].id);assert.equal(p.work.checkoutPending,true);const shiftRow=p.home.attention.find(i=>i.source.recordId===shifts[1].id&&i.what==='Server');assert.match(shiftRow.why,/scheduled shift has ended/);assert.doesNotMatch(shiftRow.why,/next published assignment/);
 log('Next-day reopen after overnight waiting checkout','Yesterday remains reachable and correctly identified as ended',`Yesterday ${p.work.shift.id} and task persisted; role home correctly describes ended shift and pending checkout.`);
 gap('SERVER-HOME-ENDED-SHIFT-LABEL','Resolved: frontline home now labels an ended shift awaiting checkout accurately.','app/shared/role-home.ts:73','Day 3 before arrival: My day selects yesterday with checkoutPending=true; inspect Server home assignment why.',{category:'resolved',checkoutPending:p.work.checkoutPending,endedShift:shifts[1].data.end,at:clock,homeWhy:shiftRow.why});
 closes[1]=await command('fixture-manager','close.transition',{step:'confirm',note:'Fixture next-day physical side-work check.'},await fresh(closes[1]));shifts[1]=await command('fixture-manager','shift.release',{note:'Fixture delayed release after manual bank settlement.'},shifts[1]);
 carried=await command('fixture-server','task.transition',{step:'ready',note:'Fixture supplies restocked.'},carried);carried=await command('fixture-manager','task.transition',{step:'verify',note:'Fixture restock checked.'},carried);clock=at(3);await finish(3);log('Finish prior work and new day','Independent manager completion; task history survives',`Old checkout released; task phase=${carried.data.phase}; day 3 released.`);

 begin(4);const swapInput={type:'swap',start:shifts[4].data.start,end:shifts[4].data.end,shiftId:shifts[4].id,replacementId:'fixture-coworker',note:'Fixture personal appointment.'};let swap=await command('fixture-server','request.create',swapInput);swap=await command('fixture-coworker','request.consent',{accept:false},swap);assert.equal((await fresh(shifts[4])).ownerId,'fixture-server');swap=await command('fixture-server','request.create',swapInput);swap=await command('fixture-coworker','request.consent',{accept:true},swap);assert.equal((await fresh(shifts[4])).ownerId,'fixture-server');assert.equal((await call('fixture-server','request.review',{approve:true,note:'Self review'},swap)).status,403);swap=await command('fixture-manager','request.review',{approve:true,note:'Fixture named leader reviewed inherited duties.'},swap);assert.equal((await fresh(shifts[4])).ownerId,'fixture-coworker');assert.equal((await fresh(closes[4])).ownerId,'fixture-coworker');
 log('Day 5 coverage declined, retried and approved','Schedule remains authoritative until independent manager review','Decline keeps owner; replacement consent keeps owner; manager transfers shift and side work together.');
 const old=await fresh(closes[3]),requestId='fixture-server-ready-retry';const first=ok(await call('fixture-server','close.transition',{step:'ready',answers:[0],note:'Fixture checked.'},old,requestId));assert.deepEqual(ok(await call('fixture-server','close.transition',{step:'ready',answers:[0],note:'Fixture checked.'},old,requestId)),first);assert.equal((await call('fixture-server','close.transition',{step:'ready',answers:[0],note:'Stale extra tap'},old)).status,409);closes[3]=await fresh(old);closes[3]=await command('fixture-manager','close.transition',{step:'confirm',note:'Fixture check passed.'},closes[3]);shifts[3]=await command('fixture-manager','shift.release',{note:'Fixture physical side work and bank reviewed.'},shifts[3]);log('Network retry and stale tap','Idempotent replay; reject stale revision','Exact request replay returned original result, extra stale command rejected 409, checkout released once.');

 begin(5);p=await projections();assert.notEqual(p.work.shift?.id,shifts[4].id);const coworker=await projections('fixture-coworker');assert.equal(coworker.work.shift.id,shifts[4].id);assert.equal(coworker.work.duties.some(i=>i.record.id===closes[4].id),true);await finish(5,'fixture-coworker');log('Reopen after approved swap','Original Server does not own covered work; coworker inherits open close',`Original focus ${p.work.shift?.id}; replacement ${coworker.work.shift.id} completed inherited side work and checkout.`);

 begin(6);standard=await command('fixture-manager','standard.retire',{note:'Fixture version replacement test.'},standard);rejected=await call('fixture-server','close.transition',{step:'ready',answers:[0],note:'Old guide'},closes[5]);assert.equal(rejected.status,400);p=await projections();assert.match(p.work.duties.find(i=>i.record.id===closes[5].id).reason,/no longer approved/);let newer=await command('fixture-manager','standard.save',{...standardInput,version:2,basedOnId:standard.id,basedOnRevision:standard.revision});newer=await command('fixture-manager','standard.approve',{validated:true,note:'Fictional updated review only.'},newer);closes[5]=await command('fixture-manager','close.assign',{shiftId:shifts[5].id,standardId:newer.id,managerId:'fixture-manager',due:at(6,22),note:'Fixture current guide replacement.'},closes[5]);await finish(6);log('Retired guide blocks work until current approved guide reassigned','No silently continued obsolete instructions','Old ready rejected 400; My day warned; manager approved v2, reassigned close, independent checkout completed.');
 // The remaining day 7 close also needs the current version; explicit reassignment proves the workflow.
 closes[6]=await command('fixture-manager','close.assign',{shiftId:shifts[6].id,standardId:newer.id,managerId:'fixture-manager',due:at(7,22),note:'Fixture day 7 current guide.'},closes[6]);

 begin(7);let extra=await command('fixture-manager','task.create',{ownerId:'fixture-server',kind:'task',shiftId:shifts[6].id,title:'Fixture additional bagged silverware side work',detail:'Fixture manager explicitly assigned extra silverware for this shift; remains unfinished.',due:at(7,22)});
 await ready(7);closes[6]=await command('fixture-manager','close.transition',{step:'confirm',note:'Fixture named close passed.'},closes[6]);rejected=await call('fixture-manager','shift.release',{note:'Too early: linked silverware unfinished.'},shifts[6]);assert.equal(rejected.status,400);p=await projections();assert.ok(p.work.duties.some(i=>i.record.id===extra.id));assert.match(p.work.duties.find(i=>i.record.id===shifts[6].id).next,/Closing work remains/);
 extra=await command('fixture-server','task.transition',{step:'ready',note:'Fixture silverware now bagged.'},extra);assert.equal((await call('fixture-manager','shift.release',{note:'Readiness alone is not completion.'},shifts[6])).status,400);extra=await command('fixture-manager','task.transition',{step:'verify',note:'Fixture actual side-work check passed.'},extra);shifts[6]=await command('fixture-manager','shift.release',{note:'Done'},shifts[6]);p=await projections();assert.ok(shifts[6].data.releasedAt);assert.equal((await fresh(extra)).data.phase,'closed');assert.equal(p.work.duties.some(i=>i.record.id===extra.id),false);
 log('Release requires verified silverware work explicitly linked to this shift','Linked side work blocks release until independently verified','Open linked work rejected release; reported-ready work still rejected release; physical verification closed work and manager release succeeded.');
 gap('SERVER-RELEASE-IGNORES-SEPARATE-SIDEWORK','Resolved: side work explicitly linked by Task.shiftId now blocks checkout until its workflow closes. General unrelated tasks do not block checkout.','app/shared/closing-status.ts:5; app/shared/domain.ts:1122','Day 7: task.create linked silverware; close ready/confirm; release rejected; linked task ready still rejects; independent task verify permits manager release.',{category:'resolved',shiftReleased:shifts[6].data.releasedAt,task:extra.id,taskPhase:extra.data.phase,releaseBlockedWhileOpen:true,releaseBlockedWhileReady:true});
 gap('SERVER-BANK-MANUAL-ONLY','Confirmed reference requires manager bank settlement, but release stores only free-form confirmation; no dedicated bank settlement state or POS reconciliation proves that check. This is an unimplemented structured verification, not a credentials failure.','app/shared/starter-tasks.ts:12; app/shared/domain.ts:1124','Day 7: physically confirmed close then manager shift.release with note Done; inspect stored shift fields.',{category:'unimplemented-structured-verification',releaseNote:(await fresh(shifts[6])).data.history.at(-1).note,fields:Object.keys((await fresh(shifts[6])).data),bankOrPaymentRecord:false});
 assert.equal(evidence.days.length,7);const persisted=await view('fixture-manager');assert.equal(persisted.records.filter(r=>r.kind==='shift'&&r.data.releasedAt).length,7);assert.equal(persisted.records.some(r=>/cash|payment|payroll/.test(r.kind)),false);evidence.counts.completedShifts=7;evidence.counts.days=7;evidence.counts.implementedGaps=0;evidence.counts.resolvedGaps=3;evidence.counts.intentionalScopeLimitations=0;evidence.counts.unimplementedStructuredVerification=1;evidence.counts.assertions='Meaningful handler/projection assertions across all seven days; exact numeric assertion count not instrumented.';
});
