import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {Miniflare} from 'miniflare';
import {handleWorkspaceSetup} from '../.sites-runtime/shared/workspace-setup.mjs';
import {handleWorkspace} from '../.sites-runtime/shared/service.mjs';
process.env.MINIFLARE_REGISTRY_PATH??=path.resolve('.wrangler/registry');
const plan={locationId:'fictional-restaurant',name:'Fictional restaurant',timezone:'America/New_York',ownerEmail:'owner@example.test',ownerName:'Fictional owner'};
const config={JMAX_INITIAL_WORKSPACE:JSON.stringify(plan)};
async function fixture(t){const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("test")}}',compatibilityDate:'2026-05-22',d1Databases:['DB']});t.after(()=>mf.dispose());const db=await mf.getD1Database('DB');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())await db.batch(fs.readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint').filter(s=>s.trim()).map(s=>db.prepare(s)));const headers={'oai-authenticated-user-email':plan.ownerEmail,'oai-authenticated-user-id':'real-owner-identity',Origin:'https://test.example','Content-Type':'application/json'};const call=async(body,options={})=>{const h={...headers,...options.headers};for(const k of Object.keys(h))if(h[k]===null)delete h[k];const r=await handleWorkspaceSetup(new Request('https://test.example/api/setup',{method:options.method??(body?'POST':'GET'),headers:h,...(body?{body:JSON.stringify(body)}:{})}),options.db??db,options.config??config);return {status:r.status,data:await r.json()}};return {db,call,headers}}
const submit={confirmed:true,plan};
test('setup requires designated owner and stable verified identity, and GET never creates records',async t=>{const f=await fixture(t);assert.equal((await f.call(null,{config:{JMAX_REVIEW_OWNER_EMAIL:plan.ownerEmail}})).status,404);assert.equal((await f.call(null,{headers:{'oai-authenticated-user-id':null}})).status,401);assert.equal((await f.call(submit,{headers:{'oai-authenticated-user-email':'employee@example.test'}})).status,403);assert.equal((await f.call()).data.complete,false);assert.equal((await f.db.prepare('SELECT COUNT(*) n FROM locations').first()).n,0)});
test('owner setup is atomic and idempotent, preserving fictional review and giving no station clearance',async t=>{const f=await fixture(t);await f.db.prepare("INSERT INTO locations(id,name,timezone) VALUES('owner-review','Review','America/New_York')").run();const results=await Promise.all([f.call(submit),f.call(submit)]);assert.ok(results.every(r=>r.status===200&&r.data.complete));assert.equal((await f.db.prepare('SELECT COUNT(*) n FROM memberships').first()).n,1);assert.equal((await f.db.prepare('SELECT COUNT(*) n FROM audit_events').first()).n,1);assert.equal((await f.db.prepare('SELECT COUNT(*) n FROM locations').first()).n,2);const m=await f.db.prepare('SELECT * FROM memberships').first();assert.equal(m.auth_user_id,'real-owner-identity');assert.deepEqual(JSON.parse(m.qualifications),[]);assert.ok(JSON.parse(m.capabilities).includes('location.manage'));assert.equal((await f.call(submit)).status,200);const response=await handleWorkspace(new Request('https://test.example/api/workspace?locationId='+plan.locationId,{headers:f.headers}),f.db);assert.equal(response.status,200);const w=await response.json();assert.equal(w.location.name,plan.name);assert.deepEqual(w.records,[]);assert.equal(w.members.length,1)});
test('setup rejects stale plans, browser-selected authority, cross-site requests and unreviewed writes',async t=>{const f=await fixture(t);assert.equal((await f.call({confirmed:false,plan})).status,400);assert.equal((await f.call({...submit,capabilities:['location.manage']})).status,400);assert.equal((await f.call({confirmed:true,plan:{...plan,locationId:'owner-review'}})).status,409);assert.equal((await f.call(submit,{headers:{Origin:'https://attacker.test'}})).status,403);assert.equal((await f.call(submit,{headers:{'Sec-Fetch-Site':'cross-site'}})).status,403);assert.equal((await f.call(submit,{headers:{'Content-Type':'text/plain'}})).status,415);assert.equal((await f.db.prepare('SELECT COUNT(*) n FROM locations').first()).n,0)});
test('setup cannot take over existing restaurants or restore a suspended owner',async t=>{const f=await fixture(t);await f.db.prepare('INSERT INTO locations(id,name,timezone) VALUES(?,?,?)').bind(plan.locationId,'Existing restaurant',plan.timezone).run();assert.equal((await f.call(submit)).status,409);assert.equal((await f.db.prepare('SELECT COUNT(*) n FROM memberships').first()).n,0);const g=await fixture(t);assert.equal((await g.call(submit)).status,200);await g.db.prepare('UPDATE memberships SET active=0').run();assert.equal((await g.call(submit)).status,409);assert.equal((await g.db.prepare('SELECT active FROM memberships').first()).active,0)});
test('setup cannot rebind an established owner to a new identity or restore revoked setup authority',async t=>{const f=await fixture(t);await f.call(submit);assert.equal((await f.call(submit,{headers:{'oai-authenticated-user-id':'different-identity'}})).status,409);await f.db.prepare("UPDATE memberships SET capabilities='[]'").run();assert.equal((await f.call(submit)).status,409);assert.equal((await f.db.prepare('SELECT capabilities FROM memberships').first()).capabilities,'[]')});
test('failed audit insertion rolls back restaurant and owner creation together',async t=>{const f=await fixture(t);await f.db.prepare("CREATE TRIGGER fail_setup BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT,'test audit failure'); END").run();assert.equal((await f.call(submit)).status,503);assert.equal((await f.db.prepare('SELECT COUNT(*) n FROM locations').first()).n,0);assert.equal((await f.db.prepare('SELECT COUNT(*) n FROM memberships').first()).n,0);await f.db.prepare('DROP TRIGGER fail_setup').run();assert.equal((await f.call(submit)).status,200)});
