'use client';
import {useState} from 'react';
import type {CateringMenuLine} from '../shared/catering-menu';
export function MenuLineFields({initial=[]}:{initial?:CateringMenuLine[]}){
 const [rows,setRows]=useState(()=>initial.map((line,key)=>({...line,key}))),[next,setNext]=useState(initial.length);
 return <fieldset><legend>Menu quantities</legend><p>Optional structured quantities for this event. Keep each recorded unit explicit. No price, recipe conversion or stock reservation is calculated.</p>{rows.map((row,i)=><div className="ops-card" key={row.key}><h3>Menu line {i+1}</h3><input type="hidden" name="menuLine" value={row.key}/><label className="shared-field">Item {i+1}<input name={'menuItem'+row.key} required maxLength={200} defaultValue={row.item}/></label><div className="ops-fields"><label className="shared-field">Quantity {i+1}<input name={'menuQuantity'+row.key} type="number" required min="0.001" max="100000" step="0.001" defaultValue={row.quantity||''}/></label><label className="shared-field">Unit {i+1}<input name={'menuUnit'+row.key} required maxLength={40} defaultValue={row.unit} placeholder="e.g. trays or portions"/></label></div><label className="shared-field">Item reference {i+1}<input name={'menuReference'+row.key} maxLength={500} defaultValue={row.reference}/></label><label className="shared-field">Item notes {i+1}<textarea name={'menuNotes'+row.key} maxLength={500} defaultValue={row.notes}/></label><button type="button" onClick={()=>setRows(rows.filter(r=>r.key!==row.key))}>Remove menu line {i+1}</button></div>)}{!rows.length&&<p>No structured menu quantities recorded. A printed sheet will flag this gap.</p>}<button type="button" disabled={rows.length>=40} onClick={()=>{setRows([...rows,{key:next,item:'',quantity:0,unit:'',reference:'',notes:''}]);setNext(next+1)}}>Add menu line</button></fieldset>;
}
export function readMenuLines(f:FormData){return f.getAll('menuLine').map(key=>({item:f.get('menuItem'+key),quantity:Number(f.get('menuQuantity'+key)),unit:f.get('menuUnit'+key),reference:f.get('menuReference'+key),notes:f.get('menuNotes'+key)}));}
export function MenuLines({lines=[]}:{lines?:CateringMenuLine[]}){
 return <section><h3>Menu quantities</h3>{lines.length?<ol>{lines.map((l,i)=><li key={i}><strong>{l.item}</strong> · {l.quantity} {l.unit}{l.reference&&<p className="ops-preserve">Reference: {l.reference}</p>}{l.notes&&<p className="ops-preserve">{l.notes}</p>}</li>)}</ol>:<p>Structured menu quantities are not recorded in this version. Confirm them before preparation.</p>}</section>;
}
