'use client';
import {useState,type FormEvent} from 'react';
import {cateringOwner,cateringManager,cateringParticipant,cateringEditor,cateringReader,cateringView,cateringPhase,cateringNeedsRead,cateringNoticeKey,cateringOnDate,type Catering,type CateringFacts} from '../shared/catering';
import {personName,type Workspace,type RecordOf} from '../shared/types';
import {displayTime,localDate,localClock} from '../shared/local-time';
import type {Send} from './workspace';
import './operations.css';
import {MenuLineFields,MenuLines,readMenuLines} from './catering-menu';
const labels={draft:'Draft · not published',review:'Awaiting owner review','update-pending':'Changed · update awaiting review',upcoming:'Upcoming event','in-progress':'Event time in progress',ended:'Event ended · outcome not recorded',cancelled:'Cancelled internal brief',completed:'Completion reported'};
type Props={w:Workspace;send:Send;busy:boolean;now:string};
function Fields({w,d,now}:{w:Workspace;d?:Catering;now:string}){
 const managers=w.members.filter(m=>cateringManager(m)&&(cateringOwner(w.me)||m.id===w.me.id));
 return <><label className="shared-field">Event title<input name="title" defaultValue={d?.title} required maxLength={200}/></label>
  {(['start','end'] as const).map(side=><div key={side} className="ops-fields"><label className="shared-field">{side==='start'?'Start date':'End date'}<input type="date" name={side+'Date'} required defaultValue={d?localDate(d[side],w.location.timezone):localDate(now,w.location.timezone)}/></label><label className="shared-field">{side==='start'?'Start time':'End time'}<input type="time" name={side+'Time'} required defaultValue={d?localClock(d[side],w.location.timezone):''}/></label><label className="shared-field">{side==='start'?'Start':'End'} occurrence if clocks repeat<select name={side+'Occurrence'} defaultValue=""><option value="">Choose only if this hour repeats</option><option value="earlier">First occurrence</option><option value="later">Second occurrence</option></select></label></div>)}
  <p className="shared-muted">Times follow {w.location.timezone}. Events may span up to seven days. If an hour repeats during a clock change, choose its occurrence.</p>
  <div className="ops-fields"><label className="shared-field">Service location or pickup point<input name="venue" required maxLength={500} defaultValue={d?.venue}/></label><label className="shared-field">Guest count<input name="guests" type="number" min="1" max="10000" step="1" required defaultValue={d?.guests}/></label></div>
  {([['menuRef','Menu or order reference',1500],['menuNotes','Menu and service details',3000],['prepNotes','Preparation requirements',3000],['staffingNotes','Staffing requirements',3000]] as const).map(([key,title,max])=><label key={key} className="shared-field">{title}<textarea name={key} maxLength={max} required defaultValue={d?.[key]}/></label>)}
  <MenuLineFields initial={d?.menuLines}/>
  <p className="shared-muted">Record the checked requirements and any unresolved details. These notes do not create a prep list, assign a shift or reserve stock.</p>
  <fieldset><legend>Staff briefing audience</legend>{(['FOH','BOH'] as const).map(a=><label className="ops-check" key={a}><input type="checkbox" name="audience" value={a} defaultChecked={d?.audience.includes(a)}/>{a}</label>)}</fieldset>
  <label className="shared-field">Responsible manager<select name="managerId" defaultValue={d?.managerId??(cateringOwner(w.me)?'':w.me.id)} required><option value="">Choose manager</option>{d&&!managers.some(m=>m.id===d.managerId)&&<option value={d.managerId} disabled>{d.managerName} · no longer available</option>}{managers.map(m=><option key={m.id} value={m.id}>{m.name} · {m.area}</option>)}</select></label>
  <label className="shared-field">Private booking reference<input name="bookingRef" required maxLength={200} defaultValue={d?.internal?.bookingRef}/></label><label className="shared-field">Private planning source<textarea name="sourceRef" required maxLength={2000} defaultValue={d?.internal?.sourceRef}/></label><p className="shared-muted">Use a document or booking reference. Keep card details and passwords out of this record. Booking references and planning history stay with the assigned manager and restaurant owners.</p>
 </>;
}
const readFields=(f:FormData)=>({...Object.fromEntries(['title','startDate','startTime','startOccurrence','endDate','endTime','endOccurrence','venue','menuRef','menuNotes','prepNotes','staffingNotes','managerId','sourceRef','bookingRef'].map(k=>[k,f.get(k)])),guests:Number(f.get('guests')),audience:f.getAll('audience'),menuLines:readMenuLines(f)});
function Facts({d,w}:{d:CateringFacts;w:Workspace}){return <><p>{displayTime(d.start,w.location.timezone)} through {displayTime(d.end,w.location.timezone)}</p><p>{d.venue} · {d.guests} guests · {d.audience.join(' / ')}</p><p>Responsible manager: {d.managerName}</p><MenuLines lines={d.menuLines}/>{([['menuRef','Menu or order reference'],['menuNotes','Menu and service details'],['prepNotes','Preparation requirements'],['staffingNotes','Staffing requirements']] as const).map(([key,label])=><div key={key}><h3>{label}</h3><p className="ops-preserve" style={{overflowWrap:'anywhere'}}>{d[key]}</p></div>)}</>}
export function CateringCalendar({w,send,busy,now,onHistory}:Props&{onHistory:()=>void}){
 const [creating,setCreating]=useState(false),[selected,setSelected]=useState(''),[filter,setFilter]=useState('current'),[day,setDay]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(0);
 if(!cateringParticipant(w.me))return null;
 const records=w.records.filter((r):r is RecordOf<'catering'>=>r.kind==='catering'&&cateringReader(r,w.me)).map(r=>cateringView(r,w.me)),current=records.find(r=>r.id===selected);
 const rows=records.filter(r=>{const phase=cateringPhase(r.data,now);return (filter==='all'||filter==='planning'&&['draft','review','update-pending'].includes(phase)||filter==='current'&&['upcoming','in-progress','update-pending','cancelled'].includes(phase)||filter==='past'&&['ended','completed'].includes(phase))&&(!day||cateringOnDate(r.data,day,w.location.timezone))&&r.data.title.toLowerCase().includes(query.trim().toLowerCase())}).sort((a,b)=>a.data.start.localeCompare(b.data.start)||a.id.localeCompare(b.id));
 const pages=Math.max(1,Math.ceil(rows.length/20)),currentPage=Math.min(page,pages-1);
 return <section className="ops-page"><div className="shared-heading"><div><p className="ops-eyebrow">{w.location.name} · Guests</p><h1>Catering calendar</h1></div>{cateringManager(w.me)&&<button disabled={busy} onClick={()=>{setCreating(!creating);setSelected('')}}>{creating?'Cancel new event':'Plan an event'}</button>}</div>
  <p>Internal event briefs use {w.location.timezone}. An owner reviews the exact details before staff can read them.</p><p className="ops-callout">This calendar does not place customer or supplier orders, take deposits, reserve stock, publish schedules or send notifications. Preparation and staffing still require follow-through in their own work areas.</p>
  {creating&&<form className="ops-card" onSubmit={async e=>{e.preventDefault();if(await send('catering.create',readFields(new FormData(e.currentTarget)))){setCreating(false);setFilter('planning');setPage(0)}}}><h2>New event draft</h2><fieldset disabled={busy}><Fields w={w} now={now}/><button className="shared-primary">Save event draft</button></fieldset></form>}
  {current?<><button onClick={()=>setSelected('')}>Back to catering calendar</button><CateringCard key={current.id+':'+current.revision} r={current} w={w} send={send} busy={busy} now={now}/></>:<>
   <div className="ops-filters">{[['current','Current and upcoming'],['planning','Drafts and owner review'],['past','Ended and completed'],['all','All events']].filter(([key])=>key!=='planning'||cateringManager(w.me)).map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>{setFilter(key);setPage(0)}}>{label}</button>)}</div>
   <div className="ops-fields"><label className="shared-field">Event on restaurant date<input type="date" value={day} onChange={e=>{setDay(e.target.value);setPage(0)}}/></label><label className="shared-field">Find event title<input value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label></div>
   <p>{rows.length} matching events. Date filters include events continuing overnight.</p><div className="shared-list">{rows.slice(currentPage*20,currentPage*20+20).map(r=><button key={r.id} onClick={()=>{setSelected(r.id);setCreating(false)}} aria-label={'Open '+r.data.title}><span><strong>{r.data.title}</strong><small>{displayTime(r.data.start,w.location.timezone)} · {r.data.guests} guests</small></span><em>{labels[cateringPhase(r.data,now)]}{cateringNeedsRead(r,w.me)?' · Unread notice':''}</em></button>)}</div>{!rows.length&&<p>No events in this view.</p>}{pages>1&&<div className="shared-actions"><button disabled={!currentPage} onClick={()=>setPage(currentPage-1)}>Previous page</button><span>Page {currentPage+1} of {pages}</span><button disabled={currentPage+1===pages} onClick={()=>setPage(currentPage+1)}>Next page</button></div>}
  </>}<p><button onClick={onHistory}>Work history</button></p>
 </section>;
}
export function CateringCard({w,r:source,send,busy,now,readOnly=false}:Props&{r:RecordOf<'catering'>;readOnly?:boolean}){
 if(!cateringReader(source,w.me))return null;
 const r=cateringView(source,w.me),d=r.data,editor=!!d.internal&&cateringEditor(r,w.me),owner=cateringOwner(w.me),phase=cateringPhase(d,now);
 const act=async(e:FormEvent<HTMLFormElement>,action:string)=>{e.preventDefault();const f=new FormData(e.currentTarget);await send('catering.'+action,{note:f.get('note'),summary:f.get('summary'),outcomeSource:f.get('outcomeSource'),checked:f.get('confirmed')==='on',confirmed:f.get('confirmed')==='on'},r)};
 const actionForm=(action:string,title:string,confirmation:string,extra?:React.ReactNode)=><form onSubmit={e=>void act(e,action)}><fieldset disabled={busy}><label className="shared-field">{title} · private reason<textarea name="note" required maxLength={3000}/></label>{extra}<label className="ops-check"><input type="checkbox" name="confirmed" required/>{confirmation}</label><button className="shared-primary">{title}</button></fieldset></form>;
 return <article className="ops-card"><h2>{d.title}</h2><p>{labels[phase]} · version {d.version}{readOnly?' · Filed history':''}</p>
  {phase==='update-pending'&&<p className="ops-callout">This event changed and its update is awaiting owner review. {editor?'The current draft is below.':'The previous published brief is below; its details are no longer current.'} Check with the responsible manager before preparing for this event.</p>}
  {d.notice&&<p className="ops-callout">{d.status==='cancelled'?'Cancellation notice':'Reported event outcome'}: {d.notice.summary}</p>}
  <Facts d={d} w={w}/>
  {d.publication&&<p>Published version {d.publication.version} · {displayTime(d.publication.at,w.location.timezone)}. Reading a brief does not confirm preparation or staffing.</p>}
  {!readOnly&&d.publication&&<p><a href={'/api/operations/catering-sheet?'+new URLSearchParams({locationId:w.location.id,recordId:r.id,revision:String(r.revision)})} target="_blank" rel="noopener noreferrer">Open printable published sheet</a><br/><small>Uses the published version, with current warnings. Private planning notes are excluded. Saved and printed copies do not update.</small></p>}
  {!readOnly&&cateringNeedsRead(r,w.me)&&<form onSubmit={async e=>{e.preventDefault();await send('catering.acknowledge',{noticeKey:cateringNoticeKey(d),read:true},r)}}><fieldset disabled={busy}><label className="ops-check"><input type="checkbox" required/>I have read this brief and any change or cancellation notice.</label><button>Record my read receipt</button></fieldset></form>}
  {!readOnly&&d.publication&&!cateringNeedsRead(r,w.me)&&<p>You recorded reading this notice. This is not a completion confirmation.</p>}
  {editor&&d.internal&&<><details><summary>Private planning source</summary><p>{d.internal.bookingRef}</p><p className="ops-preserve">{d.internal.sourceRef}</p>{d.internal.outcomeSource&&<p>Completion evidence: {d.internal.outcomeSource}</p>}</details>
   {!readOnly&&<>
    {!['cancelled','completed'].includes(d.status)&&<details><summary>Revise event details</summary><p>A revision requires a new owner review. Staff keep a visible warning with the previous published brief until the new version is published.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await send('catering.revise',{...readFields(f),note:f.get('note')},r)}}><fieldset disabled={busy}><Fields w={w} d={d} now={now}/><label className="shared-field">Revision reason<textarea name="note" required maxLength={3000}/></label><button>Save revised draft</button></fieldset></form></details>}
    {d.status==='draft'&&actionForm('submit','Submit event for review','I checked the source, dates, menu, preparation and staffing notes.')}
    {d.status==='review'&&owner&&<>{actionForm('publish','Publish event brief','Publish this exact event brief. Orders, preparation and staffing completion remain separate.')}<details><summary>Return event for correction</summary>{actionForm('return','Return to draft','Return this brief to its assigned manager for correction.')}</details></>}
    {d.status==='published'&&Date.parse(now)>=Date.parse(d.end)&&<details><summary>Report event outcome</summary>{actionForm('complete','Save completion report','This describes the actual event outcome.',<><label className="shared-field">Event outcome for staff<textarea name="summary" required maxLength={2000}/></label><label className="shared-field">Private completion evidence<textarea name="outcomeSource" required maxLength={2000}/></label></>)}</details>}
    {owner&&!['cancelled','completed'].includes(d.status)&&<details><summary>Cancel internal event brief</summary>{actionForm('cancel','Cancel event brief','Cancel this internal brief. Customer and supplier arrangements must be handled separately.',<label className="shared-field">Staff cancellation notice<textarea name="summary" required maxLength={2000}/></label>)}</details>}
   </>}
   {d.publication&&phase==='update-pending'&&<details><summary>Previous published brief · no longer current</summary><Facts d={d.publication.facts} w={w}/></details>}
   <details><summary>Private event history and read receipts</summary><ol>{d.internal.history.map((h,i)=><li key={i}>{displayTime(h.at,w.location.timezone)} · {personName(w,h.actorId)} · {h.action}<p>{h.note}</p></li>)}</ol><p>These are recorded in-app read actions, not delivery receipts or completion confirmations.</p><ul>{d.acknowledgments.map((a,i)=><li key={i}>{personName(w,a.by)} · {displayTime(a.at,w.location.timezone)} · notice {a.noticeKey}</li>)}</ul>{d.internal.versions.map((v,i)=><details key={i}><summary>Earlier version {v.version} · {v.status}</summary><p>{v.reason}</p><Facts d={v.facts} w={w}/><p>Private source: {v.sourceRef} · booking {v.bookingRef}</p></details>)}</details>
  </>}
 </article>;
}
