'use client';
import {useState} from 'react';
import {personName,type Workspace,type RecordOf} from '../shared/types';
import {operationsManager} from '../shared/operations';
import {dishCheckoutCycleStatus} from '../shared/domain';
import {displayTime,localDate,localClock,localInstant} from '../shared/local-time';
import type {Send} from './workspace';

type Props={w:Workspace;send:Send;busy?:boolean;onOpen?:(r:RecordOf<'task'>)=>void};
function Person({w,name}:{w:Workspace;name:string}){return <select name={name} required><option value="">Choose Dishwasher</option>{w.members.filter(m=>m.position==='Dishwasher'&&m.area==='BOH'&&!m.scheduleOnly).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>}
function Deadline({w,initial}:{w:Workspace;initial?:string}){const [date]=useState(()=>initial??new Date(Date.now()+86400000).toISOString());return <div className="shared-grid"><label className="shared-field">Due date<input type="date" name="dueDate" defaultValue={localDate(date,w.location.timezone)} required/></label><label className="shared-field">Due time<input type="time" name="dueTime" defaultValue={localClock(date,w.location.timezone)} required/></label></div>}
const deadline=(f:FormData,w:Workspace)=>localInstant(String(f.get('dueDate')),String(f.get('dueTime')),w.location.timezone);
function status(r:RecordOf<'task'>){return r.data.phase==='closed'?'Manager validated':r.data.phase==='verification'?'Ready · manager validation needed':r.data.phase==='correction'?'Correction required':r.data.dishHandoff&&!r.data.dishHandoff.acceptedBy?'Incoming acknowledgment missing':'Work incomplete';}

export function DishCheckoutCycles({w,send,busy=false,onOpen}:Props){
 const [creating,setCreating]=useState(false),[error,setError]=useState('');
 const supplied=w.records.filter((r):r is RecordOf<'task'>=>r.kind==='task'&&!!r.data.dishCheckout);
 const records=supplied.filter(r=>Array.isArray(r.data.dishCheckout?.participantIds)&&r.data.dishCheckout.participantIds.length===3&&r.data.dishCheckout.participantIds.every(id=>typeof id==='string')&&typeof r.data.dishCheckout.cycleId==='string');
 const cycles=[...new Set(records.map(r=>r.data.dishCheckout!.cycleId))];
 const canCreate=operationsManager(w.me,'BOH');
 if(!canCreate&&!cycles.length&&!supplied.length)return null;
 return <section className="ops-card"><div className="shared-heading"><h2>Dishwasher shift checkouts</h2>{canCreate&&<button disabled={busy} onClick={()=>setCreating(!creating)}>Set up AM / PM checkouts</button>}</div><p>Each person has a separate checkout and manager validation. One completed checkout does not complete the other person’s work.</p>{error&&<p role="alert" className="shared-error">{error}</p>}
 {supplied.length!==records.length&&<p role="status" className="shared-error">A saved checkout has incomplete participant information. The station is not confirmed complete; ask the manager to review the original record.</p>}
 {creating&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setError('');try{const result=await send('task.dish-cycle',{amOwnerId:f.get('amOwnerId'),pmOwnerIds:[f.get('pm1'),f.get('pm2')],businessDate:f.get('businessDate'),title:f.get('title'),detail:f.get('detail'),due:deadline(f,w)});if(result)setCreating(false)}catch(err){setError(err instanceof Error?err.message:'Check the checkout assignments.')}}}><fieldset disabled={busy}><div className="shared-grid"><label className="shared-field">Restaurant business date<input name="businessDate" type="date" required defaultValue={localDate(new Date().toISOString(),w.location.timezone)}/></label><label className="shared-field">AM Dishwasher<Person w={w} name="amOwnerId"/></label><label className="shared-field">First PM Dishwasher<Person w={w} name="pm1"/></label><label className="shared-field">Second PM Dishwasher<Person w={w} name="pm2"/></label></div><label className="shared-field">Checkout title<input name="title" required maxLength={200} defaultValue="Dish station checkout"/></label><label className="shared-field">What must be checked before leaving<textarea name="detail" required maxLength={4000}/></label><Deadline w={w}/><button className="shared-primary">Create three separate checkouts</button></fieldset></form>}
 {cycles.map(id=>{const rows=records.filter(r=>r.data.dishCheckout!.cycleId===id),participantIds=rows[0].data.dishCheckout!.participantIds,day=rows[0].data.dishCheckout!.businessDate,cycle=dishCheckoutCycleStatus(w,id);return <article key={id} className="ops-card"><h3>{day} · AM and PM</h3>{participantIds.map((person,index)=>{if(!canCreate&&person!==w.me.id)return null;const task=rows.find(r=>r.ownerId===person);return <div className="ops-action" key={person}><span><strong>{index===0?'AM':`PM ${index}`} · {personName(w,person)}</strong><small>{task?status(task):'Checkout missing from your accessible records — not confirmed complete'}</small></span>{task&&onOpen&&<button onClick={()=>onOpen(task)}>Open checkout</button>}</div>})}{canCreate?<div><p>{rows.filter(r=>r.data.phase==='closed').length} of 3 checkouts manager validated. {cycle.complete?'All expected checkouts and linked incoming work are manager validated.':'Station incomplete: unfinished, missing, or unacknowledged work remains.'}</p>{cycle.unavailableHandoffIds.length>0&&<p className="shared-error">{cycle.unavailableHandoffIds.length} linked handoff record(s) cannot be confirmed.</p>}{cycle.pendingHandoffIds.map(childId=>{const child=w.records.find((item):item is RecordOf<'task'>=>item.id===childId&&item.kind==='task');return child?<div key={child.id}><p>{child.data.title} · {status(child)}</p>{onOpen&&<button onClick={()=>onOpen(child)}>Open incoming work</button>}</div>:null})}</div>:<p>This is your checkout only. Your manager checks the whole station; another person’s status is not inferred from your visible work.</p>}</article>})}
 </section>;
}

export function DishCheckoutDetail({r,w,send,onError,onOpen}:{r:RecordOf<'task'>;w:Workspace;send:Send;onError:(text:string)=>void;onOpen?:(r:RecordOf<'task'>)=>void}){
 const [passing,setPassing]=useState(false);
 const checkout=r.data.dishCheckout,handoff=r.data.dishHandoff;
 const manager=operationsManager(w.me,r.area),mine=r.ownerId===w.me.id;
 const source=handoff?w.records.find((item):item is RecordOf<'task'>=>item.id===handoff.sourceId&&item.kind==='task'):undefined;
 const childIds=[...new Set([...(Array.isArray(r.data.dishHandoffs)?r.data.dishHandoffs:[]),...(r.data.dishHandoffReceiptView===true?r.data.dishHandoffPendingIds??[]:[])])];
 const children=childIds.map(id=>w.records.find((item):item is RecordOf<'task'>=>item.id===id&&item.kind==='task'));
 const receipts=r.data.dishHandoffReceiptView===true?r.data.dishHandoffAcceptances??[]:[];
 const incoming=checkout?.shift==='PM'?w.records.filter((item):item is RecordOf<'task'>=>item.kind==='task'&&item.ownerId===r.ownerId&&item.data.dishHandoff?.cycleId===checkout.cycleId&&item.data.phase!=='closed'):[];
 const submit=async(e:React.FormEvent<HTMLFormElement>,action:string)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await send(action,{note:f.get('note'),...(action==='task.dish-pass'?{incomingId:f.get('incomingId'),due:deadline(f,w)}:{step:(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')})},r)}catch(err){onError(err instanceof Error?err.message:'The saved checkout changed; refresh and review it.')}};
 return <><p><strong>{checkout?`${checkout.shift} checkout`:'Unfinished work handoff'}</strong> · {checkout?.businessDate??handoff?.businessDate} · {status(r)}</p><p className="shared-message">{r.data.detail}</p><p>Assigned to {personName(w,r.ownerId)} · Due {displayTime(r.data.due,w.location.timezone)}</p>
 {handoff&&<article className="ops-card"><h3>Incoming acknowledgment</h3><p>{handoff.acceptedBy?`Acknowledged by ${personName(w,handoff.acceptedBy)}${handoff.acceptedAt?' · '+displayTime(handoff.acceptedAt,w.location.timezone):''}`:'The named incoming Dishwasher must acknowledge this work before reporting it ready.'}</p><p>{source?`From: ${source.data.title}`:'Original outgoing checkout is linked by its saved identity; its full detail is outside your accessible records.'}</p></article>}
 {!!children.length&&<article className="ops-card"><h3>Unfinished work passed forward</h3>{children.map((child,i)=><div key={childIds[i]}><p>{child?`${personName(w,child.ownerId)} · ${status(child)}`:receipts.some(a=>a.handoffId===childIds[i])?'Incoming responsibility acknowledged. The PM work details remain outside your view; acknowledgment does not complete that work.':'Incoming acknowledgment remains unconfirmed. Ask the manager to resolve the handoff before checkout.'}</p>{child&&onOpen&&<button onClick={()=>onOpen(child)}>Open incoming work</button>}</div>)}<p>Passing work forward does not validate this checkout or close a PM checkout.</p></article>}
 {!!incoming.length&&<article role="status" className="ops-card"><p className="shared-error">Incoming unfinished work still needs acknowledgment, completion, and manager validation before this PM checkout can be reported ready.</p>{incoming.map(child=><div key={child.id}><p>{child.data.title} · {status(child)}</p>{onOpen&&<button onClick={()=>onOpen(child)}>Open incoming work</button>}</div>)}</article>}
 {r.data.phase!=='closed'&&<form onSubmit={e=>void submit(e,'task.transition')}><label className="shared-field">Evidence, checks completed, or correction needed<textarea name="note" required maxLength={4000}/></label><div className="shared-actions">{mine&&handoff&&!handoff.acceptedBy&&<button value="accept" className="shared-primary">Acknowledge incoming work</button>}{mine&&['open','correction'].includes(r.data.phase)&&(!handoff||!!handoff.acceptedBy)&&<button value="ready" disabled={!!incoming.length} className="shared-primary">{handoff?'Incoming work ready for manager validation':'Checkout ready for manager validation'}</button>}{manager&&r.ownerId!==w.me.id&&r.data.phase==='verification'&&<button value="verify" className="shared-primary">{handoff?'Validate this incoming work':'Validate this checkout'}</button>}{manager&&<button value="fix">Return this work for correction</button>}</div></form>}
 {mine&&checkout?.shift==='AM'&&['open','correction'].includes(r.data.phase)&&<><button onClick={()=>setPassing(!passing)}>Pass unfinished work to incoming Dishwasher</button>{passing&&<form onSubmit={e=>void submit(e,'task.dish-pass')}><label className="shared-field">Incoming PM Dishwasher<select name="incomingId" required><option value="">Choose incoming person</option>{(Array.isArray(checkout.participantIds)?checkout.participantIds:[]).slice(1).filter(id=>id!==w.me.id).map(id=><option key={id} value={id}>{personName(w,id)}</option>)}</select></label><label className="shared-field">Unfinished work and next action<textarea name="note" required maxLength={4000}/></label><Deadline w={w} initial={r.data.due}/><button className="shared-primary">Save linked handoff for acknowledgment</button></form>}</>}
 </>;
}
