'use client';
import { useState, type ReactNode } from 'react';
import { personName, has, manages, type Workspace, type WorkRecord, type RecordOf } from '../shared/types';
import { displayTime, localDate, localClock, localInstant } from '../shared/local-time';
import { reviewDueState } from '../shared/followthrough';
import type { Send } from './workspace';
import { approvedStationGuides } from '../shared/station-knowledge';
import { StationGuideContent } from './station-knowledge';
import { learningNextStep } from '../shared/learning-queue';
import { LearningPath } from './learning-path';
import { ReviewSetup } from './review-setup';
import {reviewRatings,ratingLabel} from '../shared/personal-learning';
import {GuidedPractice} from './guided-practice';
import {LearningProgress} from './learning-progress';
import {DishCheckoutDetail} from './dish-checkouts';
import {shiftStationName} from '../shared/station-assignment';
import {canManageClosing} from '../shared/closing-access';

export type FollowKind='task'|'handoff'|'feedback'|'development'|'goal';
type Props={w:Workspace;send:Send;onError:(text:string)=>void};
const val=(f:FormData,name:string)=>String(f.get(name)??'');
function Field({label,children}:{label:string;children:ReactNode}){return <label className="shared-field">{label}{children}</label>}
function Form({children,submit,onError}: {children:ReactNode;submit:(f:FormData,action:string)=>Promise<unknown>;onError:Props['onError']}) {
  return <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),action=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')??'';try{await submit(f,action)}catch(error){onError(error instanceof Error?error.message:'Check the form.')}}}>{children}</form>;
}
function Note({label='Note',required=true,initial='',name='note',maxLength=4000}:{label?:string;required?:boolean;initial?:string;name?:string;maxLength?:number}){return <Field label={label}><textarea name={name} defaultValue={initial} required={required} maxLength={maxLength}/></Field>}
function People({w,name,initial='',eligible}:{w:Workspace;name:string;initial?:string;eligible:(m:Workspace['me'])=>boolean}){return <select name={name} defaultValue={initial} required><option value="">Choose a person</option>{w.members.filter(eligible).map(m=><option key={m.id} value={m.id}>{m.name} · {m.position}</option>)}</select>}
function Due({w,initial}:{w:Workspace;initial?:string}){
  const zone=w.location.timezone;
  const [defaultDue]=useState(()=>initial??new Date(Date.now()+24*60*60*1000).toISOString());
  return <><div className="shared-grid"><Field label="Due date"><input type="date" name="dueDate" defaultValue={localDate(defaultDue,zone)} required/></Field><Field label="Due time"><input type="time" name="dueTime" defaultValue={localClock(defaultDue,zone)} required/></Field></div><details><summary>Clock-change hour</summary><Field label="Repeated hour"><select name="repeated"><option value="">Choose only when the clock repeats</option><option value="earlier">First occurrence</option><option value="later">Second occurrence</option></select></Field></details></>;
}
const due=(f:FormData,w:Workspace)=>localInstant(val(f,'dueDate'),val(f,'dueTime'),w.location.timezone,val(f,'repeated'));
function History({r,w}:{r:WorkRecord;w:Workspace}){return 'history' in r.data&&r.data.history?.length?<details><summary>History</summary><ol className="shared-history">{r.data.history.map((h,i)=><li key={i}><strong>{h.action} · {personName(w,h.actorId,'Previous member')}</strong><span className="shared-message">{h.note}</span><small>{displayTime(h.at,w.location.timezone)}</small></li>)}</ol></details>:null}
function LeadershipSelect({w,name,own=false,initial,area=w.me.area,excludeIds=[],unexpired=false}:{w:Workspace;name:string;own?:boolean;initial?:string;area?:string;excludeIds?:string[];unexpired?:boolean}){return <select name={name} defaultValue={initial??''} required><option value="">Choose a scheduled leader</option>{w.records.filter((r):r is RecordOf<'leadership'>=>r.kind==='leadership'&&r.locationId===w.location.id&&r.data.active&&r.area===area&&(own?r.ownerId===w.me.id:r.ownerId!==w.me.id)&&!excludeIds.includes(r.ownerId)&&(!unexpired||Date.parse(r.data.end)>Date.now())&&w.members.some(m=>m.id===r.ownerId&&!m.scheduleOnly&&manages(m,r.area,'tasks.manage'))).map(r=><option value={r.id} key={r.id}>{personName(w,r.ownerId)} · {displayTime(r.data.start,w.location.timezone)}</option>)}</select>}

export function FollowForm({kind,w,send,onError,record}:{kind:FollowKind;record?:WorkRecord}&Props) {
  const [taskKind,setTaskKind]=useState('task');
  const [taskOwner,setTaskOwner]=useState(record?.kind==='shift'?record.ownerId:'');
  const [checkoutShift,setCheckoutShift]=useState(record?.kind==='shift'&&record.data.published&&!record.data.cancelled&&!record.data.releasedAt?record.id:'');
  const eligible=(m:Workspace['me'])=>!m.scheduleOnly&&(m.position!=='Dishwasher'||kind==='task'&&taskKind==='task')&&(manages(w.me,m.area,kind==='development'?'people.manage':'tasks.manage')||kind==='task'&&canManageClosing(w.me,m.area,'tasks.manage')&&w.records.some(s=>s.kind==='shift'&&s.locationId===w.location.id&&s.ownerId===m.id&&s.area===m.area&&s.data.published&&!s.data.cancelled&&!s.data.releasedAt));
  const taskShifts=w.records.filter((r):r is RecordOf<'shift'>=>r.kind==='shift'&&r.locationId===w.location.id&&r.ownerId===taskOwner&&r.data.published&&!r.data.cancelled&&!r.data.releasedAt&&w.members.some(m=>m.id===taskOwner&&m.area===r.area&&!m.scheduleOnly&&eligible(m)));
  const linkedShift=taskShifts.find(r=>r.id===checkoutShift);
  if(kind==='development')return <ReviewSetup w={w} send={send} onError={onError}/>;
  if(kind==='feedback')return <Form onError={onError} submit={(f,action)=>send('feedback.save',{text:val(f,'note'),shared:action==='share'},record)}><p>Private notes are visible only to you. Share a note when you want the managers responsible for people in your department to follow up.</p><Note label="What is on your mind?" initial={record?.kind==='feedback'?record.data.text:''}/><div className="shared-actions"><button value="private">Save privately</button><button value="share" className="shared-primary">Share for manager follow-up</button></div></Form>;
  if(kind==='task')return <Form onError={onError} submit={f=>{if(checkoutShift&&!linkedShift)throw Error('The selected checkout shift changed. Choose an eligible published shift again.');return send('task.create',{ownerId:val(f,'ownerId'),kind:taskKind,title:val(f,'title'),detail:val(f,'note'),due:due(f,w),...(linkedShift?{shiftId:linkedShift.id}:{}),...(taskKind==='handoff'?{incomingId:val(f,'incomingId')}:{})})}}><Field label="Work type"><select value={taskKind} onChange={e=>{setTaskKind(e.target.value);setTaskOwner('');setCheckoutShift('')}}><option value="task">Assigned work</option><option value="issue">Operational issue</option><option value="handoff">Station handoff</option></select></Field><Field label="Responsible employee"><select name="ownerId" required value={taskOwner} onChange={e=>{setTaskOwner(e.target.value);setCheckoutShift('')}}><option value="">Choose a person</option>{w.members.filter(eligible).map(m=><option key={m.id} value={m.id}>{m.name} · {m.position}</option>)}</select></Field><Field label="Required for shift checkout"><select name="shiftId" value={checkoutShift} onChange={e=>setCheckoutShift(e.target.value)}><option value="">No shift checkout requirement</option>{taskShifts.map(shift=><option key={shift.id} value={shift.id}>{shiftStationName(shift)} · {displayTime(shift.data.start,w.location.timezone)} → {displayTime(shift.data.end,w.location.timezone)}</option>)}</select></Field>{linkedShift&&<p>This work must pass its required checks before checkout. The due time must fall within this published shift.</p>}<Field label="Task"><input name="title" required maxLength={200}/></Field><Note label="What must be true when this is done?"/>{taskKind==='handoff'&&<Field label="Incoming employee"><People w={w} name="incomingId" eligible={eligible}/></Field>}<Due key={checkoutShift} w={w} initial={linkedShift?.data.end}/><button className="shared-primary">Assign work</button></Form>;
  if(kind==='handoff')return <Form onError={onError} submit={f=>{const opening=w.records.find(r=>r.id===val(f,'incomingLeadershipId')&&r.kind==='leadership');return send('handoff.create',{title:val(f,'title'),detail:val(f,'note'),outgoingLeadershipId:val(f,'outgoingLeadershipId'),incomingLeadershipId:val(f,'incomingLeadershipId'),incomingId:opening?.ownerId,priority:val(f,'priority'),safeToDefer:f.get('safe')==='on'})}}><p>You remain responsible until the opening manager accepts. Their opening assignment sets the acceptance deadline.</p><Field label="Your closing leadership assignment"><LeadershipSelect w={w} name="outgoingLeadershipId" own/></Field><Field label="Receiving opening manager"><LeadershipSelect w={w} name="incomingLeadershipId"/></Field><Field label="Issue to carry forward"><input name="title" required maxLength={200}/></Field><Note label="Current condition, temporary action and next step"/><Field label="Priority"><select name="priority"><option value="routine">Routine safe deferral</option><option value="urgent">Safety, security or after-hours professional concern — notify owner</option></select></Field><label className="shared-check"><input type="checkbox" name="safe" required/>I have assessed this issue and confirmed it can be deferred safely.</label><button className="shared-primary">Send for opening-manager acceptance</button></Form>;
  return <GoalForm w={w} send={send} onError={onError} record={record}/>;
}

function GoalForm({w,send,onError,record}:Props&{record?:WorkRecord}) {
  const [goalKind,setGoalKind]=useState('development');
  const [goalOwner,setGoalOwner]=useState(record?.kind==='standard'||!has(w.me,'people.manage')&&!has(w.me,'tasks.manage')?w.me.id:'');
  const [goalSource,setGoalSource]=useState<{id:string;revision:number}|null>(()=>record?.kind==='standard'?{id:record.id,revision:record.revision}:null);
  const owner=w.members.find(m=>m.id===goalOwner);
  const reviewers=w.members.filter(m=>!!owner&&m.id!==owner.id&&manages(m,owner.area,goalKind==='development'?'people.manage':'tasks.manage'));
  const guides=approvedStationGuides(w).filter(r=>!owner||r.area===owner.area),selected=guides.find(r=>r.id===goalSource?.id&&r.revision===goalSource?.revision);
  const sourceKey=(r:{id:string;revision:number})=>JSON.stringify([r.id,r.revision]);
  return <Form onError={onError} submit={f=>{
    if(!reviewers.length)throw Error('A restaurant administrator needs to assign a reviewing manager for this department before you can save this goal.');
    if(goalSource&&!selected)throw Error('This instruction changed. Choose its current approved version before saving.');
    return send('goal.create',{ownerId:val(f,'ownerId')||w.me.id,managerId:val(f,'managerId'),type:goalKind,title:val(f,'title'),definition:val(f,'note'),due:due(f,w),...(selected?{standardId:selected.id,standardRevision:selected.revision}:{})});
  }}>
    {has(w.me,'tasks.manage')&&<Field label="Goal type"><select value={goalKind} onChange={e=>setGoalKind(e.target.value)}><option value="development">Employee-chosen development</option><option value="required-correction">Required correction</option></select></Field>}
    <p>{goalKind==='development'?'A proposed goal starts only when the employee accepts it. A goal you choose for yourself starts when you save.':'This is a required correction to an approved standard. It is not an optional goal.'}</p>
    {(has(w.me,'people.manage')||has(w.me,'tasks.manage'))&&<Field label="Employee"><select name="ownerId" value={goalOwner} onChange={e=>setGoalOwner(e.target.value)} required><option value="">Choose a person</option>{w.members.filter(m=>m.position!=='Dishwasher'&&(m.id===w.me.id||manages(w.me,m.area,goalKind==='development'?'people.manage':'tasks.manage'))).map(m=><option key={m.id} value={m.id}>{m.name} · {m.position}</option>)}</select></Field>}
    <Field label="Reviewing manager"><People key={goalOwner+goalKind} w={w} name="managerId" eligible={m=>reviewers.some(r=>r.id===m.id)}/></Field>
    {owner&&!reviewers.length&&<p role="status">No reviewing manager is assigned for this department. Ask a restaurant administrator to set one up, then refresh to continue.</p>}
    <Field label="Goal"><input name="title" required maxLength={200} defaultValue={record?.kind==='standard'?('Learn '+record.data.title).slice(0,200):''}/></Field>
    <Note label="Observable outcome and support needed"/>
    <Field label={goalKind==='required-correction'?'Current approved standard':'Approved instruction (optional)'}><select required={goalKind==='required-correction'} value={goalSource?sourceKey(goalSource):''} onChange={e=>{const r=guides.find(g=>sourceKey(g)===e.target.value);setGoalSource(r?{id:r.id,revision:r.revision}:null)}}>
      <option value="">{goalKind==='required-correction'?'Choose a standard':'No linked instruction'}</option>
      {goalSource&&!selected&&<option disabled value={sourceKey(goalSource)}>Instruction changed — choose the current version</option>}
      {guides.map(r=><option key={r.id} value={sourceKey(r)}>{r.data.title} · approved version {r.data.version}</option>)}
    </select></Field>
    {selected&&<p className="shared-muted">The goal keeps this exact approved version. Its instructions remain available from the saved goal.</p>}
    <p className="shared-muted">Your saved goal is shared with the responsible managers. Your private JMAX conversation is not shared. Completing a goal does not grant station clearance.</p>
    <Due w={w}/><button className="shared-primary" disabled={!reviewers.length}>{goalKind==='development'?'Save goal':'Assign required correction'}</button>
  </Form>;
}

export function FollowDetail({record:r,w,send,onError,onOpen}:Props&{record:WorkRecord;onOpen?:(r:WorkRecord)=>void}) {
  const owner=personName(w,r.ownerId,'Employee'),trail=<History r={r} w={w}/>;
  if(r.kind==='development')return <ReviewDetail record={r} w={w} send={send} onError={onError}/>;
  if(r.kind==='feedback')return <><p><strong>{owner}</strong> · {r.data.shared?r.data.status:'Private — only you'}</p><p className="shared-message">{r.data.text}</p>{!r.data.shared&&r.ownerId===w.me.id&&<FollowForm kind="feedback" record={r} w={w} send={send} onError={onError}/>} {r.data.response&&<article><strong>Manager commitment</strong><p className="shared-message">{r.data.response}</p><p>Follow-up due {displayTime(r.data.due,w.location.timezone)}</p></article>}
    {r.data.shared&&r.ownerId!==w.me.id&&manages(w.me,r.area,'people.manage')&&r.data.status!=='closed'&&<Form onError={onError} submit={f=>send('feedback.respond',{response:val(f,'note'),due:due(f,w)},r)}><Note label="What I will do and how we will follow up" initial={r.data.response}/><Due w={w} initial={r.data.due||undefined}/><button className="shared-primary">Record commitment</button></Form>}
    {r.ownerId===w.me.id&&r.data.shared&&['follow-up','closed'].includes(r.data.status)&&<Form onError={onError} submit={(f,action)=>send(`feedback.${action}`,{note:val(f,'note')},r)}><Note label="Outcome or what still needs attention"/><div className="shared-actions">{r.data.status==='follow-up'&&<button value="close" className="shared-primary">Confirm resolved</button>}<button value="reopen">Needs more follow-up</button></div></Form>}{trail}</>;
  if(r.kind==='handoff')return <><p><strong>Responsible now: {owner}</strong></p><p className="shared-kicker">{r.data.phase} · {r.data.priority}</p><p className="shared-message">{r.data.detail}</p><p>Opening manager: {personName(w,r.data.incomingId)} · accept by {displayTime(r.data.due,w.location.timezone)}</p>
    {r.data.phase==='offered'&&r.data.incomingId===w.me.id&&<Form onError={onError} submit={(f,step)=>send('handoff.transition',{step,note:val(f,'note')},r)}><Note label="Condition and next action"/><div className="shared-actions"><button value="dispute">Return with a concern</button><button value="accept" className="shared-primary">Accept responsibility</button></div></Form>}
    {r.ownerId===w.me.id&&r.data.phase==='accepted'&&<Form onError={onError} submit={f=>send('handoff.transition',{step:'resolve',note:val(f,'note')},r)}><Note label="What resolved the issue?"/><button className="shared-primary">Record resolution</button></Form>}
    {r.data.phase==='accepted'&&manages(w.me,r.area,'tasks.manage')&&<details><summary>Arrange replacement manager</summary><p>If the responsible manager is unavailable, name a replacement and explain the remaining work. You retain responsibility until the replacement accepts; this does not resolve the issue.</p><Form onError={onError} submit={f=>{const opening=w.records.find(x=>x.id===val(f,'incomingLeadershipId')&&x.kind==='leadership');return send('handoff.transition',{step:'recover',note:val(f,'note'),incomingLeadershipId:val(f,'incomingLeadershipId'),incomingId:opening?.ownerId},r)}}><Field label="Replacement manager assignment"><LeadershipSelect w={w} name="incomingLeadershipId" area={r.area} excludeIds={[r.ownerId]} unexpired/></Field><Note label="Reason, current condition and remaining action"/><button className="shared-primary">Request replacement acceptance</button></Form></details>}
    {r.ownerId===w.me.id&&['offered','disputed'].includes(r.data.phase)&&<><p>Your responsibility continues until the receiving manager accepts.</p><Form onError={onError} submit={(f,step)=>{const opening=w.records.find(x=>x.id===val(f,'incomingLeadershipId')&&x.kind==='leadership');return send('handoff.transition',{step,note:val(f,'note'),incomingLeadershipId:val(f,'incomingLeadershipId'),incomingId:opening?.ownerId},r)}}><Field label="Receiving opening manager"><LeadershipSelect w={w} name="incomingLeadershipId" initial={r.data.incomingLeadershipId} area={r.area}/></Field><Note label="Clarification or reason"/><div className="shared-actions"><button value="offer" className="shared-primary">Send updated handoff</button><button value="cancel">Cancel this deferral</button></div></Form></>}{trail}</>;
  if(r.kind==='goal')return <GoalDetail record={r} w={w} send={send} onError={onError}/>;
  if(r.kind==='task') {
    if(r.data.dishCheckout||r.data.dishHandoff)return <><DishCheckoutDetail r={r} w={w} send={send} onError={onError} onOpen={onOpen}/>{trail}</>;
    const correction=r.data.phase==='correction'?[...r.data.history].reverse().find(h=>h.action==='fix'||h.action==='dispute'):undefined;
    const shift=r.data.shiftId?w.records.find((s):s is RecordOf<'shift'>=>s.kind==='shift'&&s.id===r.data.shiftId&&s.locationId===r.locationId):undefined;
    const taskManager=r.data.shiftId?canManageClosing(w.me,r.area,'tasks.manage'):manages(w.me,r.area,'tasks.manage');
    return <><p><strong>{owner}</strong> · {r.data.kind}</p>{r.data.shiftId&&<article><strong>Required for shift checkout</strong><p>{shift?`${shiftStationName(shift)} · ${displayTime(shift.data.start,w.location.timezone)}`:'The linked shift is outside your accessible records.'}</p><p>{r.data.phase==='closed'?'The required work is checked. Manager checkout is a separate step.':'This responsibility must pass its required checks before the linked shift can be checked out.'}</p>{shift&&onOpen&&<button type="button" onClick={()=>onOpen(shift)}>Open linked shift</button>}</article>}<p className="shared-message">{r.data.detail}</p><p>Due {displayTime(r.data.due,w.location.timezone)} · {r.data.phase}</p>{correction&&<article><strong>What needs correction</strong><p>{correction.note}</p></article>}
      {r.data.closingHandoff&&<p>Received by {personName(w,r.data.closingHandoff.acceptedBy)} from {personName(w,r.data.closingHandoff.outgoingId)} · {displayTime(r.data.closingHandoff.acceptedAt,w.location.timezone)}. The incoming employee completes the remaining work before an independent physical check.</p>}
      {r.data.phase!=='closed'&&<Form onError={onError} submit={(f,step)=>send('task.transition',{step,note:val(f,'note')},r)}><Note label="Evidence or next action"/><div className="shared-actions">{r.ownerId===w.me.id&&['open','correction'].includes(r.data.phase)&&<button value="ready" className="shared-primary">{r.data.closingHandoff?'Incoming work ready for physical check':r.data.shiftId?'Work ready for physical check':'Ready for review'}</button>}{taskManager&&r.data.phase==='verification'&&r.ownerId!==w.me.id&&<button value="verify" className="shared-primary">Physical check passed</button>}{taskManager&&<button value="fix">Return for correction</button>}{r.data.incomingId===w.me.id&&r.data.phase==='acceptance'&&<><button value="accept" className="shared-primary">Accept handoff</button><button value="dispute">Dispute handoff</button></>}</div></Form>}
      {manages(w.me,r.area,'tasks.manage')&&!r.data.shiftId&&r.data.phase!=='closed'&&<details><summary>Reassign the remaining work</summary><Form onError={onError} submit={f=>send('task.reassign',{ownerId:val(f,'ownerId'),note:val(f,'note')},r)}><Field label="New responsible employee"><People w={w} name="ownerId" eligible={m=>(m.position!=='Dishwasher'||r.data.kind==='task')&&m.area===r.area&&m.id!==r.data.incomingId}/></Field><Note label="Reason and remaining work"/><button>Reassign work</button></Form></details>}{trail}</>;
  }
  return null;
}

function GoalDetail({record:r,w,send,onError}:Props&{record:RecordOf<'goal'>}) {
  const instruction=approvedStationGuides(w).find(s=>s.id===r.data.standardId&&s.revision===r.data.standardRevision);
  const stale=!!r.data.standardId&&!instruction;
  const followup=r.data.history.at(-1),showFollowup=followup&&!['employee-chosen','proposed','required-correction-assigned'].includes(followup.action);
  const step=learningNextStep(w,r,new Date().toISOString());
  const guided=!!r.data.automaticLearning&&r.ownerId===w.me.id&&r.data.phase==='active'&&!stale;
  const canCoach=!stale&&r.data.phase==='active'&&r.data.managerId===w.me.id&&r.ownerId!==w.me.id&&manages(w.me,r.area,r.data.type==='development'?'people.manage':'tasks.manage');
  return <div className="learning-detail">{r.data.automaticLearning?<><div className="practice-identity"><span className="practice-state" data-phase={r.data.phase}>{r.data.phase==='verification'?'Ready for review':r.data.phase==='closed'?'Manager confirmed':step.ended?'Ended':'In practice'}</span><h3>{instruction?.data.title??r.data.title}</h3><p>{personName(w,r.ownerId)} · {instruction?.data.position??w.members.find(m=>m.id===r.ownerId)?.position}</p><small>{step.unavailable?'Reviewing manager needs reassignment':r.data.phase==='verification'?personName(w,r.data.managerId)+' has the next step':r.data.phase==='closed'?'Practice outcome confirmed. Station clearance is separate.':personName(w,r.data.managerId)+' reviews this practice'}</small></div>{!guided&&instruction&&<><LearningProgress count={(r.data.practiceChecks??[]).filter(i=>i>=0&&i<instruction.data.criteria.length).length} total={instruction.data.criteria.length} label="reported practiced"/><ul className="practice-review-criteria" aria-label="Reported practice">{instruction.data.criteria.map((criterion,i)=><li key={i}><span aria-hidden="true">{r.data.practiceChecks?.includes(i)?'✓':'○'}</span><span>{criterion}</span></li>)}</ul></>}{!guided&&!instruction&&<p className="shared-message">{r.data.definition}</p>}</>:<><div className="learning-detail-meta"><span>{personName(w,r.ownerId,'Employee')}</span><span>{r.data.type==='development'?'Learning goal':'Required correction'}</span></div><LearningPath record={r}/><div className="learning-detail-next"><strong>{step.label}</strong><span>{step.ended?'This goal is in your history.':step.unavailable?'Responsibility needs reassignment.':step.needsMe?'Your next step':'Waiting on '+personName(w,step.actorId)}</span></div><h3>What you’re working toward</h3><p className="shared-message">{r.data.definition}</p><dl className="learning-detail-facts"><div><dt>Due</dt><dd>{displayTime(r.data.due,w.location.timezone)}</dd></div><div><dt>Reviewing manager</dt><dd>{personName(w,r.data.managerId)}</dd></div></dl></>}
    {showFollowup&&(!r.data.automaticLearning||["coach","fix"].includes(followup.action))&&<article><strong>{followup.action==='practice'?'Latest practice note':followup.action==='coach'?'Latest coaching note':'Latest follow-up'} · {personName(w,followup.actorId)}</strong><p className="shared-message">{followup.note}</p><small>{displayTime(followup.at,w.location.timezone)}</small></article>}
    {instruction&&<details><summary>Read instructions</summary><p>Approved version {instruction.data.version} · {instruction.data.source}</p><StationGuideContent guide={instruction.data.guide} provenance={instruction.data.provenance}/><h3>What done looks like</h3><ul>{instruction.data.criteria.map((c,i)=><li key={i}>{c}</li>)}</ul></details>}
    {stale&&<p role="status" className="shared-error">The linked instructions changed or are no longer available. Ask the reviewing manager to replace this goal using the current approved instruction before accepting it or reviewing the outcome.</p>}
    {!r.data.automaticLearning&&<p className="shared-muted">Goal progress does not grant station clearance or complete an operating check.</p>}
    {guided&&instruction&&<GuidedPractice key={r.id+':'+r.revision} goal={r} guide={instruction} send={send} onError={onError}/>}
    {!guided&&!step.ended&&(canCoach||step.needsMe&&!step.stale||r.ownerId===w.me.id&&r.data.phase==='proposed')&&<Form onError={onError} submit={(f,step)=>send('goal.transition',{step,note:val(f,'note')},r)}><Note maxLength={2000} label={canCoach?'What should they practice next, and how will you support them?':r.data.phase==='active'?'What did you practice, and where do you need help?':r.data.phase==='verification'?'What did you observe, and what support is needed?':'Your choice and the support you need'}/>{r.data.phase==='active'&&<p className="shared-muted">{canCoach?'Your note goes to the employee. The goal stays in practice.':`Practice notes are saved with this goal for ${personName(w,r.data.managerId)} to read. Choose ready for review when you want the outcome checked.`}</p>}<div className="shared-actions">
      {r.ownerId===w.me.id&&r.data.phase==='proposed'&&<><button value="decline">Decline this goal</button><button value="accept" disabled={stale} className="shared-primary">Choose this goal</button></>}
      {r.ownerId===w.me.id&&r.data.phase==='active'&&<><button value="practice" disabled={stale} className="shared-primary">Save practice note</button><button value="ready" disabled={stale}>Ready for outcome review</button></>}
      {canCoach&&<button value="coach" className="shared-primary">Send coaching note</button>}
      {r.data.managerId===w.me.id&&r.data.phase==='verification'&&<><button value="fix">More work needed</button><button value="verify" disabled={stale} className="shared-primary">Confirm outcome</button></>}
    </div></Form>}{!step.ended&&(r.data.managerId===w.me.id||r.ownerId===w.me.id&&r.data.type==='development')&&<details><summary>End this goal</summary><Form onError={onError} submit={f=>send('goal.transition',{step:'cancel',note:val(f,'note')},r)}><Note label="Why are you ending this goal?"/><button>End this goal</button></Form></details>}<History r={r} w={w}/></div>;
}

function ReviewDetail({record:r,w,send,onError}:Props&{record:RecordOf<'development'>}) {
  const employee=r.ownerId===w.me.id,manager=r.data.managerId===w.me.id,gm=r.data.approverId===w.me.id;
  const assessing=employee&&r.data.phase==='self-assessment'||manager&&r.data.phase==='manager-assessment';
  const dueState=reviewDueState(r,localDate(new Date().toISOString(),w.location.timezone));
  const person=(id:string)=>personName(w,id,'Previous member');
  return <><p><strong>{person(r.ownerId)}</strong> · {r.data.phase.replaceAll('-',' ')}</p>{!assessing&&<LearningPath record={r}/>}<details><summary>Reviewers and due date</summary><p>Manager: {person(r.data.managerId)} · Approver: {person(r.data.approverId)}</p><p>Original due date: {r.data.originalDueDate}</p></details>{!['approved','cancelled'].includes(r.data.phase)&&dueState.overdueDays>0&&<p className="shared-error">{dueState.overdueDays} days overdue · responsibility: {person(dueState.responsibleId)}{dueState.level==='owner'?' · owner follow-up due':dueState.level!=='normal'?' · reminder due':''}</p>}
    <p className="shared-muted">Choose the description that fits these criteria. Ratings and examples stay in this review’s history.</p>
    {!assessing&&r.data.stations.map((s,i)=><article key={i}><strong>{s.name}</strong><p>{s.definition}</p><small>Source: {s.source}</small><div className="shared-grid"><div><p><strong>Employee: {ratingLabel(s.selfScore,s.selfRatingScale)}</strong></p><p>{s.selfNote}</p></div><div><p><strong>Manager: {ratingLabel(s.managerScore,s.managerRatingScale)}</strong></p><p>{s.managerNote}</p></div></div></article>)}
    {r.data.selfSummary&&<p><strong>Employee summary:</strong> {r.data.selfSummary}</p>}{r.data.managerSummary&&<p><strong>Manager summary:</strong> {r.data.managerSummary}</p>}
    {assessing&&<AssessmentForm record={r} w={w} send={send} onError={onError} self={employee}/>}
    {r.data.managerDiscussion&&<article><strong>Manager conversation record</strong><p>{r.data.managerDiscussion}</p></article>}{r.data.employeeDiscussion&&<article><strong>Employee acknowledgement</strong><p>{r.data.employeeDiscussion}</p></article>}
    {r.data.phase==='discussion'&&(manager||employee)&&<Form onError={onError} submit={(f,action)=>send('development.discuss',{note:val(f,'note'),confirm:action==='confirm'},r)}><Note label={manager?'What we discussed, differences and agreed next steps':'My perspective on the conversation'}/><div className="shared-actions">{manager?<button className="shared-primary">Record conversation</button>:r.data.managerDiscussion&&<><button value="dispute">Needs more discussion</button><button value="confirm" className="shared-primary">Confirm the conversation occurred</button></>}</div>{employee&&<p className="shared-muted">Acknowledging the conversation does not mean agreeing with every score.</p>}</Form>}
    {manager&&r.data.phase==='discussion'&&<button disabled={!r.data.managerDiscussion||!r.data.employeeDiscussion} className="shared-primary" onClick={()=>send('development.request-approval',{},r)}>Send for GM approval</button>}
    {manager&&['discussion','gm-review'].includes(r.data.phase)&&<details><summary>Correct an assessment before approval</summary><Form onError={onError} submit={(f,by)=>send('development.revise-assessment',{by,note:val(f,'note')},r)}><Note label="What needs to be revised?"/><div className="shared-actions"><button value="manager">Revise my assessment</button><button value="employee">Return to employee</button></div></Form></details>}
    {gm&&r.data.phase==='gm-review'&&<Form onError={onError} submit={(f,action)=>send('development.approve',{approve:action==='approve',note:val(f,'note')},r)}><Note label="GM decision and follow-up"/><div className="shared-actions"><button value="return">Return for discussion</button><button value="approve" className="shared-primary">Approve completed review</button></div></Form>}
    {r.data.approvalNote&&<p><strong>GM decision:</strong> {r.data.approvalNote}</p>}
    {gm&&!['approved','cancelled'].includes(r.data.phase)&&<details><summary>Change review responsibility</summary><Form onError={onError} submit={f=>send('development.reassign',{managerId:val(f,'managerId'),approverId:val(f,'approverId'),note:val(f,'note')},r)}><Field label="Responsible manager"><People w={w} name="managerId" initial={r.data.managerId} eligible={m=>m.id!==r.ownerId&&manages(m,r.area,'people.manage')}/></Field><Field label="GM approver"><People w={w} name="approverId" initial={r.data.approverId} eligible={m=>m.id!==r.ownerId&&manages(m,r.area,'people.approve')}/></Field><Note label="Reason for reassignment"/><button>Reassign and preserve original due date</button></Form></details>}
    {!!r.data.submissions.length&&<details><summary>Submitted assessments</summary><p>Earlier submissions stay here when an assessment is revised.</p>{r.data.submissions.map((s,i)=><article key={i}><strong>{s.by==='employee'?'Employee':'Manager'} · {person(s.actorId)}</strong><small>{displayTime(s.at,w.location.timezone)}</small><p>{s.summary}</p>{s.ratings.map((rating,j)=><p key={j}><strong>{rating.name}: {ratingLabel(rating.score,rating.scale)}</strong><br/>{rating.note}</p>)}</article>)}</details>}
    <History r={r} w={w}/>
  </>;
}
function AssessmentForm({record:r,send,onError,self}:Props&{record:RecordOf<'development'>;self:boolean}) {
  return <Form onError={onError} submit={(f,action)=>send('development.assess',{by:self?'employee':'manager',submit:action==='submit',ratings:r.data.stations.map((_,i)=>{const value=val(f,`score-${i}`),legacy=value.startsWith('legacy:');return {score:value===''?null:Number(legacy?value.slice(7):value),...(!legacy?{scale:'readiness-v1'}:{}),note:val(f,`note-${i}`)}}),summary:val(f,'summary'),allZeroConfirmed:f.get('allZero')==='on'},r)}>
    <p>{self?'Your assessment draft is private until you submit it.':'Your assessment draft remains private until you send it to the conversation step.'}</p>
    {r.data.stations.map((s,i)=><fieldset key={i}><legend>{s.name}</legend><p>{s.definition}</p><div className="rating-choices" role="radiogroup" aria-label={s.name+' readiness'}>{reviewRatings.map(choice=><label key={choice.value}><input type="radio" name={`score-${i}`} value={choice.value} defaultChecked={(self?s.selfRatingScale:s.managerRatingScale)==='readiness-v1'&&(self?s.selfScore:s.managerScore)===choice.value}/><span><strong>{choice.label}</strong><small>{choice.description}</small></span></label>)}</div>{(self?s.selfScore:s.managerScore)!==null&&(self?s.selfRatingScale:s.managerRatingScale)!=='readiness-v1'&&<label className="shared-check"><input type="radio" name={`score-${i}`} value={'legacy:'+(self?s.selfScore:s.managerScore)} defaultChecked/>Keep previous rating: {self?s.selfScore:s.managerScore}/10</label>}<Note name={`note-${i}`} label={`${s.name}: observable examples and support needed`} required={false} initial={self?s.selfNote:s.managerNote}/></fieldset>)}
    <Note name="summary" label="Assessment summary" required={false} initial={self?r.data.selfSummary:r.data.managerSummary}/><label className="shared-check"><input type="checkbox" name="allZero"/>If every station is “Not tried yet,” my summary explains the missing practice opportunities.</label><div className="shared-actions"><button value="draft">Save private draft</button><button value="submit" className="shared-primary">{self?'Submit self-assessment':'Send to conversation'}</button></div>
  </Form>;
}
