'use client';
import {useState} from 'react';
import {type Workspace,personName} from '../shared/types';
import {followupDesk,followupAreas,type FollowupEntry} from '../shared/followup-desk';
import {localDate} from '../shared/local-time';
export function FollowupLine({entry,w,onOpen}:{entry:FollowupEntry;w:Workspace;onOpen:(id:string)=>void}){
 const timing=entry.overdue?(entry.dateMeaning==='target'?'Past target':'Overdue'):entry.timing==='today'?'Today':entry.timing==='upcoming'?'Upcoming':entry.timing==='past'?'Past recorded date':'';
 return <li><button onClick={()=>onOpen(entry.id)}><strong>{entry.title}</strong><span>{followupAreas[entry.kind]} · {entry.area} · {entry.nextStep}</span><small>{entry.date?`${entry.dateLabel}: ${entry.date} · ${timing}`:entry.dateLabel.startsWith('No ')?entry.dateLabel:'No date entered'} · {entry.mode==='waiting'?'Waiting on another reviewer':entry.mode==='review'?'Evidence or assignment needs review':'Your next step'}</small>{entry.responsibleId&&<small>Recorded responsibility: {personName(w,entry.responsibleId,'Former or unavailable reviewer')}</small>}</button></li>;
}
export function FollowupSummary({w,now,onOpen,onAll}:{w:Workspace;now:string;onOpen:(id:string)=>void;onAll:()=>void}){
 const rows=followupDesk(w,now);return <article className="jmax-panel"><div className="jmax-panel-heading"><h2>People, guest and source follow-up</h2><button onClick={onAll}>Open follow-up desk</button></div><p>{rows.length} accessible active {rows.length===1?'record':'records'} · {rows.filter(r=>r.overdue).length} past due or target · {rows.filter(r=>r.mode==='your-step').length} with your next step.</p>{!rows.length?<p>No follow-ups from these work areas are recorded in your accessible scope.</p>:<ul className="jmax-work-list">{rows.slice(0,4).map(entry=><FollowupLine key={entry.id} entry={entry} w={w} onOpen={onOpen}/>)}</ul>}<p className="jmax-small">Staff ideas, guest reviews, onboarding, permits and promotions. Open the original record before acting. These counts do not establish completion or delivered reminders.</p></article>;
}
export function FollowupDesk({w,now,onOpen}:{w:Workspace;now:string;onOpen:(id:string)=>void}){
 const [query,setQuery]=useState(''),[kind,setKind]=useState('all'),[state,setState]=useState('all'),[page,setPage]=useState(0);
 const rows=followupDesk(w,now),filtered=rows.filter(r=>(kind==='all'||r.kind===kind)&&(state==='all'||state==='overdue'&&r.overdue||state==='today'&&r.timing==='today'&&r.dateMeaning!=='event'||r.mode===state)&&`${r.title} ${r.area} ${followupAreas[r.kind]}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())),lastPage=Math.max(0,Math.ceil(filtered.length/20)-1),current=Math.min(page,lastPage),start=current*20;
 return <section className="jmax-directory"><p className="jmax-eyebrow">{w.location.name} · {localDate(now,w.location.timezone)}</p><h1>Follow-up desk</h1><p>Recorded work across staff ideas, guest reviews, onboarding, inspections and permits, and promotions. Only your currently accessible records appear. Open the original record to review its evidence and actions.</p><p>No automatic reminders are sent. A proposed offer date is not an approval deadline, and an absent date does not mean the work is complete.</p><div className="jmax-area-grid"><label className="shared-field">Find follow-up<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label><label className="shared-field">Work area<select value={kind} onChange={e=>{setKind(e.target.value);setPage(0)}}><option value="all">All six areas</option>{Object.entries(followupAreas).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="shared-field">Show follow-up<select value={state} onChange={e=>{setState(e.target.value);setPage(0)}}><option value="all">All accessible follow-up</option><option value="your-step">Your next step</option><option value="review">Evidence or assignment review</option><option value="waiting">Waiting on another reviewer</option><option value="overdue">Past due or target</option><option value="today">Due or target today</option></select></label></div><p role="status">{filtered.length} matching {filtered.length===1?'record':'records'} of {rows.length} accessible · {filtered.length?`${start+1}–${Math.min(start+20,filtered.length)}`:'0'} shown.</p><ul className="jmax-work-list">{filtered.slice(start,start+20).map(entry=><FollowupLine key={entry.id} entry={entry} w={w} onOpen={onOpen}/>)}</ul>{!filtered.length&&<p>No recorded follow-ups match these filters.</p>}<div className="shared-actions"><button disabled={current===0} onClick={()=>setPage(current-1)}>Previous follow-ups</button><button disabled={current>=lastPage} onClick={()=>setPage(current+1)}>Next follow-ups</button></div><p className="jmax-small">Manager Log issues and maintenance remain in their existing daily panels. Specialist Food work stays in the Food work areas. Filed history is reviewed separately.</p></section>;
}
