'use client';
import {useEffect,useState} from 'react';
import type {ExcessBillingChoices} from '../shared/food-excess-billing';
import type {FoodHistoryPage} from '../shared/food-contract';
import {has,personName,type RecordOf,type Workspace} from '../shared/types';
import {displayTime} from '../shared/local-time';
import type {Send} from './workspace';
type Props={entry:FoodHistoryPage['entries'][number];r:RecordOf<'fooditem'>;w:Workspace;send:Send;busy:boolean};
const qty=(n:number)=>n>0&&n<.000001?'<0.000001':new Intl.NumberFormat('en-US',{maximumFractionDigits:6}).format(n);
export function ExtraBillingPicker({entry,r,w,send,busy,apiRoot}:Props&{apiRoot:string}){
 const [open,setOpen]=useState(false),[cursor,setCursor]=useState({before:0,revision:0}),[page,setPage]=useState<ExcessBillingChoices|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[selected,setSelected]=useState(''),[quantity,setQuantity]=useState(''),[note,setNote]=useState(''),[confirmed,setConfirmed]=useState(false);
 useEffect(()=>{if(!open)return;const ctrl=new AbortController();setPage(null);setError('');setSelected('');setQuantity('');setNote('');setConfirmed(false);
  const query=new URLSearchParams({locationId:w.location.id,recordId:r.id,dataset:r.data.source.dataset,view:'extra-billing',excessRevision:String(entry.revision),before:String(cursor.before),revision:String(cursor.revision)});
  void fetch(apiRoot+'/food?'+query,{signal:ctrl.signal}).then(async response=>{const d=await response.json() as ExcessBillingChoices&{error?:string};if(!response.ok)throw Error(d.error??'Could not load billing invoices.');if(d.recordId!==r.id||d.dataset!==r.data.source.dataset||d.excessRevision!==entry.revision||!Array.isArray(d.entries))throw Error('Unexpected billing invoice scope. Refresh before continuing.');if(!ctrl.signal.aborted)setPage(d)}).catch(e=>{if(!ctrl.signal.aborted)setError(e.message)});return()=>ctrl.abort();
 },[open,cursor,refresh,apiRoot,w.location.id,w.me.id,r.id,r.revision,r.data.source.dataset,entry.revision]);
 const extra=entry.event.excess;if(!extra||entry.excessVoided)return null;const totals=entry.excessBilled??{entries:0,quantity:0},review=has(w.me,'location.manage')||has(w.me,'orders.review'),picked=page?.entries.find(e=>e.revision===Number(selected));
 const limit=page&&picked?Math.min(Math.max(0,page.quantity-page.matched),Math.max(0,picked.invoice.quantity-picked.matched)):0,valid=!!picked&&!picked.issue&&quantity.trim()!==''&&Number.isFinite(Number(quantity))&&Number(quantity)>0&&Number(quantity)<=limit&&note.trim().length>0&&confirmed;
 return <section aria-label={`Billing matches for extra delivery ${extra.deliveryReference}`}><h4>Extra goods linked to an issued invoice</h4><p>{qty(totals.quantity)} of {qty(extra.quantity)} {extra.invoice.invoiceUnit} linked in {totals.entries} active billing matches. This identifies document quantities only; it does not approve a charge, record payment or change stock or receiving.</p><p>Supplier pickups remain separate facts. A billing match does not subtract or cancel a recorded pickup.</p>
  {review&&<button disabled={busy} onClick={()=>{setOpen(!open);setCursor({before:0,revision:0});setConfirmed(false)}}>{open?'Close billing matching':'Match an issued billing invoice'}</button>}
  {open&&review&&<><p>Record the actual issued invoice through invoice history first. Only the same item and supplier can be matched, with the same invoice unit and quantity basis. Pack changes require review.</p><button disabled={busy} onClick={()=>{setCursor({before:0,revision:0});setRefresh(refresh+1)}}>Refresh billing invoices</button>{error&&<p role="alert">{error}</p>}{!page&&!error&&<p role="status">Loading recorded invoices…</p>}
   {page&&<form onSubmit={async e=>{e.preventDefault();if(valid&&await send('fooditem.excess-billing',{excessRevision:entry.revision,invoiceRevision:Number(selected),quantity,note,confirmed},r))setOpen(false)}}><fieldset disabled={busy}>
    <p>{qty(Math.max(0,page.quantity-page.matched))} {page.invoiceUnit} from this extra delivery is not yet linked to billing.</p>
    {page.entries.length?<><label className="shared-field">Recorded billing invoice<select required value={selected} onChange={e=>{setSelected(e.target.value);setQuantity('');setConfirmed(false)}}><option value="">Choose the checked invoice line</option>{page.entries.map(e=><option key={e.revision} value={e.revision} disabled={!!e.issue||e.matched>=e.invoice.quantity}>{e.invoice.invoiceNumber} · line {e.invoice.lineReference} · {e.invoice.invoiceDate} · {e.issue||qty(Math.max(0,e.invoice.quantity-e.matched))+' '+e.invoice.invoiceUnit+' not linked'}</option>)}</select></label>
     {picked&&<p className="food-preserve">Invoice source: {picked.invoice.sourceNote}. Recorded line amount: {new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(picked.invoice.lineTotalCents/100)}. No amount is allocated by this quantity match.</p>}
     <label className="shared-field">Quantity linked ({page.invoiceUnit})<input type="number" required min="0" max={limit} step="any" value={quantity} onChange={e=>{setQuantity(e.target.value);setConfirmed(false)}}/></label><p>Up to {qty(limit)} {page.invoiceUnit} for this match.</p>
     <label className="shared-field">Billing match evidence<textarea required maxLength={1000} value={note} onChange={e=>{setNote(e.target.value);setConfirmed(false)}}/></label><label className="food-check"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked that this issued invoice line bills this quantity from the selected extra delivery.</label><button className="shared-primary" disabled={!valid}>Save checked billing match</button></>:<p>No recorded billing invoices on this page.</p>}
    <div className="shared-actions">{cursor.before>0&&<button type="button" onClick={()=>setCursor({before:0,revision:0})}>First invoice page</button>}{page.next&&<button type="button" onClick={()=>setCursor({before:page.next!,revision:page.revision})}>More billing invoices</button>}</div>
   </fieldset></form>}
  </>}
 </section>;
}
export function ExtraBillingHistory({entry,r,w,send,busy}:Props){
 const [correcting,setCorrecting]=useState(false),match=entry.event.excessBilling;if(!match)return null;const review=has(w.me,'location.manage')||has(w.me,'orders.review');
 return <div className="food-waste-history"><h4>Extra delivery {match.excess.deliveryReference} ↔ billing invoice {match.invoice.invoiceNumber}, line {match.invoice.lineReference}</h4><p><strong>{qty(match.quantity)} {match.invoice.invoiceUnit} linked</strong> · {match.invoice.sku.vendor} · invoice dated {match.invoice.invoiceDate}. Original extra delivery dated {match.excess.observedDate}, against invoice {match.excess.invoice.invoiceNumber}, line {match.excess.invoice.lineReference}.</p><p className="food-preserve">Billing source: {match.invoice.sourceNote}. Match evidence: {match.note}</p><p>Checked by {personName(w,match.by)} on {displayTime(match.at,w.location.timezone)}. No charge approval, payment, stock, receiving or pickup adjustment.</p>
  {entry.excessBillingVoided?<p><strong>Billing match voided; original retained.</strong> {personName(w,entry.excessBillingVoided.by)} · {displayTime(entry.excessBillingVoided.at,w.location.timezone)} · {entry.excessBillingVoided.reason}</p>:review&&<><button disabled={busy} onClick={()=>setCorrecting(!correcting)}>{correcting?'Keep billing match':'Void incorrect billing match'}</button>{correcting&&<form onSubmit={async e=>{e.preventDefault();await send('fooditem.excess-billing-void',{matchRevision:entry.revision,reason:new FormData(e.currentTarget).get('reason')},r)}}><fieldset disabled={busy}><label className="shared-field">Reason for voiding billing match<textarea name="reason" required maxLength={1000}/></label><p>This corrects only the document association. Original delivery, invoice and pickup facts are retained.</p><button>Confirm billing match void</button></fieldset></form>}</>}
 </div>;
}
