'use client';
import {useEffect,useState} from 'react';
import type {ReturnQueue,ReturnFilter} from '../shared/food-return-queue';
import type {Workspace} from '../shared/types';
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const valid=(v:unknown):v is ReturnQueue=>object(v)&&Array.isArray(v.entries)&&object(v.totals)&&typeof v.total==='number'&&typeof v.revision==='number'&&(v.next===null||typeof v.next==='number');
const qty=(v:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:6}).format(v);

export function FoodReturnQueue({w,apiRoot,dataset,onOpen}:{w:Workspace;apiRoot:string;dataset:'demo'|'operating';onOpen:(id:string,sequence:number)=>void}){
 const [filter,setFilter]=useState<ReturnFilter>('unmatched'),[query,setQuery]=useState(''),[cursor,setCursor]=useState<{before:number;revision?:number}>({before:0}),[reload,setReload]=useState(0),[page,setPage]=useState<ReturnQueue|null>(null),[error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();setPage(null);setError('');const params=new URLSearchParams({locationId:w.location.id,dataset,view:'returns',filter,q:query,before:String(cursor.before),...(cursor.revision===undefined?{}:{revision:String(cursor.revision)})});
  void fetch(`${apiRoot}/food?${params}`,{signal:abort.signal}).then(async response=>{const value:unknown=await response.json();if(!response.ok)throw Error(object(value)&&typeof value.error==='string'?value.error:'Unable to load supplier returns.');if(!valid(value))throw Error('Unexpected return queue response.');if(!abort.signal.aborted)setPage(value);}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Unable to load supplier returns.')});return()=>abort.abort();
 },[apiRoot,w.location.id,dataset,filter,query,cursor,reload]);
 return <section aria-label="Supplier return review"><h2>Supplier return review</h2><p>Find recorded physical returns whose quantities have not been fully matched to issued credit documents. Unmatched does not mean a supplier owes a credit; check the source documents and agreed outcome.</p>
  <div className="food-controls"><label className="shared-field">Return view<select value={filter} onChange={e=>{setFilter(e.target.value as ReturnFilter);setCursor({before:0})}}><option value="unmatched">Have unmatched quantities</option><option value="matched">Fully matched quantities</option><option value="voided">Voided return records</option><option value="all">All recorded returns</option></select></label><label className="shared-field">Find return or invoice<input type="search" maxLength={100} value={query} placeholder="Return, delivery, invoice, supplier or item" onChange={e=>{setQuery(e.target.value);setCursor({before:0})}}/></label></div>
  <button onClick={()=>{setCursor({before:0});setReload(n=>n+1)}}>Refresh return review</button>
  {error&&<p role="alert" className="food-warning">{error}</p>}{!page&&!error&&<p role="status">Loading supplier returns…</p>}
  {page&&<><p>Return-record counts for this search, across all views:</p><div className="food-summary"><span>Active returns<strong>{page.totals.active}</strong></span><span>Have unmatched quantities<strong>{page.totals.unmatched}</strong></span><span>Fully matched quantities<strong>{page.totals.matched}</strong></span><span>Voided returns<strong>{page.totals.voided}</strong></span></div><p className="shared-muted">Only saved returns are included. Different units are not added together. A fully matched quantity does not verify payment, value coverage or claim settlement.</p>
   {page.entries.map(e=>{const r=e.returned,invoice=r.receiving.invoice;return <article className="food-card" key={e.sequence}><h3>{e.currentTitle}</h3><p>{e.controlNumber} · Current catalog name</p><p><strong>Return {r.returnReference} · {r.returnDate}</strong><br/>{invoice.sku.vendor} · invoice {invoice.invoiceNumber}, line {invoice.lineReference} · delivery {r.receiving.deliveryReference}</p><p>Original supplier pack: {invoice.sku.packCount??'?'} × {invoice.sku.unitQty??'?'} {invoice.sku.unitUOM} / {invoice.sku.purchaseUnit}.</p>
    {e.voided?<p><strong>Voided return — excluded from active review.</strong> Original recorded quantity: {qty(e.quantity)} {invoice.invoiceUnit}.</p>:<><div className="food-summary"><span>Physically returned<strong>{qty(e.quantity)} {invoice.invoiceUnit}</strong></span><span>Matched to issued credits<strong>{qty(e.matched)} {invoice.invoiceUnit}</strong></span><span>Still unmatched<strong>{qty(e.remaining)} {invoice.invoiceUnit}</strong></span></div><p>{e.matches} active {e.matches===1?'match':'matches'}. Original delivery facts and dated physical counts are unchanged.</p></>}
    <p className="food-preserve">Return evidence: {r.evidence}</p><button onClick={()=>onOpen(e.recordId,e.sequence)}>{e.voided?'Open retained return history':'Open return and credit matching'}</button>
   </article>})}
   {!page.entries.length&&<p>No saved returns match this view. This does not confirm that all physical returns or credits have been recorded.</p>}<div className="shared-actions"><span>{page.entries.length} shown · {page.total} matching return records</span>{cursor.before>0&&<button onClick={()=>setCursor({before:0})}>First return page</button>}{page.next!==null&&<button onClick={()=>setCursor({before:page.next!,revision:page.revision})}>Next 20 returns</button>}</div>
  </>}
 </section>;
}
