'use client';
import {useState} from 'react';
import {claimReasons,type ClaimState,type FoodClaim} from '../shared/food-claim';
import type {FoodHistoryPage} from '../shared/food-contract';
import {has,personName,type RecordOf,type Workspace} from '../shared/types';
import {displayTime,localDate} from '../shared/local-time';
import type {Send} from './workspace';
type Props={entry:FoodHistoryPage['entries'][number];r:RecordOf<'fooditem'>;w:Workspace;send:Send;busy:boolean};
export function InvoiceClaim({entry,r,w,send,busy}:Props){
 const [open,setOpen]=useState(false),invoice=entry.event.invoiceLine;if(!invoice)return null;
 const claim=entry.invoiceClaim,mayEdit=has(w.me,'location.manage')||has(w.me,'orders.review'),today=localDate(new Date().toISOString(),w.location.timezone);
 if(claim)return <p><strong>Supplier issue {claim.claim.reference}: {claim.latest?.state==='closed'?'internally closed':'pending follow-up'}.</strong> Open it in Supplier issue follow-up, or find its original entry in this item’s history to continue or correct it. Issued credits remain separate records.</p>;
 if(entry.invoiceVoided||!mayEdit)return null;
 return <section aria-label="Invoice supplier issue"><button disabled={busy} onClick={()=>setOpen(!open)}>{open?'Close issue form':'Track a supplier issue'}</button>{open&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await send('fooditem.claim',{invoiceRevision:entry.revision,reference:f.get('reference'),openedDate:f.get('openedDate'),reason:f.get('reason'),details:f.get('details'),followUpDate:f.get('followUpDate'),quantity:f.get('quantity'),quantityUnit:invoice.invoiceUnit,amount:f.get('amount'),confirmed:f.get('confirmed')==='on'},r))setOpen(false)}}><fieldset disabled={busy}><h4>Track a supplier issue</h4><p>Keep a pending shortage, damage, return or price question together for invoice {invoice.invoiceNumber}, line {invoice.lineReference}. Saving is internal follow-up; it does not submit a claim or create a supplier credit.</p>
 <div className="food-controls"><label className="shared-field">Internal issue reference<input name="reference" required maxLength={100} placeholder="A reference your team can recognize"/></label><label className="shared-field">Issue date<input name="openedDate" type="date" required defaultValue={today} min={invoice.invoiceDate} max={today}/></label><label className="shared-field">Issue reason<select name="reason">{Object.entries(claimReasons).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="shared-field">Follow-up date<input name="followUpDate" type="date" required defaultValue={today} min={invoice.invoiceDate}/></label></div>
 <div className="food-controls"><label className="shared-field">Quantity in question ({invoice.invoiceUnit}, optional)<input name="quantity" type="number" step="any" min="0" max={invoice.quantity} placeholder="Unknown or not checked"/></label><label className="shared-field">Net amount in question (USD, optional)<input name="amount" type="number" step="0.01" min="0" max={invoice.lineTotalCents/100} placeholder="Unknown or not checked"/></label></div><p>Use the original invoice unit and net line amount. Leave unchecked figures blank; quantity and amount are separate facts and are not calculated from each other. Explain their source below.</p><label className="shared-field">Issue facts and source reference<textarea name="details" required maxLength={2000} placeholder="What differs, how the quantity or amount was checked, and where to find the source evidence"/></label><p>Describe any actual supplier contact in your notes. A source reference is not an uploaded attachment. This entry does not change stock, cost, recorded credits or accounting.</p><label className="food-check"><input name="confirmed" type="checkbox" required/>I checked these facts for internal follow-up.</label><button className="shared-primary">Save pending supplier issue</button></fieldset></form>}</section>;
}
export function SupplierClaimHistory({entry,r,w,send,busy}:Props){
 const [editing,setEditing]=useState(false),[state,setState]=useState<ClaimState>('pending'),claim=entry.event.supplierClaim;if(!claim)return null;
 const latest=entry.claimLatest,status=latest?.state??'pending',followUp=latest?.followUpDate??claim.followUpDate,mayEdit=has(w.me,'location.manage')||has(w.me,'orders.review');
 const today=localDate(new Date().toISOString(),w.location.timezone);
 return <section className="food-waste-history" aria-label={`Supplier issue ${claim.reference}`}><h4>Supplier issue {claim.reference} · {status==='pending'?'Pending follow-up':status==='closed'?'Internally closed':'Cancelled record'}</h4><p>{claimReasons[claim.reason]} · opened {claim.openedDate} · {claim.invoice.sku.vendor} · invoice {claim.invoice.invoiceNumber}, line {claim.invoice.lineReference}</p><p className="food-preserve">Original facts: {claim.details}</p><p>Original invoice: {claim.invoice.quantity} {claim.invoice.invoiceUnit}; supplier pack {claim.invoice.sku.packCount??'?'} × {claim.invoice.sku.unitQty??'?'} {claim.invoice.sku.unitUOM} / {claim.invoice.sku.purchaseUnit}.</p>
 <ClaimImpactFacts claim={claim}/>{status==='pending'&&<p><strong>Follow-up {followUp}{followUp<today?' · overdue':followUp===today?' · due today':''}</strong>. This date is an internal reminder in this view; no notification has been sent.</p>}
 {latest&&<p className="food-preserve">Latest update by {personName(w,latest.by)}, {displayTime(latest.at,w.location.timezone)}: {latest.note}</p>}
 <p className="shared-muted">Internal closure does not verify supplier acceptance, an issued credit, payment or settlement. Record issued credit documents separately. Earlier facts and updates remain in this item’s history. To correct the original quantity or amount, cancel the incorrect record with a reason and open a corrected issue from its invoice.</p>
 {mayEdit&&status!=='cancelled'&&<><button disabled={busy} onClick={()=>{setState('pending');setEditing(!editing)}}>{editing?'Keep current issue status':status==='closed'?'Reopen or correct supplier issue':'Update supplier follow-up'}</button>{editing&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await send('fooditem.claim-update',{claimRevision:entry.revision,state,followUpDate:f.get('followUpDate'),note:f.get('note')},r))setEditing(false)}}><fieldset disabled={busy}><label className="shared-field">Internal issue status<select value={state} onChange={e=>setState(e.target.value as ClaimState)}><option value="pending">{status==='closed'?'Reopen for follow-up':'Keep pending follow-up'}</option>{status!=='closed'&&<option value="closed">Close internal follow-up</option>}<option value="cancelled">Cancel incorrect record</option></select></label>{state==='pending'&&<label className="shared-field">Next follow-up date<input name="followUpDate" type="date" required min={claim.openedDate} defaultValue={followUp||today}/></label>}
 <label className="shared-field">Follow-up facts or reason<textarea name="note" maxLength={2000} required placeholder={state==='cancelled'?'Explain the incorrect record. The original and all updates stay in history.':'What was checked, any actual contact, and the next step or closing outcome'}/></label>{state==='cancelled'&&<p>Cancellation corrects this internal record only. It cannot cancel a request already made to the supplier. Open a corrected issue from the invoice afterward.</p>}<button className="shared-primary">Save issue update</button></fieldset></form>}</>}
 </section>;
}
export function ClaimUpdateHistory({entry,w}:{entry:Props['entry'];w:Workspace}){const update=entry.event.claimUpdate;if(!update)return null;return <p className="food-preserve"><strong>Supplier issue entry {update.claimRevision}: {update.state}</strong>{update.followUpDate?` · follow-up ${update.followUpDate}`:''}<br/>{update.note}<br/>{personName(w,update.by)}, {displayTime(update.at,w.location.timezone)}. Retained update; the original issue shows its current status.</p>}

export function ClaimImpactFacts({claim}:{claim:FoodClaim}){
 const impact=claim.impact;
 return <p>Quantity in question: <strong>{impact?.quantity===undefined?'Not recorded':`${impact.quantity} ${impact.unit}`}</strong><br/>Net amount in question: <strong>{impact?.amountCents===undefined?'Not recorded':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(impact.amountCents/100)}</strong>. These are source-checked internal issue facts, not an issued credit or settlement.</p>;
}
