'use client';
import {useEffect,useRef,useState} from 'react';
import type {Command,RecordOf,Workspace} from '../shared/types';
import {has} from '../shared/types';
import type {FoodTransfer,TransferPage,TransferDetail} from '../shared/food-transfer';
import {transferPending} from '../shared/food-transfer';
import {displayTime} from '../shared/local-time';
import {transferFormTimestamp} from '../shared/food-transfer-time';
import {TransferReceiptForm,ReceiptUnitFacts} from './food-transfer-receipt-units';
export {TransferReceiptForm} from './food-transfer-receipt-units';
import {TransferDestinationMatch,MatchedItemFacts} from './food-transfer-match';
import {TransferParcels,ParcelFacts,TransferTimeFields} from './food-transfer-parcels';
import {TransferManifestPanel} from './food-transfer-manifest';
import {TransferDateFilter,TransferWindowNote,type TransferDates} from './food-transfer-dates';
const qty=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:6}).format(n);
const field=(f:FormData,n:string)=>String(f.get(n)??'');
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="shared-field">{label}{children}</label>}
class ResponseError extends Error{constructor(message:string,public status:number){super(message)}}
async function response<T>(r:Response):Promise<T>{const v=await r.json() as {error?:string};if(!r.ok)throw new ResponseError(v?.error??'Transfer request failed.',r.status);return v as T;}
export function FoodTransfers({w,apiRoot,dataset,item,onBusy,commissaryOnly}:{commissaryOnly?:boolean;w:Pick<Workspace,'location'|'me'>;apiRoot:string;dataset:'demo'|'operating';item?:RecordOf<'fooditem'>;onBusy:(v:boolean)=>void}){
 const [view,setView]=useState('incoming'),[status,setStatus]=useState('sent'),[cursor,setCursor]=useState<{before:number;revision?:number}>({before:0}),[reload,setReload]=useState(0),[selected,setSelected]=useState(''),[after,setAfter]=useState(0),[historyRevision,setHistoryRevision]=useState<number>(),[dispatching,setDispatching]=useState(!!item);
 const [page,setPage]=useState<TransferPage|null>(null),[detail,setDetail]=useState<TransferDetail|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState<Command|null>(null),[saving,setSaving]=useState(false);
 const [query,setQuery]=useState(''),[search,setSearch]=useState('');
 const [dates,setDates]=useState<TransferDates>({from:'',through:''});
 const inFlight=useRef(false),pendingRef=useRef<Command|null>(null);const busy=saving||!!pending;
 useEffect(()=>{const abort=new AbortController();setError('');setPage(null);setDetail(null);
  const params=new URLSearchParams({locationId:w.location.id,dataset,...(selected?{recordId:selected,after:String(after),...(historyRevision===undefined?{}:{revision:String(historyRevision)})}:{view,status,q:query,...dates,before:String(cursor.before),...(cursor.revision===undefined?{}:{revision:String(cursor.revision)})})});
  void fetch(apiRoot+'/food/transfers?'+params,{signal:abort.signal}).then(async r=>{const v=await response<TransferPage|TransferDetail>(r);if(abort.signal.aborted)return;if('transfer'in v)setDetail(v);else setPage(v)}).catch(e=>{if(!abort.signal.aborted)setError(e.message)});return()=>abort.abort();
 },[w.location.id,apiRoot,dataset,view,status,query,dates,cursor,reload,selected,after,historyRevision]);
 useEffect(()=>{if(!busy)return;const stop=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',stop);return()=>window.removeEventListener('beforeunload',stop)},[busy]);
 const save=async(c:Command)=>{if(inFlight.current)return;inFlight.current=true;setSaving(true);onBusy(true);setError('');setNotice('');
  try{const r=await response<{recordId:string;revision:number}>(await fetch(apiRoot+'/food/transfers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(c)}));pendingRef.current=null;setPending(null);setDispatching(false);setSelected(r.recordId);setAfter(0);setHistoryRevision(undefined);setReload(n=>n+1);setNotice('Transfer record saved. Physical counts were not changed.');onBusy(false)}
  catch(e){if(e instanceof ResponseError&&e.status<500){pendingRef.current=null;setPending(null);onBusy(false)}setError(e instanceof Error?e.message:'Save not confirmed.');}
  finally{inFlight.current=false;setSaving(false)}
 };
 const send=(action:string,input:Record<string,unknown>,r?:FoodTransfer)=>{if(pendingRef.current||inFlight.current)return;const c:Command={requestId:crypto.randomUUID(),locationId:w.location.id,action,input:{...input,dataset},...(r?{recordId:r.id,expectedRevision:r.revision}:{})};pendingRef.current=c;setPending(c);onBusy(true);void save(c)};
 const reset=()=>{setSelected('');setAfter(0);setHistoryRevision(undefined);setCursor({before:0});setReload(n=>n+1)};
 const d=detail?.transfer;
 return <section aria-label="Restaurant transfers"><h2>Restaurant transfers</h2><p>Record goods that actually left, then let the destination check what arrived. These records do not change physical counts or place an order.</p>
  {error&&<p role="alert" className="food-warning">{error}</p>}{notice&&<p role="status">{notice}</p>}{pending&&!saving&&<p className="food-warning">Save is not confirmed. Keep this restaurant open and retry the same request.<button onClick={()=>void save(pending)}>Retry transfer save</button></p>}
  <fieldset disabled={busy}>
   {!selected&&!dispatching&&<TransferManifestPanel key={w.location.id+dataset} w={w} apiRoot={apiRoot} dataset={dataset} onOpen={id=>{setSelected(id);setAfter(0);setHistoryRevision(undefined)}}/>}
   {selected?<button onClick={reset}>Back to transfer list</button>:<><div className="food-controls"><Field label="Transfer direction"><select value={view} onChange={e=>{setView(e.target.value);setCursor({before:0})}}><option value="incoming">Incoming to this restaurant</option><option value="outgoing">Outgoing from this restaurant</option></select></Field><Field label="Transfer status"><select value={status} onChange={e=>{setStatus(e.target.value);setCursor({before:0})}}><option value="sent">Open delivery checks</option><option value="received">Final checks</option><option value="differences">Rejected or missing goods</option><option value="voided">Voided records</option><option value="all">All transfers</option></select></Field></div><form className="shared-actions" style={{alignItems:'center'}} onSubmit={e=>{e.preventDefault();setQuery(search.trim());setCursor({before:0});setReload(n=>n+1)}}><Field label="Search transfers"><input value={search} maxLength={100} onChange={e=>setSearch(e.target.value)} placeholder="Reference, item or restaurant"/></Field><button>Search transfers</button>{(query||search)&&<button type="button" onClick={()=>{setQuery('');setSearch('');setCursor({before:0})}}>Clear transfer search</button>}</form><button onClick={reset}>Refresh transfers</button></>}
   {!page&&!detail&&!error&&<p role="status">Loading transfers…</p>}
   {!selected&&!dispatching&&<TransferDateFilter key={w.location.id+dataset} applied={dates} zone={w.location.timezone} onApply={value=>{setDates(value);setCursor({before:0});setReload(n=>n+1)}}/>}
   {!selected&&page&&<TransferWindowNote window={page.window}/>}
   {dispatching&&item&&page&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setError('');try{send('transfer.dispatch',{itemId:item.id,itemRevision:item.revision,destinationId:field(f,'destination'),reference:field(f,'reference'),quantity:field(f,'quantity'),dispatchedAt:transferFormTimestamp(f,w.location.timezone),note:field(f,'note'),confirmed:f.get('confirmed')==='on'})}catch(error){setError(error instanceof Error?error.message:'Check the dispatch time.')}}}>
    <h3>Record transfer out: {item.data.title}</h3><p>Original count pack: {item.data.packCount} × {item.data.unitQty} {item.data.unitUOM} / {item.data.purchaseUnit}.</p>
    {!page.routes.length?<p className="food-warning">No destination is configured for this restaurant and record set. Restaurant routes must be reconciled before transfers can be recorded.</p>:<><div className="food-controls"><Field label="Destination restaurant"><select name="destination" required defaultValue=""><option value="" disabled>Choose destination</option>{page.routes.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></Field><Field label="Transfer reference"><input name="reference" required maxLength={150} placeholder="Trip or transfer slip reference"/></Field><Field label={'Sent quantity in '+item.data.purchaseUnit}><input name="quantity" required type="number" min="0.000001" max="1000000" step="any"/></Field><TransferTimeFields zone={w.location.timezone} label="Dispatch"/><Field label="Dispatch note"><textarea name="note" maxLength={1000}/></Field></div><label className="food-check"><input name="confirmed" type="checkbox" required/>I checked the destination and the goods actually left in this stated count unit.</label><button className="shared-primary">Save dispatched transfer</button></>}
   </form>}
   {!selected&&page&&<><div className="food-summary" aria-label="Transfer review counts"><span>Open delivery checks<strong>{qty(page.totals.open)}</strong></span><span>Rejected or missing<strong>{qty(page.totals.differences)}</strong></span><span>Final checks<strong>{qty(page.totals.final)}</strong></span></div><p>Transfer counts for this direction{page.query?' and search':''}, across all pages. A transfer can have rejected goods while more are expected. Pending goods are not missing; recorded differences do not show whether a claim was settled.{page.totals.voided>0&&<> {qty(page.totals.voided)} voided {page.totals.voided===1?'record':'records'} excluded from these counts.</>}</p>{page.query&&<p>Applied search: {page.query}</p>}{!page.entries.length&&<p>No transfers match this view.</p>}{page.entries.map(r=><article key={r.id} className="food-card"><TransferFacts r={r} w={w}/>{r.parcelTotals&&<p>{r.parcelTotals.records} active parcel records · {qty(r.parcelTotals.arrived)} {r.dispatch.item.pack.purchaseUnit} with arrival recorded · {qty(r.parcelTotals.awaitingArrival)} awaiting arrival record. Receiving checks remain separate.</p>}<button onClick={()=>{setSelected(r.id);setAfter(0);setHistoryRevision(undefined)}}>Open transfer {r.dispatch.reference}</button></article>)}<div className="shared-actions"><span>{page.entries.length} shown · {qty(page.total)} matching {page.total===1?'transfer':'transfers'}</span>{cursor.before>0&&<button onClick={()=>setCursor({before:0})}>First transfer page</button>}{page.next!==null&&<button onClick={()=>setCursor({before:page.next!,revision:page.revision})}>Next 20 transfers</button>}</div></>}
   {d&&<article className="food-card" key={d.id+':'+d.revision}><TransferFacts r={d} w={w}/>
    {!commissaryOnly&&<TransferDestinationMatch d={d} w={w} apiRoot={apiRoot} review={detail?.destinationMatchReview} send={send}/>}
    <TransferParcels d={d} w={w} send={send}/>
    {d.status!=='voided'&&d.destinationId===w.location.id&&<>
     {d.status==='sent'&&<TransferReceiptForm d={d} review={detail?.destinationMatchReview} zone={w.location.timezone} send={send}/>}
     {d.receipt&&(d.receipt.by===w.me.id||has(w.me,'location.manage')||has(w.me,'orders.review'))&&<TransferReceiptForm d={d} review={detail?.destinationMatchReview} zone={w.location.timezone} send={send} correction/>}
    </>}
    {d.status==='sent'&&!d.receipt&&!(d.parcels??[]).some(p=>!p.void)&&d.sourceId===w.location.id&&(d.dispatch.by===w.me.id||has(w.me,'location.manage')||has(w.me,'orders.review'))&&<details><summary>Void incorrect dispatch record</summary><p>Voiding corrects a mistaken record. It does not cancel transport or undo a physical movement.</p><form onSubmit={e=>{e.preventDefault();send('transfer.void',{reason:field(new FormData(e.currentTarget),'reason')},d)}}><Field label="Reason for voiding dispatch"><textarea name="reason" required maxLength={1000}/></Field><button>Void incorrect record</button></form></details>}
    <h3>Retained transfer history</h3><p>Each check shows the totals known then. Do not add history rows together.</p>{detail!.events.map(e=><div key={e.revision}><p>{displayTime(e.at,w.location.timezone)} · {e.byName} · {e.action}{e.reason?' — '+e.reason:''}</p>{e.parcel&&<ParcelFacts p={e.parcel} unit={d.dispatch.item.pack.purchaseUnit} zone={w.location.timezone}/>}{e.destinationMatch&&<MatchedItemFacts match={e.destinationMatch}/>}{e.receipt&&<><ReceiptUnitFacts receipt={e.receipt}/><p>{e.receipt.complete===false?'Open check':'Final check'}: accepted {qty(e.receipt.accepted)}, rejected {qty(e.receipt.rejected)}, {e.receipt.complete===false?'pending '+qty(transferPending(d.dispatch,e.receipt)):'missing '+qty(e.receipt.missing)} {d.dispatch.item.pack.purchaseUnit}. Checked {displayTime(e.receipt.receivedAt,w.location.timezone)}. {e.receipt.reason} {e.receipt.note}</p></>}</div>)}{after>0&&<button onClick={()=>{setAfter(0);setHistoryRevision(undefined)}}>First history page</button>}{detail!.next!==null&&<button onClick={()=>{setAfter(detail!.next!);setHistoryRevision(d.revision)}}>More transfer history</button>}
   </article>}
  </fieldset>
 </section>;
}
function TransferFacts({r,w}:{r:FoodTransfer;w:Pick<Workspace,'location'|'me'>}){const d=r.dispatch,p=d.item.pack;return <><h3>{d.item.title} · {d.reference}</h3><p>{r.sourceName} → {r.destinationName} · {r.status==='sent'?(r.receipt?'Delivery check open — more expected':'Awaiting destination check'):r.status==='received'?'Final destination check':'Voided record'}</p><p>{qty(d.quantity)} {p.purchaseUnit} dispatched · {displayTime(d.dispatchedAt,w.location.timezone)} · {d.byName}</p><p>Original pack: {p.packCount} × {p.unitQty} {p.unitUOM} / {p.purchaseUnit}. Item {d.item.controlNumber}. {d.note}</p>{r.receipt&&<><div className="food-summary"><span>Accepted<strong>{qty(r.receipt.accepted)} {p.purchaseUnit}</strong></span><span>Rejected<strong>{qty(r.receipt.rejected)} {p.purchaseUnit}</strong></span><span>{r.receipt.complete===false?'Pending':'Missing'}<strong>{qty(r.receipt.complete===false?transferPending(d,r.receipt):r.receipt.missing)} {p.purchaseUnit}</strong></span></div><ReceiptUnitFacts receipt={r.receipt}/><p>Checked {displayTime(r.receipt.receivedAt,w.location.timezone)} by {r.receipt.byName}. {r.receipt.reason} {r.receipt.note}</p></>}</>}
