'use client';
import {useEffect,useRef,useState} from 'react';
import {has,personName,type Workspace,type RecordOf,type Command} from '../shared/types';
import {foodViews,foodPurchaser,type FoodView} from '../shared/food-navigation';
import {parseFoodItem,parseFoodRecipe} from '../shared/food';
import {foodItemCost,foodUnits,type FoodSource} from '../shared/food-model';
import type {FoodPage,FoodHistoryPage,FoodResult} from '../shared/food-contract';
import {displayTime} from '../shared/local-time';
import type {Send} from './workspace';
import './food.css';
import {WasteForm,WasteHistory} from './food-waste';
import {InvoiceForm,InvoiceHistory} from './food-invoice';
import {CreditHistory} from './food-credit';
import {ReturnCreditHistory} from './food-return-credit';
import {SupplierReturnHistory} from './food-return';
import {ExtraBillingHistory} from './food-excess-billing';
import {ReplacementReturnHistory} from './food-replacement-return';
import {ReplacementHistory} from './food-replacement';
import {ExtraReturnHistory} from './food-excess-return';
import {ExcessHistory} from './food-excess';
import {ReceivingHistory} from './food-receiving';
import {FoodWasteReport} from './food-waste-report';
import {FoodReceivingQueue} from './food-receiving-queue';
import {SupplierClaimHistory,ClaimUpdateHistory} from './food-claim';
import {FoodClaimQueue} from './food-claim-queue';
import {FoodReturnQueue} from './food-return-queue';
import {FoodTransfers} from './food-transfers';
import {FoodCatalogReview} from './food-catalog-review';
import {InvoiceCatalogPicker} from './food-invoice-catalog';
import type {InvoiceCatalogDraft} from '../shared/invoice-catalog-review';
import {FoodOrderGuide} from './food-order-guide';

const dollars=(v:number|null)=>v===null?'Not calculable':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:4}).format(v);
const isObject=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const isFoodPage=(v:unknown):v is FoodPage=>isObject(v)&&Array.isArray(v.records)&&Array.isArray(v.areas)&&isObject(v.costs)&&isObject(v.names)&&['revision','total','items','recipes','counted'].every(k=>typeof v[k]==='number')&&(v.next===null||typeof v.next==='string');
const isHistoryPage=(v:unknown):v is FoodHistoryPage=>isObject(v)&&Array.isArray(v.entries)&&(v.next===null||typeof v.next==='number');
const isResult=(v:unknown):v is FoodResult=>isObject(v)&&typeof v.foodRevision==='number'&&typeof v.added==='number'&&typeof v.existing==='number';
class FoodResponseError extends Error{constructor(message:string,public status:number){super(message)}}
async function responseValue<T>(response:Response,check:(v:unknown)=>v is T):Promise<T>{const value:unknown=await response.json();if(!response.ok)throw new FoodResponseError(isObject(value)&&typeof value.error==='string'?value.error:'Food request failed.',response.status);if(!check(value))throw new Error('Unexpected food response. Refresh before continuing.');return value;}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="shared-field">{label}{children}</label>}
type FoodSend=(action:string,input:Record<string,unknown>,record?:RecordOf<'fooditem'>)=>Promise<FoodResult|null>;
export function FoodWorkspace({w,apiRoot,recipesOnly=false,initialView='items',onBusy}:{w:Workspace;apiRoot:string;recipesOnly?:boolean;initialView?:FoodView;onBusy:(v:boolean)=>void}){
 const [dataset,setDataset]=useState<FoodSource['dataset']>('operating'),[query,setQuery]=useState(''),[area,setArea]=useState(''),[importing,setImporting]=useState(false);
 const [page,setPage]=useState<FoodPage|null>(null),[after,setAfter]=useState(''),[reload,setReload]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[pending,setPending]=useState<Command|null>(null);
 const inFlight=useRef(false),pendingRef=useRef<Command|null>(null);
 const [loadError,setLoadError]=useState('');
 const [invoiceBatchBusy,setInvoiceBatchBusy]=useState(false);
 const lockInvoiceBatch=(v:boolean)=>{setInvoiceBatchBusy(v);onBusy(v)};
 const [invoiceReview,setInvoiceReview]=useState(!recipesOnly&&initialView==='invoices'&&foodPurchaser(w.me)),[invoiceDraft,setInvoiceDraft]=useState<InvoiceCatalogDraft>(),[invoiceEpoch,setInvoiceEpoch]=useState(0);
 const [transfers,setTransfers]=useState(!recipesOnly&&initialView==='transfers'),[transferItem,setTransferItem]=useState<RecordOf<'fooditem'>>(),[transferBusy,setTransferBusy]=useState(false);
 const lockTransfer=(v:boolean)=>{setTransferBusy(v);onBusy(v)};
 const [reporting,setReporting]=useState(!recipesOnly&&initialView==='waste'),[receiving,setReceiving]=useState(!recipesOnly&&initialView==='receiving'),[returns,setReturns]=useState(!recipesOnly&&initialView==='returns'),[claims,setClaims]=useState(!recipesOnly&&initialView==='claims'),[focused,setFocused]=useState<{id:string;sequence:number;from:'receiving'|'returns'|'claims'|'invoice'}|null>(null);
 useEffect(()=>{const abort=new AbortController();setPage(null);setLoadError('');if(reporting||receiving||returns||claims||transfers)return;const params=new URLSearchParams({locationId:w.location.id,dataset,kind:recipesOnly?'foodrecipe':'fooditem',q:focused?'':query,area:focused?'':area,after:focused?'':after,...(focused?{itemId:focused.id}:{})});
  void fetch(`${apiRoot}/food?${params}`,{signal:abort.signal}).then(async response=>{const value=await responseValue(response,isFoodPage);if(!abort.signal.aborted)setPage(value);}).catch(e=>{if(!abort.signal.aborted)setLoadError(e instanceof Error?e.message:'Unable to load food records.');});return()=>abort.abort();
 },[w.location.id,apiRoot,dataset,recipesOnly,query,area,after,reload,reporting,receiving,returns,claims,focused,transfers]);
 const save=async(command:Command):Promise<FoodResult|null>=>{if(inFlight.current)return null;inFlight.current=true;setSaving(true);setError('');setNotice('');try{const response=await fetch(`${apiRoot}/food`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)}),result=await responseValue(response,isResult);pendingRef.current=null;setPending(null);setReload(n=>n+1);setInvoiceEpoch(n=>n+1);return result;}catch(e){if(e instanceof FoodResponseError&&e.status<500){pendingRef.current=null;setPending(null)}setError(e instanceof Error?e.message:'Save not confirmed.');return null;}finally{inFlight.current=false;setSaving(false)}};
 const foodSend:FoodSend=async(action,input,record)=>{if(inFlight.current||pendingRef.current)return null;const command:Command={requestId:crypto.randomUUID(),locationId:w.location.id,action,input,...(record?{recordId:record.id,expectedRevision:record.revision}:{})};pendingRef.current=command;setPending(command);return save(command)};
 const send:Send=async(action,input,record)=>{if(record&&record.kind!=='fooditem')return false;return !!await foodSend(action,input,record)};
 const busy=saving||!!pending||transferBusy||invoiceBatchBusy,items=page?.records.flatMap(r=>r.kind==='fooditem'?[r]:[])??[],recipes=page?.records.flatMap(r=>r.kind==='foodrecipe'?[r]:[])??[],areas=page?.areas??[];
 const selectDataset=(value:FoodSource['dataset'])=>{setDataset(value);setAfter('');setArea('');setFocused(null);setInvoiceDraft(undefined)};
 const activeView=foodViews[transfers?'transfers':receiving?'receiving':returns?'returns':claims?'claims':reporting?'waste':invoiceReview?'invoices':'items'];
 return <section className="food-workspace"><p className="jmax-eyebrow">{w.location.name} · Food</p><div className="shared-heading"><h1>{recipesOnly?'Recipes and build cards':activeView.title}</h1>{has(w.me,'location.manage')&&<button disabled={busy} onClick={()=>setImporting(!importing)}>{importing?'Close import':'Import Jeff’s export'}</button>}</div>
 <p>{recipesOnly?'Recipe definitions and pack-based ingredient costs from the food source.':activeView.description}</p>
 <div className="food-controls"><Field label="Records"><select disabled={busy} value={dataset} onChange={e=>selectDataset(e.target.value as FoodSource['dataset'])}><option value="operating">Restaurant records</option><option value="demo">Demo / training records</option></select></Field>{!reporting&&!receiving&&!returns&&!claims&&!transfers&&!focused&&<><Field label="Search"><input type="search" value={query} maxLength={100} onChange={e=>{setQuery(e.target.value);setAfter('')}} placeholder="Name or item code"/></Field>{!recipesOnly&&<Field label="Storage area"><select value={area} onChange={e=>{setArea(e.target.value);setAfter('')}}><option value="">All storage areas</option>{areas.map(a=><option key={a} value={a}>{a||'Unassigned'}</option>)}</select></Field>}</>}</div>
 {(error||loadError)&&<p role="alert" className="food-warning">{error||loadError}</p>}{notice&&<p role="status">{notice}</p>}{pending&&!saving&&<button onClick={async()=>{if(await save(pending))setNotice('The pending save is confirmed.')}}>Retry the same pending save</button>}<button disabled={busy} onClick={()=>{setError('');setReload(n=>n+1)}}>Refresh food records</button>
 {dataset==='demo'&&<p className="food-warning" role="status">DEMO DATA — practice records only. These are not restaurant stock or operating costs.</p>}
 {!recipesOnly&&<button disabled={busy} onClick={()=>{setInvoiceReview(false);setInvoiceDraft(undefined);setClaims(false);setReturns(false);setTransfers(false);setReporting(!reporting);setReceiving(false);setFocused(null);setImporting(false)}}>{reporting?'Back to food items':'Review waste and estimated costs'}</button>}
 {!recipesOnly&&<button disabled={busy} onClick={()=>{setInvoiceReview(false);setInvoiceDraft(undefined);setClaims(false);setReturns(false);setTransfers(false);setReceiving(!receiving);setReporting(false);setFocused(null);setImporting(false)}}>{receiving?'Back to food items':'Review delivery checks'}</button>}
 {!recipesOnly&&<button disabled={busy} onClick={()=>{setInvoiceReview(false);setInvoiceDraft(undefined);setClaims(false);setReturns(false);setTransfers(!transfers);setTransferItem(undefined);setReceiving(false);setReporting(false);setFocused(null);setImporting(false)}}>{transfers?'Back to food items':'Review restaurant transfers'}</button>}
 {!recipesOnly&&<button disabled={busy} onClick={()=>{setInvoiceReview(false);setInvoiceDraft(undefined);setClaims(false);setReturns(!returns);setTransfers(false);setReporting(false);setReceiving(false);setFocused(null);setImporting(false)}}>{returns?'Back to food items':'Review supplier returns'}</button>}
 {!recipesOnly&&<button disabled={busy} onClick={()=>{setInvoiceReview(false);setInvoiceDraft(undefined);setClaims(!claims);setReturns(false);setTransfers(false);setReporting(false);setReceiving(false);setFocused(null);setImporting(false)}}>{claims?'Back to food items':'Review supplier issues'}</button>}
 {!recipesOnly&&(has(w.me,'location.manage')||has(w.me,'orders.review'))&&<button disabled={busy} onClick={()=>{setInvoiceReview(!invoiceReview);setClaims(false);setReturns(false);setTransfers(false);setReporting(false);setReceiving(false);setFocused(null);setInvoiceDraft(undefined);setImporting(false)}}>{invoiceReview?'Close invoice CSV matching':'Match invoice CSV to items'}</button>}
 {invoiceReview&&foodPurchaser(w.me)&&!recipesOnly&&!claims&&!returns&&!transfers&&!reporting&&!receiving&&<InvoiceCatalogPicker key={w.location.id+':'+dataset} locationId={w.location.id} dataset={dataset} apiRoot={apiRoot} disabled={busy} refreshVersion={invoiceEpoch} onBatchBusy={lockInvoiceBatch} onBatchChanged={()=>setReload(n=>n+1)} onOpenSaved={(id,sequence)=>{setInvoiceDraft(undefined);setFocused({id,sequence,from:'invoice'});setReload(n=>n+1)}} onReset={()=>{setInvoiceDraft(undefined);setFocused(null)}} onSelect={draft=>{setInvoiceDraft(draft);setFocused({id:draft.itemId,sequence:0,from:'invoice'});setReload(n=>n+1)}}/>}
 {claims&&<FoodClaimQueue key={w.location.id+':'+dataset+':'+reload} w={w} apiRoot={apiRoot} dataset={dataset} onOpen={(id,sequence)=>{setFocused({id,sequence,from:'claims'});setClaims(false)}}/>}
 {returns&&<FoodReturnQueue key={w.location.id+':'+dataset+':'+reload} w={w} apiRoot={apiRoot} dataset={dataset} onOpen={(id,sequence)=>{setFocused({id,sequence,from:'returns'});setReturns(false)}}/>}
 {transfers&&<FoodTransfers key={w.location.id+':'+dataset} w={w} apiRoot={apiRoot} dataset={dataset} item={transferItem} onBusy={lockTransfer}/>}
 {focused&&<button disabled={busy} onClick={()=>{const from=focused.from;setFocused(null);setReceiving(from==='receiving');setReturns(from==='returns');setClaims(from==='claims')}}>{focused.from==='invoice'?'Back to food items':focused.from==='claims'?'Back to supplier issues':focused.from==='returns'?'Back to return review':'Back to delivery queue'}</button>}
 {receiving&&<FoodReceivingQueue key={w.location.id+':'+dataset+':'+reload} w={w} apiRoot={apiRoot} dataset={dataset} onOpen={(id,sequence)=>{setFocused({id,sequence,from:'receiving'});setReceiving(false)}}/>}
 {reporting&&<FoodWasteReport key={w.location.id+':'+dataset+':'+reload} w={w} apiRoot={apiRoot} dataset={dataset}/>}
 {importing&&<FoodImport w={w} send={foodSend} busy={busy} onDataset={selectDataset}/>}
 {!recipesOnly&&foodPurchaser(w.me)&&!invoiceReview&&!claims&&!returns&&!transfers&&!reporting&&!receiving&&<FoodOrderGuide key={w.location.id+':'+dataset+':'+reload} locationId={w.location.id} locationName={w.location.name} dataset={dataset} apiRoot={apiRoot} disabled={busy}/>}
 {!reporting&&!receiving&&!returns&&!claims&&!transfers&&!page&&!loadError&&<p role="status">Loading this food page…</p>}
 {page&&<div className="food-summary"><span><strong>{page.items}</strong> food items</span><span><strong>{page.counted}</strong> with a saved count <small>(check each count’s date)</small></span><span><strong>{page.recipes}</strong> recipes</span></div>}
 {page&&!page.items&&!page.recipes&&<div className="jmax-panel"><h2>{dataset==='demo'?'No demo records imported':'No restaurant food records imported'}</h2><p>No food definitions have been imported into this restaurant workspace. A shared database upload does not automatically appear here. An owner can review a restaurant-specific item and recipe export; imported physical counts start blank.</p></div>}
 {!recipesOnly&&items.map(r=><FoodItemCard key={r.id+':'+r.revision+':'+(focused?.sequence??0)+':'+(focused?.from==='invoice'?invoiceDraft?.source.sha256+':'+invoiceDraft?.source.row.recordNumber+':'+invoiceDraft?.skuId:'')} invoiceDraft={focused?.from==='invoice'?invoiceDraft:undefined} onInvoiceSaved={()=>setInvoiceDraft(undefined)} r={r} w={w} send={send} busy={busy} apiRoot={apiRoot} historySequence={focused?.sequence} onTransfer={()=>{setInvoiceReview(false);setInvoiceDraft(undefined);setClaims(false);setReturns(false);setTransferItem(r);setTransfers(true);setReceiving(false);setReporting(false);setFocused(null);setImporting(false)}}/>)}
 {recipesOnly&&recipes.map(r=>{const d=r.data,result=page!.costs[r.id]??{total:null,perYield:null,issues:['Cost not loaded']};return <article className="food-card" key={r.id}><div className="shared-heading"><h2>{d.title}</h2><span>{d.recipeType==='prep'?'Prep recipe':'Menu recipe'}</span></div><p>{d.menuCategory} · Yield: {d.yieldQty??'Missing'} {d.yieldUOM||'unit missing'}</p><div className="food-summary"><span>Ingredient total <strong>{dollars(result.total)}</strong></span><span>Per yield unit <strong>{dollars(result.perYield)}</strong></span></div>{result.issues.length>0&&<div className="food-warning"><strong>Cost needs review</strong><ul>{result.issues.map(s=><li key={s}>{s}</li>)}</ul></div>}
 <h3>Ingredients</h3><ul>{d.lines.map((l,i)=><li key={i}>{l.qty} {l.sourceType==='item'?`portion(s) · ${page!.names['fooditem:'+l.controlNumber]??l.controlNumber}`:`yield unit(s) · ${page!.names['foodrecipe:'+l.recipeId]??l.recipeId}`}</li>)}</ul>
 <h3>Method</h3><p className="food-preserve">{d.procedure||'Procedure not supplied in this export.'}</p><dl><dt>Portion note</dt><dd>{d.portionNote||'Not supplied'}</dd><dt>Equipment</dt><dd>{d.equipment||'Not supplied'}</dd><dt>Shelf life from source</dt><dd>{d.shelfLife||'Not supplied'}</dd></dl><p className="shared-muted">Source: {d.source.label} · {d.source.sourceRestaurantId} · {d.sourceId}. Prices use the dated preferred supplier packs; no live invoice feed is connected.</p></article>})}
 {page&&page.records.length===0&&(page.items>0||page.recipes>0)&&<p>No {recipesOnly?'recipes':'items'} in this view.</p>}
 {page&&<div className="shared-actions"><span>{page.records.length} shown · {page.total} matching records</span>{after&&<button onClick={()=>setAfter('')}>First page</button>}{page.next&&<button onClick={()=>setAfter(page.next!)}>Next 20 records</button>}</div>}
 <p className="shared-muted">Invoice review accepts the JMAX CSV template and supplier CSVs with reviewed column mappings. Prep production and Purchasing review use this restaurant’s saved Food records through their own work areas. Internal approval does not place a supplier order. Nothing on this screen sends an order or changes Toast.</p></section>;
}
function FoodItemCard({r,w,send,busy,apiRoot,historySequence,onTransfer,invoiceDraft,onInvoiceSaved}:{invoiceDraft?:InvoiceCatalogDraft;onInvoiceSaved:()=>void;r:RecordOf<'fooditem'>;w:Workspace;send:Send;busy:boolean;apiRoot:string;historySequence?:number;onTransfer:()=>void}){
 const d=r.data,cost=foodItemCost(d),[editing,setEditing]=useState(false),[counting,setCounting]=useState(false),[wasting,setWasting]=useState(false),[invoicing,setInvoicing]=useState(!!invoiceDraft&&invoiceDraft.itemId===r.id&&invoiceDraft.itemRevision===r.revision);
 const editAllowed=has(w.me,'location.manage')||has(w.me,'orders.review');
 return <article className="food-card"><div className="shared-heading"><h2>{d.title}</h2><span>{d.controlNumber}</span></div><p>{d.storageArea||'Storage area not set'} · Count unit: <strong>{d.purchaseUnit||'Not set'}</strong> · Par: {d.par??'Not set'}</p><div className="food-summary"><span>Last physical count <strong>{d.count?`${d.count.quantity} ${d.purchaseUnit}`:'Not counted'}</strong></span><span>Cost per portion <strong>{dollars(cost.costPerPortion)}</strong></span></div>
 {d.count&&<p>Counted {displayTime(d.count.at,w.location.timezone)} by {personName(w,d.count.by)}{d.count.note?' · '+d.count.note:''}</p>}
 <p>Portion: {d.portionSize??'Missing'} {d.portionUOM||'unit missing'}. Count pack: {d.packCount??'?'} × {d.unitQty??'?'} {d.unitUOM||'unit missing'}.</p>
 {cost.issues.length>0&&<p className="food-warning">{cost.issues.join(' · ')}</p>}
 <details><summary>Supplier packs and price dates ({d.vendorSkus.length})</summary>{d.vendorSkus.map(s=><p key={s.id}><strong>{s.vendor}</strong> · {s.vendorSku} · {s.packCount??'?'} × {s.unitQty??'?'} {s.unitUOM} / {s.purchaseUnit} · {dollars(s.price)} · Price dated {s.priceUpdatedAt||'unknown'}{s.priceSource?' · From reviewed invoice':''}{s.preferred?' · Preferred':''}{!s.available?' · Unavailable':''}</p>)}</details>
 <div className="shared-actions">{d.active&&!d.needsReview&&<button disabled={busy} onClick={onTransfer}>Record transfer out</button>}{d.active&&d.countActive&&<button onClick={()=>{setCounting(!counting);setWasting(false);setEditing(false);setInvoicing(false)}}>Record physical count</button>}{d.active&&<button onClick={()=>{setWasting(!wasting);setCounting(false);setEditing(false);setInvoicing(false)}}>Record waste</button>}{editAllowed&&<button onClick={()=>{setEditing(!editing);setCounting(false);setWasting(false);setInvoicing(false)}}>Correct item definition</button>}{editAllowed&&d.active&&<button onClick={()=>{setInvoicing(!invoicing);setCounting(false);setWasting(false);setEditing(false)}}>Record invoice line</button>}</div>
 {counting&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await send('fooditem.count',{quantity:f.get('quantity'),note:f.get('note'),confirmed:f.get('confirmed')==='on'},r))setCounting(false)}}><fieldset disabled={busy}><div className="food-controls"><Field label={`Count in ${d.purchaseUnit||'purchase units'}`}><input name="quantity" type="number" min="0" max="1000000" step="any" required placeholder="Enter a physical count"/></Field><Field label="Count note"><input name="note" maxLength={1000}/></Field></div><label className="food-check"><input type="checkbox" name="confirmed" required/>I physically counted this item in the stated unit. Zero means none on hand.</label><button className="shared-primary">Save count</button></fieldset></form>}
 {editing&&<FoodItemEditor r={r} send={send} busy={busy} onSaved={()=>setEditing(false)}/>}
 {wasting&&<WasteForm r={r} send={send} busy={busy} onSaved={()=>setWasting(false)}/>}
 {invoiceDraft&&invoiceDraft.itemRevision!==r.revision&&<p role="alert">This item changed after CSV matching. Refresh matches and saved lines to check its current packs.</p>}
 {invoicing&&<InvoiceForm apiRoot={apiRoot} draft={invoiceDraft?.itemId===r.id&&invoiceDraft.itemRevision===r.revision?invoiceDraft:undefined} r={r} w={w} send={send} busy={busy} onSaved={()=>{setInvoicing(false);onInvoiceSaved()}}/>}
 <FoodHistory r={r} w={w} apiRoot={apiRoot} send={send} busy={busy} initialSequence={historySequence}/></article>;
}
function FoodHistory({r,w,apiRoot,send,busy,initialSequence}:{r:RecordOf<'fooditem'>;w:Workspace;apiRoot:string;send:Send;busy:boolean;initialSequence?:number}){
 const [open,setOpen]=useState(!!initialSequence),[after,setAfter]=useState(initialSequence?initialSequence-1:0),[page,setPage]=useState<FoodHistoryPage|null>(null),[error,setError]=useState('');
 useEffect(()=>{if(!open)return;const abort=new AbortController();setPage(null);setError('');const params=new URLSearchParams({locationId:w.location.id,dataset:r.data.source.dataset,view:'history',recordId:r.id,after:String(after)});void fetch(`${apiRoot}/food?${params}`,{signal:abort.signal}).then(async response=>{const value=await responseValue(response,isHistoryPage);if(!abort.signal.aborted)setPage(value)}).catch(e=>{if(!abort.signal.aborted)setError(e.message)});return()=>abort.abort()},[open,after,apiRoot,w.location.id,r.id,r.data.source.dataset]);
 return <details open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>Source and change history</summary><p>{r.data.source.label} · {r.data.source.dataset} · source restaurant {r.data.source.sourceRestaurantId}. Imported {displayTime(r.data.source.importedAt,w.location.timezone)}.</p><p>Imported stock quantities are not treated as physical counts in JMAX.</p>{error&&<p role="alert">{error}</p>}{open&&!page&&!error&&<p>Loading history…</p>}{page?.entries.map(entry=><div key={entry.sequence}>{entry.event.history.map((h,i)=><p key={i}>{displayTime(h.at,w.location.timezone)} · {personName(w,h.actorId)} · {h.action}: {h.note}</p>)}<WasteHistory entry={entry} r={r} w={w} send={send} busy={busy}/><InvoiceHistory entry={entry} r={r} w={w} send={send} busy={busy} apiRoot={apiRoot}/><SupplierClaimHistory entry={entry} r={r} w={w} send={send} busy={busy}/><ClaimUpdateHistory entry={entry} w={w}/><CreditHistory entry={entry} r={r} w={w} send={send} busy={busy}/><ReplacementReturnHistory entry={entry} r={r} w={w} send={send} busy={busy}/><ReplacementHistory entry={entry} r={r} w={w} send={send} busy={busy}/><ReceivingHistory entry={entry} r={r} w={w} send={send} busy={busy}/><ExcessHistory entry={entry} r={r} w={w} send={send} busy={busy} apiRoot={apiRoot}/><ExtraBillingHistory entry={entry} r={r} w={w} send={send} busy={busy}/><ExtraReturnHistory entry={entry} r={r} w={w} send={send} busy={busy}/><SupplierReturnHistory entry={entry} r={r} w={w} send={send} busy={busy} apiRoot={apiRoot}/><ReturnCreditHistory entry={entry} r={r} w={w} send={send} busy={busy}/>{entry.event.count&&<p>Count pack at the time: {entry.event.count.pack.packCount} × {entry.event.count.pack.unitQty} {entry.event.count.pack.unitUOM}.</p>}{entry.event.definition&&<details><summary>Definition before correction</summary><pre className="food-preserve">{JSON.stringify(entry.event.definition.before,null,2)}</pre></details>}{entry.event.legacy&&<details><summary>Preserved earlier counts and corrections</summary><pre className="food-preserve">{JSON.stringify(entry.event.legacy,null,2)}</pre></details>}</div>)}{after>0&&<button onClick={()=>setAfter(0)}>First history page</button>}{page?.next&&<button onClick={()=>setAfter(page.next!)}>More history</button>}</details>
}
function FoodItemEditor({r,send,busy,onSaved}:{r:RecordOf<'fooditem'>;send:Send;busy:boolean;onSaved:()=>void}){
 const d=r.data;
 return <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const item={...d,name:f.get('name'),restaurantId:d.source.sourceRestaurantId,storageArea:f.get('storageArea'),purchaseUnit:f.get('purchaseUnit'),packCount:f.get('packCount'),unitQty:f.get('unitQty'),unitUOM:f.get('unitUOM'),portionSize:f.get('portionSize'),portionUOM:f.get('portionUOM'),par:f.get('par'),needsReview:f.get('needsReview')==='on',active:f.get('active')==='on',countActive:f.get('countActive')==='on',vendorSkus:d.vendorSkus.map((s,i)=>({...s,purchaseUnit:f.get(`purchaseUnit${i}`),packCount:f.get(`packCount${i}`),unitQty:f.get(`unitQty${i}`),unitUOM:f.get(`unitUOM${i}`),price:f.get(`price${i}`),priceUpdatedAt:f.get(`date${i}`),preferred:f.get('preferred')===s.id,available:f.get(`available${i}`)==='on'}))};if(await send('fooditem.configure',{item,reason:f.get('reason')},r))onSaved()}}><fieldset disabled={busy}><h3>Correct definition</h3><div className="food-controls"><Field label="Item name"><input name="name" defaultValue={d.title} required maxLength={200}/></Field><Field label="Storage area"><input name="storageArea" defaultValue={d.storageArea}/></Field><Field label="Count unit"><input name="purchaseUnit" defaultValue={d.purchaseUnit} placeholder="case, bag, each" maxLength={30}/></Field><Field label="Units in count pack"><input name="packCount" type="number" min="0" step="any" defaultValue={d.packCount??''}/></Field><Field label="Quantity per unit"><input name="unitQty" type="number" min="0" step="any" defaultValue={d.unitQty??''}/></Field><Unit name="unitUOM" label="Count pack measure" value={d.unitUOM}/><Field label="Portion size"><input name="portionSize" type="number" min="0" step="any" defaultValue={d.portionSize??''}/></Field><Unit name="portionUOM" label="Portion measure" value={d.portionUOM}/><Field label="Par in count units"><input name="par" type="number" min="0" step="any" defaultValue={d.par??''}/></Field></div>
 <div className="food-controls">{(['active','countActive','needsReview'] as const).map(key=><label className="food-check" key={key}><input type="checkbox" name={key} defaultChecked={d[key]}/>{{active:'Active item',countActive:'Include in counts',needsReview:'Mapping still needs review'}[key]}</label>)}</div>
 {d.vendorSkus.map((s,i)=><fieldset key={s.id}><legend>{s.vendor} · {s.vendorSku}</legend><div className="food-controls"><Field label="Supplier purchase unit"><input name={`purchaseUnit${i}`} defaultValue={s.purchaseUnit}/></Field><Field label="Units per supplier pack"><input name={`packCount${i}`} type="number" min="0" step="any" defaultValue={s.packCount??''}/></Field><Field label="Quantity per supplier unit"><input name={`unitQty${i}`} type="number" min="0" step="any" defaultValue={s.unitQty??''}/></Field><Unit name={`unitUOM${i}`} label="Supplier pack measure" value={s.unitUOM}/><Field label="Price for this purchase pack"><input name={`price${i}`} type="number" step="any" min="0" defaultValue={s.price??''}/></Field><Field label="Price date"><input name={`date${i}`} type="date" defaultValue={s.priceUpdatedAt}/></Field></div><label className="food-check"><input type="radio" name="preferred" value={s.id} defaultChecked={s.preferred}/>Preferred pack</label><label className="food-check"><input type="checkbox" name={`available${i}`} defaultChecked={s.available}/>Available</label></fieldset>)}
 <Field label="Source and reason for correction"><textarea name="reason" required maxLength={1000}/></Field><p>Changing the count pack requires a fresh count. Existing history stays saved.</p><button className="shared-primary">Save correction</button></fieldset></form>;
}
function Unit({name,label,value}:{name:string;label:string;value:string}){return <Field label={label}><select name={name} defaultValue={value}><option value="">Unknown</option>{value&&!foodUnits.includes(value)&&<option>{value}</option>}{foodUnits.map(u=><option key={u}>{u}</option>)}</select></Field>}

function FoodImport({w,send,busy,onDataset}:{w:Workspace;send:FoodSend;busy:boolean;onDataset:(s:FoodSource['dataset'])=>void}){
 const [file,setFile]=useState<Record<string,unknown>|null>(null),[name,setName]=useState(''),[sourceId,setSourceId]=useState(''),[dataset,setDataset]=useState<FoodSource['dataset']>('demo'),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState(''),[running,setRunning]=useState(false);
 const allItems=Array.isArray(file?.items)?file.items:[],allRecipes=Array.isArray(file?.dishes)?file.dishes:[],ids=[...new Set([...allItems,...allRecipes].map(r=>String(r?.restaurantId??'')))].filter(Boolean);
 const source:FoodSource={dataset,sourceRestaurantId:sourceId,label:name,importedAt:'',importedBy:w.me.id};
 const parsed:{kind:'fooditem'|'foodrecipe';row:unknown}[]=[],errors:string[]=[],keys=new Set<string>();
 for(const [kind,list] of [['fooditem',allItems],['foodrecipe',allRecipes]] as const){for(const row of list){if(row?.restaurantId!==sourceId)continue;try{const d=kind==='fooditem'?parseFoodItem(row,source):parseFoodRecipe(row,source),key=kind+':'+('controlNumber'in d?d.controlNumber:d.sourceId);if(keys.has(key))throw new Error('Duplicate identifier in this file: '+key);keys.add(key);parsed.push({kind,row});}catch(e){errors.push(e instanceof Error?e.message:'Invalid row');}}}
 const importRows=async()=>{setRunning(true);setError('');onDataset(dataset);let completed=0,existing=0;try{for(const kind of ['fooditem','foodrecipe'] as const){const pending=parsed.filter(r=>r.kind===kind);while(pending.length){const batch:unknown[]=[];let size=0;while(pending.length&&batch.length<25){const row=pending[0].row,bytes=new TextEncoder().encode(JSON.stringify(row)).length;if(size+bytes>80000&&batch.length)break;batch.push(pending.shift()!.row);size+=bytes;}setProgress(`Reviewed ${completed+existing} of ${parsed.length} definitions…`);const result=await send(`${kind}.import`,{dataset,sourceRestaurantId:sourceId,sourceLabel:name,destinationLocationId:w.location.id,confirmed:true,rows:batch});if(!result){setProgress(`${completed} additions confirmed; ${existing} existing definitions kept. Import stopped. Resolve the pending save, then review and retry the file; saved identifiers will be kept.`);return;}completed+=result.added;existing+=result.existing;}}setProgress(`${completed} new definitions saved; ${existing} existing definitions kept. No physical counts were imported.`);setConfirmed(false);}catch(e){setError(String(e));setProgress(`${completed} additions confirmed before interruption. Review before retrying.`);}finally{setRunning(false)}};
 return <div className="food-import"><h2>Review food export</h2><p>Choose Jeff’s JSON export with <code>items</code> and/or <code>dishes</code>. This imports food definitions only. Purchases, stock balances, prep sessions, supplier contacts and other sections stay out of this import.</p><fieldset disabled={busy||running}><Field label="Export file"><input type="file" accept=".json,application/json" onChange={async e=>{setError('');setFile(null);setConfirmed(false);setProgress('');const f=e.target.files?.[0];if(!f)return;try{if(f.size>5000000)throw new Error('Use an export under 5 MB.');const parsed=JSON.parse(await f.text());if(!parsed||typeof parsed!=='object'||Array.isArray(parsed)||(!Array.isArray(parsed.items)&&!Array.isArray(parsed.dishes)))throw new Error('Choose an item/recipe JSON export.');if((parsed.items?.length??0)+(parsed.dishes?.length??0)>2000)throw new Error('Split exports with more than 2,000 definitions.');setFile(parsed);setName(f.name);setSourceId('');setDataset('demo');}catch(err){setError(err instanceof Error?err.message:'Cannot read export.')}}}/></Field>
 {file&&<><div className="food-controls"><Field label="Source restaurant identifier"><select value={sourceId} onChange={e=>{setSourceId(e.target.value);setConfirmed(false)}}><option value="">Choose from this export</option>{ids.map(id=><option key={id}>{id}</option>)}</select></Field><Field label="Data type"><select value={dataset} onChange={e=>{setDataset(e.target.value as FoodSource['dataset']);setConfirmed(false)}}><option value="demo">Demo / training</option><option value="operating">Actual restaurant definitions</option></select></Field><Field label="Source label"><input value={name} onChange={e=>{setName(e.target.value);setConfirmed(false)}} maxLength={300}/></Field></div><p><strong>Destination: {w.location.name}</strong> · source: {sourceId||'not selected'} · {dataset}</p><p>{parsed.filter(r=>r.kind==='fooditem').length} items; {parsed.filter(r=>r.kind==='foodrecipe').length} recipes to review. Existing identifiers will be checked on the server and kept unchanged.</p>
 {errors.length>0&&<div className="food-warning" role="alert"><strong>{errors.length} invalid rows — fix them before importing.</strong><ul>{errors.slice(0,8).map((s,i)=><li key={i}>{s}</li>)}</ul></div>}
 <details><summary>Preview names ({parsed.length})</summary><ul>{parsed.map((r,i)=><li key={i}>{r.kind==='fooditem'?'Item':'Recipe'}: {String((r.row as Record<string,unknown>).name)}</li>)}</ul></details><label className="food-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the source restaurant, destination and data type. Definitions will be added; saved records will not be overwritten.</label><button className="shared-primary" disabled={!confirmed||!sourceId||!name.trim()||!parsed.length||!!errors.length} onClick={()=>void importRows()}>Import reviewed definitions</button></>}
 </fieldset>{error&&<p role="alert" className="food-warning">{error}</p>}{progress&&<p role="status">{progress}</p>}<FoodCatalogReview disabled={busy||running}/></div>;
}
