'use client';
import {useEffect,useState} from 'react';
import type {ClaimQueue,ClaimFilter} from '../shared/food-claim-queue';
import {claimReasons} from '../shared/food-claim';
import {ClaimImpactFacts} from './food-claim';
import type {Workspace} from '../shared/types';
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const valid=(v:unknown):v is ClaimQueue=>object(v)&&Array.isArray(v.entries)&&object(v.totals)&&typeof v.total==='number'&&typeof v.revision==='number'&&typeof v.today==='string'&&(v.next===null||typeof v.next==='number');
export function FoodClaimQueue({w,apiRoot,dataset,onOpen}:{w:Workspace;apiRoot:string;dataset:'demo'|'operating';onOpen:(id:string,sequence:number)=>void}){
 const [filter,setFilter]=useState<ClaimFilter>('pending'),[query,setQuery]=useState(''),[cursor,setCursor]=useState<{before:number;revision?:number;day?:string}>({before:0}),[reload,setReload]=useState(0),[page,setPage]=useState<ClaimQueue|null>(null),[error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();setPage(null);setError('');const params=new URLSearchParams({locationId:w.location.id,dataset,view:'claims',filter,q:query,before:String(cursor.before),...(cursor.revision===undefined?{}:{revision:String(cursor.revision),day:cursor.day??''})});
 void fetch(`${apiRoot}/food?${params}`,{signal:abort.signal}).then(async response=>{const value=await response.json();if(!response.ok)throw Error(object(value)&&typeof value.error==='string'?value.error:'Unable to load supplier issues.');if(!valid(value))throw Error('Unexpected supplier issue response.');if(!abort.signal.aborted)setPage(value);}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Unable to load supplier issues.')});return()=>abort.abort();
 },[apiRoot,w.location.id,dataset,filter,query,cursor,reload]);
 return <section aria-label="Supplier issue follow-up"><h2>Supplier issue follow-up</h2><p>Pending invoice questions and your team’s follow-up notes. To add an issue, open a saved invoice in its item’s source history or delivery checks. These records do not submit claims to suppliers.</p><div className="food-controls"><label className="shared-field">Issue view<select value={filter} onChange={e=>{setFilter(e.target.value as ClaimFilter);setCursor({before:0})}}><option value="pending">Pending follow-up</option><option value="due">Due today or overdue</option><option value="closed">Internally closed</option><option value="cancelled">Cancelled records</option><option value="all">All supplier issues</option></select></label><label className="shared-field">Find supplier issue<input type="search" maxLength={100} value={query} placeholder="Issue, invoice, supplier or item" onChange={e=>{setQuery(e.target.value);setCursor({before:0})}}/></label></div><button onClick={()=>{setCursor({before:0});setReload(n=>n+1)}}>Refresh supplier issues</button>
 {error&&<p role="alert">{error}</p>}{!page&&!error&&<p role="status">Loading supplier issues…</p>}{page&&<><div className="food-summary"><span>Pending<strong>{page.totals.pending}</strong></span><span>Due or overdue<strong>{page.totals.due}</strong></span><span>Internally closed<strong>{page.totals.closed}</strong></span><span>Cancelled<strong>{page.totals.cancelled}</strong></span></div><p className="shared-muted">Counts cover this search across all views. Due dates use the local calendar for {w.location.name} ({page.today}); no supplier response or payment is inferred.</p>
 {page.entries.map(e=>{const c=e.claim,status=e.latest?.state??'pending',date=e.latest?.followUpDate??c.followUpDate;return <article className="food-card" key={e.sequence}><h3>{c.reference} · {status==='closed'?'Internally closed':status==='cancelled'?'Cancelled record':'Pending follow-up'}</h3><p>{e.currentTitle} · {e.controlNumber}<br/>{c.invoice.sku.vendor} · invoice {c.invoice.invoiceNumber}, line {c.invoice.lineReference} · {claimReasons[c.reason]}</p>{status==='pending'&&<p><strong>Follow-up {date}{date<page.today?' · overdue':date===page.today?' · due today':''}</strong></p>}<ClaimImpactFacts claim={c}/><p className="food-preserve">{e.latest?.note??c.details}</p><button onClick={()=>onOpen(e.recordId,e.sequence)}>Open supplier issue history</button></article>})}
 {!page.entries.length&&<p>No saved supplier issues match this view.</p>}<div className="shared-actions"><span>{page.entries.length} shown · {page.total} matching issues</span>{cursor.before>0&&<button onClick={()=>setCursor({before:0})}>First issue page</button>}{page.next!==null&&<button onClick={()=>setCursor({before:page.next!,revision:page.revision,day:page.today})}>Next 20 issues</button>}</div></>}
 </section>;
}
