'use client';
import {useEffect,useState} from 'react';
import type {ReceivingQueue,ReceivingFilter} from '../shared/food-receiving-queue';
import type {Workspace} from '../shared/types';

const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const quantities=(v:unknown,keys:string[],integer=false)=>object(v)&&keys.every(k=>typeof v[k]==='number'&&Number.isFinite(v[k])&&Number(v[k])>=0&&(!integer||Number.isSafeInteger(v[k])));
export const validReceivingQueue=(v:unknown):v is ReceivingQueue=>object(v)&&Array.isArray(v.entries)&&quantities(v.totals,['unreplaced','replacements'],true)&&v.entries.every(e=>quantities(e,['replacementQuantity','replacementRemaining','replacementReturned'])&&quantities(e,['replacementEntries','replacementReturnEntries'],true))&&typeof v.total==='number'&&typeof v.revision==='number'&&(v.next===null||typeof v.next==='number');
const qty=(v:number)=>v>0&&v<.000001?'<0.000001':new Intl.NumberFormat('en-US',{maximumFractionDigits:6}).format(v);
export function FoodReceivingQueue({w,apiRoot,dataset,onOpen}:{w:Workspace;apiRoot:string;dataset:'demo'|'operating';onOpen:(id:string,sequence:number)=>void}){
 const [filter,setFilter]=useState<ReceivingFilter>('pending'),[query,setQuery]=useState(''),[cursor,setCursor]=useState<{before:number;revision?:number}>({before:0}),[reload,setReload]=useState(0),[page,setPage]=useState<ReceivingQueue|null>(null),[error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();setPage(null);setError('');const params=new URLSearchParams({locationId:w.location.id,dataset,view:'receiving',filter,q:query,before:String(cursor.before),...(cursor.revision===undefined?{}:{revision:String(cursor.revision)})});
  void fetch(`${apiRoot}/food?${params}`,{signal:abort.signal}).then(async response=>{const value:unknown=await response.json();if(!response.ok)throw new Error(object(value)&&typeof value.error==='string'?value.error:'Unable to load delivery checks.');if(!validReceivingQueue(value))throw new Error('Unexpected delivery queue response.');if(!abort.signal.aborted)setPage(value);}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Unable to load delivery checks.')});return()=>abort.abort();
 },[apiRoot,w.location.id,dataset,filter,query,cursor,reload]);
 return <section aria-label="Delivery checks"><h2>Delivery checks</h2><p>Find reviewed invoices that still need quantities checked, or review rejected goods, replacement arrivals and extra goods. This queue covers saved invoice lines; an empty queue does not prove all deliveries were recorded.</p>
  <div className="food-controls"><label className="shared-field">Delivery view<select value={filter} onChange={e=>{setFilter(e.target.value as ReceivingFilter);setCursor({before:0})}}><option value="pending">Still need a delivery check</option><option value="rejected">Have rejected goods</option><option value="unreplaced">Rejected goods without recorded replacements</option><option value="replacements">With accepted replacements</option><option value="excess">With extra goods recorded</option><option value="all">All invoice lines, including voids</option></select></label><label className="shared-field">Find invoice or item<input type="search" maxLength={100} value={query} placeholder="Invoice, supplier, item name or code" onChange={e=>{setQuery(e.target.value);setCursor({before:0})}}/></label></div>
  <button onClick={()=>{setCursor({before:0});setReload(n=>n+1)}}>Refresh delivery queue</button>
  {error&&<p role="alert" className="food-warning">{error}</p>}{!page&&!error&&<p role="status">Loading delivery checks…</p>}
  {page&&<><p>Invoice-line counts for this search, across all delivery views:</p><div className="food-summary"><span>Active invoice lines<strong>{page.totals.active}</strong></span><span>Still need a check<strong>{page.totals.pending}</strong></span><span>With rejected goods<strong>{page.totals.rejected}</strong></span><span>Without recorded replacements<strong>{page.totals.unreplaced}</strong></span><span>With accepted replacements<strong>{page.totals.replacements}</strong></span><span>With extra goods<strong>{page.totals.excess??0}</strong></span><span>Voided lines<strong>{page.totals.voided}</strong></span></div><p className="shared-muted">An invoice can need a check and have rejected goods. Quantities from different items or units are not added together. Replacement quantities are actual recorded arrivals, not orders or a decision about how the supplier must resolve an issue. Credits and financial settlement are reviewed separately in the invoice history.</p>
   {page.entries.map(e=><DeliveryInvoiceCard key={e.sequence} entry={e} onOpen={onOpen}/>)}
   {!page.entries.length&&<p>No saved invoice lines match this view.</p>}<div className="shared-actions"><span>{page.entries.length} shown · {page.total} matching invoice lines</span>{cursor.before>0&&<button onClick={()=>setCursor({before:0})}>First delivery page</button>}{page.next!==null&&<button onClick={()=>setCursor({before:page.next!,revision:page.revision})}>Next 20 invoice lines</button>}</div>
  </>}
 </section>;
}
export function DeliveryInvoiceCard({entry:e,onOpen}:{entry:ReceivingQueue['entries'][number];onOpen:(id:string,sequence:number)=>void}){
 return <article className="food-card" key={e.sequence}><h3>{e.currentTitle}</h3><p>{e.controlNumber} · Current catalog name</p><p><strong>Invoice {e.invoice.invoiceNumber} · line {e.invoice.lineReference}</strong><br/>{e.invoice.sku.vendor} · {e.invoice.invoiceDate} · {qty(e.invoice.quantity)} {e.invoice.invoiceUnit} invoiced</p><p>Original supplier pack: {e.invoice.sku.packCount??'?'} × {e.invoice.sku.unitQty??'?'} {e.invoice.sku.unitUOM} / {e.invoice.sku.purchaseUnit}.</p>
    {e.voided?<p><strong>Voided invoice — excluded from active delivery checks.</strong></p>:<><div className="food-summary"><span>Accepted<strong>{qty(e.accepted)} {e.invoice.invoiceUnit}</strong></span><span>Rejected<strong>{qty(e.rejected)} {e.invoice.invoiceUnit}</strong></span><span>Still unaccounted for<strong>{qty(e.remaining)} {e.invoice.invoiceUnit}</strong></span></div><p>{e.receipts} active receiving {e.receipts===1?'entry':'entries'}. {e.rejected>0?'Rejected quantities remain visible even if a credit was issued. ':''}Unaccounted quantity has not been classified as shortage or waste.</p>{e.rejected>0&&<section aria-label="Replacement arrivals"><h4>Replacement arrivals</h4><p><strong>{qty(e.replacementQuantity)} {e.invoice.invoiceUnit} accepted replacements</strong> in {e.replacementEntries} active {e.replacementEntries===1?'delivery':'deliveries'}. <strong>{qty(e.replacementRemaining)} {e.invoice.invoiceUnit} without a recorded replacement.</strong></p><p>{qty(e.replacementReturned)} {e.invoice.invoiceUnit} of recorded replacement arrivals were later returned in {e.replacementReturnEntries} active pickup records. Returns do not reduce the arrival total or reopen its allowance. Original rejected quantity remains {qty(e.rejected)} {e.invoice.invoiceUnit}. An unreplaced quantity may instead need credit or another reviewed outcome; it is not an order instruction, stock balance or unpaid amount.</p></section>}{e.extraEntries>0&&<p><strong>{qty(e.extraQuantity)} {e.invoice.invoiceUnit} extra</strong> in {e.extraEntries} active observations. {qty(e.extraReturned??0)} {e.invoice.invoiceUnit} recorded as returned; {qty(Math.max(0,e.extraQuantity-(e.extraReturned??0)))} {e.invoice.invoiceUnit} not recorded as returned. This is not a return instruction or stock balance. These facts remain separate from invoice receiving totals and supplier settlement.</p>}</>}
    <button onClick={()=>onOpen(e.recordId,e.sequence)}>{e.voided?'Open retained invoice history':'Open delivery check'}</button>
   </article>;
}
