'use client';
import {useState} from 'react';
import {has,personName,type RecordOf,type Workspace} from '../shared/types';
import {hireCoordinator,type HireCandidate} from '../shared/hire-handoff';
import {hireChecklistReader,hireChecklistCurrent,hireChecklistProgress,type HireChecklistState} from '../shared/hire-checklist';
import {displayTime,localDate} from '../shared/local-time';
import type {Send} from './workspace';

const labels={open:'Checks pending or awaiting review',reviewed:'Entered checklist reviewed',cancelled:'Checklist cancelled'};
const privacy='Record status and a source reference only. Keep document contents, identification numbers, bank details and medical information out of this checklist.';
function Field({name,children}:{name:string;children:React.ReactNode}){return <label className="shared-field">{name}{children}</label>}
function RequirementsForm({employee,d,busy,save}:{employee:HireCandidate;d?:HireChecklistState;busy:boolean;save:(input:Record<string,unknown>)=>Promise<unknown>}){
 const [items,setItems]=useState(d?.items.map(i=>({label:i.label,dueDate:i.dueDate}))??[{label:'',dueDate:''}]),[confirmed,setConfirmed]=useState(false);
 const change=(index:number,key:'label'|'dueDate',value:string)=>{setItems(items.map((i,n)=>n===index?{...i,[key]:value}:i));setConfirmed(false)};
 return <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await save({employeeId:employee.id,employeeRevision:employee.revision,sourceReference:f.get('sourceReference'),items,confirmed,note:f.get('note')})}}><fieldset disabled={busy}>
  <p>{employee.name} · {employee.area} · {employee.position} · Hire date {employee.hireDate}</p>
  <Field name="Source for this restaurant’s requirements"><textarea name="sourceReference" maxLength={1000} required defaultValue={d?.sourceReference} onChange={()=>setConfirmed(false)} placeholder="Checked checklist title, version or responsible manager’s instructions"/></Field>
  <p>{privacy}</p>
  {items.map((i,index)=><div className="ops-card" key={index}><div className="ops-fields"><Field name={`Requirement ${index+1}`}><input required maxLength={160} value={i.label} onChange={e=>change(index,'label',e.target.value)}/></Field><Field name={`Entered due date ${index+1} (optional)`}><input type="date" value={i.dueDate} onChange={e=>change(index,'dueDate',e.target.value)}/></Field></div>{items.length>1&&<button type="button" onClick={()=>{setItems(items.filter((_,n)=>n!==index));setConfirmed(false)}}>Remove requirement {index+1}</button>}</div>)}
  <button type="button" disabled={items.length>=30} onClick={()=>{setItems([...items,{label:'',dueDate:''}]);setConfirmed(false)}}>Add requirement</button>
  {d&&<><p>Revising requirements resets all current checks and the final review. Earlier requirements and evidence remain in history.</p><Field name="Reason for revising requirements"><textarea name="note" required maxLength={1000}/></Field></>}
  <p><label><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I checked these requirements against the restaurant’s source.</label></p><button className="shared-primary" disabled={!confirmed}>{d?'Save revised requirements':'Save onboarding checklist'}</button>
 </fieldset></form>;
}
function StateView({d,w}:{d:HireChecklistState;w:Workspace}){return <><p>{d.employeeName} · {d.position} · Hire date {d.hireDate}</p><p className="ops-preserve">Requirements source: {d.sourceReference}</p>{d.review&&<p className="ops-preserve">Checklist reviewed by {personName(w,d.review.by)} on {displayTime(d.review.at,w.location.timezone)}: {d.review.note}</p>}</>}
function ChecksView({d,w}:{d:HireChecklistState;w:Workspace}){return <>{d.items.map(i=><div key={i.id}><h4>{i.label}</h4><p>{i.dueDate?'Entered due date: '+i.dueDate:'No due date entered'}</p>{i.check?<><p>Recorded completion: {i.check.completedDate} · Checked by {personName(w,i.check.by)} on {displayTime(i.check.at,w.location.timezone)}</p><p className="ops-preserve">{i.check.evidence}</p></>:<p>Not checked</p>}</div>)}</>}
export function HireChecklistCard({r,w,send,busy,now,readOnly=false}:{r:RecordOf<'hirechecklist'>;w:Workspace;send:Send;busy:boolean;now:string;readOnly?:boolean}){
 const d=r.data,current=hireChecklistCurrent(w,r),employee=w.hireCandidates?.find(c=>c.id===r.ownerId),today=localDate(now,w.location.timezone),counts=hireChecklistProgress(r,today),canEdit=!readOnly&&hireChecklistReader(r,w.me),open=canEdit&&current&&d.status==='open';
 const submit=(action:string,values:(f:FormData)=>Record<string,unknown>)=>async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();await send('hirechecklist.'+action,values(new FormData(e.currentTarget)),r)};
 const reasonForm=(action:string,title:string,confirmation?:string)=><form onSubmit={submit(action,f=>({note:f.get('note'),confirmed:f.get('confirmed')==='on'}))}><fieldset disabled={busy}><Field name={title+' reason or evidence'}><textarea name="note" maxLength={1000} required/></Field>{confirmation&&<p><label><input type="checkbox" name="confirmed" required/> {confirmation}</label></p>}<button>{title}</button></fieldset></form>;
 return <article className="ops-card"><h2>{d.title}</h2><p className="ops-badge">{readOnly?'Historical record · ':''}{labels[d.status]}</p><StateView d={d} w={w}/>
  <p>{counts.checked} of {counts.total} entered requirements checked{counts.overdue?` · ${counts.overdue} past entered due date`:''}.</p>
  <p className="ops-callout">This tracks checks against the entered list. It does not establish legal document validity, enable sign-in, verify Toast setup, confirm a first shift or grant training clearance.</p>
  {!readOnly&&!current&&d.status!=='cancelled'&&<p className="ops-callout">Hire, department or position changed. Review the requirements before using these checks for the current hire.</p>}
  {d.items.map(i=><section className="ops-card" key={i.id}><h3>{i.label}</h3><p>{i.dueDate?'Entered due date: '+i.dueDate:'No due date entered'}{open&&!i.check&&i.dueDate&&i.dueDate<today?' · Past due':''}</p>
   {i.check?<><p>Recorded completion: {i.check.completedDate} · Checked by {personName(w,i.check.by)} on {displayTime(i.check.at,w.location.timezone)}</p><p className="ops-preserve">{i.check.evidence}</p>{open&&<details><summary>Correct this check</summary><p>The previous completion and evidence will remain in history.</p><form onSubmit={submit('uncheck',f=>({itemId:i.id,note:f.get('note')}))}><fieldset disabled={busy}><Field name="Reason to return this requirement to pending"><textarea name="note" required maxLength={1000}/></Field><button>Return to pending</button></fieldset></form></details>}</>:<><p>Not checked</p>{open&&<details><summary>Record checked completion</summary><p>{privacy}</p><form onSubmit={submit('check',f=>({itemId:i.id,note:f.get('note'),completedDate:f.get('completedDate'),confirmed:f.get('confirmed')==='on'}))}><fieldset disabled={busy}><Field name="Actual completion date"><input type="date" name="completedDate" max={today} defaultValue={today} required/></Field><Field name="What was checked and its source reference"><textarea name="note" required maxLength={1000}/></Field><p><label><input type="checkbox" name="confirmed" required/> I personally checked this requirement.</label></p><button>Save checked completion</button></fieldset></form></details>}</>}
  </section>)}
  {open&&counts.checked===counts.total&&<details><summary>Review the completed checklist</summary>{reasonForm('review','Record checklist review','I reviewed every entered requirement and its recorded completion evidence.')}</details>}
  {canEdit&&current&&d.status!=='open'&&<details><summary>Reopen checklist</summary><p>Earlier checks are retained for review. A new checklist review will be required.</p>{reasonForm('reopen','Reopen checklist')}</details>}
  {canEdit&&employee&&hireCoordinator(w.me,employee.area)&&employee.status!=='archived'&&employee.hireDate===d.hireDate&&<details><summary>Revise requirements or current employee details</summary><RequirementsForm key={r.id+':'+r.revision} employee={employee} d={d} busy={busy} save={input=>send('hirechecklist.revise',input,r)}/></details>}
  {canEdit&&d.status!=='cancelled'&&<details><summary>Cancel this checklist</summary><p>This cancels only the checklist. Employee access, schedules and training stay separate.</p>{reasonForm('cancel','Cancel checklist')}</details>}
  <details><summary>Checklist history ({d.history.length})</summary>{d.history.slice().reverse().map((h,i)=><p className="ops-preserve" key={i}>{displayTime(h.at,w.location.timezone)} · {personName(w,h.actorId)} · {h.action}: {h.note}</p>)}{d.versions.map((v,i)=><details key={i}><summary>Earlier checklist {i+1} · {labels[v.state.status]}</summary><StateView d={v.state} w={w}/><ChecksView d={v.state} w={w}/><p>{personName(w,v.by)} · {displayTime(v.at,w.location.timezone)} · {v.reason}</p></details>)}</details>
 </article>;
}
export function HireChecklists({initialRecordId,w,send,busy,now,onNavigate}:{initialRecordId?:string;w:Workspace;send:Send;busy:boolean;now:string;onNavigate:(tab:string)=>void}){
 const [creating,setCreating]=useState(false),[employeeId,setEmployeeId]=useState(''),[selected,setSelected]=useState<string|null>(initialRecordId??null),[filter,setFilter]=useState('open'),[query,setQuery]=useState('');
 const candidates=(w.hireCandidates??[]).filter(c=>c.status!=='archived'&&hireCoordinator(w.me,c.area)),employee=candidates.find(c=>c.id===employeeId),records=w.records.filter((r):r is RecordOf<'hirechecklist'>=>r.kind==='hirechecklist'&&hireChecklistReader(r,w.me)),current=records.find(r=>r.id===selected),today=localDate(now,w.location.timezone);
 const needsReview=(r:RecordOf<'hirechecklist'>)=>r.data.status!=='cancelled'&&(r.data.status==='open'||!hireChecklistCurrent(w,r));
 const rows=records.filter(r=>(filter==='all'||filter==='open'&&needsReview(r)||filter==='closed'&&!needsReview(r))&&`${r.data.employeeName} ${r.area} ${r.data.hireDate}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>a.data.hireDate.localeCompare(b.data.hireDate)||a.id.localeCompare(b.id));
 return <section className="ops-page"><div className="shared-heading"><div><p className="ops-eyebrow">{w.location.name} · People</p><h1>Onboarding checklist</h1></div><button disabled={busy} onClick={()=>{setCreating(!creating);setSelected(null)}}>{creating?'Cancel new checklist':'Add hire checklist'}</button></div>
  <p>Enter the checked requirements for this restaurant and hire, record actual completion evidence, then review the list. The app supplies no default legal paperwork requirements.</p><p>{privacy}</p>
  <div className="ops-filters"><button disabled={busy} onClick={()=>onNavigate('First-shift handoff')}>Open first-shift handoff</button>{has(w.me,'location.manage')&&<button disabled={busy} onClick={()=>onNavigate('Employee access')}>Open employee setup</button>}<button disabled={busy} onClick={()=>onNavigate('Work history')}>Open work history</button></div>
  {creating&&<section className="ops-card"><Field name="Employee with a recorded hire date"><select disabled={busy} value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Choose employee</option>{candidates.map(c=><option key={c.id} value={c.id}>{c.name} · {c.area} · {c.hireDate}</option>)}</select></Field>{!candidates.length&&<p>An owner must record the hire in Employee setup first.</p>}{employee&&<RequirementsForm key={employee.id+':'+employee.revision} employee={employee} busy={busy} save={async input=>{if(await send('hirechecklist.create',input)){setCreating(false);setEmployeeId('')}}}/>}</section>}
  {current?<><button disabled={busy} onClick={()=>setSelected(null)}>Back to onboarding checklists</button><HireChecklistCard key={current.id+':'+current.revision} r={current} w={w} send={send} busy={busy} now={now}/></>:<><div className="ops-filters">{[['open','Needs follow-through'],['closed','Reviewed or cancelled'],['all','All']].map(([value,label])=><button disabled={busy} key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}<Field name="Find employee, department or hire date"><input value={query} onChange={e=>setQuery(e.target.value)}/></Field></div>{!rows.length&&<p className="ops-empty">No matching checklists. Older reviewed or cancelled lists may be in Work history.</p>}{rows.map(r=>{const p=hireChecklistProgress(r,today);return <article className="ops-card" key={r.id}><h2>{r.data.title}</h2><p>{r.area} · Hire date {r.data.hireDate} · {p.checked}/{p.total} checked{p.overdue?` · ${p.overdue} past due`:''}</p><p>{r.data.status!=='cancelled'&&!hireChecklistCurrent(w,r)?'Employee setup changed — review needed':labels[r.data.status]}</p><button disabled={busy} onClick={()=>{setSelected(r.id);setCreating(false)}}>Open {r.data.title}</button></article>})}</>}
 </section>;
}
