'use client';
import {useState} from 'react';
import {has,personName,type RecordOf,type Workspace} from '../shared/types';
import {hireCoordinator,hireScheduler,hireReader,hireEvidence,firstShiftOptions,type HireCandidate,type HireFacts,type HireCycle} from '../shared/hire-handoff';
import {displayTime,localDate} from '../shared/local-time';
import type {Send} from './workspace';
import './operations.css';

const labels={'awaiting-ack':'Awaiting scheduler acknowledgment',accepted:'Scheduler accepted',scheduled:'First shift confirmed',cancelled:'Handoff cancelled'};
function Field({name,children}:{name:string;children:React.ReactNode}){return <label className="shared-field">{name}{children}</label>}
function Setup({employee}:{employee:HireCandidate}){return <p>{employee.name} · {employee.area} · {employee.position}<br/>Hire date: {employee.hireDate} · {employee.status==='archived'?'Archived employee':employee.active?'Enabled employee':employee.scheduleOnly?'Scheduling-only employee':'Employee setup pending'}</p>}
function Facts({w,employee,d}:{w:Workspace;employee:HireCandidate;d?:HireFacts}){const schedulers=w.members.filter(m=>m.id!==employee.id&&hireScheduler(m,employee.area));return <><Setup employee={employee}/><div className="ops-fields"><Field name="Responsible scheduler"><select name="schedulerId" defaultValue={schedulers.some(m=>m.id===d?.schedulerId)?d!.schedulerId:''} required><option value="">Choose scheduler</option>{schedulers.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field name="Target first-shift date"><input name="targetDate" type="date" min={employee.hireDate??undefined} defaultValue={d?.targetDate} required/></Field></div><Field name="Scheduling handoff note"><textarea name="handoffNote" maxLength={3000} defaultValue={d?.handoffNote} placeholder="What the scheduler needs to arrange. Keep credentials, payroll and private documents out of this note." required/></Field></>}
const readFacts=(f:FormData,employee:HireCandidate)=>({employeeId:employee.id,employeeRevision:employee.revision,schedulerId:f.get('schedulerId'),targetDate:f.get('targetDate'),handoffNote:f.get('handoffNote')});
function FactView({d}:{d:HireFacts}){return <><p>{d.employeeName} · {d.position} · Hire date {d.hireDate}</p><p>Assigned to {d.schedulerName} · Target first shift {d.targetDate}</p><h3>Scheduling handoff</h3><p className="ops-preserve">{d.handoffNote}</p></>}
function CycleView({d,w}:{d:HireCycle;w:Workspace}){return <>{d.acknowledgment&&<div><h3>Scheduler acknowledgment</h3><p className="ops-preserve">{d.acknowledgment.note}</p><p>{personName(w,d.acknowledgment.by)} · {displayTime(d.acknowledgment.at,w.location.timezone)}</p></div>}{d.confirmation&&<div><h3>Saved shift confirmation</h3><p>{displayTime(d.confirmation.start,w.location.timezone)} – {displayTime(d.confirmation.end,w.location.timezone)} · {d.confirmation.position}</p><p className="ops-preserve">{d.confirmation.note}</p><p>Checked by {personName(w,d.confirmation.by)} · {displayTime(d.confirmation.at,w.location.timezone)}</p></div>}</>}
export function HireHandoffs({initialRecordId,w,send,busy,now,onNavigate}:{initialRecordId?:string;w:Workspace;send:Send;busy:boolean;now:string;onNavigate:(tab:string)=>void}){
 const [creating,setCreating]=useState(false),[employeeId,setEmployeeId]=useState(''),[selected,setSelected]=useState<string|null>(initialRecordId??null),[filter,setFilter]=useState('open');
 const candidates=(w.hireCandidates??[]).filter(c=>c.status!=='archived'&&hireCoordinator(w.me,c.area)),employee=candidates.find(c=>c.id===employeeId);
 const records=w.records.filter((r):r is RecordOf<'hirehandoff'>=>r.kind==='hirehandoff'&&hireReader(r,w.me)),current=records.find(r=>r.id===selected),today=localDate(now,w.location.timezone);
 const rows=records.filter(r=>filter==='all'||filter==='open'&&r.data.status!=='cancelled'&&(r.data.status!=='scheduled'||!hireEvidence(w,r).current)||filter==='complete'&&(r.data.status==='cancelled'||r.data.status==='scheduled'&&hireEvidence(w,r).current)).sort((a,b)=>a.data.targetDate.localeCompare(b.data.targetDate)||a.id.localeCompare(b.id));
 return <section className="ops-page"><div className="shared-heading"><div><p className="ops-eyebrow">{w.location.name} · People</p><h1>First-shift handoff</h1></div>{hireCoordinator(w.me)&&<button disabled={busy} onClick={()=>{setCreating(!creating);setSelected(null)}}>{creating?'Cancel new handoff':'Assign first shift'}</button>}</div>
 <p>Give one scheduler responsibility for the new hire’s first shift. Their acknowledgment and the published schedule stay together.</p><p className="ops-callout">A confirmed shift covers scheduling only. Employee sign-in, documents and training are separate. Saving this handoff does not send an email or text.</p>
 <div className="ops-filters"><button disabled={busy} onClick={()=>onNavigate('Schedule week')}>Open schedule</button>{has(w.me,'location.manage')&&<button disabled={busy} onClick={()=>onNavigate('Employee access')}>Open employee setup</button>}<button disabled={busy} onClick={()=>onNavigate('Work history')}>Open work history</button></div>
 {creating&&<form className="ops-card" onSubmit={async e=>{e.preventDefault();if(employee&&await send('hirehandoff.create',readFacts(new FormData(e.currentTarget),employee))){setCreating(false);setEmployeeId('')}}}><h2>Assign scheduling responsibility</h2><fieldset disabled={busy}><Field name="Employee with a recorded hire date"><select required value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Choose employee</option>{candidates.map(c=><option key={c.id} value={c.id}>{c.name} · {c.area}</option>)}</select></Field>{!candidates.length&&<p>No eligible hire setup is recorded in your department. An owner can add the hire and start date in Employee setup.</p>}{employee&&<div key={employee.id+':'+employee.revision}><Facts w={w} employee={employee}/><button className="shared-primary">Save scheduling handoff</button></div>}</fieldset></form>}
 {current?<><button disabled={busy} onClick={()=>setSelected(null)}>Back to first-shift handoffs</button><HireHandoffCard key={current.id+':'+current.revision} r={current} w={w} send={send} busy={busy}/></>:<><div className="ops-filters">{[['open','Needs follow-through'],['complete','Completed or cancelled'],['all','All']].map(([value,label])=><button key={value} disabled={busy} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}</div>{!rows.length&&<p className="ops-empty">No matching first-shift handoffs. Older completed records may be in Work history.</p>}{rows.map(r=>{const evidence=hireEvidence(w,r),open=r.data.status!=='cancelled'&&(r.data.status!=='scheduled'||!evidence.current);return <article className="ops-card" key={r.id}><div className="shared-heading"><h2>{r.data.title}</h2><span className="ops-badge">{evidence.needsReview?'Schedule or employee setup changed — review needed':labels[r.data.status]}</span></div><p>{r.area} · {r.data.schedulerName} · Target {r.data.targetDate}{open&&r.data.targetDate<today?' · Past entered target date':''}</p><button disabled={busy} onClick={()=>{setSelected(r.id);setCreating(false)}}>Open {r.data.title}</button></article>})}</>}
 </section>;
}
export function HireHandoffCard({r,w,send,busy,readOnly=false}:{r:RecordOf<'hirehandoff'>;w:Workspace;send:Send;busy:boolean;readOnly?:boolean}){
 const d=r.data,e=hireEvidence(w,r),employee=e.person,coordinator=hireCoordinator(w.me,r.area),assigned=w.me.id===d.schedulerId&&hireScheduler(w.me,r.area),shift=firstShiftOptions(w,r)[0];
 const submit=(action:string,values:(f:FormData)=>Record<string,unknown>)=>async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();await send('hirehandoff.'+action,values(new FormData(event.currentTarget)),r)};
 const actionForm=(action:string,title:string,button:string,check?:[string,string])=><form className="ops-card" onSubmit={submit(action,f=>({note:f.get('note'),...(check?{[check[0]]:f.get(check[0])==='on'}:{})}))}><h3>{title}</h3><fieldset disabled={busy}><Field name={title+' note'}><textarea name="note" maxLength={3000} required/></Field>{check&&<label><input name={check[0]} type="checkbox" required/> {check[1]}</label>}<p><button className="shared-primary">{button}</button></p></fieldset></form>;
 return <article className="ops-card"><h2>{d.title}</h2><p className="ops-badge">{readOnly?'Historical record · '+labels[d.status]:e.needsReview?'Schedule or employee setup changed — review needed':labels[d.status]}</p><FactView d={d}/><CycleView d={d} w={w}/>
 {!readOnly&&<>{!e.setupCurrent&&d.status!=='cancelled'&&<p className="ops-callout">The current hire date, department or employment status no longer matches. A coordinator must review this handoff.</p>}{e.setupCurrent&&!e.schedulable&&d.status!=='cancelled'&&<p className="ops-callout">Employee setup is pending. The scheduler may accept responsibility now; an owner must finish the existing employee setup before a shift can be confirmed.</p>}{!w.members.some(m=>m.id===d.schedulerId&&hireScheduler(m,r.area))&&d.status!=='cancelled'&&<p className="ops-callout">The named scheduler no longer has scheduling access. A coordinator must correct the assignment.</p>}
 {assigned&&d.status==='awaiting-ack'&&e.setupCurrent&&actionForm('accept','Accept scheduling responsibility','Acknowledge handoff',['accepted','I read the handoff and accept responsibility for arranging this first shift.'])}
 {assigned&&d.status==='accepted'&&e.schedulable&&<section className="ops-card"><h3>Confirm the earliest published shift</h3>{shift?<><p>{displayTime(shift.data.start,w.location.timezone)} – {displayTime(shift.data.end,w.location.timezone)} · {shift.data.position}</p><form onSubmit={submit('confirm',f=>({note:f.get('note'),shiftId:shift.id,shiftRevision:shift.revision,checked:f.get('checked')==='on'}))}><fieldset disabled={busy}><Field name="First-shift confirmation note"><textarea name="note" maxLength={3000} required/></Field><label><input name="checked" type="checkbox" required/> I checked the employee and this published first shift.</label><p><button className="shared-primary">Confirm published first shift</button></p></fieldset></form></>:<p>No current published shift is recorded for this employee on or after the hire date. Create and publish the shift through the existing schedule workflow.</p>}</section>}
 {['scheduled','cancelled'].includes(d.status)&&e.setupCurrent&&<details><summary>Reopen scheduling handoff</summary><p>A fresh acknowledgment and shift confirmation will be required. The earlier outcome stays below.</p>{actionForm('reopen','Reason to reopen','Reopen handoff')}</details>}
 {!['scheduled','cancelled'].includes(d.status)&&<details><summary>Add scheduling update</summary>{actionForm('note','Scheduling progress','Save progress note')}</details>}
 {coordinator&&employee&&employee.status!=='archived'&&employee.hireDate===d.hireDate&&<details><summary>Correct scheduler, target or handoff</summary><p>The corrected assignment needs a new acknowledgment. Earlier facts and confirmations stay in history.</p><form onSubmit={submit('correct',f=>({...readFacts(f,employee),note:f.get('note')}))}><fieldset disabled={busy}><Facts w={w} employee={employee} d={d}/><Field name="Correction reason"><textarea name="note" maxLength={3000} required/></Field><button>Save corrected handoff</button></fieldset></form></details>}
 {coordinator&&d.status!=='cancelled'&&<details><summary>Cancel scheduling handoff</summary><p>This cancels only the handoff. It does not remove an employee, shift or sign-in access.</p>{actionForm('cancel','Cancellation reason','Cancel handoff')}</details>}
 </>}
 <details><summary>Handoff history ({d.history.length})</summary>{d.history.slice().reverse().map((h,i)=><p className="ops-preserve" key={i}>{displayTime(h.at,w.location.timezone)} · {personName(w,h.actorId)} · {h.action}: {h.note}</p>)}{d.versions.map((v,i)=><details key={i}><summary>Earlier handoff {i+1} · {labels[v.cycle.status]}</summary><FactView d={v.facts}/><CycleView d={v.cycle} w={w}/><p>{personName(w,v.by)} · {displayTime(v.at,w.location.timezone)} · Reason: {v.reason}</p></details>)}</details>
 </article>;
}
