'use client';
import {useEffect,useRef,useState} from 'react';
import type {Workspace} from '../shared/types';
import {maintenanceManager} from '../shared/maintenance';
import {maintenanceMoney} from '../shared/maintenance-cost';
import {localDate,nextDate,displayTime} from '../shared/local-time';
import {createServiceCostReportLoader,serviceCostReportCsv,type ServiceCostReport,type CostReportRange} from '../shared/maintenance-cost-report';

export function ServiceCostAllocationReview({data,onOpen}:{data:ServiceCostReport;onOpen:(planId:string,serviceId:string)=>void}){
 return <section aria-label="Repeated service cost references"><h4>Compare repeated references</h4>
 <p>Matching evidence dates and references are review leads. They may be legitimate split allocations or different suppliers using the same reference. Confirm the original document and each service share before correcting a cost. No amount is removed or approved here.</p>
 <p>Only included costs within the applied service dates and your available plans are compared. No matches does not prove there are no duplicates elsewhere.</p>
 {!data.referenceGroups.length&&<p>No repeated date/reference groups in this report.</p>}
 {data.referenceGroups.map(g=><details key={g.id}><summary>{g.documentDate} · {g.references[0]} · {g.services} allocations · {maintenanceMoney(g.amountCents)} USD combined</summary>
 <p>{g.plans} plans · Recorded service shares, not the original invoice total. Different spellings of the reference are preserved below.</p>
 {g.members.map(m=>{const e=data.entries.find(e=>e.planId===m.planId&&e.serviceId===m.serviceId)!,c=e.cost;
 return <article className="ops-card" key={m.planId+':'+m.serviceId}><h5>{e.serviceDate} · {e.planTitle}</h5><p>{e.equipment} · {e.assetTag??'No checked asset link'}{e.archivedAt?' · Filed plan':e.planStatus==='retired'?' · Retired plan':''}</p><p><strong>{maintenanceMoney(e.includedCents!)} USD allocated</strong></p>{c?.kind==='recorded'&&<><p className="ops-preserve">Reference: {c.sourceRef}</p><p className="ops-preserve">Allocation: {c.allocation}</p><p className="ops-preserve">Cost note: {c.note}</p></>}<button onClick={()=>onOpen(m.planId,m.serviceId)}>Open service evidence: {e.serviceDate} · {e.planTitle}</button></article>})}
 </details>)}</section>;
}
export function ServiceCostReportDetails({data}:{data:ServiceCostReport}){
 const [copied,setCopied]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<string|null>(null);
 const [focused,setFocused]=useState<{planId:string;serviceId:string}|null>(null),evidence=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(focused){evidence.current?.scrollIntoView({block:'start'});evidence.current?.focus({preventScroll:true});}},[focused]);
 const entries=focused?data.entries.filter(e=>e.planId===focused.planId&&e.serviceId===focused.serviceId):data.entries;
 useEffect(()=>()=>{if(file)URL.revokeObjectURL(file)},[file]);
 const csv=()=>serviceCostReportCsv(data);
 const prepare=()=>{try{setFile(URL.createObjectURL(new Blob([csv()],{type:'text/csv;charset=utf-8'})));setError('')}catch(e){setError(e instanceof Error?e.message:'CSV unavailable')}};
 const copy=async()=>{setCopied(false);try{await navigator.clipboard.writeText(csv());setCopied(true);setError('')}catch{setError('Copy was unavailable. Prepare a CSV and use the save link.')}};
 return <section className="ops-card"><h3>Service-cost review · {data.from} through {data.through}</h3><p>Actual service dates · {data.restaurant} · Checked {displayTime(data.generatedAt,data.timezone)}.</p><p>{data.coverage==='active-retired-filed'?'Includes active, retired and filed plans available to this owner.':'Active, unfiled plans only. Retired and filed costs are outside this manager view.'}</p><p><strong>{data.totals.recorded?maintenanceMoney(data.totals.amountCents)+' USD recorded':'No recorded amount'}</strong> · {data.totals.recorded} costed services ({data.totals.noCharge} checked no-charge) · {data.totals.unknown} unknown cost · {data.totals.voided} voided services excluded.</p><p>{data.totals.services} service records across {data.totals.plans} plans. {data.totals.repeatedReferenceGroups} repeated date/reference groups need allocation review. These are recorded allocations, not accounting or payment totals; no duplicate amount is automatically deducted.</p>
 <div className="shared-actions"><button onClick={prepare}>Prepare complete service-cost CSV</button><button onClick={()=>void copy()}>Copy complete service-cost CSV</button>{file&&<a href={file} download={'JMAX-service-costs-'+data.from+'-to-'+data.through+'.csv'}>Save service-cost CSV</a>}</div>{copied&&<p role="status">Complete service-cost CSV copied.</p>}{error&&<p role="alert">{error}</p>}
 <ServiceCostAllocationReview data={data} onOpen={(planId,serviceId)=>setFocused({planId,serviceId})}/>
 <h4>Equipment and unlinked plans</h4><p>Groups use the checked asset identity saved with each service. Unlinked plans stay separate. Names and tags below come from service-time snapshots.</p>{data.assets.map(a=><article className="ops-card" key={a.key}><h5>{a.label}</h5><p>{a.recorded?maintenanceMoney(a.amountCents)+' USD recorded':'No recorded amount'} · {a.plans} plans · {a.recorded} costed · {a.unknown} unknown · {a.voided} voided</p></article>)}
 <h4 ref={evidence} tabIndex={-1}>Original service and cost evidence</h4>{focused&&<button onClick={()=>setFocused(null)}>Show all service evidence</button>}{!data.entries.length&&<p>No accessible service records match these dates. This does not establish that no maintenance occurred or no costs exist.</p>}{entries.map(e=><details open={focused?true:undefined} key={e.planId+':'+e.serviceId}><summary>{e.serviceDate} · {e.planTitle} · {e.voidReason?'Voided service':e.includedCents!==null?maintenanceMoney(e.includedCents)+' USD':e.costStatus==='withdrawn'?'Cost withdrawn':'Cost unknown'}{e.repeatedReference?' · Review repeated reference':''}</summary><p>{e.equipment} · {e.assetTag??'No checked asset link'}{e.archivedAt?' · Filed plan':e.planStatus==='retired'?' · Retired plan':''}</p><p>Plan {e.planId} · Revision {e.planRevision} · Service {e.serviceId}</p><p className="ops-preserve">Service evidence: {e.serviceEvidence}</p>{e.voidReason&&<p>Excluded: {e.voidReason}</p>}{e.cost?.kind==='recorded'?<><p>Evidence date {e.cost.documentDate} · {e.recordedCents!==null?maintenanceMoney(e.recordedCents)+' USD originally recorded':'Cost evidence needs review'}</p><p className="ops-preserve">{e.cost.sourceRef}</p><p className="ops-preserve">Allocation: {e.cost.allocation}</p></>:<p>{e.costStatus==='withdrawn'?'The latest cost was withdrawn; the amount is unknown.':'No current checked cost evidence.'}</p>}{e.cost&&<p className="ops-preserve">Cost update: {e.cost.note} · {displayTime(e.cost.at,data.timezone)}</p>}</details>)}
 <p>Read-only snapshot. Refresh after cost corrections, service voids or filing changes. Open the original plan or Work history for the full retained event history.</p></section>;
}
export function ServiceCostReview({w,now,busy}:{w:Workspace;now:string;busy:boolean}){
 const today=localDate(now,w.location.timezone),[from,setFrom]=useState(nextDate(today,-29)),[through,setThrough]=useState(today),[applied,setApplied]=useState<CostReportRange|null>(null),[refresh,setRefresh]=useState(0),[result,setResult]=useState<{key:string;data:ServiceCostReport|null;error:string}>({key:'',data:null,error:''});
 const allowed=maintenanceManager(w.me),key=[w.location.id,w.me.id,w.location.revision,applied?.from,applied?.through,refresh].join(':');
 useEffect(()=>{if(!applied||!allowed)return;const loader=createServiceCostReportLoader(r=>setResult({...r,key}));void loader.load(w.location.id,w.me.id,w.location.revision,applied);return ()=>loader.cancel();},[key,allowed]);
 if(!allowed)return null;
 const current=result.key===key?result:null;
 return <section className="ops-card"><h2>Review service costs across plans</h2><p>Review recorded amounts and missing cost evidence by actual service date, including older filed plans where your access allows. Choose up to 366 days and 500 services. Larger results require a narrower date range; no partial total is shown.</p><form onSubmit={e=>{e.preventDefault();setApplied({from,through});setRefresh(n=>n+1)}}><div className="ops-fields"><label className="shared-field">First service date<input type="date" required value={from} max={today} onChange={e=>setFrom(e.target.value)}/></label><label className="shared-field">Last service date<input type="date" required value={through} max={today} onChange={e=>setThrough(e.target.value)}/></label></div><button disabled={busy}>Review service costs</button></form>
 {applied&&<>{(from!==applied.from||through!==applied.through)&&<p role="status">Dates changed. Submit them to replace the applied report.</p>}{current?.error?<p role="alert">{current.error}</p>:current?.data?<ServiceCostReportDetails key={key} data={current.data}/>:<p role="status">Loading service-cost evidence…</p>}</>}</section>;
}
