'use client';
import {useState} from 'react';
import {ServiceCostReview} from './maintenance-cost-report';
import {personName,type Workspace,type RecordOf} from '../shared/types';
import {maintenanceOwner,maintenanceManager,maintenanceReader,maintenanceSchedule,type MaintenanceFacts} from '../shared/maintenance';
import {maintenanceTiming,maintenanceOccurrence,maintenanceWeekdays,maintenanceOrdinals,type CalendarRecurrence} from '../shared/maintenance-calendar';
import {contactReader} from '../shared/service-contacts';
import {equipmentReader,equipmentLinkState,type EquipmentSnapshot} from '../shared/equipment';
import {MeterRuleFields,MeterStatus,MaintenanceMeterPanel} from './maintenance-meter';
import {meterTiming} from '../shared/maintenance-meter';
import {MaintenanceCostSummary,MaintenanceServiceCost} from './maintenance-cost';
import {EquipmentRegister} from './equipment';
import {localDate,displayTime} from '../shared/local-time';
import type {Send} from './workspace';
import './operations.css';
function AssetSnapshot({asset}:{asset:EquipmentSnapshot}){return <div><p>Checked asset: {asset.facts.assetTag} · {asset.facts.title} · {asset.facts.placement}</p><p>Manufacturer: {asset.facts.manufacturer||'Not entered'} · Model: {asset.facts.model||'Not entered'} · Serial: {asset.facts.serial||'Not entered'}</p><p className="ops-preserve">Equipment source: {asset.facts.sourceRef}</p><p className="ops-preserve">{asset.facts.details}</p></div>}
function Field({name,children}:{name:string;children:React.ReactNode}){return <label className="shared-field">{name}{children}</label>}
export function PlanFields({w,d}:{w:Workspace;d?:MaintenanceFacts}){
 const [mode,setMode]=useState(d?(d.meterOnly?'meter-only':d.recurrence?.kind??'after-service'):''),[anchor,setAnchor]=useState(d?.initialDue??''),[every,setEvery]=useState(d?.recurrence?String(d.recurrence.every):''),[weekday,setWeekday]=useState(d?.recurrence?.kind==='calendar-month-weekday'?String(d.recurrence.weekday):''),[ordinal,setOrdinal]=useState(d?.recurrence?.kind==='calendar-month-weekday'?String(d.recurrence.ordinal):'');
 const [assetId,setAssetId]=useState(d?.asset?.id??'');
 const assets=w.records.filter((r):r is RecordOf<'equipment'>=>r.kind==='equipment'&&r.data.status==='active'&&equipmentReader(r,w.me)),asset=assets.find(r=>r.id===assetId);
 const monthly=mode.startsWith('calendar-month');let preview:string[]=[];
 if(mode.startsWith('calendar-')&&/^\d{4}-\d{2}-\d{2}$/.test(anchor)&&Number.isInteger(Number(every))&&Number(every)>=1&&Number(every)<=(monthly?120:3650)&&(mode!=='calendar-month-weekday'||weekday!==''&&ordinal!=='')){
  try{const recurrence=(mode==='calendar-month-weekday'?{kind:mode,every:Number(every),weekday:Number(weekday),ordinal:Number(ordinal)}:{kind:mode,every:Number(every)}) as CalendarRecurrence;
   preview=[0,1,2].map(i=>maintenanceOccurrence({initialDue:anchor,intervalDays:0,recurrence},i));
  }catch{/* Incomplete or unsupported dates are validated on save. */}
 }
 return <>
 <Field name="Plan title"><input name="title" defaultValue={d?.title} maxLength={200} required/></Field>
 <Field name="Link checked equipment · optional"><select name="assetId" value={assetId} onChange={e=>setAssetId(e.target.value)}><option value="">Unlinked source reference</option>{d?.asset&&!assets.some(r=>r.id===d.asset?.id)&&<option value={d.asset.id}>Unavailable retained asset: {d.asset.facts.assetTag}</option>}{assets.map(r=><option key={r.id} value={r.id}>{r.data.assetTag} · {r.data.title} · {r.data.placement}</option>)}</select></Field><input type="hidden" name="assetRevision" value={asset?.revision??''}/>{asset&&<AssetSnapshot asset={{id:asset.id,revision:asset.revision,facts:asset.data,checkedBy:asset.data.checkedBy,checkedAt:asset.data.checkedAt}}/>}<p>Check that the selected physical asset matches the task below. Existing references are not matched automatically. Once service exists, keep the same link; changed asset details require a plan recheck.</p>
 <Field name="Equipment or asset reference"><input name="equipment" defaultValue={d?.equipment} maxLength={300} required placeholder="Exact equipment, location or asset number from the source"/></Field>
 <Field name="Source task and completion requirements"><textarea name="task" defaultValue={d?.task} maxLength={3000} required/></Field>
 <Field name="Checked source reference"><textarea name="sourceRef" defaultValue={d?.sourceRef} maxLength={2000} required placeholder="Manual section, service agreement or approved procedure and where it is kept"/></Field>
 <Field name="Timing from the checked source"><select name="recurrenceKind" value={mode} onChange={e=>{setMode(e.target.value);setEvery('');setWeekday('');setOrdinal('')}} required><option value="">Choose a timing rule</option><option value="after-service">Days after completed service</option><option value="meter-only">Meter hours only</option><option value="calendar-days">Fixed calendar day interval</option><option value="calendar-months">Same day number each scheduled month</option><option value="calendar-month-end">Last day of each scheduled month</option><option value="calendar-month-weekday">Selected weekday position each scheduled month</option></select></Field>
 {mode!=='meter-only'&&<div className="ops-fields"><Field name={mode==='after-service'?'Initial due date':'First scheduled due date'}><input type="date" name="initialDue" value={anchor} onChange={e=>setAnchor(e.target.value)} required/></Field>{mode==='after-service'?<Field name="Days after last completed service"><input type="number" name="intervalDays" min="1" max="3650" defaultValue={d?.intervalDays||''} required/></Field>:mode&&<Field name={monthly?'Calendar months between due dates':'Calendar days between due dates'}><input type="number" name="calendarEvery" min="1" max={monthly?'120':'3650'} value={every} onChange={e=>setEvery(e.target.value)} required/></Field>}<Field name="Warning window in days"><input type="number" name="warningDays" min="0" max="365" defaultValue={d?.warningDays} required/></Field></div>}
 {mode==='calendar-month-weekday'&&<div className="ops-fields"><Field name="Weekday position from source"><select name="calendarOrdinal" value={ordinal} onChange={e=>setOrdinal(e.target.value)} required><option value="">Choose position</option>{maintenanceOrdinals.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></Field><Field name="Weekday from source"><select name="calendarWeekday" value={weekday} onChange={e=>setWeekday(e.target.value)} required><option value="">Choose weekday</option>{maintenanceWeekdays.map((day,index)=><option key={day} value={index}>{day}</option>)}</select></Field></div>}
 {!!preview.length&&<div role="status"><p>First three scheduled dates: {preview.join(' · ')}</p>{preview[0]!==anchor&&<p className="ops-callout">The entered first due date does not match this rule. Choose {preview[0]} or another month’s matching occurrence; it will not be changed automatically.</p>}</div>}
 {mode==='after-service'?<p>The initial date is used until actual service is recorded. Each completed service moves the next due date by the checked number of days.</p>:mode&&mode!=='meter-only'&&<p>Due dates stay anchored to the first scheduled date, even when service is late or early. Record which scheduled occurrence was completed; missed occurrences stay due. {mode==='calendar-months'&&'Use the same day number each scheduled month; a shorter month uses its last day, then the original day resumes.'} After service evidence exists, a different calendar rule or first date needs a separate plan.</p>}
 {mode==='calendar-month-end'&&<p>The last date of each scheduled month is used, including February and leap years.</p>}{mode==='calendar-month-weekday'&&<p>Use the selected first, second, third, fourth or last weekday. Last means the final occurrence in that month; fifth-weekday and holiday-adjusted rules are not supported.</p>}
<p>Choose only timing stated in the checked source. Business-day calendars and holiday adjustments are not supplied.</p><MeterRuleFields rule={d?.meter} requiredOnly={mode==='meter-only'}/>
 <Field name="Responsible manager"><select name="managerId" defaultValue={d?.managerId??''} required><option value="">Choose manager</option>{w.members.filter(maintenanceManager).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field>
 <Field name="Evidence or reason"><textarea name="note" maxLength={2000} required/></Field>
 <label><input type="checkbox" name="checked" required/> I checked this equipment, task and timing thresholds against the stated source.</label>
 </>}
function planInput(f:FormData){return {meterEnabled:f.get('meterEnabled')==='on',meterRef:f.get('meterRef'),initialDueHours:Number(f.get('initialDueHours')),intervalHours:Number(f.get('intervalHours')),warningHours:Number(f.get('warningHours')),...Object.fromEntries(['title','equipment','task','sourceRef','initialDue','managerId','note','recurrenceKind','assetId'].map(k=>[k,f.get(k)])),assetRevision:f.get('assetRevision')?Number(f.get('assetRevision')):undefined,intervalDays:Number(f.get('intervalDays')),calendarEvery:Number(f.get('calendarEvery')),calendarWeekday:f.get('calendarWeekday')?Number(f.get('calendarWeekday')):undefined,calendarOrdinal:f.get('calendarOrdinal')?Number(f.get('calendarOrdinal')):undefined,warningDays:Number(f.get('warningDays')),checked:f.get('checked')==='on'};}
export function MaintenancePlans({w,send,busy,now,onHistory,onContacts}:{w:Workspace;send:Send;busy:boolean;now:string;onHistory:()=>void;onContacts:()=>void}){
 const [creating,setCreating]=useState(false),[selected,setSelected]=useState<string|null>(null),[filter,setFilter]=useState('active');
 const today=localDate(now,w.location.timezone),rows=w.records.filter((r):r is RecordOf<'maintenance'>=>r.kind==='maintenance'&&maintenanceReader(r,w.me)),chosen=rows.find(r=>r.id===selected);
 const displayed=rows.filter(r=>filter==='retired'?r.data.status==='retired':r.data.status==='active'&&(filter!=='due'||['overdue','today','due','soon','needs-reading'].includes(maintenanceSchedule(r.data,today).state))).sort((a,b)=>maintenanceSchedule(a.data,today).due.localeCompare(maintenanceSchedule(b.data,today).due)||a.data.title.localeCompare(b.data.title));
 return <section className="ops-page"><div className="shared-heading"><div><p className="ops-eyebrow">{w.location.name} · Maintenance</p><h1>Scheduled maintenance</h1></div>{maintenanceOwner(w.me)&&<button disabled={busy} onClick={()=>{setCreating(!creating);setSelected(null)}}>{creating?'Cancel new plan':'Add checked plan'}</button>}</div>
 <p>Track actual service against a checked task and interval. No equipment, service dates or procedures have been supplied automatically. Due dates are visible here and in the daily brief; reminders are not sent.</p>
 <button disabled={busy} onClick={onContacts}>Who to call</button>
 <details><summary>Open service-cost review</summary><ServiceCostReview key={w.location.id+':'+w.me.id} w={w} now={now} busy={busy}/></details>
 <details><summary>Open equipment register</summary><EquipmentRegister w={w} send={send} busy={busy}/></details>
 {creating&&<form className="ops-card" onSubmit={async e=>{e.preventDefault();if(await send('maintenance.create',planInput(new FormData(e.currentTarget))))setCreating(false)}}><h2>New checked maintenance plan</h2><fieldset disabled={busy}><PlanFields w={w}/><p><button className="shared-primary">Save maintenance plan</button></p></fieldset></form>}
 {chosen?<><p><button onClick={()=>setSelected(null)}>Back to maintenance</button></p><MaintenanceCard key={chosen.id+':'+chosen.revision} r={chosen} w={w} send={send} busy={busy} now={now}/></>:<><Field name="Show maintenance"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active plans</option><option value="due">Due, coming due or needs a reading</option>{maintenanceOwner(w.me)&&<option value="retired">Retired plans</option>}</select></Field>
 {!displayed.length&&<p className="ops-empty">No matching maintenance plans. An owner can enter an equipment-specific task and interval from a checked source.</p>}{displayed.map(r=>{const s=maintenanceSchedule(r.data,today);return <article className="ops-card" key={r.id}><div className="shared-heading"><h2>{r.data.title}</h2><span className="ops-badge">{s.state}</span></div><p>{r.data.equipment}</p><p>{r.data.meterOnly?'Meter hours only':`Calendar due: ${s.due}`} · {r.data.managerName}</p><MeterStatus r={r}/><p>{s.latest?'Last recorded service: '+s.latest.date:r.data.meterOnly?'No actual service recorded; first checked hour threshold applies.':'No actual service recorded; initial due date shown.'}</p><button disabled={busy} onClick={()=>{setCreating(false);setSelected(r.id)}}>Open {r.data.title}</button></article>})}<button onClick={onHistory}>Open work history</button></>}
 </section>;
}
export function MaintenanceCard({r,w,send,busy,now,readOnly=false}:{r:RecordOf<'maintenance'>;w:Workspace;send:Send;busy:boolean;now:string;readOnly?:boolean}){
 const d=r.data,today=localDate(now,w.location.timezone),s=maintenanceSchedule(d,today),owner=maintenanceOwner(w.me),assetState=equipmentLinkState(w,d.asset),canRecord=(!d.asset||assetState==='current')&&!readOnly&&d.status==='active'&&(owner||w.me.id===d.managerId);
 const contacts=w.records.filter((x):x is RecordOf<'servicecontact'>=>x.kind==='servicecontact'&&x.data.status==='active'&&contactReader(x,w.me));
 return <article className="ops-card"><h2>{d.title}</h2><p className="ops-badge">{s.state}{readOnly?' · Filed history':''}</p><p>{d.equipment}</p><p className="ops-preserve">{d.task}</p><p>Responsible manager: {d.managerName}</p>{!w.members.some(m=>m.id===d.managerId&&maintenanceManager(m))&&<p role="status">This manager is no longer available. An owner needs to assign a current manager.</p>}
 {d.meterOnly?<p><strong>{maintenanceTiming(d)}</strong></p>:<p><strong>{d.status==='retired'?'Last calculated due date':'Next due'}: {s.due}</strong> · {maintenanceTiming(d)}. Warning window: {d.warningDays} days.</p>}<p>{s.latest?'Latest unvoided service: '+s.latest.date:d.meterOnly?'No actual service recorded; using the source’s first checked hour threshold.':'No actual service recorded; using the source’s initial due date.'}</p>{d.recurrence&&<p className="ops-callout">The first occurrence without service evidence stays due. Later service dates do not automatically clear missed occurrences.</p>}
 {d.status==='retired'&&<p className="ops-callout">Retired plan: {d.retirementNote}</p>}
 <details><summary>Checked schedule source</summary><p className="ops-preserve">{d.sourceRef}</p>{!d.meterOnly&&<p>Initial due date: {d.initialDue}</p>}<p>Checked by {personName(w,d.checkedBy)} · {displayTime(d.checkedAt,w.location.timezone)}</p></details>
 {d.asset&&<details open><summary>Equipment checked with this plan</summary><AssetSnapshot asset={d.asset}/>{!readOnly&&assetState!=='current'&&<p className="ops-callout" role="status">Linked equipment is {assetState}. An owner must recheck this plan against current active equipment before recording service. Its due status remains visible.</p>}</details>}
 <MaintenanceMeterPanel r={r} w={w} send={send} busy={busy} canRecord={canRecord} owner={owner} readOnly={readOnly}/>
 {canRecord&&<details><summary>Record completed service</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),contact=contacts.find(x=>x.id===f.get('contactId'));await send('maintenance.service',{date:f.get('date'),meterReadingId:f.get('meterReadingId')||undefined,scheduledDue:d.recurrence?s.due:undefined,performedBy:f.get('performedBy'),evidence:f.get('evidence'),note:f.get('note'),contactId:contact?.id??'',contactRevision:contact?.revision,completed:f.get('completed')==='on'},r)}}><fieldset disabled={busy}>
 {d.recurrence&&<p><strong>Scheduled occurrence being completed: {s.due}</strong>. Record actual work for this occurrence only. Saving does not mark other missed occurrences complete.</p>}
 {d.meter&&<Field name="Actual meter reading on the service date"><select name="meterReadingId" required><option value="">Choose the checked reading from the same actual service date</option>{(d.meterReadings??[]).filter(x=>!x.voided).map(x=><option key={x.id} value={x.id}>{x.date} · {x.hours} hours</option>)}</select></Field>}
 <Field name={`Actual service date · ${w.location.timezone}`}><input type="date" name="date" max={today} required/></Field><Field name="Who performed the work"><input name="performedBy" maxLength={200} required/></Field>
 <Field name="Service contact · optional"><select name="contactId"><option value="">Internal work / no directory contact</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.data.title}</option>)}</select></Field>
 <Field name="Service evidence reference"><textarea name="evidence" maxLength={2000} required placeholder="Service report number, dated checklist or other evidence, and where it can be checked"/></Field><p>References do not upload documents or prove the work. Record the evidence you actually checked.</p>
 <Field name="Evidence or reason"><textarea name="note" maxLength={2000} required/></Field><label><input type="checkbox" name="completed" required/> The entire stated task was completed on this date. This is an actual service report.</label><p><button className="shared-primary">Save completed service</button></p>
 </fieldset></form></details>}
 <MaintenanceCostSummary r={r}/>
 <h3>Service evidence ({d.services.length})</h3>{!d.services.length&&<p>No completed service has been recorded.</p>}{d.services.slice().sort((a,b)=>b.date.localeCompare(a.date)||b.at.localeCompare(a.at)).map(entry=><article className="ops-card" key={entry.id}><h4>{entry.date} · {entry.voided?'Voided record':entry.performedBy}</h4><p className="ops-preserve">{entry.evidence}</p><p className="ops-preserve">{entry.note}</p>{entry.contact&&<p>Recorded service provider: {entry.contact.title}{entry.contact.contactName?' · '+entry.contact.contactName:''}. This is a retained reference, not a dispatch receipt.</p>}<p>Recorded by {personName(w,entry.by)} · {displayTime(entry.at,w.location.timezone)}</p><details><summary>Task source at the time</summary><p>{entry.plan.title} · {entry.plan.equipment}</p>{entry.plan.asset&&<AssetSnapshot asset={entry.plan.asset}/>}<p className="ops-preserve">{entry.plan.task}</p><p className="ops-preserve">{entry.plan.sourceRef}</p><p>{maintenanceTiming(entry.plan)}</p>{entry.plan.meter&&<p>{meterTiming(entry.plan.meter)}</p>}{entry.meter&&<p>Retained service meter: {entry.meter.hours} hours on {entry.meter.date}. Evidence: {entry.meter.evidence}</p>}{entry.scheduledDue&&<p>Scheduled occurrence: {entry.scheduledDue}</p>}</details>
 <MaintenanceServiceCost r={r} entry={entry} w={w} send={send} busy={busy} now={now} readOnly={readOnly}/>
 {entry.voided?<p>Voided by {personName(w,entry.voided.by)} · {displayTime(entry.voided.at,w.location.timezone)} · {entry.voided.reason}. Original evidence retained; excluded from recurrence.</p>:owner&&!readOnly&&<details><summary>Void incorrect service record</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await send('maintenance.void',{serviceId:entry.id,note:f.get('note'),confirmed:f.get('confirmed')==='on'},r)}}><fieldset disabled={busy}><Field name="Correction reason"><textarea name="note" maxLength={2000} required/></Field><label><input type="checkbox" name="confirmed" required/> Void this entry and recalculate service timing from the remaining service evidence.</label><p><button>Void service record</button></p></fieldset></form></details>}
 </article>)}
 {owner&&!readOnly&&<><details><summary>{d.status==='retired'?'Recheck and reactivate plan':'Revise checked plan'}</summary><form onSubmit={async e=>{e.preventDefault();await send('maintenance.revise',planInput(new FormData(e.currentTarget)),r)}}><fieldset disabled={busy}><PlanFields w={w} d={d}/><p><button>Save checked revision</button></p></fieldset></form></details>{d.status==='active'&&<details><summary>Retire maintenance plan</summary><form onSubmit={async e=>{e.preventDefault();await send('maintenance.retire',{note:new FormData(e.currentTarget).get('note')},r)}}><fieldset disabled={busy}><Field name="Retirement reason"><textarea name="note" maxLength={2000} required/></Field><button>Retire plan</button></fieldset></form></details>}</>}
 <details><summary>Plan history ({d.history.length})</summary><ol>{d.history.map((h,i)=><li key={i}>{h.action} · {personName(w,h.actorId)} · {displayTime(h.at,w.location.timezone)}<p>{h.note}</p></li>)}</ol>{d.versions.map((v,i)=><details key={i}><summary>Previous source · {displayTime(v.at,w.location.timezone)}</summary><p>{v.reason}</p><p>{v.facts.title} · {v.facts.equipment} · {v.facts.managerName}</p>{v.facts.asset&&<AssetSnapshot asset={v.facts.asset}/>}<p className="ops-preserve">{v.facts.task}</p><p className="ops-preserve">{v.facts.sourceRef}</p><p>{v.facts.meterOnly?maintenanceTiming(v.facts):`Initial due: ${v.facts.initialDue} · ${maintenanceTiming(v.facts)} · warning ${v.facts.warningDays} days`}</p>{v.facts.meter&&<p>{meterTiming(v.facts.meter)}</p>}</details>)}</details>
 </article>;
}
