'use client';
import {useState} from 'react';
import {promotionNeedsAck} from '../shared/promotions';
import { myWork } from '../shared/my-work';
import { localDate } from '../shared/local-time';
import { learningNextStep } from '../shared/learning-queue';
import { PersonalLearning } from './personal-learning';
import {PositionAchievements} from './position-achievements';
import {OperationalLearningHome} from './operational-learning';
import type {Send} from './workspace';
import { personalLearning } from '../shared/personal-learning';
import { shiftStationName } from '../shared/station-assignment';
import type { RecordOf, Workspace, WorkRecord } from '../shared/types';

export function MyDay({w,now,onOpen,onTraining,onSchedule,onDuties,onAsk,onStart,onPromotions,onIdeas,send,busy,onProgress,onLessons}:{send?:Send;busy?:boolean;onProgress?:()=>void;onLessons?:()=>void;onIdeas?:()=>void;onPromotions?:()=>void;w:Workspace;now:string;onOpen:(r:WorkRecord)=>void;onTraining:()=>void;onSchedule:()=>void;onDuties:()=>void;onAsk:(shift?:RecordOf<'shift'>)=>void;onStart:(guide:RecordOf<'standard'>)=>void}) {
 const [homeTab,setHomeTab]=useState<'today'|'learning'|'progress'>('today');
 const work=myWork(w,now),today=localDate(now,w.location.timezone),shiftDay=work.shift?localDate(work.shift.data.start,w.location.timezone):'';
 const path=personalLearning(w,now),linked=new Set(path.items.map(i=>i.goal?.id));
 const goals=w.records.filter((g):g is RecordOf<'goal'>|RecordOf<'development'>=>g.ownerId===w.me.id&&(g.kind==='goal'&&!linked.has(g.id)&&!['closed','declined','cancelled'].includes(g.data.phase)||g.kind==='development'&&!['approved','cancelled'].includes(g.data.phase)));
 const coming=work.ambiguous?[]:work.upcomingShifts.filter(s=>s.id!==work.shift?.id).slice(0,2);
 const ideaResponse=w.records.some(r=>r.kind==='staffidea'&&r.locationId===w.location.id&&r.ownerId===w.me.id&&r.data.responses.at(-1)&&!r.data.responses.at(-1)?.readAt);
 const shiftTime=(s:RecordOf<'shift'>)=>new Date(s.data.start).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:w.location.timezone}).replace(':00','')+' – '+new Date(s.data.end).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:w.location.timezone}).replace(':00','')+(localDate(s.data.end,w.location.timezone)!==localDate(s.data.start,w.location.timezone)?' · next day':'');
 return <section className="my-day" data-home-tab={homeTab}><div className="day-greeting"><p className="day-eyebrow">{new Date(now).toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric',timeZone:w.location.timezone})}</p><span>{w.me.name.split(' ')[0]}’s day</span></div>
  <nav className="day-home-tabs" aria-label="Your day views">{(['today','learning','progress'] as const).map(view=><button key={view} aria-pressed={homeTab===view} onClick={()=>setHomeTab(view)}>{view==='today'?'Today':view==='learning'?'Learning':'Progress'}</button>)}</nav>
  {homeTab==='today'&&<>
  {work.shift?<section className="day-shift-focus" aria-label="Your current or next shift"><button className="day-shift-open" onClick={()=>onOpen(work.shift!)}><span className="day-shift-status">{work.checkoutPending?'Checkout pending':work.current?'Scheduled now':shiftDay===today?'Your shift today':'Your next shift'}</span><h1>{work.station}</h1><strong className="day-shift-time">{shiftTime(work.shift)}</strong><span className="day-shift-meta">{shiftDay!==today?new Date(work.shift.data.start).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:w.location.timezone})+' · ':''}{work.shift.data.position}<span>View shift <b aria-hidden="true">›</b></span></span></button><button className="day-shift-ask" onClick={()=>onAsk(work.shift)}>Ask JMAX about this shift <span aria-hidden="true">↗</span></button></section>:<><h1>{work.ambiguous?'Check your shift':'Your day, '+w.me.name.split(' ')[0]}</h1><p>{work.ambiguous?'More than one shift overlaps. Check the schedule with your manager to confirm your station.':'No upcoming published shift. Your schedule and learning are still here.'} <button className="inline-action" onClick={onSchedule}>View schedule</button></p><button className="day-ask" onClick={()=>onAsk()}>Ask JMAX <span aria-hidden="true">↗</span></button></>}
  {onPromotions&&w.records.some(r=>r.kind==='promotion'&&promotionNeedsAck(r,w.me,now,w.location.timezone))&&<button className="day-ask" onClick={onPromotions}>Read your offer briefing or withdrawal notice →</button>}
  {onIdeas&&ideaResponse&&<button className="day-ask" onClick={onIdeas}>Read the response to your idea →</button>}
  <section aria-label="Your assignments"><div className="compact-heading"><h2>Your assignments</h2><button className="inline-action" onClick={onDuties}>All assignments →</button></div>{work.duties.length>0?<div className="compact-list">{work.duties.slice(0,3).map(item=><button className="compact-row" key={item.record.id} onClick={()=>onOpen(item.record)}><span><strong>{item.title}</strong><small>{item.next}{item.overdue?' · Overdue':''}</small></span><span aria-hidden="true">›</span></button>)}</div>:<p>No assignments waiting.</p>}</section>
  {coming.length>0&&<section className="day-coming" aria-label="Your upcoming shifts"><div className="compact-heading"><h2>Coming up</h2><button className="inline-action" onClick={onSchedule}>My schedule →</button></div>{coming.map(s=><button className="day-coming-row" key={s.id} onClick={()=>onOpen(s)}><span className="day-coming-date"><small>{new Date(s.data.start).toLocaleDateString('en-US',{weekday:'short',timeZone:w.location.timezone})}</small><strong>{new Date(s.data.start).toLocaleDateString('en-US',{day:'numeric',timeZone:w.location.timezone})}</strong></span><span><strong>{shiftStationName(s)}</strong><small>{new Date(s.data.start).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:w.location.timezone})} · {shiftTime(s)}</small></span><span aria-hidden="true">›</span></button>)}</section>}
  {work.guides.length>0&&<details className="day-reference"><summary>{work.shift?work.station+' reference guides':'Your job reference guides'}<span>{work.guides.length}</span></summary><div className="compact-list">{work.guides.slice(0,3).map(g=><button className="compact-row" key={g.id} onClick={()=>onOpen(g)}><span><strong>{g.data.title}</strong><small>Approved instructions</small></span><span aria-hidden="true">›</span></button>)}</div></details>}
  </>}
  {homeTab==='learning'&&<section aria-label="Learning"><h1>Learning</h1><PersonalLearning w={w} now={now} onOpen={onOpen} onStart={onStart} compact/>{goals.length>0&&<><h2>With your manager</h2><div className="compact-list">{goals.slice(0,3).map(g=>{const next=learningNextStep(w,g,now);return <button className="compact-row" key={g.id} onClick={()=>onOpen(g)}><span><strong>{g.data.title}</strong><small>{next.label}{next.needsMe?' · Your next step':''}</small></span><span aria-hidden="true">›</span></button>})}</div></>}<button className="inline-action" onClick={onTraining}>All training &amp; guides →</button></section>}
  {homeTab==='progress'&&<section aria-label="Progress"><h1>Your progress</h1><PositionAchievements w={w} send={send} busy={busy} onOpen={onOpen} compact onMore={onProgress}/>{onIdeas&&<button className="day-ask" onClick={onIdeas}>Share or follow up on an idea →</button>}{onLessons&&<OperationalLearningHome w={w} onOpen={onOpen} onShare={onLessons}/>}</section>}
 </section>;
}
