'use client';
import {useState} from 'react';
import {type RecordOf,type Workspace,personName} from '../shared/types';
import {openingOwner,openingReader} from '../shared/hiring-openings';
import {openingManager} from '../shared/hiring-openings';
import {hiringGM} from '../shared/hiring-policy';
import {applicantStages,applicantActive,applicantCurrent,type OpeningApplicant,type ApplicantState,type ApplicantFacts,type ApplicantStage} from '../shared/opening-applicants';
import {displayTime,localDate} from '../shared/local-time';
import type {Send} from './workspace';

function Field({name,children}:{name:string;children:React.ReactNode}){return <label className="shared-field">{name}{children}</label>}
function IdentityFields({a}:{a?:ApplicantFacts}){return <>
 <Field name="Applicant name"><input name="name" defaultValue={a?.name} maxLength={200} required/></Field>
 <Field name="Application reference"><input name="reference" defaultValue={a?.reference} maxLength={200} required placeholder="Unique source reference for this staffing request"/></Field>
 <Field name="Application received date"><input type="date" name="receivedOn" defaultValue={a?.receivedOn} required/></Field>
 <Field name="Checked application source"><textarea name="sourceRef" defaultValue={a?.sourceRef} maxLength={1500} required placeholder="Source and date checked; retain the original application separately."/></Field>
 </>}
function Confirm({label}:{label:string}){return <><Field name={label}><textarea name="note" maxLength={1500} required placeholder="Record the source or reason for this factual update."/></Field><label><input type="checkbox" name="checked" required/> I checked these facts against the source.</label></>}
function Facts({a}:{a:ApplicantState}){return <><p>{applicantStages[a.stage]} · Application received {a.receivedOn}</p><p className="ops-preserve">Application reference: {a.reference}<br/>Checked source: {a.sourceRef}</p>{a.followupOn&&<p>Owner follow-up: {a.followupOn}</p>}{a.interview&&<p className="ops-preserve">{a.stage==='planned'?'Planned interview':'Recorded interview'}: {a.interview.date} · {a.interview.interviewer}<br/>{a.interview.evidence}</p>}{a.hiringReview&&<p>Hiring approval evidence recorded for {a.hiringReview.candidateType} hiring · {a.hiringReview.interviews.length} completed interviews. This does not issue an offer or create an employee.</p>}</>}
export function OpeningApplicants({r,w,send,busy,now,readOnly=false}:{r:RecordOf<'opening'>;w:Workspace;send:Send;busy:boolean;now:string;readOnly?:boolean}){
 const [filter,setFilter]=useState<'active'|'closed'|'all'>('active'),[query,setQuery]=useState(''),[page,setPage]=useState(0);
 if(!openingOwner(w.me)||!openingReader(r,w.me))return null;
 const all=r.data.applicants??[],today=localDate(now,w.location.timezone),rows=all.filter(a=>(readOnly||filter==='all'||applicantActive(a)===(filter==='active'))&&(!query||[a.name,a.reference].some(x=>x.toLowerCase().includes(query.toLowerCase())))).sort((a,b)=>(a.followupOn||'9999').localeCompare(b.followupOn||'9999')||a.id.localeCompare(b.id));
 const start=Math.min(page,Math.max(0,Math.ceil(rows.length/10)-1))*10,open=r.data.status==='open'&&!!r.data.approval;
 const submit=(action:string,id?:string)=>(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const review=action==='hiring-review'?{offerApproved:f.get('offerApproved')==='on',interviews:[0,1,2].filter(i=>f.get('person'+i)).map(i=>({personId:f.get('person'+i),date:f.get('date'+i),evidence:f.get('evidence'+i)}))}:{};void send('opening.applicant-'+action,{...Object.fromEntries(f),...review,checked:f.get('checked')==='on',...(id?{applicantId:id}:{})},r)};
 return <section className="ops-card"><h3>Private applicants and interviews</h3><p className="ops-callout">Owner and administrator access only. Record source-backed contacts and interview facts. Dates here are internal follow-ups; they do not send invitations, publish jobs, assess candidates or make hiring decisions. Keep sensitive personal details and assessments in their authorized source.</p>
 <p>{all.filter(applicantActive).length} active tracking records · {all.filter(a=>applicantActive(a)&&a.followupOn<today).length} owner follow-ups past due</p>
 {!readOnly&&<><Field name="Search applicants by name or reference"><input value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></Field><div className="shared-actions">{(['active','closed','all'] as const).map(value=><button type="button" key={value} disabled={busy} aria-pressed={filter===value} onClick={()=>{setFilter(value);setPage(0)}}>{value==='active'?'Active applicants':value==='closed'?'Closed tracking':'All applicants'}</button>)}</div>
 {open?<details><summary>Record received application</summary><form onSubmit={submit('add')}><fieldset disabled={busy}><IdentityFields/><Field name="Owner follow-up date"><input type="date" name="followupOn" required/></Field><Confirm label="Application source check note"/><p><button className="shared-primary">Save received application</button></p></fieldset></form></details>:<p>Approve the current staffing request before adding or progressing applicant tracking. Existing records can still be corrected or closed.</p>}</>}
 {!rows.length&&<p>No applicant records in this view.</p>}{rows.slice(start,start+10).map(a=><ApplicantCard key={a.id+':'+r.revision} a={a} r={r} w={w} busy={busy} readOnly={readOnly} today={today} submit={submit}/>) }
 {rows.length>10&&<div className="shared-actions"><p>{start+1}–{Math.min(start+10,rows.length)} of {rows.length}</p><button disabled={busy||start===0} onClick={()=>setPage(Math.max(0,start/10-1))}>Previous applicants</button><button disabled={busy||start+10>=rows.length} onClick={()=>setPage(start/10+1)}>Next applicants</button></div>}
 </section>;
}
function ApplicantCard({a,r,w,busy,readOnly,today,submit}:{a:OpeningApplicant;r:RecordOf<'opening'>;w:Workspace;busy:boolean;readOnly:boolean;today:string;submit:(action:string,id?:string)=>(e:React.FormEvent<HTMLFormElement>)=>void}){
 const [stage,setStage]=useState<ApplicantStage>(applicantCurrent(r,a)?a.stage:'closed'),active=applicantActive(a),current=applicantCurrent(r,a),open=r.data.status==='open'&&!!r.data.approval;
 return <article className="ops-card"><h4>{a.name}</h4><Facts a={a}/>{!readOnly&&active&&a.followupOn<today&&<p className="ops-callout">Owner follow-up date has passed.</p>}
 {a.hiringReview&&<details><summary>Checked hiring approval evidence</summary><p>Final approval: {personName(w,a.hiringReview.approverId)}<br/>Recorded by {personName(w,a.hiringReview.by)} · {displayTime(a.hiringReview.at,w.location.timezone)}</p><p className="ops-preserve">{a.hiringReview.evidence}</p>{a.hiringReview.interviews.map((i,index)=><p className="ops-preserve" key={index}>{personName(w,i.personId)} · {i.date}<br/>{i.evidence}</p>)}{!current&&<p>Opening or application facts changed; this approval is retained evidence and must be checked again before use.</p>}</details>}
 {!readOnly&&<>
 {active&&current&&<details><summary>Record checked hiring approval</summary><form onSubmit={submit('hiring-review',a.id)}><fieldset disabled={busy}>
 <p>Every position requires two distinct manager interviews; the GM can be one. Frontline hiring needs GM approval. Management or GM hiring also needs an owner interview and owner final offer approval. Optional peer interviews remain at the GM’s discretion and do not replace required interviews. Record checked evidence here; offers and employee setup happen separately.</p>
 <p>Management and GM approval recording is blocked until explicit owner identity is configured. Administrator access or an Owner job title cannot substitute.</p>
 <Field name="Hiring category"><select name="candidateType" required><option value="frontline">Frontline</option><option value="management">Management</option><option value="gm">General manager</option></select></Field>
 {[0,1,2].map(i=><div key={i}><Field name={'Completed interview '+(i+1)}><select name={'person'+i}><option value="">Choose manager or owner</option>{w.members.filter(m=>openingManager(m)||openingOwner(m)).map(m=><option key={m.id} value={m.id}>{m.name} · {m.position}</option>)}</select></Field><Field name="Interview date"><input type="date" name={'date'+i}/></Field><Field name="Checked interview source"><textarea name={'evidence'+i} maxLength={1500}/></Field></div>)}
 <Field name="Final hiring approver"><select name="approverId" required><option value="">Choose authorized GM or owner</option>{w.members.filter(m=>hiringGM(m)||openingOwner(m)).map(m=><option key={m.id} value={m.id}>{m.name} · {m.position}</option>)}</select></Field>
 <Field name="Checked final approval source"><textarea name="approvalEvidence" maxLength={1500} required/></Field><label><input type="checkbox" name="offerApproved" required/> The authorized person gave final hiring/offer approval.</label><Confirm label="Hiring review source note"/><p><button>Save checked hiring approval</button></p>
 </fieldset></form></details>}
 {active&&!current&&<p className="ops-callout">Opening approval or application facts changed. Check the current opening before recording further progress.</p>}
 {active&&!current&&open&&<form onSubmit={submit('recheck',a.id)}><fieldset disabled={busy}><Confirm label="Current opening review note"/><p><button>Confirm current opening review</button></p></fieldset></form>}
 {active&&<details><summary>Record applicant update</summary><form onSubmit={submit('update',a.id)}><fieldset disabled={busy}><Field name="Factual tracking stage"><select name="stage" value={stage} onChange={e=>setStage(e.target.value as ApplicantStage)} required>{Object.entries(applicantStages).filter(([key])=>current||!applicantActive({stage:key as ApplicantStage})).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field>
 {applicantActive({stage})&&current&&<Field name="Owner follow-up date"><input type="date" name="followupOn" defaultValue={a.followupOn} required/></Field>}
 {(stage==='planned'||stage==='interviewed')&&current&&<><Field name="Interview date"><input type="date" name="interviewDate" defaultValue={a.interview?.date} required/></Field><Field name="Named interviewer"><input name="interviewer" defaultValue={a.interview?.interviewer} maxLength={200} required/></Field><Field name="Interview source evidence"><textarea name="interviewEvidence" defaultValue={a.interview?.evidence} maxLength={1500} required placeholder="Checked appointment or actual completion record. No candidate assessment."/></Field></>}
 <Confirm label="Applicant update note"/><p><button>Save factual tracking update</button></p></fieldset></form></details>}
 {!active&&open&&<details><summary>Reopen applicant tracking</summary><form onSubmit={submit('reopen',a.id)}><fieldset disabled={busy}><p>Returns tracking to Application received. Earlier contacts and interviews remain in history.</p><Field name="Owner follow-up date"><input type="date" name="followupOn" required/></Field><Confirm label="Reopen reason and source check"/><p><button>Reopen as received</button></p></fieldset></form></details>}
 <details><summary>Correct application facts</summary><form onSubmit={submit('correct',a.id)}><fieldset disabled={busy}><IdentityFields a={a}/>{active&&<Field name="Owner follow-up date"><input type="date" name="followupOn" defaultValue={a.followupOn} required/></Field>}<p>Earlier facts remain in history. Active tracking needs a fresh check against the approved opening after a correction.</p><Confirm label="Application correction reason"/><p><button>Save corrected application facts</button></p></fieldset></form></details>
 </>}
 <details><summary>Private applicant history ({a.events.length})</summary>{a.events.slice().reverse().map((event,i)=><article key={i}><h4>{event.state.name} · {event.action}</h4><p>{personName(w,event.by)} · {displayTime(event.at,w.location.timezone)}</p><Facts a={event.state}/><p className="ops-preserve">{event.note}</p></article>)}</details>
 </article>;
}
