'use client';
import {useState,type ReactNode} from 'react';
import {operationalLearningParticipant,operationalLearningReader,operationalLearningReviewer,operationalLearningSources,operationalLearningSourceState} from '../shared/operational-learning';
import {personName,type Workspace,type RecordOf,type WorkRecord} from '../shared/types';
import {displayTime} from '../shared/local-time';
import type {Send} from './workspace';
import './operational-growth.css';

function Field({label,children}:{label:string;children:ReactNode}){return <label className="shared-field">{label}{children}</label>}
function SavedForm({send,busy=false,action,record,children,onSaved}:{send:Send;busy?:boolean;action:string;record?:WorkRecord;children:ReactNode;onSaved?:()=>void}){
 const [error,setError]=useState(''),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');
 return <form data-workflow={action} onSubmit={async e=>{e.preventDefault();if(busy||saving)return;const f=new FormData(e.currentTarget),input:Record<string,unknown>={};for(const [key,value]of f.entries())input[key]=value;input.confirmed=f.get('confirmed')==='on';input.shareConfirmed=f.get('shareConfirmed')==='on';if(input.sourceRevision)input.sourceRevision=Number(input.sourceRevision);if(input.assetRevision)input.assetRevision=Number(input.assetRevision);setError('');setNotice('');setSaving(true);try{if(await send(action,input,record)){setNotice('Saved. Your original report and review history are retained.');onSaved?.();}else setError('This change was not confirmed. Your report remains unchanged; retry after refreshing the workspace.');}catch(error){setError(error instanceof Error?error.message:'The change could not be saved. Please try again.');}finally{setSaving(false)}}}><fieldset disabled={busy||saving}>{children}</fieldset>{error&&<p className="shared-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</form>;
}
function FactsForm({w,send,busy,r,onSaved}:{w:Workspace;send:Send;busy:boolean;r?:RecordOf<'learningcase'>;onSaved?:()=>void}){
 const sources=operationalLearningSources(w),[sourceId,setSourceId]=useState(r?.data.source.id??''),source=sources.find(x=>x.id===sourceId),facts=r?.data;
 return <SavedForm send={send} busy={busy} action={r?'learningcase.revise':'learningcase.submit'} record={r} onSaved={onSaved}><Field label="Link the saved work or equipment"><select name="sourceId" value={sourceId} required onChange={e=>setSourceId(e.target.value)}><option value="">Choose accessible work</option>{sources.map(s=><option key={s.id} value={s.id}>{s.data.title}</option>)}</select></Field><input type="hidden" name="sourceRevision" value={source?.revision??''}/>{source&&source.kind==='maintenance'&&<Field label="Recorded service · optional"><select key={source.id} name="serviceId" defaultValue={facts?.source.id===source.id?facts.source.serviceId??'':''}><option value="">No recorded service linked</option>{source.data.services.filter(s=>!s.voided).map(s=><option key={s.id} value={s.id}>{displayTime(s.at,w.location.timezone)} · {s.note}</option>)}</select></Field>}
 <Field label="A short title"><input name="title" required maxLength={200} defaultValue={facts?.title}/></Field><Field label="What did you notice?"><textarea name="symptom" required maxLength={3000} defaultValue={facts?.symptom}/></Field><Field label="What did you actually do? · optional"><textarea name="actionsTaken" maxLength={3000} defaultValue={facts?.actionsTaken}/></Field><Field label="What happened afterward?"><textarea name="observedResult" required maxLength={3000} defaultValue={facts?.observedResult}/></Field><Field label="What are you still unsure about? · optional"><textarea name="uncertainty" maxLength={2000} defaultValue={facts?.uncertainty}/></Field><Field label="What still needs doing? · optional"><textarea name="remainingWork" maxLength={2000} defaultValue={facts?.remainingWork}/></Field>{r&&<Field label="Why are you correcting this report?"><textarea name="note" required maxLength={3000}/></Field>}
 <p className="growth-private">Share only the operational facts you want reviewed. Your private JMAX conversations are not copied here. An independent manager reviews the outcome before this becomes a shared lesson for your department.</p><label><input name="shareConfirmed" type="checkbox" required/> Share these facts with authorized reviewers and, after review, staff in this restaurant’s department.</label><div className="shared-actions"><button className="shared-primary" disabled={!source}>{r?'Save corrected report':'Share for manager review'}</button></div>{!sources.length&&<p>No accessible saved work is available to link yet. Ask your manager to record the work or issue first.</p>}</SavedForm>;
}
export function OperationalLearningHome({w,onOpen,onShare}:{w:Workspace;onOpen:(r:WorkRecord)=>void;onShare:()=>void}){
 if(!operationalLearningParticipant(w.me))return null;
 const cases=w.records.filter((r):r is RecordOf<'learningcase'>=>r.kind==='learningcase'&&operationalLearningReader(r,w.me)),pending=cases.filter(r=>r.data.status==='reported'&&r.ownerId!==w.me.id&&operationalLearningReviewer(w.me,r.area));
 return <section className="growth-panel" aria-label="Shift lessons"><div className="compact-heading"><h2>A useful lesson from your shift</h2><button className="inline-action" onClick={onShare}>{pending.length?'Review '+pending.length+' report'+(pending.length===1?'':'s')+' →':'Share or read a shift lesson →'}</button></div><p>Something worked, failed, or still needs checking? Share the facts, keep the uncertainty, and help the next shift. Private conversations stay private.</p>{cases.filter(r=>r.ownerId===w.me.id&&r.data.status==='reported').slice(0,2).map(r=><button className="compact-row" key={r.id} onClick={()=>onOpen(r)}><span><strong>{r.data.title}</strong><small>Awaiting independent manager review</small></span><span aria-hidden="true">›</span></button>)}</section>;
}
export function OperationalLearning({w,send,busy=false,onOpen,onBack}:{w:Workspace;send:Send;busy?:boolean;onOpen:(r:WorkRecord)=>void;onBack?:()=>void}){
 if(!operationalLearningParticipant(w.me))return null;
 const cases=w.records.filter((r):r is RecordOf<'learningcase'>=>r.kind==='learningcase'&&operationalLearningReader(r,w.me)).sort((a,b)=>Number(a.data.status!=='reported')-Number(b.data.status!=='reported')||b.updatedAt.localeCompare(a.updatedAt));
 return <section className="growth-panel">{onBack&&<button className="inline-action" onClick={onBack}>‹ Back to your day</button>}<div className="growth-banner"><p className="day-eyebrow">{w.location.name} · {w.me.area}</p><h1>Shift lessons</h1><p>Turn an observed problem and its checked outcome into useful context for the next shift.</p></div><p>These are dated experiences, not new approved procedures. Use your approved instructions and manager direction for the work.</p><details><summary>Share a lesson from your work</summary><FactsForm w={w} send={send} busy={busy}/></details><h2>Reports and reviewed lessons</h2>{cases.map(r=><OperationalLearningCard key={r.id+':'+r.revision} r={r} w={w} send={send} busy={busy} onOpen={onOpen}/>)}{!cases.length&&<p>No shared reports are recorded in your accessible department yet.</p>}</section>;
}
export function OperationalLearningCard({r,w,send,busy=false,onOpen,readOnly=false}:{r:RecordOf<'learningcase'>;w:Workspace;send:Send;busy?:boolean;onOpen?:(r:WorkRecord)=>void;readOnly?:boolean}){
 const [causeStatus,setCauseStatus]=useState('not-established'),[assetId,setAssetId]=useState(r.data.asset?.id??'');
 if(!operationalLearningReader(r,w.me))return null;
 const d=r.data,own=r.ownerId===w.me.id,reviewer=operationalLearningReviewer(w.me,r.area),source=w.records.find(s=>s.id===d.source.id),sourceState=d.readSourceState??operationalLearningSourceState(w,r),current=sourceState==='current',supported=!!source&&(source.kind==='task'&&source.data.phase==='closed'&&source.data.history.some(h=>h.action==='verify'&&h.actorId!==source.ownerId)||source.kind==='maintenance'&&!!d.source.serviceId&&source.data.services.some(s=>s.id===d.source.serviceId&&!s.voided));
 const assets=operationalLearningSources(w).filter((source):source is RecordOf<'equipment'>=>source.kind==='equipment'&&source.data.status==='active'&&(!d.asset||source.id===d.asset.id)),selectedAsset=assets.find(asset=>asset.id===assetId),canReview=current||!!d.asset&&selectedAsset?.id===d.asset.id&&operationalLearningSourceState(w,{...r,data:{...d,asset:undefined}})==='current';
 return <article className="growth-card"><span className="growth-status">{d.status==='reported'?'Awaiting manager review':d.status==='withdrawn'?'Withdrawn report':d.review?.verdict==='supported'?'Outcome supported by saved evidence':d.review?.verdict==='failed'?'Reviewed · did not resolve the problem':'Reviewed · outcome uncertain'}</span><h2>{d.title}</h2><p>{d.reporterName} · {displayTime(d.submittedAt,w.location.timezone)}</p><h3>Observed problem</h3><p className="ops-preserve">{d.symptom}</p><h3>Actions actually taken</h3><p className="ops-preserve">{d.actionsTaken||'No action reported.'}</p><h3>Observed outcome</h3><p className="ops-preserve">{d.observedResult}</p>{d.uncertainty&&<><h3>Still uncertain</h3><p className="ops-preserve">{d.uncertainty}</p></>}{d.remainingWork&&<><h3>Next shift or unfinished work</h3><p className="ops-preserve">{d.remainingWork}</p></>}
 <div className="growth-evidence"><p>Linked work: {d.source.title} · saved version {d.source.revision}</p><p>{current?'Linked evidence matches its saved version.':sourceState==='unavailable'?'The linked evidence is not available in your view. Its current state is unconfirmed here.':'The linked evidence is '+sourceState+'. Refresh and relink it before using this outcome.'}</p>{source&&onOpen&&<button className="inline-action" onClick={()=>onOpen(source)}>Open linked work →</button>}{d.asset&&<p>Equipment: {d.asset.title}{d.asset.assetTag?' · '+d.asset.assetTag:''} · saved version {d.asset.revision}</p>}</div>
 {d.review&&<section className="growth-evidence"><h3>Independent outcome review</h3><p>{personName(w,d.review.by)} · {displayTime(d.review.at,w.location.timezone)}</p><p className="ops-preserve">{d.review.evidence}</p><p className="ops-preserve">{d.review.note}</p><p>{d.review.causeStatus==='not-established'?'The cause has not been established.':(d.review.causeStatus==='confirmed'?'Confirmed cause: ':'Reported cause, not confirmed: ')+d.review.cause}</p><p>This is historical evidence. It does not approve a troubleshooting procedure or establish that a repair is safe now.</p></section>}
 {!readOnly&&d.status!=='withdrawn'&&(own||reviewer)&&<details><summary>Correct this report or relink current work</summary><FactsForm w={w} send={send} busy={busy} r={r}/></details>}
 {!readOnly&&d.status!=='withdrawn'&&reviewer&&!own&&<details><summary>Review the observed outcome</summary>{canReview?<SavedForm send={send} busy={busy} action="learningcase.review" record={r}>{!current&&<p>The linked work is current, but this same machine’s record changed. Check its current equipment record and review the outcome again before reusing the lesson.</p>}<Field label="What does the evidence establish?"><select name="verdict" required defaultValue=""><option value="">Choose an outcome</option><option value="supported" disabled={!supported}>Outcome supported by checked work</option><option value="uncertain">Outcome still uncertain</option><option value="failed">Action did not resolve the problem</option></select></Field>{!supported&&<p>A supported outcome needs an independently verified completed task or a recorded maintenance service. Equipment identity alone is not repair evidence.</p>}<Field label="Identify the checked machine or equipment · optional"><select name="assetId" value={assetId} onChange={e=>setAssetId(e.target.value)}>{!d.asset&&<option value="">No equipment linked</option>}{assets.map(asset=><option key={asset.id} value={asset.id}>{asset.data.title} · {asset.data.assetTag}</option>)}</select></Field><input type="hidden" name="assetRevision" value={selectedAsset?.revision??''}/>{d.asset&&<p>This case stays linked to its original equipment. A different physical machine needs its own report.</p>}<Field label="What independent evidence did you check?"><textarea name="evidence" maxLength={2000} required/></Field><Field label="Review note and its limits"><textarea name="note" maxLength={3000} required/></Field><Field label="Is the cause established?"><select name="causeStatus" value={causeStatus} onChange={e=>setCauseStatus(e.target.value)}><option value="not-established">Cause not established</option><option value="reported">Cause reported, not confirmed</option><option value="confirmed">Cause confirmed by evidence</option></select></Field>{causeStatus!=='not-established'&&<Field label="Reported or confirmed cause"><textarea name="cause" required maxLength={2000}/></Field>}<label><input name="confirmed" type="checkbox" required/> This review describes observed evidence and its limits; it is not approval of a new procedure.</label><button className="shared-primary">Save independent review</button></SavedForm>:<p>Review is paused until the reporter or an authorized manager relinks current accessible evidence.</p>}</details>}
 {!readOnly&&d.status!=='withdrawn'&&(own||reviewer)&&<details><summary>Withdraw this shared report</summary><SavedForm send={send} busy={busy} action="learningcase.withdraw" record={r}><Field label="Reason for withdrawal"><textarea name="note" required maxLength={3000}/></Field><label><input name="confirmed" type="checkbox" required/> Withdraw this case from future shared lessons; retain the dated report and review history.</label><button>Withdraw report</button></SavedForm></details>}
 <details><summary>Report history ({d.history.length})</summary><ol>{d.history.map((h,i)=><li key={i}>{h.action} · {personName(w,h.actorId)} · {displayTime(h.at,w.location.timezone)}<p>{h.note}</p></li>)}</ol></details>
 </article>;
}
