'use client';
import { useState } from 'react';
import { has, personName, type Workspace, type RecordOf } from '../shared/types';
import { displayTime, localDate, localInstant } from '../shared/local-time';
import { logCategories, operationsManager } from '../shared/operations';
import type { Send } from './workspace';
import {RepairContactLog} from './service-contacts';
import { ShiftLog } from './shift-log';
import './operations.css';

function Fields({children}:{children:React.ReactNode}){return <div className="ops-fields">{children}</div>}
function Field({name,children}:{name:string;children:React.ReactNode}){return <label className="shared-field">{name}{children}</label>}
function dueValue(value:FormData,zone:string){return localInstant(String(value.get('date')),String(value.get('time')),zone);}
function DueFields({zone,at}:{zone:string;at:string}){return <><Field name={`Due date · ${zone}`}><input name="date" type="date" required defaultValue={localDate(at,zone)}/></Field><Field name="Time"><input name="time" type="time" required defaultValue={new Intl.DateTimeFormat('en-GB',{timeZone:zone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(at))}/></Field></>}

export function ManagerLog({w,send,busy,now,repairMode=false,limitedToNotes=false,initialIssueId,initialEntryId,onGuests,onContacts}:{w:Workspace;send:Send;busy:boolean;now:string;repairMode?:boolean;limitedToNotes?:boolean;initialIssueId?:string;initialEntryId?:string;onGuests?:()=>void;onContacts?:()=>void}) {
  const departments=['FOH','BOH','combined','production'].filter(area=>operationsManager(w.me,area));
  const [filter,setFilter]=useState('open'),[creating,setCreating]=useState(false),[error,setError]=useState(''),[view,setView]=useState(limitedToNotes||repairMode||initialIssueId?'issues':'shifts'),[department,setDepartment]=useState(departments.includes('BOH')?'BOH':departments[0]??w.me.area),[focused,setFocused]=useState(initialIssueId);
  const records=w.records.filter((r):r is RecordOf<'managerlog'>=>r.kind==='managerlog'&&r.locationId===w.location.id&&operationsManager(w.me,r.area)&&(!repairMode||r.data.category==='Maintenance'));
  const rows=records.filter(r=>focused?r.id===focused:filter==='all'||(filter==='resolved'?r.data.status==='resolved':r.data.status!=='resolved')).sort((a,b)=>Number(b.data.priority==='urgent')-Number(a.data.priority==='urgent')||(a.data.due??'9999').localeCompare(b.data.due??'9999'));
  const owners=w.members.filter(m=>operationsManager(m,department));
  return <section className="ops-page"><div className="shared-heading"><div><p className="ops-eyebrow">{w.location.name} · {repairMode?'Maintenance':'Operations'}</p><h1>{repairMode?'Repair requests':'Manager Log / Red Book'}</h1></div><button disabled={busy} onClick={()=>{setView('issues');setFocused(undefined);setCreating(!creating)}}>{repairMode?'Report repair':'New issue'}</button></div>
    <p>{limitedToNotes?'Record manager issues and add updates. Saved entries keep the author and time. Refresh to see updates from other devices.':repairMode?'Repairs share the same entry, responsible manager and history as the Manager Log. Resolve it once, and both views update.':'Unfinished work stays here until someone resolves it. Acceptance confirms who has picked it up.'}</p>
    {onContacts&&<button disabled={busy} onClick={onContacts}>Who to call</button>}
    {!repairMode&&onGuests&&<button disabled={busy} onClick={onGuests}>Guest reviews and owner follow-up</button>}
    <div className="ops-callout">Urgent injury, theft, damage or service interruption: call the primary owner now, then the other owner if unanswered. Saving an entry does not place a call or send an alert.</div>
    {!limitedToNotes&&!repairMode&&<div className="ops-filters"><button aria-pressed={view==='shifts'} onClick={()=>{setView('shifts');setCreating(false);setFocused(undefined)}}>Shift summaries</button><button aria-pressed={view==='issues'} onClick={()=>setView('issues')}>Issues and follow-up</button></div>}
    {focused&&<button className="compact-back" onClick={()=>setFocused(undefined)}>‹ All issues</button>}
    {!limitedToNotes&&view==='shifts'&&<ShiftLog w={w} send={send} busy={busy} now={now} initialEntryId={initialEntryId}/>}
    {error&&<p role="alert" className="shared-error">{error}</p>}
    {creating&&<form className="ops-card" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setError('');try{if(await send('managerlog.create',{department,title:f.get('title'),detail:f.get('detail'),category:repairMode?'Maintenance':f.get('category'),priority:f.get('priority'),ownerId:f.get('ownerId'),due:dueValue(f,w.location.timezone)}))setCreating(false)}catch(err){setError(err instanceof Error?err.message:'Check the due date.')}}}>
      <fieldset disabled={busy}><Fields><Field name="Department"><select value={department} onChange={e=>setDepartment(e.target.value)}>{departments.map(d=><option key={d}>{d}</option>)}</select></Field><Field name="Summary"><input name="title" maxLength={200} required/></Field><Field name="Category"><select name="category" defaultValue={repairMode?'Maintenance':undefined} disabled={repairMode}>{(repairMode?['Maintenance']:logCategories).map(c=><option key={c}>{c}</option>)}</select></Field><Field name="Responsible manager"><select key={department} name="ownerId" required><option value="">Choose manager</option>{owners.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field name="Priority"><select name="priority"><option value="routine">Routine follow-up</option><option value="urgent">Urgent — phone call required</option></select></Field><DueFields zone={w.location.timezone} at={now}/></Fields><Field name="What happened, temporary action and next step"><textarea name="detail" maxLength={4000} required/></Field><button className="shared-primary">Save entry</button></fieldset>
    </form>}
    {view==='issues'&&<><div className="ops-filters" aria-label="Log filter">{[['open','Needs follow-up'],['resolved','Resolved'],['all','All history']].map(([value,label])=><button key={value} aria-pressed={!focused&&filter===value} onClick={()=>{setFocused(undefined);setFilter(value)}}>{label} ({records.filter(r=>value==='all'||(value==='resolved'?r.data.status==='resolved':r.data.status!=='resolved')).length})</button>)}</div>
    {!rows.length&&<p className="ops-empty">No entries in this view.</p>}
    {rows.map(r=><LogEntry limitedToNotes={limitedToNotes} key={r.id+':'+r.revision} r={r} w={w} send={send} busy={busy} now={now}/>)}</>}
  </section>;
}
function LogEntry({r,w,send,busy,now,limitedToNotes=false}:{r:RecordOf<'managerlog'>;w:Workspace;send:Send;busy:boolean;now:string;limitedToNotes?:boolean}){
  const [note,setNote]=useState(''),[reassign,setReassign]=useState(false),[error,setError]=useState('');
  const action=(name:string)=>send(`managerlog.${name}`,{note},r);
  return <article className="ops-card"><div className="shared-heading"><h2>{r.data.title}</h2><span className={`ops-badge ${r.data.priority==='urgent'?'urgent':''}`}>{r.data.status} · {r.data.priority}</span></div><p className="ops-preserve">{r.data.detail}</p><p className="shared-muted">{r.data.category} · {personName(w,r.ownerId)} · {r.data.due?'Due '+displayTime(r.data.due,w.location.timezone):'Due time not set'}{r.data.status!=='resolved'&&r.data.due&&r.data.due<now?' · OVERDUE':''}</p>{r.data.resolution&&<p><strong>Resolution:</strong> {r.data.resolution}</p>}
    <Field name="Update or outcome"><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={4000}/></Field><div className="shared-actions"><button disabled={busy||!note.trim()} onClick={()=>void action('note')}>Add note</button>{!limitedToNotes&&(r.data.status!=='resolved'?<>{r.ownerId===w.me.id&&r.data.status==='open'&&<button disabled={busy||!note.trim()} onClick={()=>void action('accept')}>Accept handoff</button>}{(r.ownerId===w.me.id||has(w.me,'location.manage'))&&<button disabled={busy||!note.trim()} onClick={()=>void action('resolve')}>Resolve with outcome</button>}<button onClick={()=>setReassign(!reassign)}>Change responsibility</button></>:<button disabled={busy||!note.trim()} onClick={()=>void action('reopen')}>Reopen</button>)}</div>
    {!limitedToNotes&&reassign&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await send('managerlog.reassign',{note,ownerId:f.get('ownerId'),due:dueValue(f,w.location.timezone)},r)}catch(err){setError(String(err))}}}><fieldset disabled={busy}><Fields><Field name="New responsible manager"><select name="ownerId" required>{w.members.filter(m=>operationsManager(m,r.area)).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><DueFields zone={w.location.timezone} at={r.data.due??now}/></Fields><button disabled={!note.trim()}>Save handoff</button></fieldset></form>}{error&&<p role="alert">{error}</p>}
    {!limitedToNotes&&r.data.category==='Maintenance'&&<RepairContactLog r={r} w={w} send={send} busy={busy} now={now}/>}
    <details><summary>Entry history ({r.data.history.length})</summary><ol>{r.data.history.map((h,i)=><li key={i}><strong>{h.action}</strong> · {personName(w,h.actorId)} · {displayTime(h.at,w.location.timezone)}<p>{h.note}</p></li>)}</ol></details>
  </article>;
}

export function ManagerMeetings({w,send,busy,now}:{w:Workspace;send:Send;busy:boolean;now:string}){
  const [creating,setCreating]=useState(false),[error,setError]=useState('');
  const meetings=w.records.filter((r):r is RecordOf<'meeting'>=>r.kind==='meeting');
  return <section className="ops-page"><div className="shared-heading"><div><p className="ops-eyebrow">{w.location.name} · Leadership</p><h1>Manager one-on-ones</h1></div>{has(w.me,'location.manage')&&<button onClick={()=>setCreating(!creating)}>Set up meeting</button>}</div><p>Private to the owner and manager participating. Unfinished follow-ups carry forward. Every two weeks is a starting option; choose the cadence that works for this manager.</p>{error&&<p role="alert" className="shared-error">{error}</p>}
    {creating&&<form className="ops-card" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{if(await send('meeting.create',{managerId:f.get('managerId'),cadenceDays:Number(f.get('cadenceDays')),agenda:f.get('agenda'),due:dueValue(f,w.location.timezone)}))setCreating(false)}catch(err){setError(String(err))}}}><fieldset disabled={busy}><Fields><Field name="Manager"><select name="managerId" required><option value="">Choose manager</option>{w.members.filter(m=>m.id!==w.me.id&&operationsManager(m)).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field name="Repeat every (days)"><input name="cadenceDays" type="number" min={1} max={90} defaultValue={14} required/></Field><DueFields zone={w.location.timezone} at={now}/></Fields><Field name="Agenda"><textarea name="agenda" maxLength={4000} defaultValue="Wins, concerns, support needed and agreed next steps"/></Field><button className="shared-primary">Create private meeting</button></fieldset></form>}
    {!meetings.length&&<p className="ops-empty">No one-on-ones have been configured for you at this restaurant.</p>}{meetings.map(r=><MeetingCard key={r.id+':'+r.revision} r={r} w={w} send={send} busy={busy} now={now}/>)}
  </section>;
}
function MeetingCard({r,w,send,busy,now}:{r:RecordOf<'meeting'>;w:Workspace;send:Send;busy:boolean;now:string}){
  const [notes,setNotes]=useState(''),[error,setError]=useState('');
  return <article className="ops-card"><h2>{personName(w,r.ownerId)} + {personName(w,r.data.managerId)}</h2><p>Next: {displayTime(r.data.due,w.location.timezone)} · Every {r.data.cadenceDays} days</p><p className="ops-preserve">{r.data.agenda}</p>
    <h3>Follow-ups</h3>{r.data.actions.filter(a=>!a.doneAt).map(a=><div className="ops-action" key={a.id}><span>{a.title}<small>{personName(w,a.ownerId)} · {displayTime(a.due,w.location.timezone)}</small></span><button disabled={busy} onClick={()=>void send('meeting.action-complete',{actionId:a.id},r)}>Mark done</button></div>)}{!r.data.actions.some(a=>!a.doneAt)&&<p>No unfinished follow-ups.</p>}
    <details><summary>Add follow-up</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await send('meeting.action',{title:f.get('title'),ownerId:f.get('ownerId'),due:dueValue(f,w.location.timezone)},r)}catch(err){setError(String(err))}}}><fieldset disabled={busy}><Fields><Field name="Next action"><input name="title" maxLength={300} required/></Field><Field name="Responsible person"><select name="ownerId">{[r.ownerId,r.data.managerId].map(id=><option key={id} value={id}>{personName(w,id)}</option>)}</select></Field><DueFields zone={w.location.timezone} at={now}/></Fields><button>Save follow-up</button></fieldset></form></details>
    <Field name="Meeting notes — shared with this meeting's other participant"><textarea maxLength={8000} value={notes} onChange={e=>setNotes(e.target.value)}/></Field><button className="shared-primary" disabled={busy||!notes.trim()} onClick={()=>void send('meeting.complete',{notes},r)}>Record meeting and schedule next</button>
    {r.ownerId===w.me.id&&<details><summary>Reschedule or change cadence</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await send('meeting.schedule',{due:dueValue(f,w.location.timezone),cadenceDays:Number(f.get('cadenceDays')),agenda:f.get('agenda'),note:f.get('note')},r)}catch(err){setError(String(err))}}}><fieldset disabled={busy}><Fields><DueFields zone={w.location.timezone} at={r.data.due??now}/><Field name="Repeat every (days)"><input name="cadenceDays" type="number" min={1} max={90} defaultValue={r.data.cadenceDays} required/></Field></Fields><Field name="Agenda"><textarea name="agenda" defaultValue={r.data.agenda} maxLength={4000}/></Field><Field name="Reason for change"><input name="note" maxLength={2000} required/></Field><button>Save schedule</button></fieldset></form></details>}
    {error&&<p role="alert">{error}</p>}<details><summary>Previous meetings ({r.data.sessions.length}) and completed actions</summary>{r.data.sessions.slice().reverse().map((s,i)=><div key={i}><h3>{displayTime(s.at,w.location.timezone)}</h3><p>{s.agenda}</p><p className="ops-preserve">{s.notes}</p></div>)}{r.data.actions.filter(a=>a.doneAt).map(a=><p key={a.id}>✓ {a.title} · {displayTime(a.doneAt,w.location.timezone)}</p>)}</details>
  </article>;
}
