'use client';
import {useState} from 'react';
import {positionAchievements} from '../shared/position-achievements';
import type {Workspace,WorkRecord} from '../shared/types';
import type {Send} from './workspace';
import './operational-growth.css';

const labels={opportunity:'Your next opportunity',ready:'Ready to record',earned:'Verified progress','review-needed':'Evidence needs review'};
export function PositionAchievements({w,send,busy=false,onOpen,compact=false,onMore,onlyId}:{w:Workspace;send?:Send;busy?:boolean;onOpen:(r:WorkRecord)=>void;compact?:boolean;onMore?:()=>void;onlyId?:string}){
 const [error,setError]=useState(''),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');
 if(w.me.scheduleOnly)return null;
 const cards=positionAchievements(w).filter(card=>!onlyId||card.recordId===onlyId),visible=compact?cards.slice(0,3):cards;
 const refresh=async()=>{if(!send||saving||busy)return;setSaving(true);setError('');setNotice('');try{if(await send('achievement.refresh',{}))setNotice('Progress checked against your saved work.');else setError('Progress was not confirmed. Try again when the workspace is ready.');}catch(e){setError(e instanceof Error?e.message:'Your progress could not be saved. Try again.');}finally{setSaving(false)}};
 return <section className="growth-panel" aria-label="Your position progress"><div className="compact-heading"><div><p className="day-eyebrow">{w.me.position} · {w.location.name}</p><h2>Your work, moving forward</h2></div>{send&&cards.some(card=>card.state==='ready')&&<button className="inline-action" disabled={busy||saving} onClick={()=>void refresh()}>{saving?'Recording…':'Record checked progress'}</button>}</div><p>Your own saved work shows what you have accomplished and what to practice next. Progress updates after saved reviews. Reporting a problem or a shortage is responsible work.</p>{error&&<p className="shared-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="growth-grid">{visible.map(card=>{const record=w.records.find(r=>r.id===card.recordId),earned=card.state==='earned';return <article className="growth-card" key={card.id}><span className="growth-status" data-state={card.state}>{labels[card.state]}</span><h3>{card.title}</h3><p>{card.description}</p>{card.target>0&&<><progress value={Math.min(card.progress,card.target)} max={card.target} aria-label={card.title+' saved evidence progress'}/><p>{card.progress} of {card.target} evidence checks{earned?' confirmed':''}</p></>}<p>{card.nextAction}</p>{card.earnedAt&&<p>{earned?'Recorded':'Previously recorded'} {new Date(card.earnedAt).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:w.location.timezone})}</p>}{record&&!onlyId&&<button className="inline-action" onClick={()=>onOpen(record)}>View progress record →</button>}<div className="growth-evidence"><p>{card.sourceRefs.length?card.sourceRefs.length+' saved source reference'+(card.sourceRefs.length===1?'':'s'):'No qualifying saved evidence yet.'}</p>{card.sourceRefs.map(ref=>{const proof=w.records.find(r=>r.id===ref.id);return <p key={ref.id+':'+ref.event}><span>{ref.event.replaceAll('-',' ')} · saved version {ref.revision}</span>{proof&&<> · <button className="inline-action" onClick={()=>onOpen(proof)}>Open evidence</button></>}</p>})}</div></article>})}</div>{!cards.length&&<p>Your position’s opportunities will appear when your manager has set up the work and review evidence.</p>}<p className="shared-muted">Progress stays with you in this restaurant. It does not change your pay, permissions, station clearance or trainer authority.</p>
 {compact&&onMore&&<button className="inline-action" onClick={onMore}>All your progress →</button>}</section>;
}
