'use client';
import {useEffect,useRef,useState} from 'react';
import type {FoodDataset} from '../shared/food-workflow-model';
import {object} from '../shared/validation';
import type {AdvisorRow,AdvisorReview} from '../shared/food-advisor-bridge';
type Approval={locationId:string;dataset:FoodDataset;requestId:string;recommendationId:string;sourceRevision:string;foodRevision:number;definitionRevision:number;confirmed:true};
const valid=(value:unknown):value is AdvisorReview=>{const data=object(value);return ['unavailable','needs-review','ready'].includes(String(data.status))&&typeof data.locationId==='string'&&(data.dataset==='demo'||data.dataset==='operating')&&typeof data.foodRevision==='number'&&Array.isArray(data.rows)&&data.rows.every(row=>{const r=object(row);return typeof r.id==='string'&&typeof r.title==='string'&&(typeof r.currentPar==='number'||r.currentPar===null)&&(typeof r.recommendedPar==='number'||r.recommendedPar===null)&&typeof r.unit==='string'&&(r.status==='ready'||r.status==='needs-review')&&Array.isArray(r.reasons)&&r.reasons.every(reason=>typeof reason==='string');});};
export function PrepAdvisor({locationId,dataset,apiRoot,disabled,onBusy,onUpdated}:{locationId:string;dataset:FoodDataset;apiRoot:string;disabled:boolean;onBusy:(value:boolean)=>void;onUpdated:()=>void}){
 const [epoch,setEpoch]=useState(0),[result,setResult]=useState<{key:string;review:AdvisorReview|null;error:string}|null>(null),[pending,setPending]=useState<Approval|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const flight=useRef(false),mounted=useRef(true),key=apiRoot+':'+locationId+':'+dataset+':'+epoch;
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;onBusy(false)}},[onBusy]);
 useEffect(()=>{const controller=new AbortController();void fetch(`${apiRoot}/food/advisor?${new URLSearchParams({locationId,dataset})}`,{signal:controller.signal,credentials:'same-origin',cache:'no-store'}).then(async response=>{const data:unknown=await response.json();if(!response.ok)throw new Error(typeof object(data).error==='string'?String(object(data).error):'Food prep advice could not be read.');if(!valid(data)||data.locationId!==locationId||data.dataset!==dataset)throw new Error('Refresh this restaurant’s Food prep advice.');return data;}).then(review=>{if(!controller.signal.aborted)setResult({key,review,error:''})}).catch(e=>{if(!controller.signal.aborted)setResult({key,review:null,error:e instanceof Error?e.message:'Food prep advice could not be read.'})});return()=>controller.abort();},[apiRoot,locationId,dataset,key]);
 const refresh=()=>{setError('');setEpoch(n=>n+1)},current=result?.key===key?result:null;
 async function approve(command:Approval){if(flight.current)return;flight.current=true;setSaving(true);onBusy(true);setError('');setNotice('');try{const response=await fetch(`${apiRoot}/food/advisor`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)}),data=object(await response.json());if(!mounted.current)return;if(!response.ok){if(response.status<500){setPending(null);onBusy(false);if(response.status===409||response.status===403){setEpoch(n=>n+1);setError(response.status===409?'The recommendation or its source changed. Review the refreshed advice before approving.':'Access changed. Review the refreshed restaurant view.');return;}}throw new Error(typeof data.error==='string'?data.error:'Approval could not be saved.');}if(typeof data.recordId!=='string'||typeof data.revision!=='number'||typeof data.foodRevision!=='number')throw new Error('Approval was not confirmed. Retry the same request.');setPending(null);onBusy(false);setNotice('Recommended par accepted. Review the resulting prep need before releasing work.');setEpoch(n=>n+1);onUpdated();}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Approval is not confirmed. Retry the same request.');}finally{flight.current=false;if(mounted.current)setSaving(false);}}
 const lock=disabled||saving||!!pending;
 return <section className="food-flow-panel"><h2>Food prep advice</h2><p>Jeff’s recommendations use Food history and planning inputs. Review the mapped target par here; a recommended par is not the amount to make. Existing count, release and assignment controls still determine the prep work.</p><button disabled={lock||!current} onClick={refresh}>Refresh Food advice</button>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}{pending&&!saving&&<><p>The last approval is not confirmed. Retry the same request before leaving this screen or restaurant.</p><button onClick={()=>void approve(pending)}>Retry same approval</button></>}{!current?<p role="status">Reading Food recommendations…</p>:current.error?<p role="alert">{current.error}</p>:current.review&&<PrepAdvisorReview review={current.review} disabled={lock} onApprove={row=>{const review=current.review!;if(lock||row.status!=='ready'||typeof row.definitionRevision!=='number'||!review.sourceRevision)return;const command:Approval={locationId,dataset,requestId:crypto.randomUUID(),recommendationId:row.id,sourceRevision:review.sourceRevision,foodRevision:review.foodRevision,definitionRevision:row.definitionRevision,confirmed:true};setPending(command);void approve(command);}}/>}</section>;
}
export function PrepAdvisorReview({review,disabled,onApprove}:{review:AdvisorReview;disabled:boolean;onApprove:(row:AdvisorRow)=>void}){
 if(review.status==='unavailable')return <p className="food-flow-note" role="status">{review.message||'Jeff’s Food recommendation connection is not available. Existing reviewed prep plans remain available.'}</p>;
 return <>{review.message&&<p className="food-flow-note">{review.message}</p>}{review.generatedAt&&<p>Recommendation snapshot: {new Date(review.generatedAt).toLocaleString()}</p>}{!review.rows.length&&<p>No pending mapped recommendations in this snapshot.</p>}{review.rows.map(row=><article className="food-flow-panel" key={row.id}><h3>{row.title}</h3><p>Current par: {row.currentPar??'Unknown'} {row.unit} → recommended par: {row.recommendedPar??'Unknown'} {row.unit}</p>{row.shelfLife&&<p>Recipe shelf life: {row.shelfLife}</p>}{row.reasoning&&<p>{row.reasoning}</p>}{row.reasons.map((reason,n)=><p key={n}>{reason}</p>)}{row.status==='needs-review'?<p>Source matching or units need review before this advice can be accepted.</p>:<button disabled={disabled||!review.sourceRevision||typeof row.definitionRevision!=='number'} onClick={()=>onApprove(row)}>Accept recommended par for {row.title}</button>}</article>)}</>;
}
