'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {buildOwnerHome,buildRoleHome,type RoleHomeAttention,type RoleHomeKind,type RoleHomeModel} from '../shared/role-home';
import {publicWorkspace} from '../shared/domain';
import type {WorkRecord} from '../shared/types';
import {WorkspaceIcon} from './workspace-icon';
import {createRoleReviewFixtures,roleReviewStores,type RoleReviewWorkspace,type RoleReviewStore,type RoleReviewPosition} from './role-home-fixture';
import './role-home.css';

export const roleHomeReviewPersonas:{id:RoleHomeKind;title:string;scope:string;icon:string}[]=[{id:'frontline',title:'Frontline',scope:'My position',icon:'Review'},{id:'department-manager',title:'Manager',scope:'My department',icon:'Team'},{id:'general-manager',title:'General manager',scope:'One restaurant',icon:'Home'},{id:'owner',title:'Owner',scope:'The whole group',icon:'Areas'}];
const freshnessNames={current:'Current date',historical:'Earlier date',stale:'Outdated evidence',changed:'Needs review',missing:'Missing',unavailable:'Unavailable',recorded:'Saved record'};
const displayDate=(at:string|null)=>at?new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(at)):'Not supplied';

export function roleReviewContext(now:string,role:RoleHomeKind,locationId:RoleReviewStore='berts',department='BOH',position:RoleReviewPosition='Dishwasher'){
 const sources=createRoleReviewFixtures(now),store=sources.find(w=>w.location.id===locationId)!;
 if(role==='owner')return {sources,active:store,model:buildOwnerHome(sources,new Date(now),roleReviewStores.map(s=>({locationId:s.id,locationName:s.name})))};
 const person=role==='frontline'?store.members.find(m=>m.position===position)!:role==='department-manager'?store.members.find(m=>m.id===`role-review-${locationId}-${department==='FOH'?'foh':'boh'}`)!:store.members.find(m=>m.id===`role-review-${locationId}-gm`)!;
 // GM uses its own fictional membership and explicit, bounded store permissions.
 // Changing this review selection never provisions or enables a real account.
 const active={...store,me:person},model=buildRoleHome(active,role,new Date(now));
 return {sources:[active],active,model};
}
export function resolveRoleReviewRecord(sources:RoleReviewWorkspace[],item:RoleHomeAttention):WorkRecord|null{
 const w=sources.find(s=>s.location.id===item.locationId);
 if(!w||w.roleHomeSource?.state!=='available'||!item.actionable||!item.recordId||!item.recordKind)return null;
 return publicWorkspace(w).records.find(r=>r.id===item.recordId&&r.kind===item.recordKind&&r.locationId===item.locationId)??null;
}
function SourceBadge({item}:{item:RoleHomeAttention}){return <span className="rh-source-badge" data-state={item.freshness.state}>{freshnessNames[item.freshness.state]}</span>;}
export function RoleHomeAttentionCard({item,onOpen,compact=false}:{item:RoleHomeAttention;onOpen?:(item:RoleHomeAttention)=>void;compact?:boolean}){
 return <article className={compact?'rh-attention rh-attention-compact':'rh-attention'} data-priority={item.priority} data-record-id={item.recordId??undefined} data-location-id={item.locationId}>
  <div className="rh-card-meta"><span>{item.locationName}{item.area?' · '+item.area:''}</span><SourceBadge item={item}/></div>
  <h3>{item.what}</h3><p className="rh-why">{item.why}</p>
  <dl className="rh-next"><div><dt>Responsible</dt><dd>{item.person}</dd></div><div><dt>Next step</dt><dd>{item.nextAction}</dd></div></dl>
  <div className="rh-card-bottom"><small>{item.source.label}{item.source.revision!==null?' · v'+item.source.revision:''}</small>{item.actionable&&item.recordId?<button onClick={()=>onOpen?.(item)}>Open sample record <span aria-hidden="true">↗</span></button>:<span className="rh-no-record">A source is needed</span>}</div>
 </article>;
}
export function RoleHomePanel({model,onOpen}:{model:RoleHomeModel;onOpen?:(item:RoleHomeAttention)=>void}){
 const remaining=model.attention.filter(i=>!model.priorities.some(p=>p.id===i.id));
 return <><section id="rh-priorities" className="rh-section"><div className="rh-section-heading"><div><span className="rh-kicker">Your starting point</span><h2>{model.role==='frontline'?'What matters for your work':'What needs attention first'}</h2></div><span className="rh-count">{model.priorities.length} shown</span></div>
  {model.priorities.length?<div className="rh-priority-grid">{model.priorities.map(item=><RoleHomeAttentionCard key={item.id} item={item} onOpen={onOpen}/>)}</div>:<div className="rh-empty">No attention items were supplied. Confirm the source coverage below before assessing the shift.</div>}
 </section>
 {remaining.length>0&&<section className="rh-section"><div className="rh-section-heading"><div><span className="rh-kicker">Keep the next step visible</span><h2>{model.role==='frontline'?'Your work and handoff':'Recorded work and source gaps'}</h2></div><span className="rh-count">{remaining.length} more</span></div><div className="rh-work-grid">{remaining.map(item=><RoleHomeAttentionCard compact key={item.id} item={item} onOpen={onOpen}/>)}</div></section>}</>;
}
function ReviewRecord({item,record,onClose}:{item:RoleHomeAttention;record:WorkRecord;onClose:()=>void}){
 const panel=useRef<HTMLElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;panel.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();if(event.key==='Tab'){const elements=panel.current?.querySelectorAll<HTMLButtonElement>('button');if(!elements?.length)return;const first=elements[0],last=elements[elements.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){event.preventDefault();last.focus();}else if(!event.shiftKey&&(document.activeElement===last||document.activeElement===panel.current)){event.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[onClose]);
 const data=record.data as unknown as {title?:string;detail?:string;body?:string;summary?:string;tomorrowNote?:string;position?:string;start?:string;end?:string;history?:{actorId:string;action:string;at:string;note:string}[]};
 return <div className="rh-dialog-backdrop" onClick={onClose}><section ref={panel} tabIndex={-1} className="rh-record-dialog" role="dialog" aria-modal="true" aria-labelledby="rh-record-title" onClick={event=>event.stopPropagation()}><div className="rh-dialog-heading"><div><span className="rh-kicker">Fictional saved record · read only</span><h2 id="rh-record-title">{item.what}</h2></div><button onClick={onClose} aria-label="Close sample record">×</button></div><p className="rh-record-scope">{item.locationName} · {record.area} · {item.source.label} · version {record.revision}</p><p>{data.detail??data.body??data.summary??(data.start&&data.end?`${data.position} · ${displayDate(data.start)} to ${displayDate(data.end)}`:item.why)}</p>{data.tomorrowNote&&<p><strong>Next shift:</strong> {data.tomorrowNote}</p>}<dl className="rh-record-details"><div><dt>Responsible</dt><dd>{item.person}</dd></div><div><dt>Recorded</dt><dd>{displayDate(record.updatedAt)}</dd></div><div><dt>Original record ID</dt><dd>{record.id}</dd></div><div><dt>Working screen</dt><dd>{item.tab}</dd></div></dl><p className="rh-source-explanation">{item.freshness.label}</p>{data.history?.length?<div className="rh-record-history"><h3>Retained history</h3>{data.history.map((event,index)=><p key={index}><strong>{event.action}</strong> · {displayDate(event.at)}<br/>{event.note}</p>)}</div>:null}<div className="rh-dialog-footer"><span>This review keeps the original record identity and makes no changes.</span><button onClick={onClose}>Back to home</button></div></section></div>;
}

export default function RoleHomesReview({now,initialRole='owner',initialLocation='berts',initialDepartment='BOH',initialPosition='Dishwasher'}:{now:string;initialRole?:RoleHomeKind;initialLocation?:RoleReviewStore;initialDepartment?:string;initialPosition?:RoleReviewPosition}){
 const [role,setRole]=useState<RoleHomeKind>(initialRole),[locationId,setLocationId]=useState<RoleReviewStore>(initialLocation),[department,setDepartment]=useState(initialDepartment),[position,setPosition]=useState<RoleReviewPosition>(initialPosition),[focusLocation,setFocusLocation]=useState<string|null>(null),[openItem,setOpenItem]=useState<RoleHomeAttention|null>(null);
 const context=useMemo(()=>roleReviewContext(now,role,locationId,department,position),[now,role,locationId,department,position]);
 const focus=role==='owner'&&focusLocation?context.sources.find(s=>s.location.id===focusLocation):undefined;
 const model=focus?buildRoleHome(focus,'owner',new Date(now)):context.model;
 const record=openItem?resolveRoleReviewRecord(context.sources,openItem):null;
 const mainRef=useRef<HTMLElement>(null),available=context.model.sources.filter(s=>s.state==='available').length;
 const persona=roleHomeReviewPersonas.find(p=>p.id===role)!;
 const relevantSources=focus?model.sources:context.model.sources;
 const urgent=model.attention.filter(i=>i.priority==='urgent').length,missing=model.attention.filter(i=>['missing','unavailable','changed','stale'].includes(i.freshness.state)).length;
 const changeRole=(value:RoleHomeKind)=>{setRole(value);setFocusLocation(null);setOpenItem(null);mainRef.current?.scrollTo({top:0});};
 const open=(item:RoleHomeAttention)=>{if(resolveRoleReviewRecord(context.sources,item))setOpenItem(item);};
 return <div className="rh-review" data-role={role}>
  <header className="rh-app-header"><a className="rh-brand" href="/team"><b>J</b><span>JMAX<small>RESTAURANT OPERATIONS</small></span></a><div className="rh-header-context"><strong>{role==='owner'?(focus?focus.location.name:'Three restaurants + commissary'):context.active.location.name}</strong><span>{persona.title} home{role==='department-manager'?' · '+department:role==='frontline'?' · '+position:''}</span></div><a className="rh-return" href="/team">Open working app <span aria-hidden="true">↗</span></a></header>
  <div className="rh-review-toolbar"><div><span className="rh-review-label">LOCAL ROLE REVIEW</span><span>Fictional personas and records</span></div><nav aria-label="Choose a fictional role home">{roleHomeReviewPersonas.map(p=><button key={p.id} aria-pressed={role===p.id} onClick={()=>changeRole(p.id)}><WorkspaceIcon name={p.icon} size={17}/><span>{p.title}</span></button>)}</nav></div>
  <div className="rh-app-body"><aside className="rh-rail"><div className="rh-rail-heading"><span>YOUR WORKSPACE</span><strong>{persona.scope}</strong></div><a className="rh-rail-home" href="#rh-top" onClick={()=>setFocusLocation(null)} aria-current={!focus?'page':undefined}><WorkspaceIcon name="Home" size={19}/>{role==='owner'?'Group overview':'My home'}</a>
   {role==='owner'?<div className="rh-rail-locations"><span>RESTAURANTS & PRODUCTION</span>{roleReviewStores.map(s=><button key={s.id} onClick={()=>{setFocusLocation(s.id);setOpenItem(null);mainRef.current?.scrollTo({top:0});}} aria-current={focusLocation===s.id?'page':undefined}><i data-location={s.id}>{s.short}</i><span>{s.name}<small>{s.type}</small></span><b aria-hidden="true">›</b></button>)}</div>:<div className="rh-scope-controls"><label>Review restaurant<select value={locationId} onChange={event=>{setLocationId(event.target.value as RoleReviewStore);setOpenItem(null);}}>{roleReviewStores.filter(s=>s.id!=='comm').map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>{role==='department-manager'&&<label>Department<select value={department} onChange={e=>{setDepartment(e.target.value);setOpenItem(null);}}><option value="BOH">Back of house</option><option value="FOH">Front of house</option></select></label>}{role==='frontline'&&<label>Position<select value={position} onChange={e=>{setPosition(e.target.value as RoleReviewPosition);setOpenItem(null);}}><option>Dishwasher</option><option>Cook</option><option>Server</option></select></label>}<p>{role==='general-manager'?'One restaurant, with front and back of house together.':role==='department-manager'?'The current department and its recorded responsibilities.':'Your published position, handoff and manager messages.'}</p></div>}
   <div className="rh-rail-footer"><a href="#rh-evidence"><WorkspaceIcon name="Log" size={17}/>Source coverage</a><a href="#rh-assumptions"><WorkspaceIcon name="Review" size={17}/>Review assumptions</a><small>Selections change this fictional review only.</small></div>
  </aside><main ref={mainRef} className="rh-main" id="rh-top"><div className="rh-page-heading"><div><p className="rh-kicker">Home / {persona.title}{focus?' / '+focus.location.name:''}</p><h1>{focus?focus.location.name+' in focus':model.title}</h1><p>{focus?'The same group records, focused on this location.':model.purpose}</p></div><div className="rh-snapshot"><span>Sample snapshot</span><strong>{displayDate(now)}</strong></div></div>
   {focus&&<button className="rh-back" onClick={()=>setFocusLocation(null)}>← Back to the whole group</button>}
   <div className="rh-scope-line"><WorkspaceIcon name={role==='owner'?'Areas':'Home'} size={17}/><strong>{focus?focus.location.name:role==='owner'?'Bert’s · Rudd’s · Papa Leone’s · Commissary':role==='general-manager'?context.active.location.name+' · FOH + BOH':role==='department-manager'?context.active.location.name+' · '+department:context.active.location.name+' · '+position}</strong><span>{model.scopeLabel}</span></div>
   <div className="rh-overview-strip" aria-label="Recorded sample overview"><div><strong>{urgent}</strong><span>marked urgent<small>In the supplied records</small></span></div><div><strong>{missing}</strong><span>source gaps<small>Need evidence or review</small></span></div><div><strong>{role==='owner'&&!focus?`${available} / ${context.model.sources.length}`:model.sources.filter(s=>s.state==='available').length}</strong><span>{role==='owner'&&!focus?'location sources available':'location source available'}<small>Availability is not readiness</small></span></div></div>
   <RoleHomePanel model={{...model,attention:model.priorities}} onOpen={open}/>
   {role==='owner'&&!focus&&<section className="rh-section rh-locations"><div className="rh-section-heading"><div><span className="rh-kicker">One group, four operating locations</span><h2>Restaurant and commissary view</h2></div></div><div className="rh-location-grid">{roleReviewStores.map(store=>{const source=context.model.sources.find(s=>s.locationId===store.id),items=context.model.attention.filter(i=>i.locationId===store.id),top=items.find(i=>i.recordId)??items[0];return <button key={store.id} data-location={store.id} onClick={()=>{setFocusLocation(store.id);mainRef.current?.scrollTo({top:0});}}><span className="rh-location-name"><i>{store.short}</i><strong>{store.name}<small>{store.type}</small></strong><b>↗</b></span><span className="rh-location-state" data-state={source?.state}>{source?.state==='available'?'Source supplied':source?.state==='missing'?'Source missing':source?.state==='stale'?'Source outdated':'Source unavailable'}</span><span className="rh-location-focus">{top?.what??'Review source coverage'}</span><small>{source?.state==='available'?`${items.filter(i=>i.recordId).length} saved items · ${items.filter(i=>!i.recordId).length} evidence gaps`:source?.label}</small></button>})}</div></section>}
   {role==='general-manager'&&<div className="rh-department-grid" aria-label="Both restaurant departments">{['FOH','BOH'].map(area=><section className="rh-department" key={area}><span className="rh-kicker">{area==='FOH'?'Front of house':'Back of house'}</span><h2>{area} at a glance</h2><p>{model.attention.filter(i=>i.area===area&&i.recordId).length} saved items · {model.attention.filter(i=>i.area===area&&!i.recordId).length} evidence gaps</p></section>)}</div>}
   {model.attention.length>model.priorities.length&&<section className="rh-section"><div className="rh-section-heading"><div><span className="rh-kicker">Carry the work forward</span><h2>{role==='frontline'?'Your work and handoff':'Recorded work and source gaps'}</h2></div></div><div className="rh-work-grid">{model.attention.filter(i=>!model.priorities.some(p=>p.id===i.id)).map(item=><RoleHomeAttentionCard compact key={item.id} item={item} onOpen={open}/>)}</div></section>}
   <section id="rh-evidence" className="rh-section rh-evidence"><div className="rh-section-heading"><div><span className="rh-kicker">Know what this view is built on</span><h2>Source coverage</h2></div><span className="rh-count">Saved work, not live feeds</span></div>{relevantSources.map(s=><div className="rh-evidence-row" key={s.locationId}><strong>{s.locationName}</strong><span data-state={s.state}>{s.state==='available'?'Available':s.state==='missing'?'Missing':s.state==='stale'?'Outdated':'Unavailable'}</span><p>{s.label}{s.asOf&&<><br/>Source as of {displayDate(s.asOf)}</>}</p></div>)}<p className="rh-evidence-note">Sales, labor cost and food-cost feeds are not supplied to this review. No financial totals or “all clear” result is inferred.</p></section>
   <details id="rh-assumptions" className="rh-assumptions"><summary>Working assumptions and review scope</summary><p>Every role should open a home that makes its work and responsibility clear. These examples use fictional records and the current app’s record visibility rules.</p><ul>{model.assumptions.map(note=><li key={note}>{note}</li>)}{role==='owner'&&<li>Owner review covers all three restaurants and the commissary, with a combined overview and separate location views.</li>}{role==='general-manager'&&<li>The GM example uses a distinct fictional account with {context.active.me.capabilities.join(', ')}. It can coordinate this restaurant’s FOH and BOH operating logs. Other workflows retain their own permissions; this does not provision a real GM account.</li>}<li>Live account provisioning and shared rollout remain unchanged.</li></ul></details>
  </main></div>{openItem&&record&&<ReviewRecord item={openItem} record={record} onClose={()=>setOpenItem(null)}/>}
 </div>;
}
