'use client';
import { useRef, useState, type ReactNode } from 'react';
import { shiftStationName } from '../shared/station-assignment';
import { personName, type RecordOf, type Workspace } from '../shared/types';
import { displayTime, localDate } from '../shared/local-time';
import { canPublish } from '../shared/schedule-policy';
import { attendanceForShift, attendanceTypes, canManageAttendance } from '../shared/attendance';
import { WorkspaceIcon } from './workspace-icon';

export type ScheduleView='day'|'people'|'mine';
export function scheduledDuration(minutes:number){const whole=Math.round(minutes),hours=Math.floor(whole/60),rest=whole%60;return `${hours.toLocaleString('en-US')}h${rest?' '+rest+'m':''}`;}
const minutes=(s:RecordOf<'shift'>)=>(Date.parse(s.data.end)-Date.parse(s.data.start))/60000;
const date=(day:string,options:Intl.DateTimeFormatOptions)=>new Date(day+'T12:00:00Z').toLocaleDateString('en-US',{...options,timeZone:'UTC'});
const clock=(value:string,zone:string)=>new Date(value).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:zone}).replace(':00','');
const departmentLabel=(area:string)=>area==='Executive'?'Management':area;
const departmentOrder=(area:string)=>area==='BOH'?0:area==='FOH'?1:2;
const jobTone=(job:string)=>/dish/i.test(job)?'dish':/cook|grill|fry|pizza|sandwich|flat top/i.test(job)?'cook':/host|busser|window|runner/i.test(job)?'host':/server/i.test(job)?'server':'other';

export function ScheduleBoard({w,now,days,onDayChange,shifts,selected,onSelect,onOpen,busy,onRequests,pendingRequests,weekNavigation,view:preferredView,onViewChange}:{w:Workspace;now:string;days:string[];onDayChange:(day:string)=>void;shifts:RecordOf<'shift'>[];selected:string[];onSelect:(shift:RecordOf<'shift'>,checked:boolean)=>void;onOpen:(shift:RecordOf<'shift'>)=>void;busy:boolean;onRequests:()=>void;pendingRequests:number;weekNavigation:ReactNode;view?:ScheduleView;onViewChange:(view:ScheduleView)=>void}){
 const boardRef=useRef<HTMLDivElement>(null);
 const today=localDate(now,w.location.timezone),manager=canManageAttendance(w.me)||w.me.capabilities.some(c=>['schedule.manage','schedule.publish','schedule.change'].includes(c));
 const [query,setQuery]=useState(''),[department,setDepartment]=useState('all'),[day,setDay]=useState(days.includes(today)?today:days[0]),[filtersOpen,setFiltersOpen]=useState(false);
 const view=manager?(preferredView??'people'):'mine';
 const top=()=>boardRef.current?.closest('main')?.scrollTo({top:0,left:0,behavior:'instant'});
 const changeView=(next:ScheduleView)=>{onViewChange(next);top()};
 const filtered=shifts.filter(s=>view==='mine'||!manager?s.ownerId===w.me.id&&s.data.published:((department==='all'||s.area===department)&&[personName(w,s.ownerId),s.data.position,shiftStationName(s)].join(' ').toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))).sort((a,b)=>a.data.start.localeCompare(b.data.start)||personName(w,a.ownerId).localeCompare(personName(w,b.ownerId)));
 const next=filtered.find(s=>!s.data.releasedAt&&Date.parse(s.data.end)>Date.parse(now));
 const people=[...new Set(filtered.map(s=>s.ownerId))].sort((a,b)=>personName(w,a).localeCompare(personName(w,b))),total=filtered.reduce((sum,s)=>sum+minutes(s),0);
 const forDay=filtered.filter(s=>localDate(s.data.start,w.location.timezone)===day),departments=[...new Set(shifts.map(s=>s.area))].sort((a,b)=>departmentOrder(a)-departmentOrder(b)||a.localeCompare(b));
 const personal=shifts.filter(s=>s.ownerId===w.me.id&&s.data.published),hasDrafts=filtered.some(s=>!s.data.published),activeFilters=!!query.trim()||department!=='all';
 const spanStart=forDay.length?Math.min(...forDay.map(s=>Date.parse(s.data.start))):0,spanEnd=forDay.length?Math.max(...forDay.map(s=>Date.parse(s.data.end))):0;
 const weekMinutes=(personId:string)=>shifts.filter(s=>s.ownerId===personId&&(view!=='mine'||s.data.published)).reduce((sum,s)=>sum+minutes(s),0);
 function shiftCard(s:RecordOf<'shift'>,showName=true){const overnight=localDate(s.data.end,w.location.timezone)!==localDate(s.data.start,w.location.timezone),weekly=weekMinutes(s.ownerId);return <div key={s.id} className="schedule-shift" data-area={s.area} data-job-tone={jobTone(s.data.position)} data-draft={!s.data.published}>
  {!s.data.published&&canPublish(w.me,s.area)&&<input type="checkbox" aria-label={'Select '+personName(w,s.ownerId)+' '+displayTime(s.data.start,w.location.timezone)} checked={selected.includes(s.id)} disabled={busy||!selected.includes(s.id)&&selected.length>=100} onChange={e=>onSelect(s,e.target.checked)}/>}
  <button disabled={busy} onClick={()=>onOpen(s)} aria-label={`${personName(w,s.ownerId)}, ${shiftStationName(s)}, ${displayTime(s.data.start,w.location.timezone)} to ${displayTime(s.data.end,w.location.timezone)}, ${s.data.published?'published':'draft'}`}>
   <span className="schedule-shift-main">{showName&&<strong>{personName(w,s.ownerId)}</strong>}<span className="schedule-shift-time">{clock(s.data.start,w.location.timezone)} – {clock(s.data.end,w.location.timezone)}{overnight&&<small>Next day</small>}</span><span className="schedule-shift-job"><span className="schedule-job-label">{shiftStationName(s)}</span>{s.data.stationId&&<span className="schedule-parent-job">{s.data.position}</span>}{!s.data.published&&<em>Draft</em>}</span>{attendanceForShift(w,s).filter(r=>r.data.status==='recorded').map(r=><small className="attendance-mark" key={r.id}>{attendanceTypes[r.data.type]}</small>)}</span>
   <span className="schedule-shift-length"><strong>{scheduledDuration(minutes(s))}</strong>{showName&&<small>{scheduledDuration(weekly)} week{shifts.some(other=>other.ownerId===s.ownerId&&!other.data.published)?' *':''}</small>}<span aria-hidden="true">›</span></span>
   {view==='day'&&spanEnd>spanStart&&<span className="schedule-timeband" aria-hidden="true"><i style={{left:`${100*(Date.parse(s.data.start)-spanStart)/(spanEnd-spanStart)}%`,width:`${100*(Date.parse(s.data.end)-Date.parse(s.data.start))/(spanEnd-spanStart)}%`}}/></span>}
  </button>
 </div>}
 return <div className="schedule-board" ref={boardRef}>
  <div className="schedule-board-controls">
   {weekNavigation}
   <div className="schedule-view-toggle" aria-label="Schedule views">{manager&&<><button aria-pressed={view==='people'} onClick={()=>changeView('people')}>Week</button><button aria-pressed={view==='day'} onClick={()=>changeView('day')}>Day</button></>}<button aria-pressed={view==='mine'} onClick={()=>changeView('mine')}>My schedule</button><button className="schedule-request-tab" onClick={onRequests}>Requests{pendingRequests>0&&<span className="schedule-count">{pendingRequests}</span>}</button></div>
   {view==='day'&&<div className="schedule-days" aria-label="Choose schedule day">{days.map(d=><button key={d} aria-label={date(d,{weekday:'long',month:'short',day:'numeric'})} aria-pressed={day===d} data-today={today===d} onClick={()=>{setDay(d);onDayChange(d);top()}}><span>{date(d,{weekday:'short'})}</span><strong>{date(d,{day:'numeric'})}</strong><i aria-hidden="true" data-scheduled={filtered.some(s=>localDate(s.data.start,w.location.timezone)===d)}/></button>)}</div>}
  </div>
  <div className="schedule-roster-summary"><p role="status"><strong>{scheduledDuration(total)}</strong> {view==='mine'?'this week':activeFilters?'filtered week':'team this week'}{view!=='mine'&&<span> · {people.length} people · {filtered.length} shifts</span>}{hasDrafts&&<span> · incl. drafts</span>}</p>{manager&&view!=='mine'&&<button aria-label="Search and filter roster" aria-expanded={filtersOpen} onClick={()=>setFiltersOpen(!filtersOpen)}><WorkspaceIcon name="Filter" size={18}/><span>{activeFilters?'Filtered':'Filter'}</span></button>}</div>
  {manager&&view!=='mine'&&filtersOpen&&<div className="schedule-board-filters"><label className="schedule-search"><span>Find a person or station</span><input type="search" placeholder="Name, job or station" value={query} onChange={e=>setQuery(e.target.value)}/></label><div><label><span>Department</span><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="all">All teams</option>{departments.map(area=><option key={area} value={area}>{departmentLabel(area)}</option>)}</select></label><label><span>Roster layout</span><select value={view} onChange={e=>changeView(e.target.value as ScheduleView)}><option value="day">By day</option><option value="people">By person</option></select></label></div>{activeFilters&&<button onClick={()=>{setQuery('');setDepartment('all')}}>Clear filters</button>}</div>}
  {view==='mine'?<div className="personal-agenda" key="mine"><h2 className="schedule-sr-only">My schedule</h2>{days.filter(d=>filtered.some(s=>localDate(s.data.start,w.location.timezone)===d)).map(d=><section key={d} className="personal-agenda-day" data-today={d===today}><div className="personal-date"><span>{date(d,{weekday:'short'})}</span><strong>{date(d,{day:'numeric'})}</strong><small>{date(d,{month:'short'})}</small></div><div>{filtered.filter(s=>localDate(s.data.start,w.location.timezone)===d).map(s=><div key={s.id}>{s.id===next?.id&&<p className="personal-next">{Date.parse(s.data.start)<=Date.parse(now)?'Scheduled now':'Next shift'}</p>}{shiftCard(s,false)}</div>)}</div></section>)}{!personal.length&&<div className="schedule-empty-state"><WorkspaceIcon name="Schedule" size={30}/><h2>No shifts this week</h2><p>Your published shifts will appear here.</p>{manager&&<button onClick={()=>changeView('day')}>View team roster</button>}</div>}</div>:view==='day'?<div className="schedule-agenda" key={day+department+query}>
   <div className="schedule-agenda-heading"><h2>{day===today?'Today':date(day,{weekday:'long'})}<small>{date(day,{month:'short',day:'numeric'})}</small></h2><span>{forDay.length} {forDay.length===1?'shift':'shifts'}<small>{scheduledDuration(forDay.reduce((sum,s)=>sum+minutes(s),0))}</small></span></div>
   {forDay.length>0&&<div className="schedule-timeband-key"><span>Shift times</span><span>{clock(new Date(spanStart).toISOString(),w.location.timezone)} – {clock(new Date(spanEnd).toISOString(),w.location.timezone)}{localDate(new Date(spanEnd).toISOString(),w.location.timezone)!==day?' · next day':''}</span></div>}
   {departments.filter(area=>forDay.some(s=>s.area===area)).map(area=><section className="schedule-department" key={area} aria-label={departmentLabel(area)+' roster'}><h3>{departmentLabel(area)}<span>{new Set(forDay.filter(s=>s.area===area).map(s=>s.ownerId)).size} on schedule</span></h3>{forDay.filter(s=>s.area===area).map(s=>shiftCard(s))}</section>)}
   {!forDay.length&&<div className="schedule-empty-state"><h3>{activeFilters?'No matching shifts':'No shifts on this day'}</h3><p>{activeFilters?'Try another name, station or department.':'Choose another day from the week above.'}</p>{activeFilters&&<button onClick={()=>{setQuery('');setDepartment('all')}}>Clear filters</button>}</div>}
  </div>:<div className="schedule-week-scroll" key={department+query} role="region" aria-label="Weekly schedule by person" tabIndex={0}>
   {people.length>0?<table className="schedule-week-grid"><caption className="schedule-sr-only">Weekly shifts by person. Select a shift to open its details.</caption><thead><tr><th scope="col" className="schedule-week-person-heading">People <small>{people.length} on this schedule</small></th>{days.map(d=>{const daily=filtered.filter(s=>localDate(s.data.start,w.location.timezone)===d);return <th scope="col" key={d} data-today={d===today}><span>{date(d,{weekday:'short'})}</span><strong>{date(d,{month:'short',day:'numeric'})}</strong><small>{daily.length} shifts · {scheduledDuration(daily.reduce((sum,s)=>sum+minutes(s),0))}</small></th>})}</tr></thead><tbody>{people.map(personId=>{const own=filtered.filter(s=>s.ownerId===personId);return <tr key={personId}><th scope="row"><span className="schedule-person-identity"><span className="schedule-person-initials" aria-hidden="true">{personName(w,personId).split(/\s+/).slice(0,2).map(n=>n[0]).join('')}</span><span><strong>{personName(w,personId)}</strong><small>{[...new Set(own.map(s=>departmentLabel(s.area)))].join(' / ')} · {scheduledDuration(own.reduce((sum,s)=>sum+minutes(s),0))}</small></span></span></th>{days.map(d=>{const daily=own.filter(s=>localDate(s.data.start,w.location.timezone)===d);return <td key={d} data-today={d===today}>{daily.length?daily.map(s=>shiftCard(s,false)):<span className="schedule-week-off">—<span className="schedule-sr-only"> No shift recorded</span></span>}</td>})}</tr>})}</tbody></table>:<p className="shared-empty">{shifts.length?'No people match these filters.':'No shifts for this week.'}</p>}
  </div>}
  {view==='people'&&<div className="schedule-grid-legend"><span><i data-tone="cook"/>Kitchen</span><span><i data-tone="server"/>Service</span><span><i data-tone="host"/>Support</span><span><i data-tone="dish"/>Dish</span><small>Open any shift for details. Use Day on a smaller screen.</small></div>}
  <small className="schedule-board-note">Scheduled hours before breaks.{view!=='mine'&&shifts.some(s=>!s.data.published)?' * Weekly totals include drafts.':''}</small>
 </div>;
}
