'use client';
import { canPlan, scheduleReview } from '../shared/schedule-review';
import { canPublish } from '../shared/schedule-policy';
import { displayTime, localClock, localDate, localInstant } from '../shared/local-time';
import { personName, manages, type RecordOf, type WorkRecord, type Workspace } from '../shared/types';
import type { Send } from './workspace';
import { closingPublicationIssues } from '../shared/publication';

export function ScheduleReadiness({w,start,selected,onOpen,onAdd,onCover}:{w:Workspace;start:string;selected?:string[];onOpen:(r:WorkRecord)=>void;onAdd:()=>void;onCover:(r:RecordOf<'staffing'>)=>void}) {
  if(!w.members.some(m=>canPlan(w.me,m.area)))return null;
  const review=scheduleReview(w,start,selected),zone=w.location.timezone;
  const closingIssues=w.records.filter((r):r is RecordOf<'shift'>=>r.kind==='shift'&&!r.data.cancelled&&!r.data.published&&canPlan(w.me,r.area)&&r.data.start<review.period.end&&r.data.end>review.period.start&&(!selected||selected.includes(r.id))).flatMap(s=>closingPublicationIssues(w,s));
  const drafts=w.records.filter((r):r is RecordOf<'staffing'>=>r.kind==='staffing'&&r.data.status==='draft'&&canPlan(w.me,r.area)&&r.data.start<review.period.end&&r.data.end>review.period.start);
  return <section aria-label="Coverage and workload review" className="schedule-readiness"><h2>Coverage & hours</h2><p>{selected?'Published shifts and the drafts selected for publication.':'Check coverage, availability and overlapping shifts.'}</p>
    <details><summary>Calendar-week hours by employee · {review.hours.length} people</summary><p>Hours inside {start} through {localDate(new Date(Date.parse(review.period.end)-1).toISOString(),zone)}, before breaks. Overnight hours outside these dates belong to the adjacent week; shift cards show each complete shift. These are planned hours, not worked time or an overtime calculation.</p><div className="schedule-table-wrap"><table><thead><tr><th>Employee</th><th>Published</th><th>{selected?'After selection':'With drafts'}</th></tr></thead><tbody>{review.hours.map(m=><tr key={m.personId}><th scope="row">{m.name}<details><summary>View {m.shifts.length} shifts</summary>{m.shifts.map(id=>{const r=w.records.find(r=>r.id===id);return r?.kind==='shift'?<button key={id} onClick={()=>onOpen(r)}>{displayTime(r.data.start,zone)} → {displayTime(r.data.end,zone)}</button>:null})}</details></th><td>{(m.publishedMinutes/60).toFixed(1)} h</td><td>{(m.plannedMinutes/60).toFixed(1)} h</td></tr>)}</tbody></table></div>{!review.hours.length&&<p>No scheduled hours in this period.</p>}</details>
    <h3>Approved staffing needs</h3>{!review.staffing.length?<p>No approved staffing needs cover these dates. Coverage has not been assessed.</p>:<><p>{review.publishedGapCount} uncovered time {review.publishedGapCount===1?'window':'windows'} in the published schedule · {review.plannedGapCount} with {selected?'this selection':'drafts'}.</p><p>Counts use employees approved for these scheduling jobs without conflicting shifts or approved availability. Only the approved stations and times below have been assessed.</p>{review.staffing.map(({record:r,published,planned})=><article key={r.id}><button onClick={()=>onOpen(r)}><strong>{r.data.title}</strong> · {r.data.minimum} {r.data.position} · {r.area}</button><p>{displayTime(r.data.start,zone)} → {displayTime(r.data.end,zone)}</p>{planned.length?<><ul>{planned.map((g,i)=><li key={i}>{displayTime(g.start,zone)} → {displayTime(g.end,zone)}: {g.scheduled} of {g.required} scheduled; {g.required-g.scheduled} more needed.</li>)}</ul>{manages(w.me,r.area,'schedule.manage')&&<button onClick={()=>onCover(r)}>Add a covering shift</button>}</>:<p>{published.length?'Covered in this preview; still short in the published schedule.':'The published schedule covers this staffing need.'}</p>}</article>)}</>}
    {!!review.issues.length&&<><h3>Assignments needing review</h3>{review.issues.map(({record:r,reason})=><p key={r.id}><button onClick={()=>onOpen(r)}>{personName(w,r.ownerId,'Inactive employee')} · {r.data.position}</button> {reason}</p>)}</>}
    {!!closingIssues.length&&<><h3>Closing setup before publication</h3>{closingIssues.map(({record:r,reason},i)=><p key={r.id+':'+i}><button onClick={()=>onOpen(r)}>{r.data.standard.title} · {displayTime(r.data.due,zone)}</button> {reason}</p>)}</>}
    {!!drafts.length&&<><h3>Staffing needs awaiting approval</h3>{drafts.map(r=><p key={r.id}><button onClick={()=>onOpen(r)}>{r.data.title} · {r.data.minimum} {r.data.position} · Draft</button></p>)}</>}
    {w.me.capabilities.includes('schedule.manage')&&<button onClick={onAdd}>Draft a staffing need</button>}
  </section>;
}

export function StaffingForm({w,day,record,send,onError}:{w:Workspace;day:string;record?:RecordOf<'staffing'>;send:Send;onError:(s:string)=>void}) {
  const p=record?.data,zone=w.location.timezone;
  return <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),v=(s:string)=>String(f.get(s)??'');try{await send('staffing.save',{title:v('title'),area:v('area'),position:v('position'),minimum:Number(v('minimum')),start:localInstant(v('startDate'),v('startTime'),zone,v('repeated')),end:localInstant(v('endDate'),v('endTime'),zone,v('repeated')),source:v('source'),note:v('note')},record)}catch(e){onError(e instanceof Error?e.message:'Check the staffing dates and times.')}}}>
    <p>Enter a specific station and time window. The publisher must approve it before it is used to assess coverage.</p>
    <label className="shared-field">Staffing need<input name="title" required maxLength={200} defaultValue={p?.title}/></label><div className="shared-grid"><label className="shared-field">Department<select name="area" defaultValue={record?.area??w.me.area}>{[...new Set(w.members.map(m=>m.area))].filter(a=>manages(w.me,a,'schedule.manage')).map(a=><option key={a}>{a}</option>)}</select></label><label className="shared-field">Station / position<input name="position" required maxLength={100} defaultValue={p?.position}/></label><label className="shared-field">People required<input name="minimum" type="number" required min={1} max={100} defaultValue={p?.minimum??1}/></label></div>
    <div className="shared-grid"><label className="shared-field">Start date<input type="date" name="startDate" required defaultValue={p?localDate(p.start,zone):day}/></label><label className="shared-field">Start time<input type="time" name="startTime" required defaultValue={p?localClock(p.start,zone):'16:00'}/></label><label className="shared-field">End date<input type="date" name="endDate" required defaultValue={p?localDate(p.end,zone):day}/></label><label className="shared-field">End time<input type="time" name="endTime" required defaultValue={p?localClock(p.end,zone):'23:00'}/></label></div>
    <details><summary>Clock-change hour</summary><label className="shared-field">If a time occurs twice<select name="repeated"><option value="">Choose only if the hour repeats</option><option value="earlier">First occurrence</option><option value="later">Second occurrence</option></select></label></details>
    <label className="shared-field">Source or operating reason<textarea name="source" required maxLength={2000} defaultValue={p?.source}/></label><label className="shared-field">Draft note<textarea name="note" maxLength={2000}/></label><button className="shared-primary">Save staffing draft</button>
  </form>;
}

export function StaffingDetail({w,record:r,send,onError}:{w:Workspace;record:RecordOf<'staffing'>;send:Send;onError:(s:string)=>void}) {
  const publisher=canPublish(w.me,r.area),drafter=manages(w.me,r.area,'schedule.manage'),zone=w.location.timezone;
  return <><p>{r.data.minimum} {r.data.position} · {r.area} · {r.data.status}</p><p>{displayTime(r.data.start,zone)} → {displayTime(r.data.end,zone)}</p><p>Source or operating reason: {r.data.source}</p>{r.data.status==='draft'&&drafter&&<details><summary>Edit staffing draft</summary><StaffingForm w={w} record={r} day={localDate(r.data.start,zone)} send={send} onError={onError}/></details>}
    {r.data.status!=='retired'&&(publisher||r.data.status==='draft'&&drafter)&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),action=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value');await send(action==='approve'?'staffing.approve':'staffing.retire',{confirmed:f.get('confirmed')==='on',note:String(f.get('note')??'')},r)}}><label className="shared-field">Staffing review reason<textarea name="note" required maxLength={2000}/></label>{publisher&&r.data.status==='draft'&&<label className="shared-check"><input type="checkbox" name="confirmed"/>I reviewed the headcount, station, times and source.</label>}<div className="shared-actions">{publisher&&r.data.status==='draft'&&<button value="approve" className="shared-primary">Approve staffing need</button>}<button value="retire">{r.data.status==='draft'?'Withdraw draft':'Retire staffing need'}</button></div></form>}
    <details><summary>Staffing history</summary><ol>{r.data.history.map((h,i)=><li key={i}>{h.action} · {personName(w,h.actorId,'Previous member')} · {displayTime(h.at,zone)}<p>{h.note}</p></li>)}</ol></details>
  </>;
}
