'use client';
import {useState} from 'react';
import {personName,type Workspace,type RecordOf} from '../shared/types';
import {contactInstant,contactCategories,contactOwner,contactReader,phoneLink,type ContactFacts} from '../shared/service-contacts';
import {displayTime,localDate} from '../shared/local-time';
import type {Send} from './workspace';
import './operations.css';
function Field({name,children}:{name:string;children:React.ReactNode}){return <label className="shared-field">{name}{children}</label>}
function ContactFields({d}:{d?:ContactFacts}){return <>
 <Field name="Business or service"><input name="title" defaultValue={d?.title} maxLength={200} required/></Field>
 <div className="ops-fields"><Field name="Service category"><select name="category" defaultValue={d?.category}>{contactCategories.map(v=><option key={v}>{v}</option>)}</select></Field><Field name="Contact name · optional"><input name="contactName" defaultValue={d?.contactName} maxLength={200}/></Field></div>
 <div className="ops-fields"><Field name="Regular phone"><input name="phone" type="tel" defaultValue={d?.phone} maxLength={60} required/></Field><Field name="After-hours phone · optional"><input name="afterHoursPhone" type="tel" defaultValue={d?.afterHoursPhone} maxLength={60}/></Field></div>
 <Field name="Availability and after-hours coverage"><textarea name="hours" defaultValue={d?.hours} maxLength={1000} required placeholder="State the verified hours or that availability is unknown."/></Field>
 <Field name="Calling instructions · optional"><textarea name="instructions" defaultValue={d?.instructions} maxLength={2000} placeholder="Extensions, equipment served and who to ask for."/></Field>
 <Field name="Checked source reference"><textarea name="sourceRef" defaultValue={d?.sourceRef} maxLength={2000} required placeholder="Vendor record, service agreement or confirmed contact. No account passwords."/></Field>
 <Field name="Source check or reason"><textarea name="note" maxLength={2000} required/></Field>
 <label><input name="checked" type="checkbox" required/> I checked these contact details for this restaurant against the stated source.</label>
 </>}
const fields=(f:FormData)=>({...Object.fromEntries(['title','category','contactName','phone','afterHoursPhone','hours','instructions','sourceRef','note'].map(k=>[k,f.get(k)])),checked:f.get('checked')==='on'});
function Facts({d,callable=false}:{d:ContactFacts;callable?:boolean}){return <><p>{d.category}{d.contactName?' · '+d.contactName:''}</p><p>Regular: {callable&&phoneLink(d.phone)?<a href={phoneLink(d.phone)!}>Call {d.phone}</a>:d.phone}</p>{d.afterHoursPhone&&<p>After hours: {callable&&phoneLink(d.afterHoursPhone)?<a href={phoneLink(d.afterHoursPhone)!}>Call {d.afterHoursPhone}</a>:d.afterHoursPhone}</p>}<p className="ops-preserve">{d.hours}</p>{d.instructions&&<p className="ops-preserve">{d.instructions}</p>}<details><summary>Contact source</summary><p className="ops-preserve">{d.sourceRef}</p></details></>}
export function ServiceContacts({w,send,busy,onHistory}:{w:Workspace;send:Send;busy:boolean;onHistory:()=>void}){
 const [creating,setCreating]=useState(false),[selected,setSelected]=useState<string|null>(null),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[retired,setRetired]=useState(false);
 const records=w.records.filter((r):r is RecordOf<'servicecontact'>=>r.kind==='servicecontact'&&contactReader(r,w.me)),chosen=records.find(r=>r.id===selected);
 const rows=records.filter(r=>(retired||r.data.status==='active')&&(category==='all'||r.data.category===category)&&[r.data.title,r.data.contactName,r.data.instructions].join(' ').toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>a.data.title.localeCompare(b.data.title));
 return <section className="ops-page"><div className="shared-heading"><div><p className="ops-eyebrow">{w.location.name} · Maintenance</p><h1>Who to call</h1></div>{contactOwner(w.me)&&<button disabled={busy} onClick={()=>{setCreating(!creating);setSelected(null)}}>{creating?'Cancel new contact':'Add checked contact'}</button>}</div>
 <p>Service contacts checked by a restaurant owner or administrator. A calling link opens your device’s dialer; JMAX cannot confirm that a call connected.</p>
 <p className="ops-callout">For urgent injury, theft, damage or service interruption, call the primary owner and then the other owner if unanswered. Take necessary immediate safety action. A service contact does not replace this escalation or authorize spending.</p>
 {creating&&<form className="ops-card" onSubmit={async e=>{e.preventDefault();if(await send('servicecontact.create',fields(new FormData(e.currentTarget))))setCreating(false)}}><h2>New checked contact</h2><fieldset disabled={busy}><ContactFields/><p><button className="shared-primary">Save checked contact</button></p></fieldset></form>}
 {chosen?<><button onClick={()=>setSelected(null)}>Back to contacts</button><ServiceContactCard key={chosen.id+':'+chosen.revision} r={chosen} w={w} send={send} busy={busy}/></>:<><div className="ops-fields"><Field name="Find contact"><input value={query} onChange={e=>setQuery(e.target.value)}/></Field><Field name="Filter service category"><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All services</option>{contactCategories.map(v=><option key={v}>{v}</option>)}</select></Field></div>{contactOwner(w.me)&&<label><input type="checkbox" checked={retired} onChange={e=>setRetired(e.target.checked)}/> Include retired contacts</label>}
 {!rows.length&&<p className="ops-empty">No matching checked contacts. An owner can add details from an existing verified source.</p>}{rows.map(r=><article className="ops-card" key={r.id}><div className="shared-heading"><h2>{r.data.title}</h2><span className="ops-badge">{r.data.status}</span></div><Facts d={r.data} callable={r.data.status==='active'}/><p>Checked {displayTime(r.data.verifiedAt,w.location.timezone)}</p><button disabled={busy} onClick={()=>{setCreating(false);setSelected(r.id)}}>Open {r.data.title}</button></article>)}<button onClick={onHistory}>Open work history</button></>}
 </section>;
}
export function ServiceContactCard({r,w,send,busy,readOnly=false}:{r:RecordOf<'servicecontact'>;w:Workspace;send:Send;busy:boolean;readOnly?:boolean}){
 const d=r.data;return <article className="ops-card"><h2>{d.title}</h2><p className="ops-badge">{d.status}{readOnly?' · Filed history':''}</p>{d.status==='retired'&&<p className="ops-callout">Retired contact — do not use these numbers. {d.retirementNote}</p>}<Facts d={d} callable={!readOnly&&d.status==='active'}/><p>Checked by {personName(w,d.verifiedBy)} · {displayTime(d.verifiedAt,w.location.timezone)}</p>
 {contactOwner(w.me)&&!readOnly&&<><details><summary>{d.status==='retired'?'Recheck and reactivate':'Update checked details'}</summary><form onSubmit={async e=>{e.preventDefault();await send('servicecontact.revise',fields(new FormData(e.currentTarget)),r)}}><fieldset disabled={busy}><ContactFields d={d}/><p><button className="shared-primary">Save rechecked details</button></p></fieldset></form></details>{d.status==='active'&&<details><summary>Retire contact</summary><form onSubmit={async e=>{e.preventDefault();await send('servicecontact.retire',{note:new FormData(e.currentTarget).get('note')},r)}}><fieldset disabled={busy}><Field name="Reason for retiring contact"><textarea name="note" maxLength={2000} required/></Field><button>Retire contact</button></fieldset></form></details>}</>}
 {d.internal&&<details><summary>Contact changes ({d.internal.history.length})</summary><ol>{d.internal.history.map((h,i)=><li key={i}>{h.action} · {personName(w,h.actorId)} · {displayTime(h.at,w.location.timezone)}<p>{h.note}</p></li>)}</ol>{d.internal.versions.map((v,i)=><details key={i}><summary>Previous details · {displayTime(v.verifiedAt,w.location.timezone)}</summary><p>{v.facts.title} · {v.reason}</p><Facts d={v.facts}/></details>)}</details>}
 </article>;
}
export function RepairContactLog({r,w,send,busy,now}:{r:RecordOf<'managerlog'>;w:Workspace;send:Send;busy:boolean;now:string}){
 const [selected,setSelected]=useState(''),[error,setError]=useState('');const contacts=w.records.filter((c):c is RecordOf<'servicecontact'>=>c.kind==='servicecontact'&&c.data.status==='active'&&contactReader(c,w.me)),contact=contacts.find(c=>c.id===selected);
 return <details><summary>Service calls ({r.data.contactAttempts?.length??0})</summary><p>Record what actually happened. A saved report does not dispatch a vendor, confirm delivery or resolve this repair.</p>
 {r.data.status!=='resolved'&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setError('');try{await send('managerlog.contact',{contactId:contact?.id,contactRevision:contact?.revision,route:f.get('route'),occurredAt:contactInstant(String(f.get('date')),String(f.get('time')),w.location.timezone,String(f.get('repeated')??'')),result:f.get('result'),note:f.get('note'),confirmed:f.get('confirmed')==='on'},r)}catch(err){setError(String(err))}}}><fieldset disabled={busy}>
 <Field name="Checked service contact"><select value={selected} onChange={e=>setSelected(e.target.value)} required><option value="">Choose contact</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.data.title}</option>)}</select></Field>{!contacts.length&&<p>No checked contacts are available. Ask an owner to add the verified details in Who to call.</p>}
 {contact&&<><Facts d={contact.data} callable/><Field name="Number actually called"><select name="route"><option value="regular">Regular · {contact.data.phone}</option>{contact.data.afterHoursPhone&&<option value="after-hours">After hours · {contact.data.afterHoursPhone}</option>}</select></Field>
 <div className="ops-fields"><Field name={`Call date · ${w.location.timezone}`}><input type="date" name="date" defaultValue={localDate(now,w.location.timezone)} required/></Field><Field name="Call time"><input type="time" name="time" step="1" required/></Field></div><Field name="Repeated clock-change hour · only if needed"><select name="repeated"><option value="">Not a repeated hour</option><option value="earlier">First occurrence</option><option value="later">Second occurrence</option></select></Field><Field name="What happened"><select name="result"><option value="no-answer">No answer</option><option value="left-message">Left a message</option><option value="spoke">Spoke with the contact</option></select></Field><Field name="Call outcome and next step"><textarea name="note" maxLength={3000} required/></Field><label><input name="confirmed" type="checkbox" required/> I am recording an actual call attempt and its outcome.</label><p><button className="shared-primary">Save call report</button></p></>}
 </fieldset></form>}{error&&<p role="alert">{error}</p>}
 {(r.data.contactAttempts??[]).slice().reverse().map((a,i)=><article className="ops-card" key={i}><h3>{a.contact.title} · {a.result.replaceAll('-',' ')}</h3><p>{a.contact.phone} · {a.contact.route} · {displayTime(a.occurredAt,w.location.timezone)}</p><p className="ops-preserve">{a.note}</p><p>Reported by {personName(w,a.by)} · saved {displayTime(a.recordedAt,w.location.timezone)}</p><small>Contact details retained from the checked directory at the time of this report.</small></article>)}
 </details>;
}
