'use client';
import { useLayoutEffect, useMemo, useRef, useState } from 'react';
import { canChangePublished } from '../shared/schedule-policy';
import { localClock, localDate } from '../shared/local-time';
import { selectableStations, stationAssignmentIssue, stationById } from '../shared/station-assignment';
import { schedulingJobs, shiftCandidateChecks, shiftPeriod, type ShiftTimeInput } from '../shared/shift-planning';
import { manages, type RecordOf, type Workspace } from '../shared/types';
import { scheduledDuration } from './schedule-board';
import type { Send } from './workspace';

export function ShiftEditor({w,day,shift,draftNeed,send,onError}:{w:Workspace;day:string;shift?:RecordOf<'shift'>;draftNeed?:RecordOf<'staffing'>;send:Send;onError:(message:string)=>void}) {
  const initial=shift?.data??draftNeed?.data,zone=w.location.timezone;
  const [step,setStep]=useState(0),[query,setQuery]=useState(''),[personId,setPersonId]=useState(shift?.ownerId??''),[position,setPosition]=useState(shift?.data.position??draftNeed?.data.position??''),[note,setNote]=useState(''),[error,setError]=useState('');
  const [stationId,setStationId]=useState(shift?.data.stationId??'');
  const [time,setTime]=useState<ShiftTimeInput>(()=>({date:initial?localDate(initial.start,zone):day,startTime:initial?localClock(initial.start,zone):'16:00',endTime:initial?localClock(initial.end,zone):'23:00',overnight:initial?localDate(initial.end,zone)!==localDate(initial.start,zone):false,startFold:'',endFold:''}));
  const editorRef=useRef<HTMLDivElement>(null);
  useLayoutEffect(()=>{editorRef.current?.closest('dialog')?.scrollTo({top:0,left:0,behavior:'instant'})},[step]);
  const period=useMemo(()=>{try{return {value:shiftPeriod(time,zone,shift),error:''}}catch(e){return {value:null,error:e instanceof Error?e.message:'Check the shift times.'}}},[time,zone,shift]);
  const candidates=useMemo(()=>w.members.filter(m=>m.locationId===w.location.id&&(shift?.data.published?canChangePublished(w,w.me,m.area,shift.data):manages(w.me,m.area,'schedule.manage'))&&(!draftNeed||m.area===draftNeed.area&&m.qualifications.includes(draftNeed.data.position))).map(m=>({member:m,check:period.value?shiftCandidateChecks(w,m,period.value,'',shift):{blocking:[],notices:[]}})).sort((a,b)=>a.member.name.localeCompare(b.member.name)),[w,shift,draftNeed,period]);
  const person=candidates.find(c=>c.member.id===personId)?.member,jobs=person?schedulingJobs(person):[];
  const check=person&&period.value?shiftCandidateChecks(w,person,period.value,position,shift):{blocking:[],notices:[]};
  const stations=person?selectableStations(w,person,position):[],station=stationById(w,stationId);
  const stationIssue=person?stationAssignmentIssue(w,person,position,stationId):'';if(stationIssue)check.blocking.push(stationIssue);
  const matches=candidates.filter(c=>(c.member.name+' '+c.member.position+' '+schedulingJobs(c.member).join(' ')).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
  const choose=(id:string)=>{const selected=candidates.find(c=>c.member.id===id)?.member;if(!selected)return;setPersonId(id);setStationId('');const choices=schedulingJobs(selected);setPosition(choices.includes(position)?position:choices.length===1?choices[0]:'');setError('')};
  const move=(next:number)=>{if(next>0&&!period.value){setError(period.error);return}if(next===2&&(!person||!position||!jobs.includes(position)||check.blocking.length)){setError(check.blocking[0]??'Choose an employee and one of their scheduling jobs.');return}setStep(next);setError('');onError('')};
  const when=period.value?new Date(period.value.start).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:zone}):'';
  const duration=period.value?scheduledDuration((Date.parse(period.value.end)-Date.parse(period.value.start))/60000):'';
  const update=<K extends keyof ShiftTimeInput>(key:K,value:ShiftTimeInput[K])=>{setTime(old=>({...old,[key]:value}));setError('')};
  return <div ref={editorRef} className="shift-editor">
    <div className="shift-editor-steps" aria-label="Shift setup steps">{['When','Who','Review'].map((label,i)=><button type="button" key={label} aria-current={step===i?'step':undefined} disabled={i>step&&(i===1?!period.value:!person||!position||!period.value||check.blocking.length>0)} onClick={()=>move(i)}><span>{i+1}</span>{label}</button>)}</div>
    {error&&<p role="alert" className="shared-error">{error}</p>}
    {step===0&&<><h3>When is the shift?</h3><label className="shared-field">Shift date<input type="date" value={time.date} onInput={e=>update('date',e.currentTarget.value)} onChange={e=>update('date',e.target.value)} required/></label><div className="shift-time-fields"><label className="shared-field">Starts<input type="time" value={time.startTime} onInput={e=>update('startTime',e.currentTarget.value)} onChange={e=>update('startTime',e.target.value)} required/></label><label className="shared-field">Ends<input type="time" value={time.endTime} onInput={e=>update('endTime',e.currentTarget.value)} onChange={e=>update('endTime',e.target.value)} required/></label></div><label className="shared-check"><input type="checkbox" checked={time.overnight} onChange={e=>update('overnight',e.target.checked)}/>Ends the next day</label><p className="shift-time-summary">{period.value?duration+' scheduled':period.error}</p><details><summary>If an hour repeats when clocks change</summary><label className="shared-field">Start occurrence<select value={time.startFold} onChange={e=>update('startFold',e.target.value)}><option value="">Keep saved time or choose if needed</option><option value="earlier">First occurrence</option><option value="later">Second occurrence</option></select></label><label className="shared-field">End occurrence<select value={time.endFold} onChange={e=>update('endFold',e.target.value)}><option value="">Keep saved time or choose if needed</option><option value="earlier">First occurrence</option><option value="later">Second occurrence</option></select></label></details><div className="shift-editor-footer"><button className="shared-primary" type="button" onClick={()=>move(1)}>Choose employee</button></div></>}
    {step===1&&<><p className="shift-time-summary">{when} · {duration}</p><h3>Who is working?</h3><label className="shared-field">Find employee<input type="search" value={query} placeholder="Search name or job…" onInput={e=>setQuery(e.currentTarget.value)} onChange={e=>setQuery(e.target.value)}/></label><div className="shift-employee-picker" aria-label="Employees for this shift">{matches.map(({member,check:result})=><button type="button" key={member.id} aria-pressed={personId===member.id} onClick={()=>choose(member.id)}><span><strong>{member.name}</strong><small>{member.position} · {member.area}</small><small className={result.blocking.length?'shift-conflict':result.notices.length?'shift-pending':''}>{result.blocking.join(' · ')||result.notices.join(' · ')||(schedulingJobs(member).length?'No recorded conflict':'No scheduling jobs assigned')}</small></span><span aria-hidden="true">{personId===member.id?'✓':'›'}</span></button>)}{!matches.length&&<p>No employees match this search and your scheduling access.</p>}</div>
      {person&&<div className="shift-job-choice"><p><strong>{person.name}</strong></p><label className="shared-field">Job for this shift<select value={jobs.includes(position)?position:''} onChange={e=>{setPosition(e.target.value);setStationId('')}}><option value="">Choose a scheduling job</option>{jobs.map(job=><option key={job}>{job}</option>)}</select></label>{!!position&&<label className="shared-field">Station for this shift<select value={stationId} onChange={e=>setStationId(e.target.value)}><option value="">Job only — no station selected</option>{stationId&&!stations.some(s=>s.id===stationId)&&<option value={stationId}>{station?.data.title??'Previous station'} — review eligibility</option>}{stations.map(s=><option key={s.id} value={s.id}>{s.data.title}</option>)}</select></label>}{!!position&&!stations.length&&<p>No configured stations match this employee and job. A manager can set them up in Team.</p>}{station&&<p>{station.data.setup?.standardIds.length??0} linked guides · {station.data.setup?.goals.length??0} station goals. Only approved guides reach employees; publishing proposes any goals they have not already received.</p>}{!jobs.length&&<p>This employee needs a scheduling job set up in Team before you can assign a shift.</p>}{check.blocking.length>0&&<ul className="shift-conflict">{check.blocking.map(c=><li key={c}>{c}</li>)}</ul>}{!check.blocking.length&&<p className="shared-muted">Checks use saved shifts, time off and availability. Confirm anything that has not been recorded.</p>}</div>}
      <div className="shift-editor-footer"><button type="button" onClick={()=>move(0)}>Back</button><button type="button" className="shared-primary" disabled={!person||!position||check.blocking.length>0} onClick={()=>move(2)}>Review shift</button></div></>}
    {step===2&&(!person||!period.value)&&<p role="alert">These shift details are no longer available. Go back to When or Who and review your selection.</p>}
    {step===2&&person&&period.value&&<form onSubmit={async e=>{e.preventDefault();if(check.blocking.length){setError(check.blocking.join('. '));return}try{await send('shift.save',{personId:person.id,position,stationId:stationId||null,...period.value,note},shift)}catch(e){onError(e instanceof Error?e.message:'Could not save this shift.')}}}>
      <h3>{shift?'Review shift change':'Review new shift'}</h3>{shift&&<details><summary>Previous shift</summary><p>{w.members.find(m=>m.id===shift.ownerId)?.name??'Employee'} · {shift.data.position}</p><p>{new Date(shift.data.start).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:zone})} – {new Date(shift.data.end).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:zone})}</p></details>}<div className="shift-review-card"><strong>{person.name}</strong><p>{position} · {person.area}</p>{station&&<p><strong>Station: {station.data.title}</strong></p>}<p>{when}</p><strong>{new Date(period.value.start).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:zone})} – {new Date(period.value.end).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:zone})}{time.overnight?' (next day)':''}</strong><p>{duration} scheduled</p></div>
      {check.blocking.length>0&&<p role="alert" className="shift-conflict">{check.blocking.join(' · ')}</p>}{check.notices.length>0&&<ul className="shift-pending">{check.notices.map(c=><li key={c}>{c}</li>)}</ul>}
      <label className="shared-field">{shift?.data.published?'Reason for this change':'Note (optional)'}<textarea value={note} onChange={e=>setNote(e.target.value)} required={!!shift?.data.published} maxLength={2000}/></label><p className="shared-muted">{shift?.data.published?'Saving updates this published shift and notifies the affected employees.':'This saves a draft. Employees see it after you publish the schedule.'}</p><div className="shift-editor-footer"><button type="button" onClick={()=>move(1)}>Back</button><button className="shared-primary" disabled={check.blocking.length>0||!jobs.includes(position)}>{shift?.data.published?'Save published change':shift?'Save draft change':'Save draft'}</button></div>
    </form>}
  </div>;
}
