'use client';
import {useState} from 'react';
import {personName,type Workspace,type RecordOf} from '../shared/types';
import {checkinPatterns,checkinReviewer,shiftExperiences,type ShiftExperience} from '../shared/shift-checkin';
import {displayTime} from '../shared/local-time';
import type {Send} from './workspace';
import './operations.css';
const labels:Record<ShiftExperience,string>={good:'Good',okay:'Okay',rough:'Rough'};
function Experience({value}:{value?:ShiftExperience}){return <label className="shared-field">How did the shift go?<select name="experience" defaultValue={value??''} required><option value="">Choose a response</option>{shiftExperiences.map(x=><option key={x} value={x}>{labels[x]}</option>)}</select></label>}
export function ShiftCheckins({w,send,busy,now,onHistory}:{w:Workspace;send:Send;busy:boolean;now:string;onHistory:()=>void}){
 const [person,setPerson]=useState<string|null>(null),[reviewing,setReviewing]=useState(false);
 const own=w.records.filter((r):r is RecordOf<'shiftcheckin'>=>r.kind==='shiftcheckin'&&r.locationId===w.location.id&&r.ownerId===w.me.id).sort((a,b)=>b.data.shift.end.localeCompare(a.data.shift.end));
 const shifts=w.records.filter((r):r is RecordOf<'shift'>=>r.kind==='shift'&&r.ownerId===w.me.id&&r.data.published&&!r.data.cancelled&&Date.parse(r.data.end)<=Date.parse(now)&&!own.some(c=>c.data.shiftId===r.id)).sort((a,b)=>b.data.end.localeCompare(a.data.end));
 const patterns=checkinPatterns(w),chosen=patterns.find(p=>p.personId===person),reviewer=checkinReviewer(w.me);
 const zone=w.location.timezone;
 return <section className="ops-page"><p className="ops-eyebrow">{w.location.name} · People</p><h1>Shift check-ins</h1><p>How did the shift go? Your response and optional note are shared with authorized restaurant owners and GM reviewers. Other employees and ordinary shift managers cannot see them.</p>
 <p className="ops-callout">This records your experience of a scheduled shift. It does not clock you out, change attendance, or replace a conversation when you need help.</p>
 <p>Older responses may be filed in Work history. The latest five for each employee and department stay here for the review count.</p><button disabled={busy} onClick={onHistory}>Open Work history</button>
 {reviewer&&<div className="ops-filters"><button disabled={busy} aria-pressed={!reviewing} onClick={()=>{setReviewing(false);setPerson(null)}}>My check-ins</button><button disabled={busy} aria-pressed={reviewing} onClick={()=>{setReviewing(true);setPerson(null)}}>GM review{patterns.some(p=>p.flagged)?' · Needs attention':''}</button></div>}
 {reviewing&&reviewer?<><h2>Latest five submitted check-ins</h2><p>Three rough responses out of five raises an on-screen flag. Each shift counts once, ordered by its recorded end time. Fewer than five responses are shown without a pattern flag. Missing check-ins are not treated as good or rough.</p>
 {chosen?<><button disabled={busy} onClick={()=>setPerson(null)}>Back to counts</button><h3>{chosen.name}: {chosen.rough} rough of {chosen.count}</h3>{chosen.latest.map(r=><CheckinCard key={r.id+':'+r.revision} r={r} w={w} send={send} busy={busy}/>)}</>:<>{!patterns.length&&<p>No submitted check-ins are available for your review scope.</p>}{patterns.map(p=><article key={p.personId} className="ops-card"><h3>{p.name}</h3><p>{p.rough} rough of {p.count}{p.count<5?' · Waiting for five submitted check-ins':''}</p>{p.flagged&&<p className="ops-badge">Needs a conversation</p>}<button disabled={busy} onClick={()=>setPerson(p.personId)}>Open {p.name} check-ins</button></article>)}</>}
 </>:<>{shifts.length?<form key={'new:'+own.length} className="ops-card" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),shift=shifts.find(s=>s.id===f.get('shiftId'));if(shift)await send('shiftcheckin.submit',{shiftId:shift.id,shiftRevision:shift.revision,experience:f.get('experience'),note:f.get('note'),shareConfirmed:f.get('shareConfirmed')==='on'})}}><h2>Check in after a shift</h2><fieldset disabled={busy}><label className="shared-field">Completed scheduled shift<select name="shiftId" required defaultValue=""><option value="">Choose shift</option>{shifts.map(s=><option key={s.id} value={s.id}>{displayTime(s.data.start,zone)} – {displayTime(s.data.end,zone)} · {s.data.position}</option>)}</select></label><Experience/><label className="shared-field">Optional shift note<textarea name="note" maxLength={2000}/></label><label className="ops-check"><input type="checkbox" name="shareConfirmed" required/>Share this response and note with this restaurant’s authorized owner / GM reviewers.</label><button className="shared-primary">Save my check-in</button></fieldset></form>:<p>No unchecked completed shifts are available. A published schedule entry is required; Toast remains the time clock.</p>}
 <h2>My submitted check-ins</h2>{!own.length&&<p>You have not submitted a check-in here.</p>}{own.map(r=><CheckinCard key={r.id+':'+r.revision} r={r} w={w} send={send} busy={busy}/>)}</>}
 </section>;
}
export function CheckinCard({r,w,send,busy,readOnly=false}:{r:RecordOf<'shiftcheckin'>;w:Workspace;send:Send;busy:boolean;readOnly?:boolean}){
 const d=r.data,zone=w.location.timezone;
 return <article className="ops-card"><h3>{labels[d.experience]} · {displayTime(d.shift.end,zone)}</h3><p>{d.shift.position} · {d.employeeName}</p>{d.note&&<p className="ops-preserve">{d.note}</p>}<p>Submitted {displayTime(d.submittedAt,zone)}</p>
 {!readOnly&&r.ownerId===w.me.id&&<details><summary>Correct my check-in</summary><p>Earlier responses and notes remain visible in this entry’s history.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await send('shiftcheckin.correct',{experience:f.get('experience'),note:f.get('note'),reason:f.get('reason')},r)}}><fieldset disabled={busy}><Experience value={d.experience}/><label className="shared-field">Optional shift note<textarea name="note" maxLength={2000} defaultValue={d.note}/></label><label className="shared-field">Correction reason<textarea name="reason" maxLength={2000} required/></label><button>Save corrected check-in</button></fieldset></form></details>}
 <details><summary>Check-in history ({d.history.length})</summary>{d.history.map((h,i)=><p key={i}>{displayTime(h.at,zone)} · {personName(w,h.actorId)} · {h.action}: {h.note}</p>)}{d.versions.map((v,i)=><div key={i}><h4>Before correction {i+1}: {labels[v.experience]}</h4><p className="ops-preserve">{v.note||'No optional note.'}</p><p>Reason: {v.reason}</p></div>)}</details></article>;
}
