'use client';
import {useState} from 'react';
import {personName,type Workspace,type RecordOf} from '../shared/types';
import {carriedIssues,previousShift,operationsManager} from '../shared/operations';
import {localDate,displayTime,nextDate} from '../shared/local-time';
import type {Send} from './workspace';

export function ShiftLog({w,send,busy,now,initialEntryId}:{w:Workspace;send:Send;busy:boolean;now:string;initialEntryId?:string}){
 const departments=['FOH','BOH','combined','production'].filter(area=>operationsManager(w.me,area));
 const initial=w.records.find((r):r is RecordOf<'shiftentry'>=>r.id===initialEntryId&&r.kind==='shiftentry'&&r.locationId===w.location.id);
 const [date,setDate]=useState(initial?.data.businessDate??localDate(now,w.location.timezone)),[department,setDepartment]=useState(initial?.area??(departments.includes('BOH')?'BOH':departments[0]??w.me.area)),[editing,setEditing]=useState<RecordOf<'shiftentry'>|'new'|null>(null),[focused,setFocused]=useState(initial?.id);
 const entries=w.records.filter((r):r is RecordOf<'shiftentry'>=>r.kind==='shiftentry'&&r.data.businessDate===date&&r.area===department&&(!focused||r.id===focused));
 const carried=carriedIssues(w,date,department),previous=previousShift(w,date,department);
 return <div>{focused&&<p className="ops-callout">Opened original summary {focused}. <button onClick={()=>setFocused(undefined)}>All summaries for this date</button></p>}<div className="shared-actions"><button onClick={()=>{setDate(nextDate(date,-1));setEditing(null);setFocused(undefined)}}>Previous day</button><button disabled={date>=localDate(now,w.location.timezone)} onClick={()=>{setDate(nextDate(date));setEditing(null);setFocused(undefined)}}>Next day</button><button onClick={()=>{setDate(localDate(now,w.location.timezone));setEditing(null);setFocused(undefined)}}>Today</button></div><div className="ops-fields"><label className="shared-field">Business date<input type="date" value={date} max={localDate(now,w.location.timezone)} onChange={e=>{setDate(e.target.value);setEditing(null);setFocused(undefined)}}/></label><label className="shared-field">Department<select value={department} onChange={e=>{setDepartment(e.target.value);setEditing(null);setFocused(undefined)}}>{departments.map(d=><option key={d}>{d}</option>)}</select></label></div>
 <article className="ops-card"><h2>At opening</h2>{previous&&<div className="ops-callout"><strong>Previous handoff · {previous.data.businessDate}</strong><p className="ops-preserve">{previous.data.tomorrowNote||'No next-shift note was entered.'}</p><small>Recorded readiness: {previous.data.readiness.replaceAll('-',' ')}</small></div>}<p>Issues left open before this business date remain visible, including across days without service.</p>{carried.length?<ul>{carried.map(r=><li key={r.id}><strong>{r.data.title}</strong> · {personName(w,r.ownerId)} · Current status: {r.data.status}</li>)}</ul>:<p>No carried issues are recorded for this department.</p>}<p className="shared-muted">No opening submission is invented. A missing summary means no record, not that the shift was ready.</p></article>
 <div className="shared-heading"><h2>Shift summaries</h2><button disabled={busy||!date} onClick={()=>setEditing('new')}>New shift summary</button></div>
 {editing&&<ShiftForm key={editing==='new'?date+department:editing.id+':'+editing.revision} w={w} date={date} department={department} r={editing==='new'?undefined:editing} send={send} busy={busy} onDone={()=>setEditing(null)}/>}
 {entries.map(r=><article className="ops-card" key={r.id} data-record-id={r.id}><div className="shared-heading"><h3>{r.data.shift} · {r.data.status}</h3><span className="ops-badge">{r.data.readiness.replaceAll('-',' ')}</span></div><p className="ops-preserve">{r.data.summary}</p>{r.data.tomorrowNote&&<p><strong>Next shift:</strong> {r.data.tomorrowNote}</p>}<p className="shared-muted">{personName(w,r.ownerId)} · {r.data.submittedAt?'Submitted '+displayTime(r.data.submittedAt,w.location.timezone):'Draft only'}</p><div className="shared-actions"><button disabled={busy} onClick={()=>setEditing(r)}>Edit {r.data.status==='submitted'?'with correction history':'draft'}</button>{r.data.status==='draft'&&<button disabled={busy} onClick={()=>void send('shiftentry.submit',{},r)}>Submit shift summary</button>}</div><details><summary>Related issues ({r.data.issueIds.length}) and corrections</summary><ul>{r.data.issueIds.map(id=><li key={id}>{w.records.find((x):x is RecordOf<'managerlog'>=>x.id===id&&x.kind==='managerlog')?.data.title??'Related issue retained in history'}</li>)}</ul>{r.data.versions.map((v,i)=><div key={i}><p>{displayTime(v.at,w.location.timezone)} · {personName(w,v.by)}</p><p>{v.summary}</p><p>{v.tomorrowNote}</p></div>)}<ol>{r.data.history.map((h,i)=><li key={i}>{h.action} · {h.note}</li>)}</ol></details></article>)}
 {!entries.length&&<p className="ops-empty">No {department} shift summary recorded for this date.</p>}
 </div>;
}
function ShiftForm({w,date,department,r,send,busy,onDone}:{w:Workspace;date:string;department:string;r?:RecordOf<'shiftentry'>;send:Send;busy:boolean;onDone:()=>void}){
 const issues=w.records.filter((x):x is RecordOf<'managerlog'>=>x.kind==='managerlog'&&x.area===department);
 return <form className="ops-card" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await send('shiftentry.save',{businessDate:date,department,shift:f.get('shift'),summary:f.get('summary'),tomorrowNote:f.get('tomorrowNote'),readiness:f.get('readiness'),issueIds:f.getAll('issues'),note:f.get('note')},r))onDone()}}><fieldset disabled={busy}><div className="ops-fields"><label className="shared-field">Shift<select name="shift" defaultValue={r?.data.shift??'closing'} disabled={!!r}><option value="opening">Opening</option><option value="closing">Closing</option><option value="production">Production</option></select></label><label className="shared-field">Readiness<select name="readiness" defaultValue={r?.data.readiness??'not-assessed'}><option value="not-assessed">Not assessed</option><option value="ready">Ready</option><option value="action-needed">Action needed</option></select></label></div><label className="shared-field">Shift summary<textarea name="summary" maxLength={6000} defaultValue={r?.data.summary??''} required/></label><label className="shared-field">Next shift note<textarea name="tomorrowNote" maxLength={4000} defaultValue={r?.data.tomorrowNote??''}/></label><details><summary>Link issues</summary>{issues.map(issue=><label className="ops-check" key={issue.id}><input type="checkbox" name="issues" value={issue.id} defaultChecked={r?.data.issueIds.includes(issue.id)}/>{issue.data.title}</label>)}</details>{r?.data.status==='submitted'&&<label className="shared-field">Reason for correction<input name="note" required maxLength={2000}/></label>}<div className="shared-actions"><button className="shared-primary">Save {r?.data.status==='submitted'?'correction':'draft'}</button><button type="button" onClick={onDone}>Cancel</button></div></fieldset></form>;
}
