'use client';
import { useState } from 'react';
import { canDraftStandard, type RecordOf, type Workspace } from '../shared/types';
import type { Send } from './workspace';
import type { SourceDocument, SourceLibraryIndex } from '../shared/source-library-types';

export function SourceLibraryReview({w,send,onOpen}:{w:Workspace;send:Send;onOpen:(r:RecordOf<'standard'>)=>void}) {
 const locationId=w.location.id;
 const linked=(sourceId:string)=>w.records.find((r):r is RecordOf<'standard'>=>r.kind==='standard'&&r.data.provenance?.sourceId===sourceId&&r.data.status!=='retired');
 const [library,setLibrary]=useState<SourceLibraryIndex|null>(null),[document,setDocument]=useState<SourceDocument|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [query,setQuery]=useState(''),[station,setStation]=useState('all'),[type,setType]=useState('all');
 const base='/api/source-library?locationId='+encodeURIComponent(locationId);
 async function load(documentId?:string){if(busy)return;setBusy(true);setError('');try{const response=await fetch(base+(documentId?'&documentId='+encodeURIComponent(documentId):''),{cache:'no-store'});const result=await response.json() as SourceLibraryIndex & {error?:string;document?:SourceDocument};if(!response.ok)throw Error(result.error??'Could not load the sources.');if(documentId){if(!result.document)throw Error('This source could not be read.');setDocument(result.document)}else setLibrary(result);}catch(e){setError(e instanceof Error?e.message:'Could not load the sources.')}finally{setBusy(false)}}
 const matches=library?.documents.filter(d=>(station==='all'||d.stations.includes(station))&&(type==='all'||d.documentType===type)&&(d.title+' '+d.roles.join(' ')+' '+d.assignment).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))??[];
 const title=(id:string)=>library?.documents.find(d=>d.id===id)?.title??'Related source';
 return <details className="source-library" onToggle={e=>{if(e.currentTarget.open&&!library&&!busy&&!error)void load()}}><summary>OneDrive source review</summary>
  <p>Owner review only. Sources become employee guidance through a separately approved training standard.</p>
  {error&&<p role="alert" className="shared-error">{error} <button disabled={busy} onClick={()=>void load()}>Try again</button></p>}
  {busy&&<p role="status">Loading source…</p>}
  {library&&<>{document?<>
   <button className="schedule-back" onClick={()=>setDocument(null)}>‹ Back to sources</button><h2>{document.title}</h2>
   <p className="source-status">Reference only · {document.sourceStatus==='draft'?'Draft':'Approval unverified'}</p>
   <dl className="source-facts"><div><dt>Restaurant</dt><dd>{document.locationName}</dd></div><div><dt>Department</dt><dd>{document.department}</dd></div><div><dt>Station / role</dt><dd>{document.assignment}</dd></div><div><dt>Document type</dt><dd>{document.documentType}</dd></div><div><dt>Use</dt><dd>{document.operationalUse.join(', ')}</dd></div><div><dt>Source owner</dt><dd>{document.sourceOwner??'Not yet identified'}</dd></div><div><dt>Last approved</dt><dd>{document.lastApprovedDate??'No approval date recorded'}</dd></div><div><dt>Approval evidence</dt><dd>{document.approvalEvidence??'Not yet verified'}</dd></div><div><dt>Replacement</dt><dd>{document.supersededBy?title(document.supersededBy):'No replacement confirmed'}</dd></div></dl>
   {document.conflicts.length>0&&<div className="source-issues"><h3>Resolve before approval</h3>{library.conflicts.filter(c=>document.conflicts.includes(c.id)).map(c=><article key={c.id}><strong>{c.title}</strong><p>{c.detail}</p></article>)}</div>}
   {document.duplicates.length>0&&<p><strong>Duplicate check:</strong> {document.duplicates.map(d=>title(d.id)+' — '+d.kind).join('; ')}. Both versions are retained.</p>}
   {document.relatedVersions.length>0&&<details><summary>Related versions and sources</summary><div className="source-related">{document.relatedVersions.map(id=><button key={id} disabled={busy} onClick={()=>void load(id)}>{title(id)}</button>)}</div></details>}
   {linked(document.id)?<button className="shared-primary" onClick={()=>onOpen(linked(document.id)!)}>Open linked {linked(document.id)!.data.status==='draft'?'draft':'guide'}</button>:canDraftStandard(w.me,document.department)&&document.roles.some(s=>s!=='Dishwasher')&&<details className="source-to-guide"><summary>Create a training draft</summary><p>Choose the role and topic. The original stays reference material; write and review the instructions before approval.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await send('standard.from-source',{sourceId:document.id,sourceHash:document.sha256,title:String(f.get('title')??''),area:String(f.get('area')??''),zone:String(f.get('zone')??''),position:String(f.get('position')??'')})}finally{setBusy(false)}}}>
   <label className="shared-field">Guide title<input name="title" required maxLength={200} defaultValue={document.title}/></label><label className="shared-field">Department<input name="area" required maxLength={100} defaultValue={document.department}/></label><label className="shared-field">Station / role<input name="position" list="source-guide-jobs" required maxLength={100} defaultValue={document.roles.length===1?document.roles[0]:''}/></label><datalist id="source-guide-jobs">{[...new Set(w.members.flatMap(m=>[m.position,...(m.scheduleJobs??[])]))].filter(s=>s!=='Dishwasher').sort().map(s=><option key={s} value={s}/>)}</datalist><label className="shared-field">Training topic / work area<input name="zone" required maxLength={100} defaultValue={document.stations.length===1?document.stations[0]:''}/></label><button className="shared-primary" disabled={busy}>Create draft</button></form></details>}
   <details><summary>Read source text</summary><p>Extracted from {document.filename}. This is historical source material, not an approved procedure.</p><div className="source-text" tabIndex={0}>{document.content}</div></details>
   <details><summary>Source record</summary><p>{document.sourcePath}</p><p>Captured {document.capturedAt}</p><p>Prepared by: {document.preparedBy??'Not established'}</p><p className="source-hash">File SHA-256: {document.sha256}</p></details>
  </>:<>
   <p><strong>{library.documents.length} sources</strong> · {library.conflicts.length} unresolved review topics · {w.records.filter(r=>r.kind==='standard'&&r.data.provenance?.intake&&r.data.status==='approved').length} approved linked guides</p>
   {library.conflicts.length>0&&<details className="source-issues"><summary>What needs a decision</summary>{library.conflicts.map(c=><article key={c.id}><strong>{c.title}</strong><p>{c.detail}</p><div className="source-related">{c.documentIds.map(id=><button key={id} disabled={busy} onClick={()=>void load(id)}>{title(id)}</button>)}</div></article>)}</details>}
   {library.documents.length>0&&<><div className="source-filters"><label><span className="schedule-sr-only">Find a source</span><input type="search" placeholder="Find a source…" value={query} onInput={e=>setQuery(e.currentTarget.value)} onChange={e=>setQuery(e.target.value)}/></label><label><span className="schedule-sr-only">Source station</span><select aria-label="Source station" value={station} onChange={e=>setStation(e.target.value)}><option value="all">All stations</option>{[...new Set(library.documents.flatMap(d=>d.stations))].sort().map(s=><option key={s}>{s}</option>)}</select></label><label><span className="schedule-sr-only">Source type</span><select aria-label="Source type" value={type} onChange={e=>setType(e.target.value)}><option value="all">All document types</option>{[...new Set(library.documents.map(d=>d.documentType))].sort().map(t=><option key={t}>{t}</option>)}</select></label></div>{(query.trim()||station!=='all'||type!=='all')&&<button onClick={()=>{setQuery('');setStation('all');setType('all')}}>Clear filters</button>}
   <div className="source-documents">{matches.map(d=><button key={d.id} disabled={busy} onClick={()=>void load(d.id)}><strong>{d.title}</strong><span>{d.department} · {d.documentType}</span><span>{d.assignment}</span><small>{linked(d.id)?'Linked '+(linked(d.id)!.data.status==='draft'?'draft':'approved guide'):'Reference only'}{d.conflicts.length?' · '+d.conflicts.length+' review topics':''}{d.duplicates.length?' · duplicate content':''}</small></button>)}</div>{!matches.length&&<p>No sources match these filters.</p>}</>}
   {!library.documents.length&&<p>No source batch has been reviewed for this restaurant.</p>}
  </>}</>}
 </details>;
}
