'use client';
import {useState} from 'react';
import {personName,type Workspace,type RecordOf} from '../shared/types';
import {ideaParticipant,ideaReader,ideaReviewer,ideaOwner,ideaOutcomeLabels} from '../shared/staff-ideas';
import {localDate,displayTime} from '../shared/local-time';
import type {Send} from './workspace';
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="shared-field">{label}{children}</label>}
export function StaffIdeas({initialRecordId,w,send,busy,now,onHistory}:{initialRecordId?:string;w:Workspace;send:Send;busy:boolean;now:string;onHistory:()=>void}){
 const [creating,setCreating]=useState(false),[selected,setSelected]=useState(initialRecordId??''),[filter,setFilter]=useState('all');
 if(!ideaParticipant(w.me))return null;
 const rows=w.records.filter((r):r is RecordOf<'staffidea'>=>r.kind==='staffidea'&&ideaReader(r,w.me)),r=rows.find(x=>x.id===selected),today=localDate(now,w.location.timezone);
 return <section className="ops-page"><div className="shared-heading"><div><p>{w.location.name} · Your department and restaurant</p><h1>Staff ideas</h1></div><button disabled={busy} onClick={()=>{setCreating(true);setSelected('')}}>Share an idea</button></div>
 <p>Your name and submission are visible to you, restaurant owners and authorized managers for your department. Coworkers do not see one another’s submissions. This is a named channel; anonymous submissions and rewards are not enabled.</p><p>Use the appropriate incident or urgent-contact route for an immediate safety concern. No email, text or push notification is sent by this page.</p>
 {creating?<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await send('staffidea.submit',{title:f.get('title'),idea:f.get('idea'),benefit:f.get('benefit'),shareConfirmed:f.get('shareConfirmed')==='on'}))setCreating(false)}}><fieldset disabled={busy}><Field label="Idea title"><input name="title" maxLength={200} required/></Field><Field label="Your idea"><textarea name="idea" maxLength={4000} required/></Field><Field label="Expected benefit · optional"><textarea name="benefit" maxLength={1500}/></Field><label><input name="shareConfirmed" type="checkbox" required/> Share my name and idea with the authorized reviewers described above.</label><p>Your original submission is retained. You can add a clarification afterward.</p><button>Submit idea</button><button type="button" onClick={()=>setCreating(false)}>Cancel</button></fieldset></form>:r?<><button onClick={()=>setSelected('')}>Back to ideas</button><StaffIdeaCard r={r} w={w} send={send} busy={busy} now={now}/></>:<><Field label="Show ideas"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Open</option><option value="closed">Closed follow-up</option><option value="mine">My submissions</option><option value="all">All accessible ideas</option></select></Field>{rows.filter(x=>filter==='all'||filter==='mine'&&x.ownerId===w.me.id||filter==='closed'&&x.data.status==='closed'||filter==='open'&&x.data.status!=='closed').sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(x=><article className="ops-card" key={x.id}><h2>{x.data.title}</h2><p>{x.data.employeeName} · {x.area} · {x.data.status}</p><p>{x.data.managerId?'Reviewer: '+personName(w,x.data.managerId):'Awaiting a reviewer'}{x.data.status!=='closed'&&x.data.dueDate?' · Follow-up '+x.data.dueDate+(x.data.dueDate<today?' · overdue':''):''}</p>{x.ownerId===w.me.id&&x.data.responses.at(-1)&&!x.data.responses.at(-1)?.readAt&&<p>Response awaiting your read receipt</p>}<button onClick={()=>setSelected(x.id)}>Open {x.data.title}</button></article>)}{!rows.length&&<p>No ideas are recorded in your accessible scope.</p>}<button onClick={onHistory}>Open work history</button></>}
 </section>;
}
export function StaffIdeaCard({r,w,send,busy,now,readOnly=false}:{r:RecordOf<'staffidea'>;w:Workspace;send:Send;busy:boolean;now:string;readOnly?:boolean}){
 const d=r.data,own=r.ownerId===w.me.id,owner=ideaOwner(w.me),reviewer=ideaReviewer(w.me,r.area)&&!own,today=localDate(now,w.location.timezone),current=w.members.find(m=>m.id===d.managerId&&m.id!==r.ownerId&&ideaReviewer(m,r.area)),last=d.responses.at(-1);
 const choices=w.members.filter(m=>m.id!==r.ownerId&&m.locationId===r.locationId&&ideaReviewer(m,r.area)&&(owner||m.id===w.me.id));
 const [outcome,setOutcome]=useState('');
 return <article className="ops-card"><h2>{d.title}</h2><p>{d.employeeName} · {r.area} · {displayTime(d.submittedAt,w.location.timezone)} · {d.status}{readOnly?' · Filed history':''}</p><p className="ops-preserve">{d.idea}</p>{d.benefit&&<p className="ops-preserve">Expected benefit: {d.benefit}</p>}
 <p>{d.managerId?'Assigned reviewer: '+personName(w,d.managerId):'Awaiting an independent reviewer'}{d.dueDate?' · Follow-up date: '+d.dueDate:''}{d.status!=='closed'&&d.dueDate&&d.dueDate<today?' · overdue':''}</p>{d.status==='reviewing'&&!current&&<p role="status">The assigned reviewer is no longer available for this department. A current reviewer or owner needs to reassign follow-up.</p>}
 {!readOnly&&reviewer&&d.status!=='closed'&&<details><summary>{d.managerId?'Reassign follow-up':'Assign follow-up'}</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await send('staffidea.assign',{managerId:f.get('managerId'),dueDate:f.get('dueDate'),note:f.get('note'),accepted:f.get('accepted')==='on'},r)}}><fieldset disabled={busy}><Field label="Responsible reviewer"><select name="managerId" required defaultValue=""><option value="">Choose current reviewer</option>{choices.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Follow-up date"><input name="dueDate" type="date" min={today} required/></Field><Field label="Assignment reason"><textarea name="note" maxLength={3000} required/></Field><label><input name="accepted" type="checkbox" required/> Record this reviewer and follow-up date.</label><button>Save responsibility</button></fieldset></form></details>}
 {!readOnly&&reviewer&&current?.id===w.me.id&&d.status==='reviewing'&&<details><summary>Respond to the idea</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await send('staffidea.respond',{outcome:f.get('outcome'),note:f.get('note'),evidence:f.get('evidence'),dueDate:f.get('dueDate'),confirmed:f.get('confirmed')==='on'},r))setOutcome('')}}><fieldset disabled={busy}><Field label="Response outcome"><select name="outcome" required value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="">Choose outcome</option>{Object.entries(ideaOutcomeLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><Field label="Response to the employee"><textarea name="note" maxLength={3000} required/></Field><Field label="Implementation evidence · required when reported implemented"><textarea name="evidence" maxLength={2000} required={outcome==='implemented'}/></Field>{outcome==='follow-up'&&<Field label="Next follow-up date"><input type="date" name="dueDate" min={today} required/></Field>}<p>Describe actual work and its limits. A recorded response does not approve a procedure, authorize spending or commit a reward.</p><label><input name="confirmed" type="checkbox" required/> This response accurately describes the decision or work and its limits.</label><button>Save response</button></fieldset></form></details>}
 <h3>Response history ({d.responses.length})</h3>{!d.responses.length&&<p>No reviewer response has been recorded.</p>}{d.responses.map(response=><section className="ops-card" key={response.id}><h4>{ideaOutcomeLabels[response.outcome]}</h4><p>{personName(w,response.by)} · {displayTime(response.at,w.location.timezone)}</p><p className="ops-preserve">{response.note}</p>{response.evidence&&<p className="ops-preserve">Evidence reference: {response.evidence}</p>}<p>{response.readAt?'Employee confirmed reading: '+displayTime(response.readAt,w.location.timezone):'Employee read receipt not recorded.'} Reading is not agreement or approval.</p>{!readOnly&&own&&last===response&&!response.readAt&&<button disabled={busy} onClick={()=>void send('staffidea.read',{responseId:response.id,confirmed:true},r)}>I have read this response</button>}</section>)}
 {!readOnly&&(own||owner||reviewer&&d.managerId===w.me.id)&&d.status!=='closed'&&<details><summary>Add clarification</summary><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;if(await send('staffidea.note',{note:new FormData(form).get('note')},r))form.reset()}}><fieldset disabled={busy}><Field label="Clarification"><textarea name="note" maxLength={3000} required/></Field><button>Save clarification</button></fieldset></form></details>}
 {!readOnly&&(own||owner)&&d.status==='closed'&&<details><summary>Reopen follow-up</summary><form onSubmit={async e=>{e.preventDefault();await send('staffidea.reopen',{note:new FormData(e.currentTarget).get('note')},r)}}><fieldset disabled={busy}><Field label="Reason for reopening"><textarea name="note" maxLength={3000} required/></Field><button>Reopen idea</button></fieldset></form></details>}
 <details><summary>Activity history ({d.history.length})</summary><ol>{d.history.map((h,i)=><li key={i}>{h.action} · {personName(w,h.actorId)} · {displayTime(h.at,w.location.timezone)}<p className="ops-preserve">{h.note}</p></li>)}</ol></details>
 </article>;
}
