'use client';
import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { has, manages, personName, type Workspace, type RecordOf, type Member } from '../shared/types';
import { activeStations, defaultStationLevels, stationProficiency, workforceReader } from '../shared/workforce';
import { displayTime } from '../shared/local-time';
import type { Send } from './workspace';
import { eligibleForStation } from '../shared/station-assignment';
import { StationSetupFields, emptyStationSetup } from './station-setup-fields';
import { canManageAttendance } from '../shared/attendance';

export function TeamWorkforce({w,send,busy,onAccess,onAttendance}:{w:Workspace;send:Send;busy:boolean;onAccess:()=>void;onAttendance:()=>void}) {
 const [stationEdit,setStationEdit]=useState<RecordOf<'station'>|null|undefined>();
 const [personId,setPersonId]=useState<string|null>(null),[assessing,setAssessing]=useState(false),[view,setView]=useState('people'),[query,setQuery]=useState('');
 const section=useRef<HTMLElement>(null);
 useLayoutEffect(()=>{section.current?.closest('main')?.scrollTo({top:0,left:0,behavior:'instant'})},[personId,view,stationEdit?.id,stationEdit===null]);
 const people=w.members.filter(m=>m.id===w.me.id||workforceReader(w.me,m.area)).sort((a,b)=>a.name.localeCompare(b.name));
 const person=people.find(m=>m.id===personId),stations=activeStations(w),canDefine=has(w.me,'people.manage'),search=query.trim().toLowerCase();
 const personStations=(m:Member)=>stations.filter(s=>s.area===m.area&&(eligibleForStation(w,m,s)||stationProficiency(w,m.id,s).record));
 const matchingPeople=people.filter(m=>!search||[m.name,m.position,m.area,...m.scheduleJobs??[],...personStations(m).map(s=>s.data.title)].join(' ').toLowerCase().includes(search));
 const matchingStations=stations.filter(s=>!search||[s.data.title,s.area,...s.data.setup?.jobs??[]].join(' ').toLowerCase().includes(search));
 if(stationEdit!==undefined)return <section ref={section} className="workforce-team"><button className="compact-back" onClick={()=>setStationEdit(undefined)}>‹ Back to stations</button><StationForm key={stationEdit?.id??'new'} w={w} record={stationEdit??undefined} send={send} busy={busy} onClose={()=>{setStationEdit(undefined);setView('stations')}}/></section>;
 if(person)return <section ref={section} className="workforce-team"><button className="compact-back" onClick={()=>{setPersonId(null);setAssessing(false)}}>‹ Back to team</button><div className="compact-heading"><div><h1>{person.name}</h1><p>{person.position} · {person.area}</p></div></div>
  {assessing?<ProficiencyForm key={person.id} w={w} person={person} send={send} busy={busy} onClose={()=>setAssessing(false)}/>:<>
   <dl className="person-facts"><div><dt>Scheduling jobs</dt><dd>{[...new Set([...person.scheduleJobs??[],...person.qualifications])].join(', ')||'None recorded'}</dd></div><div><dt>Available stations</dt><dd>{stations.filter(s=>eligibleForStation(w,person,s)).map(s=>s.data.title).join(', ')||'Not assigned yet'}</dd></div></dl>
   <div className="compact-heading"><h2>Station development</h2>{person.id!==w.me.id&&person.position!=='Dishwasher'&&manages(w.me,person.area,'people.manage')&&<button onClick={()=>setAssessing(true)}>Record proficiency</button>}</div>
   <div className="person-station-list">{personStations(person).map(s=>{const p=stationProficiency(w,person.id,s);return <div key={s.id}><strong>{s.data.title}</strong><span>{p.record&&!p.current?'Reassessment needed':p.level?.label??'Not assessed'}{p.current&&p.record?.data.certifiedTrainer?' · Certified trainer':''}</span>{p.current&&p.record&&<p>{p.record.data.evidence}</p>}</div>})}</div>
   {!personStations(person).length&&<p className="shared-muted">No station assessments yet.</p>}
   <details className="compact-note"><summary>Scheduling eligibility</summary><p>Available stations come from this person’s jobs and any manager restrictions. Training progress alone does not grant clearance.</p><p>Recorded clearance: {person.qualifications.join(', ')||'None recorded'}</p></details>
  </>}
 </section>;
 return <section ref={section} className="workforce-team"><div className="compact-heading"><h1>Team</h1>{view==='people'&&has(w.me,'location.manage')&&<button onClick={onAccess}>Employee access</button>}{view==='stations'&&canDefine&&<button onClick={()=>{setStationEdit(null)}}>Add station</button>}</div>
  <div className="compact-tabs" aria-label="Team views"><button aria-pressed={view==='people'} onClick={()=>{setView('people');setQuery('')}}>People <span>{people.length}</span></button><button aria-pressed={view==='stations'} onClick={()=>{setView('stations');setQuery('')}}>Stations <span>{stations.length}</span></button></div>
  {view==='people'&&canManageAttendance(w.me)&&<button className="inline-action" onClick={onAttendance}>Attendance history</button>}
  <label className="compact-search"><span className="schedule-sr-only">{view==='people'?'Find a person or station':'Find a station'}</span><input type="search" value={query} placeholder={view==='people'?'Search people or stations':'Search stations'} onChange={e=>setQuery(e.target.value)}/></label>
  <div className="compact-list">{view==='people'?matchingPeople.map(m=><button className="compact-row" key={m.id} onClick={()=>{setPersonId(m.id);setAssessing(false)}}><span><strong>{m.name}</strong><small>{m.position} · {m.area}</small></span><span className="compact-row-meta">{personStations(m).length?personStations(m).length+' stations':''}<span aria-hidden="true">›</span></span></button>):matchingStations.map(s=><details className="compact-station" key={s.id}><summary><span><strong>{s.data.title}</strong><small>{s.area} · {w.members.filter(m=>eligibleForStation(w,m,s)).length} eligible people</small></span><span aria-hidden="true">›</span></summary><div><p>{s.data.setup?.standardIds.length??0} {s.data.setup?.standardIds.length===1?'guide':'guides'} · {s.data.setup?.goals.length??0} {s.data.setup?.goals.length===1?'goal template':'goal templates'}</p>{s.data.levels.length>0&&<ol>{s.data.levels.map(l=><li key={l.value}><strong>{l.label}</strong> — {l.definition||'Definition not supplied yet'}</li>)}</ol>}<p>Independent-readiness threshold: {s.data.levels.find(l=>l.value===s.data.independentLevel)?.label??'Not defined'}</p>{manages(w.me,s.area,'people.manage')&&<button onClick={()=>setStationEdit(s)}>Manage station</button>}</div></details>)}</div>
  {!(view==='people'?matchingPeople.length:matchingStations.length)&&<p className="shared-empty">{search?'No matches.':view==='people'?'No people available.':'No stations defined yet.'}</p>}
  {view==='stations'&&canDefine&&<details className="compact-note"><summary>Archived stations</summary>{w.records.filter((r):r is RecordOf<'station'>=>r.kind==='station'&&r.data.status==='archived'&&manages(w.me,r.area,'people.manage')).map(s=><p key={s.id}>{s.data.title} · {s.area} <button onClick={()=>setStationEdit(s)}>Review or restore {s.data.title}</button></p>)}</details>}
 </section>;
}

function StationForm({w,record,send,busy,onClose}:{w:Workspace;record?:RecordOf<'station'>;send:Send;busy:boolean;onClose:()=>void}) {
  const stationForm=useRef<HTMLFormElement>(null);
  useEffect(()=>{stationForm.current?.scrollIntoView({block:'start',behavior:'instant'});},[]);
  const [levels,setLevels]=useState(record?.data.levels??[]),[threshold,setThreshold]=useState(record?.data.independentLevel?.toString()??'');
  const [area,setArea]=useState(record?.area??(w.members.find(m=>manages(w.me,m.area,'people.manage')&&m.position!=='Dishwasher'&&((m.scheduleJobs?.length??0)>0||m.qualifications.length>0))?.area??w.me.area)),[setup,setSetup]=useState(record?.data.setup??emptyStationSetup());
  const areas=[...new Set(w.members.filter(m=>manages(w.me,m.area,'people.manage')).map(m=>m.area))];
  return <form ref={stationForm} className="workforce-form" aria-label="Station definition" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await send('station.save',{title:f.get('title'),area,setup,levels,independentLevel:threshold?Number(threshold):null,status:f.get('status'),note:f.get('note')},record))onClose()}}><fieldset disabled={busy}><h2>{record?'Manage station':'Define a station'}</h2><p>Name the work area, choose its scheduling jobs and people, then connect its training. Proficiency levels can be defined separately below.</p><div className="shared-grid"><label>Station name<input name="title" required maxLength={100} defaultValue={record?.data.title??''} readOnly={!!record} list="workforce-station-names"/></label><datalist id="workforce-station-names">{[...new Set(w.members.flatMap(m=>m.qualifications))].map(name=><option key={name} value={name}/>)}</datalist><label>Department<select name="area" value={area} onChange={e=>{setArea(e.target.value);setSetup(emptyStationSetup())}}>{(record?[record.area]:areas).map(area=><option key={area}>{area}</option>)}</select></label></div>
    <StationSetupFields w={w} area={area} value={setup} onChange={setSetup}/><details><summary>Proficiency levels (optional)</summary>{!levels.length&&<button type="button" onClick={()=>setLevels(defaultStationLevels())}>Define proficiency levels</button>}
    {levels.map((l,i)=><div className="shared-grid" key={i}><label>Level {i+1} label<input aria-label={`Level ${i+1} label`} value={l.label} required maxLength={80} onChange={e=>setLevels(levels.map((v,n)=>n===i?{...v,label:e.target.value}:v))}/></label><label>Level {i+1} definition<textarea aria-label={`Level ${i+1} definition`} rows={2} value={l.definition} maxLength={500} onChange={e=>setLevels(levels.map((v,n)=>n===i?{...v,definition:e.target.value}:v))}/></label></div>)}
    <div className="shared-actions"><button type="button" disabled={!levels.length||levels.length>=10} onClick={()=>setLevels([...levels,{value:levels.length+1,label:`Level ${levels.length+1}`,definition:''}])}>Add level</button><button type="button" disabled={levels.length<=2} onClick={()=>{if(Number(threshold)===levels.length)setThreshold('');setLevels(levels.slice(0,-1))}}>Remove last level</button></div>
    <label>Independent-readiness threshold<select value={threshold} onChange={e=>setThreshold(e.target.value)}><option value="">Not defined yet</option>{levels.map(l=><option key={l.value} value={l.value}>{l.label}</option>)}</select></label><p className="shared-muted">Optional. This identifies a defined level to consider when reviewing shift composition. It does not grant station clearance.</p>
    </details><label>Station status<select name="status" defaultValue={record?.data.status??'active'}><option value="active">Active</option><option value="archived">Archived — retain history</option></select></label><label>Reason for this definition<textarea name="note" required maxLength={2000}/></label>{record&&<p>Changing proficiency levels or station status requires reassessment. Updating the employee list, guides or goals preserves existing assessments.</p>}<div className="shared-actions"><button className="shared-primary" type="submit">Save station</button><button type="button" onClick={onClose}>Cancel</button></div></fieldset></form>;
}
function ProficiencyForm({w,person,send,busy,onClose}:{w:Workspace;person:Member;send:Send;busy:boolean;onClose:()=>void}) {
  const formRef=useRef<HTMLFormElement>(null);
  useEffect(()=>{formRef.current?.scrollIntoView({block:'start',behavior:'instant'});formRef.current?.querySelector('select')?.focus({preventScroll:true});},[]);
  const stations=activeStations(w).filter(s=>s.area===person.area),[stationId,setStationId]=useState(stations[0]?.id??'');
  const station=stations.find(s=>s.id===stationId),profile=station?stationProficiency(w,person.id,station):null;
  return <form ref={formRef} className="workforce-form" aria-label="Record employee proficiency" onSubmit={async e=>{e.preventDefault();if(!station)return;const f=new FormData(e.currentTarget);if(await send('proficiency.save',{personId:person.id,stationId:station.id,stationRevision:station.revision,level:f.get('level')?Number(f.get('level')):null,certifiedTrainer:f.get('trainer')==='yes',evidence:f.get('evidence')},profile?.record))onClose()}}><fieldset disabled={busy}><h2>{person.name} · station development</h2><label>Station<select value={stationId} required onChange={e=>setStationId(e.target.value)}>{stations.map(s=><option key={s.id} value={s.id}>{s.data.title}</option>)}</select></label>{!station?<p>Define a station for {person.area} first.</p>:<div key={station.id+':'+station.revision+':'+profile?.record?.revision}><label>Recorded proficiency<select name="level" defaultValue={profile?.current?profile.record?.data.level?.toString()??'':''}><option value="">Not assessed yet</option>{station.data.levels.map(l=><option key={l.value} value={l.value}>{l.label} {l.definition?`— ${l.definition}`:''}</option>)}</select></label><label>Certified trainer<select name="trainer" required defaultValue={profile?.current?(profile.record?.data.certifiedTrainer?'yes':'no'):''}><option value="" disabled>Choose explicitly</option><option value="no">No</option><option value="yes">Yes — manager confirmed</option></select></label><label>Assessment evidence and next learning step<textarea name="evidence" required maxLength={2000} defaultValue={profile?.record?.data.evidence??''}/></label>{profile?.record&&!profile.current&&<p>The station definition changed. Make a fresh assessment; the old value has not been converted.</p>}<p>This assessment is visible to the employee and authorized workforce leaders. Current recorded proficiency can inform JMAX scheduling and training guidance. Legacy private review scores stay separate.</p><div className="shared-actions"><button className="shared-primary" type="submit">Save proficiency</button><button type="button" onClick={onClose}>Cancel</button></div></div>}</fieldset></form>;
}
export function ProficiencyDetail({w,record}:{w:Workspace;record:RecordOf<'proficiency'>}) {
  const station=activeStations(w).find(s=>s.id===record.data.stationId),profile=station?stationProficiency(w,record.ownerId,station):null;
  return <section><h3>{record.data.title}</h3><p>{profile?.current?profile.level?.label??'Not assessed yet':'Station definition changed or archived; reassessment needed'}</p><p>Certified trainer: {profile?.current?(record.data.certifiedTrainer?'Yes':'No'):'Needs review'}</p><p>{record.data.evidence}</p><p>Recorded {displayTime(record.data.assessedAt,w.location.timezone)} by {personName(w,record.data.history.at(-1)?.actorId)}</p><p>Station clearance is reviewed separately in employee setup.</p><details><summary>Assessment history</summary>{record.data.history.map((h,i)=><p key={i}>{displayTime(h.at,w.location.timezone)} · {personName(w,h.actorId)} · {h.note}</p>)}</details></section>;
}
