'use client';
import { schedulingNoticeText } from '../shared/message-display';
import { useState, type ReactNode } from 'react';
import { canDraftStandard, personName, has, manages, type Workspace, type WorkRecord, type RecordOf, type Line } from '../shared/types';
import { canPublish, canChangePublished } from '../shared/schedule-policy';
import { displayTime, localClock, localDate, localInstant } from '../shared/local-time';
import { requestStatus, requestTitle } from '../shared/schedule-requests';
import {TimeOffReview} from './time-off-review';
import {OperationalLearningCard} from './operational-learning';
import {PositionAchievements} from './position-achievements';
import type { Send } from './workspace';
import { FollowForm, FollowDetail, type FollowKind } from './followthrough-forms';
import { MessageComposer, MessageAttachment } from './message-composer';
import { CoverageDetail, OfferShift } from './shift-coverage';
import { StaffingDetail, StaffingForm } from './schedule-readiness';
import { StandardEditor } from './standard-editor';
import { SourceReview } from './standard-sources';
import { SourceGuideDetail } from './source-guide-detail';
import { StationGuideContent } from './station-knowledge';
import { ShiftShortcuts } from './shift-shortcuts';
import { ShiftEditor } from './shift-editor';
import { scheduledDuration } from './schedule-board';
import { AttendanceDetail, ShiftAttendance } from './attendance';
import { shiftStationName } from '../shared/station-assignment';
import { assignedStandardCurrent } from '../shared/station-knowledge';
import { correctionPerformer, eligibleCorrectionHelper } from '../shared/close-correction';
import { CorrectionAssignment } from './close-correction';
import { ProficiencyDetail } from './team-workforce';
import { CloseAttention } from './close-attention';
import { attentionReasons, needsCloseAcknowledgment } from '../shared/close-attention';
import {guidesForShift} from '../shared/shift-learning';
import {closingStatus} from '../shared/closing-status';
import {canManageClosing} from '../shared/closing-access';
export type FormKind='shift'|'time-off'|'availability'|'message'|'order'|'standard'|'leadership'|'close'|'swap'|'staffing'|FollowKind;
type Props={w:Workspace;send:Send;onError:(message:string)=>void};
const value=(f:FormData,name:string)=>String(f.get(name)??'');
const minutes=(clock:string)=>{const [h,m]=clock.split(':').map(Number);return h*60+m};
const clock=(minute:number)=>`${String(Math.floor(minute/60)).padStart(2,'0')}:${String(minute%60).padStart(2,'0')}`;
function Field({label,children}:{label:string;children:ReactNode}){return <label className="shared-field">{label}{children}</label>}
function Form({children,submit,onError}:{children:ReactNode;submit:(data:FormData,action:string)=>Promise<unknown>;onError:Props['onError']}) {
  return <form onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget),action=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')??'';try{await submit(data,action)}catch(error){onError(error instanceof Error?error.message:'Please check the form.')}}}>{children}</form>;
}
function Note({label='Note',required=true,initial=''}:{label?:string;required?:boolean;initial?:string}) {return <Field label={label}><textarea name="note" required={required} maxLength={2000} defaultValue={initial}/></Field>}
function ClockChange(){return <details><summary>Clock-change hour</summary><Field label="If a time occurs twice"><select name="repeated"><option value="">Choose only if the hour repeats</option><option value="earlier">First occurrence</option><option value="later">Second occurrence</option></select></Field></details>}
function People({w,name='personId',current,filter}:{w:Workspace;name?:string;current?:string;filter?:(m:Workspace['me'])=>boolean}) {return <select name={name} defaultValue={current??''} required><option value="">Choose a person</option>{w.members.filter(filter??(()=>true)).map(m=><option key={m.id} value={m.id}>{m.name} · {m.position}</option>)}</select>}
function Period({day,zone,record,initial}:{day:string;zone:string;record?:WorkRecord;initial?:{start:string;end:string}}) {
  const p=record?.kind==='shift'?record.data:initial??null;
  return <><div className="shared-grid"><Field label="Start date"><input type="date" name="startDate" defaultValue={p?localDate(p.start,zone):day} required/></Field><Field label="Start time"><input type="time" name="startTime" defaultValue={p?localClock(p.start,zone):'16:00'} required/></Field><Field label="End date"><input type="date" name="endDate" defaultValue={p?localDate(p.end,zone):day} required/></Field><Field label="End time"><input type="time" name="endTime" defaultValue={p?localClock(p.end,zone):'23:00'} required/></Field></div><details><summary>Clock-change hour</summary><Field label="If a time occurs twice"><select name="repeated"><option value="">Choose only if the hour repeats</option><option value="earlier">First occurrence</option><option value="later">Second occurrence</option></select></Field></details></>;
}
function period(f:FormData,zone:string){return {start:localInstant(value(f,'startDate'),value(f,'startTime'),zone,value(f,'repeated')),end:localInstant(value(f,'endDate'),value(f,'endTime'),zone,value(f,'repeated'))}}

export function WorkspaceForm({kind,w,day,send,onError,record,draftNeed,assignment}:{kind:FormKind;day:string;record?:WorkRecord;draftNeed?:RecordOf<'staffing'>;assignment?:RecordOf<'close'>}&Props) {
  const zone=w.location.timezone,standards=record?.kind==='shift'?guidesForShift(w,record):w.records.filter((r):r is RecordOf<'standard'>=>r.kind==='standard'&&r.locationId===w.location.id&&r.data.status==='approved');
  const [standardId,setStandardId]=useState(assignment?.data.standardId??standards[0]?.id??'');
  const [allDay,setAllDay]=useState(record?.kind==='availability'&&record.data.startMinute===0&&record.data.endMinute===1440);
  const standard=standards.find(r=>r.id===standardId);
  if(kind==='task'||kind==='handoff'||kind==='feedback'||kind==='development'||kind==='goal')return <FollowForm kind={kind} w={w} send={send} onError={onError} record={record}/>;
  if(kind==='staffing')return <StaffingForm w={w} day={day} send={send} onError={onError}/>;
  if(kind==='order')return <OrderForm w={w} send={send} onError={onError} record={record}/>;
  if(kind==='shift')return <ShiftEditor w={w} day={day} shift={record?.kind==='shift'?record:undefined} draftNeed={draftNeed} send={send} onError={onError}/>;
  if(kind==='time-off')return <Form onError={onError} submit={f=>send('request.create',{type:'time-off',...period(f,zone),note:value(f,'note')})}><p>Choose the full period you need off. A manager reviews the request.</p><Period day={day} zone={zone}/><Note label="Request details"/><button className="shared-primary">Submit time-off request</button></Form>;
  if(kind==='availability') {
    const old=record?.kind==='availability'?record.data:null;
    return <Form onError={onError} submit={f=>send('availability.save',{personId:old&&record?record.ownerId:value(f,'personId')||w.me.id,title:value(f,'title'),kind:value(f,'kind'),startDate:value(f,'startDate'),endDate:value(f,'endDate'),days:f.getAll('days').map(Number),startMinute:allDay?0:minutes(value(f,'startTime')),endMinute:allDay||f.get('untilMidnight')==='on'?1440:minutes(value(f,'endTime')),beforeMinutes:Number(value(f,'beforeMinutes')),afterMinutes:Number(value(f,'afterMinutes')),excludedDates:value(f,'exceptions').split(/[\s,]+/).filter(Boolean),...(old&&record?{replacesId:record.id}:{})})}>
      <Field label="Employee"><People w={w} current={record?.ownerId??w.me.id} filter={m=>old&&record?m.id===record.ownerId:m.id===w.me.id||manages(w.me,m.area,'schedule.manage')}/></Field><p>Choose the days and times this person cannot work. A manager reviews changes before they affect scheduling.</p>
      <Field label="Name"><input name="title" required maxLength={150} defaultValue={old?.title}/></Field><Field label="Type"><select name="kind" defaultValue={old?.kind??'school'}><option value="school">School / classes</option><option value="unavailable">Unavailable</option></select></Field>
      <label className="shared-check"><input type="checkbox" checked={allDay} onChange={e=>setAllDay(e.target.checked)}/>Unavailable all day</label>
      <div className="shared-grid"><Field label="First date"><input type="date" name="startDate" required defaultValue={old?.startDate??day}/></Field><Field label="Last date"><input type="date" name="endDate" required defaultValue={old?.endDate??day}/></Field>{!allDay&&<><Field label="From"><input type="time" name="startTime" required defaultValue={clock(old?.startMinute??480)}/></Field><Field label="Until"><input type="time" name="endTime" required defaultValue={clock(old?.endMinute===1440?0:old?.endMinute??900)}/></Field></>}<Field label="Travel before (minutes)"><input type="number" name="beforeMinutes" min={0} max={180} defaultValue={old?.beforeMinutes??0}/></Field><Field label="Travel after (minutes)"><input type="number" name="afterMinutes" min={0} max={180} defaultValue={old?.afterMinutes??30}/></Field></div>
      {!allDay&&<label className="shared-check"><input type="checkbox" name="untilMidnight" defaultChecked={old?.endMinute===1440}/>Until midnight at the end of the day</label>}
      <fieldset><legend>Days</legend><div className="shared-checks">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=><label key={d}><input type="checkbox" name="days" value={i} defaultChecked={old?old.days.includes(i):i>0&&i<6}/>{d}</label>)}</div></fieldset>
      <Field label="Dates this restriction does not apply (YYYY-MM-DD)"><textarea name="exceptions" placeholder="One date per line" defaultValue={old?.excludedDates?.join('\n')}/></Field><button className="shared-primary">Submit for review</button>
    </Form>;
  }
  if(kind==='message')return <MessageComposer w={w} record={record} send={send} onError={onError}/>;
  if(kind==='leadership')return <Form onError={onError} submit={f=>send('leadership.assign',{personId:value(f,'personId'),area:value(f,'area'),...period(f,zone),note:value(f,'note')})}><Field label="Responsible leader"><People w={w} filter={m=>has(m,'schedule.change')||has(m,'close.confirm')}/></Field><Field label="Department"><select name="area" defaultValue={w.me.area}>{[...new Set(w.members.map(m=>m.area))].filter(area=>canPublish(w.me,area)).map(area=><option key={area}>{area}</option>)}</select></Field><Period day={day} zone={zone}/><Note label="Responsibility / reason"/><button className="shared-primary">Assign leadership</button></Form>;
  if(kind==='standard')return <StandardEditor w={w} send={send} onError={onError}/>;
  if(kind==='close'&&record?.kind==='shift')return <Form onError={onError} submit={f=>send('close.assign',{shiftId:record.id,standardId:value(f,'standardId'),managerId:value(f,'managerId'),...(value(f,'verifierId')?{verifierId:value(f,'verifierId')}:{}),due:localInstant(value(f,'dueDate'),value(f,'dueTime'),zone,value(f,'repeated')),note:value(f,'note')},assignment)}>
    <Field label="Approved closing standard"><select name="standardId" value={standardId} onChange={e=>setStandardId(e.target.value)} required><option value="">Choose a standard</option>{standards.map(s=><option key={s.id} value={s.id}>{`${s.data.title} · v${s.data.version}`}</option>)}</select></Field>{!standards.length&&<p>No approved closing standard matches this shift’s station. Review the station’s approved guides before assigning the close.</p>}
    <Field label="Closing manager"><People w={w} name="managerId" current={assignment?.data.managerId} filter={m=>m.id!==record.ownerId&&canManageClosing(m,record.area,'close.confirm')}/></Field>
    {standard?.kind==='standard'&&standard.data.verification==='senior-then-manager'&&<Field label="First physical verifier"><People w={w} name="verifierId" current={assignment?.data.verifierId} filter={m=>m.id!==record.ownerId&&canManageClosing(m,record.area,'close.verify')}/></Field>}
    <div className="shared-grid"><Field label="Due date"><input type="date" name="dueDate" defaultValue={localDate(assignment?.data.due??record.data.end,zone)} required/></Field><Field label="Due time"><input type="time" name="dueTime" defaultValue={localClock(assignment?.data.due??record.data.end,zone)} required/></Field></div><ClockChange/><Note label="Assignment note"/><button className="shared-primary">{assignment?'Save closing assignment':'Assign closing work'}</button>
  </Form>;
  if(kind==='swap'&&record?.kind==='shift')return <Form onError={onError} submit={f=>send('request.create',{type:'swap',shiftId:record.id,replacementId:value(f,'replacementId'),start:record.data.start,end:record.data.end,note:value(f,'note')})}><p>You remain responsible until the replacement accepts and an authorized leader approves.</p><Field label="Proposed replacement"><People w={w} name="replacementId" filter={m=>m.id!==w.me.id&&m.area===record.area&&m.qualifications.includes(record.data.position)}/></Field><Note label="Coverage request"/><button className="shared-primary">Request coverage</button></Form>;
  return <p>This action is not available.</p>;
}

export function RecordDetail({record:r,w,send,onError,onOpen,onWeek,onGuides,onAskWeek,now,apiRoot='/api'}:Props&{apiRoot?:string;record:WorkRecord;onGuides:(station:string)=>void;onAskWeek:(r:RecordOf<'shift'>)=>void;onOpen:(record:WorkRecord)=>void;onWeek:(r:WorkRecord)=>void;now:string}) {
  const [editingShift,setEditingShift]=useState(false);
  if(r.kind==='learningcase')return <OperationalLearningCard r={r} w={w} send={send} onOpen={onOpen}/>;
  if(r.kind==='achievement')return <PositionAchievements w={w} send={send} onOpen={onOpen} onlyId={r.id}/>;
  if(r.kind==='shift'&&editingShift)return <><button className="detail-back" type="button" onClick={()=>setEditingShift(false)}>‹ Back to shift</button><ShiftEditor w={w} day={localDate(r.data.start,w.location.timezone)} shift={r} send={send} onError={onError}/></>;
  if(r.kind==='proficiency')return <ProficiencyDetail w={w} record={r}/>;
  if(r.kind==='attendance')return <AttendanceDetail w={w} record={r} send={send} onError={onError} now={now}/>;
  if(r.kind==='coverage')return <CoverageDetail w={w} record={r} send={send} now={now}/>;
  if(r.kind==='staffing')return <StaffingDetail w={w} record={r} send={send} onError={onError}/>;
  if(r.kind==='task'||r.kind==='handoff'||r.kind==='feedback'||r.kind==='development'||r.kind==='goal')return <FollowDetail record={r} w={w} send={send} onError={onError} onOpen={onOpen}/>;
  const me=w.me,zone=w.location.timezone,owner=personName(w,r.ownerId,'Employee'),day=localDate(new Date().toISOString(),zone);
  const history='history' in r.data?r.data.history:undefined;
  const correction=r.kind==='close'&&r.data.phase==='correction'?[...(history??[])].reverse().find(h=>h.action==='fix'||h.action==='dispute'):null;
  const instruction=correction&&<article aria-label="What needs correction"><strong>What needs correction</strong><p className="shared-message">{correction.note}</p><small>{personName(w,correction.actorId,'Your reviewer')} · {displayTime(correction.at,zone)}</small></article>;
  const trail=history?.length?<details><summary>History</summary><ol className="shared-history">{history.map((h,i)=><li key={i}><strong>{h.action} · {personName(w,h.actorId,'Previous member')}</strong><span>{h.note}</span><small>{displayTime(h.at,zone)}</small></li>)}</ol></details>:null;
  const review=(action:string)=> <Form onError={onError} submit={(f,decision)=>send(action,{approve:decision==='approve',note:value(f,'note')},r)}><Note label="Review note"/><div className="shared-actions"><button value="decline">Return / decline</button><button value="approve" className="shared-primary">Approve</button></div></Form>;
  if(r.kind==='shift')return <><div className="shift-detail-summary"><div className="shift-summary-top"><span className="shift-station-tag">{shiftStationName(r)}</span><span className="shift-status">{r.data.cancelled?'Cancelled':r.data.published?'Published':'Draft'}</span></div><p>{new Date(r.data.start).toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',timeZone:zone})}</p><div className="shift-clock-pair"><div><small>Starts</small><strong>{new Date(r.data.start).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:zone})}</strong></div><span aria-hidden="true">→</span><div><small>Ends</small><strong>{new Date(r.data.end).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:zone})}</strong></div></div><p>{localDate(r.data.start,zone)!==localDate(r.data.end,zone)?'Ends '+new Date(r.data.end).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:zone})+' · ':''}{scheduledDuration((Date.parse(r.data.end)-Date.parse(r.data.start))/60000)} scheduled · {r.area}</p>{r.data.releasedAt&&<p>Operational checkout confirmed</p>}</div>
    <ShiftAttendance w={w} shift={r} send={send} onError={onError} now={now} onOpen={onOpen}/>
    <ShiftShortcuts key={r.id} send={send} onError={onError} apiRoot={apiRoot} w={w} shift={r} onOpen={onOpen} onGuides={onGuides} onAskWeek={onAskWeek} onEdit={!r.data.cancelled&&!r.data.releasedAt&&(r.data.published?canChangePublished(w,me,r.area,r.data):manages(me,r.area,'schedule.manage'))?()=>setEditingShift(true):undefined}/>
    {closingStatus(w,r,{allowProjectedReceipts:true}).required&&<article><h3>Required for shift checkout</h3>{[...closingStatus(w,r,{allowProjectedReceipts:true}).closes,...closingStatus(w,r,{allowProjectedReceipts:true}).tasks].map(c=><p key={c.id}><button type="button" onClick={()=>onOpen(c)}>{c.kind==='close'?c.data.standard.title:c.data.title} · {c.data.phase}</button></p>)}<p>{closingStatus(w,r,{allowProjectedReceipts:true}).complete?'Required work is checked. The closing manager confirms checkout.':'The linked work and its required checks must finish before manager checkout.'}</p></article>}
    {!r.data.cancelled&&!r.data.releasedAt&&<>
      {!r.data.published&&canPublish(me,r.area)&&(w.records.some(n=>n.kind==='staffing'&&n.area===r.area&&n.data.status==='approved'&&n.data.start<r.data.end&&n.data.end>r.data.start)?<button className="shared-primary" onClick={()=>onWeek(r)}>Review staffing and publish in Week view</button>:<button className="shared-primary" onClick={()=>send('shift.publish',{},r)}>Publish shift</button>)}
      {r.data.published&&!canChangePublished(w,me,r.area,r.data)&&(manages(me,r.area,'schedule.manage')||canPublish(me,r.area)||manages(me,r.area,'schedule.change'))&&<p role="status">Published changes need an authorized leader assigned to this department for the full shift.{canPublish(me,r.area)?' Use Account → Manage restaurant → Shift leadership, then reopen this shift.':' Ask the schedule publisher to assign the responsible leader.'}</p>}
      {(r.data.published?canChangePublished(w,me,r.area,r.data):manages(me,r.area,'schedule.manage'))&&<details className="shift-management"><summary><span>Manage this shift</span><span aria-hidden="true">+</span></summary><button type="button" onClick={()=>setEditingShift(true)}>Edit time or station</button><details><summary>Cancel / reassign shift</summary><Form onError={onError} submit={f=>send('shift.cancel',{note:value(f,'note'),closeTransfers:w.records.filter(c=>c.kind==='close'&&c.data.shiftId===r.id&&!['closed','cancelled'].includes(c.data.phase)).map(c=>({closeId:c.id,shiftId:value(f,`transfer-${c.id}`)}))},r)}>
      {w.records.filter(c=>c.kind==='close'&&c.data.shiftId===r.id&&!['closed','cancelled'].includes(c.data.phase)).map(c=><Field key={c.id} label={`Cover ${c.kind==='close'?c.data.standard.title:'closing work'}`}><select name={`transfer-${c.id}`} required><option value="">Choose a covering shift</option>{w.records.filter(s=>s.kind==='shift'&&s.id!==r.id&&s.area===r.area&&!s.data.cancelled&&!s.data.releasedAt).map(s=><option key={s.id} value={s.id}>{s.kind==='shift'?`${personName(w,s.ownerId)} · ${displayTime(s.data.start,zone)}`:''}</option>)}</select></Field>)}<Note label="Reason for cancellation"/><button>Cancel shift and retain closing coverage</button></Form></details></details>}
      {canManageClosing(me,r.area,'tasks.manage')&&<>{r.data.position!=='Dishwasher'&&<details><summary>Assign closing work</summary><WorkspaceForm kind="close" record={r} w={w} day={day} send={send} onError={onError}/></details>}{r.data.published&&<details><summary>Assign required checkout work</summary><FollowForm kind="task" record={r} w={w} send={send} onError={onError}/></details>}</>}
      {r.ownerId===me.id&&r.data.published&&<><OfferShift w={w} shift={r} send={send} onOpen={onOpen} now={now}/><details><summary>Ask a specific coworker to cover</summary><WorkspaceForm kind="swap" record={r} w={w} day={day} send={send} onError={onError}/></details></>}
      {r.data.published&&r.ownerId!==me.id&&canManageClosing(me,r.area,'close.confirm')&&<details><summary>Shift checkout</summary><Form onError={onError} submit={f=>send('shift.release',{note:value(f,'note')},r)}><Note label="Checkout note"/><button disabled={!closingStatus(w,r,{allowProjectedReceipts:true}).complete}>Confirm checkout</button>{!closingStatus(w,r,{allowProjectedReceipts:true}).complete&&<p>Open the required closing work above to finish its checks.</p>}<p className="shared-muted">Manager checkout only; payroll time is unchanged.</p></Form></details>}
      {r.data.published&&r.ownerId===me.id&&canManageClosing(me,r.area,'close.confirm')&&<p className="shared-muted">Another authorized closing manager must confirm your checkout. You cannot release your own shift.</p>}
    </>}{trail}</>;
  if(r.kind==='close')return <><p><strong>{owner}</strong> · due {displayTime(r.data.due,zone)}</p><p>First check: {personName(w,r.data.verifierId,'Closing manager')} · Final confirmation: {personName(w,r.data.managerId)}</p><details><summary>Approved instructions for this assignment</summary>{assignedStandardCurrent(w,r)?<StationGuideContent guide={r.data.standard.guide} provenance={r.data.standard.provenance}/>:<p>This assigned version is no longer current. Ask the responsible manager to review and reassign the approved standard before continuing.</p>}<p>Assigned source: {r.data.standard.source} · Version {r.data.standard.version}</p></details><p className="shared-kicker">{r.data.phase.replaceAll('-',' ')}</p><p>Version {r.data.standard.version} · {r.data.standard.source}</p>
    {canManageClosing(me,r.area,'tasks.manage')&&!['closed','cancelled'].includes(r.data.phase)&&w.records.filter((s):s is RecordOf<'shift'>=>s.kind==='shift'&&s.id===r.data.shiftId&&!s.data.cancelled&&!s.data.releasedAt).map(shift=><details key={shift.id}><summary>Edit closing assignment</summary><p>Changing the assignment clears submitted checks. Review the due time and independent reviewers.</p><WorkspaceForm kind="close" w={w} day={day} send={send} onError={onError} record={shift} assignment={r}/></details>)}
    {instruction}<CloseAttention w={w} record={r} send={send} onError={onError}/><CorrectionAssignment w={w} record={r} send={send} onError={onError}/><Form onError={onError} submit={(f,step)=>send('close.transition',{step,...(step==='fix'&&value(f,'managerAttention')?{managerAttention:value(f,'managerAttention')}:{}),answers:f.getAll('answers').map(Number),note:value(f,'note')||(step==='ready'?'All listed conditions confirmed; ready for the physical check.':'Physical check completed.')},r)}>
      <fieldset><legend>Required conditions</legend>{r.data.standard.criteria.map((c,i)=><label className="shared-check" key={i}><input type="checkbox" name="answers" value={i} defaultChecked={r.data.answers?.includes(i)} disabled={correctionPerformer(r)!==me.id||!!r.data.correction&&!eligibleCorrectionHelper(r,me)||!['open','correction'].includes(r.data.phase)}/>{c}</label>)}</fieldset><Note label="Condition, correction or help needed" required={false}/>
      {(r.data.managerId===me.id||r.data.verifierId===me.id)&&!['closed','cancelled'].includes(r.data.phase)&&<details><summary>Flag a correction for manager acknowledgment</summary><p>Every correction is visible to the closing manager. Flag a repeated, serious or unresolved issue when their explicit response is needed. This applies when you return the work for correction.</p><Field label="Manager attention"><select name="managerAttention" defaultValue=""><option value="">No additional acknowledgment</option>{Object.entries(attentionReasons).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field></details>}
      <div className="shared-actions">
      {correctionPerformer(r)===me.id&&(!r.data.correction||eligibleCorrectionHelper(r,me))&&['open','correction'].includes(r.data.phase)&&<button value="ready" className="shared-primary">Ready for physical check</button>}
      {r.data.verifierId===me.id&&r.data.phase==='verification'&&<button value="verify" className="shared-primary">Physical first check passed</button>}
      {r.data.managerId===me.id&&r.data.phase==='manager-confirmation'&&!needsCloseAcknowledgment(r)&&<button value="confirm" className="shared-primary">Confirm final physical check</button>}
      {(r.data.managerId===me.id||r.data.verifierId===me.id)&&!['closed','cancelled'].includes(r.data.phase)&&<button value="fix" onClick={e=>{const form=e.currentTarget.form;if(!form?.querySelector<HTMLTextAreaElement>('textarea')?.value.trim()){e.preventDefault();onError('Describe what needs to be corrected.')}}}>Return for correction</button>}
      </div></Form>{canManageClosing(me,r.area,'tasks.manage')&&!['closed','cancelled'].includes(r.data.phase)&&!needsCloseAcknowledgment(r)&&<details><summary>Remove an unnecessary closing assignment</summary><Form onError={onError} submit={f=>send('close.cancel',{note:value(f,'note')},r)}><Note label="Why this work is no longer required"/><button>Cancel assignment</button></Form></details>}{trail}</>;
  if(r.kind==='request')return <><p>{owner} · {requestTitle(r)} · {requestStatus(r)}</p><p>{displayTime(r.data.start,zone)} → {displayTime(r.data.end,zone)}</p><p>{r.data.note}</p>{r.data.decision&&<p>{r.data.decision}</p>}{r.data.replacementId===me.id&&r.data.status==='pending'&&<div className="shared-actions"><button onClick={()=>send('request.consent',{accept:false},r)}>Decline coverage</button><button onClick={()=>send('request.consent',{accept:true},r)}>Accept for manager review</button></div>}{r.ownerId!==me.id&&r.data.replacementId!==me.id&&['pending','accepted-by-replacement'].includes(r.data.status)&&(r.data.type==='swap'?canChangePublished(w,me,r.area,r.data):manages(me,r.area,'schedule.manage'))&&(r.data.type==='time-off'?<TimeOffReview w={w} request={r} send={send} onError={onError}/>:review('request.review'))}</>;
  if(r.kind==='availability')return <><p>{owner} · {requestStatus(r)}</p><p>{r.data.startDate} through {r.data.endDate}</p><p>{r.data.days.map(d=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]).join(', ')} · {clock(r.data.startMinute)}–{clock(r.data.endMinute)}</p><p>Travel: {r.data.beforeMinutes} minutes before, {r.data.afterMinutes} after</p><p>Exceptions: {r.data.excludedDates?.join(', ')||'None'}</p><p>{r.data.decision}</p>{r.data.status==='pending'&&r.ownerId!==me.id&&manages(me,r.area,'schedule.manage')&&review('availability.review')}{r.data.status==='approved'&&r.ownerId===me.id&&<details><summary>Request a change</summary><WorkspaceForm kind="availability" record={r} w={w} day={day} send={send} onError={onError}/></details>}</>;
  const linked=r.kind==='message'?w.records.find(x=>x.id===r.data.recordId):undefined;
  if(r.kind==='message')return <>{r.data.context&&<MessageAttachment context={r.data.context} w={w} changed={r.data.contextStatus==='changed'}/>}
    {r.data.contextStatus==='unavailable'&&<p>The original attachment is no longer available with your current access. The message remains in this conversation.</p>}{linked&&<button className="shared-primary" onClick={()=>onOpen(linked)}>Open related work</button>}<p className="shared-message">{schedulingNoticeText(r.data.title,r.data.body,w.location.timezone)}</p>{r.data.replies.map((reply,i)=><article key={i}><strong>{personName(w,reply.actorId,'Previous member')}</strong><p className="shared-message">{reply.text}</p></article>)}{!r.data.readBy.includes(me.id)&&<button onClick={()=>send('message.read',{},r)}>Mark read</button>}{!r.data.automated&&<Form onError={onError} submit={f=>send('message.reply',{text:value(f,'reply')},r)}><Field label="Reply in this conversation"><textarea name="reply" required maxLength={4000}/></Field><button className="shared-primary">Send reply</button></Form>}</>;
  if(r.kind==='standard'&&(r.data.provenance?.intake||r.data.provenance?.starter))return <SourceGuideDetail key={r.id} w={w} record={r} send={send} onError={onError} trail={trail}/>;
  if(r.kind==='standard')return <><p>{r.data.zone} · {r.data.position} · version {r.data.version} · {r.data.status}</p>{r.data.status==='draft'&&<p>This is a draft for review, not approved operating guidance.</p>}{r.data.status==='retired'&&<p>This version has been retired. Use the currently approved instruction.</p>}<StationGuideContent guide={r.data.guide}/><h3>What done looks like</h3><ul>{r.data.criteria.map((c,i)=><li key={i}>{c}</li>)}</ul><p>Source: {r.data.source}</p>{r.data.provenance&&<SourceReview provenance={r.data.provenance} approved={r.data.status==='approved'}/>}<p>When assigned as closing work: {r.data.verification==='manager'?'Closing manager physical check':'Designated senior / lead, then closing manager physical confirmation'}</p>{manages(me,r.area,'standards.approve')&&r.data.status==='draft'&&<Form onError={onError} submit={f=>send('standard.approve',{validated:f.get('validated')==='on',note:value(f,'note')},r)}><label className="shared-check"><input type="checkbox" name="validated" required/>I have validated the instructions and conditions against the current restaurant source.</label><Note label="Validation and approval record"/><button className="shared-primary">Approve this version</button></Form>}{manages(me,r.area,'standards.approve')&&r.data.status==='approved'&&<Form onError={onError} submit={f=>send('standard.retire',{note:value(f,'note')},r)}><Note label="Reason for retiring this standard"/><button>Retire standard</button></Form>}{canDraftStandard(me,r.area)&&<details><summary>{r.data.status==='draft'?'Edit this draft':'Draft a new version'}</summary><StandardEditor w={w} record={r} send={send} onError={onError}/></details>}{trail}</>;
  if(r.kind==='leadership')return <><p>{owner} · {r.data.area}</p><p>{displayTime(r.data.start,zone)} → {displayTime(r.data.end,zone)}</p><p>{r.data.note}</p>{r.data.active&&canPublish(me,r.area)&&<Form onError={onError} submit={f=>send('leadership.revoke',{note:value(f,'note')},r)}><Note label="Reason for ending this responsibility"/><button>Revoke assignment</button></Form>}</>;
  if(r.kind==='order')return <><p>{owner} · {r.data.status} · version {r.revision}</p><ul>{r.data.lines.map((l,i)=><li key={i}><strong>{l.quantity} {l.unit} · {l.name}</strong><p>{l.productId} {l.note}</p></li>)}</ul><p>{r.data.note}</p>{r.ownerId===me.id&&['draft','returned'].includes(r.data.status)&&<><details><summary>Edit request</summary><OrderForm record={r} w={w} send={send} onError={onError}/></details><button className="shared-primary" onClick={()=>send('order.submit',{},r)}>Submit for purchaser review</button></>}{r.ownerId===me.id&&r.data.status==='review'&&<button onClick={()=>send('order.withdraw',{},r)}>Withdraw to edit</button>}{has(me,'orders.review')&&r.data.status==='review'&&review('order.review')}<p>No supplier order is placed by this action.</p>{trail}</>;
  return <p>This record is available through its assigned workflow.</p>;
}

function OrderForm({record,w,send,onError}:Props&{record?:WorkRecord}) {
  const [lines,setLines]=useState<Line[]>(record?.kind==='order'?record.data.lines:[{name:'',quantity:1,unit:'case',productId:'',note:''}]);
  const change=(i:number,patch:Partial<Line>)=>setLines(rows=>rows.map((l,j)=>i===j?{...l,...patch}:l));
  return <Form onError={onError} submit={f=>send('order.save',{lines,note:value(f,'note')},record)}>
    <p>{w.location.name} · Internal request</p><Field label="Load a saved JMAX order guide"><input type="file" accept=".json,application/json" onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>1000000)throw Error('Choose a guide under 1 MB.');const data=JSON.parse(await file.text());if(!Array.isArray(data.lines)||!data.lines.length||data.lines.length>200)throw Error('Choose a guide with 1–200 items.');setLines(data.lines.map((l:Record<string,unknown>)=>{if(typeof l.name!=='string'||typeof l.unit!=='string'||!Number.isFinite(l.quantity??l.qty))throw Error('Every guide item needs a product, quantity and unit.');return {name:l.name,quantity:Number(l.quantity??l.qty),unit:l.unit,productId:typeof l.productId==='string'?l.productId:'',note:typeof l.note==='string'?l.note:''}}))}catch(error){onError(error instanceof Error?error.message:'Could not load guide.')}}}/></Field>
    {lines.map((l,i)=><fieldset key={i}><legend>Item {i+1}</legend><Field label="Product"><input required maxLength={200} value={l.name} onChange={e=>change(i,{name:e.target.value})}/></Field><div className="shared-grid"><Field label="Quantity"><input type="number" required min={0.01} max={10000} step="any" value={l.quantity} onChange={e=>change(i,{quantity:Number(e.target.value)})}/></Field><Field label="Unit"><input required maxLength={40} value={l.unit} onChange={e=>change(i,{unit:e.target.value})}/></Field></div><Field label="Supplier product number"><input maxLength={100} value={l.productId} onChange={e=>change(i,{productId:e.target.value})}/></Field><Field label="Quality / product requirements"><textarea maxLength={500} value={l.note} onChange={e=>change(i,{note:e.target.value})}/></Field><button type="button" onClick={()=>setLines(rows=>rows.filter((_,j)=>i!==j))}>Remove item</button></fieldset>)}
    <button type="button" disabled={lines.length>=200} onClick={()=>setLines(rows=>[...rows,{name:'',quantity:1,unit:'case',productId:'',note:''}])}>Add item</button><Note label="Order notes" required={false} initial={record?.kind==='order'?record.data.note:''}/><button className="shared-primary">Save draft</button>
  </Form>;
}

