'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { historyManager } from '../shared/record-history';
import type { HistoryPage, HistoryPreview, HistoryRestore } from '../shared/history-service';
import { displayTime, localDate, nextDate } from '../shared/local-time';
import { personName, type WorkRecord, type Workspace } from '../shared/types';
import { RecordDetail } from './workspace-forms';
import {EquipmentCard} from './equipment';
import {ComplianceCard} from './compliance';
import {StaffIdeaCard} from './staff-ideas';
import {RecognitionCard} from './recognition';
import {CateringCard} from './catering';
import {MaintenanceCard} from './maintenance';
import {ServiceContactCard} from './service-contacts';
import {PromotionCard} from './promotions';
import {OpeningCard} from './hiring-openings';
import {HireHandoffCard} from './hire-handoff';
import {HireChecklistCard} from './hire-checklist';
import { GuestReviewCard } from './guest-reviews';
import { CheckinCard } from './shift-checkin';

type Detail={workspace:Workspace;recordId:string;archivedAt:string;canRestore:boolean};
const kinds=[['opening','Hiring openings'],['catering','Catering events'],['recognition','Recognition'],['staffidea','Staff ideas'],['compliance','Inspections and permits'],['equipment','Equipment'],['hirechecklist','Onboarding checklists'],['maintenance','Scheduled maintenance'],['servicecontact','Service contacts'],['promotion','Promotions'],['hirehandoff','First-shift handoffs'],['guestreview','Guest reviews'],['shift','Shifts'],['attendance','Attendance'],['shiftcheckin','Shift check-ins'],['message','Messages'],['request','Schedule requests'],['goal','Goals'],['development','Development reviews'],['close','Closing work'],['task','Tasks'],['handoff','Handoffs'],['leadership','Shift leadership'],['availability','Availability'],['coverage','Coverage'],['staffing','Staffing plans'],['feedback','Feedback'],['order','Order requests']];
const historyDate=(r:WorkRecord)=>r.kind==='shift'?r.data.start:r.kind==='attendance'||r.kind==='shiftcheckin'?r.data.shift.start:r.updatedAt;
const label=(r:WorkRecord,w:Workspace)=>r.kind==='equipment'?r.data.assetTag+' · '+r.data.title:r.kind==='shiftcheckin'?personName(w,r.ownerId)+' · Shift check-in':r.kind==='shift'?personName(w,r.ownerId)+' · '+r.data.position:r.kind==='close'?r.data.standard.title:'title' in r.data?r.data.title:personName(w,r.ownerId)+' · '+(kinds.find(([k])=>k===r.kind)?.[1]??r.kind);
class HistoryError extends Error{constructor(message:string,public status:number){super(message)}}
async function read<T>(url:string,body?:Record<string,unknown>):Promise<T>{const response=await fetch(url,{credentials:'same-origin',cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});let data;try{data=await response.json()}catch{throw new HistoryError('Could not confirm the response. Retry the same change to check its saved result.',503)}if(!response.ok)throw new HistoryError(data&&typeof data==='object'&&'error' in data&&typeof data.error==='string'?data.error:'History is unavailable.',response.status);return data as T;}

export function WorkHistory({w,apiRoot,onChanged,onBack,onCheckins}:{w:Workspace;apiRoot:string;onChanged:()=>Promise<void>;onBack:()=>void;onCheckins:()=>void}){
  const [kind,setKind]=useState(''),[from,setFrom]=useState(''),[through,setThrough]=useState(''),[before,setBefore]=useState(()=>nextDate(localDate(new Date().toISOString(),w.location.timezone),-90));
  const [page,setPage]=useState<HistoryPage|null>(null),[detail,setDetail]=useState<Detail|null>(null),[preview,setPreview]=useState<HistoryPreview|null>(null),[restore,setRestore]=useState<HistoryRestore|null>(null);
  const [cursor,setCursor]=useState(''),[back,setBack]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirmed,setConfirmed]=useState(false),[uncertain,setUncertain]=useState(false);
  const pending=useRef<Record<string,unknown>|null>(null),generation=useRef(0),section=useRef<HTMLElement>(null);
  const appliedFilters=useRef<{kind?:string;from?:string;through?:string}>({});
  const endpoint=apiRoot+'/history',base=endpoint+'?locationId='+encodeURIComponent(w.location.id);
  const fail=(e:unknown)=>{setError(e instanceof Error?e.message:'History is unavailable.');if(e instanceof HistoryError&&[401,403].includes(e.status)){setPage(null);setDetail(null);setPreview(null);setRestore(null)}};
  const load=useCallback(async(next='',filters:{kind?:string;from?:string;through?:string}={})=>{
    const token=++generation.current;setBusy(true);setError('');
    try{const query=new URLSearchParams({locationId:w.location.id,...Object.fromEntries(Object.entries(filters).filter(([,v])=>v)),...(next?{cursor:next}:{})});const data=await read<HistoryPage>(endpoint+'?'+query);if(token===generation.current){setPage(data);setCursor(next);setDetail(null);setPreview(null);setRestore(null);setConfirmed(false);section.current?.closest('main')?.scrollTo({top:0,left:0,behavior:'instant'})}}catch(e){if(token===generation.current)fail(e)}finally{if(token===generation.current)setBusy(false)}
  },[endpoint,w.location.id]);
  useEffect(()=>{void load();return()=>{generation.current++}},[load]);
  async function open(recordId:string){setBusy(true);setError('');try{const data=await read<Detail>(base+'&recordId='+encodeURIComponent(recordId));setDetail(data);setRestore(null);section.current?.closest('main')?.scrollTo({top:0,left:0,behavior:'instant'})}catch(e){fail(e)}finally{setBusy(false)}}
  async function review(){setBusy(true);setError('');setNotice('');try{setPreview(await read<HistoryPreview>(base+'&preview=1&before='+encodeURIComponent(before)));setConfirmed(false)}catch(e){fail(e)}finally{setBusy(false)}}
  async function reviewRestore(){if(!detail)return;setBusy(true);setError('');try{setRestore(await read<HistoryRestore>(base+'&restore='+encodeURIComponent(detail.recordId)));setConfirmed(false)}catch(e){fail(e)}finally{setBusy(false)}}
  async function save(action:'archive'|'restore'){
    if(!pending.current){const plan=action==='archive'?preview:restore;if(!plan||!confirmed)return;pending.current={action,locationId:w.location.id,requestId:crypto.randomUUID(),confirmed:true,workspaceRevision:plan.workspaceRevision,records:plan.records.map(({id,revision})=>({id,revision})),...(action==='archive'?{before:preview!.before}:{recordId:detail!.recordId})};}
    setBusy(true);setError('');
    try{const result=await read<{action:string;count:number}>(endpoint,pending.current);pending.current=null;setUncertain(false);setNotice(`${result.count} ${result.count===1?'record':'records'} ${result.action==='archive'?'filed in history':'restored to the active workspace'}.`);setPreview(null);setRestore(null);setConfirmed(false);setDetail(null);setBack([]);await onChanged();await load('',appliedFilters.current)}catch(e){if(e instanceof HistoryError&&[400,401,403,404,409,415].includes(e.status)){pending.current=null;setUncertain(false);setPreview(null);setRestore(null)}else setUncertain(!!pending.current);fail(e)}finally{setBusy(false)}
  }
  const shown=detail?.workspace.records.find(r=>r.id===detail.recordId);
  const names={...w,formerMembers:page?.formerMembers??w.formerMembers};
  return <section ref={section} className="work-history">
    <button className="schedule-back" disabled={busy||uncertain} onClick={()=>detail?setDetail(null):onBack()}>{detail?'‹ Back to history':'‹ Back to schedule'}</button>
    <h1>Work history</h1>
    {w.me.position!=='Dishwasher'&&<button disabled={busy||uncertain} onClick={onCheckins}>Open Shift check-ins</button>}
    {error&&<p role="alert" className="shared-error">{error}</p>}{notice&&<p role="status" className="shared-notice">{notice}</p>}
    {uncertain&&<div className="shared-notice"><p>The last change has not been confirmed. Check that same change before starting another.</p><button disabled={busy} onClick={()=>void save(pending.current?.action==='restore'?'restore':'archive')}>Check saved result</button></div>}
    {detail&&shown?<>
      <h2>{label(shown,detail.workspace)}</h2><p>{detail.archivedAt?'Filed '+displayTime(detail.archivedAt,w.location.timezone)+'. ':''}Saved history is read-only. Restore a record before making a correction.</p>
      {detail.canRestore&&!restore&&<button disabled={busy||uncertain} onClick={()=>void reviewRestore()}>Review restoration</button>}
      {restore&&<section className="history-review"><h3>Restore {restore.records.length} {restore.records.length===1?'record':'records'}?</h3><p>{shown.kind==='compliance'?'The same source records return with their saved follow-up outcomes, source checks and renewal evidence. Open Inspections and permits to correct or reopen follow-up. Restoring does not certify permit validity or compliance.':shown.kind==='equipment'?'The same physical asset returns as retired. Its tag, source checks and history stay attached; reactivation requires an owner recheck in the equipment register.':shown.kind==='guestreview'?'The same guest follow-up returns with its source, acknowledgment and outcome history. Open Guest reviews to reopen or correct it.':shown.kind==='shiftcheckin'?'Only the response returns; its original shift stays in history. Open Shift check-ins afterward to correct your own response.':'Required related records return with this one. Their saved outcomes and original content stay the same.'}</p><ul>{restore.records.map(r=><li key={r.id}>{label(r,detail.workspace)}</li>)}</ul><label className="shared-check"><input type="checkbox" checked={confirmed} disabled={busy||uncertain} onChange={e=>setConfirmed(e.target.checked)}/>Restore these reviewed records to the active workspace.</label><button className="shared-primary" disabled={!confirmed||busy||uncertain} onClick={()=>void save('restore')}>Restore records</button></section>}
      {shown.kind==='opening'?<OpeningCard r={shown} w={detail.workspace} send={async()=>false} busy={busy} now={new Date().toISOString()} readOnly/>:shown.kind==='catering'?<CateringCard r={shown} w={detail.workspace} send={async()=>false} busy={busy} now={new Date().toISOString()} readOnly/>:shown.kind==='recognition'?<RecognitionCard r={shown} w={detail.workspace} send={async()=>false} busy={busy} now={new Date().toISOString()} readOnly/>:shown.kind==='staffidea'?<StaffIdeaCard r={shown} w={detail.workspace} send={async()=>false} busy={busy} now={new Date().toISOString()} readOnly/>:shown.kind==='compliance'?<ComplianceCard r={shown} w={detail.workspace} send={async()=>false} busy={busy} dueText="Filed internal follow-up · retained source evidence" readOnly/>:shown.kind==='equipment'?<EquipmentCard r={shown} w={detail.workspace} send={async()=>false} busy={busy} readOnly/>:shown.kind==='hirechecklist'?<HireChecklistCard r={shown} w={detail.workspace} send={async()=>false} busy={busy} now={new Date().toISOString()} readOnly/>:shown.kind==='maintenance'?<MaintenanceCard r={shown} w={detail.workspace} send={async()=>false} busy={busy} now={new Date().toISOString()} readOnly/>:shown.kind==='servicecontact'?<ServiceContactCard r={shown} w={detail.workspace} send={async()=>false} busy={busy} readOnly/>:shown.kind==='promotion'?<PromotionCard r={shown} w={detail.workspace} send={async()=>false} busy={busy} now={new Date().toISOString()} readOnly/>:shown.kind==='hirehandoff'?<HireHandoffCard r={shown} w={detail.workspace} send={async()=>false} busy={busy} readOnly/>:shown.kind==='guestreview'?<GuestReviewCard r={shown} w={detail.workspace} send={async()=>false} busy={busy} readOnly/>:shown.kind==='shiftcheckin'?<CheckinCard r={shown} w={detail.workspace} send={async()=>false} busy={busy} readOnly/>:<fieldset disabled className="history-readonly"><RecordDetail record={shown} w={detail.workspace} send={async()=>false} onError={setError} onOpen={()=>{}} onWeek={()=>{}} onGuides={()=>{}} onAskWeek={()=>{}} now={new Date().toISOString()}/></fieldset>}
    </>:<>
      <p>Older completed work stays here with its original details and history. You can see only records your account is allowed to open.</p>
      {historyManager(w)&&<details className="history-review"><summary>File older completed work</summary><p>Review up to 50 records at a time. Open work, unread notices and records still needed by active assignments stay in place. No records are deleted.</p><label className="shared-field">Completed before<input type="date" value={before} max={nextDate(localDate(new Date().toISOString(),w.location.timezone),-30)} disabled={busy||uncertain} onChange={e=>{setBefore(e.target.value);setPreview(null);setConfirmed(false)}}/></label><button disabled={busy||uncertain||!before} onClick={()=>void review()}>Review eligible records</button>
        {preview&&<><p>{preview.activeCount} active records. {preview.records.length} can be filed in this batch.</p>{preview.records.length?<><ul>{preview.records.map(r=><li key={r.id}>{r.label}</li>)}</ul><p>Private completed records keep their existing access restrictions. Filing them does not let an owner read private content.</p><label className="shared-check"><input type="checkbox" checked={confirmed} disabled={busy||uncertain} onChange={e=>setConfirmed(e.target.checked)}/>File this exact reviewed batch in history.</label><button className="shared-primary" disabled={!confirmed||busy||uncertain} onClick={()=>void save('archive')}>File {preview.records.length} records</button></>:<p>Nothing is eligible for this date. Recent changes and records supporting other work stay active.</p>}{preview.remainingCandidates>0&&<p>Other older work may become eligible after this batch or after its linked work is resolved.</p>}</>}
      </details>}
      <form className="attendance-filters" onSubmit={e=>{e.preventDefault();setBack([]);appliedFilters.current={kind,from,through};void load('',appliedFilters.current)}}>
        <label className="shared-field">Record type<select value={kind} disabled={busy||uncertain} onChange={e=>setKind(e.target.value)}><option value="">All available records</option>{kinds.filter(([k])=>w.me.position!=='Dishwasher'||['shift','message','request'].includes(k)).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label>
        <label className="shared-field">From<input type="date" value={from} disabled={busy||uncertain} onChange={e=>setFrom(e.target.value)}/></label><label className="shared-field">Through<input type="date" value={through} disabled={busy||uncertain} onChange={e=>setThrough(e.target.value)}/></label><button disabled={busy||uncertain}>Find history</button>
      </form><p className="shared-muted">Dates use the shift date for schedules, attendance and check-ins; other records use their last update. The latest five check-ins for each employee and department stay active.</p>
      {busy&&!page&&<p role="status">Loading history…</p>}
      {page&&<><div className="shared-list">{page.items.map(item=><button key={item.record.id} disabled={busy||uncertain} onClick={()=>void open(item.record.id)}><span><strong>{label(item.record,names)}</strong><small>{displayTime(historyDate(item.record),w.location.timezone)}</small></span><em>{kinds.find(([k])=>k===item.record.kind)?.[1]}</em></button>)}</div>{!page.items.length&&<p>No matching records on this page.</p>}<div className="shared-actions"><button disabled={!back.length||busy||uncertain} onClick={()=>{const previous=back.at(-1)!;setBack(s=>s.slice(0,-1));void load(previous,appliedFilters.current)}}>Previous page</button><button disabled={!page.nextCursor||busy||uncertain} onClick={()=>{setBack(s=>[...s,cursor]);void load(page.nextCursor!,appliedFilters.current)}}>Next page</button></div></>}
    </>}
  </section>;
}
