'use client';
import {useEffect,useState} from 'react';
import type {WorkspaceSetup} from '../shared/workspace-setup';
import '../team/workspace.css';
export default function OwnerSetup({signInPath}:{signInPath:string}){
 const [view,setView]=useState<WorkspaceSetup|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[status,setStatus]=useState(0);
 useEffect(()=>{const controller=new AbortController();fetch('/api/setup',{credentials:'same-origin',cache:'no-store',signal:controller.signal}).then(async r=>{const data=await r.json() as WorkspaceSetup & {error?:string};if(controller.signal.aborted)return;setStatus(r.status);if(!r.ok)throw Error(data.error??'Setup could not be loaded.');setView(data)}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Setup could not be loaded.')}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return()=>controller.abort()},[]);
 async function create(){if(!view||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/setup',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmed:true,plan:view.plan})});const data=await r.json() as WorkspaceSetup & {error?:string};setStatus(r.status);if(!r.ok)throw Error(data.error??'Setup could not be confirmed.');setView(data)}catch(e){setError(e instanceof Error?e.message:'Setup could not be confirmed.')}finally{setBusy(false)}}
 return <div className="shared-shell"><header><a href="/team">JMAX Companion</a></header><main><section className="shared-welcome" aria-busy={busy}><h1>{view?.complete?'Your workspace is ready':'Set up your restaurant'}</h1>{error&&<p role="alert" className="shared-error">{error}</p>}{busy&&!view&&<p>Checking owner access…</p>}{status===401&&<a className="shared-primary" href={signInPath} target="_top">Sign in with ChatGPT</a>}{view&&<><h2>{view.plan.name}</h2><p>Owner: {view.plan.ownerName} · {view.plan.ownerEmail}</p><p>Time zone: {view.plan.timezone}</p>{view.complete?<><p>Your real restaurant workspace is separate from the sample review.</p><a className="shared-primary" href="/team">Open your workspace</a></>:<><p>Create the restaurant with your owner access. Then connect Toast and review your employees.</p><p>Sample records stay in the review area. Employee invitations and schedules are separate steps.</p><button className="shared-primary" disabled={busy} onClick={()=>void create()}>{busy?'Creating workspace…':'Create restaurant workspace'}</button></>}</>}{error&&<p><a href="/setup">Reload setup</a></p>}<p><a href="/review">Back to sample review</a></p></section></main></div>
}
