"use client";
import {useState} from 'react';
import {toastEmployees,type Person} from './demo-data';
import {isAdmin,type State} from './workflow-model';
import {Panel,Title,Notice,type Update} from './workflows';
export function IntegrationFlow({person,state,update}:{person:Person;state:State;update:Update}){
 const [selected,setSelected]=useState(''),[assignment,setAssignment]=useState(''),[notice,setNotice]=useState('');const item=toastEmployees.find(e=>e.name===selected);
 return <div className="page-wrap workflow-page"><Title title="Source connections" copy="Review the import process with fictional records. A Toast job never grants management authority."/><Notice text="Toast, scheduling providers, supplier accounts, and live AI are not connected. No credentials or real employee data are loaded."/><h2>Fictional employee import</h2>{toastEmployees.map(e=><article className="workflow-card" key={e.name}><h3>{e.name} · {e.job}</h3><p>{isAdmin(person)?`${e.wage} · fictional rate`:'Rate restricted'}</p><p>{state.mappings[e.name]?`Reviewed station mapping: ${state.mappings[e.name]}`:`Suggested station mapping: ${e.map.split(' · ').pop()}`}</p><button onClick={()=>{setSelected(e.name);setAssignment(state.mappings[e.name]??e.map.split(' · ').pop()??'');setNotice('')}}>Review mapping</button></article>)}{item&&<Panel title={`Review ${item.name}`} onClose={()=>setSelected('')}><p>Imported job: {item.job}. This mapping changes the example assignment only. It does not grant a role or permissions.</p><label>Approved station mapping<input value={assignment} onChange={e=>setAssignment(e.target.value)}/></label><Notice text={notice}/><button onClick={()=>{if(!assignment.trim()){setNotice('Enter the station assignment.');return}update(s=>({...s,mappings:{...s.mappings,[item.name]:assignment.trim()}}));setSelected('')}}>Save reviewed mapping</button></Panel>}</div>
}
export function OperatingFlow({person}:{person:Person}){
 const [detail,setDetail]=useState<string|null>(null),owner=person.tier==='Owner';
 const units=person.id==='owner-limited'?['Bert’s','Rudd’s','Bulk Prep']:['Bert’s','Rudd’s','Bulk Prep','Papa Leone’s'];
 const metrics=[['Net sales','$56,420','Example sales after discounts; not a current Toast result.'],['Actual labor','22.4%','Fictional labor expense divided by fictional net sales for the same period.'],['Scheduled labor','23.1%','Fictional schedule forecast; different from actual time entries.'],['Food cost','31.8%','Illustrative estimate. No purchase, invoice, or inventory counts are connected.']];
 return <div className="page-wrap workflow-page"><Title title={owner?'Business health':'Operating picture'} copy="These examples show the intended decision view. No current restaurant result is represented."/>{owner?<div>{units.map(u=><article key={u} className="workflow-card"><h2>{u}</h2><p>{u==='Papa Leone’s'?'Jay’s limited summary only. No individual records or operational detail.':'Live operating data is not connected.'}</p><button onClick={()=>setDetail(u==='Papa Leone’s'?'Only the authorized Papa Leone’s summary belongs here. No additional business records are loaded.':`${u}: sales, labor, exceptions, and management follow-through require verified source connections.`)}>View source status</button></article>)}</div>:<div className="metric-grid">{metrics.map(([name,value,copy])=><article key={name}><small>{name} · fictional</small><strong>{value}</strong><button onClick={()=>setDetail(copy)}>View source & meaning</button></article>)}</div>}{detail&&<Panel title="Source and evidence" onClose={()=>setDetail(null)}><p>{detail}</p><Notice text="No live source has been verified. Use the completed workflow review to identify what must be connected before launch."/></Panel>}</div>
}
