import {station,tasksFor,type Person} from './demo-data';
import {coverage,canSeeMessage,eventVisible,personName,taskKey,DEMO_DAY,shiftLabel,type State} from './workflow-model';
export function answerFromContext(question:string,person:Person,state:State){
 const q=question.toLowerCase(),tasks=tasksFor(person),next=tasks.find(t=>!state.tasks[taskKey(person,t.id)]?.submitted),events=state.events.filter(e=>eventVisible(e,person)&&e.phase!=='closed'),messages=state.messages.filter(m=>canSeeMessage(m,person)),shift=state.shifts.find(s=>s.personId===person.id&&s.date===DEMO_DAY);
 const summary=events.length?events.map(e=>`${e.title}: ${e.phase}; ${personName(e.ownerId)} owns the next action, due ${e.due.toLowerCase()}.`).join('\n'):'No open follow-up is assigned in this review day.';
 if(/summarize this message/.test(q)){const m=messages.find(m=>question.includes(m.subject));return m?`${m.subject}\n${m.body}\n${m.replies.map(r=>`${r.from}: ${r.text}`).join('\n')}\nOpen Inbox to acknowledge or reply. Nothing has been sent.`:'That message is not available in this role. Open a visible message from Inbox.';}
 if(/papa/.test(q)&&person.id==='owner-limited')return 'Papa Leone’s is outside your authorized business scope.';
 if(/compare|business/.test(q)&&person.tier==='Owner')return `Your authorized businesses: ${person.id==='owner-limited'?'Bert’s, Rudd’s, and Bulk Prep':'Bert’s, Rudd’s, Bulk Prep, and Papa Leone’s summary only'}. The displayed figures are fictional; no live business comparison is connected.`;
 if(/back window|coverage|cover|uncovered/.test(q)){const r=state.shifts.find(s=>s.date===DEMO_DAY&&s.position==='Back Window');return `${coverage(state)?`Back Window is covered: ${r?personName(r.personId):'assigned employee'}, ${r?shiftLabel(r):'through close'}.`:'Back Window is missing a full 4 PM–close assignment.'} ${messages.find(m=>m.id==='coverage-update')?.body??''}\nOpen Schedule to review current assignments or a pending request. I have not changed the schedule.`;}
 if(/next task|what matters|right now/.test(q)&&person.tier==='Team Member')return next?`Next: ${next.title}.\n${next.steps.map((s,i)=>`${i+1}. ${s}`).join('\n')}\n${summary}`:`Your submitted tasks are recorded. ${summary}`;
 const task=tasks.find(t=>q.includes(t.title.toLowerCase()));if(task)return `${task.title}\n${task.why}\n${task.steps.map((s,i)=>`${i+1}. ${s}`).join('\n')}\nReport the actual condition in the task. A help request stays open in Today until the responsible person acts.`;
 if(/schedule|shift|availability|swap/.test(q))return `${shift?`Your Friday assignment is ${shift.position}, ${shiftLabel(shift)}.`:'You have no Friday shift recorded.'} Open Schedule to request time off, an availability change, or a swap. A manager reviews it and the result appears in Inbox.`;
 if(/pay|wage|rate/.test(q))return ['GM','Owner'].includes(person.tier)?'People & development shows fictional individual rates within the available restaurant scope. These are not payroll data.':'Individual pay is restricted for this role. Ask your GM about labor impact or staffing needs.';
 if(/labor|sales|food cost/.test(q))return 'The operating examples show 22.4% actual labor and 23.1% scheduled labor. These are fictional examples, not current Toast or payroll figures. Open Operating picture for the source boundaries.';
 if(/close/.test(q)&&person.tier==='Team Member')return `${station[person.position]?.close??'Follow the approved station close'}. Record each close step in Today, then request physical checkout. The task remains open until a different authorized leader verifies it.`;
 if(/train|goal|develop|coach/.test(q))return person.tier==='Team Member'?`${state.goals[person.id]?.text??'No agreed goal is recorded yet.'} Goals & development holds your feedback and manager follow-up. Level 4 or 5 plus separate trainer certification is required to train.`:`People & development contains your department’s goals and shared feedback. ${summary}`;
 if(/help|problem|report/.test(q))return `For ${person.position}, open the relevant task in Today and record the specific issue. It will appear in the assigned leader’s queue. For workplace feedback, use Goals & development and explicitly choose whether to share it.\n${summary}`;
 if(/attention|derail|overdue|fix|evidence|risk|resolve/.test(q))return summary;
 return `This build can explain recorded tasks, schedule, coverage, shared messages, and open follow-up. It does not yet have a live AI connection. ${person.tier==='Team Member'&&next?`Your next task is ${next.title}.`:summary}`;
}
