"use client";
import {useState,useEffect} from "react";
import {people,station,tasksFor,toastEmployees,type Person,type Task,type TeamMessage,type MessageKind,type NewMessageDraft,type VoiceRecognition,type VoiceWindow} from "./demo-data";
import {canSeeMessage,canOrder,eventVisible,coverage,taskKey,type State} from "./workflow-model";
export function Heading({eyebrow,title,copy,side}:{eyebrow:string;title:string;copy:string;side?:React.ReactNode}){return <section className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></div>{side}</section>}

export function NavIcon({item}:{item:string}){
  const props={width:20,height:20,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const};
  if(item==="Today")return <svg {...props}><circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/></svg>;
  if(item==="Schedule")return <svg {...props}><rect x="4" y="5.5" width="16" height="14" rx="2"/><path d="M8 3.5v4M16 3.5v4M4 10h16"/></svg>;
  if(item==="Inbox")return <svg {...props}><path d="M4 6h16v12H4z"/><path d="M4 7l8 6 8-6"/></svg>;
  if(item==="JMAX")return <svg {...props}><path d="M12 3l1.3 4.2L17.5 9l-4.2 1.5L12 15l-1.4-4.5L6.5 9l4.1-1.8L12 3z"/><path d="M18.5 15l.7 2.2 2.3.8-2.3.8-.7 2.2-.7-2.2-2.3-.8 2.3-.8.7-2.2z"/></svg>;
  if(item==="Growth")return <svg {...props}><path d="M5 18l5-5 3 3 6-8"/><path d="M15 8h4v4"/></svg>;
  if(item==="Health")return <svg {...props}><circle cx="12" cy="12" r="8"/><path d="M7.5 12h2.2l1.2-3 2.1 6 1.2-3h2.3"/></svg>;
  if(item==="Operate")return <svg {...props}><path d="M4 7h10M18 7h2M4 12h3M11 12h9M4 17h8M16 17h4"/><circle cx="16" cy="7" r="2"/><circle cx="9" cy="12" r="2"/><circle cx="14" cy="17" r="2"/></svg>;
  if(item==="People")return <svg {...props}><circle cx="9" cy="9" r="3"/><circle cx="17" cy="10" r="2"/><path d="M4 19c.3-3 2.2-5 5-5s4.7 2 5 5M14 15c2.8-.2 5 1.3 5.5 4"/></svg>;
  return <svg {...props}><path d="M5 6h14M5 11h14M5 16h8"/></svg>;
}

export function TeamToday({person,tasks,completed,onTask}:{person:Person;tasks:Task[];completed:string[];onTask:(id:string)=>void}){
  const c=station[person.position]??station.Dishwasher;
  const dishLabels:Record<string,string>={arrival:"Arrival",service:"Machine refresh",handoff:"Handoff",close:"Final close"};
  const actionMeta:Record<string,{icon:string;summary:string;badge:string}>={arrival:{icon:"✓",summary:"Record what the team inherited",badge:completed.includes("arrival")?"RECORDED":"DUE"},service:{icon:"↻",summary:person.position==="Dishwasher"?"Machine refresh · due before volume":"Readiness check before service volume",badge:"NEXT"},handoff:{icon:"→",summary:"Outgoing ready · leader verify · incoming response",badge:"OPEN"},close:{icon:"⇥",summary:"Universal close plus station-specific items",badge:"LATER"}};
  const railLabel=(task:Task)=>person.position==="Dishwasher"?dishLabels[task.id]:task.title.replace(`${person.position} `,"");
  const activeActions=tasks.slice(0,2);
  return <div className="page-wrap">
    <Heading eyebrow="TODAY · BERT’S" title={`${person.position} · ${person.shift}`} copy={`Closing leader: Jordan · ${c.purpose}`} side={<div className="shift-people"><span>JL</span><span>{person.initials}</span></div>}/>
    <section className="now-card" onClick={()=>onTask(tasks[0].id)}>
      <div className="now-label"><span>STATION ORIENTATION · {person.position}</span></div>
      <div><p className="eyebrow">YOUR SHIFT</p><h2>What did you inherit?</h2><p>Routine work stays quiet. JMAX speaks up only when something needs action.</p></div>
      <button onClick={(event)=>{event.stopPropagation();onTask(tasks[0].id)}}>Open arrival check <span>→</span></button>
    </section>
    <section className="shift-section"><div className="section-title rail-title"><div><p className="eyebrow">SHIFT RAIL</p></div><span>{completed.length} of {tasks.length} complete</span></div><div className="task-list">{tasks.map((t,index)=><button key={t.id} className={`task-row ${t.state} ${completed.includes(t.id)?"complete":""}`} onClick={()=>onTask(t.id)}><span className="task-time">{t.time}</span><span className="task-dot"><i>{index+1}</i></span><span className="task-copy"><small>{t.state==="now"?"DUE NOW":t.state==="next"?"NEXT CHECK":t.state==="required"?"REQUIRED":"LATER"}</small><strong>{railLabel(t)}</strong><span>{t.summary}</span></span><span className="task-action">{completed.includes(t.id)?"RECORDED":t.state==="now"?"DUE NOW":t.state==="next"?"NEXT CHECK":t.state==="required"?"REQUIRED":"LATER"}</span></button>)}</div></section>
    <section className="action-section"><div className="section-title"><div><p className="eyebrow">ACTIONS</p></div><span>Only what matters now</span></div>{activeActions.map(t=><button key={t.id} className="action-card" onClick={()=>onTask(t.id)}><span className="action-icon">{actionMeta[t.id].icon}</span><span><strong>{t.id==="arrival"?"Arrival condition":railLabel(t)}</strong><small>{actionMeta[t.id].summary}</small></span><b>{actionMeta[t.id].badge}</b><i>›</i></button>)}</section>
    <section className="goal-card"><div><p className="eyebrow">THIS WEEK’S FOCUS</p><h3>Complete every {person.position} handoff with no undisclosed carryover</h3></div><div className="progress-ring">75%</div></section>
  </div>
}

export function RoleSwitcher({current,onClose,onChoose}:{current:string;onClose:()=>void;onChoose:(id:string)=>void}){return <div className="overlay"><div className="switcher"><button className="close" onClick={onClose}>×</button><p className="eyebrow">FICTIONAL DEMONSTRATION</p><h2>Experience JMAX as…</h2>{(["BOH","Bridge","FOH","Executive"] as const).map(area=><section key={area}><h3>{area}</h3><div className="people-grid">{people.filter(p=>p.area===area).map(p=><button key={p.id} className={p.id===current?"selected":""} onClick={()=>onChoose(p.id)}><span className="avatar">{p.initials}</span><span><strong>{p.name}</strong><small>{p.position} · {p.tier}</small></span></button>)}</div></section>)}</div></div>}


export function ControlCenter({person,onClose,onNavigate,onSwitchRole,onReplayTour}:{person:Person;onClose:()=>void;onNavigate:(tab:string)=>void;onSwitchRole:()=>void;onReplayTour:()=>void}){
  const lead=person.tier!=="Team Member";
  const admin=person.tier==="GM"||person.tier==="Owner";
  return <div className="overlay"><div className="switcher control-center" role="dialog" aria-modal="true" aria-label="Control center"><button className="close" onClick={onClose}>×</button><p className="eyebrow">CONTROL CENTER · {person.tier.toUpperCase()}</p><h2>Everything beyond today.</h2><p className="control-intro">Daily work stays in the four-item dock. Settings and less-frequent tools live here according to authority.</p><section><h3>MY WORK</h3><div className="control-grid">{person.tier==="Team Member"&&person.position!=="Dishwasher"&&<button onClick={()=>onNavigate("Growth")}><span>↗</span><b>Goals & development</b><small>Progress, station growth and feedback</small></button>}<button onClick={()=>onNavigate("Schedule")}><span>◫</span><b>Availability & schedule</b><small>Your working pattern and change requests</small></button></div></section>{lead&&<section><h3>TEAM</h3><div className="control-grid"><button onClick={()=>onNavigate("People")}><span>◎</span><b>People & development</b><small>Roles, access, coaching and readiness</small></button><button onClick={()=>onNavigate("Inbox")}><span>✉</span><b>Team communication</b><small>Messages, acknowledgments and follow-up</small></button></div></section>}{lead&&<section><h3>RESTAURANT</h3><div className="control-grid"><button onClick={()=>onNavigate(person.tier==="Owner"?"Health":"Operate")}><span>⌁</span><b>{person.tier==="Owner"?"Business health":"Operating picture"}</b><small>Labor, sales, exceptions and source labels</small></button><button onClick={()=>onNavigate("Today")}><span>✓</span><b>Execution & handoffs</b><small>What is open, due and unresolved</small></button></div></section>}{admin&&<section><h3>ADMINISTRATION</h3><div className="control-grid"><button onClick={()=>onNavigate("Toast")}><span>⇄</span><b>Toast connection</b><small>Read-only employee and operating data mapping</small></button><button onClick={()=>onNavigate("People")}><span>⌘</span><b>Roles & permissions</b><small>Custom titles with standardized access controls</small></button></div></section>}{canOrder(person)&&<section><h3>ORDERING</h3><button className="switch-role-action" onClick={()=>onNavigate("Orders")}>Food orders · requests & review →</button></section>}<section className="demo-control"><h3>HELP & DEMONSTRATION</h3><button className="switch-role-action" onClick={onSwitchRole}><span className="avatar">{person.initials}</span><span><b>View as another role</b><small>Explore how JMAX changes by assignment and authority</small></span><i>→</i></button><button className="replay-tour-action" onClick={onReplayTour}><span>?</span><span><b>Replay the guided tour</b><small>See the four parts of the companion again</small></span><i>→</i></button></section></div></div>;
}


export function TutorialOverlay({dish=false,step,onStep,onFinish}:{dish?:boolean;step:number;onStep:(step:number)=>void;onFinish:()=>void}){
  const slides=[
    {label:"MEET YOUR COMPANION",icon:"JMAX",title:"JMAX starts the conversation.",copy:"Open the app and JMAX tells you what matters for your role, assignment and restaurant. It brings the signal to you instead of waiting for you to hunt through screens."},
    {label:"RUN THE WORKDAY",icon:"TODAY",title:"Today turns insight into action.",copy:"Your current work, timed tasks, handoffs, exceptions and approvals live here. Tap any item for guided steps, help, photos and an answer from JMAX in context."},
    {label:"STAY CONNECTED",icon:"SCHEDULE + INBOX",title:"The essentials stay one tap away.",copy:"Schedule shows who is working and where coverage is weak. Inbox keeps staff communication, acknowledgments and follow-up attached to the right people."},
    {label:"YOUR ACCESS",icon:"PROFILE",title:"JMAX changes with responsibility.",copy:"Tap your name to open the Control Center. Team members see their growth. Leaders see the team. GMs and owners receive the operating and administrative tools they are authorized to use."},
  ];
  if(dish){slides[0]={label:"YOUR SCHEDULE",icon:"SCHEDULE",title:"Your schedule, one tap away.",copy:"See your shifts, request time off or availability changes, and follow your manager’s decision."};slides[1]={label:"KEEP IT SIMPLE",icon:"SCHEDULE",title:"A simple experience for Dish.",copy:"Dish uses scheduling and team messages. The richer task and AI Companion experience belongs to the roles that need it."};} const slide=slides[step],last=step===slides.length-1;
  return <div className="tutorial-overlay" role="dialog" aria-modal="true" aria-label="Welcome to JMAX"><div className="tutorial-card" key={step}><button className="tutorial-skip" onClick={onFinish}>Skip</button><div className="tutorial-icon"><span className="mini-brand">J</span><b>{slide.icon}</b></div><p className="eyebrow">{slide.label}</p><h2>{slide.title}</h2><p className="tutorial-copy">{slide.copy}</p><div className="tutorial-map">{["JMAX","TODAY","SCHEDULE","INBOX"].map((item,index)=><span key={item} className={index===Math.min(step,3)?"active":""}>{item}</span>)}</div><div className="tutorial-progress"><span>{step+1} of {slides.length}</span><div>{slides.map((_,index)=><i key={index} className={index<=step?"active":""}/>)}</div></div><div className="tutorial-actions">{step>0?<button onClick={()=>onStep(step-1)}>Back</button>:<span/>}<button className="tutorial-next" onClick={()=>last?onFinish():onStep(step+1)}>{last?"Start using JMAX":"Next"} →</button></div></div></div>;
}


export function routeMessageAudience(draft:NewMessageDraft):Partial<TeamMessage>{
  const named=people.find(p=>draft.audience.startsWith(`${p.name} ·`));
  if(named)return {targetIds:[named.id]};
  if(draft.audience.includes("Bert’s leadership"))return {leadershipOnly:true};
  if(draft.audience.includes("FOH team"))return {targetArea:"FOH"};
  if(draft.audience.includes("BOH team"))return {targetArea:"BOH"};
  const position=Object.keys(station).find(name=>draft.audience===name||draft.audience.startsWith(`${name} ·`));
  return position?{targetPosition:position}:{};
}


export function InboxView({person,messages,onOpen,onCompose}:{person:Person;messages:TeamMessage[];onOpen:(id:string)=>void;onCompose:()=>void}){
  const [filter,setFilter]=useState<"All"|MessageKind>("All");
  const visible=messages.filter(m=>canSeeMessage(m,person));
  const filtered=filter==="All"?visible:visible.filter(m=>m.kind===filter);
  const acknowledgments=visible.filter(m=>m.ackRequired&&!m.acknowledgedBy.includes(person.id)).length;
  return <div className="page-wrap inbox-page">
    <Heading eyebrow="TEAM COMMUNICATION · BERT’S" title="The right message. The right people." copy="Operational communication stays attached to a person, shift, position or acknowledgment—not buried in a group chat." side={<button className="compose-action" onClick={onCompose}>New message</button>}/>
    <div className="inbox-summary"><article><small>Visible to you</small><strong>{visible.length}</strong><span>Based on role and assignment</span></article><article className={acknowledgments?"needs-attention":""}><small>Acknowledgments due</small><strong>{acknowledgments}</strong><span>{acknowledgments?"Tap to read and confirm":"You’re caught up"}</span></article></div>
    <div className="message-filters">{(["All","Direct","Shift","Position","Announcement"] as const).map(item=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{item}</button>)}</div>
    <section className="message-list">{filtered.map(item=>{const needsAck=item.ackRequired&&!item.acknowledgedBy.includes(person.id);return <button key={item.id} className={`message-card ${needsAck?"unread":""}`} onClick={()=>onOpen(item.id)}><span className="message-kind">{item.kind.slice(0,1)}</span><span className="message-copy"><small>{item.kind} · {item.audience}</small><strong>{item.subject}</strong><span>{item.body}</span><em>{item.from} · {item.fromRole} · {item.time}</em></span><span className="message-state">{needsAck?"ACK DUE":item.replies.length?`${item.replies.length} REPLY`:"OPEN"}</span></button>})}{!filtered.length&&<div className="empty-messages"><strong>No messages in this view.</strong><span>JMAX keeps communication scoped instead of showing everyone everything.</span></div>}</section>
    {person.position!=="Dishwasher"&&<section className="message-ai-note"><span className="mini-brand">J</span><div><p className="eyebrow">MESSAGE SUPPORT</p><h3>Summarize and reply.</h3><p>Message summaries use this review day’s visible conversation. The sender reviews every message before sending.</p></div></section>}
  </div>;
}


export function MessageDrawer({message,person,onClose,onAcknowledge,onReply,onAsk}:{message:TeamMessage;person:Person;onClose:()=>void;onAcknowledge:()=>void;onReply:(text:string)=>void;onAsk:()=>void}){
  const [reply,setReply]=useState("");
  const needsAck=message.ackRequired&&!message.acknowledgedBy.includes(person.id);
  const sendReply=()=>{const text=reply.trim();if(!text)return;onReply(text);setReply("")};
  return <div className="overlay"><div className="drawer message-drawer" role="dialog" aria-modal="true" aria-label={message.subject}><button className="close" onClick={onClose}>×</button><div className="drawer-kicker"><span>{message.kind}</span><span>{message.audience}</span>{message.ackRequired&&<span>ACK REQUIRED</span>}</div><h2>{message.subject}</h2><p className="drawer-summary">From {message.from} · {message.fromRole} · {message.time}</p><div className="message-thread"><article className="thread-original"><p>{message.body}</p>{message.attachments?.length?<div className="attachment-row">{message.attachments.map(x=><span key={x}>{x}</span>)}</div>:null}</article>{message.replies.map((item,index)=><article key={`${item.from}-${index}`} className={item.from===person.name?"thread-reply mine":"thread-reply"}><strong>{item.from}</strong><p>{item.text}</p><small>{item.time}</small></article>)}</div>{needsAck?<button className="ack-action" onClick={onAcknowledge}>Acknowledge message →</button>:message.ackRequired?<div className="ack-complete">✓ Acknowledged by {person.name}</div>:null}<div className="message-reply"><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Write an operational reply…"/><div>{person.position!=="Dishwasher"&&<button onClick={onAsk}>Ask JMAX</button>}<button onClick={sendReply} disabled={!reply.trim()}>Send reply →</button></div></div><p className="message-privacy">Operational visibility follows restaurant role and location. Private workplace reports use a separate escalation path.</p></div></div>;
}


export function ComposeDrawer({person,onClose,onSend}:{person:Person;onClose:()=>void;onSend:(draft:NewMessageDraft)=>void}){
  const kinds:MessageKind[]=person.tier==="Team Member"?["Direct"]:person.tier==="Shift Leader"?["Direct","Shift","Position"]:["Direct","Shift","Position","Announcement"];
  const recipients=person.tier==="Team Member"?["Jordan · Shift Leader",person.area==="FOH"?"Avery · FOH Manager":"Renee · BOH Manager"]:person.tier==="Shift Leader"?["Tonight · 3:00 PM–Close",`${person.area} team`,"Bert’s leadership","Eli · Dishwasher"]:person.tier==="Department Manager"?[`${person.area} team`,"Tonight · 3:00 PM–Close","Bert’s leadership","Taylor · GM","Marcus · Sandwich"]:person.tier==="GM"?["Bert’s · All staff","Bert’s leadership","FOH team","BOH team","Renee · BOH Manager"]:["Bert’s · All staff","Bert’s leadership","Taylor · GM","All authorized locations"];
  const [kind,setKind]=useState<MessageKind>(person.tier==="Team Member"?"Direct":"Shift"),[audience,setAudience]=useState(recipients[0]),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[attachments,setAttachments]=useState<string[]>([]);
  const toggleAttachment=(item:string)=>setAttachments(items=>items.includes(item)?items.filter(x=>x!==item):[...items,item]);
  const ready=Boolean(subject.trim()&&body.trim());
  return <div className="overlay"><div className="drawer compose-drawer" role="dialog" aria-modal="true" aria-label="Compose team message"><button className="close" onClick={onClose}>×</button><div className="drawer-kicker"><span>NEW MESSAGE</span><span>{person.tier}</span></div><h2>Send something people can act on.</h2><p className="drawer-summary">Choose the smallest audience that can resolve or use the information.</p><label>Message type</label><div className="compose-choices">{kinds.map(item=><button key={item} className={kind===item?"selected":""} onClick={()=>setKind(item)}>{item}</button>)}</div><label>Audience</label><div className="compose-choices recipient-choices">{recipients.map(item=><button key={item} className={audience===item?"selected":""} onClick={()=>setAudience(item)}>{item}</button>)}</div><label htmlFor="message-subject">Subject</label><input id="message-subject" value={subject} onChange={e=>setSubject(e.target.value)} placeholder="What is this about?"/><label htmlFor="message-body">Message</label><textarea id="message-body" value={body} onChange={e=>setBody(e.target.value)} placeholder="What does this person or group need to know or do?"/><div className="attachment-actions">{["Photo","Voice note","Task link"].map(item=><button key={item} className={attachments.includes(item)?"selected":""} onClick={()=>toggleAttachment(item)}>{item}{attachments.includes(item)?" ✓":" +"}</button>)}</div><button className="jmax-draft" onClick={()=>{if(!subject)setSubject("Shift follow-up");setBody("Please review this before your next assigned task. Reply if anything is unclear or if you need help completing it. ")}}>Ask JMAX to help word this</button>{attachments.length>0&&<p className="attachment-note">Demo attachments: {attachments.join(" · ")}</p>}<div className="compose-footer"><span>Nothing sends until you tap Send.</span><button disabled={!ready} onClick={()=>onSend({kind,audience,subject:subject.trim(),body:body.trim(),attachments})}>Send message →</button></div></div></div>;
}

export function CompanionView({person,state,chat,message,listening,setMessage,setListening,send,onToday}:{person:Person;state:State;chat:{from:"ai"|"me";text:string}[];message:string;listening:boolean;setMessage:(x:string)=>void;setListening:(x:boolean)=>void;send:(x?:string)=>void;onToday:()=>void}){
  const starters=person.tier==="Team Member"?["What matters most right now?","Explain my next task","I need help","How do I close?"]:person.tier==="Owner"?["What actually needs me?","Compare the businesses","What is management not fixing?","Show strategic opportunities"]:["What can derail tonight?","Show labor exposure","Who needs development?","What is overdue?"];
  const open=state.events.filter(e=>eventVisible(e,person)&&e.phase!=="closed");
  const next=tasksFor(person).find(t=>!state.tasks[taskKey(person,t.id)]?.submitted);
  const brief={title:person.tier==="Team Member"?"Your assignment and next step.":person.tier==="Owner"?"Review the work that needs a decision.":"Keep the next action with its owner.",copy:person.tier==="Team Member"?(next?.title??"Your tasks have been submitted. Follow open items in Today."):(open.length?open.map(e=>e.title).join(" · "):"No open items in your review queue."),status:open.length+" OPEN FOLLOW-UPS",facts:[["ASSIGNMENT",person.position],["COVERAGE",coverage(state)?"Back Window covered":"Review Back Window"],["DATA","Fictional review day"]]};
  const [recognition,setRecognition]=useState<VoiceRecognition|null>(null);
 useEffect(()=>()=>{recognition?.stop()},[recognition]);
  const toggleVoice=()=>{if(listening){recognition?.stop();setListening(false);return}const Voice=(window as VoiceWindow).SpeechRecognition??(window as VoiceWindow).webkitSpeechRecognition;if(!Voice){setMessage("Voice typing is not available on this device. You can still type your question here.");return}const next=new Voice();next.lang="en-US";next.interimResults=false;next.continuous=false;next.onresult=event=>{setMessage(event.results[0][0].transcript);setListening(false)};next.onerror=()=>{setMessage("I couldn’t hear that clearly. Tap the microphone and try again.");setListening(false)};next.onend=()=>setListening(false);setRecognition(next);setListening(true);try{next.start()}catch{setListening(false);setMessage("Microphone unavailable. You can type your question.")}};
  return <div className="page-wrap companion-page"><Heading eyebrow="JMAX · PROACTIVE BRIEF" title={`Good afternoon, ${person.name}.`} copy={person.tier==="Team Member"?"I know your assignment, what comes next, and where help belongs.":person.tier==="Owner"?"I’ll bring you patterns, failed management and serious risk—not restaurant noise.":"I sorted today’s restaurant signals by urgency, authority and who can still act."}/><section className="jmax-brief"><div className="brief-status"><span className="mini-brand">J</span><b>{brief.status}</b><small>CURRENT REVIEW STATE</small></div><h2>{brief.title}</h2><p>{brief.copy}</p><div className="brief-facts">{brief.facts.map(([label,value])=><span key={label}><small>{label}</small><b>{value}</b></span>)}</div><div className="brief-actions"><button onClick={onToday}>Open today’s work →</button><button onClick={()=>send(person.tier==="Team Member"?"What matters most right now?":"What actually needs attention?")}>Talk this through</button></div></section><div className="companion-context"><span><small>Speaking as</small><b>{person.name}</b></span><span><small>Authority</small><b>{person.tier}</b></span><span><small>Assignment</small><b>{person.position}</b></span><span><small>Memory</small><b>{chat.length?`${chat.length} messages`:"Ready"}</b></span></div><section className="chat-panel"><div className="chat-label"><p className="eyebrow">ASK, EXPLAIN OR REPORT</p><span>Restaurant work only</span></div><div className="chat-thread compact"><div className="bubble ai"><span className="mini-brand">J</span><p>{person.tier==="Team Member"?`I can guide your ${person.position} work, answer a task question, help with a goal, or route a workplace problem.`:person.tier==="Owner"?"Ask for the evidence behind an owner-level signal, compare authorized businesses, or test whether management is closing the loop.":"Ask about labor, coverage, development, exceptions or what can still be changed today."}</p></div>{chat.map((x,i)=><div key={i} className={`bubble ${x.from}`}><p>{x.text}</p></div>)}</div><div className="starter-row">{starters.map(s=><button key={s} onClick={()=>send(s)}>{s}</button>)}</div><div className="composer"><button className={listening?"mic listening":"mic"} onClick={toggleVoice} aria-label={listening?"Stop listening":"Talk to JMAX"}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3M9 21h6"/></svg></button><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder={listening?"Listening…":`Ask JMAX as ${person.name}…`}/><button onClick={()=>send()}>Send</button></div><p className="boundary">Local review · contextual demo responses · live AI is not connected.</p></section></div>
}

export function OperateView({person}:{person:Person}){return <div className="page-wrap"><Heading eyebrow="LIVE OPERATING PICTURE · FICTIONAL" title={person.tier==="Owner"?"Details are here when ownership asks.":"Control today while action is still possible."} copy="Every number states what it is and where it came from."/><div className="metric-grid"><Metric label="Net sales" value="$56,420" note="Toast · observed"/><Metric label="Actual labor" value="22.4%" note="Time entries · calculated"/><Metric label="Scheduled labor" value="23.1%" note="Schedule · forecast"/><Metric label="Food cost" value="31.8%" note="Purchases + counts · estimate"/></div><Info title="Dinner labor is projected 1.4 points above plan." copy="Review the 7:30 PM coverage transition while action is still possible."/><Capability person={person}/></div>}

export function ToastView({person}:{person:Person}){return <div className="page-wrap"><Heading eyebrow="FICTIONAL TOAST CONNECTION · READ ONLY" title="Import facts. Map authority separately." copy="No live credentials, write-back, payroll, or clock-in changes." side={<button className="outline-action">Connect fictional Toast</button>}/><div className="import-steps"><span><b>1</b>Connect<small>Read only</small></span><span><b>2</b>Detect<small>New · changed · archived</small></span><span><b>3</b>Map<small>AI recommends</small></span><span><b>4</b>Approve<small>GM or Owner</small></span></div><div className="import-list">{toastEmployees.map(e=><article key={e.name}><div><span className="avatar">{e.name.split(" ").map(n=>n[0]).join("")}</span><span><h3>{e.name}</h3><small>Toast job: {e.job} · Wage: {e.wage}</small></span></div><span className="import-status">{e.status}</span><div><small>JMAX RECOMMENDATION · {e.confidence}</small><strong>{e.map}</strong></div><button>Review mapping</button></article>)}</div><section className="security-card"><strong>Security rule</strong><p>Toast jobs never grant JMAX authority. Sensitive changes require approval and an audit trail.</p></section><Capability person={person}/></div>}

export function OwnerHealth({person}:{person:Person}){const units=person.id==="owner-limited"?["Bert’s","Rudd’s","Bulk Prep"]:["Bert’s","Rudd’s","Papa Leone’s","Bulk Prep"];return <div className="page-wrap"><Heading eyebrow="OWNER · CROSS-BUSINESS HEALTH" title="Are the businesses being run well?" copy="Ownership sees material deviation, failed management, serious risk, and opportunity. Routine work stays with the GM."/><div className="unit-grid">{units.map((u,i)=><article key={u}><span className={`signal ${i===0||i===units.length-1?"amber":"green"}`}/><small>{u}</small><h2>{i===0?"Contained equipment risk":i===units.length-1?"Labor forecast above plan":"No ownership action required"}</h2><div><span>Sales <b>{u==="Bulk Prep"?"Internal":["$56,420","$34,180","$41,760"][i]}</b></span><span>Labor <b>{u==="Bulk Prep"?"+4h":["23.1%","21.7%","22.4%"][i]}</b></span></div></article>)}</div><section className="owner-action"><p className="eyebrow">WHAT ACTUALLY NEEDS OWNERSHIP</p><h2>Walk-in temperature risk</h2><p>Product is protected and the GM opened the vendor workflow. Ownership is informed because shutdown risk crossed the escalation rule.</p><button>Ask JMAX for evidence →</button></section><p className="noise-note">✓ Three routine events remain below ownership.</p><Capability person={person}/></div>}

export function Capability({person}:{person:Person}){return <section className="capability"><p className="eyebrow">CAPABILITY-BASED ACCESS</p><h3>{person.tier}</h3><p>{person.position} at Bert’s</p><div><span><b>{person.tier==="Owner"?27:person.tier==="GM"?22:person.tier==="Department Manager"?15:11}</b> capabilities</span><span><b>{person.tier==="Owner"?(person.id==="owner-limited"?3:4):1}</b> locations</span><span><b>{person.area}</b> scope</span></div></section>}

export function Metric({label,value,note}:{label:string;value:string;note:string}){return <article><small>{label}</small><strong>{value}</strong><span>{note}</span></article>}

export function Info({title,copy}:{title:string;copy:string}){return <section className="info-card"><p className="eyebrow">ACTIONABLE NOW</p><h2>{title}</h2><p>{copy}</p><button>Open details →</button></section>}
