import type {Workspace,RecordOf} from './types';
import {cateringReader,cateringFacts} from './catering';
import {displayTime} from './local-time';
import {requireThat} from './validation';
const esc=(v:string|number)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function cateringSheet(w:Workspace,r:RecordOf<'catering'>,generatedAt:string){
 requireThat(cateringReader(r,w.me),'Event not found.',404);const d=r.data,p=d.publication;
 requireThat(p,'Publish an event brief before opening its operational sheet.',409);
 // Always print the publication, including for an editor. Draft facts and
 // private sources never enter the HTML. Legacy publications have no lines.
 const f=cateringFacts(p.facts),pending=d.status==='draft'||d.status==='review';
 const state=d.status==='cancelled'?'CANCELLED — do not use for preparation':pending?'SUPERSEDED — update awaiting owner review':d.status==='completed'?'COMPLETION REPORTED':Date.parse(generatedAt)>=Date.parse(f.end)?'EVENT ENDED — outcome not recorded':'PUBLISHED EVENT BRIEF';
 const detail=(title:string,body:string)=>`<section><h2>${esc(title)}</h2><p class="pre">${esc(body)}</p></section>`;
 const lines=f.menuLines??[];
 const table=lines.length?`<table><caption>Published menu quantities</caption><thead><tr><th scope="col">Item</th><th scope="col">Quantity</th><th scope="col">Unit</th><th scope="col">Reference / notes</th></tr></thead><tbody>${lines.map(l=>`<tr><th scope="row">${esc(l.item)}</th><td>${esc(l.quantity)}</td><td>${esc(l.unit)}</td><td class="pre">${esc(l.reference)}${l.reference&&l.notes?'\n':''}${esc(l.notes)}</td></tr>`).join('')}</tbody></table>`:'<p class="notice">Structured menu quantities were not recorded in this published version. Confirm them before preparation.</p>';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(f.title)} — internal event sheet</title><style>
 @page{size:auto;margin:15mm}*{box-sizing:border-box}body{font:15px/1.45 system-ui,sans-serif;color:#17212b;max-width:1000px;margin:24px auto;padding:0 20px}h1{font-size:28px;line-height:1.2}h2{font-size:17px;margin-bottom:6px}p{margin:8px 0}.meta{font-size:13px;color:#475569}.state{border:3px solid #17212b;padding:12px;font-weight:800}.notice{border-left:4px solid #a65d16;padding:10px;background:#fff7e7}.pre{white-space:pre-wrap;overflow-wrap:anywhere}table{border-collapse:collapse;table-layout:fixed;width:100%;margin:20px 0}caption{text-align:left;font-size:18px;font-weight:700;margin-bottom:8px}th,td{border:1px solid #67717a;padding:8px;text-align:left;vertical-align:top;overflow-wrap:anywhere}th:nth-child(2){width:13%}th:nth-child(3){width:16%}thead{display:table-header-group}tr{break-inside:avoid}section{break-inside:avoid}footer{margin-top:22px;border-top:1px solid #67717a;padding-top:8px;font-size:12px}@media(max-width:500px){body{padding:0 12px}th,td{padding:5px;font-size:12px}}@media print{body{margin:0;max-width:none;padding:0}.screen-only{display:none}h1,h2,caption{break-after:avoid}table{font-size:12px}.state,.notice{background:white}}
 </style></head><body><header><p>${esc(w.location.name)} · JMAX internal event sheet</p><h1>${esc(f.title)}</h1><p class="state">${esc(state)}</p>${pending?'<p class="notice">These are the previous published details. They are no longer current. Contact the responsible manager before preparation.</p>':''}${d.notice?`<p class="notice pre">${esc(d.status==='cancelled'?'Cancellation notice':'Reported outcome')}: ${esc(d.notice.summary)}</p>`:''}<p class="meta">Published version ${p.version}; latest event version ${d.version}. Published ${esc(displayTime(p.at,w.location.timezone))}. Snapshot generated ${esc(displayTime(generatedAt,w.location.timezone))} (${esc(w.location.timezone)}).</p><p class="screen-only">Use your browser’s Print or Save as PDF command. Check the current event in JMAX before using any saved or printed copy.</p></header>
 ${detail('When',displayTime(f.start,w.location.timezone)+' through '+displayTime(f.end,w.location.timezone))}${detail('Service location or pickup point',f.venue)}<p><strong>${f.guests} guests</strong> · ${esc(f.audience.join(' / '))}</p>${detail('Responsible manager',f.managerName)}${detail('Menu or order reference',f.menuRef)}${table}${detail('Menu and service details',f.menuNotes)}${detail('Preparation requirements',f.prepNotes)}${detail('Staffing requirements',f.staffingNotes)}<footer><p>This is an internal operational brief. It does not confirm customer booking, payment, supplier order, stock reservation, completed preparation or scheduled staff. Quantities keep their recorded units; no recipe conversion or total across different units is implied.</p><p>Printed copies do not update. Recheck the latest version and status in JMAX before use. No print, delivery or completion receipt is recorded by opening this page.</p><p>Event ${esc(r.id)} · restaurant ${esc(r.locationId)} · record revision ${r.revision}</p></footer></body></html>`;
}
