import type {FoodReplacementReturn,FoodReplacementReturnVoid} from './food-replacement-return';
import type {FoodReplacement,FoodReplacementVoid} from './food-replacement';
import type {FoodExcessBilling,FoodExcessBillingVoid} from './food-excess-billing';
import type {FoodExcessReturn,FoodExcessReturnVoid} from './food-excess-return';
import type {FoodExcess,FoodExcessVoid,ExcessTotals} from './food-excess';
import type {FoodClaim,FoodClaimUpdate,ClaimLatest,InvoiceClaim} from './food-claim';
import type {RecordOf,History} from './types';
import type {FoodItem,FoodCount,foodRecipeCost} from './food-model';
import type {FoodWaste,FoodWasteVoid} from './food-waste';
import type {FoodInvoiceLine,FoodInvoiceVoid} from './food-invoice';
import type {FoodInvoicePrice} from './food-price';
import type {FoodCredit,FoodCreditVoid,CreditTotals} from './food-credit';
import type {FoodReceiving,FoodReceivingVoid,ReceivingTotals} from './food-receiving';
import type {FoodSupplierReturn,FoodSupplierReturnVoid} from './food-return';
import type {FoodReturnCredit,FoodReturnCreditVoid,MatchTotals} from './food-return-credit';
export type FoodRecord=RecordOf<'fooditem'>|RecordOf<'foodrecipe'>;
export type FoodPage={records:FoodRecord[];next:string|null;revision:number;total:number;items:number;recipes:number;counted:number;areas:string[];costs:Record<string,ReturnType<typeof foodRecipeCost>>;names:Record<string,string>};
export type FoodEvent={action:string;replacementReturn?:FoodReplacementReturn;replacementReturnVoid?:FoodReplacementReturnVoid;replacement?:FoodReplacement;replacementVoid?:FoodReplacementVoid;excessBilling?:FoodExcessBilling;excessBillingVoid?:FoodExcessBillingVoid;excessReturn?:FoodExcessReturn;excessReturnVoid?:FoodExcessReturnVoid;excess?:FoodExcess;excessVoid?:FoodExcessVoid;history:History;count?:FoodCount;supplierClaim?:FoodClaim;claimUpdate?:FoodClaimUpdate;waste?:FoodWaste;wasteVoid?:FoodWasteVoid;invoiceLine?:FoodInvoiceLine;invoiceVoid?:FoodInvoiceVoid;invoicePrice?:FoodInvoicePrice;invoiceCredit?:FoodCredit;creditVoid?:FoodCreditVoid;receiving?:FoodReceiving;receivingVoid?:FoodReceivingVoid;supplierReturn?:FoodSupplierReturn;supplierReturnVoid?:FoodSupplierReturnVoid;returnCredit?:FoodReturnCredit;returnCreditVoid?:FoodReturnCreditVoid;definition?:FoodItem['definitionHistory'][number];legacy?:{countHistory?:FoodCount[];definitionHistory?:FoodItem['definitionHistory']}};
export type FoodHistoryPage={entries:{sequence:number;revision:number;at:string;actorId:string;event:FoodEvent;replacementReturned?:ExcessTotals;replacementReturnVoided?:FoodReplacementReturnVoid&{revision:number};receivingReplacements?:ExcessTotals;replacementVoided?:FoodReplacementVoid&{revision:number};excessBilled?:ExcessTotals;invoiceExtraBilling?:ExcessTotals;excessBillingVoided?:FoodExcessBillingVoid&{revision:number};voided?:FoodWasteVoid&{revision:number};wastePriceSourceVoided?:boolean;invoiceVoided?:FoodInvoiceVoid&{revision:number};invoicePriceApplied?:FoodInvoicePrice&{revision:number};invoiceCredits?:CreditTotals;invoiceClaim?:InvoiceClaim;claimLatest?:ClaimLatest;invoiceReceiving?:ReceivingTotals;invoiceExcess?:ExcessTotals;invoiceExcessReturns?:ExcessTotals;excessReturned?:ExcessTotals;excessReturnVoided?:FoodExcessReturnVoid&{revision:number};excessVoided?:FoodExcessVoid&{revision:number};receivingVoided?:FoodReceivingVoid&{revision:number};creditVoided?:FoodCreditVoid&{revision:number};receivingReturns?:ReceivingTotals;supplierReturnVoided?:FoodSupplierReturnVoid&{revision:number};returnMatched?:MatchTotals;creditMatched?:MatchTotals;returnCreditVoided?:FoodReturnCreditVoid&{revision:number}}[];next:number|null};
export type FoodResult={recordId?:string;revision?:number;foodRevision:number;added:number;existing:number};
