import { manages, type Member, type RecoveredStandard, type SourceQuestion, type StandardProvenance } from './types';
import { object, requireThat, text } from './validation';

// Server-owned source snapshots. Recovered documents are evidence, never runtime instructions.
const mapTitle='Bert’s FOH Close — Current Operating Map and Approved J Max Decisions';
const mapHash='5804A91DBBEBCC3E833E7E591A2126F1C41CD5BF2E7DCAFB3E6830F9A1E709D4';
const attribution='Walter/FOH working session with Jason Albert and Rudd Maxwell, recovered from Manus. This is a curated draft from the operating map and selectively inspected conversation, not a complete transcript or a current restaurant approval.';
const commonQuestions:SourceQuestion[]=[
  {id:'restaurant',prompt:'Confirm which parts of this Bert’s material apply at this restaurant. Describe any local differences and update the instructions to match.'},
  {id:'verification',prompt:'Confirm the station name, accountable closer and physical verification chain for this restaurant. Update the station and check settings if needed.'},
];
type Seed=Pick<RecoveredStandard,'id'|'title'|'zone'|'position'|'criteria'|'verification'|'guide'|'questions'> & {excerpt:string};
const seeds:Seed[]=[
  {id:'berts-foh-bathrooms',title:'Bathroom close',zone:'Bathrooms',position:'Server',verification:'senior-then-manager',
    excerpt:'Toilets clean; counters and mirrors clean; soap at least half full; two toilet-paper rolls per stall; active paper-towel roll replaced at about one-third; floors swept/mopped and free of dirt; faucets fully off with no drip.',
    criteria:['Toilets, counters and mirrors are clean.','Soap is at least half full; each stall has two toilet-paper rolls.','Paper-towel roll is replaced at about one-third remaining.','Floors are clean and faucets are fully off with no drip.'],
    guide:{purpose:'Leave the bathrooms clean and stocked for the next shift.',preparation:['Confirm that bathroom close is your assigned responsibility.'],steps:['Check the toilets, counters, mirrors and floors against the completion conditions.','Check soap, toilet paper and paper towels against the listed stocking levels.','Check that faucets are fully off and report any remaining drip.','Signal ready after the work is complete. The designated senior or lead checks first; the closing manager final-confirms.'],troubleshooting:['If a condition needs correction, complete the correction and request another physical check.'],escalation:'Tell the closing manager about missing supplies, a persistent drip or work you cannot finish.'},
    questions:[{id:'cleaning',prompt:'Add the approved bathroom cleaning method, products, equipment and any required precautions. The source lists results, not the cleaning procedure.'}]},
  {id:'berts-foh-server-station',title:'Server Station close',zone:'Server Station',position:'Server',verification:'senior-then-manager',
    excerpt:'Tea urns cleaned inside/out and drying; soda and tea nozzles soaking; coffee pot cleaned; filters washed/returned; ice bins filled; cups, soufflé cups, lids, sanitation buckets, and bagged silverware ready; trash removed; counters/floors clean; cups put away; no personal items left.',
    criteria:['Beverage equipment is cleaned and reset by its approved procedure.','Ice and service stock are ready to the approved opening quantities.','Trash is removed; counters and floors are clean; cups are put away.','No personal items remain in the station.'],
    guide:{purpose:'Have one accountable closer leave the complete Server Station ready for opening.',preparation:['Confirm the named Server Station closer and the designated senior or lead verifier.'],steps:['Complete the approved beverage-equipment cleaning and reset procedure.','Prepare ice, cups, soufflé cups, lids, sanitation buckets and bagged silverware to the approved opening quantities.','Remove trash, clean the counters and floors, put cups away and remove personal items.','Signal ready for the designated senior or lead’s physical check, followed by closing-manager confirmation.'],troubleshooting:['Completing a remaining station task does not make that server the verifier.','If staffing changes, the manager names the accountable closer while redistributing any help.'],escalation:'Bring missing stock, equipment questions or an unresolved correction to the closing manager.'},
    questions:[{id:'equipment',prompt:'Supply current approved procedures for tea urns, soda and tea nozzles, coffee equipment and filters. The historical soaking statement does not establish a product, method or duration.'},{id:'pars',prompt:'Specify current opening quantities for ice, cups, lids, soufflé cups, sanitation supplies and bagged silverware.'}]},
  {id:'berts-foh-salad-bar',title:'Final Salad Bar close',zone:'Salad Bar',position:'Server',verification:'manager',
    excerpt:'Product labeled/dated, filled, protected, and covered; crocks, top bar, glass, sneeze guard, storage/under-crock areas, crackers, and table clean; crumbs removed; condensation/leaks checked.',
    criteria:['Products meet the approved storage, labeling, dating, fill and cover requirements.','Crocks, top bar, glass, sneeze guard, storage areas and table are clean.','Cracker area is clean, crumbs removed and condensation or leaks checked.'],
    guide:{purpose:'Complete the final Salad Bar reset with a thorough closing-manager check.',preparation:['Confirm who owns final Salad Bar close; in-shift upkeep does not provide final approval.'],steps:['Use the approved product-specific storage, labeling, dating and cover procedure.','Reset the crocks, top bar, glass, sneeze guard, under-crock and storage areas, crackers and table.','Check for crumbs, condensation and leaks.','Signal ready for the closing manager’s physical PASS or FIX.'],troubleshooting:['Report leaks or conditions that remain unresolved after the reset.'],escalation:'Ask the closing manager about uncertain product handling or an unresolved equipment or sanitation condition.'},
    questions:[{id:'food-handling',prompt:'Add the current product-specific storage, labeling, dating, disposal and fill requirements. The recovered map does not specify these controls.'},{id:'cleaning',prompt:'Add the approved equipment and surface-cleaning procedures and the response to condensation or leaks.'}]},
  {id:'berts-foh-back-window',title:'Back Window close',zone:'Back Window',position:'Back Window',verification:'manager',
    excerpt:'Employee restroom cleaned; pizza boxes folded; backup dressings/condiments ready; window locked; table reset; area clean and swept/mopped. Cash drawer is separately manager-counted.',
    criteria:['Employee restroom is clean and service supplies meet approved opening quantities.','Pizza boxes are folded; backup dressings and condiments are ready.','Window is locked, table reset and area clean.'],
    guide:{purpose:'Leave Back Window ready for the next shift while retaining manager-owned drawer verification.',preparation:['Confirm your Back Window assignment and the responsible closing manager.'],steps:['Complete the employee-restroom cleaning and approved stock preparation.','Fold pizza boxes and prepare backup dressings and condiments to the approved quantities.','Reset the table, clean the area and check the physical window lock.','Signal ready for the closing manager’s walkthrough. The manager separately counts and verifies the drawer before operational release.'],troubleshooting:['The employee’s ready signal is not drawer approval. Cash variances belong in a restricted manager follow-up.'],escalation:'Tell the closing manager about a lock problem, missing stock or drawer discrepancy.'},
    questions:[{id:'methods-pars',prompt:'Supply the restroom cleaning procedure, box sizes and quantities, condiment quantities and approved food handling.'},{id:'drawer',prompt:'Confirm the current manager-owned drawer and release procedure. Keep cash amounts and sensitive details out of this shared guide.'}]},
  {id:'berts-foh-host-entry',title:'Host and entry close',zone:'Host / entry area',position:'Host',verification:'manager',
    excerpt:'Booster seats and high chairs clean; menus wiped; glass/front doors cleaned and wiped; weekend Back Room support complete when assigned.',
    criteria:['Assigned booster seats, high chairs and menus are clean.','Assigned glass and front-door cleaning is complete.','Back Room support is complete when assigned.'],
    guide:{purpose:'Complete the host and entry work with clear ownership among the hosts actually closing.',preparation:['Confirm how the closing manager has split the work among the hosts present.'],steps:['Complete your assigned booster-seat, high-chair and menu cleaning using the approved methods.','Complete the assigned glass and front-door cleaning.','Complete weekend Back Room support if assigned.','Signal ready for the closing manager to physically check your assigned work.'],troubleshooting:['Clarify an unassigned or overlapping piece with the closing manager.'],escalation:'Ask the closing manager about an unclear assignment, cleaning method or unfinished piece before release.'},
    questions:[{id:'methods-scope',prompt:'Supply approved cleaning methods and confirm when Back Room support belongs to hosts.'}]},
  {id:'berts-foh-back-room',title:'Server section and Back Room close',zone:'Server section / Back Room',position:'Server',verification:'senior-then-manager',
    excerpt:'Tables wiped/reset, floors swept/mopped, and area generally clean. Back Room is simply a separate party/overflow room, not a special checklist.',
    criteria:['Tables are clean and reset to the approved layout.','Floors and the assigned section are clean.'],
    guide:{purpose:'Reset the assigned section or Back Room without treating the overflow room as a separate kind of service station.',preparation:['Confirm your assigned section and the closing verification plan.'],steps:['Clean and reset the assigned tables to the approved layout.','Complete the assigned floor and section cleaning.','Signal ready for the planned physical checks. A second-out server’s remaining Server Station task does not grant verification authority.'],troubleshooting:['Ask the closing manager how any remaining Server Station work is assigned.'],escalation:'Bring unfinished work or a missing verifier to the closing manager.'},
    questions:[{id:'layout-methods',prompt:'Add the current table-reset layout and approved cleaning methods.'},{id:'senior-fallback',prompt:'The source says senior/lead first verification when available, then a final manager walk. Confirm which chain should apply here when no senior is available; select the appropriate check setting.'}]},
  {id:'berts-foh-first-out',title:'First-out Salad Bar Room side work',zone:'First-out Salad Bar Room',position:'Server',verification:'manager',
    excerpt:'Begins Salad Bar Room side work around the 8:00 p.m. hour while still serving. Cleans most tea urns, hot-fudge counter, salad-bar cooler, and salad-bar prep tables.',
    criteria:['Assigned tea-urn, hot-fudge-counter, cooler and prep-table side work is complete.','Hot fudge remains available and its later put-away responsibility is handed off.'],
    guide:{purpose:'Complete first-out side work around live guests while preserving the later close responsibilities.',preparation:['Confirm the manager’s timing and assigned first-out work while service continues.'],steps:['Complete the assigned tea-urn, hot-fudge-counter, salad-bar-cooler and prep-table work using approved methods.','Leave hot fudge available for service and hand its later put-away to the assigned closer.','Signal ready for a closing-manager physical check before operational release.'],troubleshooting:['Coordinate with the closing manager if the work conflicts with serving guests.'],escalation:'Tell the closing manager if timing, guest service or the later hot-fudge handoff is unclear.'},
    questions:[{id:'timing-methods',prompt:'Confirm current service-safe timing, equipment-cleaning methods and the later hot-fudge handoff. The historical approximate time and duration are not automatically a current target.'}]},
];

export const recoveredStandards:RecoveredStandard[]=/* @__PURE__ */ seeds.map(({excerpt,...seed})=>({...seed,revision:1,area:'FOH',restaurant:'Bert’s',sourceDate:'2026-08-28',attribution,source:`Bert’s FOH working session, August 28, 2026; ${mapTitle}. Recovered draft; local review required.`,references:[{title:mapTitle,section:'Normal FOH Close Sequence / Area Standards Already Defined',excerpt,sha256:mapHash}],questions:[...commonQuestions,...seed.questions]}));
export function recoveredFor(me:Member){return me.position==='Dishwasher'?[]:recoveredStandards.filter(s=>manages(me,s.area,'tasks.manage')||manages(me,s.area,'standards.approve'));}
export function readSourceAnswers(value:unknown,provenance:StandardProvenance):Record<string,string>{
  const v=object(value),allowed=new Set(provenance.questions.map(q=>q.id));
  requireThat(Object.keys(v).every(key=>allowed.has(key)),'A source review question changed. Reload the draft.');
  return Object.fromEntries(Object.entries(v).map(([key,value])=>[key,text(value,'Restaurant clarification',2000,true)]));
}
export function requireSourceReview(provenance:StandardProvenance|undefined){
  if(provenance)requireThat(provenance.questions.every(q=>provenance.answers[q.id]?.trim()),'Resolve every source question in this draft before approving it.');
}
