import type { StationGuide, SourceQuestion } from './types';

export const starterTaskRevision=3;
export const confirmedDutySource={date:'2026-10-07',title:'Owner-confirmed position walkthrough',url:'https://chatgpt.com/space/page_6abd2330b148819189fc5f9a79583020'};
export type ConfirmedDutyReference={id:string;role:string;area:'FOH'|'BOH';locationIds:readonly string[];opening:readonly string[];service:readonly string[];closing:readonly string[]};
// A source-backed reference, separate from the proposed starter drafts below.
// Reading this catalog does not approve, assign, or replace a saved standard.
export const confirmedDutyCatalog:readonly ConfirmedDutyReference[]=[
 {id:'server-shared',role:'Server',area:'FOH',locationIds:['berts','rudds'],
  opening:['Read the Companion section assignment and opening briefing.','Check the POS station, spot-sweep the section, clean seats and wipe tables; arrive with an apron and a welcoming smile.'],
  service:['Welcome guests warmly, introduce yourself and the specials, take drinks and suggest an appetizer; give guests time to respond.','Bring drinks, check readiness to order, take the order and repeat it back; enter it promptly.','Follow appetizer and entrée delivery, refill drinks and pre-bus throughout service; return after two bites to check the meal.','Offer dessert or coffee, present the check, thank guests and handle payment at the table using server banking.'],
  closing:['After the manager stops new seating, finish existing tables and assigned side work.','Bag silverware and complete section cleanup.','A manager, FOH manager or shift lead checks side work and settles the server bank before release.']},
 {id:'server-rudds-side-work',role:'Server — Rudd’s side work',area:'FOH',locationIds:['rudds'],opening:[],service:[],
  closing:['Clean bathrooms and the employee bathroom; roll up front rugs and put chairs up for sweeping and mopping.','Break down the soda station and take tea urns back.','Check table condiments and put Love seasoning away.','Rudd’s has no salad bar; do not copy Bert’s salad-bar work into this assignment.']},
 {id:'host-shared',role:'Host',area:'FOH',locationIds:['berts','rudds'],
  opening:['Check the server lineup, occupied tables and where guests are in their meals; have clean menus ready.'],
  service:['Use the written server rotation and a steady seating pace; ask the manager for direction when a server is overloaded.','Walk comfortably with guests and make brief, welcoming conversation.','Use the waiting sign when away seating guests; nearby staff welcome arrivals, and acknowledge them promptly on returning.'],
  closing:['Wipe menus, clean glass and windows, and clean high chairs and booster seats.','Help bag silverware when there is a backlog.']},
 {id:'busser-shared',role:'Busser — when staffed',area:'FOH',locationIds:['berts','rudds'],
  opening:['Check with the manager, have a tub and sanitation towel ready, and survey the dining room.'],
  service:['Float the dining room, clear released tables and help pre-bus.','Clean the tabletop and everything on it, wipe each seat, and push applicable chairs in before the table is ready.'],
  closing:['Finish assigned dish or trash work, pick up front of house, and spot-sweep entrances and exits.','Check with each server for remaining help, then ask the manager what needs finishing before leaving.']},
 {id:'runner-shared',role:'Food Runner',area:'FOH',locationIds:['berts','rudds'],
  opening:['Check what Expo needs, help restock and make sure the window is ready.'],
  service:['Politely announce the dish, let the guest identify it, and place it for them; a formal seat-number rollout was not chosen.','Bring missing or incorrect items to Expo’s attention and inform the server so the correction is followed through.'],
  closing:['Check with servers, Expo and the manager for remaining work before leaving.']},
 {id:'expo-berts',role:'Expo — Bert’s close',area:'FOH',locationIds:['berts'],opening:[],
  service:['Request a recook or remake for a cooking error; contact the FOH manager for an ordering error.'],
  closing:['Turn off the window heater and bread drawer; refrigerate dips and broccoli.','Clean the shelf, table, microwave and Expo screen.']},
 {id:'expo-rudds',role:'Expo — Rudd’s close',area:'FOH',locationIds:['rudds'],opening:[],
  service:['Request a recook or remake for a cooking error; contact the FOH manager for an ordering error.'],
  closing:['Put beer cheese, marinara and Alfredo away, restock paper products, turn heat lamps off and clean the area.']},
 {id:'back-window-berts',role:'Back Window',area:'FOH',locationIds:['berts'],
  opening:['Check the previous close and dressing-cup count, identify portioning needs and get equipment ready.'],
  service:['Receive orders from Expo, check contents while bagging, add required condiments, cups or kits, and attach the ticket.','Match the guest name to the ticket and confirm payment before handoff; communicate missing or incorrect items to Expo.','At changeover, pass along ready and pending orders; the manager closes the cash drawer.'],
  closing:['Turn off the pizza box; organize and clean the table, shelves and cooler.','Sweep underneath the table and steps, clean the window inside and out, and clean the employee restroom.']},
 {id:'pizza-make-close',role:'Pizza Make',area:'BOH',locationIds:['rudds','papa'],
  opening:['Have clean utensils, garnish bottles, shakers, boxes and service trays or platters ready.'],
  service:['Adjust stretching, saucing, cheese and topping to the order flow; teamwork does not require a fixed handoff.'],
  closing:['Break down and clean the pizza table.','Whoever remains on pizza usually turns the oven off and handles the crumb tray; Expo or the manager can help with late pizzas.']},
 {id:'catch-rudds',role:'Pizza Catch — Rudd’s assigned area',area:'BOH',locationIds:['rudds'],opening:[],service:[],
  closing:['Sweep and mop the walk-in cooler, freezer and back hallway.']},
 {id:'oven-berts',role:'Oven / Pizza Make / Catch',area:'BOH',locationIds:['berts'],
  opening:['Have clean utensils, garnish bottles, shakers, boxes and service trays or platters ready.'],
  service:['Assemble and bake pizza, breadsticks, dinner rolls, Reubens, chicken bacon ranch subs and potato skins.','Sandwich/Pasta assembles and loads baked spaghetti; Oven pulls it out, plates it and sends it to Expo.'],
  closing:['Turn off the oven and clean the crumb tray; wipe tables and break down the pizza table.','Check dates and clean underneath, send pans to Dish, and put away or discard butter as appropriate.','Clean the large mixing-bowl area and outside smoking area; leave the station ready for opening.']},
 {id:'counter-papa',role:'Counter',area:'FOH',locationIds:['papa'],
  opening:['Fill the hot box with water, assemble the soda machine, check dressing cups and prepare needed portions.','Put chairs down, polish glass and front doors, obtain cash and count drawers, and turn music on.'],
  service:['Share counter duties, prioritize the guest in front of you and politely ask phone guests to wait when needed; keep upselling.','Bring hot and cold food together, match the ticket and confirm payment; offer the Parmesan and red-pepper-flake bag.'],
  closing:['Detail bathrooms; sweep and mop the dining room, foyer and behind the counter; wipe counters and prep counters.','Clear the seven outdoor tables and bring trash up front.','Count drawers and hand them to the GM; turn off both hot boxes and break down the soda machine.','Papa’s is a one-shift restaurant and has no salad bar.']},
 {id:'driver-papa',role:'Delivery Driver',area:'FOH',locationIds:['papa'],
  opening:['Stock pizza boxes, turn on Shipday and check the delivery car’s condition and fuel.'],
  service:['Check the complete order and use judgment about combining nearby deliveries; assignments appear in Shipday.','If delivery cannot be completed, try calling the guest, then contact the restaurant for direction. All orders are prepaid.'],
  closing:['Clean the delivery staging area, help front of house as needed, then give slips to the GM and collect the payout.']},
];
// Exact canonical IDs only. An unknown location must not inherit another store’s duties.
export function confirmedDutiesForLocation(locationId:string,areas:readonly string[]=['FOH','BOH']){
 return confirmedDutyCatalog.filter(item=>item.locationIds.includes(locationId)&&areas.includes(item.area));
}
export type StarterTaskPack={id:string;role:string;area:'FOH'|'BOH';opening:string[];service:string[];closing:string[];review:string};
// Supplemental drafts reconciled against Bert’s recovered role map. Detailed source guides
// already cover Host, Back Window, Salad Bar, station-owned prep, Kitchen Manager,
// Grill, Fry, Sandwich and Pizza/Oven. Do not preload redundant general copies.
// Template IDs remain stable when a displayed title is corrected.
// No temperatures, chemical recipes, equipment shutdowns, pars or legal rules are inferred.
export const starterTaskPacks:StarterTaskPack[]=[
 {id:'server',role:'Server',area:'FOH',opening:['Check your assigned section and the shift briefing.','Check tables, menus, service supplies and your assigned station.','Ask about unavailable items and changes before taking orders.'],service:['Confirm order details and route allergy questions to the designated manager or kitchen lead.','Check on guests and communicate delays or missing items.','Keep the section orderly and restock assigned supplies as service permits.'],closing:['Finish guest responsibilities and your named closing assignment; bussing help does not transfer section accountability.','Report shortages, unfinished work and equipment concerns to the closing manager.','Request the assigned physical closing check and manager release; a completion click does not release you.'],review:'Confirm section duties, side-work ownership, service standards and the actual closing check. Keep separate named Server Station and bathroom procedures intact.'},
 {id:'busser',role:'Busser',area:'FOH',opening:['Confirm assigned dining areas and who to check with.','Gather the approved table-reset supplies.','Check that walkways and service collection points are ready.'],service:['Clear and reset released tables using the approved method.','Communicate table readiness to the host or server.','Report spills, broken items and blocked walkways promptly.'],closing:['Complete your assigned table and dining-area reset; the named server retains the section close.','Return supplies and move collected items to the designated area.','Tell the named area owner and closing manager about unfinished work and request the assigned review.'],review:'Confirm who releases a table, the approved cleaning products/method, reset layout, and which areas belong to bussers versus servers.'},
 {id:'expo',role:'Expo',area:'FOH',opening:['Confirm your Expo assignment, the kitchen lead and the separate Food Runner handoff.','Check the pass, ticket information and required finishing supplies.','Confirm who resolves ticket, modifier and allergy questions.'],service:['Match completed items to the ticket and confirm required components.','Communicate missing items or timing problems before sending the order.','Release the checked order to the assigned Food Runner, server or Back Window; clarify the destination and outstanding items.'],closing:['Resolve or hand off open tickets with the lead.','Reset the pass and return service supplies.','Report shortages and unfinished closing work.'],review:'Expo bridges FOH and BOH; it is separate from Food Runner. Confirm who owns the pass, final ticket/quality checks and handoff. This guide grants no additional departmental or management access.'},
 {id:'food-runner',role:'Food Runner',area:'FOH',opening:['Confirm the delivery area and who releases completed orders at Expo.','Check service trays and assigned delivery supplies.','Review table identification and who handles guest or order questions.'],service:['Collect only the order released by the assigned Expo or kitchen contact and confirm its destination.','Deliver the identified order to the correct table or assigned handoff point.','Report missing items, delays or guest questions to the responsible server or lead; do not improvise substitutions.'],closing:['Hand off any delivery still in progress.','Return and clean assigned service equipment using the approved method.','Report unfinished work and request the assigned closing review.'],review:'Food Runner delivers released orders; Expo owns the reviewed pass checks. Confirm table identification, delivery method, escalation and exact side-work boundaries before approval.'},
 {id:'flat-top',role:'Flat Top Cook',area:'BOH',opening:['Confirm the Flat Top station boundary and assigned menu items.','Check approved setup, ingredients and tools.','Raise missing recipe or equipment instructions with the kitchen lead.'],service:['Follow tickets, recipes and approved doneness checks.','Coordinate order timing with adjacent stations and Expo.','Keep tools and ingredients organized under the approved procedure.'],closing:['Hand off remaining tickets and product.','Use the approved Flat Top cleaning and storage procedure.','Report issues and request the required closing check.'],review:'Flat Top is a Cook station assignment, not a new access tier. Its complete local module is still missing. Confirm current menu ownership versus Grill and Sandwich; do not assign burgers from historical Grill lists. Supply product specifications, cleaning and shutdown authority.'},
 {id:'pizza-make',role:'Pizza Make',area:'BOH',opening:['Review approved dough, sauce, topping and build specifications.','Check the make station and assigned stock quantities.','Confirm communication with the oven station.'],service:['Read size, crust, toppings and modifiers before assembling.','Build to the current approved recipe and portion specification.','Communicate the ticket and any exception to the oven operator.'],closing:['Store and identify remaining ingredients using the approved method.','Reset the make station and assigned supplies.','Record shortages and get the required closing review.'],review:'Pizza Make is a Cook station assignment. The canonical Pizza Make source is still missing; recover it or deliberately replace it with a reviewed current procedure. The older Pizza/Oven guide is not complete Pizza Make training. Confirm dough handling, build cards, pars and boundaries.'},
 {id:'floor-manager',role:'Dining Room Manager',area:'FOH',opening:['Review staffing, sections, expected guest demand and known service concerns.','Name the responsible people for the shift and closing areas.','Brief the team on changes and who can help.'],service:['Monitor guest flow and support the team.','Handle service concerns within the restaurant’s approved authority.','Record call-ins and arrange coverage as a separate schedule decision.'],closing:['Review outstanding guest, payment and closing issues.','Physically check assigned closing work; keep drawer verification and final Back Window and Salad Bar checks manager-owned.','Give the next shift a clear handoff with owners for unfinished items.'],review:'Reconcile this dining-room management routine with the authorized shift manager assignment. A job title does not grant access. Confirm seating decisions, service recovery, attendance permissions and closing checks; retain the named server, senior/lead and final manager responsibilities.'},
];

export function starterQuestions(pack:StarterTaskPack):SourceQuestion[]{return [
 {id:'local-fit',prompt:'Confirm the actual job name, department, station boundaries and which proposed tasks belong to this role here. Remove or change anything that does not apply.'},
 {id:'local-methods',prompt:pack.review},
 {id:'responsibility',prompt:'Name who teaches this work, who reviews the result, and what the employee should do when supplies, instructions or help are missing.'},
];}
export function starterGuide(pack:StarterTaskPack):StationGuide{return {purpose:`Follow a consistent ${pack.role} shift routine using the reviewed responsibilities for this restaurant.`,preparation:pack.opening,steps:[...pack.service.map(s=>'During service: '+s),...pack.closing.map(s=>'Before leaving: '+s)],troubleshooting:['If an instruction, supply or safe method is unclear, stop that task and ask the assigned manager. Record the missing information rather than guessing.'],escalation:'Ask the assigned shift manager for the current approved procedure and help with anything outside your training or authority.'};}
