export const capabilities = ['schedule.manage', 'schedule.publish', 'schedule.change', 'tasks.manage', 'operations.store', 'close.verify', 'close.confirm', 'standards.approve', 'orders.request', 'orders.review', 'people.manage', 'people.approve', 'operations.escalation', 'location.manage'] as const;
export type Capability = typeof capabilities[number];
export type Member = { id: string; locationId: string; name: string; area: string; position: string; capabilities: Capability[]; qualifications: string[]; scheduleOnly?:boolean; scheduleJobs?:string[] };
export type Location = { id: string; name: string; timezone: string; revision: number; weekStartsOn?:number };
export type History = { actorId: string; action: string; note: string; at: string }[];
export type AttendanceType = 'call-in'|'no-show'|'late'|'left-early'|'other';
export type AttendanceFacts = {contact:'unknown'|'phone'|'message'|'none';coverage:'unknown'|'confirmed'|'uncovered';emergency:'unknown'|'reported'|'not-reported'};
export type AttendanceReview = {at:string;actorId:string;actorName:string;note:string};
export type Attendance = {title:string;employeeName:string;shiftId:string;shiftRevision:number;shift:Pick<Shift,'start'|'end'|'position'>;type:AttendanceType;reportedAt:string;note:string;status:'recorded'|'voided';facts?:AttendanceFacts;review?:AttendanceReview|null;history:{actorId:string;actorName:string;at:string;action:'recorded'|'corrected'|'voided'|'reviewed'|'reopened';type:AttendanceType;reportedAt:string;note:string;changeReason:string;facts?:AttendanceFacts;review?:AttendanceReview|null}[]};
export type CopySource = { id:string; revision:number; sourceWeek:string; targetWeek:string };
export type Shift = { personId: string; start: string; end: string; position: string; stationId?:string; stationName?:string; published: boolean; cancelled: boolean; releasedAt?: string; history?: History; copiedFrom?:CopySource; importedFrom?:{id:string;sourceRow:number;meal:string;break:string} };
export type Leadership = { personId: string; area: string; start: string; end: string; active: boolean; note: string };
export type Availability = { startDate: string; endDate: string; days: number[]; excludedDates?: string[]; replacesId?: string; startMinute: number; endMinute: number; beforeMinutes: number; afterMinutes: number; title: string; kind: 'school' | 'unavailable'; status: 'pending' | 'approved' | 'declined' | 'superseded'; decision: string };
export type StationGuide = { purpose:string; preparation:string[]; steps:string[]; troubleshooting:string[]; escalation:string };
export type SourceQuestion = { id:string; prompt:string };
export type SourceReference = { title:string; section:string; excerpt:string; sha256:string };
export type SourceIntakeLink = {batchId:string;documentId:string;title:string;sha256:string;textSha256:string;capturedAt:string;sourceStatus:string;sourceOwner:string|null;lastApprovedDate:string|null;department:string;stations:string[];roles:string[];operationalUse:string[];relatedVersions:string[];duplicateIds:string[]};
export type StandardProvenance = { starter?:{templateId:string;catalogRevision:number}; intake?:SourceIntakeLink; review?:{ownerId:string;reviewedOn:string;evidence:string}; sourceId:string; sourceRevision:number; restaurant:string; sourceDate:string; attribution:string; references:SourceReference[]; questions:SourceQuestion[]; answers:Record<string,string>; importedBy:string; importedAt:string };
export type Standard = { title: string; zone: string; position: string; criteria: string[]; source: string; version: number; verification: 'manager' | 'senior-then-manager'; status: 'draft' | 'approved' | 'retired'; validationNote: string; history: History; guide?:StationGuide; supersedes?:{id:string;revision:number}; provenance?:StandardProvenance };
export type RecoveredStandard = Pick<Standard,'title'|'zone'|'position'|'criteria'|'source'|'verification'|'guide'> & { id:string; revision:number; area:string; restaurant:string; sourceDate:string; attribution:string; references:SourceReference[]; questions:SourceQuestion[] };
export type CloseAttention = {reason:'repeated'|'serious'|'unresolved';raisedBy:string;raisedAt:string;note:string;acknowledgment?:{by:string;at:string;note:string}};
export type Close = { shiftId: string; standardId: string; standardRevision: number; standard: Standard; verifierId?: string; managerId: string; due: string; answers?: number[]; attention?:CloseAttention; correction?:{personId:string;assignedBy:string;assignedAt:string;note:string}; phase: 'open' | 'correction' | 'verification' | 'manager-confirmation' | 'closed' | 'cancelled'; history: History };
export type ScheduleRequest = { type: 'time-off' | 'swap' | 'availability'; start: string; end: string; shiftId?: string; replacementId?: string; note: string; status: 'pending' | 'accepted-by-replacement' | 'approved' | 'declined'; decision?: string };
export type DishCheckout = {cycleId:string;shift:'AM'|'PM';participantIds:string[];businessDate:string};
export type DishHandoff = {sourceId:string;cycleId:string;businessDate:string;acceptedBy:string;acceptedAt:string|null};
export type Task = { title: string; detail: string; kind: 'task' | 'issue' | 'handoff'; phase: 'open' | 'correction' | 'verification' | 'acceptance' | 'closed'; incomingId?: string; shiftId?:string; closingHandoff?:{outgoingId:string;acceptedBy:string;acceptedAt:string}; due: string; history: History;dishCheckout?:DishCheckout;dishHandoff?:DishHandoff;dishHandoffs?:string[];dishHandoffAcceptances?:{handoffId:string;acceptedBy:string;acceptedAt:string}[];dishHandoffReceiptView?:boolean;dishHandoffPendingIds?:string[] };
export type Line = { name: string; quantity: number; unit: string; productId: string; note: string; food?:import('./food-workflow-model').FoodOrderLineSource };
export type Order = { lines: Line[]; note: string; status: 'draft' | 'review' | 'returned' | 'approved'; history: History; approvedRevision?: number; reviewerId?: string; food?:import('./food-workflow-model').FoodOrderSource; foodVersions?:{at:string;by:string;food:import('./food-workflow-model').FoodOrderSource;lines:Line[]}[] };
export type MessageContext = { recordId:string; revision:number; kind:'standard'|'close'; capturedAt:string; standardId:string; standardRevision:number; instruction:Pick<Standard,'title'|'zone'|'position'|'version'|'source'|'criteria'|'guide'|'verification'>; clarifications:{question:string;answer:string}[]; assignment?:{ownerId:string;due:string;phase:Close['phase'];helperId?:string} };
export type Message = { title: string; body: string; recipients: string[]; readBy: string[]; replies: { actorId: string; text: string; at: string }[]; recordId?:string; automated?:boolean; context?:MessageContext; contextStatus?:'current'|'changed'|'unavailable' };
export type Feedback = { text: string; shared: boolean; status: 'private' | 'submitted' | 'follow-up' | 'closed'; response: string; due: string; history: History };
export type OvernightHandoff = { title:string; detail:string; outgoingId:string; incomingId:string; outgoingLeadershipId:string; incomingLeadershipId:string; due:string; priority:'routine'|'urgent'; phase:'offered'|'disputed'|'accepted'|'resolved'|'cancelled'; history:History };
export type AssessmentStation = { name:string; definition:string; source:string; standardId?:string; standardRevision?:number; selfScore:number|null; selfRatingScale?:string; selfNote:string; managerScore:number|null; managerRatingScale?:string; managerNote:string };
export type AssessmentSubmission = { by:'employee'|'manager'; actorId:string; at:string; summary:string; ratings:{name:string;score:number;note:string;scale?:string}[] };
export type Development = { title:string; managerId:string; approverId:string; hireDate:string; originalDueDate:string; stations:AssessmentStation[]; phase:'self-assessment'|'manager-assessment'|'discussion'|'gm-review'|'approved'|'cancelled'; selfShared:boolean; managerShared:boolean; submissions:AssessmentSubmission[]; selfSummary:string; managerSummary:string; managerDiscussion:string; employeeDiscussion:string; approvalNote:string; history:History };
export type Goal = { automaticLearning?:boolean; practiceChecks?:number[]; title:string; definition:string; type:'development'|'required-correction'; managerId:string; due:string; standardId?:string; standardRevision?:number; standardSource?:string; stationLearning?:{stationId:string;stationName:string;templateId:string;shiftId:string}; phase:'proposed'|'active'|'declined'|'verification'|'closed'|'cancelled'; history:History };
export type CoverageDuty = {id:string;standardId:string;standardRevision:number;title:string;zone:string;criteria:string[];source:string;version:number;due:string};
export type Coverage = {title:string;shiftId:string;shiftRevision:number;position:string;start:string;end:string;duties:CoverageDuty[];note:string;status:'open'|'approved'|'withdrawn'|'invalidated';volunteers:{personId:string;at:string}[];selectedId?:string;history:History;unavailableReason?:string;eligible?:boolean};
export type Staffing = {title:string;position:string;start:string;end:string;minimum:number;source:string;status:'draft'|'approved'|'retired';history:History;copiedFrom?:CopySource};
export type StationLevel = {value:number;label:string;definition:string};
export type StationGoalTemplate={id:string;title:string;definition:string;dueDays:number;standardId?:string};
export type StationSetup={jobs:string[];memberIds:string[];allJobMembers?:boolean;standardIds:string[];managerId:string;goals:StationGoalTemplate[]};
export type Station = {title:string;levels:StationLevel[];independentLevel:number|null;definitionRevision?:number;setup?:StationSetup;issuedGoals?:{personId:string;templateId:string;goalId:string}[];status:'active'|'archived';history:History};
export type Proficiency = {title:string;stationId:string;stationRevision:number;position:string;level:number|null;certifiedTrainer:boolean;evidence:string;assessedAt:string;history:History};
export type DataMap = { learningcase:import('./operational-learning').OperationalLearningCase; achievement:import('./position-achievements').Achievement; opening:import('./hiring-openings').HiringOpening; catering:import('./catering').Catering; recognition:import('./recognition').Recognition; staffidea:import('./staff-ideas').StaffIdea; equipment:import('./equipment').Equipment; hirechecklist:import('./hire-checklist').HireChecklist; maintenance:import('./maintenance').Maintenance; servicecontact:import('./service-contacts').ServiceContact; promotion:import('./promotions').Promotion; hirehandoff:import('./hire-handoff').HireHandoff; guestreview:import('./guest-reviews').GuestReview; shiftcheckin:import('./shift-checkin').ShiftCheckin; compliance:import('./compliance').Compliance; incident:import('./incidents').Incident; fooditem:import('./food-model').FoodItem; foodrecipe:import('./food-model').FoodRecipe; managerlog:ManagerLog; meeting:Meeting; shiftentry:ShiftEntry; shift: Shift; request: ScheduleRequest; task: Task; order: Order; message: Message; feedback: Feedback; leadership: Leadership; availability: Availability; standard: Standard; close: Close; handoff:OvernightHandoff; development:Development; goal:Goal; coverage:Coverage; staffing:Staffing;station:Station;proficiency:Proficiency;attendance:Attendance };
export type ManagerLog = {contactAttempts?:import('./service-contacts').ContactAttempt[];title:string;detail:string;category:string;priority:'routine'|'urgent';due:string|null;status:'open'|'accepted'|'resolved';acceptedBy:string;resolution:string;history:History};
export type ShiftEntry = {title:string;businessDate:string;shift:'opening'|'closing'|'production';department:string;status:'draft'|'submitted';readiness:'not-assessed'|'ready'|'action-needed';summary:string;tomorrowNote:string;issueIds:string[];submittedAt:string;history:History;versions:{at:string;by:string;summary:string;tomorrowNote:string;readiness:string;issueIds:string[]}[]};
export type Meeting = {title:string;managerId:string;cadenceDays:number;due:string;agenda:string;status:'active'|'paused';actions:{id:string;title:string;ownerId:string;due:string;doneAt:string}[];sessions:{at:string;by:string;notes:string;agenda:string}[];history:History};
export type Kind = keyof DataMap;
export type WorkRecord = { [K in Kind]: { id: string; locationId: string; ownerId: string; area: string; revision: number; updatedAt: string; kind: K; data: DataMap[K] } }[Kind];
export type RecordOf<K extends Kind> = Extract<WorkRecord, {kind: K}>;
export type Workspace = { hireCandidates?:import('./hire-handoff').HireCandidate[]; learningHistory?:{personId:string;standardId:string;standardRevision:number}[]; activeRecordCount?:number; location: Location; me: Member; members: Member[]; records: WorkRecord[]; formerMembers?:{id:string;name:string}[]; recoveredStandards?:RecoveredStandard[] };
export function personName(w:Workspace|null|undefined,id:string|undefined,fallback='Employee'){return w?.members.find(m=>m.id===id)?.name??w?.formerMembers?.find(m=>m.id===id)?.name??fallback;}
export type Command = { requestId: string; locationId: string; action: string; recordId?: string; expectedRevision?: number; input: Record<string, unknown> };
export type CommandResult = { recordId: string; revision: number; workspaceRevision: number };
export function has(member: Member, capability: Capability) { return member.capabilities.includes(capability); }
export function manages(member: Member, area: string, capability: Capability) { return has(member, capability) && (has(member, 'location.manage') || member.area === area); }

export function canDraftStandard(member:Member,area=member.area){return member.position!=='Dishwasher'&&(manages(member,area,'tasks.manage')||manages(member,area,'standards.approve'));}

// A scheduled job is staffing eligibility, not proof of station training.
export function canScheduleJob(m:Member,job:string){return m.qualifications.includes(job)||!!m.scheduleJobs?.includes(job);}
