'use client';
import { useEffect,useState } from 'react';
import '../team/workspace.css';
export default function EmployeeLogin({ownerSignIn}:{ownerSignIn:string}){
 const [code,setCode]=useState(''),[busy,setBusy]=useState(false),[available,setAvailable]=useState<boolean|null>(null),[error,setError]=useState(''),[person,setPerson]=useState<{name:string;position:string;restaurantName:string}|null>(null);
 useEffect(()=>{let alive=true;fetch('/api/employee-login',{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('Sign-in is temporarily unavailable.');return r.json() as Promise<{available:boolean}>}).then(v=>{if(alive)setAvailable(v.available)}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[]);
 const submit=async(action:'verify'|'logout')=>{if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/employee-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...(action==='verify'?{code}:{})})});const value=await r.json() as {error?:string;memberId:string;name:string;position:string;restaurantName:string};if(!r.ok)throw Error(value.error);setCode('');if(action==='verify'){const check=await fetch('/api/workspace',{cache:'no-store'});const workspace=await check.json() as {memberships?:{id:string}[]};if(!check.ok||!workspace.memberships?.some(m=>m.id===value.memberId))throw Error('Your code was accepted, but this browser did not retain the correct sign-in. Keep this browser open and ask your administrator for help.');setPerson(value)}else{setPerson(null);setError('Ask your manager for a code attached to your own name.')}}catch(e){setError(e instanceof Error?e.message:'Could not sign in. Please try again.')}finally{setBusy(false)}};
 const ownerLogin=async()=>{if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/employee-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});if(!r.ok)throw Error('Could not clear the previous sign-in. Try again.');window.location.assign(ownerSignIn)}catch(e){setError(e instanceof Error?e.message:'Could not start owner sign-in.');setBusy(false)}};
 return <div className="shared-ui"><div className="shared-shell"><header><a className="shared-brand" href="/login"><b>J</b> MAX <span>Companion</span></a></header><main><section className="shared-welcome employee-login">
 {person?<><p className="shared-kicker">Your account</p><h1>{person.name}</h1><p>{person.position} · {person.restaurantName}</p><p>Check that this is your name.</p><a className="shared-primary" href="/team?welcome=1">That’s me — open JMAX</a><button disabled={busy} onClick={()=>void submit('logout')}>That’s not me</button></>:<><h1>Sign in to JMAX</h1><p>Enter the setup code your manager gave you.</p><form onSubmit={e=>{e.preventDefault();void submit('verify')}}><label className="shared-field">12-digit setup code<input aria-label="12-digit setup code" type="text" inputMode="numeric" autoComplete="one-time-code" value={code} onInput={e=>setCode(e.currentTarget.value)} onChange={e=>setCode(e.target.value)} maxLength={32} placeholder="0000 0000 0000" required disabled={busy}/></label><button className="shared-primary" disabled={busy||available!==true||code.replace(/[\s-]/g,'').length!==12}>{busy?'Signing in…':'Continue'}</button></form><p>You’ll stay signed in on this phone for up to 30 days. If you need a new code, ask your manager.</p>{available===false&&<p>Your manager is finishing employee sign-in setup.</p>}<details><summary>Owner sign-in</summary><a href={ownerSignIn} target="_top" onClick={e=>{e.preventDefault();void ownerLogin()}}>Continue with ChatGPT</a></details></>}
 {error&&<p className="shared-error" role="alert">{error}</p>}
 </section></main></div></div>;
}
